mpv-player/mpv

video/out/gpu/video.c, video/out/gpu/video.h, video/out/vo_direct3d.c, video/out/vo_gpu.c, video/out/vo_xv.c
This adds `video-target-params` support for the remaining VOs which have video output parameters available.
=> vo_{gpu,direct3d,xv}: support `video-target-params`

DOCS/man/options.rst, video/out/w32_common.c
win32 does not respect `--native-keyrepeat` option, and native key repeat has been broken since https://github.com/mpv-player/mpv/commit/0ab3482f73a199b2e839ad4ec0a4b21adc1e75d5.
This lets mpv respect the `--native-keyrepeat` option on win32.
=> win32: fix native key repeat support

audio/out/ao_alsa.c
During AO init, snd_pcm_open() is called, which calls snd_config_update() to allocate a global config node and stores it in the snd_config global variable. This is never freed on uninit.
Fix this by freeing the global config node on uninit.
=> ao_alsa: fix snd_config memory leak

video/out/wayland_common.c
At least on some compositors, when the pointer enters a surface, only a wl_pointer_enter event is generated, but not wl_pointer_motion. This results in the initial mouse position being lost, which is especially problematic when input simulation is used.
Fix this by setting the mouse position on pointer enter event.
=> wayland_common: set mouse position on pointer enter

demux/demux.c
When a video-reconfig occurs with an image, the cache is not used because the code checks if the start time was initialized, but for images it stays at MP_NOPTS_VALUE. This make rotating large network images slow because they are re-downloaded on every rotation.
Fix this by allowing the use of image cache ranges whose times are uninitialized, but that span from the beginning to the end of the file (r->is_bof and r->is_eof are true) and are therefore still valid.
=> demux: use the cache for video-reconfigs of images

audio/out/ao_avfoundation.m, audio/out/ao_pipewire.c, audio/out/ao_wasapi.c, audio/out/ao_wasapi.h, audio/out/buffer.c, audio/out/internal.h
Currently `set_pause` is only used for push-based ao. This PR enables the use of it in pull-based ao.
The motivation is to avoid device buffer flushing when pull-based ao is paused. The original code path to pause and resume pull-based ao is to go through a `reset` and `start` cycle. In `reset`, the ao will flush its internal buffer. e.g., `pw_stream_flush` in pipewire, `IAudioClient_Reset` in wasapi, and `[renderer flush]` in avfoundation. If a large number of samples have been queued to device, flushing the device can cause desync when the ao is resumed.
This PR introduces the use of `set_pause` for pull-based ao. If it is not null, it will be called during pausing/resuming instead of a `reset` and `start` cycle. The ao can preserve its queued samples in this case.
=> ao: set_pause for pull-based ao

audio/decode/ad_spdif.c, ci/build-mingw64.sh
No idea how things previously worked without having these set, but apparently they did...
If this was a normal encoder to muxer case, we would utilize `avcodec_parameters_to_context`, but alas this is not.
Fixes: #13794
=> audio/ad_spdif: specify media type and sample rate in output codecpar

audio/out/ao_pipewire.c
Pipewire 0.3.50 has introduced `time.buffered` for the number of samples buffered in its resampler. It can be non-zero if the sink has a different samplerate. This commit takes it into consideration when calculating total delay.
This commit also includes `time.now` in calculation for more precise delay.
By the way, the buffer size is made proper for planar format. `SPA_PARAM_BUFFERS_size` should be the size of a single plane, not all planes.
=> ao_pipewire: proper delay calculation

DOCS/interface-changes/add-win32-context-menu.txt, DOCS/man/input.rst, DOCS/man/mpv.rst, meson.build, player/command.c, video/out/vo.h, video/out/w32_common.c, video/out/win32/menu.c, video/out/win32/menu.h
This is a draft implementation of #13677 for win32, from [mpv-menu-plugin](https://github.com/tsl0922/mpv-menu-plugin) .
I’m not sure if the code should live here, correct me if I’m wrong.
test.lua
```lua
local items = {
{title="foo", cmd="show-text 'foo'", shortcut="Ctrl+A"},
{type="separator"},
{title="hello"},
{type="separator"},
{title="dir", type="submenu", submenu={
{title="foo", cmd="#hello"},
{title="bar", cmd="show-text 'bar'"},
}},
{title="select", type="submenu", submenu={
{title="item 1", state={"checked"}, cmd="show-text 'item 1'", shortcut="Ctrl+1"},
{type="separator"},
{title="item 2", cmd="show-text 'item 2'", shortcut="Ctrl+2"},
{title="item 3", cmd="show-text 'item 3'"},
{type="separator"},
{title="item 4", state={"disabled"}, cmd="show-text 'item 4'"},
{title="item 5", …
```
=> vo: add win32 context menu support

DOCS/man/encode.rst, DOCS/man/input.rst, DOCS/man/mpv.rst, DOCS/man/options.rst, DOCS/man/vo.rst
This unifies flag option descriptions to use the same `--foobar=<yes|no>` format, which is more in line with the syntax of other option types.
=> DOCS/man: unify flag option descriptions, and minor fixes

video/out/vulkan/context.c, video/out/vulkan/context_display.c
This change is mostly motivated by missing
VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME instance extension when enumerating the devices. Which causes issues with MoltenVK which does not advertise full Vulkan conformance.
To avoid duplicating code use pl_vk_inst_create() which correctly query availability and enables the mentioned extension.
While at it fix the VkInstance leaking in vk_validate_dev().
=> vulkan: use pl_vk_inst_create

osdep/terminal-win.c
And skip unsupported private sequences, instead of printing them.
=> terminal-win: add more control codes support in non-VT mode

DOCS/interface-changes/vo-tct-buffering.txt, DOCS/man/vo.rst, misc/bstr.h, osdep/io.c, osdep/io.h, osdep/terminal-dummy.c, osdep/terminal-win.c, osdep/terminal.h, test/test_utils.c, video/out/vo_tct.c
This is multiple times faster than just writing every pixel sequence separately. Especially on slower terminal emulators. In general no need to stress I/O, while we can just prepare the frame to print and do it once.
=> vo_tct: write frame fully instead of every pixel

misc/bstr.h, video/out/vo_tct.c
Allows to avoid non-portable strlen usage. Also avoid "initializer element is not constant" warnings on older GCC that doesn't like explicit type specification in aggregate initialization.
=> bstr: change bstr0_s to bstr0_lit, restrict it only for string literals

video/out/vo_dmabuf_wayland.c
This commit was originally sparked by a change in sway. When looking at the wording of the spec, it was believed that the rotation should be counter-clockwise. But that was interpreted incorrectly. The rotation direction in the spec is meant for compositors not clients. Clients should be rotating clockwise and compositors rotate it the opposite direction. Also see the discussion in upstream wayland*.
*: https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/369
This reverts commit 27ef1725e7724f4b6899e3992ac3a884db9fbe13.
CC @mahkoh
=> Revert "vo_dmabuf_wayland: assume counter-clockwise rotations"

player/lua.c
Previously it always inserts a whitespace after an arg because `i > 0` is always true.
=> player/lua: fix trailing whitespace for mp.log output

video/out/mac/window.swift
this will prevent jumping of the window size in the case the window size was 'externally' modified and not via the window-scale property, when using the pinch gesture.
Fixes #11594
Fixes #13799
=> mac/window: fix window pinch gesture and modify current-window-scale

DOCS/man/mpv.rst, player/command.c
When converting a list to string for show-text, since 05c398fb6c3a48c6a72b6b0706ea0156c46b146d the OSD_ASS_0 escape hatch is used. This usage is problematic because the same format string is used for print-text, which results in these ASS escape sequences being printed in the terminal.
Also since d6610a5b2f34e398e2ceba2a4da2b79e556b1c9e, the print-text output to console.lua is no longer escaped if OSD_ASS_0 is present. This results in abnormally formated text in the console output.
Fix this by not using ASS escape sequences for this. Instead, use the circle symbols used by the OSC, which also results in the same width for active and inactive items.
=> command: don't use OSD_ASS_0 when converting lists to strings

audio/filter/af_scaletempo2_internals.c
This is an attempt to fix #8705 and is the result to my ideas [commented](https://github.com/mpv-player/mpv/pull/13737#issuecommnt-2013445939) on #13737.
The idea here is to increase the weight of louder channels. Some details are in the commit message. Should have very little effect on stereo audio and none on mono.
I tested it with the [sample](https://github.com/mpv-player/mpv/issues/8705#issuecomment-2000666720) from the issue, with the [test file](https://github.com/mpv-player/mpv/pull/13737#issuecomment-2014064370) in the discussion, and in random other videos I've watched and my impression is pretty good so far.
=> af_scaletempo2: prioritize louder channels for similarity measure

common/msg.c
Noticed while looking at this code, we shouldn't append status line to partial when !print_term.
=> msg: don't keep status line in partial

video/out/wayland_common.c, video/out/wayland_common.h
If mpv is coming out of some locked size state (fullscreen, maximized, tiled), the window size given by the reconfigure event should be used assuming the --auto-window-size option is set.
Fixes 8a9749b8a563f258342450160c98e9c02ebedc96
@na-na-hi: I'm not sure what specific example you had in mind with that commit but does this affect that? I made this change about as conservative as possible.
=> wayland: enforce a state change after a reconfigure

video/out/vo_gpu_next.c
Turns out libplacebo rotate target crop in relation to source. We want viewing size.
Fixes: a9354b36ca
=> vo_gpu_next: unrotate target crop

demux/demux_mkv.c
Draft PR to address https://github.com/mpv-player/mpv/issues/13830. The direction is being discussed in the issue.
Edit: see ietf-wg-cellar/matroska-specification#822.
=> demux_mkv: corrected direction of ProjectionPoseRoll rotation

video/out/wayland_common.c, video/out/wayland_common.h
See commit message for full details.
This unfortunately has a really bizarre bug on specifically sway 1.9 (sway master works well), so this will have to be a draft for that reason alone. Try to move a window to another monitor with a different scale value using the hotkey shortcuts and only the border appears to move and not the actual mpv buffer. No idea how the code changes here could cause that.
=> wayland: only perform a rescale if window is on one output

TOOLS/osxbundle.py
Fixes #13872
also removed an unused import, didn't feel like this warrants a separate commit.
=> osxbundle: use arg list instead of a string for signing subprocess call

video/out/wayland_common.c
Fixes: 895f40e150d4 ("wayland: only perform a rescale if window is on one output")
Fixes #13887
=> wayland: fix segfault in surface_handle_enter due to memory read

player/core.h, player/playloop.c, player/sub.c
If the player is paused, switching subtitle track requires us to read subs packets for an indefinite amount of time in order to actually display the subtitles. The problem with this is that it puts a blocking loop in the play thread which can be slow in cases where it takes a long time to fetch the subtitle (e.g. over a network).
9e27b1f523071db184443d78f7144cb599dd0829 alleviates this when a pause happens because of buffering, but it's not complete. One could encounter this if the user pauses the video first manually and then switches the subtitle track.
To solve this better, make it so the loop has a time out (100 ms, totally arbitrary) so the player isn't blocked forever. If subtitles are not fetched within that time, we flag the track and try again later in the playloop.
=> player: avoid busy looping during reinit_sub

player/misc.c
`--stop-playback-on-init-failure=no` is documented to continue playback in audio-only mode if video init fails. However, this does not function properly after a0804329927904fdeb70d9712ff23baaab161bb4: because video is initialized first, if video init fails, `ao_chain` is still null. As a result, `!(mpctx->vo_chain || mpctx->ao_chain)` is true, a playback error is raised, so the playback ends and audio does not play.
Fix this by reverting that change, so it checks the tracks instead.
Fixes: a0804329927904fdeb70d9712ff23baaab161bb4
=> player/misc: fix audio-only fallback when video init fails

audio/out/ao_coreaudio.c
=> Revert "ao_coreaudio: switch to ao_read_data_nonblocking()"

input/input.c, sub/dec_sub.c
This restructures code by establishing a call hierarchy between public and private functions, so that any lock is called no more than necessary and recursive locks are no longer necessary for `input.c` and `dec_sub.c`, which means they no longer need recursive mutex. All uses of recursive mutex are now removed except `vdpau.c`, where we call a function outside of our control inside a lock.
See also: https://github.com/mpv-player/mpv/pull/9727#issuecomment-1018343800
=> input, dec_sub: avoid unnecessary recursive locks and don't use recursive mutex

DOCS/man/stats.rst, player/lua/stats.lua
Avoid having to configure both the OSD and the stats script opts when you change the OSD options, in particular avoid having to convert colors to BGR.
Also document the shadow options.
font_size, border_size and shadow offset defaults are kept because the same values look much bigger in the stats than in the corresponding OSD options.
osd-back-color is now respected without extra checks until you explicitly set a shadow_color.
IMHO `font`, `font_color`, `border_color` and `shadow_color` could just be removed since I don't see why you would want them to be the different from the rest of the OSD.
=> stats.lua: inherit OSD styles

DOCS/man/options.rst, options/options.c, options/options.h, sub/sd_ass.c
Enable ASS_FEATURE_INCOMPATIBLE_EXTENSIONS and auto base detection
by default, and add an option to disable this if needed.
This currently means auto base direction, changing how bidi runs are
split, bidi bracket matching, and unicode soft line wrapping.
This is strictly an improvement for Webvtt files as they always use
auto base detection. This _fixes_ right-to-left text rendering for
webvtt files which correctly mark rtl/ltr. Webvtt files obtained from
sources which sideload the RTL information through css also see an
improvement due to the auto detection.
Generally SRT files also want this, but some are also written to
workaround VSFilter quirks.
=>  sd_ass: add `sub-vsfilter-bidi-compat` to enable vsfilter bidi compat 

osdep/terminal-unix.c, osdep/terminal-win.c, osdep/terminal.h, video/out/vo_kitty.c, video/out/vo_sixel.c, video/out/vo_tct.c
This adds mouse input parsing and enables mouse support for terminal VOs (`vo_tct`, `vo_sixel`, `vo_kitty`), making it possible to use mouse key bindings and OSC with these VOs.
=> terminal: support mouse input

DOCS/man/stats.rst, player/lua/stats.lua
This lets you press / in page 4 of the stats and type a keybinding or part of its command to filter it by using mp.input.
This works badly without a VO because both stats.lua and console.lua use show-text and only one can be displayed at a time, but it's still better than not having the search available at all.
=> stats.lua: filter input bindings by typing them

DOCS/man/mpv.rst, DOCS/man/options.rst, options/m_option.c, player/command.c, video/out/d3d11/context.c, video/out/gpu/context.c, video/out/gpu/context.h, video/out/opengl/context_android.c, video/out/opengl/context_angle.c, video/out/opengl/context_drm_egl.c, video/out/opengl/context_dxinterop.c, video/out/opengl/context_glx.c, video/out/opengl/context_wayland.c, video/out/opengl/context_win.c, video/out/opengl/context_x11egl.c, video/out/vulkan/context_android.c, video/out/vulkan/context_display.c, video/out/vulkan/context_mac.m, video/out/vulkan/context_wayland.c, video/out/vulkan/context_win.c, video/out/vulkan/context_xlib.c, video/out/wldmabuf/context_wldmabuf.c
Since the list of available GPU contexts is a compile time constant, use `obj_settings_list` instead of `opt_string_validate` for GPU contexts. This has several advantages:
- Aligns with the existing usage of vo, ao, and filter lists.
- Allows custom probing order.
- Allows list option suffixes. (`--gpu-context-append`, etc.)
- Allows autocomplete in `console.lua`.
- Uses the standard `obj_settings_list` help printing, so detailed descriptions of the contexts are printed and the custom help printing function is no longer needed.
=> video/out/gpu/context: convert `--gpu-context` to use `obj_settings_list`

demux/demux_lavf.c
Fixes #13431, fixes #13192. See the comment for details.
=> demux_lavf: pass jpg filenames to ffmpeg for probing

DOCS/man/stats.rst, player/lua/stats.lua
This adds two new options to `stats.lua`:
- `plot_bg_border_width` to control the border width of graphs
- `vidscale` to allow contents staying at constant size instead of being scaled with video, similar to the `vidscale` option for the OSC.
=> stats.lua: add graph border width and vidscale options

DOCS/interface-changes/wasapi-exclusive-buffer.txt, DOCS/man/ao.rst, audio/out/ao_wasapi.c, audio/out/ao_wasapi.h, audio/out/ao_wasapi_utils.c
This allows users to set buffer duration in exclusive mode. We have been using the default device period as the buffer size and it is robust enough in most cases. However, on some devices there are horrible glitches after a stream reset. Unfortunately, the issue is not consistently reproducible, but using a smaller buffer size (e.g., the minimum device period) seems to resolve the problem.
For shared mode, MS is actually requiring us to set both buffer duration and device period to 0 on initialization, whereas we are passing a non-zero duration. It works somehow, and has been working well thus far, so I decided to leave it for the time being.
=> ao_wasapi: add `--wasapi-exclusive-buffer` option

demux/demux.c
After transcoding an mp3 file with an embedded cue sheet to opus, I discovered, that mpv only reads the "CUESHEET" tag from format-level metadata. With this PR, `demux_init_cuesheet` also reads a stream-level "CUESHEET" tag, if the former read fails.
I have zero familiarity with the mpv code base, and while this works, someone should verify, that reading from field `.metadata_stream` in `struct demux_internal` is the correct fix.
------------
Read embedded cue sheets from stream-level metadata, in addition to
format-level metadata.
Fixes missing chapters in opus files with "CUESHEET" tags.
=> demux: also read "CUESHEET" tag from stream metadata

meson.build, video/out/d3d11/ra_d3d11.c, video/out/gpu/d3d11_helpers.c, video/out/gpu/d3d11_helpers.h
DXGI debug interface encapsulate multiple message queues, which allows
to get validation not only for D3D11 calls, but also DXGI ones.
Also this makes leak detector not report self debug interface as alive
like it was before. And same as with validation, it has ability to
detect more alive objects, not being limited to D3D11.
It works with latest version of mingw-w64. I tested in MSYS env, only DXGI_DEBUG_D3D11 is missing, but it was easy to define ourselves. Needs this commit for the rest https://github.com/mingw-w64/mingw-w64/commit/7b860f89460c0984f46812ec4475eb58b647595b
As probably we want to keep compatibility with older version I sent this patch only for reference and maybe for the future.
We could disable debug interface, if they are not supported, though, not sure who is using …
=> d3d11: use IDXGIInfoQueue instead ID3D11InfoQueue

audio/out/ao_coreaudio.c
This reverts commit 0341a6f1d39801160322d3fe16245f8387735f4b.
Fixes #13348.
We've discussed it in #13902.
=> Revert "ao_coreaudio: signal buffer underruns"

audio/out/ao_coreaudio_chmap.c, audio/out/ao_coreaudio_chmap.h, audio/out/ao_coreaudio_properties.h, audio/out/ao_coreaudio_utils.c, audio/out/ao_coreaudio_utils.h, meson.build
Looks like https://github.com/mpv-player/mpv/pull/11955/ broke iOS audiounit builds.
Related issue: https://github.com/mpv-player/mpv/issues/13921
ao_coreaudio_properties.c includes coreaudio specific types that are not available on iOS. Also, in some headers - just having audiounit enabled shouldn't assume that coreaudio types are available.
=> ao: fix ios audiounit build

DOCS/man/console.rst, DOCS/man/osc.rst, DOCS/man/stats.rst
Currently they refer to the OSC documentation. However, the "mp.options functions" already documents that, is more detailed, and does not contain false statements like "there may be no spaces around the ``=`` or anywhere else" (the primitive parser does not care about them, so starting a string option value with spaces is perfectly fine).
Change them to refer to "mp.options functions" and remove the redundant section in the OSC documentation.
=> DOCS/man: refer to "mp.options functions" for script config docs

test/libmpv_test.c
Among others this provides a trivial test that built-in scripts aren't throwing an error at load or init time.
(if someone e.g. introduces a syntax error in `osc.lua`)
=> test: make libmpv_test abort if an error is logged

DOCS/man/input.rst, osdep/mac/swift_extensions.swift, video/out/mac/common.swift
the Screen property localizedName returns a none unique dynamic name that doesn't allow a specific selection of a Screen on every OS boot. the name consists of the vendor name and model name (eg DELL U2723QE). if the same model display is connected to the system several times, macOS starts to add numbers to the localizedName (eg DELL U2723QE (1)), that may not be associated to the same Screen on every OS boot or connecting the display. it also changes the name of the first connected display by adding that numeration. this makes it impossible specify the proper screen with the screen-name option every time.
to circumvent this we remove the enumeration from the name and instead add the serial number to the display-names property. this makes the actual Screen unique and none dynamic. …
=> mac: make display-names unique to allow specific selection

osdep/mac/input_helper.swift
tilde and accents weren't reported on macOS. for example the default console key binding didn't work.
=> mac/input: add support for dead key reporting

options/m_config_core.c
bc28f7693d095758275448410aaa91255482857a originally added this, but the implementation isn't correct and causes excessive notifications when writing to other options which may have bad behavior in some some circumstances. Fix this by reworking the implementation for force options so that the timestamps of the option update compared instead. Whenever an option gets changed, the internal timestamp in the cache is always incremented. For a special force option, we can save this timestamp internally as well.
Because cache_check_update is always checked before potentially sending an option notification, we know that if the internal timestamp is equal to the timestamp saved by a force update option, it must have been previously written. Thus, the notification can be sent. This lets options like …
=> m_config_core: fix forced option notification with m_config_cache

audio/out/ao_wasapi.c, audio/out/ao_wasapi.h
https://github.com/mpv-player/mpv/commit/6863eefc3d1d683a08f56aeaca0b4706672f2447 handled this situation by using an atomic variable to express the state for which the wakeup is caused by AO control, and the dispatch queue is only processed at this state. However, this can cause permanent lockup of the player core when the following happens:
- AO control sets the thread state to `WASAPI_THREAD_DISPATCH`, and sets the wakeup handle.
- WASAPI thread reads the `WASAPI_THREAD_DISPATCH` state and processes the dispatch queue.
- Another AO control happens. A dispatch item is enqueued, and the state stays at `WASAPI_THREAD_DISPATCH`.
- WASAPI thread resets the thread state to `WASAPI_THREAD_FEED` since the state has not changed.
- `WaitForSingleObject()` returns in the WASAPI thread, sees this …
=> ao_wasapi: fix player core lockup when avoiding premature buffer fills

audio/filter/af_scaletempo2.c, audio/filter/af_scaletempo2_internals.c, audio/filter/af_scaletempo2_internals.h
Fixes corrupted audio after resize_input_buffer; realloc_2d did not move data to new location. Detailed description in #13969.
This makes #13969 obsolete. Rather than reimplementing more allocator logic, migrate internals to talloc.
=> af_scaletempo2: migrate to talloc

player/lua/stats.lua
This change displays the scaled position and size of the image before cropping to the target rectangle. In simple terms, it shows how much margin has been added to the image or how much of the image has been cropped.
Note that target resolution is displayed after crop as in fact all other pixels are discarded anyway.
=> stats.lua: show osd-dimensions property

DOCS/interface-changes/sub-text-ass-full.txt, DOCS/interface-changes/sub-text-ass.txt, DOCS/man/input.rst, player/command.c, sub/dec_sub.h, sub/filter_jsre.c, sub/filter_regex.c, sub/sd.h, sub/sd_ass.c
This is like `sub-text-ass`, but it returns a full ASS line, making it suitable for some more advanced scripting use-cases.
=> player/command: add sub-text-ass-full property

.github/workflows/build.yml, fuzzers/common.h, fuzzers/fuzzer_loadfile.c, fuzzers/fuzzer_loadfile_direct.c, fuzzers/fuzzer_set_property.c, fuzzers/meson.build, meson.build, meson_options.txt
fuzzer_set_property.c:
fuzz mpv_set_property in both initialized and non-initialized state. Useful for user provided values sanitization test. I've already seen some memory leaks in parsing code, good to drill it.
fuzzer_loadfile.c:
mpv_command "loadfile" test. Good for testing demuxers, decoding and playback loop. Sadly in headless mode we can't really test AO and VO, but at least all the code around can be fuzzed. Especially our custom demuxers like demux_mkv.
fuzzer_loadfile_direct.c:
Similar to loadfile above, but instead of saving the data to file, it passes the fuzz intput in the command. Generated protocol specific versions (mf:// and memory:// for now) and generic one.
Nothing really complex, but good start and even those few targets should give good coverage of the most common …
=> fuzzers: add new fuzzer targets

etc/_mpv.zsh
This is made by possible by 96e1f1dfa5 standardizing --gpu-context's help output. This changes the check to complete any Object settings list so it will automatically work with future options of this kind.
=> zsh-completion: complete --gpu-context

TOOLS/lua/autoload.lua
Why? Sometimes you want to ignore thumbnails, auto-generated backups or just unwanted files. And here is a non-exhaustive list of real-world examples:
- user backup files: `%.bak%.mp4$` or `^bak-`;
- telegram-desktop chat export thumbnails: `_thumb%.jpg$`;
- a krita graphics editor backup suffix: `^~`
But it's an RFC because... there is little point in a single pattern. It would be better if we could configure a list of patterns. But... Should we just split by commas or write a custom parser for `ignore_pattern` that allows to escape commas? Maybe something else?
=> [RFC] TOOLS/lua/autoload: add ignore_patterns option

demux/demux_lavf.c, demux/demux_mkv.c
This allows to demux Versatile Video Codec with Matroska container to play, but MKV tag is V_QUICKTIME.
Feel free to reply or ask question to me. Thank you! :)
Sincerely,
- Martin Eesmaa
=> demux_mkv: support VVC matroska demux

video/out/wayland_common.c
This is done for the other protocol interfaces already but was accidentally omitted.
=> wayland: log if cursor shape support is missing

sub/sd_lavc.c
If sub decoder does not exist, priv remains NULL.
Fixes: 1394e5a111d7917674d1c05e03aec3ebd9c27312
=> sd_lavc: fix null dereference on error

DOCS/interface-changes/input-touch-emulate-mouse.txt, DOCS/interface-changes/native-touch.txt, DOCS/interface-changes/touch-pos.txt, DOCS/man/input.rst, DOCS/man/options.rst, input/input.c, input/input.h, input/keycodes.h, options/options.c, options/options.h, player/command.c, video/out/w32_common.c, video/out/wayland_common.c
Currently, mpv's input system has no real touch handling. Touch messages are either not requested, or very awkwardly translated to emulated mouse, which results in some bugs on Wayland and severely limits mpv's gesture recognition ability. 
This adds multi-touch support to mpv, in the form of added `touch-pos` property, and implements the support for Win32 and Wayland. The property contains the positions of all current touch points, each corresponds to a finger on the touch surface. Scripts can implement custom gesture recognition algorithms to process these values and determine the appropriate action to perform. 
For compatibility, `--input-touch-emulate-mouse` and `--native-touch` options are added to control whether touch events need to be emulated as mouse events. 
The following …
=> add multi-touch support

video/out/wayland_common.c
If we get either preferred_scale or preferred_buffer_scale this early during initialization the wl->scaling value should be immediately updated instead of being deferred until later for correct geometry. Fixes #14019.
=> wayland: set wl->scaling if there is no wl->current_output yet

video/out/w32_common.c, video/out/win32/menu.c, video/out/win32/menu.h
This makes the context menu items accessible from the window menu, which can be opened by either right-clicking on the title bar or left-clicking on the mpv icon on the title bar.
=> win32: make context menu items accessible from the window menu

DOCS/man/osc.rst, player/lua/osc.lua
There's no reason for it to not be a thing.
=> OSC: implemented user configurable colors

filters/f_decoder_wrapper.c
It is not longer valid and may cause use-after-free if used after decoder itself is destroyed.
Fixes: #14051
=> f_decoder_wrapper: clear decoder info on deinit

demux/demux_mkv.c
This allows playing files with any fourcc that is supported by mpv.
=> demux_mkv: make V_QUICKTIME codec detection generic

ci/lint-commit-msg.py
No reason to use short hash in script internally.
=> ci/lint: use long commit hash

sub/sd_ass.c
Users shouldn't have to care if subtitles' duration is unknown because the only difference is that decode() sets a duration to packets without one, if any.
The main difference was code intentionally breaking sub-seek, sub-step, sub-start and sub-end for unknown duration subtitles for some reason, but I removed it in 0f2370476b and 185fa9ffc6.
LRC subtitles always have unknown duration so if you use them having this logged on every song is annoying, so only log it in verbose mode.
=> sd_ass: don't log if subtitles have unknown duration

video/out/w32_common.c
WS_POPUP windows cannot be maximized, so instead of forcing it with unavoidable side-effects, change the window style before maximizing to make it work correctly.
=> win32: fix maximize state with --border=no

DOCS/man/input.rst, demux/demux.c, demux/demux.h, player/command.c, player/osd.c, player/playloop.c
this replaces https://github.com/mpv-player/mpv/pull/5789
the logic should be the same as before, but now ts stats are kept per stream type, and are available via the demuxer-cache-state property. for example:
>demuxer-cache-state: {cache-end=2.176000111110625, reader-pts=1.3120001111092279, cache-duration=0.864000000001397, eof=false, underrun=false, idle=false, total-bytes=1682448, fw-bytes=1287760, raw-input-rate=758321, debug-low-level-seeks=0, debug-byte-level-seeks=1, debug-ts-last=89903.50713322223, ts-per-stream=[{type=video, duration=2.018688888885663, reader=89903.5405, end=89905.55918888889}, {type=audio, duration=0.864000000001397, reader=89903.64051111111, end=89904.50451111111}], bof-cached=true, eof-cached=false, seekable-ranges=[{start=1.1111842468380928E-7, …
=> demux: keep track of ts information per stream type

demux/demux_mkv.c
If blocks were already demuxed we would skip them and ask for new ones. For files with few blocks it would return EOF without actually checking the content.
Also make demux limit higher. In practice it doesn't matter, because if it is image, video track will have only 1 block. And if it is not image it will break on 2nd video block.
Fixes: #13975
=> demux_mkv: fix image detection

filters/f_lavfi.c, filters/f_lavfi.h, filters/user_filters.c, options/m_option.h, player/command.c
This adds non-mpv filters to option-info/af/choices and option-info/vf/choices, which allows completing them with set af/vf \<Tab> in console.lua.
Partial fix of #13017. Getting the filter options would required adding af-list and vf-list properties.
=> command: return lavfi filters in option-info/[av]f/choices

DOCS/man/input.rst
sub-seek depends on cached range to know future subtitles, make it clear in documentation how to control this range.
=> docs: mention Cache section in sub-seek

DOCS/man/input.rst
Documents the functionality added by 155f7fa. Also make it clear than can you can seek with arbitrary <skip>s instead of just 1 and -1.
=> DOCS/input: document sub-seek 0

test/paths.c, test/scale_test.c
This is necessary to show the output with meson test. Followup to 06edb04692.
=> test: fflush between printf and abort

DOCS/man/options.rst, meson.build, meson_options.txt, osdep/mac/app_bridge.h, osdep/mac/app_bridge.m, osdep/mac/meson.build, video/out/cocoa_cb_common.swift, video/out/mac/common.swift, video/out/mac/gl_layer.swift, video/out/mac/view.swift
up to date version of #8485, with some added new colour spaces. also only for cocoa-cb since it's not necessary for the macvk vulkan backend or rather would break it.
this will most likely be the last new feature for the cocoa-cb/libmpv/opengl backend from me. just wanted to add this already done feature that was resting for years.
it might come in handy for future backends though.
Fixes #7341
=> cocoa-cb: add support for macOS color space transformation (EDR/HDR)

meson.build, misc/path_utils.c, player/configfiles.c, test/meson.build, test/paths.c
Paths like foo.mkv, ./foo.mkv .//foo.mkv, ../"$(basename "$PWD")"/foo.mkv, and C:\foo.mkv and C:/foo.mkv on Windows, use different config files for resuming playback, so if you quit-watch-later and later play the same file with a different path mpv does not resume playback. This commit normalizes the paths to fix this.
References https://github.com/mpv-player/mpv/pull/495
Someone needs to fix the code for Windows, and also test if the performance impact of calling `GetFullPathNameW` on thousands of playlist entries is acceptable. On Linux `realpath` is actually much slower than this normalizing function. The loop in `mp_check_playlist_resume` with 2330 images takes 0.012 seconds before this patch, 0.014 with it, and if I make it use `realpath` with `/dir/../dir/*` it takes 0.038 seconds.
=> player: normalize paths for resuming playback

DOCS/man/input.rst
It should be next to expand-text and expand-path, not under Input Commands that are Possibly Subject to Change.
=> DOCS/input: move escape-ass documentation

DOCS/man/input.rst
These need to coincide with the ones in command.c because they can be specified in mp.command_native.
=> DOCS/lua: fix some argument names

DOCS/interface-changes/normalize-path.txt, DOCS/man/input.rst, player/command.c
This can be used e.g. by a bookmarking script to show normalized paths.
=> command: add normalize-path command

common/encode_lavc.c, common/encode_lavc.h, common/msg.c, player/main.c
This change allows stdout to remain free for encoder output or similar tasks like vo=tct.
Before commit 4939570e17, all messages were printed to stdout, except status messages, which were printed to stderr. This approach was reasonable because one could redirect the stream to a file with messages or status output.
After commit 4939570e17, however, some messages started being printed to stderr, while others continued to be output to stdout. This inconsistency involved two output streams printing related messages.
After this change, messages are printed to stderr always, keeping stdout open for all other tasks.
This adjustment also fixes the issue of status messages being printed to both streams after commit 82451bdf04.
=> msg: print all messages to one stream

video/out/hwdec/hwdec_cuda.c, video/out/hwdec/hwdec_cuda.h, video/out/hwdec/hwdec_cuda_gl.c, video/out/hwdec/hwdec_cuda_vk.c
`cuInit` wakes up the nvidia dgpu on nvidia laptops. This is bad news because the wake up process
is blocking and takes a few seconds. It also needlessly increases power consumption.
Sometimes, a VO loads several hwdecs (like `dmabuf_wayland`). When `cuda` is loaded, it calls
`cuInit` before running all interop inits. However, the first checks in the interops do not
require cuda initialization, so we only need to call `cuInit` after those checks.
`cuInit` is handled by the new `cuda_priv_init` function. It ensures `cuInit` is only called once.
With these changes, there's no cuda initialization if no OpenGL/Vulkan backend is available. This prevents
`dmabuf_wayland` and other VOs which automatically load cuda from waking up the nvidia dgpu unnecessarily,
making them start faster and …
=> Avoid gpu wakeup in hwdec_cuda by deferring cuInit

meson.build, stream/stream_file.c
```
dd if=/dev/zero of=/tmp/10g.empty bs=1 seek=10G count=0
dd if=/dev/zero of=/tmp/10m.empty bs=1 seek=10M count=0
time mpv /tmp/10{g,m}.empty
```
I keep files with the name format `${name}-${hash}.${ext}.empty` around, where the original is removed, and a sparse file with the size of the original is created instead.
A lot of time is wasted on such files when going through playlists/directories that include some of them.
This admittedly may not be that common of a use-case.
=> stream: don't try to read from all-sparse/no-data files

DOCS/interface-changes/input-select.txt, DOCS/man/javascript.rst, DOCS/man/lua.rst, player/javascript/defaults.js, player/lua.c, player/lua/console.lua, player/lua/fzy.lua, player/lua/input.lua, player/lua/meson.build
This allows scripts to make the user choose from a list of entries by typing part of their text and/or by navigating them with keybindings, like dmenu or fzf.
Closes #13964.
This is simple by reusing console.lua's code and even works in the terminal. I'm not sure if we should go with this or implement a more graphical menu. Example usage:
```lua
local input = require 'mp.input'
local default_item = 1
mp.add_key_binding('F1', function ()
local playlist = {}
for i, entry in ipairs(mp.get_property_native('playlist')) do
local _, filename = require 'mp.utils'.split_path(entry.filename)
playlist[i] = filename
if entry.playing then
default_item = i
end
end
input.select({
items = playlist,
default_item = default_item,
submit = function (id)
mp.commandv('playlist-play-index', id - 1) …
```
=> scripting: add mp.input.select()

audio/filter/af_scaletempo.c
`scaletempo` sometimes sounds much worse then one would expect. Here are some improvements.
The correlation change made a big difference. I'm not sure if the Hann window is placebo or not...
Here are two examples where this makes a huge difference compared to master.
The bass in that song is prone to cause problems with scaletempo (and scaletempo2).
`mpv --no-config --vid=no --start=54 --speed=1.04 --af=scaletempo=overlap=.4:search=30:stride=10 'https://www.youtube.com/watch?v=zyfiwK6wvIg'`
And the first song I found my collection that used integers, which turned out to also be a good example.
`mpv --no-config --vid=no --start=100 --speed=1.04 --af=scaletempo=overlap=.4:search=30:stride=10 'https://www.youtube.com/watch?v=04UjShXZbD0'`
In case anyone is interested, I made [a …
=> af_scaletempo: use Hann window, better correlation

audio/out/buffer.c
Fixes #13641
`ao_play_data` (which is only used in push-based AO) wakes up the core for more data on EOF or underruns. However, it did not wake up the core if `ao->untimed` was set to `true`. This caused the issue of indefinite spinning. This PR addresses this problem by modifying `ao_play_data` to also wake up the core for untimed AO.
I have no idea why untimed AO was explicitly checked in the original code. It was written by wm4. Perhaps someone more familiar with the AO codebase can provide further insight. Nevertheless, this patch just works.
CC @kasper93
=> ao: in ao_play_data, wakeup core for untimed AO as well

fuzzers/fuzzer_loadfile_direct.c, fuzzers/meson.build
Loading external files makes little sense. Might disable this completely later, but let see how it works, The idea is the same as for direct load. Exclude paths starting with `file://.` and `file:///`. But still fuzz any processing that other input might have. It shouldn't be a huge problem if we do `file://mpv` for example. Not great, but also not terrible.
=> fuzzer_loadfile_direct: exclude paths also for file://

misc/language.c, misc/language.h, player/command.c, player/external_files.c, player/external_files.h, test/language.c
commit 1: external_files: rename variables in guess_lang_from_filename()
commit 2: external_files: detect locales with a region like en-US
This loads subtitle files like foo.en-US.srt with --sub-auto=exact.
To preserve the case of these locales and not convert them to e.g. en-us, stop lower casing filenames, and instead use case insensitive functions to check if the media filename is contained in the external filenames. Extensions, whitelisted cover art filenames and idx files were already being compared case insensitively.
Fixes #12372, fixes #13251.
=> external_files: detect locales with a region like en-US

fuzzers/fuzzer_load.c, fuzzers/fuzzer_loadfile.c, fuzzers/fuzzer_loadfile_direct.c, fuzzers/fuzzer_set_property.c
We don't expect any data to actually access, so timeout as soon as possible.
=> fuzzers: set network-timeout to 1 second

audio/aframe.c, audio/out/ao.c, audio/out/ao_pcm.c, audio/out/internal.h
It happens that sample rate can have completely bogus value coming from lavf. Reject that, as we wouldn't do anything useful with it anyway.
Fixes: #13648
=> audio: change bps format to int64_t

meson.build
If subprojects are used, linking language of mpv might be upgraded to C++ add our flags there too.
=> meson: add link flags also to cpp

player/lua/console.lua
console.lua is too close to the left and bottom of the OSD IMO. Make the margins a bit bigger.
=> console.lua: increase margins from the bottom-left corner

player/audio.c
Example file [ao-eof.zip](https://github.com/mpv-player/mpv/files/15268562/ao-eof.zip)
=> audio: report EOF also for untimed AO mode

DOCS/man/osc.rst, player/lua/osc.lua
This is unused since 4e013afd37 because the mpv logo and the "Drop files or URLs to play here." message are shown instead of the OSC controls. It has the adverse affect of making the OSC twice as big when playing videos with --lavfi-complex, because that makes the video property which osc.lua checks unavailable.
=> osc.lua: remove scaleforcedwindow

.luacheckrc, DOCS/man/lua.rst, DOCS/man/mpv.rst, DOCS/man/options.rst, etc/input.conf, input/input.c, options/options.c, options/options.h, player/core.h, player/javascript/defaults.js, player/lua.c, player/lua/console.lua, player/lua/input.lua, player/lua/meson.build, player/lua/select.lua, player/scripting.c
This adds script messages to select playlist entries, tracks, chapters and subtitle lines using the newly introduced mp.input.select().
This fully closes #13964.
=> select.lua: add this script

common/av_common.c
=> av_common: fix integer overflow when adjusting timebase

player/command.c, player/playloop.c
Normally if you seek during EOF, mpv will reset the value of mpctx->stop_play so it doesn't exit. There's at least a couple of exceptions where this *shouldn't* happen however. If the play direction changes right at the end of the file, we shouldn't touch the value to avoid an erronous assertion error. Additionally, it is apparently possible for the queue_seek call in VO reinit code to trigger the assertion issue. This is a seek of exactly zero and logically shouldn't be reset mpctx->stop_play anyways (i.e. AT_END_OF_FILE should stay the same). By moving this to queue_seek itself, most of the special handling in player/command.c can be dropped. The option still needs to be set though. Fixes #13778.
@user1121114685: Can you verify if this works for you?
=> player: do not always set mpctx->stop_play when seeking at EOF

video/out/wayland_common.c
=> wayland: cap xdg_wm_base at 4 if wm_capabilities aren't supported

DOCS/interface-changes/cmd-nonrepeatable.txt, DOCS/man/input.rst, input/cmd.c, input/cmd.h, player/lua/console.lua
This allows forcing certain commands to be non-repeatable, e.g. volume.
Closes https://github.com/mpv-player/mpv/issues/14165.
=> input/cmd: add nonrepeatable prefix

player/lua/select.lua
Show e.g. "30 fps" instead of "30.000 fps".
=> select.lua: strip trailing zeros from FPS values

player/lua/stats.lua
If using --script-opts=stats-vidscale=no, until osd-height changes from 0 to the correct value, stats.lua's text sizes are multiplied by a scale of 720, which with the default font size results in a font size of 5760. Depending on the order of operations, if the stats are drawn at this size before osd-height is updated, mpv freezes. I get this with --input-commands=script-message-to stats display-stats-toggle in conditional profiles, e.g.:
mpv --script-opts=stats-vidscale=no --include=<(echo $'[test]\nprofile-cond=true\ninput-commands=script-message-to stats display-stats-toggle') av://lavfi:testsrc
Fix this by setting a scale to 1 until osd-height is updated to the correct value.
=> stats.lua: prevent freeze in certain cases with vidscale=no

input/input.c
This fixes 2 different bugs:
- mp.add_key_binding('c', ...) taking priority over the builtin g-c binding.
This follows up 994a08f5a7 which fixed this within the same input section. This fixes it across different input sections.
- mp.add_key_binding('g-c', ...) not taking priority over a c binding defined in input.conf.
This happened because is_builtin of bindings added with mp.add_key_binding is true though they're not actually builtin.
=> input: prioritize builtin bindings matching longer key sequences

player/lua/console.lua
The value of list options is a table not just for vf and af but for all object settings lists. Extract just the names from the tables returned when retrieving these options.
=> console.lua: fix completing change-list ao/vo/gpu-context remove

player/playloop.c
handle_osd_redraw is called while we're in the middle of the cleanup portion of play_current_file (via kill_demuxers_reentrant and mp_idle). This happens after we've torn down the subtitle track, so we end up requesting a redraw from the vo, which results in a 1-frame flash of the video without subs before we either quit or switch to the next file (or the force-window state). This detects that condition and skips the redraw, without interfering with drawing the osd during idle (eg for pseudo-gui mode).
=> playloop: don't redraw without subs on quit

.github/workflows/build.yml
This makes rebuilds after build failures significantly faster. There is no reason to discard newly acquired ccache entries.
=> ci: save cache also on failures

DOCS/compatibility.rst, DOCS/interface-changes.rst, DOCS/man/ao.rst, DOCS/man/input.rst, DOCS/man/options.rst, DOCS/man/vo.rst
There is clearly not enough being conveyed about the incompatible changes happened, and users are left guessing what should be done after that. This PR adds these details and requirements so that these concerns are clearly conveyed to the users so that breaking changes can be handled swiftly.
See also https://github.com/mpv-player/mpv/discussions/13974.
=> DOCS: add more details and requirements about incompatible changes

meson.build
Statically linking, especially with LTO can use a lot of memory. Limit to 16 jobs by default, which is more than enough. Only fuzzers are affected as we don't produce that much binaries otherwise.
=> meson: limit concurrent link jobs to 16

player/lua/select.lua
Also don't assume that exit codes are portable between platforms and just print them as is.
=> select.lua: allow ffmpeg to print errors if it fails

fuzzers/fuzzer_loadfile_direct.c, fuzzers/fuzzer_set_property.c
While LibFuzzer supports rejecting unwanted inputs, it looks like Honggfuzz treats anything other than 0 as fatal error.
https://llvm.org/docs/LibFuzzer.html#rejecting-unwanted-inputs https://github.com/google/honggfuzz/blob/348a47213919f14b9453e89a663b1515369bd9a2/libhfuzz/persistent.c#L67 This LOG_F calls exit(EXIT_FAILURE)
=> fuzzers: always return 0

video/mp_image.c
This function is always available, if libplacebo is compiled without libdovi it is no-op.
=> mp_image: remove unneeded PL_HAVE_LIBDOVI check

fuzzers/fuzzer_load.c
They were previously left over, and now that it looks like runners are stuck, the big question is: is /tmp persistent?
This commit will be reverted after the next rebuild.
=> fuzzers/load: clear old temp files if they exist

video/out/wayland_common.c
The idle inhibit protocol specifies that the compositor may ignore the idle inhibitor if the surface is occluded. In the case of vo_dmabuf_wayland, wl->surface corresponds to typical black bars when the video aspect ratio is different than the display's. So in many cases, wl->surface is actually occluded by wl->video_surface which sits above it. Change this so that the idle inhibitor is created on wl->callback_surface instead which is either wl->surface for the gpu VOs or wl->video_surface for vo_dmabuf_wayland. Fixes #14206.
=> wayland: use wl->callback_surface for idle inhibitor creation

TOOLS/gen-mpv-desktop.py, common/av_common.c, common/av_common.h, meson.build, stream/stream.c, stream/stream.h, stream/stream_lavf.c
=> build: dynamically generate mpv.desktop file protocols

audio/decode/ad_spdif.c
It seems that we decode small portion of the audio to determine codec params. We can remember that information.
Fixes: #14178
=> ad_spdif: set codec params

DOCS/man/encode.rst, DOCS/man/input.rst, DOCS/man/options.rst, DOCS/man/vf.rst
They are replaced by `--option=value`.
=> DOCS/man: replace legacy option syntax usage

TOOLS/osxbundle/mpv.app/Contents/Info.plist
Replaces deprecated CFBundleTypeExtensions with LSItemContentTypes. 
LSHandlerRank ranks apps that declare as editors or viewers of a specific file type. [Default value](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundledocumenttypes/lshandlerrank#possibleValues) was chosen since mpv is a viewer of file types as opposed to an editor. 
I tested this patch with some filetypes (avi,mkv,mov,wav) and the launch service seemed to behave appropriately.
=> osxbundle: refactor Information Property List 

audio/out/ao_audiotrack.c, audio/out/ao_audiounit.m, audio/out/ao_avfoundation.m, audio/out/ao_coreaudio.c, audio/out/ao_coreaudio_exclusive.c, audio/out/ao_jack.c, audio/out/ao_opensles.c, audio/out/ao_pipewire.c, audio/out/ao_sdl.c, audio/out/buffer.c, audio/out/internal.h
As we've previously discussed in #13902, a mechanism for pull-based AO to know EOF is needed. This PR addresses this by adding an `eof` out param to `ao_read_data`. The AO can know whether EOF has been reached by checking its value and do proper EOF handling like stop requesting more data.
Meanwhile, to reduce code duplication, this PR merges `ao_read_data` and `ao_read_data_nonblocking` into a unified interface. `ao_read_data` now accepts three more arguments: `bool *eof, bool pad_silence, bool blocking`. I have not touched `ao_read_data_converted` yet; maybe it can also be unified.
This is a draft: I have only implemented EOF handling in `ao_avfoundation`. Work need to be done for other AOs. Also, proper handling of audio frames after EOF is WIP.
=> ao: EOF handling for pull-based AO

player/playloop.c
Fix the bug that seeking to the end of cover art while paused goes back to the beginning of the file because of this condition meant for videos.
This doesn't check mpctx->vo_chain->is_sparse because prevent_eof should be true with actual sparse videos.
=> playloop: don't loop when seeking to the end of cover art while paused

player/lua/console.lua
If complete is case-sensitive and no completions exist the script crashes with the following:
`Lua error: @console.lua:1417: attempt to concatenate local 'prefix' (a nil value)`
=> console.lua: fix crash if no completions exist

video/out/x11_common.c, video/out/x11_common.h
When initially mapping the mpv window, if it was started in fullscreen, mpv unconditionally marked x11->pos_changed_during_fs as true. This is not needed and causes a bunch of problems. While in fullscreen, the window can be moved in a number of ways by the window manager or so on. The net result is that this just causes the mpv window to exit fullscreen on screen 0 instead of the screen it was actually moved to. The size change adjustment is still needed for this case, but forcing pos_changed_during_fs doesn't do anything but cause weird behavior. Fixes #14226.
TODO: Test a bit more to see if something weird happens on another wm.
=> x11: correct position coordinates if mpv was launched with --fs

player/video.c
The logic in question was added in 201bef7ee150f9d852996b379c926ba0c47320d5 for the VDPAU vsync frame timing algorithm, but after the code was moved around for several times, it is now used for all VOs with non-display-sync mode (where the video is synced to audio or system time). It nonetheless likely never did whatever it was intended for.
This "correction" reduced the VO frame duration by the amount that the frame is fallen behind the ideal time. Since a frame is presented between pts (the ideal time for which the frame is scheduled) and pts + duration (the end time for which frame drop is determined), and pts is already computed from the current time and the deviation from the ideal time, this "correction" causes the end time to have the deviation added twice, which is nonsense: if …
=> player/video: fix incorrect VO frame duration and frame drops

DOCS/man/input.rst, player/audio.c, player/command.c, player/configfiles.c, player/playloop.c, player/video.c
See commit message for full details. Supersedes #14205. Hopefully if I understood it right, this should fix all the weird behavior that happens because the audio pts becomes negative.
This fully fixes https://github.com/mpv-player/mpv/issues/10346, and https://github.com/mpv-player/mpv/issues/12247 is still fixed (used a different file that I confirmed exhibited the described issue before some related commits closed it).
=> [RFC] player: handle audio pts more consistently

player/command.c, player/osd.c
For this purpose, the printf precision specifier can be used.
No need to call lrint.
=> various: simplify printing floats as integers

TOOLS/lua/autoload.lua
Operations on option values need to be performed after they are read.
Fixes 843161d96e.
=> TOOLS/autoload.lua: fix directory_mode and ext options

DOCS/interface-changes/input-builtin-dragging.txt, DOCS/interface-changes/input-dragging-deadzone.txt, DOCS/man/options.rst, input/input.c
This PR fixes several problems with VO dragging: 
- Adds `--input-dragging-deadzone` option, which adds a deadzone for the built-in VO dragging.
- Dragging now only begins after the mouse is moved outside of the deadzone while the left button is held down, which should resolve race condition with dragging on some WMs.
- Resolves the conflict between VO dragging and `MBTN_LEFT` binding.
- Makes it possible to disable the built-in VO dragging so that custom dragging behavior can be implemented.
- Prevents activation of double click if the first click begins VO dragging.
Fixes #7563.
Fixes #13225.
Fixes #13958.
Fixes #14248.
=> input: implement VO dragging deadzone

TOOLS/lua/autoload.lua
The extensions list needs to be cleared in this case. Also, add the missing split_patterns().
=> autoload.lua: fix options update

input/input.c
Otherwise, on sections which don't allow VO dragging, the mouse button is force released and dragging events won't be generated.
Fixes: 349aac462e0ce4380df79e59383293c4db6a6039
=> input: only begin VO dragging if the section allows

DOCS/compile-windows.md, README.md
General update. Removed MXE as it is not supported, doesn't support libplacebo and in general it doesn't do anything useful which native Meson cannot do already.
=> DOCS/compile-windows.md: update Windows compilation documentation

osdep/terminal-win.c
Fixes crash when FLS data is attempted to be cleared.
This affects only 32-bit build where the calling convention were not matching the expected one.
=> terminal-win: use proper __stdcall callback for FLS

meson.build, misc/bstr.c
May be faster to use optimized variants instead of simple loop.
=> bstr: use memchr and memrchr for bstrchr and bstrrchr

DOCS/interface-changes/keybind-cancel.txt, DOCS/man/input.rst, DOCS/man/lua.rst, input/cmd.h, input/input.c, player/command.c, player/javascript/defaults.js, player/lua/defaults.lua
There is a subtle behavior difference for built-in/input.conf key bindings and key bindings registered by scripts: when a key binding is canceled (e.g. a mouse button is bound to a command, is pressed down, and then another key is pressed which is bound to another command), the command is not invoked if the binding is built-in/input.conf, but is invoked if it's registered by scripts, because it's handled with a different mechanism, which gives no way for scripts to detect this.
Fix this by using the newly available canceled flag to detect this. If a key binding is canceled, the callback is now not invoked unless the key binding is registered with the complex option. In this situation, the callback is invoked with the canceled state available so that scripts can detect and handle this …
=> defaults.lua: fix canceled key bindings handling

video/out/w32_common.c
It will be set again on first key press, but no need to call IME api every 250ms until any key is pressed.
=> w32_common: stop IME initialization timer after first try

audio/out/ao_wasapi_changenotify.c, audio/out/ao_wasapi_utils.c
May fix broken systems like #12145 or #14314. Probably won't change anything, but it is the correct context to use anyway.
=> ao_wasapi: limit the scope of execution context

.github/workflows/build.yml, ci/build-mingw64.sh, ci/build-msys2.sh, video/out/hwdec/hwdec_vaapi.c
Draft until it is fixed upstream. https://github.com/actions/runner-images/issues/9977
=> ci/mingw: use Ubuntu 24.04

osdep/terminal.h, player/loadfile.c
Make terminal output consistent with the symbols introduced in 14462dafe4.
There is no need to print ◌ for unselected tracks for alignment since terminal text is always monospace.
=> loadfile: improve the format of terminal track information

player/lua/select.lua
commit 1: select.lua: preselect the correct sub line with duration >= 100 minutes
ffmpeg outputs timestamps like '100:00.00' in LRCs instead of adding hours, and timestamps like '100:00' are < '10:00', so since these strings are being compared, if there is no current subtitle line, there are subtitle lines at >= 100 minutes, and time-pos is between 10 minutes and 100 minutes, one of the last subtitle lines gets preselected.
Fix this by converting the timestamps to numbers before comparing them.
Also simplify the logic by merging the 2 loops to determine the default line, and reformat the timestamps by adding hours to not print minutes > 60 in the selector, and by removing the hundredths of seconds. This requires storing the accurate timestamps in a table to seek to them on submit.
commit …
=> select.lua: preselect the correct sub line with duration >= 100 minutes

player/lua/console.lua
After d49879f1f7 terminal escape sequences are printed in the console log for unselected tracks. Remove them and make those lines grey.
=> console.lua: prettify unselected track log messages

DOCS/interface-changes/show-playlist-titles.txt, DOCS/man/options.rst, DOCS/man/osc.rst, options/options.c, options/options.h, player/command.c, player/lua/osc.lua, player/lua/select.lua
Allow configuring whether to print the media-title or the filename in show-text ${playlist}, the OSC playlist and in the playlist selector.
Showing titles can be annoying when files are badly tagged, or when it hides the track numbers of album songs.
The OSC's playlist_media_title script-opt is removed because this option is better since it works everywhere after configuring it once.
Closes #11653.
=> options: add --osd-playlist-entry

DOCS/man/vf.rst, video/filter/vf_vapoursynth.c
Currently the vapoursynth video filter does not accept any argument for passing arbitrary user data. This limits what the VS script can do.
Ideally, the vapoursynth filter has an user-data parameter that contains string value. mpv passes that value to the VS script just like container_fps and others. Once the VS script gets the data, it can do all sorts of data extraction and transformation.
Another benefit is that instead of mpv always have to catch up to user needs for this filter, with this users can just pass whatever needed themselves, thus becomes more future-proof.
Fixes #14214
Discussion: I did not put any restriction on how big the user data can be. Could there be any security vulnerability without such restriction?
=> vf_vapoursynth: add user-data parameter to allow user to pass arbitrary data to script

DOCS/interface-changes/egl-output-format.txt, DOCS/man/options.rst, options/options.c, options/options.h, video/out/opengl/egl_helpers.c
This PR adds two options:
- `--egl-config-id`: select specific EGL config based on ID.
- `--egl-output-format`: select EGL config based on format names.
This allow users to customize swapchain format when using EGL.
=> egl: allow customizing egl config 

DOCS/man/osc.rst, player/lua/osc.lua
OSC rendering used to be smooth (up to OSD rendering fps) before 48f906249ef359c66fc6c5bf4cc5885c8293bf8e, but after that commit the frame duration is hardcoded to 30 ms. This is too high and results in choppy OSC rendering, which is very noticable with the progress bar while moving mouse over it or playing a short 60 fps video.
This makes the duration an option so that it can be decreased to make OSC rendering smoother.
=> osc.lua: add option to make rendering smoother

DOCS/contribute.md, DOCS/interface-changes.rst, DOCS/interface-changes/input-select.txt, DOCS/interface-changes/input-touch-emulate-mouse.txt, DOCS/interface-changes/native-touch.txt, DOCS/interface-changes/touch-pos.txt, TOOLS/gen-interface-changes.py
Sort interface changes by the types of changes to make it easier for users to find breaking changes. I think it's more useful than sorting it by date. Closely related changes can still be grouped by files.
=> TOOLS/gen-interface-changes.py: sort interface changes by change types

TOOLS/lua/status-line.lua, player/lua/osc.lua, player/lua/stats.lua
This doesn't do anything because nil is already the default value of unavailable properties.
=> lua: don't pass nil as the second argument of mp.get_property_number

input/input.c
Normally, key bindings are resolved in the input section stack order. However, mouse key bindings have a special "active mouse section" feature (which is a section with MOUSE_MOVE bound and mouse button is down in the section) which lets the section to be selected instead, with a fallback to the "default" section. The intention of the feature is for mouse dragging which should "stick" to the section where the mouse is down.
This causes a problem with scripts which bind mouse double clicks: since double clicks are triggered on mouse down, it's resolved with the "active mouse section" feature instead of the section stack order. If the section which has the double click bound doesn't also have MOUSE_MOVE bound, the "default" section will be used instead. If it's already bound there, it will …
=> input: don't resolve double clicks on the active mouse section

DOCS/man/options.rst, DOCS/man/stats.rst, player/lua/stats.lua
This adds file tags to display along with the title, including album/artist etc. for music, and series etc. for some videos. The list of tags to display is identical to the tags printed to the terminal and is controlled by the `--display-tags` option.
=> stats.lua: display file tags

player/lua/console.lua
https://github.com/rossy/mpv-repl enabled and disabled its keybindings with input sections (define-section, mp.enable_key_bindings and mp.disable_key_bindings), but when wm4 merged it in mpv, he changed it to use mp.add_forced_key_binding and mp.remove_key_binding because he deprecated input sections, but he forgot to remove the mp.enable_key_bindings line. Remove it now.
=> console.lua: don't enable the console-input input section

etc/input.conf
It makes sense to reset panscan along with the zoom because it is a kind of zoom.
=> input.conf: make Alt+BS reset panscan

demux/demux_lavf.c
d0aeca59189c44b3999cc7add9d23642a73fe188 started passing the file name to libavformat when probing for jpeg files so some weird edgecases would work. The problem with that commit is that it causes image2 to be picked which is blacklisted in demux_lavf (for good reason) and then it falls back to demux_mf. This works, but it breaks fetching several properties (demux-w, demux-h, etc.) since demux_mf is not capable of providing this information. That leads to subpar behavior in scripts (e.g. my own but there could easily be other people) that rely on this information that was previously available for the vast majority of well-behaved files. So revert it since it's basically a sledgehammer.
To address the two fringe cases that tried to fix, a couple of different approaches are used. One is …
=> Revert "demux_lavf: pass jpg filenames to ffmpeg for probing"

DOCS/interface-changes/vapoursynth-api-v4.txt.txt, meson.build, video/filter/vf_vapoursynth.c
VapourSynth introduced their version 4 API in R55, 3 years ago. mpv is still using the deprecated version 3. I think it is good to migrate before VapourSynth completely removes it.
The gist of the change is documented in https://github.com/vapoursynth/vapoursynth/blob/master/APIV4%20changes.txt. The most impacted area is the video format. Previously we have a fixed table of supported formats, each represented by an integer. In v4, the integer is replaced by pointer to the full struct of the format. More details below.
Second, the way to create video filter is changed. Previously caller needs to supply a "initialization" callback to `createFilter()`, which sets up video info etc. In v4, video info is prepared first, passed to the `createVideoFilter2()` and we get back the node.
Also, …
=> vf_vapoursynth: upgrade to VapourSynth API v4

player/lua/stats.lua
It is not common to have one pass with 100% usage, but it is not impossible, so handle this case too.
=> stats.lua: align 100% correctly on page 2

demux/demux_lavf.c
The options parameter here can be NULL. It's NULL checked a few lines down, but not for the propagate_opts loop. This results in null derefence with `--demuxer-lavf-format=image2`.
Fixes: b6413f82b22b5c3bd7b0a4fec28fdd2625feaf94
=> demux_lavf: fix null derefence in io_open callback

demux/demux_lavf.c
demux_stream_is_selected() already checks if stream is valid, so move the image format hack check after that.
Fixes: 4ef7931266759560a860e66e01b75622a0a3996b
=> demux_lavf: fix null derefence of stream variable

fuzzers/meson.build, meson.build
This is kinda required by fuzzers and makes easier to handle stdlib instead of manually injecting it into link flags.
=> fuzzers/meson: set link language to cpp

.editorconfig
This makes tab width to 7 on GitHub web UI and supported editors, making it impossible to use tabs to match the existing 4 space indentation.
=> editorconfig: punish tab usage

DOCS/interface-changes/osc-show.txt, DOCS/man/osc.rst, player/lua/osc.lua
Add a way to briefly show the OSC, which is useful to check file name, playback progress and time left, etc.
Fix issue #3826
=> osc.lua: add script message to show up the OSC

etc/mpv.bash-completion
Hashbangs are meant for scripts that are executed, but a bash completion script is meant to be sourced and therefor shouldn't have a hashbang.
Remarked by Debian's ``lintian`` tool with the ``bash-completion-with-hashbang`` tag.
=> bash-completion: remove hashbang

audio/out/ao_avfoundation.m, meson.build, meson_options.txt, osdep/mac/event_helper.swift, osdep/mac/log_helper.swift, osdep/mac/meson.build, osdep/mac/swift_compat.swift, video/out/cocoa_cb_common.swift
https://developer.apple.com/documentation/foundation/nslocking/4059821-withlock available from macOS 10.10 but xcode 14+ required. xcode 14.0 introduced swift 5.7
logger is a macOS 11 feature. ~~i hope the runtime check works like that.~~ otherwise the initialisation of the logger has to move to init or a computed property.
Fixes #14310
=> mac: compatibility for older dev tools

player/lua/osc.lua
Deprecated since mpv 0.9. Use the flags instead.
No need to specify flags for relative seek since it's the default.
=> osc.lua: don't use legacy argument for seeking

test/libmpv_encode.c
Doesn't really matter but it's annoying so replace it with mkstemp instead. For windows, just keep using mktemp.
=> test/libmpv_encode: avoid mktemp warning

video/out/vo_tct.c
We were drawing garbage data after reconfig, if there is no yet video frame ready or in --force-window without video track.
Found by OSS-Fuzz.
=> vo_tct: clear backbuffer on reconfig

player/lua/select.lua
commit 1: select.lua: don't use sub-start to preselect subtitle lines
There is no need to compare sub-start now that we don't check for exact matches with ffmpeg's timestamps. time-pos can always be used.
Comparing time-pos removes the need for the workaround of sub-start of embedded subtitles being earlier than ffmpeg's timestamps, as time-pos is always slightly after sub-start.
Removing this workaround also fixes a bug present since 4059d1832b, which started comparing numerical values of timestamps instead of strings to determine the preselected subtitle line, where the line after the current one is preselected when sub-start is greater than ffmpeg's timestamps because they have been rounded, e.g. sub-start 10.001 is > than ffmpeg's 10.00.
This will also allow considering --sub-delay in …
=> select.lua: consider --sub-delay for the subtitle line selector

video/out/gpu/video.c
No need to reset `mp_pass_perf` which is only read when `desc.len > 0`. This avoids zeroing >16384 `uint64_t`'s every time it's called. Profiling shows that this reduces CPU usage for frame rendering by ~4%.
=> vo_gpu: optimize pass_info_reset

options/m_config_core.c, options/m_config_core.h, options/m_config_frontend.c, options/m_option.h, player/command.c
Previously, using m_option_type_alias required that the alias have the full name of the option value. This is limited if you are reusing the same opts struct in different sub options. Fix this by add an additional field to m_option to signal whether or not prefixes should be taken into account for the alias option. Instead of blindly using whatever is stored in opt->priv as the name, we can construct the desired option name for either case (using the prefix or not).
Would be useful for #14195.
=> m_option: add a way for aliases to use sub option prefix

osdep/terminal.h, player/loadfile.c, player/lua/console.lua, player/lua/select.lua
Stop making unselected tracks and editions grey because they can be hard to read over a dark background (\033[2m would be hard to differentiate from regular text with a light theme instead), and because there is no way to not print the escape sequences in --log-file.
Just use the same circles as the OSD and OSC. We need to print the empty circles for alignment on mlterm with East Asian fonts (we could also make them invisible with \033[8m but it would still get added to log files).
Add back the space before tracks and editions so they look like a sub-section of the "Playing..." line printed with playlists and of "Track switched", consistently with the metadata which starts with space which makes it look like a sub-section of the "File tags" line.
Also stop converting Hz to kHz for …
=> loadfile: update the format of terminal track information

.github/workflows/build.yml, fuzzers/fuzzer_set_property.c, fuzzers/meson.build
Makes it easier to build only fuzzer binaries and avoid building unnecessary targets from subprojects.
=> meson: add fuzzers alias for all fuzzer targets

DOCS/interface-changes/option-removal.txt, demux/cache.c, demux/demux_cue.c, filters/f_decoder_wrapper.c, options/options.c, options/options.h, stream/stream_cdda.c, video/out/drm_common.c, video/out/gpu/video.c, video/out/vo_sixel.c, video/out/vulkan/context.c
Felt like doing some janitor work again. All of these were from mpv 0.37 or earlier, and I see no reason to continue leaving these deprecated/useless options in the codebase for years. Let me know if you think if any of these are too soon. I also didn't document the removal of the `OPT_REMOVED` ones because mpv fails opening if you use any one of those so it's not really a terribly relevant interface change imo. Just the removal message goes away.
Didn't touch the `--gamma-auto` or `--gamma-factor` stuff since we already have a PR for that (#14369).
=> [RFC] cleanup some deprecated options

common/playlist.c, common/playlist.h, player/loadfile.c
Previously, playlist-prev didn't work if you played a playlist to completion using --idle and tried to go back. Naturally, one would expect this to bring up the last item in the playlist, but nothing happens. This is just because playlist_get_next is stupid and doesn't take this into account since pl->current is NULL and thus returns NULL. Fix this by also considering the direction and grabbing the last playlist entry in the index.
=> playlist: fix some playlist-prev/playlist-next edge cases

demux/demux_playlist.c, filters/f_lavfi.c, fuzzers/fuzzer_load.c, fuzzers/fuzzer_loadfile_direct.c, fuzzers/fuzzer_set_property.c
Adding base path make sense only if it is real directory or url location. In case of protocols like memory adding base path to playlist entry in facts adds whole playlist to that entry.
For example `mpv $'memory://#EXTM3U\na/b` produces infinite loop, expanding playlist.
Found by OSS-Fuzz.
=> demux_playlist: don't add base path to self-expanding protocols

misc/natural_sort.c
Before a7158ceec00f14e680a885722cfe23761b4662d3, string comparision was done with strcmp, which does unsigned comparison. The natural sort implementation instead compares on char values.
This causes implementation-defined behavior in comparison, depending on the signedness of char type.
Fix this by using unsigned comparison instead.
Fixes: #13435
=> misc/natural_sort: avoid implementation-defined behavior in comparison

DOCS/man/options.rst, video/out/wayland_common.c, video/out/wayland_common.h
Mainly for debugging. It might be handy to disable presentation feedback on wayland to make sure something isn't going wrong with the calculations somewhere.
=> wayland: add a --wayland-present option

player/lua.c
We wrap the default Lua allocator to allow used memory tracking. This works well, except that we never destroy the default allocator or notify it that we are closing. Since we override it for the current Lua state, it is reasonable that the Lua engine does not expect it to be used. We get and pass through a free call, but in the case of LuaJIT, the internal allocator has additional state and is freed differently. So, in fact, it is a LuaJIT leak because once we replace the allocator with our custom one, they should clean its internal state. I guess the assumption is to override allocator only before any allocation happen. To work around this issue, restore the default allocator, the one that we use, before closing the state. This way, everything is cleared as expected.
Note that the …
=> player/lua: restore original lua allocator before close

input/cmd.c, input/cmd.h, options/m_option.c, options/m_option.h
A relic when commands lived in input.c. Move them to where other option types live. Also remove the redundant copy_opt.
=> input/cmd: move m_option_type_cycle_dir to m_option.c

player/lua/ytdl_hook.lua
Sometimes the `cookies` field output from yt-dlp will have a cookie with a quoted value, e.g. when it contains a special character such as `=`:
```
yt-dlp --print "%(.{formats.-1.cookies})#j" "https://www.tiktok.com/@conner_omalley_/video/7365919655254347050"
```
```json
{
"cookies": "tt_chain_token=\"bCJCjdkykbJshO3+LUEj4w==\"; Domain=.tiktok.com; Path=/; Secure; Expires=1735098525"
}
```
These quotes are added by the Python stdlib function `http.cookies.SimpleCookie.value_encode()`, and do not pose an issue for yt-dlp or other Python scripts.
They do pose an issue for mpv, though. The following command throws HTTP 403 Forbidden due to ffmpeg making a request with a cookie value that has literal quotes:
```
mpv -v -v -v "ytdl://https://www.tiktok.com/@conner_omalley_/video/736591965525434 …
```
=> ytdl_hook: strip quotes from cookie values

DOCS/man/options.rst, player/command.c, video/out/gpu/context.c, video/out/gpu/context.h
This follows up 96e1f1dfa5 which converted --gpu-context, and has the same advantages as listed there.
Unlike with --gpu-context auto can be used anywhere in the list, e.g. --gpu-api=d3d11,auto works.
I wanted to use the list of GPU contexts as the description in get_type_desc(), but there is no talloc context to allocate it to, so I set a print_help_list to print them. The printed lines don't being with spaces because otherwise they are added to the completions by etc/_mpv.zsh.
=> video/out/gpu/context: convert --gpu-api to object settings list

demux/demux.c, player/loadfile.c
Slightly tighten the refresh seek requirement for https://github.com/mpv-player/mpv/pull/14399 to make sure not to unnecessarily seek video streams.
=> demux: avoid seeking video streams for refresh seek

DOCS/interface-changes/console-scale.txt, DOCS/man/console.rst, player/lua/console.lua
commit 1: console.lua: remove the scale script-opt
This is redundant because you can set font_size and border_size to have the same effect.
commit 2: console.lua: minor tweaks
- Remove the opts comments because they are already in console.rst and will become outdated if not updated in both places
- Reuse last_pos in truncate_utf8() instead of recalculating the previous character's position
- Clear the OSD earlier when the console is not active
=> console.lua: minor tweaks

player/lua/stats.lua
nonrepeatable was missed since mpv-player/mpv@bc5863a
=> stats.lua: add a missing command prefix

demux/ebml.c
There was one zero too many. Change the limit to 128 MiB with more readable notation.
=> demux/ebml: fix ebml size check

audio/out/buffer.c
Introduced by b74c09efbf7c6969fc053265f72cc0501b840ce1
=> ao: don't add buffer length to timeout twice 

video/out/vo_dmabuf_wayland.c
This happens with a positive --video-zoom value. We send invalid toplevel size and get killed by the compositor.
=> vo_dmabuf_wayland: don't use -ve margins in window size calculation

demux/demux_edl.c, demux/demux_mkv.c, player/loadfile.c
Fixes infinite recursion. Trying to extract dirname from string of memory://<data> is not really a good idea.
Found by OSS-Fuzz.
=> demux_edl: don't try to extract dirname from self-expanding protocols

video/out/x11_common.c
On X11, aspect ratio constraint is applied on the window manager side, so whenever keepaspect and keepaspect-window change, mpv should update the size hint immediately, otherwise the new constraint isn't applied.
=> x11_common: handle runtime keepaspect/keepaspect-window change

demux/demux_mf.c
This allows playing arguments like
mf://https://foo.jpg,https://bar.jpg
and also URLs within @listfiles (files with 1 image per line).
URLs still don't work with globs and printf-formats.
=> demux_mf: support URLs in @listfile and filemask

demux/demux_mf.c
Not intended to be run on urls. Fixes stack-overflow in glob() when unexpected data is passed.
Found by OSS-Fuzz.
=> demux_mf: don't run glob() on urls

osdep/subprocess.c, osdep/subprocess.h, player/command.c, player/lua/ytdl_hook.lua, player/scripting.c
Useful for debugging purposes and sanity checks.
=> player/{command,scripting}: log subprocess execution

video/out/vo_dmabuf_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h
Described in more detail in the upstream MR*. mpv naively rounds which makes us susceptible to the mentioned error. Fix this by keeping wl->scaling and wl->pending_scaling in the base 120 units. Use the simple rounding algorithm when needed for calculating widths/heights. Create a wl->scaling_factor as convenient shorthand for scale / 120 which is what wl->scaling used to previously be.
*: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/309
=> wayland: avoid potential floating point errors while scaling

.github/workflows/fuzz.yml
To increase our testing coverage before merging. This uses already build corpus and coverage info to test the modified code, if possible.
See: https://google.github.io/oss-fuzz/getting-started/continuous-integration
=> [RFC] ci: add fuzzing of pull requests for 20 minutes

demux/ebml.c
While the code before 571f9b0f23f31741f3c5947b839411acfefae3cf had a typo and it was intended to be 100 MB, there are files that exceed this limit, like 147 MiB. Increase the limit to 512 MiB which should be more than enough for valid files.
From quick look ffmpeg limits to 1<<8 bytes, so we should be good with our new limit.
In theory this limit could be removed, but it is better to play the file, possibly with skipped some corrupted block of data, instead OOM.
Fixes: 571f9b0f23f31741f3c5947b839411acfefae3cf
=> demux/ebml: bump ebml size limit to 512 MiB

test/libmpv_lifetime.c, video/out/vulkan/context_mac.m
@kasper93 just wonder if this is what you had in mind. was the test supposed to test a vo on every platform or is it more like a test that libmpv init works properly and if no vo can be initialised it should error out gracefully?
this does the latter now on macOS and errors out properly if the context can't be initialised because no NSApplication environment is found.
if we want the former, we would need to init an NSApplication in the test.
=> mac/vulkan: error out on context creation without an NSApplication

video/out/vo_gpu_next.c
There's broad agreement that this option will be undeprecated, so just factor in the multiplier for vo_gpu_next.
=> vo_gpu_next: support --gamma-factor

player/command.c, player/playloop.c
This makes sure that commands like show-text update the osd properly with --idle=yes.
=> command: run input commands after idle state is ready

player/lua/osc.lua
This lets touch events activate a separate timeout for osc hiding so that the osc only hides when both mouse and touch timeout are expired. This is the general expectation with touchscreen UI, and also fixes platforms which reset the mouse position when all fingers leave the touchscreen (e.g. sway).
Fixes: #13985
=> osc.lua: don't hide osc when touch is active

DOCS/interface-changes/packet-bitrate.txt, DOCS/man/input.rst, player/command.c, player/loadfile.c, player/lua/select.lua, player/lua/stats.lua
Print "Image" instead of "Video" for video tracks. This fixes #8561.
Print the hls-bitrate in select.lua.
Show the same flags in loadfile.c, select.lua and stats.lua. The only differences are that only stats.lua prints albumart because it's supposed to show detailed track information, and select.lua prints the image flag because pressing g-v doesn't show Video or Image like in loadfile.c and stats.lua.
=> various: sync track information output

DOCS/man/options.rst
ARGB is in fact _not_ like web color. It's easy to skim over the actual hexadecimal provided in the next sentence and just assume mpv understands RGBA after reading the words "web colors"
As an aside, if we decide to change OPT_COLOR to actually be like web colors, the only options that use OPT_COLOR are `sub-color`, `sub-outline-color`, `sub-back-color`, `macos-title-bar-color`, and `background-color`.
=> DOCS/options: remove misdirection in `sub-color`

options/options.c, options/options.h, video/out/opengl/context_wayland.c, video/out/vo_dmabuf_wayland.c, video/out/vo_wlshm.c, video/out/vulkan/context_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h
Unlike every other platforming backend, wayland has its own specific sub_options struct. 027ca4fb855f3dff4cba1c907c92c509b82e6fe8 originally introduced this and some more options were added later, but in retrospect it's unneccesary complications. There are already x11, windows, and macos-specific options within vo_opts. In fact, there actually is a wayland one in there already as well (wayland-content-type) so it's split between two places. All of the platform-specific code already has to handle vo_opts as well. Additionally, we already make sure to update vo_opts on runtime and there's an existing mechanism already in place to handle callbacks if needed. The wayland-specific sub_options struct was stuck with whatever you set at init time.
So solve everything by deleting the old …
=> options: move all wayland specific options to vo_opts

DOCS/interface-changes/loop.txt, DOCS/man/input.rst, DOCS/man/options.rst, player/command.c, player/core.h, player/loadfile.c, player/misc.c, player/playloop.c
commit 1: player: don't decrement --loop-file=N and add remaining-file-loops
This stops decreasing numerical values of --loop-file on each iteration so that loop-file=N loops every playlist entry without having to add --loop-file to --reset-on-next-file.
The current behavior confuses users as seen in:
https://github.com/mpv-player/mpv/issues/2481
https://github.com/mpv-player/mpv/issues/5943
https://github.com/mpv-player/mpv/issues/11291
https://github.com/mpv-player/mpv/issues/13860
https://www.reddit.com/r/mpv/comments/rcwnrw/looping_each_file_n_times_in_a_playlist/
Also options are supposed to reflect the value configured by the user and not change on their own.
A remaining-file-loops property is exposed as a replacement to check how many loops are left.
commit 2: player: don't …
=> don't decrement --loop-file=N and --ab-loop-count=N

player/command.c
It turns out that mpv runs all option callbacks with a flag on init, so since a5937ac7e3 if --force-window is passed, the VO is immediately reinited and initialized and mpv acts as if --force-window=immediate was passed. Fix this by excluding UPDATE_VO from UPDATE_OPTS_MASK on init.
=> player/main: fix --force-window=yes acting like immediate

DOCS/compile-windows.md
Attempting to install `git` on the `pacboy` line fails with `error: target not found: mingw-w64-clang-x86_64-git` so move that to another spot.
`video_mp_image_pool.c` fails to build due to libavutil right now because of missing vulkan headers so make sure to also install those with `pacboy`. A relevant github issue elsewhere: https://github.com/mesonbuild/meson/issues/13016
<details>
<summary>Example error:</summary>
<pre>
[164/254] Compiling C object libmpv-2.dll.p/video_mp_image_pool.c.obj
FAILED: libmpv-2.dll.p/video_mp_image_pool.c.obj
"cc" "-Ilibmpv-2.dll.p" "-I." "-I.." "-Icommon" "-Ietc" "-Iplayer/javascript" "-Iplayer/lua" "-Isub"
"-IC:/msys64/clang64/include/fribidi" "-IC:/msys64/clang64/include/freetype2" "-IC:/msys64/clang64/
include/libpng16" …
=> DOCS/compile-windows.md: fix MSYS2 packages

meson.build
Vulkan dependency implies only vulkan loader, but some distributions split vulkan-loader and vulkan-headers, so check if the headers are actually there.
=> meson: check for vulkan headers

DOCS/man/ipc.rst, DOCS/man/mpv.rst, DOCS/man/options.rst, input/ipc-unix.c, input/ipc-win.c, options/options.c, player/scripting.c
This makes `--input-ipc-client` work on Windows.
=> input/ipc-win: support fd:// for --input-ipc-client 

player/audio.c, player/core.h, player/video.c
See individual commit messages
=> player/audio: invert audio_started boolean

player/loadfile.c, player/lua/select.lua
Print demux-bitrate if available, else hls-bitrate, not both (as demux-bitrate is generally more reliable). This avoids printing "HLS kbps" which looks weird.
Fixes
https://github.com/mpv-player/mpv/pull/14453#discussion_r1700550385
=> loadfile,select.lua: print only one bitrate

DOCS/client-api-changes.rst, osdep/mac/libmpv_helper.swift, video/out/gpu/libmpv_gpu.c
It won't be TA allocated and would fail on header check. Also documentation doesn't mention that ownership is transfered to mpv, so it is unexpected.
This will cause existing clients of this API leak this memory, but I doubt anyone really used it in this broken state.
Fixes: #14633
=> vo_libmpv: don't steal pointer provided by the API user

player/lua/osc.lua, player/lua/select.lua
If a playlist entry ends with a slash these scripts only show the basename which is empty. Fix this by stripping trailing slashes so that the last directory component becomes the basename.
This was broken even before dc998560aa.
=> {osc,select}.lua: show playlist entries with trailing /

DOCS/interface-changes/user-data-subpath.txt, DOCS/man/input.rst, player/lua/console.lua
Currently user-data/osc is used for interpolation between the osc and other internal scripts. Reserve this sub-path and also user-data/mpv to make sure external scripts can only use these values as directed. New internal uses of user-data should use user-data/mpv instead.
=> DOCS/man/input: reserve user-data/osc and user-data/mpv sub-paths

DOCS/interface-changes/pitch-shift.txt, DOCS/man/options.rst, options/options.c, options/options.h, player/audio.c, player/command.c
Uses resampling in tandem with any time-stretching audio filter (scaletempo, scaletempo2, rubberband) to change the audio's pitch while leaving its tempo intact.
=> audio: add a pitch-shifting feature

DOCS/man/af.rst, DOCS/man/options.rst
Previously, this was in the rubberband filter but it gives out random numbers without explaning where they come from. Move it to the --pitch section instead and reword it a bit. Closes #14652.
=> DOCS/man: improve explanation on how to shift notes with --pitch

filters/f_lavfi.c, filters/filter.c, filters/filter.h, osdep/mac/meson.build, video/decode/vd_lavc.c, video/filter/vf_d3d11vpp.c, video/filter/vf_vavpp.c, video/filter/vf_vdpaupp.c, video/hwdec.c, video/hwdec.h, video/out/d3d11/hwdec_d3d11va.c, video/out/d3d11/hwdec_dxva2dxgi.c, video/out/gpu/hwdec.c, video/out/gpu/hwdec.h, video/out/hwdec/hwdec_aimagereader.c, video/out/hwdec/hwdec_cuda.c, video/out/hwdec/hwdec_drmprime.c, video/out/hwdec/hwdec_drmprime_overlay.c, video/out/hwdec/hwdec_vaapi.c, video/out/hwdec/hwdec_vt.c, video/out/hwdec/hwdec_vulkan.c, video/out/opengl/hwdec_d3d11egl.c, video/out/opengl/hwdec_dxva2egl.c, video/out/opengl/hwdec_dxva2gldx.c, video/out/opengl/hwdec_vdpau.c
This series sets up the infrastructure we will need to support the `v4l2request` hw device type in ffmpeg, assuming that code gets merged upstream.
This new device type creates a scenario we haven't seen before - two device types that produce the same hw image format (`IMGFMT_DRMPRIME`). Our existing logic will result in the first declared hwdec being used, regardless of the device type associated with the frame being decoded - and that means either the traditional `DRM` device type doesn't work or the new `V4L2REQUEST` one doesn't work. Not great.
To avoid that, we introduce the ability to look up an hwdec with both an image format and a device type, and then propagate that everywhere it needs to be known.
This change doesn't actually include anything `v4l2request` specific. That is a …
=> Add support for multiple hwdecs with the same image format and different device types

video/out/drm_prime.c, video/out/opengl/context_drm_egl.c
Similar to `handles` the `modifiers` must be supplied for each plane of the format or a framebuffer cannot be created.
Use the `format_modifier` tied to the `object` used for the `plane` to fix use of formats with modifiers.
Also fix the improper use of the `DRM_MODE_FB_MODIFIERS`-flag for formats without modifiers.
This changes to always use `drmModeAddFB2WithModifiers` for all formats and with proper use of the `DRM_MODE_FB_MODIFIERS`-flag all formats with or without modifiers should be supported. The fallback to use `drmModeAddFB2` is kept just in case.
This fixes playback of videos decoded by e.g. `rpivid` into `NV12` format with `SAND128` modifer on RPi5 using the `drmprime-overlay` interop.
=> drm_prime: fix use of formats with modifiers

video/img_format.c
Addresses the warning: "writing 1 byte into a region of size 0"
=> img_format: prevent an offset >= MP_MAX_PLANES into bpp

.github/workflows/build.yml, ci/build-mingw64.sh
Support for 32-bit binaries were restored.
See:
https://github.com/actions/runner-images/issues/9977
https://bugs.launchpad.net/ubuntu/+source/linux-signed-azure/+bug/2071445
https://launchpad.net/ubuntu/+source/linux-azure/6.8.0-1012.14
This reverts commit f47cbcd43967fca0d2ae8b5a0a409a6e3ed96528.
=> Revert "ci/mingw: don't run test on 32-bit binary"

video/filter/vf_d3d11vpp.c
Fixes: bbb3d5ba78b2423393bc65e9d5f13f0ab62d3c4d
=> vf_d3d11vpp: ensure width and height is even

player/lua/console.lua
If you type something before pressing Ctrl+r, filter the commands containing the typed line.
fuzzy_find() is modified to not code a separate case when the line is empty in both handle_edit() or search_history().
=> console.lua: pre-filter searched commands if the line is filled

video/out/vulkan/context_display.c
There are generic fallback paths for those and it shouldn't be replaced by noop.
=> vulkan/context_display: don't fake avalibity of callbacks

DOCS/man/vf.rst, filters/f_hwtransfer.c, video/filter/vf_d3d11vpp.c
This fixes d3d11 frame download further in filtering chain.
Fixes: #14732
=> vf_d3d11vpp: alloc output frames through AVHWFramesContext

video/out/gpu/video.c
This makes the reported sizes the same as how stats.lua calculates sizes for VOs witout video-target-params while in dumb mode.
=> video/out/gpu/video: use video rectangle for video-target-params

video/filter/vf_format.c, video/mp_image.c, video/mp_image.h, video/out/vo_gpu.c
Since d9c1e9bc5c8ca5e4a75b197789b77890375cb8e2 dovi metadata is unconditionally mapped to colorspace in mp_image.
However, Dolby Vision videos can have backwards compatibility present for players without the ability to interpret dovi metadata, like all current VOs other than gpu-next. In this case, the original video colorspace should be used instead of the fabricated dolbyvision/pq colorspace.
So make mp_image contain both colorspaces (original and mapped), and only use the mapped colorspace when the VO understands dovi metadata.
Fixes: d9c1e9bc5c8ca5e4a75b197789b77890375cb8e2
Fixes: https://github.com/mpv-player/mpv/issues/14770
=> mp_image: save fallback colorspace when dovi metadata is present

etc/input.conf
Allows users to toggle software decoding with a single action if they are using a value for `hwdec` that is different from `auto-safe`.
The previous behavior was annoying if you selected specific decoding APIs like `--hwdec=vulkan,d3d11va,...`, since you had to cycle to `auto-safe` first before being able to cycle to `no`. Doesn't regress the previous behavior of the keybind when you're using `--hwdec=no`, so it should be a straight improvement unless I'm missing something.
=> input.conf: swap the positions of values for `ctrl+h` binding

video/out/gpu/libmpv_gpu.c
Same as 2a72e6cb20c2af302041a0b30dbf0d1b93990a4a for libmpv.
=> vo_libmpv: use fallback colorspace for Dolby Vision

etc/mpv.conf
We don't support reading mpv.conf without a mpv parent directory anymore (did we ever?).
=> etc/mpv.conf: update stale comment about mpv config location

input/input.c, misc/node.c, misc/node.h
It has been changed in one of the iterations of the patch during review, but bstr doesn't have to be null terminated. Fix it by adding dedicated node_map helper.
Fixes: 1a27f3c
=> input: fix use of bstr like null terminated one

player/lua/stats.lua
After a subject line, the text style needs to be reset to make sure that key binding lines have correct size and alignment while scrolling the page.
=> stats.lua: fix text size/alignment for key bindings page

player/main.c
The terminal input thread holds the input_ctx reference.
Fixes: c1282d4d43be8fb8bbc8529b22804d288d59038a
Fixes: https://github.com/mpv-player/mpv/issues/14817
=> player/main: uninit input after terminal uninit

video/out/wayland_common.c, video/out/wayland_common.h
Supersedes #11420.
This makes resizing in a completely vertical direction (no left/right change) actually work with --keepaspect.
=> wayland: fix vertical resizing

audio/out/ao_alsa.c
Test by having mpv running then killing and restarting alsa.
=> ao_alsa: assume device lost if we couldn't recover after 10 attempts

video/out/vulkan/context.c
This prevents us from recreating the swapchain when needed for direct scan out on Wayland, and the comment is old and doesn't seem to be true.
With this, direct scanout with vulkan on wayland should just work. Note that you might also need https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/31122 if you're on an explicit sync compositor.
=> vulkan: don't tolerate suboptimal swapchain configurations

player/lua/console.lua, video/out/filter_kernels.c, video/out/filter_kernels.h, video/out/gpu/video.c, video/out/gpu/video.h, video/out/vo_gpu_next.c
This allows Tab completing them in the console and zsh, and using cycle scale.
jinc is also added to --tscale=help's output, while before it was missing because validate_scaler_opt() skipped filter windows with the same name as a filter kernel, but the jinc kernel was skipped with --tscale because it is polar.
=> vo_gpu{,_next}: convert scale options to type choice

common/msg.c, player/lua/console.lua
Also avoid regular white/black, because it is often the terminal background and invisible as foreground color.
Change debug messages to blue while at it to differentiate them from trace ones.
=> msg: don't use bold colors and instead use bright ones

sub/osd.c
Ideally it should be fast, it is on VO thread and steals precious frame time budget. Looks like this is one of the main reasons why display-resample on higher refresh rate displays is too slow.
=> sub/osd: add log if osd rendering takes too long time

osdep/terminal-win.c, player/main.c
msg must be the last module to uninit since pretty much everything else uses logging.
This reverts commit f92d5da89cf0b025f1bee1801e66911fe1efb6ff.
This reverts commit c1282d4d43be8fb8bbc8529b22804d288d59038a.
Fixes https://github.com/mpv-player/mpv/issues/14851
=> player/main: revert msg uninit order changes

player/lua/console.lua
commit 1: console.lua: fix highlighting the selected item with --msg-module
With --msg-module mp.input.select also highlights the "statusline" on the next line. Fix this by resetting the color before \n instead of after it. This requires changing all log code to not pre-emptively add a newline, which is actually simpler, though we have to modify the messages received with log-message which already contain a newline.
commit 2: console.lua: truncate more characters with --msg-module and --msg-time
Fix the terminal width calculation for mp.input.select with these options.
=> console.lua: fixes for --msg-module

DOCS/interface-changes/sub-ass-use-video-data.txt, DOCS/man/options.rst
I didn't get a chance to review that before it was LGTM'd.
=> DOCS: fix sub-ass-use-video-data documentation

video/out/vo_gpu_next.c
This has been possible since https://github.com/haasn/libplacebo/commit/11771cdd82cec0d2f775553611c276092fb283cf but nobody bothered to map it to mpv until now?
Fixes #11925
=> vo_gpu_next: allow setting antiring value for cscale

filters/f_auto_filters.c
Not wanted apparently: https://github.com/mpv-player/mpv/pull/14822#discussion_r1758134111
=> f_auto_filters: don't set interlaced-only for userdeint

TOOLS/gen-mpv-desktop.py
Apparently for an user mpv would crash on startup if built with asan and mpv attemps to load mpv-mpris. Just set --no-config so we don't load anything external since this is more correct anyway.
=> TOOLS/gen-mpv-desktop.py: set --no-config when probing protocols

sub/sd_ass.c
ASS_OVERRIDE_BIT_STYLE includes ASS_OVERRIDE_BIT_ATTRIBUTES, which we don't want.
This prevents --sub-ass-override=force from overriding attributes such as bold, italics, underline or strikeout to mpv defaults.
=> sub/sd_ass: don't override event attributes to mpv defaults

filters/f_hwtransfer.c, video/hwdec.h, video/out/hwdec/dmabuf_interop_wl.c, video/out/hwdec/hwdec_vaapi.c, video/out/vo_dmabuf_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h, video/out/wldmabuf/ra_wldmabuf.c, video/out/wldmabuf/ra_wldmabuf.h
You need bad hardware to actually test this. If you don't have bad drivers with poor format support, nothing should change except you might technically do an extra autoconvert step. Couldn't avoid that sorry but just use `--hwdec` anyway.
Basically my card is unable to correctly display vaapi frames from nv12 and other several common formats. On master, the behavior I get is red frames with broken colors (e.g.: #13098). This can be worked around by manually specifying a format version beforehand (e.g. `--vf=format=bgr0` in my case) which will then display the correct colors since my GPU does do bgr0.
Edit: removed some dated stuff since this changed alot.
=> vo_dmabuf_wayland: reject formats not supported by the GPU

video/mp_image.c
This results in all image params not being restored even if only one is unknown. In particular params->color.hdr isn't cleared, causing overblown color for some samples.
It should be safe to restore even unknown values.
mp_image_params_guess_csp will handle that.
This reverts commit 3acd253e896206c79cd0c46ba93bf29219f61aa8.
=> Revert "mp_image: don't restore image params if they're unknown"

TOOLS/lua/cycle-deinterlace-pullup.lua
This has been broken since b56e63e2a9 removed vf del. Replace it with vf remove. Fixes #14881.
=> TOOLS/cycle-deinterlace-pullup.lua: fix removing the filter

DOCS/man/options.rst
Avoids promising/specifying fallback behaviours not controlled by mpv and a bit of additional rewording
*(e.g. if read on a glance without full context/attention “recommenden to only use `none` or `aspect-ratio`” can be interpreted in exactly the opposite way as was intended)*
cc @na-na-hi
=> DOCS/man/options.rst: further tweak sub-ass-use-video-data description

player/lua/select.lua
There's no advantage in using the forced version here. It is a leftover from when this was an external script and forced was necessary to bind key sequences reliably until 3f83671f20.
=> select.lua: don't use add_forced_key_binding

DOCS/interface-changes/ytdl-path-and-json-properties.txt, DOCS/man/input.rst, player/lua/ytdl_hook.lua
It's useful for user scripts to be able to use the same ytdl binary that
ytdl_hook uses without having to replicate ytdl_hook's process of
searching for the ytdl binary.
Some user scripts might also find it useful to be able to access ytdl's
json output that the ytdl_hook already receives, sparing user scripts
from having to make a duplicate ytdl binary invocation to get the json
output.
Providing just the json output is not enough though, as ytdl doesn't communicate
errors though it -- if an error occurs, ytdl provides no json output and instead
prints to stderr. So without stderr, there is no way for user scripts to figure
out why ytdl has failed: no such username / video id, the channel is not live
yet, etc. Because of that, the entire result of the subprocess call is provided
to the …
=> ytdl_hook: make path and json available to other scripts

TOOLS/file2string.py, TOOLS/osxbundle/meson.build, etc/meson.build, input/meson.build, player/javascript/meson.build, player/lua/meson.build, sub/meson.build
This fixes "Generated from" comments to not include local source path in generated files.
=> meson: use relative file paths for file2string

DOCS/man/mpv.rst, input/input.c
Also fixes an incorrect BOM handling.
=> DOCS/man/mpv.rst: clarify configuration files should be UTF-8

demux/demux_mkv.c
Fixes: 66e451f4e6e0d0b259eddfd3673f1aa5ff127726
=> demux_mkv: add missing color repr init

demux/demux_mkv.c
It turns out that probing too many blocks is bad. I did not attempt to go through all the logic but reading that many blocks causes the demux_reader_state have some pretty funny values which then makes the playloop think it needs to buffer for cache. It's probably fixable... but seems hard admittedly so I'll be lazy. Just take out a magnitude off the probing down to 10000. These seems to be more than sufficient. The sample in #13975 where we had the opposite issue only needs somewhere between 1700 and 1750 blocks to be properly detected. Crudely looking at the demuxer values, 10000 here doesn't appear to alter anything meaningfully so it does not have the "too many blocks problem". Hopefully this is a perfect medium? Further improvements to the probe can always be added later. Or maybe we …
=> demux_mkv: drop image probing down to 10000 blocks

options/options.c
Since f411f3145ba2f6eebc658917d0879d5e573bbdf0, these properties no longer change with each loop. This however caused a regression on the behavior of resetting loop count by resetting these properties.
Previously, after the loop count is decreased, it is possible to reset these properties back their original values and thus reset the remaining loop count. Currently, because setting properties has no effect if the new value is the same as the existing value (which no longer changes), resetting these properties does nothing, and remaining-*-loops (which are read-only) remain unchanged. There is no way to reset them other than temporarily setting them to a different value, which is awkward.
Fortunately, this can be fixed by marking these properties as force_update, which always notifies …
=> options: force --ab-loop-count and --loop-file notification

misc/random.c, misc/random.h, osdep/timer.c, player/main.c
I recently encountered issues when running multiple instances of `mpv --shuffle` in parallel like this:
for i in $(seq 4)
do
mpv --shuffle dir/ &
done
([full script here](https://gist.github.com/frostschutz/0e88a14a4b3e2a17ca0b88407c18e5ad#file-noise-sh-L42))
The same tracks were played in the same random order. On my system this happened like 1 out of 10 times.
Turns out two instances of mpv ended up using the same random seed despite using nanosecond time. Since the seed is based on time, I can work around it by sleeping some random time before starting mpv:
sleep 0.$RANDOM && mpv --shuffle dir/ &
But then I thought, why not improve the seed...?
Since each process has a unique pid, and mpv already has `mp_getpid()`, I thought of adding it to the seed. That alone, pretty much fixed the …
=> misc/random: seed using libavutil/random_seed

player/external_files.c, video/decode/vd_lavc.c
Fixes segfault when using `--cover-art-whitelist-clr` and `--hwdec-clr` because they are not checked for list emptiness.
=> various: fix null deref for string list options

video/out/wayland_common.c, video/out/wayland_common.h, video/out/wldmabuf/ra_wldmabuf.c
I believe my mistake in #14815 is that I was too aggressive with the format filters and planar ones should only be used if there was not any valid modifiers. If a valid format + modifier pair is matched, then it should be considered valid and we accept it.
@na-na-hi: Does this fix the extra conversion you were seeing?
=> ra_wldambuf: don't unconditionally filter out non-planar formats

etc/_mpv.zsh
The list options --screenshot-avif-opts and --vo-image-opts are completed with an extra 8), e.g. --screenshot-avif-opts-add=8), because *= in
`screenshot-avif-opts=-:Key/value list (default\: usage=allintra,crf=0,cpu-used=8):`
matches up to `cpu-used=` instead of instead of up to `screenshot-avif-opts=.`
Fix this by enabling non-greedy matching.
=> zsh-completion: fix completing --screenshot-avif-opts-*

video/out/vo_dmabuf_wayland.c, video/out/vo_wlshm.c
Both of these VOs draw buffers in software via wl_shm to an mp_image, so they are affected by the internals of whatever mpv does for alignment. When wlshm was originally written, mp_sws was aligning to 16 bytes and thus it chose this value but it was hardcoded. vo_dmabuf_wayland later blindly copied this value. e1157cb6e8191f98b60813dc91342e3baf577d92 actually changed the internal value to 64 bytes. In theory, this doesn't probably doesn't really matter since 16 should also work in most cases, but we might as well stop using a magic number and be consistent.
Additionally, wl_shm did some funny alignments that no other software output did. The reasoning was apparently due to warning messages from ffmpeg while cropping*. This was left in at the time, but I'm not able to reproduce any such …
=> vo_{dmabuf_wayland,wlshm}: use proper values with MP_ALIGN_{UP,DOWN}

ci/build-mingw64.sh
A bunch of lavfi filters were presumably not available in mingw builds because of this.
``` ps
% grep -E '=(".+ |")gpl("| .+")$' configure
blackframe_filter_deps="gpl"
boxblur_filter_deps="gpl"
boxblur_opencl_filter_deps="opencl gpl"
colormatrix_filter_deps="gpl"
cover_rect_filter_deps="avcodec avformat gpl"
cropdetect_filter_deps="gpl"
delogo_filter_deps="gpl"
eq_filter_deps="gpl"
find_rect_filter_deps="avcodec avformat gpl"
fspp_filter_deps="gpl"
histeq_filter_deps="gpl"
hqdn3d_filter_deps="gpl"
interlace_filter_deps="gpl"
kerndeint_filter_deps="gpl"
mcdeint_filter_deps="avcodec gpl"
mpdecimate_filter_deps="gpl"
mptestsrc_filter_deps="gpl"
nnedi_filter_deps="gpl"
owdenoise_filter_deps="gpl"
perspective_filter_deps="gpl"
phase_filter_deps="gpl"
pp7_filter_deps="gpl"
pp_filter_deps="gpl …
```
=> ci/mingw: pass --enable-gpl to ffmpeg's configure

video/out/hwdec/dmabuf_interop_wl.c, video/out/vo_dmabuf_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h, video/out/wldmabuf/ra_wldmabuf.c, video/out/wldmabuf/ra_wldmabuf.h
The multi device part is mostly theoretical, but it turns out that plasma does send multiple tranches to the same device so we have to take that into account. And that means taking into account multiple devices as well. In theory if a compositor gives us a scanout tranche, that should be preferred for vo_dmabuf_wayland if there's a format match in there. Otherwise, we look at the main device.
We would still need some way to force mpv to do a reconfig + clear the autoconverter if devices actually changed during runtime. That can be for another day.
=> wayland: support multiple devices and tranches when querying formats

filters/f_hwtransfer.c, video/hwdec.h, video/out/hwdec/hwdec_vaapi.c
Limited range rgb is evil and not supported by FFmpeg, this ensures parity of hardware conversion with software conversion.
Fixes: #14849
=> f_hwtransfer: ensure that we convert to full range rgb with scale_vaapi

DOCS/interface-changes/display-page-toggle.txt, DOCS/man/stats.rst, player/javascript/defaults.js, player/lua/console.lua, player/lua/input.lua, player/lua/stats.lua
commit 1: stats.lua: filter keybindings by comment
Requested in #14966.
commit 2: stats.lua: scroll keybindings while filtering them
console.lua binds up and down to navigate its history. After it is opened by pressing /, bind up and down to scroll the keybindings again.
Fixes #14966.
=> stats.lua bindings fixes

DOCS/interface-changes/geometry-behavior.txt, options/m_option.c, video/out/cocoa_cb_common.swift, video/out/mac/common.swift, video/out/mac_common.swift, video/out/vo_sdl.c, video/out/w32_common.c, video/out/wayland_common.c, video/out/win_state.c, video/out/win_state.h, video/out/x11_common.c
9e81fc9ba992949172c405e09dea8897587e3ce2 started doing this and then later when force update notifications were added it became even more apparent with issues like #14911. In retrospect, this behavior change is not really intuitive (nobody would reasonably expect --geometry=50% to also center the window) and actually completely avoidable. vo_calc_window_geometry3 already flags for us if the window should be moved either via the opts->force_window_position or if there is a valid xy specified in the geometry option. All we need to do is check the flags for VO_WIN_FORCE_POS and use that for determining whether or not an actual window move should be done.
=> x11: don't unconditionally move the window on geometry changes

.github/workflows/build.yml
It's being dropped upstream* and recently lua51 was removed along with luajit*. mingw32 already covers 32-bit support, and it's not like we're in dire need of this so just remove it.
*: https://github.com/msys2/msys2.github.io/commit/89521b9f8d43b6ebf4a4f4a51c912066ab5f5b50
*: https://github.com/msys2/MINGW-packages/commit/947a8592ca9b7d4af6d6520d3083f6118a390036
=> github/workflows: drop clang32

README.md
yasm is no longer supported by FFmpeg.
See: https://github.com/FFmpeg/FFmpeg/commit/2f888fb99eef07a259879273bc9999c5e86620ca
=> README.md: reference nasm instead of yasm

.github/workflows/build.yml, ci/build-msys2.sh
No longer needed after 232919336d567b70330c43a41920238a56e100da.
This reverts commit 883a45fa3eb7347431c246d831cf8ece12da8676.
=> Revert "ci/msys2: disable some features for 32-bit build"

meson.build, osdep/mac/app_bridge.m
building without swift makes mpv as a standalone app completely useless, because the main function exits immediately. besides other functionalities that are also missing.
this is really only useful as a libmpv only usage.
Fixes #14931
=> mac/app: fix building with swift disabled

video/filter/vf_format.c, video/mp_image.c
It currently doesn't copy original params before mapping, resulting in wrong colors when some video filters are used.
The original format also needs to be set when converting formats to make sure the correct format is restored.
=> mp_image: copy params before dovi mapping for mp_image_copy_attributes

video/out/w32_common.c
This remembers and sets window-scale when exiting maximized state. Also fixes not staying in maximized state when exiting fullscreen mode.
Fixes: #14126
=> win32: fix resizing window when maximized

.github/workflows/build.yml
Homebrew does support 3 latest macOS versions, so while macOS 12 still works it takes 1h 40m 7s to build. It is bit too much...
While we drop macOS 12, add macOS 15 as it is available now.
=> ci/macos: shift macOS versions to 13-15

demux/demux_playlist.c
Even if it doesn't match extensions in filter mode.
=> demux_playlist: ensure the file is added to autocreated playlist

DOCS/man/mpv.rst, player/lua/console.lua
This adds click support for the select menu. Scrolling with the wheel already worked.
If a custom OSC binds a button to a select.lua script-binding, this lets users keep using the mouse to select an item.
While the OSC and the select menu are open at the same time, you can no longer click the OSC's buttons. By using mp.add_key_binding instead of add_forced_key_binding you could click both, but the console's binding would be shadowed by MBTN_LEFT bindings in input.conf.
Inspired by https://github.com/Samillion/ModernZ
=> console.lua: allow clicking selectable items

video/out/vulkan/context.c
lavu has recently had support added for these two extensions, so enable them.
Both are older than the oldest required Vulkan headers version.
=> vulkan/context: use VK_EXT_shader_object if available

DOCS/interface-changes/ytdl_hook-include.txt, DOCS/man/options.rst, player/lua/ytdl_hook.lua
By the default mpv tries opening URLs with ffmpeg first, and users who don't configure try_ytdl_first get a slower startup for youtube URLs, on top of yt-dlp already being slow.
Fix this by adding a script-opt of URL pattern to try with ytdl first. Youtube and twitch are included by default.
Compared to the alternative of trying ytdl first by default and excluding URLs with a media extension, this only works for the sites explicitly included in the new option, but doesn't have false positives on media URLs without an extension.
Alternative to #14963
=> ytdl_hook.lua: add include script-opt of URLs to try with ytdl first

video/out/vo_gpu_next.c
Bit of an edge case since image-lut requires the frames to be remapped again so the normal redraw when paused doesn't work. Also we use update_options in the VOCTRL here.
=> vo_gpu_next: force a reset when --image-lut is updated

meson.build, meson_options.txt, osdep/mpv.exe.manifest
This essentially obsoletes the console wrapper (mpv.com), which is no longer needed. The console is attached depending on the context in which mpv.exe is run.
Add an option to control which subsystem is targeted. Keep the GUI application as the default to preserve compatibility with Windows versions prior to 24H2.
For more information about the new console handling, see: https://github.com/microsoft/terminal/blob/4386bf07fd65f763693132ee5e4c43a2a571dc76/doc/specs/%237335%20-%20Console%20Allocation%20Policy.md
=> win32: set consoleAllocationPolicy to detached in the manifest

test/meson.build
The CI breaking because some new format was added in the master branch is pretty annoying so only run these on release versions that are known to work to reduce some maintenance burden. Although why we even bother with this is still a valid question.
=> test: only run ffmpeg tests on release versions

player/sub.c
The video_pts condition here would bail out on still images with no audio since their pts is always MP_NOPTS_VALUE. This is not exactly great because the subtitles may need to be updated so just let these files also go through the subtitle redraw logic below.
=> player/sub: ensure subtitles are updated for images with no audio

options/options.c
To properly update lavc options it may be required to reinit sub decoder, so mark this option as UPDATE_SUB_HARD.
=> options: mark sub-lavc-o as UPDATE_SUB_HARD

video/out/vulkan/context.c
Fixes build on Debian stable (Bookworm).
Fixes: #15041
Fixes: 2ac1d6db329a129f9f35dba0e679e9044fc05ee6
=> vulkan/context: make use of VK_EXT_shader_object only if available

video/out/w32_common.c
I must have misunderstood the intent of the previous commit. Adjusted to always center on window initialization.
Fixes: #15043
Fixes: e01eab4385d8fe6a542dd9526f912e37b691f58e
=> win32: center geometry, but only at start

video/out/w32_common.c
Now VO_WIN_FORCE_POS is set even if position is not provided by user, so we have no choice to always fit. We should do that anyway and if some issues in multi monitor configuration happens, this has to be fixed differently.
Fixes: #15049
Fixes: e5159de8118120163689c27f5cbc1ec68c2d27c8
=> win32: always fit to the screen on initial positioning

video/out/vo_gpu_next.c
It is not going anywhere soon.
Fixes: #14696
=> vo_gpu_next: suppress tone_mapping_param deprecation warning

filters/f_hwtransfer.c, video/hwdec.h, video/out/hwdec/hwdec_vaapi.c
Uploading all available formats has proven to be problematic because more unusual ones can crash the driver, even when no upload is necessary. Check the upload only if needed to avoid issues with broken drivers.
Fixes: #14956
Fixes: #15030
=> hwdec_vaapi: try format upload lazily

video/out/wayland_common.c
Version 2 allows the compositor to send an appropriate refresh rate if the output uses VRR. There are no changes to the API. Since mpv would otherwise use a heuristic based on the last-seen output, it does not matter to mpv if the output uses VRR.
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/320/diffs
=> wayland: use wp-presentation v2 if available

stream/stream_cdda.c
This was fixed upstream* and in a new release, so it is no longer needed for our CI.
*: https://github.com/rocky/libcdio-paranoia/commit/3ced3d72debae3cf304c81be820356c336fd31a2
=> stream_cdda: stop suppressing -Wscript-prototypes

player/lua/stats.lua
These options keep text readable whether you use a small screen near you or a faraway large screen, but they make it unreadable in small windows, so change them to only scale upwards, i.e. when the window height is > 720.
Proposed in https://github.com/mpv-player/mpv/discussions/15044. But I don't use these options so I don't know if you may want the downscaling. Also scrollable stats page 1 was already implemented in https://github.com/mpv-player/mpv/pull/12271 / https://github.com/mpv-player/mpv/compare/06f8166ae83253de79e44f62cfdceda15eef9393..3e34942c55eca8a3908f8e845787064f3157e3a8 so that can be reused.
=> stats.lua: rename a variable

DOCS/man/input.rst, input/cmd.c, input/cmd.h, player/lua/console.lua, player/lua/stats.lua
Some keys like WHEEL_UP are "scaled" if the input source is high resolution, like touchpad. However, sometimes it's desirable to disable this scaling and only active the key binding in discrete steps, such as relative keyframe seeking which interacts poorly if the command is scaled.
This adds the nonscalable prefix to disable this scaling.
Fixes: https://github.com/mpv-player/mpv/issues/15080
=> input/cmd: add nonscalable prefix

TOOLS/gen-mpv-desktop.py, meson.build
Running cross-compiled binaries may be possible, but the runtime environment must be configured correctly. In some configurations, an exe_wrapper needs to be used, and in all cases, the library path must be set correctly for the given binary. Fortunately, Meson handles all of this if cross-compilation is configured correctly.
Fix this by having Meson run the mpv binary directly, instead of as a subprocess of a Python script. This ensures that the environment is properly set for running host binaries, if possible.
Fixes: #15075
Fixes: 056b03f9ed05607786427da8f336e3ef819b3a1e
=> build: fix dynamic generation of mpv.desktop file protocols

video/out/x11_common.c
See commit message for details on why it's not enabled for standalone mode.
=> video/out/x11_common: make IME work (for libmpv usage)

DOCS/man/mpv.rst, DOCS/man/stats.rst, etc/input.conf
This should help new users to view mpv's key bindings as it's easier to discover than shift+i and 4, because many other websites and terminal applications show key bindings upon pressing ?.
=> input.conf: bind ? to show keybindings

video/out/cocoa_cb_common.swift
since commit 15c48f3 we were force to start drawing on the main queue again. this has several unintended side effects due to the nature of the main queue. in this case fullscreen event and shutdown event are executed out of order and fullscreening is done after shutdown, leading to accessing options that are already de-initialised.
just nil the window on shutdown and make it impossible to fullscreen after shutdown.
Fixes #14810
=> cocoa-cb: fix race on shutdown and toggling fullscreen

osdep/mac/application.swift
since the bundle operates in a different shell environment than the one from the terminal, it only has a few default paths set.
add the homebrew ARM default install paths to the PATH environment variable, so the bundle can also find the needed binaries like yt-dl.
=> mac/app: add homebrew ARM install paths to the bundle PATH environment

video/out/cocoa_cb_common.swift, video/out/mac/common.swift, video/out/mac_common.swift
we keep track of the current vo struct to flag for events that are initiated async by various thread from different system notifications. the problem here is the usage of that vo struct after uninit.
make accessing of that vo struct atomic and clear it on uninit, so it can't be used afterwards by concurrent threads from system notifications or events.
Fixes #15088
=> mac/common: fix usage of vo struct after vo uninit race

video/out/meson.build, video/out/protocols/xx-color-management-v4.xml, video/out/vo_dmabuf_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h
This is #14936 but with only the `xx-color-management-v4` part since that is used by compositors in the wild nowadays (mutter 47 and kwin 6.2) and users can actually benefit.
@denkdran: If you could test out this branch, that would be good so any necessary fixes/tweaks can be caught.
=> wayland: add support for xx-color-management-v4

DOCS/man/input.rst, DOCS/man/osc.rst, player/command.c, player/lua/osc.lua, sub/osd_libass.c
All of the code to format playlist/track-list/chapter-list is unnecessary when mpv's core can already show-text these properties.
Also an issue with this custom formatting is that showing fewer entries than can fit on the OSD can make it seem like the playlist ends there and there are no entries afterwards.
Also remove lots of pointless code around the track-list (mpv's track id and the osc_id are exactly the same).
This simplification will make it easier to bind customizable commands, otherwise yet another script message to call set_track would have to be added, when cycle sub/audio already output information about the new track on their own.
show-text ${track-list} shows all types of tracks unlike the OSC formatting. Sub-properties to only show one type can be added to replicate that if …
=> osc.lua: remove NIH list formatting

meson.build
(void) isn't enough for gcc. You also need an "!" apparently.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425#c34
=> meson: add back '-Wno-unused-result' for gcc

DOCS/man/stats.rst, player/lua/stats.lua
If not opened in oneshot mode, close the stats with ESC. Especially now that ? toggles showing key bindings by default, this provides an intuitive way to close the stats.
Also do some minor reformatting of key binding documentation.
=> stats.lua: exit with ESC if being toggled

common/msg.c
There were some concerns about the width of the … glyph, so avoid it and use two dots.
Fixes: 6aa331289f10b12622fadc1589092276d30296aa
=> msg: use .. instead of … as ellipsis char

video/out/wayland_common.c
Basically we only want to create the color surface if the compositor supports parametric image descriptions and if the vo is dmabuf-wayland. Instead of doing the weird dance of creating it in one spot and destroying it later, just only make the wayland object when we actually want it. It makes the logging less confusing as well.
=> wayland: be less stupid with color surface creation

DOCS/man/options.rst, osdep/mac/app_bridge.h, osdep/mac/app_bridge.m, osdep/mac/app_hub.swift, osdep/mac/application.swift, osdep/mac/type_helper.swift
this wasn't previously possible, but with the recent complete rewrite of Application mechanics it is now possible to access options early in the mac App creation.
App Bundles operate in their own shell environment that is different from the one in the terminal. the default PATH variable for all Bundles is /usr/bin:/bin:/usr/sbin:/sbin. because of that mpv can not find binaries installed by package manager that might be used in scripts for example.
add an option to prepend paths to the Bundle PATH. we prepend to make the order fully configurable, opposed to appending where the default Bundle binaries would always take precedence.
=> mac/app: add option to adjust Bundle PATH variable

osdep/mac/event_helper.swift, osdep/mac/remote_command_center.swift, osdep/mac/type_helper.swift
something i meant to do for some time. this only shows external cover images or opened images as cover artwork. embedded covers are not supported atm.
=> mac/remote: show external covers in Now Playing Info Center

input/input.c, options/parse_configfile.c, player/javascript.c, stream/stream.c, stream/stream.h
This allows cleaning up some code duplication which can be served by `stream_read_file`.
=> various: use stream_read_file for loading files

.github/workflows/build.yml, DOCS/compile-windows.md
The fix for response files escaping issues has been merged.
See: https://github.com/mesonbuild/meson/pull/11715
Available as of meson 1.6.0
=> ci/win32: use upstream meson

DOCS/man/input.rst
This paragraph is clearly wrong. load-input-conf was recently added, but even before that the enable-section and disable-section commands could change key bindings at runtime without scripts.
=> DOCS/man/input: input-bindings can change at runtime

DOCS/man/options.rst, video/out/x11_common.c, video/out/x11_common.h
When the present extension was originally implemented, nvidia was specifically blacklisted. The reason was because at the time it would give bogus values that appeared to be real but actively made playback worse. So out of an abundance of caution, any nvidia detection at all (e.g. on a multi-gpu system) would disable the use of the extension. Well times have changed and actually presentation-time on wayland for nvidia works now amazingly enough. For xorg, the extension still doesn't work, but from user testing it does not seem to be harmful anymore. It just does nothing. So we can remove the blacklist part and just only use a whitelist. Like before, we only enable the extension for mesa drivers by default so no practical change for anyone except multi-gpu systems whom may have this …
=> x11: remove nvidia blacklist logic from --x11-present=auto

DOCS/interface-changes/stats-term-clip.txt, DOCS/man/stats.rst, player/lua/stats.lua
Use the new property introduced in bf025cd289 to clip the lines of stats.lua with accurate unicode width detection and considering --msg-module and --msg-time.
no_ass_indent is changed from \t to 4 spaces because the width of \t is not calculated correctly.
mpv --idle --script-opts=stats-bindlist=yes uses io.write, so don't use ${term-clip-cc} in that case because it doesn't work.
=> stats.lua: clip lines with ${term-clip-cc}

.github/workflows/comment.yml
If the pull request is not found or is not open, it should not be treated as a critical error. This situation can occur after a merge. There is no reliable way to query a pull request from a workflow_run event, so this has been made a non-error log.
=> workflows/comment: don't error out on closed pull requests

player/lua/osc.lua
The alternative would be wrapping in single quotes, to keep the output consistent with doubles. Though if the aim is consistency, `osc.lua` is more double wrap than single.
=> osc.lua: replace escaped double quotes with single quotes

demux/demux_playlist.c, player/javascript.c, stream/stream.c, stream/stream.h
Needed because js_pushlstring can throw and skip the free below.
@avih Does this look good to you?
=> player/javascript: use af for stream_read_file talloc context

video/out/vo_gpu_next.c
First of all, `lutdata` was passed to `pl_lut_parse_cube()` even if
it was empty. This caused a bogus error message to be printed by
the LUT parsing code in libplacebo.
"[vo/gpu-next/libplacebo] Missing LUT size specification?"
One of the reasons why `lutdata` can be empty is if the LUT file size
exceeds the `max_size` limit passed to `stream_read_file()`.
So in this commit, `lutdata` is checked first before getting passed to
libplacebo, and a non-bogus error message is printed if it's empty.
And secondly, the max size allowed is raised from 100MB to 600MB, which
should be more than enough for opening 256\*256\*256 LUT files. This LUT
size (256) covers the RGB 24bit color range, and is helpful for testing
different 3D interpolation algorithms.
=> vo_gpu_next: raise LUT file max size and report an error if exceeded

DOCS/man/osc.rst, player/lua/osc.lua
This allows seeking to the start of a chapter without exactly clicking a chapter mark.
Inspired by ModernX.
=>  osc.lua: seek to the nearest chapter when right clicking the seekbar

DOCS/interface-changes/osc-buttons.txt, DOCS/man/osc.rst, player/lua/osc.lua
8bf5548589 added mouse support to selectors, so open them from OSC buttons.
It's up for debate where middle or right click should be bound. By binding middle click `show_message(get_tracklist())` is no longer bound. By binding right click, it no longers cycles tracks backwards, though scrolling with the wheel still does.
Closes #5067, closes #6291, closes #10621, closes #11878.
=> osc.lua: open select.lua by clicking buttons

DOCS/man/osc.rst, player/lua/osc.lua
osc.lua: don't show the osd-bar on chapter navigation
It is redundant if you're already using the OSC, so only show the chapter text. Also fix the documented default commands of these buttons which were outdated.
=> osc.lua: don't show the osd-bar on chapter navigation

video/out/x11_common.c
The logic for getting the display edges was wrong and always resulting in 0 0 0 0 (first display) instead of the full desktop. This also fixes #11716 
This was tested with my own window manager inspecting the x11 _NET_WM_FULLSCREEN_MONITORS content.
=> x11: fix --fs-screen=all

video/out/vo_gpu_next.c, video/out/vulkan/context.c, video/out/vulkan/context.h, video/out/vulkan/context_mac.m
see #13767.
@Dudemanguy is that what you had in mind?
should i optimise the `sw->fns->color_depth(sw)` call so it isn't called twice in the worst case?
=> mac/vulkan: add retrieval of color depth and return auto (0)

video/out/gpu/context.c
For most actual desktop users, vulkan should be the a superior experience over opengl as this point and our autoprobe should pick that. For linux users, vulkan on wayland is rapidly seeing improvements and is far ahead of egl. There is no sign of that changing anytime soon and working fifo is on the horizon, so really wayland users should just all be using vulkan from now on. For x11, there is not a big difference between using egl vs vulkan as far as I know and both work well. macOS already prefers the vulkan backend over the libmpv one anyways, and finally windows still defaults to d3d11. Probably virtually no one uses opengl on windows, but vulkan is reasonably common among windows users and it doesn't make any sense to prefer opengl over it.
The two outliers here are Android and …
=> video/out/gpu/context: prefer vulkan over opengl when reasonable

demux/demux_playlist.c
when the file is in the current directory, p->real_stream->path points
directly to the path, while path includes "./". Neither include "./" in
any other situation
Fixes: c201c4874def40b30e5017728bbfbe04ad065dcc
=> demux_playlist: fix comparison for current file if it's in current dir

DOCS/man/osc.rst, player/lua/osc.lua
Useful now that track metadata is printed. This now uses the same duration as playlist and chapter-list.
=> osc.lua: show track-list for one more second

player/lua/ytdl_hook.lua
This PR mostly serves as a discussion about how this issue might be resolved.
`ytdl_hook` is aware of many useful playlist metadata tags which are essentially lost during the creation of a playlist as `yt-dlp` is called twice: once for the playlist url and then again for each entry. Here the json representing the playlist and its metadata is no longer available in the json produced for each entry.
It is not clear whether `yt-dlp` should provide the metadata or if `ytdl_hook` should go out of its way to try and capture this information and provide it during another instance of `run_ytdl_hook()` and what consequences that might have.
See also https://github.com/yt-dlp/yt-dlp/issues/11234
=> ytdl_hook.lua: support playlist_title

player/lua/osc.lua
While files are loading, track options have the value "auto". Print "-" in that case.
Fixes 1a558bf5c2.
=> osc.lua: don't print auto before tracks are selected

DOCS/man/osc.rst, player/lua/osc.lua
This might be more useful than having the same binding as middle click. Suggested by llyyr.
=> osc.lua: cycle tracks on right click

DOCS/interface-changes/console-scale-with-window.rst, DOCS/man/console.rst, player/lua/console.lua
This makes console.lua consistent with the OSD, osc.lua and stats.lua. This reads --osd-scale-by-window so users don't have to configure vidscale in yet another script.
=> console.lua: scale with the window height

player/lua/console.lua
Fixes overly large text on hidpi displays.
=> console.lua: don't scale with display dpi if scaling with window size

DOCS/man/console.rst, player/lua/console.lua
console.lua: fix the hovered line calculation
Update the logic for the hidpi scaling changes introduced by a670f75679.
=> console.lua: fix the hovered line calculation

player/lua/console.lua
If not scaling with the window the hidpi scale needs to be factored into mouse-pos. Follow up to a670f75679 and a2106396bc.
=> console.lua: fix the hovered line calculation without scale with window

DOCS/man/console.rst, player/lua/console.lua
In the select menu there are no completions to align in a grid, so the better looking proportional font of --osd-font can be used by default. It is also easier to read for the visually impaired.
The text width calculation is no longer performed if the console is only opened through select, it is only performed the first time something is completed. This avoids having to pass an argument to get_font() to make it use the monospace font regardless of selectable_items.
Proposed in #15176, I don't know if this is wanted.
Fixes #15176.
=> console.lua: default to a proportional font for select

DOCS/man/osc.rst
Fixes: a80f535a6dfc889dc32c9984e25d5c60ae906d05
=> DOCS/man/osc: remove non-existent options

DOCS/man/lua.rst
Lua doesn't have this comment syntax.
=> DOCS/man/lua: correct example syntax

video/mp_image.c
Fixes: 9b571a7aa711b9587e6acf68572e2003e2ddd51e
=> video/mp_image: fix original param copy implementation

DOCS/interface-changes/stats-sizes.rst, DOCS/man/stats.rst, player/lua/stats.lua
Currently --script-opt=stats-font_size=n is much bigger than --osd-font-size=n, which can confuse users, so calculate sizes the same way.
The \fs value to replicate --osd-font-size is
${osd-font-size} * 288 / 720 with --osd-scale-by-window, and \fs${osd-font-size} * 288 / ${osd-height}
with --osd-scale-by-window=no. This is because
sub/osd_libass.c:update_playres() sets
track->PlayResY = ass->res_y ? ass->res_y : MP_ASS_FONT_PLAYRESY, where MP_ASS_FONT_PLAYRESY is 288.
This also works with persistent_overlay=yes.
{\fscx100}{\fscy100} would also replicate --osd-font-size with show-text and with osd-verlay + --osd-scale-by-window, but not with osd-overlay + --osd-scale-by-window=no.
The default font and border sizes are multiplied by 720/288 = 2.5 to keep them the same as before.
=> stats.lua: calculate sizes like --osd-*-size options

DOCS/compatibility.rst, DOCS/man/osc.rst, README.md, etc/restore-old-bindings.conf, etc/restore-osc-bindings.conf, meson.build
The OSC changed to use select.lua for various tasks, resulting in a significant change in user interaction. This adds a config file which records OSC behavior changes so that the old behavior can be restored.
Fixes: https://github.com/mpv-player/mpv/issues/15176
=> etc/restore-osc-bindings.conf: add file to restore old osc bindings

player/lua/console.lua
This is more accurate, especially with an always visible OSC bottombar.
=> console.lua: refine the hovered item calculation

options/options.h, player/configfiles.c, player/main.c
=> player: don't load encoding mode profile twice

DOCS/man/input.rst, input/input.c, input/input.h, player/command.c
Fixes various issues with the `keybind` command.
=> input: fix keybind command

DOCS/man/input.rst, DOCS/man/lua.rst
It comes up often in IRC and issues that users don't understand why the path property is initially unavailable, so document it.
=> DOCS/man/input: note that properties can be unavailable on init

options/m_option.c, options/m_property.c
Some properties, like `${decoder-list}`, are resource-intensive to expand. Prevent fuzzing from generating strings with excessive expansions to encourage shorter test cases.
Expanding properties on each playback frame for `osd-msg1` can be demanding. However, in regular use cases, this typically isn’t an issue, so implementing a caching solution wouldn’t be practical in real scenarios.
Fixes timeouts on OSS-Fuzz.
=> m_property: stop expanding strings after 10 properties during fuzzing

video/out/w32_common.c
Make sure the window is at the correct position when fullscreen while geometry is set.
Fixes: e5159de8118120163689c27f5cbc1ec68c2d27c8
Fixes: https://github.com/mpv-player/mpv/issues/15238
=> video/out/w32_common: always move window when setting state

.luacheckrc, DOCS/man/javascript.rst, DOCS/man/lua.rst, player/lua/auto_profiles.lua, player/lua/defaults.lua
commit 1: defaults.lua: add an exit() function
Scripts can terminate execution by setting mp.keep_running = false. Add an exit() function to wrap setting mp.keep_running and properly expose this feature. It can be used e.g. by a thumbnail script to spawn workers with load-script and then let them quit.
It is not added to the mp namespace as mp.exit because that would make it look like it terminates mpv.
commit 2: auto_profiles.lua: actually exit when no auto profiles are defined
Unsetting _G.mp_event_loop at the top level quits the script, but not within callbacks. Use the new exit() function instead. Fixes e2284fba18.
This actually has an edge case since e2284fba18 where you can add auto profiles only later with load-config-file and the script stays unloaded, but it's still reasonable to …
=> defaults.lua: add an exit() function

osdep/terminal-dummy.c
c2ed2e7 introduced the terminal_set_mouse_input function to various terminal backends, but overlooked the dummy backend.
This causes linking errors when trying to build on platforms with no terminal, as vo_kitty and vo_tct are unconditionally enabled and make use of that function.
=> osdep/terminal: fix dummy implementation

video/out/w32_common.c
Maximized state is not allowed without WS_OVERLAPPEDWINDOW style and doesn't stick. Set the style after.
Fixes: #15093
=> w32_common: update window style after changing maximized state

player/command.c
If a script registers hooks before exiting mpv logs "Sending hook command failed. Removing hook.". (Also there is no function to unregister hooks.) Don't register hooks in auto_profiles.lua before it exits to not log these warnings. Fixes 5dc4047415. Fixes #15244.
=> player/client: reduce log level for hooks not sent to clients

.github/workflows/build.yml, DOCS/interface-changes/target-hint.txt, DOCS/man/options.rst, meson.build, video/out/drm_atomic.c, video/out/drm_common.c, video/out/drm_common.h, video/out/gpu/context.h, video/out/opengl/context_drm_egl.c, video/out/vo_gpu.c, video/out/vo_gpu_next.c, video/out/wayland_common.c
Somebody please actually test since I have no actual hdr capable monitors. There's also a `HDMI_EOTF_TRADITIONAL_GAMMA_HDR` enum in there but I have no idea what on earth that was supposed to be so I ignored it.
Also not sure if any existing `--drm-format` options are capable enough here.
=> context_drm_gl: add support for hdr metadata

audio/out/ao_coreaudio.c, audio/out/ao_coreaudio_exclusive.c, audio/out/ao_coreaudio_properties.c, audio/out/ao_coreaudio_utils.c, osdep/mac/compat.h, osdep/mac/swift_compat.swift, osdep/mac/type_helper.swift, video/out/hwdec/hwdec_mac_gl.c, video/out/mac/common.swift
just some cleaning up. only tested the macOS 12 deprecation fixes as much as i could, but didn't actually build it on macOS 11 with the corresponding SDK.
OpenGL deprecations are only silenced for the (objective-)c parts. they sadly can't be silenced in swift.
alternative to #9045
=> mac: fix or silence several deprecations

player/lua/osc.lua
Observing playlist property with "native" type is too expensive for
larger playlists, and we only observe this property to
activate/deactivate next/prev buttons on the osc. We actually only need
to know if the playlist-count has changed, nothing else.
Fixes: https://github.com/mpv-player/mpv/issues/15264
=> osc.lua: observe playlist-count instead of playlist property

.github/ISSUE_TEMPLATE/2_bug_report_linux.yml, .github/ISSUE_TEMPLATE/2_bug_report_macos.yml, .github/ISSUE_TEMPLATE/2_bug_report_windows.yml, .github/ISSUE_TEMPLATE/3_bug_report.yml
Currently it asks which version introduced the problem, but users are unlikely to know if they don't update and test every single version released, and this field is rarely filled in practice by non-developers.
On the other hand, it's much easier to recall the last working version that they have used before.
So ask for the last known working version, which is useful information for developers to narrow down bisecting range.
=> github/issue_template: ask for last known working version 

ci/build-win32.ps1
The same as 87826224a296d744a8add8b8dc47b0c5713b453f.
=> ci/win32: restrict shaderc version to fix build errors

options/options.c
See https://qoiformat.org/
The format is supported by ffmpeg and can be opened in mpv as expected
=> options: add .qoi to the list of image extensions

DOCS/man/input.rst
Most of the commands list here are several years old and we will probably never change them. And it is already stated in the description of individual commands if they are deprecated or subject to change.
Furthermore, it is easy to add new commands at the end of this section by accident. I added load-config-file and load-input-conf here without realizing it's a separate section, and I assume this was also the case for begin-vo-dragging.
=> DOCS/man/input.rst: remove input commands subject to change heading

sub/osd_libass.c
High --osd-blur values break the osd-bar by not drawing the filled portion, and even low values just make it look worse, so don't apply --osd-blur to the osd-bar.
=> sub/osd_libass: don't blur the osd-bar

video/out/gpu/video.c
https://github.com/mpv-player/mpv/commit/82231fd74d173fb47845dd086d360bceb3e5fc17 mentioned that for the "rot" transform flip=true must be set, which "makes no sense at all".
The reason this is happening is that the rotation matrix calculation is only valid for the 2D coordinate system where y axis is 90 degrees counterclockwise from x axis, but the coordinate system of chroma offset has its origin at top-left so it is the opposite, which results in the rotation going to the opposite way. Setting flip=true fixes the rotation direction, but results in a flipped y coordinate.
Fix this by reversing the rotation angle for chroma offset rotation matrix calculation. This also allows removing some duplicated code.
Fixes: https://github.com/mpv-player/mpv/issues/15288
=> video/out/gpu/video: fix chroma offset rotation matrix calculation

player/javascript/defaults.js
The opened event doesn't send any arguments. Don't call JSON.parse(undefined) in that case because it errors.
Fixes eb4c6be630, fixes #15301.
=> defaults.js: fix the opened event with mp.input.get

player/command.c
It already prints %, so no need for /100. Also use print helper while at it.
=> player/command: remove /100 from sub-pos print

input/input.c
With scalable input source, scale_units can be 0, and cmd is not freed. Fix this by freeing cmd when scale_units is 0.
Fixes: 937128697fbbef6b21e2d23a4785f1334f62b9e3
=> input: fix memory leak with scalable input and nonscalable commands

input/cmd.c
--input-cmdlist crops playlist-next-playlist, playlist-prev-playlist, write-watch-later-config and delete-watch-later-config, so increase the string length to that of the longest command.
Also stop specifying both the minimum and maximum length since they are the same.
=> input/cmd: increase the command length for --input-cmdlist

meson.build
Windows SDK 10.0.26100.0 defines the NAN macro in a non-constant manner. This violates the C/C++ standard and breaks the compilation of initializers with Clang.
See:
https://developercommunity.visualstudio.com/t/NAN-is-no-longer-compile-time-constant-i/10688907
=> meson: define _UCRT_NOISY_NAN to workaround the non-constant NAN define

player/lua/console.lua
With --osd-border-style=opaque-box and background-box, respect --osd-shadow-offset.
I am not sure if --osd-shadow-offset should be inherited with --osd-border-style=outline-and-shadow, especially since it doesn't let you specify different x and y offsets.
=> console.lua: don't override the offset of opaque boxes

common/playlist.c
If the playlist is loaded directly from a protocol like memory://, the playlist_path represents the entire playlist. In cases where we have a large playlist, this results in the entire playlist being duplicated for each item. For example, if the input size is 300 kB with 10k items, we end up using 3 GB of memory just to store the playlist_path strings.
=> common/playlist: don't allocate duplicated playlist_path

options/options.c, options/options.h, stream/stream_dvdnav.c, sub/osd.c, sub/osd.h, sub/osd_libass.c, sub/sd.h, sub/sd_ass.c
Move several option definitions to the respective modules and use common prefix if possible.
=> options.c cleanup

DOCS/man/input.rst
mpv has too many commands and they are unorganized in the documentation, making it difficult to navigate.
This commit completely reorganizes the commands into several categories to make the documentation easier to navigate.
The following categories are defined:
- Playback Control: Seeking and stepping.
- Property Manipulation: Changing property values.
- Playlist Manipulation: Playlist navigation and editing.
- Track Manipulation: Track navigation and editing.
- Text Manipulation: Text printing, expansion, escaping.
- Configuration: General configuration and related files.
- OSD: Displaying contents as OSD.
- Input and Keybind: Input configuration and key bindings.
- Execution: Execution of mpv and subprocesses.
- Scripting: Script loading and communication.
- Screenshot: Taking …
=> DOCS/man/input.rst: add sections to categorize commands

player/lua/console.lua, video/out/wayland_common.c
This resolves a feature request that I made, in https://github.com/mpv-player/mpv/issues/15330 ; the issue gives more background and motivation.
To test: in a Wayland session, run mpv under a tool that sets WAYLAND_SOCKET, like `waypipe` with the `--oneshot` flag, or using the attached test script: [wldisplaytosocket.py.txt](https://github.com/user-attachments/files/17792476/wldisplaytosocket.py.txt). With this PR, `./wldisplaytosocket.py mpv path/to/video` should now behave the same as `mpv path/to/video`.
=> console.lua,wayland_common: also detect Wayland if WAYLAND_SOCKET set

osdep/mac/compat.h, osdep/mac/swift_compat.swift, video/out/mac/common.swift
the swift parts can't be nicely encapsulated in the compat file because it lags proper target version compile time checks.
Fixes #15292
=> mac/compat: fix compatibility for deployment targets lower than SDK ver

audio/filter/af_lavcac3enc.c, audio/out/ao_lavc.c, misc/lavc_compat.h, video/image_writer.c, video/out/vo_lavc.c
See: https://github.com/FFmpeg/FFmpeg/commit/3305767560a6303f474fffa3afb10c500059b455
Someone had to do janitorial work... sigh.
=> various: use avcodec_get_supported_config() to resolve deprecation warn

video/out/wayland_common.c, video/out/wayland_common.h
Whenever mpv window gains focus, a new data offer is sent for the selection. However, mpv currently treats it the same as dnd data offers, which results in wrong handling. One bug which results from this is when focus follow mouse is enabled, dropping the dnd file results in the window being focused and selection offer being sent, freeing the existing dnd offer. This results in dnd being broken on at least GTK3.
Fix this by separating selection and dnd offer handling. Since there is no way to know whether an offer introduced by data_device_handle_data_offer is a selection or dnd offer, make it pending, and move them once the identity is confirmed.
Fixes: https://github.com/mpv-player/mpv/issues/9789
Fixes: https://github.com/mpv-player/mpv/issues/13498
=> video/out/wayland_common: fix dnd with focus follow mouse

player/lua/console.lua
console.lua: strip multiple lines in selectable items
If an item contains newlines, it hides the top items. This is often the case for sub-ass-extradata and metadata/ytdl_description in the property list. So keep only the first line.
console.lua: limit the length of selectable items
Giving very long lines to libass freezes mpv and makes the CPU spin (though it's fine with terminal output). This is often the case user-data/mpv/ytdl/json-subprocess-result in the property list. So limit the length of selectable items to 300 characters (not Unicode aware). This is enough to fill a 1920x1080 window with font_size=16 and Japanese text.
=> console.lua: select fixes

.github/workflows/build.yml, ci/lint-commit-msg.py
Latter is now available, and pkg-config as a package has been deprecated.
Additionally, attempt to work around recent GHA image breakage.
=> github/workflows: switch from pkg-config to pkgconf for macOS and Ubuntu mingw-w64

player/loadfile.c
This fixes `ytdl_hook`, which would start playback with the thumbnail track selected. This issue occurs because the thumbnail track is added first. If the main track is not marked as default afterward, which it isn't for single streams, the first track (the image track) would be selected.
In general, if a non-image track is available, it should be preferred.
=> player/loadfile: prefer non-image when selecting video track

video/out/vo_gpu_next.c
Fixes: ef6052c01e323cece4ace135a1724fd09f86c86d
=> vo_gpu_next: fix mp_image colorspace with some hwdecs

DOCS/man/console.rst, player/lua/console.lua
console.lua: determine completions with fuzzy search
For example, set vo gn<Tab> will complete to gpu-next.
console.lua: complete fewer properties
10k properties makes the console hang and the CPU fan spin with live fuzzy filtering, so print fewer sub-properties. These are rarely useful anyway.
console.lua: show completions as you type
Show available completion suggestions as you type without having to press Tab.
This is fast even on a 2011 CPU, so we can get away with doing this in the same thread that draws the console. The one case where it could make the console hang is file completion of network drives, but in general it is convenient for loadfile.
mp.input.get clients also get a request to complete on each character typed, but those run in a different thread so performance is always …
=> console.lua: implement real-time fuzzy autocompletion

DOCS/man/mpv.rst
The previous documentation was pretty scary and misleading, and was also outdated in several sections.
It was also difficult to understand some of the paragraphs.
The path documentation has now been overhauled to be easier to understand and to document the latest mpv behavior.
This change documents the fact that there's no difference between `~~/foo` and `~~home/foo` in terms of that "scary bug". They both use the exact same code and have the same `--no-config` "bug" behavior.
References:
- [--no-config](https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst#program-behavior)
- [old docs which makes it sound like ~~/ is buggier than ~~home/](https://github.com/mpv-player/mpv/blob/master/DOCS/man/mpv.rst#paths)
- [code proof that both actually behave *identically* when falling …
=> DOCS/man/mpv: improve path docs and clarify config-dir path behavior

video/out/wayland_common.c
If we lose the current output for any reason (unplug, turns off, etc.) and then later it comes back, mpv should always recalculate all the scaling stuff. The optimization to avoid needless scaling calculations didn't consider this case and would always exit since the scaling is the same. So just check wl->current_output's existence as well.
Fixes #15361.
=> wayland: always recalculate scaling if wl->current_output is not set

video/mp_image.c
It turns out mpv doesn't tag at all when doing conversions, so we just re-tag here and hope for the best. This should be improved, but there are many different code paths when conversion can happen, so for now revert to previous behavior.
Fixes: 4e5cc9cf1dd7471eca3c9c43c60fbf680dea2aa6
=> mp_image: always force RGB formats to full-range RGB

player/lua/console.lua
2f271a92de made it so that the first completion suggestion is automatically selected when pressing enter, but that was done after saving the command in the history. Save it to the history after expanding it, so re-running the previous command actually works, e.g. save "set vo gpu-next" instead of "set vo gn".
=> console.lua: save commands in history after autocompletion

player/lua/console.lua
...and after navigating the history.
I thought of making the new function accept the new cursor position and set it, but it would not be clear that you're only supposed to call it when handle_edit() is not already called.
=> console.lua: update completions after moving the cursor

player/lua/console.lua
After pressing Tab a space is usually appended after the suggestion, and with the new autocompletion you have to enter a space again before seeing the completions for the next token even when there is only 1 matching completion. Just don't append spaces and let the user manually type 1 space after completion, which is more intuitive.
=> console.lua: don't append spaces after completion

DOCS/interface-changes/selected-style.rst, DOCS/man/options.rst, misc/bstr.h, options/options.c, options/options.h, osdep/terminal.h, player/command.c, player/lua/console.lua, player/misc.c, video/out/gpu/shader_cache.c, video/out/vo_tct.c
Instead of printing circles in show-text ${playlist}, ${chapter-list} and ${edition-list}, introduce --osd-selected-color and --osd-selected-outline-color to reduce clutter, make the selected item easier to differentiate, and have visual consistency with select.lua.
The defaults are taken from the style of the selected item in the console. These new options are also used there, replacing the hardcoded styles. Due to being user-configurable, selected item styles are changed to take priority over default item styles.
The default selected style is yellow and bold. The bold (hardcoded) allows differentiating the selected item with color blindness. There is also a separate --osd-selected-outline-color option defaulting to black, since without it if the user changes --osd-outline-color yellow …
=> command: highlight selected list items with color

DOCS/man/input.rst, video/out/mac/common.swift, video/out/mac/view.swift, video/out/mac/window.swift
only works with left clicks.
overlooked by me and follow up of #13582.
also resolves the possible blocker on #15314.
tested with `MBTN_LEFT cycle pause` and works as expected now. 
also tested with following test script that dragging can be triggered by a script with different binding.
```
local mp = require 'mp'
local function vo_drag()
mp.command("begin-vo-dragging")
end
mp.add_forced_key_binding('alt+MBTN_LEFT', vo_drag, {complex=true, event=down})
```
=> mac: implement VOCTRL_BEGIN_DRAGGING

DOCS/man/osc.rst, etc/restore-osc-bindings.conf, player/lua/osc.lua
Alternative to #15186. To not complicate things and make it easier to transition form previous bindings.
=> osc.lua: cycle sub/audio on left-click, select on right-click

DOCS/interface-changes.rst
This has been happening for a while now apparently, so change it to accurately reflect reality. I chose the next release as the point to formally make this change, because I was under the impression that we didn't have to list new options so I never did it and there may be others like that too.
=> DOCS/interface-changes: specify that new additions have to be listed

DOCS/interface-changes/clipboard.txt, DOCS/man/input.rst, DOCS/man/options.rst, meson.build, options/m_option.h, options/options.c, options/options.h, player/clipboard/clipboard-vo.c, player/clipboard/clipboard-win.c, player/clipboard/clipboard.c, player/clipboard/clipboard.h, player/command.c, player/core.h, player/lua/console.lua, player/main.c, player/playloop.c, video/out/vo.h, video/out/wayland_common.c, video/out/wayland_common.h
Alternative to https://github.com/mpv-player/mpv/pull/13837.
This adds a general internal clipboard API with support for different formats, targets, and autoprobing backends, and implements 2 clipboard backends (win32and VO) and Wayland support for the VO backend. The clipboard can be interacted publicly with the `clipboard` property, with change notification support. The internal API provides a polling interface for clipboard backends which use polling for notification. Other backends monitors changes in the backgrounds and notify the property when changes are detected.
Currently, only text format and clipboard target is implemented, but image formats and primary selection target can be added later. 
`console.lua` is changed to use the clipboard property when supported. 
Fixes: …
=> win32, wayland: add clipboard support

DOCS/interface-changes/script-binding-scalable.txt, DOCS/man/input.rst, DOCS/man/lua.rst, input/cmd.h, player/command.c, player/javascript/defaults.js, player/lua/defaults.lua
This makes `script-binding` command and key bindings added by `mp.add_key_binding()` scalable. The script-message command now has an extra argument with the scale of the key.
=> command: make script-binding command scalable

player/clipboard/clipboard.c, player/clipboard/clipboard.h
This header should not be included except when really needed.
Fixes: e1d30c4c5a7443d08c7d4c183644917a340954b2
=> player/clipboard/clipboard: don't include global.h in header

video/filter/vf_format.c
If p->colormatrix is 0 if not set by user, so it would always override _orig parameters with Dolby Vision ones and restore that erroneously.
Fixes: e2365bfeceeef8939d159780b607698d05073910
=> vf_format: fix format=dolbyvision=no metadata stripping

sub/sd_ass.c
mkvtoolnix recently introduced this mimetype in https://gitlab.com/mbunkus/mkvtoolnix/-/commit/d858c2bf138009b8316b32c4554397ecb609d938 which is available since the version 88.0, so I tought we would also need it.
=> Add ``application/x-font-otf`` to font_mimetypes

DOCS/interface-changes/gamma-factor.txt, DOCS/man/options.rst, video/out/gpu/video.c
=> vo_gpu: undeprecate --gamma-factor and --gamma-auto

player/command.c
Using 3 %x in a row can produce colors like 0ff0 which are interpreted incorrectly, so ensure each colors has 2 digits.
=> command: fix --osd-selected{,-outline}-color

osdep/mac/app_bridge_objc.h, osdep/mac/option_helper.swift
looked into all the OpaquePointers and additional to `mpv_global` we only use these structs that are all private: [struct mpv_handle](https://github.com/mpv-player/mpv/blob/master/player/client.c#L106-L161),  [struct input_ctx](https://github.com/mpv-player/mpv/blob/master/input/input.c#L99-L168), [struct mpv_render_context](https://github.com/mpv-player/mpv/blob/master/video/out/vo_libmpv.c#L60-L112), [struct mp_log](https://github.com/mpv-player/mpv/blob/master/common/msg.c#L100-L109).
so there actually is nothing else to do besides what was already done in #15395. had to open a new PR because github didn't like me force pushing to the same branch when the PR was closed.
=> mac/option: explicitly include and define type of global init variable

player/lua/defaults.lua
A client's input sections are destroyed along with it since bf385e1140.
=> defaults.lua: remove outdated comment

player/lua/console.lua
run completion on Windows is slow because system32 contains thousands of DLLs, so filter executables with an extension in PATHEXT.
=> console.lua: don't complete DLLs on Windows

player/lua/console.lua
This avoids inserting the characters in front of the cursor again when completing to text already in front of the cursor.
This is important after 2f271a92de made Enter automatically insert the first completion.
=> console.lua: don't reinsert the next characters on complete

demux/demux_lavf.c, demux/demux_mkv.c, demux/stheader.h
This process has been deprecated since avformat 60.15.100 and
since avcodec 60.30.101 AV_PKT_DATA_DOVI_CONF has been read from
AVCodecContext's coded_side_data. Additionally, the HEVC decoder
is the only one which currently reads this side data from packets,
the native AV1 decoder as well as the libdav1d wrapper instead only
support the newer propagation method via codec context's side data.
How this currently is supposed to propagate is:
* demuxer copies the codec parameters into sh_stream's lav_codecpar.
* {ad,sd,vd}_lavc call mp_set_avctx_codec_headers that calls
avcodec_parameters_to_context, which then sets global side data
to the codec context.
As this logic is already in place, so no additional changes are required
for things to work and the deprecated function call can just be …
=> demux: remove AVPacket global side data injection

DOCS/interface-changes/video-recenter.txt, DOCS/man/options.rst, options/options.c, options/options.h, video/out/aspect.c
This resets ``--video-align-x`` and ``--video-align-y`` to 0 when the video becomes smaller than the OSD in the respective direction, e.g. by zooming out.
Unlike doing this by observing osd-dimensions in a script, this is done before rerendering, so you don't see the image being rendered not centered for an instant after zooming out before being rerendered centered.
Defaults to yes.
=> aspect: add --video-recenter

player/lua/console.lua
Actually update the rendered text when typing with an input.get client that didn't specify a complete callback.
Fixes #15430, fixes 57b73f1af6.
=> console.lua: fix mp.input.get clients that don't specify completions

.github/workflows/lint.yml
See: https://github.com/ChartBoost/ruff-action/commit/c413c59d2aa0f58662aec40228cd7c8dfb69cbc1
=> github/workflows: replace ruff-action with a maintained one

DOCS/man/input.rst, demux/demux_disc.c, stream/stream.h, stream/stream_bluray.c, stream/stream_dvdnav.c
This allows to select DVD/Blu-Ray title easily. Titles are listed as
editions with their duration and number.
I wanted to include Angles also in this selection, but currently Angles
are not that well supported, so let's stick with titles and leave the
rest for the future changes.
We might migrate to lavf demuxer for DVD/Blu-Ray in the future, the mpv
implementation is rotted anyway.
Fixes https://github.com/mpv-player/mpv/issues/14586
=> demux_disc: expose titles as editions

osdep/io.c
This PR makes `mp_make_wakeup_pipe()` work on Windows, as discussed in #14933.
Note: I do not aim to undeprecate the C API, but only to undeprecate the Lua API and make it cross-platform. I do not deny that there are workarounds to achieve the purpose (i.e. custom event loop), but IMO making the existing API cross-platform is simplest and most straighforward.
Sample Lua code for testing (work on both Windows and POSIX):
```lua
local uv = require('luv')
local fd = mp.get_wakeup_pipe()
local h = uv.new_pipe(false)
h:open(fd)
h:read_start(function(err)
if err ~= nil then
error(err)
end
print("waken up")
mp.dispatch_events(false)
end)
function _G.mp_event_loop()
while mp.keep_running do
uv.run("once")
end
end
```
=> io: support `mp_make_wakeup_pipe()` on Windows

meson.build, osdep/mac/meson.build
Use swiftc instead of swift for building on macOS. This is requested in https://github.com/mpv-player/mpv/issues/13608.
The compile has been tested and successfully passed on M1 Air running Sequoia 15.1.1(Swift version 6.0.2).
Ref doc: https://github.com/swiftlang/swift/blob/main/docs/Driver.md
=> meson: use swiftc instead of swift for building

options/m_option.c, options/m_option.h, video/out/win_state.c
This fixes geometry uses where it is expected to be centered. For example this fixes video-crop option.
Fixes: e01eab4385d8fe6a542dd9526f912e37b691f58e
Fixes: #15398
=> options/m_option: restore m_geometry_apply centering ability

common/encode_lavc.c, options/m_option.h, options/options.c
This makes things more readable.
=> options: remove old compatibility definitions

player/configfiles.c
With --ignore-path-in-watch-later-config the basename of files is used for watch later files, but since 1d640c9887 this was checking the wrong variable to determine if the file is a URL and thus also taking the basename of URLs, when URLs should use the full path regardless of this option.
=> configfiles: don't use the basename of urls

DOCS/interface-changes/console-margins.txt, DOCS/man/console.rst, player/lua/console.lua
Allow configuring the margin from the bottom indipendently of --osd-margin-y.
Fixes #15478.
=> console.lua: add margin script-opts

options/m_option.h
Update flags are often updated, so make space for expand them. Reorder all values to make it easier to add new ones, untill there is no more space.
=> m_option: put UPDATE_ flags at the beginning

player/lua/console.lua
These are easier to read with _ between words. Also screenx/y could be assumed to be display coordinates, so rename them to osd_w/h. They are not named osd_width/osd_height to avoid Redefined local LSP warnings with the ones in the upper scope.
=> console.lua: rename dimension variables

DOCS/interface-changes/osc-fadein.txt, DOCS/man/osc.rst, player/lua/osc.lua
Fade in is already implemented, so I enabled it.
Is there a reason it's already implemented but not currently used?
=> osc.lua: add option to enable fade-in effect

video/out/vo.c
First two commits are entirely theoretical, it's more correct but it probably doesn't matter much because this code is only used to detect underruns and to wait for a frame to finish before applying new image_params.
Third commit fixes a real world problem with bad drivers that I encountered while testing various wip fifo-v1/commit-timing implementations. By not always updating base_vsync, we could potentially end up in a [permanent underflow state](https://github.com/mpv-player/mpv/blob/a61518db986dcd4babfae66cef017010a9eb5c88/video/out/vo.c#L461-L470) and never recover from it even once the driver has stopped giving us bogus values.
=> Misc display sync fixes

player/lua/osc.lua
Stop setting the z of the OSD overlay. This prevents the console from being drawn below the box layout when clicking buttons with visibility=always.
This reverts 9c22d6b438 and 86d24b069b.
=> osc.lua: don't place the overlay above other ones

sub/osd.c, sub/sd_lavc.c
Previous fixes in bcc3d72 make subtitles on videos with non-square pixel aspect ratios appear incorrect. This can happen on subtitles for SD Blu-rays where the video resolution is 720x480 but the aspect ratio is 4:3. The scaling still applies when the video frame is cropped with filters so the previous fix will still work.
Fixes #15415.
=> sd_lavc: apply video PAR to PGS subtitles

audio/out/buffer.c, player/audio.c
See commits. Basically alsa was bugged with different samplerates in a playlist since probably b74c09efbf7c6969fc053265f72cc0501b840ce1 but it was not noticed because most people's devices probably default to the highest sampling rate, resample anything upwards, and that is used throughout the entire playlist. To test, you would need to specify `--audio-device` since it seems using `auto` (or `default` as it is internally called in alsa) is different and happens to work in a way that doesn't have this problem.
=> alsa edgecase fixes

demux/ebml.c, options/m_property.c, options/options.c
For OSS-Fuzz.
See: 2054d872d48f315d4658f0871d914061a35eda2a
=> m_property: stop processing after 10 properties even in skip cases

DOCS/man/osc.rst, player/lua/osc.lua
Sort mbtn script-opts according to how they are shown to the user in bar layout instead of how they are defined in osc_init().
=> osc.lua: move title mbtn script-opts below playlist_next's

DOCS/man/osc.rst, etc/restore-osc-bindings.conf, player/lua/osc.lua
osc.lua: open the playlist selector when right clicking playlist arrows
- It makes more sense to select a playlist entry from the buttons that navigate the playlist than from the title
- Provides different bindings for right and middle click
- Mirrors chapter button bindings
osc.lua: show the full path when right clicking the title
Right clicking playlist arrows already opens the playlist selector so bind something else to right clicking the title. Make it show the full path which is useful but not bound anywhere on either the keyboard or the OSC.
DOCS/man/osc: sort mouse bindings consistently
Always list in the order left shift+L middle right click.
=> osc.lua: update mouse bindings

player/lua/select.lua
MKVs have 1 edition by default so don't show an empty edition selection in that case.
=> select.lua: abort edition selection when there's only 1

player/lua/osc.lua
When track IDs are auto mp.get_property_native() returns "auto", but mp.get_property_number() returns nil.
Follow up to 1a558bf5c2 and 897c04afe1.
=> osc.lua: simplify track ID retrival

demux/demux_lavf.c
Like 565e7d906c did for avif, consider 1-frame HEVC as images, as HEVC videos have nb_frames 0 or > 1.
Specifically, in the FATE suite:
nb_frames = 0 and are images:
cbf_cr_cb_TUDepth_4_circle.h265 food.hevc hdr10_plus_h265_sample.hevc hdr_vivid_h265_sample.hevc hevc-monochrome.hevc
nb_frames = 0 and are videos:
mv_nuh_layer_id.bit paired_fields.hevc
paramchange_yuv420p_yuv420p10.hevc pir.hevc
nb_frames > 0:
dv84.mov extradata-reload-multi-stsd.mov multiview.mov two_first_slice.mp4
As with other video codecs, the hevc images with nb_frames = 0 which are really frames cut from a video are not detected as images, but you will only find these files in FATE.
=> demux_lavf: detect heif/heic as images

demux/demux_lavf.c
AV_DISPOSITION_TIMED_THUMBNAILS was added in FFmpeg 3.2 and AV_DISPOSITION_STILL_IMAGE in FFmpeg 4.1, and we require FFmpeg 6.1.
=> demux_lavf: remove obsolete defines

player/lua/ytdl_hook.lua
According to yt-dlp empty proxy is used to disable proxy setting `Pass in an empty string (--proxy "") for direct connection`. Currently ytdl_hook.lua don't pass any empty args.
mpv currently translate
`mpv --ytdl-raw-options=proxy= https://music.163.com/song?id=28754103`
into
`/usr/bin/python /usr/bin/yt-dlp --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --proxy --sub-langs all --write-srt --no-playlist -- https://music.163.com/song?id=28754103`
with nothing provided to `--proxy`. This end up an error.
```
[ytdl_hook] ERROR: [netease:song] 28754103: Unable to download JSON metadata: ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x774e8f8c8500>: Failed to establish a new connection: [Errno -2] …
```
=> empty proxy should be passed

meson.build
the previous check was incorrect since because drmGetDeviceFromDevId is only available since 2.4.109.
https://gitlab.freedesktop.org/mesa/drm/-/commit/57e0b0552e11b3f04e6d5704c1c7efea5f83ffe4
Fixes: 0d7b4d64a5ec9b9ef132c07c1fb6712b1653101f
=> meson: bump libdrm version to 2.4.109

sub/sd_ass.c
Saving old playresx method is incorrect for the first draw after the subtitle is loaded.
Fixes: f862d3b6cd66abee98f2af21c36255ef7361cb80
Fixes: https://github.com/mpv-player/mpv/issues/15523
=> sd_ass: fix fix_margins calculation

player/lua/console.lua
Currently if you change --osd-selected-color the preselected item stays yellow and can't be changed. Since the default item style was just chosen from the selected color without the bold, also make the default item follow --osd-selected-color.
Requested in
https://github.com/Samillion/ModernZ/issues/259#issuecomment-2556608926.
=> console.lua: color the default item with --osd-selected-color

DOCS/man/mpv.rst
Modified the man page.
There were two pairs of key bindings that appeared in one order but the description of what they do appeared in the reverse order. Modified the description to match the order in which the keys appear.
Note: I have not tested this change.
=> DOCS: fix description of subtitle delay adjustment

player/lua/console.lua
Stop overriding the OSD font and outline color in the console input line and log, except for the lines already in a different color. This allows configuring the console color and makes it consistent with the rest of the OSD, like 51bd00c33a did for stats.
=> console.lua: inherit --osd-color and --osd-outline-color

player/lua/stats.lua
This doesn't work for changing page key script-opts at runtime because they are used as the indexes of the pages variable, but nothing actually breaks if you do, it just uses the initial values. This is still useful for conditionally changing sizes at runtime or for trying out the osd-box profile by applying it from the console.
=> stats.lua: enable runtime script-opt changes

video/out/x11_common.c, video/out/x11_common.h
There were a few pitfalls with the way this was previously implemented because --geometry implicitly depended on --auto-window-resize being enabled to operate in a few cases. Instead, let's change the logic a bit so that instead we choose whether or not to reuse the old rc (i.e. don't resize) and use the wh_valid and xy_valid fields within the m_geometry struct instead of using x11->geometry_change. This fixes several edge cases involving setting the position with --geometry when using --auto-window-resize=no.
=> x11: simplify --geometry and --auto-window-resize logic

DOCS/contribute.md
something that should be discussed. this is only meant for Apple Platforms and should not affect other Platforms. right now we don't have any 'official' guidelines how to deal with newly added code for swift/obj-c. personally i would like to avoid an even bigger mix of obj-c and swift in the future and my goal is to eventually have no/nearly no obj-c code anymore.
some random points:
- i put a great amount of work into migrating a lot of the osdep code to Swift and refactoring it at the same time, trying to decrease complexity and code amount
- currently all video backends/contexts are majorly written in swift
- swift was made mandatory for a fully working mpv build
- the swift parts have been in wide use for many years now and seem pretty stable
- swift itself got ABI stable with version …
=> [RFC] DOCS/contribute.md: add guidelines for Swift and Objective-C

DOCS/man/ao.rst
was forgotten in initial implementation 8 years ago 3f5b41d.
=> DOCS/ao: add missing documentation for audiounit

osdep/mac/meson.build
similar to how our config.h is created the feature flags added to the swift build should be generated from our features array, instead of manually adding those when needed.
this prevents errors when forgetting to add any needed flags or remove obsolete ones.
also removes a bit of complexity and LOC.
=> osdep/mac/meson.build: dynamically add features to swift build flags

DOCS/man/input.rst, DOCS/man/options.rst, meson.build, osdep/mac/app_bridge_objc.h, osdep/mac/clipboard.swift, player/clipboard/clipboard-mac.m, player/clipboard/clipboard.c, player/lua/console.lua
follow up of #15355
maybe `osdep/mac/clipboard.swift` should be under a different location in `player/mac`, `player/clipboard` or `player/clipboard/mac`.
=> clipboard-mac: add macOS clipboard backend

video/sws_utils.c, video/sws_utils.h
This has been used before 2c43d2b75a88b8e0e8f0a715f993ffc1c8977d13. Now that we have also zimg support, using swscale directly may not be wanted depending on the user options.
=> video/sws_utils: remove unused mp_image_swscale

meson.build, osdep/mac/menu_bar.swift, video/out/mac/common.swift
1. after the cleanups and splits to the various other helpers, libmpv_helper is only ever used with cocoa-cb. so only build it with cocoa-cb
2. we have a dedicated function to check for bundle usage, so we should use it.
=> mac: minor cleanups

.github/workflows/build.yml, ci/build-win32.ps1
We build and ship this code, so it makes sense to make sure it is ok.
Tests for libass and libplacebo are explicitly enabled. The rest is in default state, so if tests are enabled by default, they will run.
FFmpeg tests and currently disabled, because they are failing on Windows. Once the patch is merged upstream, we can back-port it to our build. See: https://ffmpeg.org/pipermail/ffmpeg-devel/2024-December/337262.html
=> ci/win32: enable tests for dependencies

player/lua/console.lua
There is no need to override this for colored lines.
=> console.lua: keep --osd-{,outline}-color's alpha component for styles

DOCS/interface-changes/exts.rst, DOCS/man/options.rst, demux/demux_playlist.c, options/options.c, options/options.h
options: add --archive-exts
And add archive to --directory-filter-types' default.
Fixes #15550, fixes #15096.
options: add --playlist-exts
And add playlist to --directory-filter-types' default.
Fixes https://github.com/mpv-player/mpv/issues/15096#issuecomment-2466695186, fixes https://github.com/mpv-player/mpv/discussions/15508
=> options: add --archive-exts and --playlist-exts

player/lua/console.lua
The first completion is highlighted because it is automatically inserted when pressing Enter, but this isn't the case when the console is used with mp.input.get, and autoselecting it can be undesirable if you're entering arbitrary text, unlike with mpv commands where you're usually choosing from predefined lists. So just don't highlight the first completion for mp.input clients.
=> console.lua: don't highlight the first completion with mp.input.get

player/osd.c
Makes status line more stable, without variable width.
=> player/osd: use fixed width for vsync-ratio value in status line

etc/_mpv.zsh
It is annoying to type these over and over.
=> zsh-completion: complete av://lavfi:testsrc and av://lavfi:sine

player/video.c, video/out/vo.c, video/out/vo.h, video/out/vo_caca.c, video/out/vo_direct3d.c, video/out/vo_dmabuf_wayland.c, video/out/vo_drm.c, video/out/vo_gpu.c, video/out/vo_gpu_next.c, video/out/vo_image.c, video/out/vo_kitty.c, video/out/vo_lavc.c, video/out/vo_libmpv.c, video/out/vo_mediacodec_embed.c, video/out/vo_null.c, video/out/vo_sdl.c, video/out/vo_sixel.c, video/out/vo_tct.c, video/out/vo_vaapi.c, video/out/vo_vdpau.c, video/out/vo_wlshm.c, video/out/vo_x11.c, video/out/vo_xv.c, video/out/x11_common.c
This solves the problem mentioned [here](https://github.com/mpv-player/mpv/pull/15056#issuecomment-2538207435). If we skip rendering while the player is in display-sync mode, then there is no driver-level blocking which means mpv will go through the render loop unthrottled. Not good of course. On X11, I just ignored this problem and made it always render if we were using display sync. Wayland has its own blocking thing so it works there. So fix this by simply repurposing the already existing code path for audio sync when we hit this case. display sync is meaningless if the window is obscured and the audio sync stuff already handles all the appropriate throttling/timings for us.
=> fallback to audio sync logic if mpv window isn't visible

DOCS/man/vo.rst
=> DOCS/man/vo.rst: improve dmabuf-wayland documentation

stream/stream_file.c
To avoid all sorts of I/O loops.
=> stream_file: don't allow to open standard streams during fuzzing

player/lua/select.lua
In files other than MKVs edition-list is an empty table, not nil. It is current-edition that is nil.
However nil still needs to be checked to not crash with mpv --idle.
=> select.lua: fix select-edition crash on non-MKVs

DOCS/man/input.rst
I added RW to edition-list/N/id in 34f2143e8f because in #8077 it was assumed that it is writable from the wording of the docs. But what the docs actually meant is that you can retrieve edition-list/N/id and then use the retrieved value to set the edition property.
Remove RW and the ambiguous sentence.
=> DOCS/man/input: edition-list/N/id is not writable

sub/osd.h
OSD_STOP was never used.
OSD_BALANCE is unused since 3d27a0792b.
OSD_PB_* are unused since ef3c0e6eda.
=> osd: remove unused constants

DOCS/interface-changes/audiounit-exclusive.txt, DOCS/man/options.rst, audio/out/ao_audiounit.m
Using this option means the OS  won't pause other
sources of audio when playback starts in MPV.
This matches the behaviour on other platforms.
=> ios/macos: use non-exclusive audio session

DOCS/man/options.rst, video/out/mac_common.swift
(that's a lot less changes than i anticipated.)
This pull request includes a bug fix and adds support for a feature.
*****
1. In `Common::getWindowGeometry -> (NSRect, Bool)`
https://github.com/mpv-player/mpv/blob/dbb3291e8e9729fb3488a82e21622dafb5a68910/video/out/mac/common.swift#L440-L440
`Int32(VO_WIN_FORCE_POS)` is always a constant 1, irrespective of `--force-window-position`. As a result, whenever `--geometry` is passed, `forcePosition` is returned as 1.
You can easily verify this by:
a) Adding a breakpoint just before the return statement, or
b) Including a debug line such as `print("Bool", Bool(geo.flags & Int32(VO_WIN_FORCE_POS)))`
Then:
```
build/mpv --geometry=500:500 '/Users/neko/Downloads/test.mp4'
build/mpv --geometry=500:500 --force-window-position …
```
=> mac: add support for --force-window-position

player/lua/console.lua
When console is opened with selectable items and a default item, the default item is placed at the center. But if you type something and then clear the line, the first item becomes the selected one. Make it select the default item and place it in the center in this case too.
=> console.lua: focus the default item after emptying the input line

player/lua/console.lua
It was requested in
https://github.com/Samillion/ModernZ/issues/259#issuecomment-2556608926 to make console's shadow offset consistent with --osd-shadow-offset. Not specifying shadow offsets achieves that. This disables console's shadow by default but there is no reason console should default to having shadows but the rest of the OSD shouldn't. Users who want shadows can enable them in the whole OSD with --osd-shadow-offset. console-specific shadow_{x,y}_offset script-opts can be added if someone requests them later.
=> console.lua: inherit --osd-shadow-offset

player/lua/console.lua
console.lua: inherit --osd-color in the cursor
Following up 19537a4996, also respect the user-specified color in the cursor. But the cursor is drawn as a border, so we actually need to use --osd-color as the border color.
console.lua: inherit --osd-back-color in the cursor
3dcc661de7 made the cursor reset to Default style to not apply the blur, but \blur0 achieves that without resetting every user style. The cursor can thus respect the user's --osd-back/shadow-color.
console.lua: don't set the cursor color
This makes no visible difference, only the border color is visible, as the border is drawn on top of the regular color.
=> console.lua: inherit OSD styles in the cursor

osdep/mac/remote_command_center.swift
it's unnecessary to use the overhead of an obj-c selector and the resulting bridging.
=> mac/remote: use swift closure instead of obj-c selector bridging

LICENSE.GPL, LICENSE.LGPL
Downloaded from:
https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
Non-printable characters stripped from LICENSE.LGPL.
=> LICENSE.{GPL,LGPL}: update to upstream version

DOCS/interface-changes/media-controls-player.txt, DOCS/man/options.rst, etc/builtin.conf, options/options.c, options/options.h, player/main.c
It is now handled internally by the libmpv profile.
Since `player` was the default option, the impact should be minimal, as it is uncommon to override the default option with the same value. yes/no args will function the same way as before this commit.
API users might be affected though.
=> options: remove the `player` argument from `--media-controls`

DOCS/interface-changes/edl.txt, demux/demux_edl.c
Apparently there are some scripts that use nested edls instead of flattening them first, so let's live with this.
This reverts commit de42e11662f3f002033b28876b6a03e0313ba8a9.
=> Revert "demux_edl: disallow nested edl to avoid infinite loop"

osdep/mac/app_bridge_objc.h
some more preparations for the swift 6 concurrency stuff. the usage of those leads to errors with strict concurrency in swift 6.
those variables were imported as vars (mutable) in swift and were never meant to be mutable. make them const and none pointers and immutable.
=> mac/app: make re-assignment of complex macros const

DOCS/man/input.rst
They are not required but the current documentation only indicates this to some commands but not for others.
=> DOCS/man/input.rst: mark flags as optional

DOCS/man/stats.rst, etc/builtin.conf, player/lua/stats.lua
Unlike font and border sizes, the default stats shadow offset is 0 like --osd-shadow-offset, so it can be inherited from it by default to not make users configure it in 2 places.
Since 0 and negative numbers are valid offsets, use infinity as the placeholder for unconfigured values.
=> stats.lua: inherit --osd-shadow-offset

.github/workflows/build.yml
Avoids timeout of libplacebo/d3d11.c test that takes ~120s on Microsoft software implementation.
=> ci/win32: bump test timeout to 240 seconds

video/out/vulkan/context_display.c
Implement VOCTRL_GET_DISPLAY_FPS and VOCTRL_GET_DISPLAY_RES by returning values obtained from Vulkan.
=> vulkan/context_display: implement display fps and resolution info

DOCS/interface-changes/osc-buttons.txt, DOCS/man/osc.rst, player/lua/osc.lua
Allow adding custom buttons without forking the whole OSC like in https://github.com/christoph-heinrich/mpv-quality-menu/blob/master/osc.patch
I tried to put these to the left of the cache text at first but the layout is determined at startup so you can't conditionally remove elements at runtime.
Emoji may not be perfectly aligned depending on the font used.
Example with:
```
custom_button_1_content=🔁
custom_button_1_mbtn_left_command=cycle-values loop-file inf no
custom_button_1_mbtn_right_command=cycle-values loop-playlist inf no
custom_button_2_content=🔂
custom_button_2_mbtn_left_command=cycle-values loop-file 1 no
custom_button_3_content=🔀
custom_button_3_mbtn_left_command=playlist-shuffle
```
=> osc.lua: allow adding custom buttons

player/lua/stats.lua
Make this behave like the comment says it should, because currently when you show oneshot stats and change file, stats are printed again and hide --osd-playing-msg. This happens even if you hide the stats by show-texting something else and change file before the timer expires.
=> stats.lua: only reprint stats on video-reconfig when toggled

.github/workflows/lint.yml, .pre-commit-config.yaml
Tests some basic errors in files like, trailing white-spaces. Additionally check the spelling with codespell.
=> github/workflows/lint: add pre-commit hooks

DOCS/interface-changes/console-pause-on-open.rst, DOCS/man/console.rst, player/lua/console.lua
Add a script-opt to pause when console opens and unpause when it closes, disabled by default.
This is particularly useful for selectors that take several seconds to open so you don't have to guess when to pause, like the subtitle line selector with embedded subtitles, or my script which lets you select which lyrics to download after requesting them with curl.
=> console.lua: add pause_on_open script-opt

audio/out/ao_pulse.c
The server's protocol version is not available until a connection is properly established. Currently the value of `PA_INVALID_INDEX` is printed due to calling `pa_context_get_server_protocol_version()` before connecting.
Fix this by doing the call after the connection has been set up.
Fixes: f744aadb776d ("ao_pulse: dump library version etc.")
=> ao/pulse: only print server protocol after connection

audio/out/ao_openal.c
When the monitor goes to sleep, the OpenAL context was not properly handled, resulting in a null pointer dereference and a crash. This fix ensures that the OpenAL context is created and set correctly before proceeding. This avoids the crash under these conditions.
Fixes: #15648
Also fixes #[8307](https://github.com/SubtitleEdit/subtitleedit/issues/8307) of Subtitle Edit that utilizes Libmpv
Afterwards the important log part looks like this (can be compared to the log in #15648):
[ 108.517][d][ao/wasapi] Find device ''
[ 108.520][v][ao/wasapi] No device specified. Selecting default.
[ 108.534][v][ao/wasapi] Selecting device '{4d7dd748-07de-421c-9960-81369cb0b289}' (42 FHD_LCD-TV (NVIDIA High Definition Audio))
[ 108.534][v][ao/wasapi] Monitoring changes in device …
=> ao_openal: Fix null pointer dereference when creating OpenAL context

DOCS/man/osc.rst, player/lua/osc.lua
Add layouts with only the top line of bottombar to be used with images.
This was requested by some users, and is meant to be added to the image profile.
=> osc.lua: add slimbottombar and slimtopbar layouts

video/out/gpu/video.c
Use RGBA format to take transparent screenshots when the video has an alpha channel.
=> video/out/gpu/video: allow taking transparent screenshots

player/lua/osc.lua
osc.lua: extract icon_font and icons variables
Define the icon font and icons in variables instead of scattering them throughout the code to make it easy to change them in the future, or for forks to change them. Also put the hex values in comments to easily compare which icons in the font are unused, and explain how to get the decimal values of the bytes.
Copied from ModernX.
TOOLS/mpv-osd-symbols.sfdir: remove unused icons
E003 is a stop icon that was never used
E010 to E013 are the progress bar icons removed by ef3c0e6eda
E111 is a duplicate of the icon to exit fullscreen, E109
=> osc.lua: extract icon_font and icons variables

DOCS/interface-changes/current-watch-later-dir.txt, DOCS/man/input.rst, DOCS/man/mpv.rst, etc/input.conf, player/command.c, player/configfiles.c, player/core.h, player/lua/select.lua
Implement selection of files with watch later config files. Requires --write-filename-in-watch-later-config.
Suggested by llyyr. He also suggested showing this when mpv opens, but it completely covers the logo and the text, and stays open after dropping a file. Alternatively "Drop files or URLs to play here." could also suggest pressing g-h.
=> select.lua: select files with watch later files with g-w

player/lua/console.lua
console.lua: improve the hovered item calculation
Currently determine_hovered_item() assumes that each item is opts.font_size pixels tall, which usually works well. This breaks with fonts that get drawn taller than that, such as Japanese text, which makes the calculation inaccurate for the top items and clips the counter. A couple of users reported that it is inaccurate for them for the top items even with ASCII characters in track selectors, presumably because the circles are taken from a different font and make all lines taller.
To fix this place each selectable item in its own ASS event positioned like determine_hovered_item() expects.
Unfortunately this breaks --profile=box, so keep placing every item in one ASS event with it.
This should fix @sfan5's issue.
=> console.lua: improve the hovered item calculation

player/lua/console.lua, player/lua/osc.lua
Revert "osc.lua: draw box layout below console"
This reverts commit 2dd5bd4cd1d87e6e3b6e73f1976d060e64781d38.
Instead of drawing the box layout below any other overlay with z >= 0 which may not be wanted, the next commit will increase console's z only in select mode instead.
console.lua: set a high z in select mode
Give console's overlay a high z only in select mode, since in this case you want to click it so it should be above other overlays. In particular console should be above the OSC's box layout with visibility=always when you show it by clicking its buttons.
Keep using z=0 otherwise when it doesn't handle clicks, to avoid unintuitive behavior of overlays handling clicks like the OSC being drawn below console.
Since the legacy mp.set_osd_ass() doesn't accept z, we need to repeat its …
=> console.lua: set a high z in select mode

player/command.c, player/core.h, player/loadfile.c
With --prefetch-playlist, mp_next_file() is called continously since the last second of playback or when viewing an image, which decreases --loop-playlist=N to 1.
Fix this by adding a flag to mp_next_file() to specify whether to decrement --loop-playlist=N. The first playlist entry is still prefetched when it's the next one, but without decrementing --loop-playlist=N.
=> loadfile: fix --loop-playlist=N with --prefetch-playlist

audio/filter/af_scaletempo.c, options/m_option.c, options/m_option.h, options/options.c
OPT_FLOAT values currently reuses OPT_DOUBLE handling, but if a finite double value is produced which is out of the float range,
it results in UB.
If the floating point implementation is IEEE-754, then the value is converted to infinity and stored in the float. However, this still
does not work as intended, as infinity is rejected for OPT_DOUBLE unless infinity is explicitly specified as the min/max range.
Fix this by adding another clamping stage after operating the values as double. Finite double values are clamped between FLT_MIN and FLT_MAX, and out of range error is signaled when suitable.
Also fixes OPT_FLOAT options with incorrect DBL_MAX range.
=> fix OPT_FLOAT range handling

DOCS/man/console.rst, player/lua/console.lua
console.lua: rename update() to render()
It is not clear what update() updates, in fact this rename allows removing the comment explaining it. render() is clearer and is the same term used by the OSC.
console.lua: always say completions instead of suggestions
Both completions and suggestions were being used inconsistently. Just always use completions which is much more common.
console.lua: rename format_table() to format_grid()
Since there is no table header or predetermined columns.
=> console.lua: rename some things

player/lua/select.lua
MKV editions can have no title. Print their IDs instead of showing an empty selection.
=> select.lua: show the ID of editions without title

.github/workflows/build.yml
A build failure will output its error, but a test failure says nothing other than what test failed. Print the meson test log as well.
An example of a test failure can be seen here: https://github.com/Dudemanguy/mpv/pull/26
=> github/workflows: print meson test log on failure on BSD

options/m_option.c
FLT_MIN is a small positive number (1.175494e-38), so the check v < FLT_MIN introduced in 0e7f9c39dc made all 0 and negative float option values error, e.g. panscan=0 or video-align-y=-1.
Fixes #15728.
=> m_option: fix float option values <= 0

.github/workflows/lint.yml, TOOLS/dylib_unhell.py, TOOLS/file2string.py, TOOLS/gen-interface-changes.py, TOOLS/gen-mpv-desktop.py, TOOLS/macos-sdk-version.py, TOOLS/osxbundle.py, TOOLS/stats-conv.py
Not everything is typed in our scripts, but this is just to make sure
current code passes linting. More typing can be added in the future.
=> github/workflows/lint: add mypy linting

player/lua/console.lua
I have no idea why, but console's blur is smaller than in OSD messages and stats (regardless of persistent_overlay). This doesn't change with scale_with_window, or by using 0 PlayRes like stats with persistent_overlay=yes.
Multiplying the blur by 2.5 seems to make it the same. This is probably because 2.5 is 720 / 288, which are the base height sizes scale from and the OSD's PlayResY.
=> console.lua: use the same blur amount as --osd-blur

ci/build-win32.ps1
This reverts commit ddba159b5128858de7e2948a77ef08b4b53d8c42.
Follow-up after: 3b586ba6c37b80bf0e64bbb75d2a37b332ccbe06
=> Revert "ci/win32: restrict shaderc version to fix build errors"

video/out/wayland_common.c, video/out/wayland_common.h
If you have two seats connected, both with the pointer capability, and use two hands to start a drag and drop operation with each pointer, then move one pointer to the mpv window, then the other, mpv fails the !wl->dnd_offer->offer assert in device.enter, because it expects that the compositor wouldn't just call device.enter again before device.leave or offer.finish.
The data device is per-seat, so this commit makes mpv track the data device's offers per-seat rather than in vo_wayland_state, which makes more sense and is easier to reason about when multi-seat is involved.
=> video/out/wayland_common: fix crash with multi-seat drag and drop

.github/workflows/build.yml, .lsan_suppressions
The leak detector has been disabled due to a libass leak that was causing the test to fail. I initially expected this change to be temporary until a patch release of libass became available and we could update it. However, it has been a few months without a release. Instead of waiting, re-enable the leak detector and add a suppression file for this specific leak.
Fixes: d6eb85bb1a027aa52a7f48b162757763c9dcc875
=> ci/linux: enable leak detector

video/out/win32/menu.c
basically a copy of tsl0922/mpv-menu-plugin#77
if you have 200+ menu items and update `menu-data` about 400 times, clicking menu item will not execute any command, the reason is that the menu identifier greater than the max value of 16-bit unsigned integer.
1. make menu id always less than 0xF000 as mpv-player/mpv@861908c7 said
2. old menu items are never reused, should delete by DeleteMenu() instead of RemoveMenu(), destroys the handle and frees the memory
=> win32: fix the issue of menu click failure caused by excessive menu-data updates

video/out/wayland_common.c
This is to allow data device and text input to be used on seats that are hotplugged after vo init.
=> video/out/wayland_common: create per-seat objects on seat hotplug

DOCS/interface-changes/clipboard.txt, DOCS/man/input.rst, DOCS/man/options.rst, meson.build, player/clipboard/clipboard-vo.c, player/clipboard/clipboard-wayland.c, player/clipboard/clipboard.c, player/clipboard/clipboard.h, player/command.c, player/lua/console.lua, video/out/meson.build
This adds a "native" Wayland clipboard backend based on the `wlr-data-control-unstable-v1/ext-data-control-v1` protocol. 
This backend overcomes the limitation of the VO (Wayland core protocol) backend, and does not require the presence of the VO window to receive clipboard updates. The backend runs in a separate thread, so clipboard reading does not stall the player like the VO backend.
This backend also supports primary selection if supported by the compositor. The `clipboard/text-primary` property is added for primary selection text.
Also add `current-clipboard-backend` property to make the current backend detectable, and update console.lua to use the new backend if available.
=> add "native" wayland clipboard backend and several related properties

DOCS/interface-changes/watch-history.txt, DOCS/man/mpv.rst, DOCS/man/options.rst, etc/input.conf, misc/json.c, misc/json.h, options/options.c, options/options.h, player/command.c, player/core.h, player/loadfile.c, player/lua/select.lua, player/misc.c
Implement saving watched paths and selecting them.
--osd-playlist-entry determines whether titles and/or filenames are shown. But unlike in show-text ${playlist} and select-playlist, "file" and "both" print full paths because history is much more likely to have files from completely different directories, so showing the directory conveys where files are located. This is particularly helpful for filenames like 1.jpg.
The last entry in the selector deletes the history file, as requested by Samillion.
The history could be formatted as CSV, but this requires escaping the separator in the fields and doesn't work with paths and titles with newlines, or as JSON, but it is inefficient to reread and rewrite the whole history on each new file, and doing so overwrites the history with an empty file …
=> select.lua: select from the watch history with g-h

demux/cache.c, demux/demux_lavf.c, demux/demux_libarchive.c, demux/demux_mkv.c, demux/demux_playlist.c, demux/demux_raw.c, options/m_option.h, options/options.c, player/command.c, player/core.h, player/loadfile.c
When using --prefetch-playlist, if demuxer options are changed in the time window between the start of prefetching and the playback of the next file, the old values are used. This includes setting demuxer options in legacy extension auto profiles.
Fix this by setting a flag when demuxer options change and not using the prefetched data when that flag is true.
UPDATE_DEMUXER is not added to demux.c's options because those already support updates while playing.
=> loadfile: discard prefetched files if demuxer options changed

DOCS/interface-changes/frame-step.txt, DOCS/man/input.rst, player/command.c, player/core.h, player/playloop.c
This commit gives the frame-step command the ability to accept an
additional argument specifying the amount of frames (forwards or
backwards) to step through. By default, it steps forward 1. The
frame-back-step command is reworked to simply be a call to frame-step
with a -1 value. In the case where the value is exactly 1, mpv will play
exactly 1 frame and stop like before. However if a backwards step is
requested or multiple frames forward, then mpv will perform a very exact
seek. This working well, of course, depends on the pts values in the
stream being reliable which may not be the case. As a minor note,
MPSEEK_BACKSTEP is renamed to MPSEEK_FRAMESTEP since forward seeks use
this as well. Fixes #10128.
=> command: let frame-step go through multiple frames

fuzzers/fuzzer_load.c, fuzzers/fuzzer_loadfile_direct.c, player/loadfile.c, stream/stream_file.c
This ensures that we don't open some other fd, for example when loading playlist. Also filters out loading any local files.
=> stream_file: allow to open only our fd in case of fuzzing

video/decode/vd_lavc.c
My goal is to reinitialize the video decoder when the `vd-lavc-threads` option changes.
This reinitializes the whole video chain, no idea how this could be restricted to the decoder only without touching the rest of the chain or if that's even desirable.
I don't really know what I'm doing here, so there is probably a much better way to achieve this.
We could also extend this to other decoder related options once the approach has been figured out.
=> player/command: reinit video chain when decoder thread count changes

player/command.c
The frame-step command also signals on up events. This is only useful when using the default "play" mode. For seek mode, it triggers another frame step which is not what you want. Rearrange the logic so the up event is ignored for the seek flag. The frames check is also not needed since add_step_frame already handles it.
Fixes 9661a3839ba5af79e5620ce87acedf6cdaa244c1
=> command: fix spammy events when frame stepping forward with seek

DOCS/interface-changes/option-paths.txt, audio/out/ao_pcm.c, common/encode_lavc.c, common/playlist.c, options/path.c, player/loadfile.c, player/misc.c, stream/stream_bluray.c, stream/stream_cdda.c, stream/stream_dvb.c, stream/stream_dvdnav.c, sub/sd_ass.c, video/out/drm_common.c, video/out/vo_image.c
There's several path-related options that do not handle common shortcuts (like ~). Fix this by using mp_get_user_path where appropriate which expands the path so users get more intuitive behavior. Fixes #15598.
=> various: expand paths for several file/directory related options

DOCS/interface-changes/hwdec-software-fallback.txt, DOCS/man/options.rst, audio/decode/ad_lavc.c, options/options.c, options/options.h, player/command.c, video/decode/vd_lavc.c
Following up on the UPDATE_AD and UPDATE_VD stuff.
=> add full runtime support to ad_lavc and vd_lavc opts

options/m_option.c
d2c409c56b49252c85eefd340863fd59a36808d6 broke setting `--slang=` to effectively `-clr` the option. Restore the behavior because scripts rely on it.
Fixes: d2c409c56b49252c85eefd340863fd59a36808d6
=> m_option: reallow setting list options to no value to -clr them

ci/lint-commit-msg.py
Allow extension skip only on core files c/cpp/h/m/swift, for the rest require ext.
=> ci/lint-commit-msg.py: remove .py from allowed extension skips.

DOCS/interface-changes/option-paths.txt, player/command.c, player/screenshot.c
Follow up to be15be3a832cedf612c5b319ee3e381d2323cfee with the same reasoning.
=> command: expand paths for all commands with path arguments

DOCS/interface-changes/console-pause-on-open.txt, DOCS/man/console.rst, DOCS/man/input.rst, DOCS/man/javascript.rst, player/lua/console.lua
DOCS/man/input: reorder user-data's docs
user-data/mpv/ytdl was documented out of nowhere instead of together with user-data/osc.
console.lua: add user-data/mpv/console/open
Fixes #15762.
Revert "console.lua: add pause_on_open script-opt"
This reverts commit 850e03d29f2e2ef59e844b93a5deb87f1826888e.
The previous commit solved this in a more general way. You can do:
[open-console]
profile-cond=p['user-data/mpv/console/open'] and p['current-tracks/video/albumart'] == false
profile-restore=copy
pause
Thankfully pause_on_open was just added and has not been in a release so we can remove it.
=> console.lua: add user-data/mpv/console/open

player/lua/console.lua
It is not needed to expand ~ in file completion as you type after 62c3aeb9c makde commands themselves interpret it. We only need to call expand-path on the directory before passing it to utils.readdir in order to find files in it when it contains ~ placeholders. As a bonus this will now also complete files in directories like ~~/ and ~state/.
This simplifies command completion and was also the blocker for splitting running commands out of console.lua since I didn't know how to replicate it through mp.input.
=> console.lua: stop expanding ~/ in file completion

TOOLS/mpv_identify.sh
Property names contain '-' characters, which are translated into underscores because POSIX shell variables cannot contain hyphens.
We should do the same thing for forward slash characters (i.e. '/') because these also cannot be present in the names of shell variables.
Fixes: #15782
=> TOOLS/mpv_identify.sh: handle forward slash in property names

DOCS/man/osc.rst, player/lua/osc.lua
And move show-text ${path} to middle click. This is more useful than the replaced show-text ${filename} binding since the left click stats binding already shows the filename, and it matches how right clicking other buttons shows menus. Alternatively middle click could also be bound to select-watch-later.
=> osc.lua: bind right clicking the title to show history

player/loadfile.c
This makes OSD more usable when the filename contains non-ASCII characters.
=> loadfile: unescape display filenames

common/global.h, common/recorder.c, demux/cache.c, demux/demux.c, demux/demux.h, demux/demux_lavf.c, demux/demux_mf.c, demux/demux_mkv.c, demux/demux_raw.c, demux/packet.c, demux/packet.h, demux/packet_pool.c, demux/packet_pool.h, filters/f_decoder_wrapper.c, filters/filter.c, filters/filter.h, filters/frame.c, meson.build, meson.options, player/main.c, sub/dec_sub.c, sub/filter_sdh.c, sub/sd.h, sub/sd_ass.c, video/decode/vd_lavc.c
This update introduces a demux_packet_pool, allowing for the reuse of previously allocated packets when needed.
sizeof(AVPacket) is not a part of the lavc public ABI, which prevents us to allocate memory in larger blocks. However, we can substantially decrease the amount of alloc/free operations during playback by reusing both mpv's demux_packet and AVPacket.
This adjustment addresses the root cause of issue #12076, which, although resolved upstream, did not fully tackle the persistent problem of allocating small blocks of aligned memory. This issue largely stems from the FFmpeg design of the AVPacket API. After this change memory will no longer be allocated once cache limits is reached.
The demux_packet_pool is shared as a global pool of packets for a given MPContext.
This change …
=> demux: reclaim demux_packets to reduce memory allocator pressure

player/loadfile.c, stream/stream.c, stream/stream.h
I got mesmerized by the simplicity of the original commit, but in fact it was not a correct thing to do.
Fixes: c0366cfa4208c24eeccfbe99c26a15b6434b8e75
=> player/loadfile: we shouldn't unescape inplace

common/meson.build
Also for release tarball builds, put a 'v' in front of the number so it matches the formatting of the git tags.
=> build: use a more user-friendly version string for shallow clones

pyproject.toml
The error message is completely incomprehensible and also inconsistent about whether it wants two newlines or just one after an import.
Consider this python script:
```
import sys
sys.stdout.write("garbage")
```
That passes the ruff isort check just fine. But this does not:
```
import sys
def fake_function():
sys.stdout.write("garbage")
fake_function()
```
This will fail. Why? Because there should be two newlines after imports but only for functions. This is not explained or documented anywhere. You just get a cryptic "Import block is un-sorted or un-formatted" message. Although sometimes it appeared to have wanted two lines anyway even when there wasn't a function being defined after the imports* (link will expire eventually). Why?
Considering the amount of time I wasted trying to even …
=> ci/lint: disable isort checks

.github/workflows/lint.yml
This enables GitHub style output, along with other improvements.
=> github/workflows/lint: update astral-sh/ruff-action to v3

common/meson.build
Also fallback to `--always` only if first `git describe` returned errors, but were called successfully.
=> build: add early exit if git is not found

player/command.c
Just "Loop" is a leftover from when --loop-playlist was called --loop.
=> command: show Loop playlist when changing --loop-playlist at runtime

options/m_property.c
Disallow silly things like ${playlist//} and trailing slashes ${playlist/0/}.
=> m_property: fix playlist property parsing

options/options.c
Updating input-commands string list causes all commands to be rerun. This happens during load-config-file command, so even with few commands it is easy to amplify single command to run hundreds of times instead of one. This causes timeouts and OOMs when specific command for example reopens current playlist appending an item.
=> player/command: disable input-commands for fuzzing

player/command.c
To have consistency with 95019fc256d8df21994b20d2503b203ac09083cc
=> command: disallow trailing / in track-list/N/metadata

player/command.c
This is not only cosmetic, but also avoids dummy get key action with empty key. While this was allowed previously, I'm bit concerned about Hyrum's law. But let's be strict about it.
This commit fixes current-tracks property.
Fixes: 95019fc256d8df21994b20d2503b203ac09083cc
=> player/command: don't synthesize property names with a trailing /

DOCS/interface-changes/target-hint.txt, DOCS/man/options.rst, video/out/vo_gpu_next.c
HDR or any color-space pass-through should be opt-in, as we cannot control the user's compositor or display. Allowing HDR signals to be pushed by default may lead to surprising results for some users. Additionally, for an optimal experience, this option should be paired with the target-peak of the display.
Make the pass-through opt-in and let the user decide if they want or need it. By default, mpv should render a safe and consistent sRGB output. mpv's tone mapping is generally of higher quality than any external solution.
This reverts commit 23843b4aa594dc8c885575f3d237cde3c29398a2.
=> Revert "vo_gpu_next: set --target-colorspace-hint to `yes` by default"

DOCS/man/options.rst
Since https://github.com/haasn/libplacebo/commit/5f630020046c9b039adc34bf520644b264776606, ``auto`` is defined as ``spline``
=> DOCS/man/options: Clarify what --tone-mapping=auto does

player/lua/select.lua
The current warning was fine when you select history directly, but giving more information can be useful when you happen to see it by right clicking the title without prior information.
Fixes https://github.com/mpv-player/mpv/pull/15655#discussion_r1948053973
=> select.lua: change the --save-watch-history warning text

.github/workflows/build.yml, ci/build-msys2.sh
Upstream dropped libplacebo* so we're pretty much out of luck here. It's not worth it to bother building a subproject for just this one.
*: https://github.com/msys2/MINGW-packages/commit/c3a79e8ae9a8e7f2215db210ba3f44d91d7e23b6
Of course, the CI is failing anyways for some other reason.
=> github/workflows: drop mingw32

player/sub.c
track->selected works for the primary and secondary subtitle.
=> player/sub: eliminate redundancy when printing terminal subtitles

DOCS/man/input.rst
We use the ext protocol, not the wlr specific protocol. Moreover, "zwlr_data_control_manager_v1" is an interface within the protocol, not the protocol name itself.
=> DOCS/man/input: fix required protocol docs for wayland clipboard

DOCS/man/mpv.rst, DOCS/man/options.rst
Also suggest checking --panscan docs from its key bindings.
Requested by avih.
=> DOCS/man/options: explain the difference between panscan and zoom

demux/stheader.h, sub/sd_ass.c
Notably they are exchanged between demux and decode thread. It's fine because we know those pointers will be alive as long as avctx is alive. And only the value may change during decoding in rare situations. Make those pointers atomic for the sake of it.
It shouldn't change anything, except some codegen.
From https://www.gnu.org/software/libc/manual/html_node/Atomic-Types.html#Atomic-Types:
In practice, you can assume that int is atomic. You can also assume that pointer types are atomic; that is very convenient. Both of these assumptions are true on all of the machines that the GNU C Library supports and on all POSIX systems we know of.
=> demux/stheader: use atomic types for mp_codec_params names

video/out/vo_gpu_next.c
error_diffusion was not disabled even if --dither were changed.
=> vo_gpu_next: allow to disable error diffusion when changing --dither

meson.build, osdep/mac/app_bridge.m, osdep/mac/app_bridge_objc.h, osdep/mac/app_hub.swift, osdep/mac/dialog.swift, osdep/mac/menu_bar.swift, osdep/mac/option_helper.swift, osdep/mac/swift_extensions.swift, video/out/mac/view.swift
some dialog refactoring and additions, to make integrations with #15845 easier and prevent code duplications. needs a followup commit for #15845.
also shamelessly stole some ideas from @kasper93.
=> mac/dialog: refactoring and additions

ci/build-openbsd.sh, meson.options
There is no good reason to disable it by default.
This reverts commit 77cbb35437ccf8904cc76475868d20bd2f1751fd.
=> Revert "build: disable optical media libs by default (DVD/BD/CD)"

demux/cue.c
Trying to playback something that is not audio is not so nice.
Ref #8322.
=> demux_cue: only accept TRACK with AUDIO type

stream/stream_cdda.c
Sometimes a CD can have non-audio data at the start that is not playable. libcdio/paranoia is smart enough to already skip this, but our calculations for when the tracks/chapters start completely fall apart. The beginning bytes are not valid CD audio so it should just be subtracted and ignored. This probably doesn't work if a CD somehow has its audio tracks in a non-continuous manner with non-audio data in between tracks at random points. There's likely not much we could do in such a case, and probably nobody has an audio CD like that anyways.
Ref: #8322
=> stream_cdda: subtract first sector when calculating chapter times

DOCS/man/mpv.rst, DOCS/tech-overview.txt, meson.build, meson.options, player/main.c
We already have more than enough options. This doesn't need to exist. Just use the environment variable if you really want to use this for some reason.
=> build: remove ta-leak-report option

demux/demux_disc.c
62294049852549e99ec948e0df16452856afa0c1 removed both of these stream types.
=> demux_disc: remove obsolete is_dvd checks

options/path.c
Having path -> path in the log is kind of useless. If someone happens to call this on memory://, it will also flood the log with garbage. Only print it at a debug level if the path actually changes/get expanded. Otherwise set it at trace.
=> options/path: only log mp_get_user_path if the path expands

player/javascript/defaults.js, player/lua/console.lua, player/lua/input.lua
Currently using mp.input while the console is open doesn't do anything. We can allow using mp.input multiple times in a row by keeping the console open, and sending a closed event only when the previous calling script is different from the current one. If it is the same, sending a closed event would unregister the new input-event listener, so it is just never sent in this case as there is no sane way to do it.
Fixes #15795.
=> console.lua: allow subsequent mp.input calls

meson.build, video/out/hwdec/dmabuf_interop_wl.c, video/out/wayland_common.c
Take 3? cc @mahkoh and @ikalco if you want to take a look real quick.
=> more drm format selection fixes

DOCS/interface-changes/hwdec.txt, DOCS/man/options.rst, etc/input.conf, player/video.c, video/decode/vd_lavc.c
Users basically never need --hwdec=auto in reality and sometimes it bites them unexpectedly (e.g. #15814). Unfortunately the name is kind of nice sounding and if you don't read the manual closely, you might inadvertently end up using it. So just make auto the same as auto-safe. auto-unsafe is introduced to have the old behavior of auto instead. A similar thing is done with the -copy variants. Try to update the documentation of this section a little bit and discourage people from using auto-unsafe because it's kind of dumb.
Feel free to bikeshed.
=> vd_lavc: alias auto to auto-safe and introduce auto-unsafe

player/command.c, player/command.h, player/core.h, player/main.c, player/playloop.c
Could use some more testing for sure, but it seems like the dumb way of just processing these in the playloop does the trick.
Stuff like `input-commands` or `hwdec` are good to test since it's obvious if those do repeated executions. e.g. consider these config files.
```
hwdec=auto
hwdec=auto-safe
hwdec=auto
hwdec=auto-safe
hwdec=auto
hwdec=auto-safe
hwdec=auto
hwdec=auto-safe
```
```
input-commands=loadfile ${options}${playlist/0}${playlist/0}${playlist/0}
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
input-commands-pre=a
```
Load them at runtime with …
=> player: coalesce option updates and drop redundant ones

video/out/meson.build, video/out/wayland_common.c, video/out/wayland_common.h
Tested on [niri](https://github.com/YaLTeR/niri) with [strict-new-window-focus-policy](https://github.com/YaLTeR/niri/wiki/Configuration:-Debug-Options#strict-new-window-focus-policy).
Should we show a warning when `xdg-activation` isn't available? (showing one when `XDG_ACTIVATION_TOKEN` is not an option because currently that will always be the starting from a terminal, and the protocol doesn't respond if the activation succeeded or not)
=> wayland: Support `xdg-activation`

player/command.c, player/loadfile.c
Instead of re-normalizing the external filenames of tracks anytime the property is read, store it normalized in the first place.
=> player: store external filenames as normalized

DOCS/interface-changes/console-menu.txt, DOCS/man/console.rst, DOCS/man/mpv.rst, DOCS/man/osc.rst, DOCS/man/select.rst, player/lua/console.lua
console.lua: improve the hovered item calculation with background-box
Follow up to c438732b23 which improved the calculation with the default outline-and-shadow. We can make the calculation accurate for background-box too without making semitransparent rectangle backgrounds overlap by adding margin between items.
We could calculate the height of each item to make them perfectly adjacent by rendering each one with compute_bounds, but that takes 15ms per render, so 20 lines would take 300ms, which is too slow.
Instead add a fixed 0.1 * opts.font_size to each item's height. This ensures the backgrounds don't overlap with tall CJK text or track circles and --osd-shadow-offset=0. Add this to outline-and-shadow too since it looks better with some margin between the items. Then add the rectangle …
=> console.lua: update the select layout

options/m_config_core.c, options/m_config_frontend.c, options/m_config_frontend.h, options/m_option.h, player/command.c, player/command.h, sub/dec_sub.c, sub/sd_ass.c
UPDATE_CLIPBOARD currently has the same value as M_OPT_DEFAULT_NAN, so increment all constants after UPDATE_OPT_LAST. But increment them by 5 so we can add a few more UPDATE flags without either forgetting to increase them like in e1d30c4c5a, or having to increase them each time like in a5937ac7e3.
=> various: upgrade option flags to uint64_t

DOCS/interface-changes/input.txt, DOCS/man/options.rst, options/options.c, player/lua/console.lua, video/out/w32_common.c
This allows IME to be enabled/disabled with `--input-ime` option on Windows, like on Wayland. 
The default of `--input-ime` is changed to no since by default mpv isn't taking text input. `console.lua/mp.input` is changed to enable/disable IME when text input is activated/deactivated to ensure the suitable IME status is used depending on context. 
Fixes: https://github.com/mpv-player/mpv/issues/13666
=> win32: support --input-ime 

player/command.c, player/command.h
PR #15457 has not been rebased after merge of #15828 resulting in type mismatch.
Fixes: f57c0af5f2b8de922e4d32764c5fdc1f4e2f6f2a
=> player/command: fix flags type in mp_option_run_callback

player/core.h, player/main.c, player/playloop.c
The refactoring in bbac628a1b01261766459c6556e36d2443a42534 missed that the initial update handler didn't immediately run all the triggered callbacks but would instead delay it until the next playloop. This subtly breaks things of course like hooks, force window handling, etc. Ensure that we immediately run all the callbacks like before on startup.
Fixes bbac628a1b01261766459c6556e36d2443a42534
Fixes https://github.com/mpv-player/mpv/pull/15828#issuecomment-2663830477
=> player: run all update handlers on init

DOCS/man/options.rst
Read this a million times in the PR and still missed it.
=> DOCS/man/options: fix a typo in the hwdec section

DOCS/man/mpv.rst, DOCS/man/options.rst, meson.build, stream/stream_bluray.c, stream/stream_cdda.c, stream/stream_dvdnav.c
=> build: use the same default optical drive for everything

video/out/wayland_common.c, video/out/wayland_common.h
I started doing this in f5944824513f3081ac01484c85960324bdaabda1 for protocol objects that were newer than the lowest version, but I can't remember why (some waf-related reason?). This wasn't even followed for other PRs merged recently like ext-data-control and color-management. Anyways, it's not needed and works fine if you're on wayland-protocols 1.31 so stop doing this void weirdness.
=> wayland: unvoid some wayland protocol structs

osdep/timer-win32.c
Does anyone compile libmpv for UWP?
=> osdep/timer-win32: add missing guards for ARM64

osdep/mac/dialog.swift
@kasper93 a heads up, this might lead to some merge conflicts with your dialog branch. also the save function needs the panel delegate set too (eg `panel.delegate = self`).
modal dialogs steal the key/mouse input and possibly eat corresponding key up events when opening via key binding. this leads to key sequence ends to not reported and key bindings not being triggered if no key up event was triggered after closing the modal.
=> mac/dialog: release all input keys when modal steals key input

DOCS/man/options.rst
Fixes: d7159e4662000457b74272ec448897ad21826061
=> DOCS/man/options: fix missing space in hwdec doc

DOCS/man/options.rst
forgot this in fc4db18 and meant to remove it when implementing wid embedding again. though it's better to fix the docs separately.
=> DOCS/man/options: remove outdated wid embedding docs for cocoa

DOCS/interface-changes/cdda-span.txt, DOCS/interface-changes/optical-device.txt, DOCS/man/mpv.rst, stream/stream_bluray.c, stream/stream_cdda.c, stream/stream_dvdnav.c
Because I like changing things.
=> disc syntax cleanups/deprecations

DOCS/interface-changes/frame-step.txt, DOCS/man/input.rst, player/audio.c, player/command.c, player/core.h, player/playloop.c, player/video.c
Need to shuffle some stuff around but it's pretty simple. Mute the audio stream before the frame step and then unmute it when we're done. It's exactly the same as the default play mode otherwise.
=> player: add an optional mute flag when framestepping

demux/demux.c, demux/demux.h, demux/demux_disc.c, demux/demux_lavf.c
Basically just bits of a9d83eac40c94f44d19fab7b6955331f10efe301 that was removed and ported to here. Not really smart but it seems like flushing buffers during seek generally leads to better behavior and avoids some errors. The additional stream_seek call that was being performed is definitely bogus (will never work and spams errors). So that is skipped for bd/dvd. SEEK_FORCE is no longer needed. Instead demux_disc calls drop_buffers on the slave demuxer (i.e. lavf).
=> demux: use a slightly better hack when seeking with dvd/bd

DOCS/interface-changes/optical-device.txt, DOCS/man/mpv.rst, stream/stream_bluray.c, stream/stream_cdda.c, stream/stream_dvdnav.c
This reverts part of PR #15899 (commit dd6e3a0ece22b351c8815cf57d18c2d90f1360ee).
"Why is this even useful?": It's very useful for multi-disc playlists. Compare:
`mpv bd:///DISC{1..4}`
`mpv -\{ bd:// --bluray-device=DISC1 -\} -\{ bd:// --bluray-device=DISC2 -\} -\{ bd:// --bluray-device=DISC3 -\} -\{ bd:// --bluray-device=DISC4 -\}`
=> Revert "stream_{bluray,cdda,dvdnav}: deprecate setting device after schema"

video/out/vo_dmabuf_wayland.c
osd_surface is a sync sub-surface of video_surface meaning that a commit
of osd_surface will not take effect until the next commit of
video_surface.
Some compositors (wlroots) do not implement sync sub-surface correctly,
meaning that the difference cannot be observed there. But it can easily
be seen on Jay and GNOME:
1. Open an mpv window.
2. Pause the video.
3. Enter the surface with the mouse.
Expected behavior:
1. The OSD shows up immediately.
Actual behavior:
1. Nothing happens for a few seconds.
2. The OSD shows up and immediately fades out.
This is because the fade-out commits cause the initial osd_surface
commit to become effective.
=> vo_dmabuf_wayland: commit surfaces in correct order

video/out/wayland_common.c, video/out/wayland_common.h
Not really tested but in theory it sets icc-related things for the compositor. Only weston supports icc AFAIK so probably this will be a draft for a while.
=> wayland: add icc support using wp-color-management-v1

player/lua/select.lua
I don't know why I didn't get it before but Lua's LSP now complains with
Compute `"Edition " .. (edition.id + 1)` first. You may need to add brackets. [ambiguity-1].
Just move the parenthesis to make it happy.
=> select.lua: fix LSP warning

video/out/gpu/context.h, video/out/opengl/context.c, video/out/opengl/context.h, video/out/opengl/context_android.c, video/out/opengl/context_angle.c, video/out/opengl/context_drm_egl.c, video/out/opengl/context_dxinterop.c, video/out/opengl/context_glx.c, video/out/opengl/context_wayland.c, video/out/opengl/context_win.c, video/out/opengl/context_x11egl.c, video/out/opengl/libmpv_gl.c, video/out/vo.c, video/out/vo.h, video/out/vo_gpu_next.c, video/out/vulkan/context.c, video/out/vulkan/context.h, video/out/vulkan/context_android.c, video/out/vulkan/context_display.c, video/out/vulkan/context_mac.m, video/out/vulkan/context_wayland.c, video/out/vulkan/context_win.c, video/out/vulkan/context_xlib.c
This fixes the delayed osd rendering thing on `vo_gpu_next` and `drm_egl`. One thing is that I really dislike this weird external swapchain API we have (only opengl even has code to deal with it), and I kind of want to remove it, but `drm_egl` is the sole legitimate user of it. I'm not entirely sure if the custom fencing stuff it has is really needed today. Maybe I might follow up on that later, but this would be a quick fix to the actual bug.
=> external swapchain simplifications and fixes

video/out/drm_common.c, video/out/drm_common.h, video/out/opengl/context.c, video/out/opengl/context_drm_egl.c, video/out/vo.c, video/out/vo.h, video/out/vo_drm.c, video/out/vo_gpu_next.c
I changed my mind. These are the first two commits from #15948 extracted to here since it's just a plain better solution and fixes 0959cdeb038de6484f75eada21f674bcc2407b89
=> drm: use VOCTRL_REDRAW when flipping buffers

DOCS/man/console.rst, player/lua/console.lua
Disabled by default.
Fixes #15897.
=> console.lua: allow persisting the command history

DOCS/man/mpv.rst, DOCS/man/options.rst, DOCS/man/positioning.rst, etc/input.conf, options/options.c, options/options.h, player/core.h, player/lua.c, player/lua/meson.build, player/lua/positioning.lua, player/scripting.c
This script provides script messages and bindings to pan videos and images, making mpv a better image viewer out of the box.
I've had this script for 3 years in my image config so why not upstream it to view images better out of the box. Credits to occivink for the original ideas of the bindings.
I also have a mouse gesture and a oneshot double page mode in my script but those may not be worth upstreaming.
For the reasoning behind the `suppress_osd` naming, see https://github.com/mpv-player/mpv/pull/9051#issuecomment-887290791
Touch input in `cursor-centric-zoom` is untested.
For negative zoom, I think we need a global option like `--auto-recenter-video` (implemented in `vo_get_src_dst_rects()`?) to reset video-align to 0 when the image is smaller than the OSD, so that it also applies …
=> positioning.lua: add this script

DOCS/man/console.rst, player/lua/console.lua
fzy returns which characters matched the search for every item, so use this to highlight them.
Using color is complicated because it will become hard to differentiate depending on --osd-color and color blindless, so just underline the matched parts.
The returned positions are just bytes, so we can't put ASS tags or escape sequences around each byte because that would break displaying multibyte UTF-8 characters. Only put them around sequences of matched positions.
=> console.lua: highlight matching parts of selectable items

player/lua/console.lua
This needs to strike a fine balance between being visible and having contrast with the text color and not taking attention away from the selected item. Make it slightly more opaque to differentiate it more easily.
Fixes https://github.com/mpv-player/mpv/pull/15711#issuecomment-2676015561
=> console.lua: increase the opacity of the default item background

DOCS/interface-changes/clipboard.txt, DOCS/man/input.rst, DOCS/man/options.rst, player/clipboard/clipboard.c, player/clipboard/clipboard.h
This allows specifying a priority list of clipboard backends to use. This is mostly useful on Linux where multiple clipboard backends exist.
=> clipboard: add --clipboard-backends option

player/lua/console.lua
300 characters doesn't always fill the window.
Fixes #15944.
=> console.lua: include more characters in selectable items

player/lua/stats.lua
The names of single invocation key bindings for specific pages will be changed if defines user key bindings, then original invocation fails.
e.g. : when user defines `key_page_4=F4`, then key binding name
`stats/display-page-4-toggle`
becomes
`stats/display-page-F4-toggle`,
and OSC menu `Help` fails.
---
This patch fixed the issue, tested in f9271fb build, with following configs.
```ini
; mpv.conf
[default]
load-stats-overlay=no  ; disable the built-in script to use a patched user script
```
```ini
; script-opts/osc.conf
key_page_4=F4
```
A patched scripts/stats.lua file.
=> stats.lua: use fixed naming for single invocation key bindings

video/out/vo.c
Windows works totally differently than the other backends and is sensitive to synchronization issues since it runs its control on a separate thread. The spot where this was originally placed was a perfect storm of causing resize weirdness because it was before the flip and right after the redraw. Ideally, this is known to the windowing backend before the flip actually happens so just move this out to before the do_redraw call. It makes no practical difference for the one user of this and sidesteps the implementation differences that exist on Windows. Fixes fc9d1ca182125efa4f16bf3ed0fec8357806b3a7.
=> vo: signal VOCTRL_REDRAW in a less sensitive spot

video/out/gpu/context.h, video/out/opengl/context.c, video/out/opengl/context_drm_egl.c
@kasper93: It turned out to be way simpler than I thought.
=> remove external swapchain usage from drm_egl

input/input.c, input/input.h, osdep/mac/input_helper.swift, osdep/terminal-unix.c, osdep/terminal-win.c, video/out/vo_caca.c, video/out/vo_sdl.c, video/out/w32_common.c, video/out/wayland_common.c, video/out/x11_common.c
Setting the mouse position always updates the cursor visibility state in the core, but that's not always desired by the caller. Make it optional. In practice, this is for wayland. Fixes #15967.
=> input: add quiet arg to mp_input_set_mouse_pos for wayland

osdep/subprocess-win.c
When a stream is not set to passthrough and there is no data to read or write, a handle to the NUL file is created. However, these handles were not included in the list of inheritable handles for the child process. This commit ensures they are properly inherited.
Fixes: 83fec9bafb13d4b506c41c0a4394ce6869f5b4f3
Fixes: #15982
=> osdep/subprocess-win: fix inheritance of NUL handles in child processes

DOCS/man/input.rst, options/m_option.c
Also adds missing details of the `chapter` property.
=> options/m_option: fix REL_TIME_CHAPTER printing

filters/f_decoder_wrapper.c, player/command.c, video/decode/vd_lavc.c
This never really worked before and then I made it work for even less people, so might as well fix it now.
=> fix hwdec printing mess

options/m_config_frontend.c, options/m_config_frontend.h
It is easy to craft a config file that loads a profile recursively. To prevent this, not only check the depth of the current inclusion but also ignore already-seen profile names.
=> options/m_config_frontend: don't allow recursive profile inclusion

filters/f_decoder_wrapper.c
Fixes deadlock when reinit is triggered by the thread itself.
Fixes: #15776
=> f_decoder_wrapper: don't wait on self thread progress on reinit

player/lua/ytdl_hook.lua
Make sure the `early` variable is boolean. The issue was that if url have `ytdl://`, find() would return position `1`. This makes `early` also `1`. And now we try to compare `early == load_fail`, which for `1 == true` is false, while we expect it to be true. Make sure we compare booleans.
=> ytdl_hook.lua: fix boolean comparision

video/out/d3d11/hwdec_d3d11va.c
This is required for creating a copy texture. Note that alignment is applied only when making a copy; if mapping the texture directly, the native texture size is used as-is. The texture itself may be larger depending on the coded dimensions, but we only copy the "interesting" part of the image.
Fixes playback of videos with odd dimensions.
=> hwdec_d3d11va: align image mapper dimensions to a multiple of 2

DOCS/man/vo.rst
minor fix to the vo manpage, since color-management-v1 landed with 6bfbaf6bc6f2161, rename xx-color-management-v4 to color-management-v1
=> DOCS/man/vo.rst: xx-color-management-v4 -> color-management-v1

meson.build
62294049852549e99ec948e0df16452856afa0c1 removed libdvdread and it has not been needed since.
=> build: remove unused dvdread dependency

TOOLS/dylib_unhell.py
for now just fixing the bundling with vulkan. current nightly builds don't include the vulkan driver because homebrew changed the location (https://github.com/Homebrew/homebrew-core/commit/0c6a7238e7c3457af8d2cc7a997a3d2732ab2751).
in future changes we should probably fail on bundle creation when vulkan can't be bundled, at least for our CI. though making the failing optional, since bundles without bundled vulkan drivers are still a valid case.
=> osxbundle: add new vulkan loader homebrew path

DOCS/interface-changes/auto-profiles-prio.txt, player/lua/auto_profiles.lua
This increases the priority from 50 (which is neutral) to ensure that profiles are applied before other scripts.
In general, applying profiles before other scripts makes sense. This was already the case for external scripts with default priority because they would load after auto_profiles.
This commit primarily fixes ytdl_hook.lua to respond to profile changes. In most cases, profile conditions are triggered by external conditions, not the output from the ytdl hook, so this is fine.
I acknowledge that this will change the order if a script previously had a priority lower than 50. However, injecting itself before profiles are evaluated is a very obscure use case, if there is even a valid one.
=> auto_profiles.lua: make profiles apply with higher priority

input/cmd.h, options/m_config_frontend.c, options/m_config_frontend.h, options/m_property.h, player/command.c, player/command.h, player/playloop.c
cc @christoph-heinrich: I think with this you just need to do this (potential backwards compatibility handling ignored):
```
diff --git a/subtitle-lines.lua b/subtitle-lines.lua
index d836b83..556796f 100644
--- a/subtitle-lines.lua
+++ b/subtitle-lines.lua
@@ -130,7 +130,7 @@ local function acquire_subtitles()
mp.set_property_bool(sub_strings.visibility, false)
-- go to the first subtitle line
-    mp.commandv('set', sub_strings.delay, mp.get_property_number('duration', 0) + 365 * 24 * 60 * 60)
+    mp.commandv('immediate', 'set', sub_strings.delay, mp.get_property_number('duration', 0) + 365 * 24 * 60 * 60)
mp.commandv('sub-step', 1, sub_strings.step)
-- this shouldn't be necessary, but it's kept just in case there actually
@@ -207,7 +207,7 @@ local function acquire_subtitles() …
```
=> player: only coalesce callbacks from parsed config files

demux/demux_timeline.c
add_tl() when creating virtual_stream list is referencing sh->codec which is owned by the demuxer. Don't close it to avoid dangling pointers. The comment is right, but this happens regardless of delay_open as we can clearly see in the add_tl() function.
=> demux_timeline: don't close segments during demuxing

DOCS/interface-changes/commands.txt, DOCS/interface-changes/mp.input.txt, DOCS/man/commands.rst, DOCS/man/console.rst, DOCS/man/lua.rst, DOCS/man/mpv.rst, DOCS/man/options.rst, etc/input.conf, options/options.c, options/options.h, player/core.h, player/javascript/defaults.js, player/lua.c, player/lua/commands.lua, player/lua/console.lua, player/lua/input.lua, player/lua/meson.build, player/scripting.c
It was suggested by CogentRedTester in https://github.com/mpv-player/mpv/pull/10282#issuecomment-1858727729 and https://github.com/mpv-player/mpv/pull/10282#issuecomment-1858809580 and by avih that making running commands an mp.input client is a better architecture.
A practical advantage is that completions are calculated in a different thread, which prevents hanging when completing slow/network filesystems.
script-binding console/enable becomes script-binding commands/open, though the console one is kept as an alias. I took the opportunity to rename this because open makes more sense for a graphical modal, and it is the word used in mp.input and user-data.
script-message-to console type becomes script-message-to commands type, though the console one is kept as an alias. It is also …
=> commands.lua: split this script out of console.lua

player/lua/positioning.lua
Otherwise you can move your cursor outside the mpv window while having align-to-cursor "held" and make the script send illegal values
=> positioning.lua: clamp values within {-1, 1} for video-align-{x,y}

player/lua/console.lua
Pressing ctrl+c in select mode crashes if console wasn't opened in free-form text mode before.
This also makes the type of the history variable clear.
Fixes a6024b562a.
=> console.lua: fix crash when pressing Ctrl+c with select

DOCS/man/input.rst, player/lua/commands.lua
The default mode actually named `apply` instead of `default`, it's a mistake that has existed for a long time.
Fixes: 1f132c6
=> DOCS/man/input: correct the mode flag of apply-profile command

audio/out/buffer.c
There's no good explanation, but I can no longer reproduce the issue described in the commit. The code as is can cause a "File descriptor in bad state" message when looping or advancing in a playlist because it jumps a bit too early to the eof part. Perhaps something in alsa somehow changed, but the non-gapless audio freezing thing doesn't happen anymore. The audio state correctly updates on play/pause without these lines. Since this is known to cause problems elsewhere, just revert it for now. If the alsa problem crops up again in the future, we can revisit it then.
This reverts commit d33e54250e6643bdd20879eae1921fe18aecccd5.
=> Revert "ao: correctly set state.playing for non-gapless audio after eof"

player/lua/console.lua
This is an improvement on #15145 .
If the cursor is automatically hidden, users may not know whether they are clicking on the inside or outside of selectable items,  the result after clicking is unclear to them.
=> console.lua: disable cursor autohide while selector is open

player/lua/console.lua
In retrospect, this isn't so great because no neccesarily everyone would want the mouse to show with the menu and said menu can be navigated with the keyboard anyway.
This reverts commit a8f5beb5a38e0ed169a9fb9faff6c5ca0a43dfee.
=> Revert "console.lua: disable cursor autohide while selector is open"

ci/build-win32.ps1
This requires PowerShell 7.4+ to work, but it's fine for our CI.
=> ci/build-win32.ps1: exit on errors from external commands early

video/out/wayland_common.c
This matches the behavior of mpv's own drm backend when setting hdr
metadata, as well as Mesa's vulkan wsi's behavior when communicating
VK_EXT_hdr_metadata values to the compositor
=> wayland: round values instead of implicitly casting float to int

player/lua/select.lua
When the first chapter is not at the start of the file but after the current time position, the chapter property is -1, which prevented displaying any chapter.
Fixes #16073.
=> select.lua: display chapters when before the first chapter

video/out/vulkan/context.c
VK_KHR_video_maintenance2 was recently merged in FFmpeg. It significantly speeds up some problematic HEVC samples, as it avoids needing to recreate sequence parameters on each frame.
It also generally speeds up everything as it avoids needing to ask the driver to allocate memory for parameters it sends on every frame anyway.
=> vulkan/context: enable VK_KHR_video_maintenance2 if supported

video/out/vo_kitty.c
=> video/out/kitty: set display_par when drawing osd

demux/demux_lavf.c
Added in https://github.com/FFmpeg/FFmpeg/commit/91d96dc8ddaebe0b6cb393f672085e6bfaf15a31
The user can still turn this on via demuxer-lavf-o=extension_picky=1 if they want to.
This causes quite a few problems with many HLS sources where the codecs are not known at probe time for whatever reason. Youtube for instance shows "aac" audio codecs as "unknown".
As an aside, the FFmpeg test is also buggy and leaks a nested connection for any playlist item that fails the extension check. mpv catches this and prints "Leaking 1 nested connections (FFmpeg bug)" for every HLS stream that has at least one stream that fails the extension check.
=> demux_lavf: disable extension_picky for hls demuxer globally

video/out/vo.c
Fixes VO thread busy looping in paused state for untimed VOs.
One example is vo_lavc (encoding mode), used commonly to extract thumbnail by scripts.
Example command that was affected:
mpv --ovc=rawvideo --of=image2 --ofopts=update=1 --o=test --pause <file>
We have to update frame parameters that it is still and shouldn't be repeated again. This has been skipped by early exit.
Fixes: 8798cec7fa14bbeb35c7b711db3a41d336f78a69
=> vo: don't burn cpu in paused state for untimed VOs

DOCS/man/mpv.rst, etc/input.conf
For symmetry with drag-to-pan. Use MBTN_MID to reset the video position.
=> Revert "input.conf: bind MBTN_MID to align-to-cursor"

player/lua/ytdl_hook.lua
Sometimes when opening a YouTube video with chapters, the chapter-list ended up having all the chapters twice, despite the json from yt-dlp only containing them once. That must mean that sometimes add_single_video() runs twice before the chapter_list table gets cleared in the on_preloaded hook.
This can be avoided by replacing chapter_list with a new table before adding entries to it.
I don't understand why add_single_video() sometimes runs twice before the table gets cleared in on_preloaded, and it happens so rarely that I can't really debug it, but this change should at least prevent the problem with the chapters.
=> ytdl_hook.lua: fix duplicated chapters

player/lua/commands.lua
With -v -v there was an infinite loop of log messages, because every new logged script message to console triggers a new script message, which gets logged again.
=> commands.lua: prevent infinite logging with debug log level

options/m_option.c
When converting list options to strings and the value is empty, an empty string is returned. This is true for key value list and object settings list options. However, for string list options, there is an edge case: if the list exists but has no element (which can happen when using change-list command), it behaves as if the property does not exist and returns "(error)". This causes confusing messages when toggling glsl-shaders at runtime and seeing "(error)" printed as the value when all shaders are toggled off, for example.
8461143ed7c0088fe08379898e74a7fbcf0a9d1e attempted to fix it, which fixed the case for unset string list, but not for a list with no element.
Fix this by making sure an empty string is returned in this case.
Fixes: https://github.com/mpv-player/mpv/issues/16101
=> m_option: fix string list printing for empty lists

meson.build
This is bare runner for mpv.exe. There is no need for stack protector here and when it forced to be added by -fno-stack-protector it complains about missing symbols, because we don't link any standard libs here.
Fixes:
undefined symbol: __stack_chk_fail
undefined symbol: __stack_chk_guard
We could define those, but this mpv.com wrapper doesn't need it.
=> meson: disable stack protector for mpv.com

DOCS/man/options.rst
The messages referred to "no" prefixes like --no-audio not working with the client API. The language was removed in b1ee92ad4aec81dd31408d0c1223f0e9ea3cb738.
Remove the messages which are bogus and incorrect now.
=> DOCS/man/options: remove bogus messages about the client API

player/lua/stats.lua
Some properties can take a long time to query, especially those which require voctrl like current-window-scale and display-names.
Similar to d37521b5ef69f4793a05583d634de286709a6806, make the script observe these properties and cache the values to avoid querying them on every refresh. This alleviates the issue when holding down "i" key for a while and releasing it results in stats being stuck on display for a long time because of the time required to query there properties.
Related: #6412
=> stats.lua: cache some properties

input/cmd.h, input/input.c, player/playloop.c
MP_EVENT_INPUT_PROCESSED is used to notify mouse and touch position updates, but it is currently notified for all input commands even when they have nothing to do with mouse position. This results in unnecessary acquisition and comparision of mouse and touch positions for all commands.
Optimize this by checking whether the command is marked as requiring the event notification, and only notify if that is true.
=> playloop: only notify MP_EVENT_INPUT_PROCESSED when needed

video/out/wayland_common.c
The version 2 changes only add some enums which makes zero difference to us so we can just allow the newer version.
=> wayland: accept version 2 of the cursor-shape protocol

DOCS/interface-changes/commands-remember-input.txt, DOCS/man/commands.rst, player/lua/commands.lua
Allow clearing the input line on close. Fixes #16104.
=> commands.lua: add remember_input script-opt

DOCS/interface-changes/kitty-passthrough.txt, DOCS/man/vo.rst, video/out/vo_kitty.c
This PR contains a total of 4 major changes:
1. Fix a SEGFAULT in kitty video output
This was caused by a use-after-free of `priv->cmd.start` which was
`free`'d in `reconfig` and used later in `flip_page`.
This could be triggered by running mpv with kitty vo and sending a
`SIGWINCH` signal.
2. Adding support for multiplexer passthrough
Only tmux and GNU screen supported at this time. This allows the kitty
image protocol to work when running mpv within these multiplexers.
3. Remove trailing `NULL` byte in payload
This is a very specific issue, currently this only causes problems in
the Ghostty terminal emulator but still is nice to fix nonetheless.
So the issue was that the write function was changed to use `bstr.len`
from `strlen`, now `av_base64_encode` outputs a `NULL` terminated
base64 …
=> vo_kitty: fix segfault, add multiplexer passthrough + QOL fixes

video/vdpau.c, video/vdpau.h
And eliminate recursive lock. This doesn't have to be guarded by mutex, if for some reason preemption happens while we are handling preemption, we remember the flag and do the dance gain. This is even nicer than locking preemption callback.
=> video/vdpau: change is_preempted bool to atomic

filters/f_swscale.c, test/img_format.c, video/mp_image.c
Fixes invalid colors with gpu-next direct mapping of some formats.
=> mp_image: set repr.alpha and repr.bits when mapping AVFrame

DOCS/man/options.rst, video/decode/vd_lavc.c
FFmpeg recently got a hardware accelerated decoder for FFv1. The decoder has been tested on all major vendors and operating systems. Intel support is currently disabled as all of their drivers have issues with buffer device addresses.
Since its a software-defined implementation, internal issues can be fixed and the overall implementation optimized further.
With that, I think it should be safe to enable it by default.
=> vd_lavc: enable FFv1 hwaccel by default

osdep/threads-posix.h, osdep/threads-win32.h, osdep/threads.h
The only use of `MP_MUTEX_RECURSIVE` is in vdpau.c. If it is disabled, remove the unused code. This simplifies the win32 implementation by eliminating unnecessary critical section references.
=> threads: remove unused recursive mutex support

video/out/wayland_common.c
Core wayland works in the surface local/logical coordinates so the width and height values should really be divided by the scale factor.
=> wayland: use logical coordinates when setting the opaque region

player/clipboard/clipboard-wayland.c
This causes mpv to use up 100% of a core if there's an offer for a mime_type that mpv doesn't accept with ext_data_control clipboard backend.
Fixes: #16139
=> clipboard-wayland: prevent reading from hung up fd

demux/demux_playlist.c
The playlist demuxer won't propagate the protocol forward to its entries if its protocol is on a whitelist, for example data:// or memory:// etc.
This commit adds fd:// to that list because that should not be expected to work.
=> demux/demux_playlist: mark fd:// as self-expanding

player/lua/select.lua
The C version of time formatting function has been exposed to lua, so why not use it, `osc.lua` and `stats.lua` are already using it.
=> select.lua: simplify the time formatting function

DOCS/man/osc.rst
The examples for each button were rendered in the same line.
=> DOCS/man/osc: fix custom button example formatting

player/lua/positioning.lua
Instead of crashing, show the correct usage when running pan-x, pan-y or cursor-centric with script-message, or with script-binding but no argument.
=> positioning.lua: validate that an amount is passed

filters/f_auto_filters.c, filters/f_auto_filters.h, filters/f_output_chain.c, filters/filter.h, video/mp_image.c, video/mp_image.h, video/out/gpu/libmpv_gpu.c, video/out/gpu/video.c, video/out/vo.c, video/out/vo.h, video/out/vo_dmabuf_wayland.c, video/out/vo_gpu.c, video/out/vo_gpu_next.c, video/out/vo_libmpv.c
Currently we check AV_FRAME_DATA_DISPLAYMATRIX for its rotation factor but not for its flip factor, which could happen with some input files. This commit adds and autovflip filter, which is applied before the autorotate filter to flip vertically before rotating. It also changes the displaymatrix reading code to output to mp_image->params.vflip so it can be autoinserted as necessary.
=> filters: automatically flip video if displaymatrix indicates so

.github/workflows/build.yml
CMake has been updated to 4.0 which breaks compatibility with all project targeting version < 3.5. See for more user stories: https://github.com/actions/runner-images/issues/11926
Remove 4.0 from path and use the one from VS installation which is working for now. Generally we want to use only tools from VS installation, but unfortunately Windows image provided by GHA have polluted PATH which already causes issues in the past, that's why we remove yet another directory from PATH.
The affected project in our case is https://github.com/webmproject/sjpeg which is build as part of libjxl.
=> ci/win32: don't use CMake 4.0

input/ipc-win.c, player/scripting.c
Clients run in detached threads and are waited to signal when they are finished with self mpv_destroy() call. Problem is that after detached thread calls this function, mpv consider this client to be done and can do whatever. One example is when mpv exits and wait for scripts to finish we got race condition, because mpv (main thread) can exit first and the detached thread calls ta_free() which crashes, because we are we may already destoryed things that the thread depends on.
I've seen this crash in FreeBSD CI job (libmpv-lifetime test), where the libmpv.so has been unloaded while the thread was still doing ta_free()
```
==5081==ERROR: AddressSanitizer: SEGV on unknoun address 0x000001111806 (pc 0x000001111806 bp 0x7fffdedf4e40 sp 0x7fffdedf4e08 T40) ==5081==The signal is caused by a READ …
```
=> player/scripting: fix race condition when destroying clients

osdep/compiler.h, osdep/io.c, osdep/threads.h
C11 uses _Thread_local as the keyword, which thread_local macro is defined to (inside of <threads.h>, which mpv doesn't use): https://port70.net/~nsz/c/c11/n1570.html#7.26.1p3
C23 promotes thread_local to a keyword and marks _Thread_local as obsolete and to be avoided in new code:
https://www.iso-9899.info/n3220.html#6.4.1p3
so just use thread_local directly, which is future-proof while having a fallback define in osdep/threads.h for pre-C23 cases.
- - -
This came up during the https://github.com/mpv-player/mpv/pull/16164 discussion in IRC a couple days ago.
=> osdep/threads: prefer using thread_local

sub/sd_ass.c
Commit 77239b8 came to fix the unknown duration subtitle handling where once a packet with an unknown duration is found, then the entire context is flagged, which will trigger the redecoding sub logic to loop through all the packets again on every future packet decodes. This is true and we want to avoid having a loop that will go through all the packets that have been decoded in the past on every decode call, especially if the packets had their duration corrected already. But the mentioned commit also stated "packets with known durations get treated as if they were unknown," which is not entirely accurate.
The unknown duration subtitle handling works by altering the duration value of already decoded packets, not the newest packet. So when the context is flagged and caused new packets with …
=> sd_ass: handle past subs with unknown duration on every decode

.github/workflows/build.yml
FreeBSD supports only two latest minor versions, since 14.3 has been released, packages for 14.1 are not longer available. Bump to 14.2, since action doesn't have images for 14.3 yet.
=> ci/freebsd: update to 14.2

video/out/vo_dmabuf_wayland.c
Evidently it is possible for some compositors to trigger an external resize before the very first initial reconfig. This can't work and will fail in various ways. Check this case and bail out. Fixes #16202.
=> vo_dmabuf_wayland: don't resize if dst rect is 0

common/msg.h, sub/osd.h, sub/osd_libass.c
Some languages actually require strings to be valid UTF-8, unlike C which couldn't care less as long as it is NULL terminated.
Change triggered by Python support, but is also useful for Rust and Java.
=> {osd,msg}: use Unicode PU{1,2} for escape codes instead of invalid Unicode

DOCS/man/input.rst, DOCS/man/lua.rst, DOCS/man/options.rst
DOCS: remove references to the removed slave mode
DOCS/man/input: remove reference to the removed --clipboard-enable
DOCS/man/options: fix link to Conditional auto profiles
=> DOCS: misc fixes

player/lua/console.lua
Calling input.select() without a prompt argument was failing due to attempting to concatenate a nil value.
Before mpv 0.40 the prompt defaulted to ">" so this is expected to work as evident from the example code.
=> console.lua: default prompt to an empty string

video/decode/vd_lavc.c
If Vulkan hwdec is exposed by the system, use this as it provides better compatibility with native Vulkan rendering.
This avoid issues with importing VkImages through DMABUF interop from nvdec or vaapi on drivers that doesn't support DMABUF.
Try native Vulkan hwdec first which will resolve compatibility issues if available. If not it will fallback to using vaapi/nvdec like before.
If Vulkan rendering is not used it will also fallback to other hwdec options.
=> vd_lavc: prefer Vulkan hwdec when available

player/clipboard/clipboard-wayland.c
A "hung up" fd only indicates that the other end of the pipe is closed. This can happen when the other client has already sent some data into the pipe and closed its end. This should not be treated as an error, and reading data should proceed until read() returns 0 or -1.
Premuturely destroying offer in this case breaks getting selection data. Change it so that the cleanup on error happens after the selection data is read.
Fixes: d20ded876d27497d3fe6a9494add8106b507a45c
=> clipboard-wayland: read already sent data when the fd is hung up

DOCS/man/mpv.rst
Fixes: 62f225ef9d6e ("sub/osd: hide secondary subtitles if secondary-sub-visibility is false")
=> DOCS/man/mpv: document alt+v to toggle secondary sub track visibility

player/lua/osc.lua
This ensures that the next/previous buttons are appropriately enabled/disabled when the position of the currently playing entry is changed.
=> osc.lua: update OSC on playlist position changes

DOCS/interface-changes/console-exact_match.txt, DOCS/man/console.rst, DOCS/man/select.rst, player/lua/console.lua
console.lua: implement exact matching
Allow matching items exactly instead of fuzzily when prefixing the search with ' (like in fzf) or with --script-opt=console-exact_match=yes.
This is mainly useful to filter history entries chronologically.
You can also specify multiple search terms delimited by spaces. But ' makes every term an exact match, unlike fzf where you need to place it before every word, since we can't hook into fzy's algorithm.
Closes #14587.
console.lua: repurpose case_sensitive to only affect exact searches
case_sensitive originally only affected Tab completion. It defaulted to yes outside of Windows just to emulate the bad defaults of bash and zsh (not fish, which has better defaults and defaults to case-insensitive completion). This was already silly, but then it …
=> console.lua: implement exact matching

player/lua/select.lua
When the first edition is not at the start of the file but after the current time position, the current-edition property is -1, which prevented displaying any edition.
Fixes https://github.com/mpv-player/mpv/issues/16073#issuecomment-2787316609
=> select.lua: display editions when before the first edition

DOCS/interface-changes/console-focused-color.txt, DOCS/man/console.rst, DOCS/man/select.rst, player/lua/console.lua
The selected term was causing confusion e.g. in
https://github.com/mpv-player/mpv/pull/15711#issuecomment-2676060139. Saying either focused or current makes more sense since the item is not actually selected until you click or press Enter.
=> console.lua: say focused instead of selected

player/lua/console.lua
Center in the middle of the rectangle surrounded by the OSC instead of in the center of the window.
=> console.lua: center correctly within OSC margins

DOCS/man/options.rst, options/options.c
I'd rather not argue about which is better so go back to status quo, users can use the more sensible option of "simple" if it doesn't break anything (which it won't).
Using simple has benefits of growing memory usage slower and much faster OSD rendering when complex isn't needed.
Simple breaks rendering complex glyphs like Material font icons
=> sub/osd: set osd-shaper to complex by default

video/zimg.c
Fixes: 6a96b15cf48e75a1f2b17dccddf7ada95f3e0fcf ("video/csputils: add missing alpha choice")
Fixes: #16255
=> video/zimg: set alpha to ZIMG_ALPHA_STRAIGHT in all cases except premul

player/lua/console.lua
Pressing Ctrl+l with selectable items without having called input.get() earlier caused a crash.
Fixes a6024b562a.
=> console.lua: fix crash when pressing Ctrl+l

video/out/wayland_common.c, video/out/wayland_common.h
Useful for debugging issues with certain AMD GPUs that have problems that are only present in zero copy scenarios
=> wayland: log when direct scanout is active

video/out/wayland_common.c
make and model aren't guaranteed to be available, so print the name as well. This is usually just the connector name e.g. HDMI-A-1.
=> wayland: log output user-friendly wl_output name

DOCS/man/input.rst, player/clipboard/clipboard-wayland.c, video/out/wayland_common.c
This makes writing to clipboard property work on both the Wayland VO backend and `ext-data-control-v1` backend.
=> wayland: support clipboard writing

video/image_writer.c
This populates the AVCodecContext->bits_per_raw_sample field value when the pixel format of the screenshot being written doesn't match the pixel format of the original video. For example, if the original video was 10-bit and the screenshot is 16-bit, it populates this field so the encoder can make use of it.
Currently libjxl and png encoders are known to accept this tag and set the corresponding metadata (via BitDepthHeader, or sBIT).
This feature is only enabled if screenshot-sw=yes is enabled, because screenshots from a hardware buffer are always natively at max-depth.
Note: Duplicate of #11247  which was closed because of branch delete shenanigans I renamed the branch and this is a new PR after the comments in that one.
=> video/image_writer: tag bits_per_raw_sample when pixfmt changes

audio/out/ao_coreaudio.c, audio/out/ao_wasapi_utils.c, filters/f_hwtransfer.c, filters/f_lavfi.c, filters/f_swscale.c, player/clipboard/clipboard-wayland.c, sub/filter_sdh.c, video/out/vo_xv.c, video/out/wayland_common.c
void return type functions don't need a final return statement.
=> various: remove redundant return

misc/language.c, osdep/compiler.h, osdep/win32/smtc.cpp, video/out/d3d11/ra_d3d11.c
Fixes unterminated-string-initialization warnings.
=> misc/language: mark arrays as nonstring for GCC 15

DOCS/interface-changes/mediacodec_embed.txt, video/out/vo.c
Feature wise `mediacodec_embed` is even more limited than `dmabuf-wayland`, which we don't put as a default for good reasons.
It's also not like `gpu` is broken or badly supported on Android. It works fine and supports zero-copy hwdec.
(mpv-android has never defaulted to `mediacodec_embed` since its inception)
=> vo: move vo_mediacodec_embed to not be the default on Android

DOCS/man/options.rst
Elsewhere, the man page uses ‘equivalent to’ to mean ‘does the same thing as’.
This probably seems like a fussy little change but I promise you that I wasted a good ten minutes wondering why setting `--vlang` was not also setting the subtitle language, when the documentation asserted that `--vlang` was ‘equivalent to `--alang` and `--slang`’, which I incorrectly interpreted as meaning it was a shortcut for setting both at once.
=> DOCS/man/options: Equivalent -> Analogous

stream/stream_libarchive.c
Try using utf8 file path to improve compatibility when reading archives on Windows.
=> libarchive: try to use utf8 pathname

ci/build-win32.ps1
Until this is fixed upstream:
https://gitlab.freedesktop.org/gstreamer/meson-ports/ffmpeg/-/issues/56
=> ci/win32: pin ffmpeg revision to the latest working one

meson.build
video/out/gpu/d3d11_helpers.c requires it as well, and it's possible to have egl-angle-win32 enabled without d3d11.
=> build: move check for DXGI_DEBUG_D3D11 down

player/clipboard/clipboard-wayland.c
The data source requests are prepared inside create_data_sources from a different thread than the clipboard thread, so it is necessary to flush here. Otherwise, if mpv is not already managing the current selection, we'll have to wait until the clipboard thread reenters clipboard_wayland_dispatch_events for the request to be sent to the compositor and have the other clients be sent new the new selection, which may take up to 10 seconds.
=> clipboard-wayland: flush display after creating data sources

ci/build-win32.ps1
Also fixes jpegxl build after upstream changes. It wasn't enabled correctly before.
=> ci/win32: revert back ffmpeg to meson-7.1 branch

video/out/wayland_common.c
The locked_size restriction also prevents dragging from working on maximized and tiled windows. A compositor may choose to restrict this anyway (esp. tiling window managers), but there's no harm in sending the request if it supports it. The only thing we really need to block here is the fullscreen case. Fixes #16338.
=> wayland: allow potential dragging of maximized windows

demux/demux_lavf.c
To catch ffmpeg bugs early, instead of crashing or worse.
=> demux_lavf: check if context is correctly passed to callbacks by ffmpeg

sub/osd_libass.c
Rendering OSD on every frame draw is quite heavy, even if some of the rendering parts are cached, it still takes significant amount of time, depending of payload can take 8-10 ms just to do the text shaping.
Instead render only when we need it.
=> sub/osd_libass: don't rerender OSD if not changed

DOCS/interface-changes/tls-options.txt, stream/stream_lavf.c
Make `mpv https://aa.com/bbb.mp4 --tls-verify --tls-cert-file=~/.ssl/pubkey.pem --tls-key-file=~/.ssl/privkey.pem --tls-ca-file=~/.ssl/ca.pem` works when https://aa.com is protected by custom (self-signed) CA and tls client authentication.
Do we have a place to document that which options are "paths"/plain strings?
Closes #16323
=> options: parse tls-related options as path

player/command.c
c7c09fdb8b5ccfb91b44cb3d1e5184c92ef7a070 made frame step with seek flag ignore key ups. However, for commands with emit_on_up flag set, which can happen with mouse buttons, command should only be triggered on key ups. This results in frame-step command with seek flag triggered on mouse down instead of mouse up, and frame-back-step command not working with mouse.
Fix this by making sure that step is triggered depending on the emit_on_up flag.
Fixes: c7c09fdb8b5ccfb91b44cb3d1e5184c92ef7a070
Fixes: #16391
=> command: fix frame step with mouse buttons

audio/out/ao_avfoundation.m
Fix memory leak in ao_avfoundation caused by audio device switching https://github.com/mpv-player/mpv/issues/16283
=> ao/avfoundation: fix memory leak

.github/workflows/build.yml, ci/build-win32.ps1, ci/install-cmake.ps1
enable libaom for win32 msvc builds which used to encode avif screenshots.
fixed #16428 
Any idea to enable librav1e? I have tried a lot but cannot integrate it.
=> ci/win32: enable libaom

player/lua/stats.lua
f676a9ff201d18c3741e223e626874dc986f9819 changed some append_property calls to append, but append does not support the exclusion feature which results in "HW: no" shown when no hwdec is active when this was not displayed before.
Fix this by adding the exclusions in the get_property_cached calls.
Fixes: f676a9ff201d18c3741e223e626874dc986f9819
=> stats.lua: fix append_property exclusions

video/out/meson.build, video/out/opengl/context_wayland.c, video/out/vo_wlshm.c, video/out/vulkan/context_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h
Alternative to #14917. The downside is that this protocol is ungodly complicated. Upside is that more people seem to implement and in theory when the color management protocol lands upstream next decade it will be like this. So probably longer term this is better.
Weston atm doesn't support the minimum features we need so it's not good for testing other than making sure I didn't make a protocol error. kwin is probably the best but `xx-color-management-v4` is only supported in kwin master at the moment and not at release (release supports v2). So not really tested yet until I go compile a bunch of kde junk later. Mutter 47 seems to support `xx-color-management-v4` though.
TODO:
=> wayland: add support for wp-color-representation-v1

DOCS/man/lua.rst
This introduces an extra [block quote](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#block-quotes) that causes incorrect indentation in the rendered document:
https://github.com/mpv-player/mpv/blob/ed8954e8cf2d92d7f2df22aeeb9b6087f76ef89e/DOCS/man/lua.rst?plain=1#L177
This introduces an extra [definition list](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#definition-lists) that causes an unexpected bolding effect:
https://github.com/mpv-player/mpv/blob/ed8954e8cf2d92d7f2df22aeeb9b6087f76ef89e/DOCS/man/lua.rst?plain=1#L492-L493
(I found these when writing a [script](https://github.com/rkscv/dotfiles/blob/8399bfc77e75cf3491c2f541a50fa1d467da9012/mpv/mp/gen.py) to generate Lua language server [definition …
=> DOCS/man/lua: fix spacing issues

demux/cue.c
It is found in cue files output by cyanrip which currently can't be opened by mpv.
```
....
REM MEDIA_TYPE "CD"
REM COMMENT "cyanrip 0.9.3"
MCN "0000000000000"
TITLE "Unknown disc (...)"
FILE "1 - Unknown track.flac" WAVE
TRACK 01 AUDIO
TITLE "Unknown track"
INDEX 01 00:00:00
```
=> demux_cue: ignore mcn

player/lua/osc.lua
The volume icon in the OSC did not update when mute toggled or
volume changed while playback was paused and mouse was idle.
This commit adds observers for mute and volume properties to
request_tick(), ensuring OSC updates immediately on mute or
volume changes, even if playback is paused and mouse is idle.
=> osc.lua: fix volume icon not updating while paused

DOCS/interface-changes/prefetch-playlist.txt, DOCS/man/options.rst, options/options.c
This reverts decisions and documentation changes based on incorrect information on how `--prefetch-playlist` works.
=> --prefetch-playlist reverts

video/out/vo_gpu_next.c
If color space hint is enabled respect configured parameters of swapchain. When color space hint is disabled, override output freely.
This fixes possible fallback or other decisions about output made during the swapchain color space negotiation.
=> vo_gpu_next: if colorspace is set on swapchain respect its parameters

DOCS/interface-changes/vo-d3d11.txt, DOCS/man/input.rst, DOCS/man/options.rst, player/command.c, video/out/d3d11/context.c, video/out/gpu/context.h, video/out/gpu/d3d11_helpers.c, video/out/vo.c, video/out/vo.h, video/out/w32_common.c, video/out/w32_common.h
Add option to export d3d11 swapchain
=> video/out/d3d11: add d3d11 composition mode support

player/loadfile.c
We have 5 seconds limit for file playback, so 10 items it's bit much. 3 should be enough to cover some file switching and so on.
=> player/loadfile: limit playlist length to 3 for fuzzing

DOCS/man/options.rst
Implementing the ideas in https://github.com/mpv-player/mpv/pull/16520#discussion_r2195345686
=> DOCS/man/options: blend-subtitles affects hdr subtitle peak behavior

DOCS/man/input.rst
DOCS/man/input: only sequence prefixes need to be unbound
Make it clear that as long as a and a-b are not bound, the a-b-c binding works even if b is bound.
The 4-key limit for sequences was raised to 16 by a5dbf34094, because MP_MAX_KEY_DOWN is used for both the number of keys that can be held down and for the key history size. Just remove the related sentence since you're never going to need sequences longer than 16 keys.
=> DOCS/man/input: only sequence prefixes need to be unbound

DOCS/man/vo.rst, video/out/vo.c
Opening a PR to track discussion on this instead of retreading the same topics repeatedly each time we discuss it.
`vo_gpu_next` is already much better than the default `vo_gpu`, and the latter doesn't receive many bug fixes or testing from maintainers making changes elsewhere in the codebase. It doesn't make much sense to keep a default that doesn't receive much or any testing at all due to almost none of the mpv contributors using it. 
There are multiple steps to doing this:
1) Just move gpu-next above gpu in the probe order and change nothing else as this PR is doing. Receive user testing and feedback before the next step.
2) Rename `gpu-next` to `gpu`, rename `gpu` to `gpu-legacy` or `gpu-old`, alias `gpu-next` to `gpu`. And deprecate `gpu-legacy`.
Potential show stoppers:
High …
=> vo: move vo_gpu_next above vo_gpu in probe order

DOCS/encoding.rst, DOCS/interface-changes/encoding-profiles.txt, etc/encoding-profiles.conf, meson.build
fd4e3af740fc00804e3f1b932462b44f795b1095 originally started installing it, and we've been doing it ever since then. The value of having all of these encoding profiles predefined by default is pretty dubious since a lot of them are pretty old ('MP4 for Nokia N900' being a shining example) and mpv is not really a good encoding tool anyways. Let's treat it like the other conf files in etc and install it in the data directory for reference. If someone really uses these, they can copy the file over locally to their mpv config directory and it'll still work fine.
Alternative to #16526.
=> build: install encoding-profiles.conf into the system data directory

audio/out/ao.c, audio/out/ao.h, audio/out/ao_lavc.c, audio/out/buffer.c, audio/out/internal.h, common/encode_lavc.c, common/encode_lavc.h, player/audio.c, player/video.c, video/out/vo.c, video/out/vo.h, video/out/vo_lavc.c
cc @kasper93. I wrote this months ago and forgot about. After a quicker refresher, I *think* that all that needs to happen is for VO to wait until the AO is ready before it starts pushing frames. Because of mpv's initialization ordering, the VO will always be reconfigured first. But let me know if I misunderstood something here.
=> encode: simplify all initial blocking logic for encoding

video/out/gpu/video.c
Fixes oversaturation when pause/redrawn with Windows HDR mode on.
Fixes: https://github.com/mpv-player/mpv/issues/15130
=> video/out/gpu/video: fix target colorspace for redrawed frames

video/out/wayland_common.c
~First commit copies MESA's behavior instead of potentially partially setting metadata.~ Less strict than MESA now. Second commit does a simplified version (or I think anyway) of what vo_gpu_next does.
cc @kasper93
=> vo_dmabuf_wayland: improve hdr metadata validation

sub/ass_mp.c, sub/img_convert.c, sub/img_convert.h
We want to add padding around the whole bitmap, not within it. Smaller parts are rendered onto bigger bitmap. Remove leftover padding code.
Fixes: e2fc75434edeba95dacf2035871a6eb3809203f6
=> sub/ass_mp: revert some unwanted changes

sub/lavc_conv.c
WebVTT subtitles in WebM require special logic, and we signal that using the `webvtt-webm` codec name, which is not part of FFmpeg. That worked fine until #14330 added a call to `mp_codec_info_from_av()`, which overwrites our codec name with FFmpeg's the first time the subtitle decoder is initialized. As a result, subsequent initializations (when the subtitle track is changed at runtime) use the wrong codec name and don't take the WebM code path.
Fix the issue and also get rid of an unnecessary allocation.
=> Prevent WebM WebVTT sub corruption after switching subtitle tracks

DOCS/man/options.rst, stream/stream_dvb.c
If a card supports both DVB-T/T2 or DVB-S/S2, `channels.conf.{sat,ter}` was always interpreted as DVB-T2 / DVB-S2 before this change. After this change, using `channels.conf.{sat1,ter1}` will enforce interpretation as DVB-S/T.
The superior VDR channel config format is still the recommended solution for such cards as it allows to specify the delivery system variant per channel, but enforcing T2/S2 for cards supporting it whenever the zap format is used does not seem reasonable.
Solves the question described in #16467 , in which the commit was also tested with real hardware, without breaking backwards compatibility.
=> stream_dvb: allow to enforce DVB-S/T for old zap format channels.conf

demux/demux_libarchive.c
Opening paths that are detected as archives which contain '%[0-9A-Fa-f][0-9A-Fa-f]' will fail, because such sequence is treated as a percent-encoded value when the path gets unescaped causing the path to be mangled. Escape '%' to prevent this from happening.
Fixes: 2b280f4522a288429253b396b778d60ed018312c ("stream: libarchive wrapper for reading compressed archives")
=> demux_libarchive: escape '%' in stream URL path

.github/workflows/build.yml
It is available in image itself now.
See: https://github.com/actions/partner-runner-images/issues/77
=> ci: remove custom rust install step from windows-11-arm job

audio/filter/af_scaletempo.c, audio/out/ao_pipewire.c, misc/bstr.h, test/json.c, test/test_utils.c, video/hwdec.h, video/out/vulkan/context_display.c
Gets most of the easier pedantic warnings present, but not all. There are a lot of `dlsym` related ones in our code base which I do not have the ability to tackle at the moment. There are also a lot of warnings from my local install of `libspa`? Not sure if that's something occurring in other build environments.
=> build: clean up easier `Wpedantic` warnings

player/client.c
See the commit message. Can be reproduced with the following program:
<details><summary>leak.c</summary><p>
```
// Build with: gcc -o leak leak.c `pkg-config --libs --cflags mpv`
// Run with: valgrind --leak-check=full --show-reachable=no ./leak /path/to/file
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <mpv/client.h>
static void die(const char *msg) {
fprintf(stderr, "%s\n", msg);
exit(1);
}
int main(int argc, char *argv[]) {
if (argc != 2) {
die("pass a single media file as argument");
}
mpv_handle *ctx = mpv_create();
if (!ctx) {
die("failed creating context");
}
mpv_set_option_string(ctx, "input-default-bindings", "yes");
mpv_set_option_string(ctx, "input-terminal", "yes");
mpv_set_option_string(ctx, "terminal", "yes");
if (mpv_initialize(ctx) < 0) {
die("failed …
```
=> client: fix leak in mpv_command_{ret,node} if result argument is NULL

fuzzers/common.h, fuzzers/fuzzer_load.c, fuzzers/fuzzer_loadfile_direct.c, fuzzers/fuzzer_options_parser.c, fuzzers/fuzzer_set_property.c
Allows to specify custom fontconfig sysroot. Useful for fuzzing environments where we might use specific config, font or the system wide config is not available.
=> fuzzers: set fontconfig sysroot

DOCS/man/options.rst, video/out/vo_gpu_next.c
We don't know which colorspace the profile were created from. We could set hint to ICC target colorspace, but it would be ambiguous, because it doesn't say which colorspace were configured in practice.
Additionally on Wayland with all the color management the client side ICC correction is not supported, because we cannot set pass-through mode.
Conceptually we should use VK_COLOR_SPACE_PASS_THROUGH_EXT to get "direct" access to display response, but while this may work on macOS, on Wayland it means "don't configure csp", instead of "configure to pass-through", which means colorspace would have to be configured externally, which is also not possible, see [1].
You can also see [2] for more discussion on the topic.
For now let's not hint any colospace and leave libplacebo in default …
=> vo_gpu_next: don't hint colorspace when ICC profile is used

video/out/vo_gpu_next.c
Also double check if 1e-7 doesn't underflow float.
=> vo_gpu_next: don't use unitialized min_luma in some cases

DOCS/man/options.rst, video/out/vo_gpu_next.c
When ICC profile is applied, use it also in hint to ensure correct target colorspace configuration.
Fixes: #16646
=> vo_gpu_next: respect ICC profile color space

video/out/mac_common.swift
add event handler for when window's occlusion state changes and now indicates some or all of the window is visible.
handling of the event is needed due to the addition of a visibility check for rendering that was added in commit 5010c24.
Fixes #16693
=> mac/vulkan: fix frame not displayed when paused

DOCS/man/options.rst, video/out/mac/common.swift, video/out/mac/window.swift, video/out/mac_common.swift
add support for the force-redraw option analogous to wayland and x11.
since commit 5010c24 the initial window always shows a black frame instead of the actual first rendered frame of the video, since the visibility for the initial render is always false. in the worst case the first shown frame wasn't the intended first rendered frame. initial always allow the first render even when the window is still hidden.
@low-batt this should fix the other issue mentioned here https://github.com/mpv-player/mpv/issues/16693#issuecomment-3195051293
=> mac: add support for force-render and fix initial black frame

TOOLS/lua/autocrop.lua
hwdec-current can be either "no" or nil.
Fixes #16739.
=> TOOLS/lua/autocrop.lua: don't error if hwdec-current is nil

player/lua/ytdl_hook.lua
Youtube uses VP9.2 for HDR videos. Previously, this would result in the codec appearing as `null` in the console and track selection menu, and as H.264 in stats page 1.
=> ytdl_hook.lua: add support for VP9 profile 2

player/lua/console.lua
The first completion is automatically inserted when Tab was not pressed, but this is unwanted when you already typed one of the completions which is not the first one, move back the cursor and press Enter.
e.g. if the line is "set vid", you place the cursor before "v" and press Enter, it runs "set ab-loop-avid".
Fix this by aborting when the text in front of the cursor matches one of the completions.
=> console.lua: don't autoselect the wrong completion

video/out/mac/title_bar.swift
when the window is snapped to a position by dragging the title bar the corresponding left mouse up event is prevented by the system snap event, which leads to the window moving state not being reset and no mouse position changes being reported. which makes UI elements unresponsive.
explicitly subscribe to left mouse up events for the whole app instead of the mouse events from the title bar and reset the moving state.
Fixes #16732
=> mac/title: fix mouse position when snapped to position from title bar

.github/workflows/build.yml, DOCS/interface-changes/mpv-register.txt, DOCS/man/options.rst, ci/build-mingw64.sh, ci/build-win32.ps1, etc/mpv-register.bat, etc/mpv-unregister.bat, meson.build, options/options.c, options/options.h, osdep/w32_register.c, osdep/w32_register.h, osdep/win32-console-wrapper.c, player/main.c
I deleted the branch by accident and it nuked the PR, which cannot be reopened for recreated branches. Old PR: #15904
=> osdep/w32_register: add register/unregister options for Windows

.github/workflows/build.yml, meson.build, osdep/mac/dialog.swift, osdep/mac/meson.build, osdep/mac/swift_compat.swift, player/command.c
fixes various things mentioned in #16765
some additional info why some fixes are needed and what errors they causd:
`command: fix type mismatch` fixes https://github.com/Akemi/mpv/actions/runs/17528518682/job/49782276161?pr=32#step:7:449
`osdep/mac/meson.build: fallback to swift build for old swift versions` fixes https://github.com/Akemi/mpv/actions/runs/17528658752/job/49782581357?pr=32#step:7:553 see also #15591 and #15594
`meson: properly add path-mac.c to path_source and don't overwrite it` https://github.com/Akemi/mpv/actions/runs/17531954401/job/49790052456?pr=32#step:11:164
=> mac: various build fixes for older systems and build toolchains

meson.build
it doesn't make sense to build the swift parts without cocoa because the swift bridge would be missing and it's impossible to interact with the swift parts from obj-c, swift depends on cocoa/appkit/etc, and the cocoa main function/main loop is missing making anything cocoa/appkit/GUI crash on use.
like this it is possible to build mpv on macOS without cocoa, it will fallback to the unix main function and mpv can run in 'headless' mode, eg you can use it from CLI, it won't spawn any App icon/menu/etc, and you can use everything that isn't related to cocoa/appkit/GUI like audio playback. anything other will make mpv segfault, for example sdl2 and its vo, since it tries to spawn a window.
this was possible before, by disabling cocoa and swift independently. this is just some convenience i …
=> meson: disable swift when cocoa not available or disabled

video/out/d3d11/context.c
fix  https://github.com/mpv-player/mpv/issues/16773
It not easy to get the target display when using composition mode 
just return and set color space outside
=> video/out/d3d11: return unknown color space when use d3d11 composition mode

.github/workflows/build.yml, ci/build-macos.sh
depends on #16770 (see https://github.com/Akemi/mpv/pull/34 with the fixes from the PR)
this i meant to catch usages of not available features and not properly guarded features. we use the newest runner with the newest SDK und target our lowest target macOS version (atm 10.15). this should prevent broken builds on older versions. the actual build is partially unusable since the resulting binary/bundle uses libs with the wrong target version, hence why i excluded it from upload artifact step.
CC/CCX was added in https://github.com/mpv-player/mpv/pull/12431
target error example (c/obj-c) https://github.com/Akemi/mpv/actions/runs/17585388806/job/49951891735?pr=33#step:7:795
target error example swift https://github.com/Akemi/mpv/pull/33
=> ci/mac: add test runner for oldest macOS target

DOCS/interface-changes/vo-d3d11.txt, DOCS/man/options.rst, options/options.c, options/options.h, player/command.c, video/out/d3d11/context.c, video/out/w32_common.c, video/out/w32_common.h
When using the composition mode, there’s no window and no way to set the output size. 
This adds changing size support for composition mode, based on the Android surface size code. 
Also, composition mode isn't limited to Win32; it can be used in UWP too.
Is it appropriate to place **vo_w32_composition_size** and **vo_w32_swapchain** in w32_common?
I'm not sure, or where they should be placed.
=> video/out/d3d11:  add changing size support for composition mode

video/out/wayland_common.c
Fixes: 39c9d1acb498b9ea5db2bd862cb0411c96979e14 ("video/out/vulkan/context_wayland: implement target_csp for wayland")
=> video/out/wayland_common: fix crash when uninit without display

DOCS/man/input.rst
Use the same wording as expand-text and similar commands.
This was misleading, see https://github.com/po5/thumbfast/issues/84#issuecomment-1525746798
=> DOCS/man/input: document that screenshot-raw works in scripts

DOCS/interface-changes/configurable-sub-fix-timing.txt, DOCS/man/options.rst, options/options.c, options/options.h, sub/sd.h, sub/sd_ass.c, sub/sd_lavc.c
Instead of hardcoding the threshold and keep duration in a header, expose them as options for users to configure and set old hardcoded values as the new defaults for those options.
Fixes #16865
=> sub: make --sub-fix-timing configurable

video/out/vo_dmabuf_wayland.c
The video viewport source rectangle is prevented from being set while force_window, but we should also unset it because it will be set if a video is played before entering force_window. Fixes out_of_buffer error from Weston and wlroots in this scenario.
=> vo_dmabuf_wayland: unset video viewport source when force_window

video/out/wayland_common.c
These have nothing to do with whether the compositor supports set_mastering_display_primaries protocol feature or not and are always available
=> wayland: always set max_cll/max_fall
