mpv-player/mpv

video/decode/dxva2.c
video/mp_image.c

I was watching a video with rotation metadata and it wasn't rotated with --hwdec=dxva2-copy. It seems like this stuff should be copied onto the software image.
I'm not sure if I've done this the right way. I had a look at mp_image_copy_attributes, but it didn't copy the rotation field. Should mp_image_copy_attributes be augmented and used instead? Also, should this be done with vaapi-copy as well?

DXVA2: Copy the image parameters

---

waftools/detections/compiler.py

j1() isn't available when ``__STRICT_ANSI__`` is defined.
Related MinGW-w64 feature request:
https://sourceforge.net/p/mingw-w64/feature-requests/68/

Fix Windows build for the ewa_lanczos stuff

---

osdep/subprocess-win.c

I don't think this will affect real-world usage, unless there are some weirdly named programs in the %PATH%, but it should make it more correct.

Fix a corner case for quoting argv[0] in subprocess-win

---

audio/out/ao_wasapi_utils.c

I've been having trouble with ao_wasapi on my work laptop (Windows 7, SigmaTel STAC9228 sound card.) It would only successfully select a format when the sample rate of the file matched the mix format. With other sample rates, it would try to select a matching format and fail init ([log][1].)
I think this was happening because the old code misinterpreted the docs and treated AUDCLNT_E_UNSUPPORTED_FORMAT as success instead of failure in shared mode (see the commit message.) This patch fixes it for me by treating that return code as failure, so it will fall back to the mix format.
Interestingly, none of my machines at home have this problem because they never fail in IsFormatSupported and always return the mix format in ``closestMatch``.
[1]: …

Fix WASAPI format selection for unsupported formats in shared mode

---

osdep/subprocess-posix.c

this was generating a warning, because apparently __GLIBC__ is not
defined in cygwin, but "extern char **environ;" is still in unistd.h

osdep/subprocess-posix: remove __GLIBC__ guard

---

RELEASE_NOTES

scale-radius=3 is the default, so use 2 as an example
Point out that ewa_lanczos (Jinc) is actually new.

A few tweaks to the 0.80 release notes

---

audio/out/ao_wasapi.c
audio/out/ao_wasapi.h
audio/out/ao_wasapi_utils.c

Moving these operations to the audio thread ensures that these operations are never happening simultaneously with thread_feed, which makes life much simpler.
I also made the pre-filling of the buffer happen only if there is less than a full buffer of audio already waiting to be played. This seems to be the key to remove fixing #1529 for me.

Move resume and reset into the wasapi audio thread

---

wscript

On cygwin 'win32' wasn't detected because it is 'os-cygwin' 
Even after fixing this, most of the required libs weren't getting linked because check_libs apparently doesn't do what's expected. Use check_cc instead.

build: fix missing windows libraries

---

osdep/subprocess-win.c

I forgot about empty arguments.
The second commit is cosmetic. Windows argument escaping is kind of weird and I don't think the old code explained it well.

Small fixes for subprocess-win

---

audio/out/ao_wasapi.c
audio/out/ao_wasapi.h
audio/out/ao_wasapi_changenotify.c
audio/out/ao_wasapi_utils.c
audio/out/ao_wasapi_utils.h

Create a second copy of the change_notify structure for the hotplug
ao. The hotplug change_notify is distinguished by not having its
"monitored" member set since it does not watch a single device.

ao/wasapi: add ao hotplug

---

DOCS/man/vo.rst
video/out/gl_video.c
video/out/gl_video.h

This can be used to draw the subtitles at the video's native res, which
can make them look more natural and increases performance.

vo_opengl: add blend-subtitles-res

---

DOCS/waf-buildsystem.rst

The gender specific pronoun is changed, since we shouldn't assume the
gender of the user.
The sentence itself is also changed to be more correct in general.
This pull request is made because the previous one was incorrectly submitted, and was assumed to be a troll.
https://github.com/mpv-player/mpv/pull/1798

DOCS/waf: Edit --enable-feature sentences

---

video/out/w32_common.c

VLC and MPC-HC also make a power request like this while playing. This _shouldn't_ be necessary for audio-only streams because it seems like the audio stack makes its own request, however I'm not sure if this is the case for all drivers.

Prevent the machine from going to sleep when a video-only stream is played

---

DOCS/man/input.rst
player/command.c
player/core.h
player/discnav.c
stream/discnav.h
stream/stream_bluray.c
stream/stream_dvdnav.c

This property indicates whether mouse cursor is located on button
or not for disc naviation.
This is useful for instance, not to override mouse button click with some other single click action for GUI.

command: disc-mouse-on-button property

---

DOCS/mplayer-changes.rst

Since joystick support was removed and is a difference from mplayer, it should be included in the document with the mplayer changes. It will help new users who were using mplayer's joystick support to seek alternatives when switching to mpv. It will also be helpful for people that had problems with the joystick support in mplayer (for example, by incorrectly recognizing other input devices as joystick) to know that those problems won't persist in mpv.

DOCS/mplayer-changes.rst: Eleborate on joystick input

---

video/out/w32_common.c

The old code didn't work for multiple-monitors, so fix it by passing the device name of the monitor we want to EnumDisplaySettings.
This includes a commit to amend the list of "rounded down" frame rates to include all multiples of 24 and 30 under 144Hz. As suggested by @avih, but I think I added more frame rates than the ones he mentioned (up to 144Hz instead of 120Hz.)

Windows: Use the refresh rate of the current monitor

---

common/common.c
common/common.h
video/out/x11_common.c

Right now, the default behavior is to pick the numerically lowest screen
ID that overlaps the window in any way - but this means that mpv will
decide to pick an ICC profile in a pretty arbitrary way even if the
window only overlaps another screen by a single pixel.
The new behavior is to query it based on the center of the window
instead.

x11: query ICC profile based on center of window

---

video/csputils.c

The previous version of this logic resulted in black crush and incorrect
brightness scaling when combined with limited range (TV) output.

csputils: improve contrast semantics for limited range output

---

video/sws_utils.c

This lets us avoid having to maintain two separate copies of the
colorspace mapping functions.

sws_utils: re-use avcolorspace for sws colorspaces

---

video/out/vo_opengl.c

The current code just segfaults.

vo_opengl: switch to new OpenGL backend API for icc-profile-auto

---

options/options.c

Since we're on the topic of consistency, I've seen multiple users
complain about the presence of this period, which does not really match
other programs' behavior.

options: remove the period at the end of "No file."

---

video/filter/vf_vdpaurb.c

I took this out because I thought the filter chain would auto-negotiate
using nv12 without the explicit hint, and it does in the basic case
with no intermediate filter, but once you start adding filters, it
can end up negotiating a different format and then failing.

vf_vdpaurb: query_format is still required

---

video/out/opengl/hwdec_vaegl.c
video/out/vo.c

This was previously trying to use the `video_output_vaapi` symbol despite vo_vaapi.c being guarded by the vaapi-x11 option.

Fix compilation failure in vo.c when vaapi is enabled and x11 disabled

---

video/out/opengl/angle.c
video/out/opengl/common.c

Move [glGetTexLevelParameter][1] out of the ES 3.0 group and into one for ES 3.1.
[1]: http://docs.gl/es3/glGetTexLevelParameter

Fix ANGLE GLES3 mode

---

audio/out/ao_wasapi.c

otherwise we were incorrectly adjusting the hardware master volume
in exclusive mode with softvol=auto

ao_wasapi: only report per-app volume in shared mode

---

player/misc.c
video/out/vo.h
video/out/w32_common.c

This also shuffles around some logic in the VOCTRL handler to save horizontal space (rather than adding an extra level of indentation.)

Don't show the Windows taskbar progress indicator in idle mode

---

DOCS/man/options.rst
DOCS/man/vf.rst
DOCS/man/vo.rst
audio/out/ao_wasapi.c
audio/out/ao_wasapi.h
audio/out/ao_wasapi_utils.c
audio/out/ao_wasapi_utils.h

get rid of the vistablob in wasapi for setting AV thread priority. Now that we are Vista+, this should just always be available.

Wasapi no vistablob

---

video/out/opengl/w32.c
video/out/win32/exclusive_hack.c
video/out/win32/exclusive_hack.h
wscript_build.py

As mentioned in the commit message, this is an awful hack, but maybe not too awful. OTOH it prevents tearing in fullscreen with dwmflush=auto.

Test for exclusive mode using the undocumented __DDrawExclMode__ mutex

---

DOCS/man/vo.rst
video/out/w32_common.c

This hijacks the update_display_fps function(), turning it into update_display_info().

Implement icc-profile-auto for Windows

---

video/out/opengl/dxinterop.c

This also makes the backend behave better on lost devices, since previously it just crashed. Now it will try to reset the device on each swap_buffers call.

Prevent DX_interop crash with 0-sized window

---

osdep/path-win.c

cygwin was giving undefined reference to `FOLDERID_Desktop' at link time

path-win: include initguid.h

---

audio/out/ao_wasapi.c

Apparently it's only wine where the qpc_position returned by
IAudioClock_GetPosition can be overflowed. So actually do the rescaling
correctly, but throw away the result if it looks unreasonable.
this fixes  #2665

ao_wasapi: fix delay calculation again

---

DOCS/man/mpv.rst
osdep/win32-console-wrapper.c
stream/stream_file.c

msvcrt.dll programs can inherit fds from each other in Windows. libuv/node.js also supports MSVC-compatible fd inheritance.
Tested with these two programs:
```c
#include <io.h>
#include <fcntl.h>
#include <process.h>
int main()
{
static const char exe[] = "C:\\path\\to\\mpv.com";
static const char file[] = "C:\\path\\to\\some\\file.mkv";
int fd = open(file, O_RDONLY | O_BINARY);
dup2(fd, 7);
return spawnl(P_WAIT, exe, exe, "fd://7", NULL);
}
```
```javascript
'use strict';
const fs = require('fs');
const spawn = require('child_process').spawn;
const exe = 'C:\\path\\to\\mpv.com';
const file = 'C:\\path\\to\\some\\file.mkv';
spawn(exe, ['fd://7'], {
stdio: [0, 1, 2, null, null, null, null, fs.openSync(file, 'r')],
});
```

Fix fd:// on Windows

---

demux/demux.c
demux/demux.h
sub/ass_mp.c
sub/ass_mp.h
sub/lavc_conv.c
sub/sd_ass.c
video/decode/vd_lavc.c

This PR wires up `AV_FRAME_DATA_A53_CC` side data in mpeg2 frames to the `eia_608` decoder in ffmpeg using sd_ass.
The pipeline is working as expected, with side data getting enqueued as subtitle packets:
```
[lavf] packets=76, bytes=969015, active=1, more=0
[lavf] append packet to sub: size=60 pts=9.590611 dts=9.590611 pos=6334660 [num=1 size=60]
[cplayer] video_output_image: 2
[lavf] packets=77, bytes=969075, active=1, more=0
```
Then being read by the demuxer:
```
[lavf] reading packet for sub
[lavf] reading packet for sub
[cplayer] Sub: c_pts=9.507 s_pts=-59413.507 duration=-1.000 len=60
[lavf] packets=76, bytes=969015, active=1, more=0
```
And finally being decoded by libass in sd_ass:
```
[libass] Event: Dialogue: 0,-16:-30:-14.-89,-16:-30:-13.-51,Default,,0,0,0,,THAT THE …
```

Add support for A/53 Closed Captions

---

audio/out/ao_openal.c

Previously used opt_exclusive option to decide which volume control code to run.
The might not always reflect the actual state, for example if passthrough
is used. Admittedly, none of the volume controls will work anyway with
passthrough, but this is the right thing to do.

ao_wasapi: use share_mode value instead of raw option opt_exclusive

---

audio/out/ao_openal.c

Previously this would break all further attempts to init the driver after one
had failed.

ao_openal: wipe out global context on init error

---

audio/out/ao_wasapi.c
audio/out/ao_wasapi.h
audio/out/ao_wasapi_changenotify.c
audio/out/ao_wasapi_utils.c

the main thing here is that this more correctly avoids an ao-reload when the default device is changed (usually via windows control panel), but the user has already told mpv to use a specific ```audio-device``` independent of the system default. The other two commits are minor fixups.

Wasapi default change

---

TOOLS/lua/ao-null-reload.lua

Only triggers if ao=null. This is required for ao=wasapi to recover from periods
with no available devices.
fixes #2738

TOOLS/lua/ao-null-reload.lua: send ao-reload on audio-device-list change

---

video/decode/dxva2.c
video/dxva2.c
video/dxva2.h
wscript_build.py

This is the first step towards getting opengl interop. It allows the individual surfaces can pass beyond the dxva2 decoder and be passed to the vo.
This also adds additional data to mp_image->planes[0] for IMGFMT_DXVA2, which is
required for maintaining and releasing the surface even if the decoder code is
uninited.
The IDirectXVideoDecoder itself is encapsulated together with its surface pool
and configuration in a dxva2_decoder structure whose creation and destruction is
managed by talloc.

use pool for dxva2 hwdec surfaces 

---

video/out/opengl/hwdec.c
wscript
wscript_build.py

Wasn't really necessary as it was equivalent to gl-dxinterop.

wscript: remove dxva2-dxinterop configure test

---

audio/out/ao_wasapi.c
audio/out/ao_wasapi.h
audio/out/ao_wasapi_utils.c

These commits were motivated by short "pops" heard around once a minute when using exclusive mode to play to an HRT microStreamer DAC. It was discovered that reducing the exclusive mode buffer size to the device period made this problem go away. It would seem that provided you can feed the device fast enough, exclusive mode works best when the buffer size is equal to the device period as suggested by the [MSDN example code](https://msdn.microsoft.com/en-us/library/windows/desktop/dd370844%28v=vs.85%29.aspx).
The problem is that we had previously increased the buffer from this value because there were under-run problems (particularly when toggling fullscreen) and glitches on unpausing/seeking. The former seems to have already been fixed by the previous refactor that switched to using an …

Fix wasapi thread loop latency problems in exclusive mode

---

DOCS/man/options.rst
DOCS/man/vo.rst
video/out/opengl/hwdec.c
video/out/opengl/hwdec_dxva2egl.c
wscript_build.py

This implements dxva2 interop on the ANGLE backend. It appears impossible to either access the NV12 planes in the D3D9 surface produced by dxva2, or to pass them to D3D11, where they should be accessible. Therefore this also uses the magic StretchRect like dxinterop. Getting unmangled RGB will require using ffmpeg's dx11va API, which is another kettle of fish.

Angle dxva2 d3d9

---

video/out/opengl/context_dxinterop.c
video/out/opengl/hwdec_dxva2gldx.c

Previously, gl->DXOpenDeviceNV was called twice using dxva2 with dxinterop. AMD
drivers refused to allow this. With this commit, context_dxinterop sets its own
implementation of MPGetNativeDisplay, which can return either a
IDirect3DDevice9Ex or a dxinterop_device_HANDLE depending on the "name" request
string. hwdec_dxva2gldx then requests both of these avoiding the need to call
gl->DXOpenDeviceNV a second time.

vo_opengl: only open one OpenGL/DX interop handle when using dxva2

---

DOCS/compile-windows.md

* Use the update-core command
* CC=gcc is no longer necessary
* Don't recommend adding /mingw64/bin to the %PATH% as this can cause problems
with other things (i.e., cygwin). Instead just copy the required DLLs where
needed.
* Recommend winpty
* Add note about ANGLE

DOCS/compile-windows.md: update MSYS2 instructions

---

audio/format.c
audio/format.h
audio/out/ao_lavc.c
audio/out/ao_wasapi_utils.c

audio: add af_select_best_samplerate function
This function chooses the best match to a given sample rate from a provided
list. This can be used by the ao to decide what samplerate to use for output.
This is then used in `ao_wasapi` exclusive mode and and `ao_lavc`. The behaviour is of `ao_wasapi` is unchanged as this essentially moves it's sample rate selection logic to `audio/format.c`. This is an improvement for `ao_lavc`, which previously failed when attempting to output a sample rate incompatible with the codec (i.e., opus).

Select best samplerate

---

DOCS/compile-windows.md

Apparently, you aren't supposed to use msys2 pkg-config for mingw stuff.

DOCS/compile-windows.md: use mingw pkg-config in msys2 instructions

---

DOCS/man/ipc.rst
DOCS/man/options.rst
input/input.h
input/ipc-unix.c
input/ipc-win.c
input/ipc.c
options/options.c
player/main.c
wscript_build.py

I definitely think named pipes are the right transport for IPC on Windows. This overloads the --input-unix-socket option to take a pipe name on Windows. Clients can connect to this pipe and send JSON or text commands.
Should resolve #2917, #2381 and #1882 (though two are already closed.)
**Note:** This probably shouldn't be merged just yet. It's in more of an RFC stage at the moment. I need to do a bit more testing (for example with QLocalSocket clients.)

Implement JSON IPC on Windows with named pipes

---

video/decode/d3d.c
video/decode/d3d11va.c
video/decode/dxva2.c

move Intel_H264_NoFGT_ClearVideo to lower priority so that H264_E is preferred. Also add some debugging about which decoder is selected and fix a missing newline.
Fixes #3059.

Deprioritize clearvideo

---

TOOLS/appveyor-build.sh
TOOLS/appveyor-install.sh
appveyor.yml

Because seemingly innocuous changes tend to break on Windows :)
Test builds are logged here: https://ci.appveyor.com/project/rossy/mpv (It will probably be necessary to create an account for mpv if this is merged.)
This uses MSYS2 for the build, which comes pre-installed in the Appveyor image. It pulls in a few more dependencies than the Travis build, but I think it would be good to make sure bits like the ANGLE code build as well.
This doesn't run the cmocka tests, but I couldn't get them to link and I noticed Travis doesn't run them either.

Add Appveyor CI integration for Windows builds

---

DOCS/man/vf.rst
DOCS/man/vo.rst
misc/bstr.c
misc/bstr.h
video/csputils.c
video/csputils.h
video/out/opengl/nnedi3.c
video/out/opengl/nnedi3.h
video/out/opengl/superxbr.c
video/out/opengl/superxbr.h
video/out/opengl/user_shaders.c
video/out/opengl/user_shaders.h
video/out/opengl/utils.c
video/out/opengl/utils.h
video/out/opengl/video.c
video/out/opengl/video.h
video/out/opengl/video_shaders.c
video/out/opengl/video_shaders.h
wscript
wscript_build.py

This makes it possible for users to define and use their own shaders like SuperRes, CrossBilateral, etc. in the vo_opengl pipeline.
Notably, things like superxbr, debanding and unsharpen are now just “regular” hooks internally. In fact, they could be replaced by a drop-in user shader with absolutely no difference, so in the future we could maybe remove them from vo_opengl's codebase entirely (and include them in etc/ or so).
Worth mentioning is that this series of commits includes one FIXME in the code, which is a preservation of the status quo (the same bug is in master currently). Fixing that bug should be a high priority, but I didn't want to delay this pull request even further. (It's also only a minor issue, related to chroma offset off-by-ones on rotated video)
This series of …

User hooks (larger vo_opengl refactor)

---

DOCS/man/vf.rst
DOCS/man/vo.rst
misc/bstr.c
misc/bstr.h
video/csputils.c
video/csputils.h
video/out/opengl/nnedi3.c
video/out/opengl/nnedi3.h
video/out/opengl/superxbr.c
video/out/opengl/superxbr.h
video/out/opengl/user_shaders.c
video/out/opengl/user_shaders.h
video/out/opengl/utils.c
video/out/opengl/utils.h
video/out/opengl/video.c
video/out/opengl/video.h
video/out/opengl/video_shaders.c
video/out/opengl/video_shaders.h
wscript_build.py

Currently, this relies on the user manually entering their display
brightness (since we have no way to detect this at runtime or from ICC
metadata). The default value of 250 was picked by looking at ~10 reviews
on tftcentral.co.uk and realizing they all come with around 250 cd/m^2
out of the box. (In addition, ITU-R Rec. BT.2022 supports this)
Since there is no metadata in FFmpeg to indicate usage of this TRC, the
only way to actually play HDR content currently is to set
``--vf=format=gamma=st2084``. (It could be guessed based on SEI, but
this is not implemented yet)
Incidentally, since SEI is ignored, it's currently assumed that all
content is scaled to 10,000 cd/m^2 (and hard-clipped where out of
range). I don't see this assumption changing much, though.
As an unfortunate consequence of …

vo_opengl: implement HDR (SMPTE ST2084)

---

video/out/opengl/common.c

The ANGLE guys merged their patch in google/angle@7d20dd4, so this should work with ANGLE master and the ANGLE DLLs from Chromium build 2768 onwards. With older ANGLE it will fail to load the extension with a warning message.

Use GL_EXT_disjoint_timer_query for timers on ANGLE

---

video/out/opengl/context_angle.c

This will happen when D3D11 is present on the machine but the supported feature level is too low, eg. on feature level 9_3 hardware.
I'm not 100% sure if the eglTerminate is required.

Try the D3D9 ANGLE backend when eglInitialize fails for D3D11

---

osdep/mpv.rc

I think this will fix rossy/mpv-install#6. For some reason Windows 10 1511+ doesn't include programs without version info in the Default Programs dialog.

Re-add version info to mpv.rc

---

video/out/wayland_common.c

Hopefully switching to xdg_shell instead of the old wl_shell will solve at least some problems.

wayland: reject resize events with either dimension being 0

---

player/client.c

I had another look at this and I think the changes are correct, whereas with the old code, there was always the possibility of missing property change events that should have been generated.

Don't miss property changes after the property is updated

---

audio/out/ao_wasapi_changenotify.c
audio/out/ao_wasapi_utils.c
osdep/path-win.c
video/decode/d3d.c
video/decode/d3d11va.c
video/decode/dxva2.c
video/filter/vf_d3d11vpp.c
video/out/opengl/context_angle.c
video/out/opengl/context_dxinterop.c
video/out/opengl/hwdec_d3d11egl.c
video/out/opengl/hwdec_d3d11eglrgb.c
video/out/w32_common.c
waftools/detections/compiler.py
waftools/fragments/wasapi.c
wscript

This should solve some sporadic linking errors. As in 622bcb0, it takes advantage of the fact that __declspec(selectany) prevents multiple definitions of each GUID, so it's safe to define INITGUID in multiple files.
See also the second note here: https://support.microsoft.com/en-us/kb/130869

Build with -DINITGUID on Windows

---

options/m_option.h
options/options.c
player/command.c
player/main.c

I hope it's okay to waste an option flag on a single option. It seems like all the other UPDATE_* flags cover more than one option.

Make Windows process priority runtime-settable

---

DOCS/man/input.rst
video/out/w32_common.c

This should make display-names usable on Windows.

Implement VOCTRL_GET_DISPLAY_NAMES on Windows

---

options/options.c

I agree that my changes can be relicensed to LGPL 2.1 or later. (do I still need to keep this text here since I've already indicated my consent in #2033). I notice that there, I only agreed for contributions prior to "signing". I guess I can't agree for code that isn't written yet? 
Facilitates changing exclusive mode at runtime. This is usefull for conditionally
bypassing audio filters and mixers added by the operating system when outputting
PCM mode.

audio: add audio-exclusive property

---

DOCS/man/osc.rst
player/lua/osc.lua

Someone suggested this in IRC.
Didn't add for filters because there's no selected/disabled properties for those and they're generic lists done with just `script-message osc-message "Video filters:\n${vf}\n\nAudio filters:\n${af}"`
And they're not keybinds because you can't change the duration with those‽

osc: add script message handlers for chapter/track/playlists

---

DOCS/man/osc.rst
player/lua/osc.lua

- ~~selectively disable elements when reaching a certain playresX/aspect?~~
- use same code as box/slimbox and additionally scale after a certain min-width is reached
- ~~change default sub positioning to not be covered by osc~~
- ~~`sub-margin-y=50` (this breaks box layout since subs are now covered by it)~~
- ~~higher boxalpha (affects readability with white video)~~
- let 0.21.1 stay with layout=bottombar so all issues get fixed and if people still complain about it change in 0.22.0
- ~~change before 0.21.1 and never hear about bottombar issues again~~
Ref: https://github.com/mpv-player/mpv/pull/3631, #3728

top/bottombar: address issues

---

player/lua/osc.lua

@ChrisK2 
I didn't understand why, though, since reproduction is kinda hard to trigger.

osc: fix crashes when dragging seekbar across file changes

---

DOCS/compile-windows.md
wscript

This fixes waf setting the wrong LIBDIR for DEST_OS=win32 in
waflib/Tools/c_config.py:get_cc_version()
Any scripts assuming the implib and pkgconfig are in the wrong
place should be changed to move the .dll instead.
@rossy

wscript: move install dirs setting to after C compiler check

---

osdep/compiler.h
osdep/win32-console-wrapper.c
ta/ta.h
video/out/vo.c
video/out/vo_direct3d.c
wscript

This should get mpv on mingw-w64/Clang into a mostly-working state, and it fixes some minor issues that Clang found.

Some fixes for mingw-w64/Clang

---

video/decode/d3d11va.c

I tested this and it seems to fix the crash in #3348 for me. It's hard to tell though, since without the fix it crashes randomly. (I wish I knew why it was crashing in the first place.)

d3d11va: unconditionally load D3D DLLs

---

video/out/wayland_common.c

Fixes a segfault introduced in libwayland e8ad23266f36521215dcd7cfcc524e0ef67d66dd, where a poison value has been introduced to catch this kind of use-after-free bug.

wayland: destroy input before closing the display connection

---

video/out/w32_common.c

According to MSDN, [SetWindowLong](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633591(v=vs.85).aspx) and [GetWindowLong](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633584(v=vs.85).aspx) have been superseded by `SetWindowLongPtr` and `GetWindowLongPtr`.
It doesn't fix or break anything in this particular case, just a cosmetic code change.

win32: update winapi functions names

---

video/out/w32_common.c

A few improvements and bug fixes to the window styles:
- Added `WS_MINIMIZEBOX` to the `NO_FRAME` styles, which allows minimizing the borderless or fullscreen window by clicking on the taskbar button or pressing <kbd>Win</kbd>+<kbd>↓</kbd> hotkey.
- I didn't add the `WS_MAXIMIZEBOX` style because it will break the fullscreen switching once the borderless windows is maximized by <kbd>Win</kbd>+<kbd>↑</kbd> hotkey. Also there's no much sense in maximizing the borderless window, since there's no difference between that and just switching to fullscreen.
---
- Removed `WS_SIZEBOX` from the `FRAME` styles, since it is already included in `WS_OVERLAPPEDWINDOW` (`WS_SIZEBOX` is the same as `WS_THICKFRAME` according to MSDN)
---
- Added `FULLSCREEN` styles set which is the same as `NO_FRAME` but …

win32: window styles improvements

---

DOCS/interface-changes.rst
DOCS/man/options.rst
options/options.c
options/options.h
osdep/macosx_compat.h
video/out/cocoa/events_view.h
video/out/cocoa/events_view.m
video/out/cocoa/mpvadapter.h
video/out/cocoa/window.m
video/out/cocoa_common.m

this is based on pigoz native-fs branch with various bug fixes and additions.
this fixes some bugs:
- overlaying menu bar and dock when mpv is not focused #3272 #2857
- disappearing window in fs on some resolutions #1352 #2062
- hidden menu bar and dock on other screens when focusing mpv in fullscreen
- a rare segfault on quit #3864
- broken icc profile retrieval in some specific cases #3241?
there is one regression, the fullscreen window can't be forced to only one specific screen anymore. this only affects the case when the windowed window is on a different screen then the desired fullscreen window (properties: screen != fs-screen).
there is one problem i couldn't solves. sometimes an error pops up `[vo/opengl] after creating framebuffer texture: OpenGL error …

cocoa: fullscreen refactoring

---

video/out/w32_common.c

According to MSDN, in [WM_SYSCOMMAND](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646360(v=vs.85).aspx) messages, the four low-order
bits of the wParam parameter are used internally by the system.
To obtain the correct result when testing the value of wParam,
an application must combine the value 0xFFF0 with the wParam
value by using the bitwise AND operator.

win32: fix for wm_syscommand

---

video/out/cocoa/window.h
video/out/cocoa/window.m
video/out/cocoa_common.m

there is one minor issue. if you cycle the border it doesn't properly redraw the title bar and the transparent part of the rounded corner is missing. resizing the window manually fixes it. so a possible workaround would be to temporarily resize the window by a pixel. though this seems a bit hacky. i couldn't find a method which would update the window decoration.

cocoa: add border cycling

---

video/out/cocoa_common.m

this uses the previously unused displaylink callback to rate limit the video output.
this fixes problems when rendering off-screen (different space), mpv being completely hidden behind another window and on mission control.

cocoa: rate limit video output

---

video/out/cocoa/window.m

fixes the first issue from #3944.
i can't completely remember why i only set this when in fullscreen, but i believe it is a remnant of a different attempt when i tested my initial native-fs attempt. i removed the functions since it is only used at one place. it was initially in a function because i used it at several places and it did more than just setting one variable. it was since refactored and simplified and doesn't have a purpose anymore.

cocoa: fix window size in certain circumstances

---

player/lua/osc.lua

before:
after:
---
after:
*until 100 chars*
after 100 chars:

Improve osc title readability

---

misc/charset_conv.c
misc/charset_conv.h
player/external_files.c

this is an attempt to fix #4016 without breaking something else again. i am not too sure if i handled the memory management properly, specifically the `talloc_steal` calls.

cocoa: consistent normalisation when searching for external files

---

DOCS/man/options.rst
osdep/windows_utils.c
video/out/opengl/angle_dynamic.h
video/out/opengl/context.c
video/out/opengl/context_angle.c
video/out/opengl/egl_helpers.c
wscript

I think I'm happy with this change now. The only thing missing is documentation for the new options (which I should do before this is merged.)
Ping @avih, @wiiaboo and @kevmitch, if you're interested, since this should fix some issues with performance and behaviour that I think you guys experienced with the old ANGLE backend. It should reliably play back 24fps video on 24Hz displays now and it shouldn't mess up the desktop when leaving fullscreen, since it now uses flip-mode present without getting DirectComposition involved.
**Note:** These changes require the latest ANGLE DLLs. Specifically, the version of ANGLE in MSYS2 is too old. See [this comment][1] for instructions on how to get the latest version.
[1]: https://github.com/mpv-player/mpv/pull/4114#issuecomment-277560247

Rewrite ANGLE backend with custom D3D11 swap chain

---

DOCS/man/options.rst
options/options.c
options/options.h
video/out/cocoa_common.m

this adds an option to modify the ontop level. this could be reused on other platforms too. i added two predefined levels, which i thought were the most common use cases. additionally it's possible to just use an integer to define the level by hand.
i am not too sure if i should use the "cocoa" in the commit title or something more general, since the option can be used on other platforms in the future but it's only implemented on macOS so far.

add --ontop-level option for modifying ontop window level

---

TOOLS/osxbundle/mpv.app/Contents/Info.plist
TOOLS/osxbundle/mpv.app/Contents/MacOS/mpv-wrapper.sh
TOOLS/osxbundle/mpv.app/Contents/Resources/mpv.conf
osdep/macosx_application.m

since this fixes the same thing as #4095 and some additional issues i decided to open another PR.
other than this. i believe we don't need to check for and remove the "-psn_" argument anymore since the wrapper doesn't pass any arguments, that were passed to the wrapper, to the mpv binary. we also don't need it anymore for the heuristic if it were started from the bundle. it was replaced we a simpler environment variable based check.
the second commit is a bit debatable as in, what login level should be used? just using 'warn' might be not enough since it doesn't log what file was opened/played.

cocoa: improve bundle situation

---

video/out/cocoa/events_view.h
video/out/cocoa/events_view.m
video/out/cocoa/mpvadapter.h
video/out/cocoa_common.m

first of all i am going to squash both commits since the second commit depends on the first one. i kept them separate for now since both commits fixed separate things and i tested them individually.
i tried to simplify the mouse event handling a bit and removed some special cases that each tried to fix a problem a previous change introduced without getting to the root of the problem. i believe and hope that this should be fixed now and no unnecessary mouse movements should be reported any more.
for the second commit i had to change the cursor visibility code (yet again). all current problems i know of could be fixed with slight adjustments to the current code, besides issue #3856. i am not quite sure how the macOS notifications are implemented but they don't trigger any events and i …

cocoa: mouse event and cursor refactor

---

DOCS/man/options.rst
libmpv/opengl_cb.h
video/out/opengl/hwdec.c
video/out/opengl/hwdec_ios.m
wscript_build.py

Implements --hwdec=videotoolbox on iOS. Similar to hwdec_osx.c, but using CVPixelBuffer APIs available on iOS instead of the equivalent IOSurface APIs in macOS.

hwdec: implement videotoolbox on iOS

---

wscript

This seems to be what's breaking the AppVeyor build.

Fix --egl-angle-lib for waf 1.9

---

DOCS/man/options.rst
options/options.c
options/options.h
osdep/macosx_compat.h
osdep/macosx_versions.h
video/out/opengl/context_cocoa.c

i can't test it myself and i also don't feel very strongly about it. it fixes #3242 and possibly partially #3653. it could also be used as a workaround for #2371.
i dropped support for OS X 10.7 and earlier to simplify the context creation which is a bit buggy because of the if directive. in some circumstances it could remove kCGLPFAAccelerated instead of kCGLPFASupportsAutomaticGraphicsSwitching, which would only be fixable with another if directive. 10.7 isn't supported officially anymore anyway

OSX add option to force dedicated GPU

---

video/out/w32_common.c
video/out/win32/droptarget.c
video/out/win32/droptarget.h
wscript_build.py

I think I promised to do this a while ago. This makes w32_common.c a bit simpler.

Split the IDropTarget implementation into a separate file and refactor

---

DOCS/man/options.rst
video/out/opengl/context_angle.c

This could be an alternative to setting ``angle-egl-windowing=yes`` to solve issues like #4263, and other issues caused by flip-model presentation on older drivers.
I had no idea DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL even worked on Windows 7, but apparently it does.

Add --angle-flip to set the presentation model used by ANGLE

---

osdep/macosx_application.m
osdep/macosx_application_objc.h
osdep/macosx_events.h
osdep/macosx_events.m
osdep/macosx_events_objc.h
osdep/macosx_touchbar.h
osdep/macosx_touchbar.m
player/main.c
waftools/fragments/touchbar.m
wscript
wscript_build.py

this partially implements support for the features wanted in issue #3943. the missing part is support for the `MediaPlayer` framework. though like @rcombs mentioned, from his tests there is a problem with the MediaPlayer support and when mpv is started from CLI. it only works completely when started from the bundle.
i tested building it on 10.10 and it worked, though i couldn't test playback because it was in a VM. visually it can probably be improved, though i'll leave major changes for another time. i wasn't sure if i should use the input_context or the mpv_handle for touchbar inputs. i decided to use the old mechanic, the input_context, like the rest of the code.
for the header/license text i just copied what is used in all the other files.
how it looks:

osx: initial Touch Bar support

---

DOCS/interface-changes.rst
DOCS/man/options.rst
etc/builtin.conf
input/input.c
osdep/macosx_application.m
osdep/macosx_compat.h
osdep/macosx_events.h
osdep/macosx_events.m
osdep/macosx_events_objc.h
video/out/cocoa/events_view.m
video/out/cocoa/mpvadapter.h
video/out/cocoa/window.m
video/out/cocoa_common.m

this fixes two bugs. one where some key presses are not reported correctly. @pigoz already noticed this behaviour with his [initial native-fs](https://github.com/mpv-player/mpv/commit/31a80aa1d4c7c5a2f6dc6965aed404326b362d02#diff-3a9bee9141665c32c50a7a49664f5ba5R744) implementation. the other wasn't noticed since it only happens with a borderless window and `--input-app-events=no`, which is activated by default. fixes part of issue #3944.
first some insight on the second bug. it can be reproduced with `mpv --no-config --input-app-events=no --no-border` and toggling fullscreen. it will lead to key inputs not working anymore and the "no key input" error sound. after quite a bit of testing i could establish that the change from a NSWindowStyleMaskBorderless style mask to a style mask without …

cocoa fixes for key events

---

sub/sd_ass.c

sdh filter returns NULL when subtitle line should be skipped

sub: sdh filter fix for null

---

player/lua.c
player/lua/ytdl_hook.lua

With string joining I was seeing 2GB usage on mpv before lua complaining about "not enough memory".
Using a temporary string allocated inside the last for-loop and joining that with the edl was still going to 1.5GB but worked better.
Using table.insert instead mpv/lua doesn't go beyond tens of MB and seems faster too.
Should fix https://github.com/mpv-player/mpv/issues/4355 at least until the 64MB limit is reached again.

ytdl_hook: increase limits and rework edl joining

---

input/cmd_list.c
input/cmd_list.h
input/cmd_parse.c
input/input.c
input/input.h
input/keycodes.h
player/command.c
video/out/w32_common.c

This changes how axis input works with non-scalable commands (commands other than seek and add/cycle) so the command is only fired when the user has scrolled one full unit. It also changes w32_common to emit MP_AXIS_* events instead of MP_MOUSE_BTN* for the scroll wheel.
In general, I want to remove the distinction between MP_AXIS_* and MP_MOUSE_BTN{3,4,5,6}, since they tend to cause user confusion and the one that's used depends on the operating system and the hardware (touchpads or notched scroll wheels.) The next step would probably be deprecating MP_MOUSE_BTN{3,4,5,6} in favour of MP_AXIS_* and/or synthesizing MP_MOUSE_BTN* input when MP_AXIS_* events are received (this isn't done yet.)

Improve axis input with non-scalable commands, and use MP_AXIS on Windows

---

audio/out/ao_wasapi.c
osdep/threads.c
osdep/win32/include/pthread.h
osdep/win32/pthread.c

This finally works in Visual Studio 2017 15.3 Preview. Hopefully other debuggers add support.

Use the new thread naming API on Windows

---

player/lua/ytdl_hook.lua

I noticed 289b115 improved playback of ytdl URLs that include a start time by making a manually set time take precedence. This change will enable that same behavior for resuming from watch_later files.

ytdl_hook: don't override start time set by saved state

---

audio/out/ao_pulse.c

Right now, the current order pretty much means that pulse defaults to
S16 for arbitrary unsupported formats, but fallback to float would make
more sense since it's the easiest to convert everything to without
requiring dithering, and PA will probably just internally convert things
to float anyway.
Also move S32 above S16, which essentially means format_maps is sorted
by preference. (Although ao_pulse currently ignores this and always
picks the first as a fallback)

ao_pulse: reorder format choice

---

DOCS/man/options.rst
video/out/opengl/common.c
video/out/opengl/context.c
video/out/opengl/video.c
video/out/opengl/video_shaders.c
video/out/opengl/video_shaders.h

This is more efficient on my machine (nvidia), but only when applied to
groups of exactly 4 texels. So we switch to the more efficient
textureGather for groups of 4. Some notes:
- textureGatherOffset seems to be faster than textureGather by a
non-negligible amount, but for some reason, textureOffset is still
slower than a straight-up texture
- textureGather* requires GLSL 400; and at least on nvidia, this
requires actually allocating a GL 4.0 context.
- the code in opengl/common.c that clamped the GLSL version to 330 is
deprecated, because the old user shader style has been removed
completely in the meantime
- To combat the growing complexity of the polar sampling code, we drop
the antiringing functionality from EWA shaders completely, since it
never really worked well for EWA to begin …

vo_opengl: use textureGatherOffset for polar filters

---

audio/out/ao.c
audio/out/ao_wasapi_utils.c
audio/out/pull.c
misc/ring.c

audio/out: correct copy length in ao_read_data_converted 
Previously, the entire convert_buffer was being copied to the destination without
regard to the fact that it may be packed and therefore smaller.
The allocated conversion buffer was also way to big
bytes * (channels * samples) ** 2
instead of
bytes * channels * samples
----
ao_wasapi: reorder channels and samplerates to speed up search
This shouldn't affect which are chosen, but it should speed up the search by
putting more common configurations earlier so that a working sample format and
sample rates can be found sooner obviating the need to search them for each
iteration of the outer loops.
--- 
fix some typos

audio: fix packed 24 bit output and enable it in wasapi

---

audio/out/ao_wasapi_utils.c

The biggest change here is that the format search is not repeated during the align hack. I actually found that my laptop's integrated sound chip does actually require this hack for playing 24 bit audio in exclusive mode, so consider this tested.
Interestingly, I wasn't able to reproduce the DEVICE_IN_USE / DEVICE_INVALIDATED errors. The associated retry might be a future candidate for removal, but for now play it safe and leave as is.

Miscelaneous wasapi fixes

---

DOCS/man/options.rst
player/lua/ytdl_hook.lua

Requested in IRC for sites which youtube-dl seems to have trouble with parsing (private sites with http auth), or, with direct URLs, saving whole 2 seconds.

[RFC] ytdl_hook blacklist

---

video/out/opengl/common.c
video/out/opengl/common.h
video/out/opengl/utils.c
video/out/opengl/video.c
video/out/opengl/video_shaders.c

Mesa 17.1 supports compute shader but not full specs of OpenGL 4.3.
Change the code to detect OpenGL extension `GL_ARB_compute_shader`
rather than OpenGL version `4.3`.
The compute polar code also utilized OpenGL extension
`GL_ARB_arrays_of_arrays`, so add it as a requirement as well.
Tested with Intel HD 4000 graphics card on Linux (Mesa 17.1.4). Upscaling
1280x720 video to 1920x1080 with `scale=ewa_lanczossharp`.
pass rendering time: 46.3 ms -> 18.5ms

vo_opengl: enable compute shader for mesa

---

video/out/opengl/utils.c

Someone reported this error with an older Intel GPU: https://pastebin.com/raw/gWv2zzUM
I think this is the right solution.

Fix image uniforms for older OpenGL

---

DOCS/man/options.rst
misc/bstr.c
misc/bstr.h
stream/stream_memory.c
video/out/opengl/user_shaders.c
video/out/opengl/user_shaders.h
video/out/opengl/video.c

Second attempt at user-loadable textures, this time more principled and less hacky.
PR mostly for comments, also cc @bjin feel free to test.
Usage example:
```glsl
//!HOOK MAIN
//!BIND HOOKED
//!BIND DISCO
//!COMPONENTS 3
vec4 hook()
{
return vec4(texture(DISCO_raw, HOOKED_pos * 3).rgb, 1);
}
//!TEXTURE DISCO
//!SIZE 3 3
//!COMPONENTS 3
//!FORMAT 32f
//!FILTER NEAREST
//!BORDER REPEAT
00 00 80 3f
00 00 00 00
00 00 00 00
00 00 00 00
00 00 80 3f
00 00 00 00
00 00 00 00
00 00 00 00
00 00 80 3f
00 00 00 00
00 00 80 3f
00 00 80 3f
00 00 80 3f
00 00 00 00
00 00 80 3f
00 00 80 3f
00 00 80 3f
00 00 00 00
9a 99 99 3e
9a 99 99 3e
9a 99 99 3e
9a 99 19 3f
9a 99 19 3f
9a 99 19 3f
00 00 80 3f
00 00 80 3f
00 00 80 3f
```

Gl user tex2

---

DOCS/man/options.rst
video/out/opengl/user_shaders.c
video/out/opengl/user_shaders.h
video/out/opengl/utils.c
video/out/opengl/utils.h
video/out/opengl/video.c

This allows users to do their own custom sample writing, mainly meant to
address use cases such as RAVU. Also clean up the compute shader code a
bit.

vo_opengl: make compute shaders more flexible

---

DOCS/man/options.rst
options/options.c
options/options.h
video/out/cocoa/mpvadapter.h
video/out/cocoa/window.m
video/out/cocoa_common.m

rather self explanatory.
i tried to keep the code of the none-native fullscreen as separate as possible, so it is a bit easier to maintain. though it leads to some minor code duplications.

cocoa: add an option to disable the native macOS fullscreen

---

osdep/macosx_application.h
osdep/macosx_application.m
osdep/macosx_application_objc.h
osdep/macosx_menubar.h
osdep/macosx_menubar.m
osdep/macosx_menubar_objc.h
wscript_build.py

yeah this is just some eye candy because i felt like doing something simple. i put all the menubar related code into its own file since it would just mess up the application file.
in general this should make the life of unexperienced macOS users easier. i put things into the menu which i thought were commonly used, but feel free to suggest other functions you think should be added. i mostly didn't add any shortcuts (yet), though this can be discussed here too.
the "Preferences" menu item just opens the config file from two predefined locations in TextEdit. if no config file is found an alert is shown which asked the user to create one. this could probably improved.
the "Open File" menu item opens the usual open file dialog from macOS. it can open multiple files and folders.
the "Manual" …

macOS menubar refactor

---

video/filter/vf_d3d11vpp.c
video/mp_image.c

Introduced in 8f2ccba71bb4. Also silence an unused variable warning that was introduced in the same commit.

Fix missing config.h in mp_image.c

---

wscript

The first one (line 140) comes from 69650851f8 and is the correct one.
The second one (line 731) comes from 72a8120daa and slipped in with the
revert commit.
Remove the second one.

build: remove duplicate android option after 72a8120da

---

video/out/gpu/context.c
video/out/vulkan/common.h
video/out/vulkan/context_win.c
wscript_build.py

This has been tested and seems to work.
One problem is that mpv spams messages like this on resize:
```
[vo/gpu/vulkan] Requested width 1392 does not match current width 1395
[vo/gpu/vulkan] Requested height 783 does not match current height 784
[vo/gpu/vulkan] Requested width 1419 does not match current width 1423
[vo/gpu/vulkan] Requested height 798 does not match current height 800
```
I think this is because resizing on Windows happens asynchronously from the perspective of the vo thread. Resizing still works though.

Add support for Vulkan on Windows

---

DOCS/man/options.rst

The gpu-gamma had been changed to gamma-factor,
but that change had not been reflected here. This fixes that.

manpage: update --blend-subtitles affected options

---

stream/dvb_tune.c
stream/dvbin.h
stream/stream_dvb.c

This changeset implements support for ATSC terrestrial / cable widespread in North America, which is a mix of ATSC and DVBC_ANNEX_B delivery systems actually, differentiation done by the modulation parameter. 
It also adds some more verbosity to the tuning part (if requested), a fallback to DVBv3 tuning if things go wrong, and parsing of the modulation parameter from VDR config files for any delivery system. 
Tested with DVB-S/S2 by me (which now also profits from parsed modulation) and ATSC terrestrial and cable by @bpaterni . 
This fixes the #4922 regression. 

DVB v5 tuning fixes, VDR format extensions, ATSC cable / terrestrial fixes

---

video/out/gpu/spirv_shaderc.c

Ping @haasn. This is useful for debugging issues with SPIRV-Cross, since it adds symbol information to the output.

Include debug info in shaderc generated SPIR-V when --gpu-debug is set

---

DOCS/man/options.rst
video/out/gpu/video.c

This change is from my ra-d3d branch, but it doesn't seem particularly Direct3D specific. Maybe it could be useful if there are Vulkan implementations out there that don't support rgba16?

Add rgba16hf to the list of FBO formats

---

demux/demux_playlist.c
osdep/io.c
osdep/io.h
waftools/detections/compiler.py

This should fix opening directories as playlists on Windows. It should also enable the filesystem loop checking in demux_playlist.c. There was an attempt to keep io.c UWP-compatible (see ``#if !HAVE_UWP``,) but it's untested.

Add more-POSIXy versions of open() and fstat() on Windows

---

video/out/opengl/context_android.c

The old code for some reason assumed constant size from creation onward...

vo_gpu/context_android: Process surface resizes correctly

---

osdep/io.c
osdep/io.h

The freelocale() fix is probably important, because otherwise mp_archive_free() won't work as expected. This also silences some warnings.

Fix semantics of Windows POSIX 2008 locale stubs

---

player/client.c

client: Allow "C.UTF-8" as LC_NUMERIC locale (for Android)

---

DOCS/man/mpv.rst

bluray:// is an alias for bd://, but this
isn't actually documented anywhere.
This should fix that.

DOCS/mpv.rst: document bluray:// alias for bd://

---

video/out/opengl/hwdec_vaegl.c

Now actually in upstream libva and the Intel driver, to be released in 2.1 (VAAPI 1.1.0 or later).
https://github.com/01org/libva/commit/fcb9cc881596d7ff809adf5f6ff631c708d407e3
https://github.com/01org/intel-vaapi-driver/commit/106d1eb730210b498c1f9fca9f4f5c3df82d056d
I'll reenable it in Mesa as well soon.

vo_opengl: hwdec_vaegl: Reenable vaExportSurfaceHandle()

---

video/out/drm_atomic.c
video/out/opengl/context_drm_egl.c
video/out/opengl/hwdec_drmprime_drm.c

The change to always use ARGB8888 format used with the DRM primary
plane (commit: 762b8cc30007480f06d338ac77d6e91cc04cd320) causes --gpu-context=drm to break on drivers which do not
support this, e.g. intel sandy bridge.
Instead we probe to see if the driver supports ARGB8888, falling back
on XRGB8888 if this is not available. If neither is available it is treated as an error.
When the driver does not support DRM atomic, we always use XRGB8888.
The reason being that the change to use ARGB8888 is primarily
motivated by the need to have the primary plane (with OSD only in this
case) above the overlay plane (the video) when using --hwdec=rkmpp
(hwdec_drmprime_drm), which also needs DRM atomic. Without DRM atomic
we cannot use that hwdec anyway, and without the hwdec everything will
always be …

video: in context_drm_egl only use ARGB8888 format for framebuffer if hardware supports this on the primary plane + various bugfixes

---

DOCS/man/options.rst

vaapi-copy works with some AMD cards (only tested with RX 470)

manpage: vaapi-copy is not limited to Intel GPUs

---

audio/aconverter.c
audio/filter/af_lavcac3enc.c
audio/out/push.c
common/recorder.c
demux/ebml.c
player/loadfile.c
player/video.c
video/out/gpu/lcms.c
video/out/opengl/hwdec_vaegl.c

I tried to keep it strictly to things that are clearly a bit off, and not just odd style choices such as the RANDOM SHOUTING in the dvb code.

Fix various typos in log messages

---

DOCS/man/options.rst
options/m_option.c

Previously when using a libmpv instance to play multiple videos,
once --start was set there was no clear way to unset it. You could
use --start=0, but 0 does not always mean the beginning of the file
(especially when using --rebase-start-time=no). Looking up the start
timestamp and passing that in also does not always work, particularly
when the first timestamp is negative (since negative values to --start
have a special meaning).
This commit adds a new "none" value which maps to the internal
REL_TIME_NONE, matching the default value of the play_start option.
cc @thebombzen @jeeb #5175

options: add --start=none to reset previously set start time

---

player/lua/ytdl_hook.lua

Using youtube-dl's metadata ends up with stupid things like missing
variant streams, or missing audio streams entirely.

ytdl: handle HLS with FFmpeg

---

osdep/terminal-unix.c

POSIX permits select() to modify the timeout, which can happen on the Linux implementation. This can reset the timeout, which spins this into a tight loop. A timeout isn't necessary in the first place, so just use NULL instead.
Addresses the performance issues @wm4 mentioned in #5195

Fix terminal thread performance issues

---

osdep/polldev.c
osdep/polldev.h
osdep/terminal-unix.c
wscript_build.py

This implements a poll-compatible interface, backed by select on macOS, suitable for polling on device files - which are not supported by macOS's implementation of poll. This is a (long-standing) bug in macOS,
so hopefully we can eventually remove this shim.
This fixes #5199

osdep: add poll shim for macOS

---

demux/demux.c
demux/demux.h
demux/demux_timeline.c

Deals with cases where timeline support and the seekable packet cache interfere. See commits.

Some packet cache fixes/improvements

---

player/osd.c

There was a compilation warning after the commit 0433162
````
../player/osd.c: In function 'set_osd_bar_chapters':
../player/osd.c:361:50: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
ab_loop_start_time != MP_NOPTS_VALUE && opts->ab_loop[1] != MP_NOPTS_VALUE) {
````
Fixed it by adding suggested parentheses, also split the line to fit in 80-char length.
Moved a curly bracket to a new line, as suggested in contribute.md for complex conditional statements.

osd: fix a compiler warning by adding parentheses in if condition

---

video/out/opengl/hwdec_drmprime_drm.c

When autoprobing the hwdec interops (which now happens to all compiled
interops if hardware decoding is used), failure to load an interop
should not print an error in the normal case. So hide it.
(We could make the log level conditional on whether autoprobing is used,
but directly loading it without autoprobing is obscure, and most other
interops don't do this either.)

vo_gpu: hwdec_drmprime_drm: silence error on failed autoprobing

---

video/filter/vf_convert.c

Full range YUV causes problems everywhere. For example it's usually the
wrong choice when using encoding mode, and libswscale sometimes messes
up when converting to full range too. (In this partricular case, we
found that converting rgba->yuv420p16 full range actually seems to
output limited range.)
This actually restores a similar heueristic from the late vf_scale.c.

vf_convert: default to limited range when converting RGB to YUV

---

video/out/w32_common.c

mpv doesn't use `WM_USER` for wakeup events since 91079c0
Updated the comment.

w32_common: update outdated comment about wakeup events

---

options/m_option.c

The same idea as in 3723e61 but for OPT_FLAG now.
Before the change:
-----
````
mpv --border=help
Invalid parameter for border flag: help
Valid values are:
yes
no
(passing nothing)
Error parsing option border (option parameter could not be parsed)
Setting commandline option --border=help failed.
Exiting... (Fatal error)
````
````
mpv --border=sdjfkhlsdfh
Invalid parameter for border flag: sdjfkhlsdfh
Valid values are:
yes
no
(passing nothing)
Error parsing option border (option parameter could not be parsed)
Setting commandline option --border=sdjfkhlsdfh failed.
Exiting... (Fatal error)
````
After the change:
-----
````
mpv --border=help
Valid values for border flag are:
yes
no
(passing nothing)
````
````
mpv --border=sdjfkhlsdfh
Invalid parameter for border flag: sdjfkhlsdfh
Valid …
```

options: don't report errors on help value for OPT_FLAG and OPT_COLOR

---

sub/sd_ass.c

Included are the new RFC8081 font media types, and the .otc file extension should now be recognized.
References:
- [RFC 8081](https://tools.ietf.org/html/rfc8081)
- [OpenType Font File Specification](https://www.microsoft.com/typography/otspec/otff.htm)
`font/woff` and `font/woff2` were deliberately not added because they were previously excluded as well.

Font Detection Fixes

---

DOCS/man/javascript.rst
DOCS/man/lua.rst
player/javascript.c
player/lua.c

I saw mention on the IRC that a `stat()` would be nice to have for the Lua and Javascript scripts, so I had a go at it. Sadly, no issue exists.
Thanks to `mp_stat()` being provided for Windows, this was pretty easy!
This *has* been tested on Linux (Ubuntu) for both Lua and Javascript. Works fine!
This has *not* been tested on Windows, but as it doesn't try to do anything cross-platform by itself and relies on the already-used `mp_stat()` being defined as `stat()` in `osdep/io.h`, it *should* work on Windows as well.

lua+js: Implement and document utils.stat()

---

osdep/subprocess-win.c

By default the CreateProcess changes the mouse cursor to IDC_APPSTARTING (or whatever it is called):
This is very noticeable when using the [mpv_thumbnail_script](https://github.com/TheAMM/mpv_thumbnail_script) script.
The cursor won't change to default arrow until the script finishes generating thumbnails.
The new flag added to `STARTUPINFOEXW` prevents changing the cursor from default arrow on creating a new process.

subprocess-win: don't change the mouse cursor in CreateProcess

---

options/m_option.c

The same idea as in 3723e61 but for `OPT_SIZE_BOX` now.
Affects options `autofit`, `autofit-larger` and `autofit-smaller`.
Before the change:
-----
````
mpv --autofit=help
Option autofit: invalid size: 'help'
Valid format: W[%][xH[%]] or empty string
Error parsing option autofit (option parameter could not be parsed)
Setting commandline option --autofit=help failed.
Exiting... (Fatal error)
````
After the change:
-----
````
mpv --autofit=help
Valid format: W[%][xH[%]] or empty string
````

options: don't report errors on help value for OPT_SIZE_BOX

---

player/command.c
stream/dvb_tune.c
stream/dvb_tune.h
stream/dvbin.h
stream/stream_dvb.c

Now tuners with multiple frontends work.
I have Astrometa DVB-T2: https://www.linuxtv.org/wiki/index.php/Astrometa_DVB-T2
where:
frontend0 - DVB-T
frontend1 - DVB-T, DVB-T2 and DVB-C ANNEX A.
Our local broadcasting is DVB-T2, so without this path I cant watch TV.
On play list load mpv query all frontends and add channels with capable DVB type, also capable frontend num saved with channel props to future use while tuning.
There was bug: channels switched exponentially long time, I suspect this some how connected with play time:
[statusline] AV: 00:00:42 / 00:00:00 A-V: -0.000 Cache: ???+1MB
was not reset, so next channel not start play while ~40 seconds.
My fix is change:
mpctx->stop_play = PT_RELOAD_FILE;
to
mpctx->stop_play = PT_CURRENT_ENTRY;
in dvb commands handle function.
Probably …

DVB: Add multiple frontends support: MAX_FRONTENDS now 8.

---

video/out/opengl/hwdec_drmprime_drm.c

Using vulkan with --hwdec crashed because of this.

vo_gpu: hwdec_drmprime_drm: don't crash for non-GL contexts

---

DOCS/client-api-changes.rst
DOCS/man/options.rst
etc/builtin.conf

This was off for mpv CLI, but on for libmpv. The motivation behind this
was that it would be confusing for applications if libmpv continued
playback in a severely "degraded" way (without either audio or video),
and that it would be better to fail early.
In reality the behavior was just a confusing difference to mpv CLI, and
has confused actual users as well. Get rid of it.
Not bothering with a version bump, since this is so minor, and it's easy
to ensure compatibility in affected applications by just setting the
option explicitly.
(Also adding the missing next-release-marker in client-api-changes.rst.)

client API: change --stop-playback-on-init-failure default

---

video/out/w32_common.c

Refactored `reinit_window_state` function:
Moved all the code related to fitting window on screen in a separate function `fit_window_on_screen`.
Also simplified that code a lot to make it easier to read and added a few debug messages.
Fixed #4753 by disabling the above mensioned code in `fit_window_on_screen` for a maximized window, since maximized window should already fit on the screen just fine.
It should be noted that this bug was only reproducible with `--fit-border` option which is enabled by default. The cause of the bug is that after calling the `add_window_borders` for a maximized window, the rect in result is slightly larger than the screen rect, which is okay, `SetWindowPos` will interpret it as a maximized state later, so no auto-fitting to screen size is needed here.
In …

w32_common: refactor and improve window state handling

---

DOCS/man/options.rst
video/out/vo_mediacodec_embed.c
wscript

Fixes vo_mediacodec_embed, which was broken in 80359c6615658f2784
Confirmed working with ffmpeg-master in mpv-android by @sfan5

Fix vo_mediacodec_embed using latest ffmpeg

---

wscript

Using a string caused all 4 flags to be passed as one argument, causing
the build to fail when trying to include bcm_host.h.

build: use a list instead of a string for rpi cflags

---

DOCS/man/input.rst
DOCS/man/mpv.rst
DOCS/man/options.rst
demux/demux.c
player/lua/osc.lua
player/osd.c
stream/cache.c

These changes have the goal to make the demuxer cache the default for network operation.
This raises the demuxer readahead limit to practically unlimited (well, 10 hours), which either enables reading the entire stream into memory, or limits it by the given byte limits (currently 400MB, per demuxer).
This also includes a small fix for track switching awkwardness, although it doesn't fix it fully. This applies to situations where the demuxer cache is maxed out on the byte limit, and you enable a stream (details see commit message). It mitigates one worry about enabling this.
Finally, this includes the demuxer cache byte amount in the CLI status line and the OSC.
In general, the demuxer cache is less efficient than the stream cache. The stream cache is a simple byte based ringbuffer, while …

Make the demuxer cache the default, reduce stream cache

---

demux/demux_mkv.c

Caused by the relatively recent change to packet parsing. This time it
was probably triggered by lace type 0, which reduces the byte length of
a 0 sized to 3 (timestamp + flag) instead of 4 (lace count for other
lace types). The thing about laces is just my guess why it worked for
other 0 sized packets, though.
Also remove the redundant and incorrect check below.
Fixes #5271.

demux_mkv: fix off by one error

---

player/external_files.c
player/loadfile.c

There is no reason not to do this, and probably saves the user some
trouble.
Mostly untested.
Closes #5272.

player: make track language matching case insensitive

---

demux/demux.c
demux/demux.h
player/playloop.c

Before this change and before the seekable stream cache became a thing,
we could possibly seek using the stream cache. But we couldn't know
whether the seek would succeed. We knew the available byte range, but
could in general not tell whether a demuxer would stay within the range
when trying to seek to a specific time position. We preferred to have
safe defaults, so seeking in streams that were detected as unseekable
were not honored. We allowed overriding this via --force-seekable=yes,
in which case it depended on your luck whether the seek would work, or
the player crapped its pants.
With the demuxer packet cache, we can tell exactly whether a seek will
work (at least if there's only 1 seek range). We can just let seeks go
through. Everything to allow this is already in place, and this …

player: allow seeking in cached parts of unseekable streams

---

demux/demux.c
demux/demux.h
player/command.c
player/command.h
player/loadfile.c

This will help with things like livestreams.
As a minor detail, subtitles are excluded, because they sometimes have
"unused" events after video and audio ends. To avoid this annoying
corner case, just ignore them.
---
Looks a bit silly when the OSC updates, and the current position seemingly jumps around because the duration is getting higher as the stream buffers. But still better than not having a seek bar at all.
In theory, the OSC could do this manually, and use the reported cache state for this. Not sure what's better. This solution would benefit all potential users, and showing the highest known time on OSD or the terminal status line might be better than "unknown".

player: update duration based on highest timestamp demuxed

---

DOCS/man/options.rst
ta/ta_talloc.h
video/out/gpu/osd.c
video/out/gpu/ra.h
video/out/gpu/shader_cache.c
video/out/gpu/shader_cache.h
video/out/gpu/video.c
video/out/opengl/ra_gl.c
video/out/vulkan/common.h
video/out/vulkan/context.c
video/out/vulkan/formats.c
video/out/vulkan/malloc.c
video/out/vulkan/ra_vk.c
video/out/vulkan/ra_vk.h
video/out/vulkan/utils.c
video/out/vulkan/utils.h

This improves on the major shortcomings of the ver1 design and enables full use of async transfers, async compute, multi-command queueing, event-based image barriers, safe FBO invalidation, better implicit renderpass layout transitions and more (tm).
It turns out that the VkSemaphore deadlock issue was an nvidia driver bug. This approach works after all, and scales well - especially now that I've refactored it to avoid using VkSemaphores for intra-frame dependencies as much as possible. There is now virtually no performance drop as a result of this refactor even without the fancy async transfer stuff. (And with async transfer on top, the performance goes through the roof again)
I probably won't actually merge this until the fixes for the nvidia deadlock issue make it into an actual driver …

Vulkan revision 2

---

DOCS/client-api-changes.rst
DOCS/interface-changes.rst
audio/decode/ad_spdif.c
options/options.c
options/options.h
player/audio.c
player/command.c
player/core.h
player/loadfile.c
video/decode/vd_lavc.c

A release has been made, so drop options deprecated for that release.
Also drop some options which have been deprecated a much longer time
before.
Also fix a typo in client-api-changes.rst.

options: drop some previously deprecated options

---

DOCS/man/osc.rst
player/lua/osc.lua

This commit adds a new osc setting `seekranges` to control the seek ranges visibility.

osc: make seek ranges rendering optional

---

player/lua/osc.lua

Also hide cache if 'cache-used' is 0 (usually means video fits
entirely within demuxer-cache-duration or stream cache is disabled).

osc: hide cache if not forced for local files

---

video/filter/vf_vdpaupp.c

Crashed when no vdpau device was loaded. Also there was a mistake of not
setting p->ctx, which broke software surface input mode. This was not
found before, because p->ctx is not needed for anything else.
Fixes #5294.

vf_vdpaupp: fix error handling and software input mode

---

DOCS/man/input.rst
DOCS/man/options.rst
input/cmd_list.c
input/cmd_list.h
options/options.c
options/options.h
player/command.c
video/out/opengl/context_android.c
video/out/vo.h
video/out/vo_gpu.c

Android fucking sucks
tl;dr
\- we need to be able to tell mpv when the surface resized
\- querying these from EGL does not work, it reports outdated values
\- thus we need additionally need those properties to pass the correct dimensions

Fix surface resizes for android_context completely

---

video/decode/vd_lavc.c

If you use vo_rpi, this could crash, because hwdec_devs is NULL.
Untested. Fixes #5301.

vd_lavc: fix crash with RPI hwdec

---

DOCS/man/options.rst
demux/demux_mkv.c
demux/stheader.h
video/decode/vd_lavc.c

Same as #5290, but the third commit uses an alternative implementation, which may be better or worse.

Gross workarounds to deal with x264 4:4:4 bugs (alternative)

---

demux/demux_mkv.c

The x264 hack requires reading the first video packet, which in turn we
handle with a hack in demux_mkv.c to get the packet without having to
add special crap to demux.c. Another useless MKV feature (which they
enabled by default at one point and which caused many demuxers to break
completely, only to disable it again when it was too late) conflicts
with this, because we actually pass a block as packet contents, instead
of after "decompression".
Fix this by calling demux_mkv_decode().

demux_mkv: fix x264 hack if video track uses header compression

---

player/playloop.c

I had changed `--loop-file` to interact with `--start` to work the same way that `--loop-playlist` does. (That is, `--loop-file` seeks to the `--start` time upon looping, not the beginning of the file.) However, the consensus (at least from hanna and wm4) is that the old behavior is preferred, and if anything, then `--loop-playlist` should also ignore the `--start` option.
I've reverted the two commits that change this behavior with standard commit revert messages to make it very clear what was reverted. If these should be rebased with different commit messages or squashed into one with this information in the extended message, I can do that too, but I left it as is just in case.

Undo --loop-file interaction with --start

---

wscript

This seems to fix issues when building on windows where compiling mpv.rc
after a `waf clean` resulted in a failure because version.h was not
always present

build: generate version.h before anything else

---

DOCS/man/options.rst
video/out/opengl/context_android.c

Uses the EGL width/height by default when the user fails to set
the android-surface-width/android-surface-height options.
This means the vo-resize command is optional, and does not need to
be implemented on android devices which do not support rotation.
cc @sfan5 #5287

vo_gpu/android: fallback to EGL_WIDTH/HEIGHT

---

stream/stream.c
stream/stream_lavf.c

Don't drop the stream buffers, because the read call (that must have
been failing) might try to extend an existing read buffer in the first
place. Just move the messy seek logic to stream_lavf.c. (In theory,
stream_lavf should probably make libavformat connect at the correct
offset instead of using a seek to reconnect it again. This patch doesn't
fix it, but at least it's a good argument to have the messing with the
position not in the generic code.)
Also update the comment about avio not supporting reconnecting. It has
that feature now. Maybe we should use it, but only after it gets fixed.

stream_lavf: minor fixes to HTTP reconnection support

---

options/m_option.c

Any suggestions on improving the repeated talloc_asprintf would be welcome.

m_option: add print callback to start/end/length

---

common/av_log.c

MPlayer legacy added in 3c49701490aecb.

av_log: stop accessing private ffmpeg fields

---

DOCS/man/options.rst
options/options.c
options/options.h
player/core.h
player/playloop.c

Two things of interested:
- the 2nd commit changes the "adaptive" buffering/pausing mechanism to a fixed wait, because the "adaptive" behavior was probably more like "bullshit" behavior
- the 3rd commit adds an option to enter the buffering state on playback start
CC @LongChair because he pretty much requested a way to wait until buffering is done; see https://github.com/mpv-player/mpv/commit/57c0c6ab3dbca28249f4ef199fcf41ff4a8eb0ea#diff-1d6a5494d6e6ca1cadd10688a1e233bdR3875
CC @tmm1 because he often seems to do streaming stuff (also maybe @sfan5 ?)

Cache pausing improvements

---

video/out/gpu/d3d11_helpers.c

BGRA swapchains don't work well with a42b8b1142fd, which attempts to use the swapchain format for intermediate FBOs, even though BGRA swapchains don't support typed UAV stores. This results in error spam with Intel graphics (but surprisingly, no errors with Nvidia):
```
[vo/gpu/d3d11] Failed to create Texture2D: The parameter is incorrect. (0x80070057)
[vo/gpu] Error: texture could not be created.
[vo/gpu/d3d11] after rendering:
[vo/gpu/d3d11] 92: ID3D11Device::CreateTexture2D: The format (0x57, B8G8R8A8_UNORM) cannot be bound as an UnorderedAccessView, or cast to a format that could be bound as an UnorderedAccessView.  Therefore this format does not support D3D11_BIND_UNORDERED_ACCESS.
[vo/gpu/d3d11] 104: ID3D11Device::CreateTexture2D: Returning E_INVALIDARG, meaning invalid parameters …
```

Don't attempt to use a BGRA-format swapchain with D3D11

---

DOCS/man/options.rst
video/out/d3d11/hwdec_dxva2dxgi.c
video/out/d3d11/ra_d3d11.c
video/out/gpu/hwdec.c
wscript_build.py

This adds hwdec_dxva2dxgi, which uses D3D9Ex/DXGI surface sharing. Unlike D3D11VA, it should work in Windows 7, but it's untested in Windows 7 at the moment because I don't have a Windows 7 PC.
~~This also attempts to use the DXVA2 video processor for YUV->RGB conversion, which should be more accurate than StretchRect(). On my PC, it uses the correct levels (0-255) by default, though the NVIDIA control panel can still override it.~~
Scratch that. mingw-w64 upstream doesn't have header file definitions for the DXVA2 video processor, so we can't use it yet. This PR just uses StretchRect() for now.

Support DXVA2 in D3D11

---

DOCS/interface-changes.rst
DOCS/man/options.rst
demux/demux_null.c
player/core.h
player/loadfile.c

Not sure about the first one, but I really don't appreciate it autoselecting any tracks with --external-files (not to do this was the reason why I added this in the first place). I think a recent commit for allowing subtitle tracks in --audio-files broke this.
Also, demux_null is sometimes used to get a "blank" state, and then adding files to it via --external-files. Allowing seeking seems to be fine in these cases. (Although the behavior is still not ideal.)

Minor --external-files fixes

---

DOCS/man/options.rst
player/command.c

Fixes  #3028 (OSD not shown on user interaction). Some white-space cleanup to command.c as well.

Make osd-msg-bar default for seeking and pausing.

---

audio/decode/dec_audio.c
video/decode/dec_video.c

If feed_packet() ended with DATA_WAIT, the player should have gone to
sleep, until the demuxer wakes it up again when there is new data. But
the call to read_frame() unconditionally overwrote this status code, so
it never waited. The consequence was that the core burned CPU by
effectively polling the demuxer status, which was noticeable especially
when seeking in network streams (since seeking is async, decoders will
start out with having to wait for network).
Regression since commit 33e5755c.

video, audio: don't actively wait for demuxer input

---

input/cmd_list.c
input/cmd_list.h
input/cmd_parse.c
input/input.h
player/command.c

Replace the static array with dynamic memory allocation. This also
requires some code to honor mp_cmd.nargs more strictly. Generally
allocates more stuff.
Fixes #5375 (although we could also just raise the static limit).
---
Well, not sure if this is better, or if the static limit should simply be raised.

input: make command argument list a dynamic array

---

wscript

See https://www.raspberrypi.org/forums/viewtopic.php?f=67&t=20005&p=194090
and https://github.com/raspberrypi/firmware/issues/110
Raspberry-pi upstream also adds '-lGLESv2' when EGL is used:
https://github.com/raspberrypi/userland/blob/master/pkgconfig/egl.pc.in
Otherwise configure fails like this: https://paste.pound-python.org/show/mfZP5DkeoSdMlFg0px2z/

build: rpi: add missing linker flags to fix build

---

libmpv/opengl_cb.h

opengl_cb.h should mention GLES 2.0 support, since this
support is available. Now it does mention it.
See comments of #5397.

libmpv/opengl_cb.h: mention OpenGL ES 2.0 support

---

DOCS/man/af.rst
audio/filter/af_rubberband.c

This commit introduces the multiply-pitch af-command. Users may bind
keys to this command in order to incrementally adjust the pitch of a
track. This will probably mostly be useful for musicians trying to
transpose up and down by semi tones without having to calculate
the correct ratio beforehand.
As an example, here is an input.conf to test this feature:
{ af-command all multiply-pitch 0.9438743126816935
} af-command all multiply-pitch 1.059463094352953

af_rubberband: add af-command to multiply current pitch

---

video/out/opengl/context_rpi.c

This segfaults otherwise. The conditional is needed to break a circular
dependency (gl_init depends on mpgl_load_functions which depends on
recreate_dispmanx which calls gl_ctx_resize).
Fixes #5398

vo_gpu: rpi: defer gl_ctx_resize until after gl_ctx_init

---

video/out/gpu/video.c

The check_gl_features(p) call here checks whether dumb mode can be used.
It uses the field use_integer_conversion, which is set _after_ the call
in the same function. Move check_gl_features() to the end of the
function, when use_integer_conversion is finally set.
Fixes that it tried to use bilinear filtering with integer textures. The
bug disabled the code that is supposed to convert it to non-integer
textures.

vo_gpu: fix broken 10 bit via integer textures playback

---

demux/demux.c
demux/demux_mkv.c
input/cmd_parse.c
ta/ta.h
ta/ta_talloc.h
video/out/vo.c

It was actually already implemented as ta_dup_ptrtype(), but that seems
like a clunky name. Also we still use the talloc_ names throughout the
source, and I'd rather use an old name instead of a mixing inconsistent
naming conventions.
---
The second commit is strictly speaking unrelated, but just a tiny change.

 ta: introduce talloc_dup() and use it in some places 

---

DOCS/tech-overview.txt
osdep/macosx_application.m
osdep/macosx_application_objc.h
osdep/macosx_compat.h
osdep/macosx_events.h
osdep/macosx_events.m
osdep/macosx_events_objc.h
osdep/macosx_menubar.m
video/decode/vd_lavc.c
video/mp_image.c
video/out/cocoa/window.m
video/out/gpu/video.c
video/out/opengl/context_cocoa.c
video/out/vo.c
video/out/vo.h
video/out/vo_vdpau.c
video/out/win_state.c
wscript

if wanted i can remove the last commit that changes some remaining vo_opengl mentions. i didn't find any more, but there still might be more. wasn't too sure how to prefix that commit message.
the macOS changes are just some cosmetics and a fix for a deprecation warning on macOS 10.13.

Cosmetic changes for macOS and vo_opengl

---

DOCS/interface-changes.rst
DOCS/man/options.rst
options/options.c
options/options.h
player/command.c

This basically undoes #5361. However, given the amount of complaining about how hard it is to change the default OSD settings by remapping every associated key led me to implement the `--osd-on-seek` option (which can still be overridden for individual key bindings in input.conf). The pause osd change is reverted outright.
You're all wrong BTW. Apologies to my comrade @eugenesvk in #3028.

Restore previous osd seek / pause behaviour and make it more configurable

---

demux/demux_lavf.c

- properly restrict seeking in HLS streams instead of dying
- restore playback of thumbnail track mp4 files
For the latter I had a patch to ffmpeg-devel that would solve it, but it looks like it's going to be rejected, so here's a workaround.

Minor demux fixes

---

video/out/gpu/video.c

Using vdpau will allocate additional textures for the reinterleaving
step, which uninit_rendering() will free. This is a problem because the
hwdec image remains mapped when reinitializing, so the reinterleaving
textures are turned into dangling pointers. Fix this by freeing the
reinterleave textures on full uninit instead.
Fixes #5447.

video: fix crash with vdpau when reinitializing rendering

---

video/out/gpu/video.c

This seems to be the bug behind #5436. FL 9_3 doesn't always imply dumb mode, since it depends on which optional texture formats are supported, so I guess I forgot to test with 9_3 _and_ dumb mode.

Check for RA_CAP_FRAGCOORD in dumb mode too

---

video/filter/vf_vapoursynth.c

The first commit fixes the deadlock mentioned in #5470 due to broken mutex usage. The second one isn't strictly needed and merely makes it "cleaner".

Vapourynth fixes

---

DOCS/man/options.rst
video/out/gpu/ra.h
video/out/gpu/video.c
video/out/gpu/video.h
video/out/gpu/video_shaders.c
video/out/opengl/ra_gl.c
video/out/vulkan/ra_vk.c

The current peak detection algorithm was very bugged (which contributed
to the excessive cross-flame flicker without long normalization) and
also didn't take into account the frame average brightness level.
The new algorithm both takes into account frame average brightness (in
addition to peak brightness), and also computes the values in a more
stable/correct way. (The old path was basically undefined behavior)
In addition to improving the algorithm, we also switch to hable tone
mapping by default, and try to enable peak computation automatically
whever possible (compute shaders + SSBOs supported). We also make the
desaturation milder, after extensive testing during libplacebo
development.
I also had to compensate a bit for the representational differences
between mpv and libplacebo …

vo_gpu: port HDR tone mapping algorithm from libplacebo

---

video/out/opengl/hwdec_drmprime_drm.c

Currently using the drmprime interop with external mpv intgration can lead
to rendering issues because the current frame is being released too early.
Typically using this with Qt results in one frame shift because Qt
will do waitforvsync and swap, rather than swap and waitforvsync.
This leads to tearing as the frambuffer is released while being
displayed on screen.
In order to avoid releasing the framebuffer that is displayed, We keep
the framebuffer alive for one more frame with triple buffering to make
sure that whatever rendering process is used, the framebuffer will not
be released when it's still on screen
This was tested on RockChip Rock64

drmprime interop : Add frames triple buffering

---

video/out/wayland_common.c

The pointer is used as a state and wasn't zeroed after seeks

wayland_common: fix idle_inhibitor protocol segfault

---

video/out/vo_drm.c

make the osd as large as the screen for vo=drm

---

DOCS/interface-changes.rst
DOCS/man/options.rst
DOCS/man/vo.rst
osdep/macOS_mpv_helper.swift
osdep/macOS_swift_bridge.h
osdep/macosx_application.m
osdep/macosx_application_objc.h
osdep/macosx_events.m
osdep/macosx_menubar.m
player/client.c
player/client.h
video/out/cocoa-cb/events_view.swift
video/out/cocoa-cb/video_layer.swift
video/out/cocoa-cb/window.swift
video/out/cocoa_cb_common.swift
video/out/opengl/context_cocoa.c
video/out/vo.h
video/out/vo_opengl_cb.c
waftools/checks/custom.py
waftools/detections/compiler_swift.py
waftools/generators/sources.py
wscript
wscript_build.py

this is a WIP and attempts to fix various annoying macOS bugs and the very long standing fullscreen regression completely. it still needs testing and some fix-ups.
this will definitely fix: #5478, #5393, #5152, #5151, #4615, #4476, #3746, #3739, #2392, #2217
and possibly fixes: #3978
feel free to test and report unknown bugs. for now one just needs to set `--vo=opengl-cb`, ~~though if the mpv core is too fast you might get a "No context set." error.~~
there are a few things to do where i don't know how to solve them yet and i might need some help.
TODO cocoa-cb:
- ~~proper cocoa-cb init routine, (--no-config --vo=opengl-cb fails since no context yet)~~
- ~~cocoa-cb vo option or comparable~~ (just compile time flag, uses vo=opengl-cb)
- ~~doesn't draw when minimised, off screen, different …

macOS opengl-cb backend

---

player/video.c
video/out/vo.c
video/out/vo.h

Fixes playback issues on some mediacodec hardware.

Avoid buffering frames in the VO when using vo_mediacodec_embed

---

DOCS/man/options.rst
video/out/gpu/video.c
video/out/gpu/video.h
video/out/gpu/video_shaders.c
video/out/gpu/video_shaders.h

The first two commits fix some of the issues surrounding HLG, and improves the HLG implementation by correctly respecting the parametric OOTF.
The final commit introduces a new option aimed towards solving #5521, which also makes it technically possible to use mpv with HDR displays on all current platforms - independent of actual platform support. (As long as users don't mind everything but mpv looking wrong - but this could easily be mediated by loading a different ICC profile for mpv specifically)

A number of HDR improvements aimed towards HLG, as well as --target-peak

---

filters/f_output_chain.c
player/audio.c

Just bail out immediately (and disable audio) if format probing has no
result, instead of doing nothing and then apparently freezing.
This can happen with bogus filters, cases where the first audio frame is
essentially dropped by filters (can happen with large resampling
factors), and if the audio track contains no packets at all, or all
packets fail to decode.

audio: improve behavior if filters output nothing during probing

---

DOCS/man/mpv.rst
stream/stream_file.c

Do this because retrying reading on higher levels (like the demuxer)
usually causes tons of problems. A hack like this is simpler and could
allow to remove some of the higher level retry behavior.
This works by trying to detect whether the file is appended. If we reach
EOF, check if the file size changed compared to the initial value. If it
did, it means the file was appended at least once, and we set the
p->appending flag. If that flag is set, we simply retry reading more
data every time we encounter EOF. The only way to do this is polling,
and we poll for at most 10 times, after waiting for 200ms every time.
---
Not sure about the merit of this. It's sort of flaky and shitty. I think the conclusion is that users should simply not try to play files that are being appended, or use `tail`. …

stream_file: add mode for reading appended files

---

video/out/gpu/video_shaders.c

Based on testing with real-world non-HDR BT.2020 clips, clipping the
color space looks better than attempting to gamut map using a tone
mapping shader that's (by now) optimized for HDR content.
If anything, we'd have to develop a separate gamut mapping shader that
works in LCh space.

vo_gpu: don't tone-map for pure gamut reductions

---

video/out/cocoa-cb/video_layer.swift
video/out/cocoa-cb/window.swift
video/out/cocoa_cb_common.swift

fixes two size issues. this makes the fullscreen animation appear a lot smoother, especially with a border.
there are still two other issues, black flicker and a stretched surface on window spect ration change, that need to be fixed. this will be done after #5520 was completed and merged because one fix loosely depends on it.

cocoa-cb: fix fs animation and wrong drawing size

---

DOCS/man/options.rst
options/options.c
options/options.h
osdep/macOS_mpv_helper.swift
osdep/macosx_application.m
video/out/cocoa-cb/events_view.swift
video/out/cocoa-cb/video_layer.swift
video/out/cocoa-cb/window.swift
video/out/cocoa_cb_common.swift
waftools/detections/compiler_swift.py

ignore the `build: fix swift detection with python2` commit, it is part of another PR but was needed to fix the build.
this drastically changes the window styling. it moves the title bar inside of the window frame and it automatically hides. it's similar to QuickTime Player now. it supports 4 different styling and auto select based on your system settings. for now `dark` is the default styling. some screenshots how it looks like, active and inactive window. feel free to voice your opinion (that's why i opened that PR before being completely done with that change) or report any issues since i didn't test it too much yet.
this also seems to have the nice side effect of fixing #3944 and the black flicker and makes the animation appear smoother, because of less abrupt resizing.
**current:** …

cocoa-cb: change window styling

---

video/out/cocoa-cb/window.swift

sometimes i have the feeling i am too dumb to code for Apple platforms.
[here](https://developer.apple.com/documentation/appkit/nswindow.buttontype) the doc for this enum. top right corner say no changes to that API (`API Changes: None`) and available since SDK 10.2. so i just assumed it works.

cocoa-cb: fix building with SDK 10.12 and earlier

---

osdep/macOS_mpv_helper.swift
osdep/macOS_swift_bridge.h
player/client.c
player/client.h
video/out/cocoa-cb/events_view.swift
video/out/cocoa-cb/video_layer.swift
video/out/cocoa-cb/window.swift
video/out/cocoa_cb_common.swift

did i catch all the legacy stuff with `client: remove legacy API that is unused now`? also should i leave it as a separate commit or merge it with `cocoa-cb: use new libmpv API instead of opengl-cb`?
yeah somehow i failed at rebasing and a `print` made it in one of my merged PRs.

cocoa-cb: use new libmpv API instead of opengl-cb

---

DOCS/man/mpv.rst
etc/input.conf

This adds key bindings for some semi-popular features. It also tries to
cleanup some old bindings. For example w/e for panscan is now changed to
w/W. In all cases, the old bindings are still kept and work, though.
---
Comments and suggestions welcome. Bikeshed away, I guess.

input: minor additions to default key bindings

---

demux/demux_tv.c
stream/tv.h
stream/tvi_def.h
stream/tvi_v4l2.c

Naturally, there's more than one fourcc that indicates an mjpeg
stream.

tv: Recognise v4l2 'JPEG' fourcc

---

video/out/cocoa-cb/video_layer.swift
video/out/cocoa-cb/window.swift
video/out/cocoa_cb_common.swift

why easy if you can do it the complicated way. anyway i could removed quite a lot of special cases now, all the aspect ratio checks. the atomic drawing, which caused some problems is now only ever used when the vo is reconfigured, eg file switch.
this also fixes an issue @avih mentioned on irc when deactivating the fs resize animation still kept the sliding animation visible on videos with an aspect ratio different from the display aspect ratio. the rounded corners are still there till it actually enters fullscreen though.
this also removes the atomic drawing that @sCreami had some problems with on #5520.

cocoa-cb: several size related fixes

---

audio/out/ao_opensles.c

Avoid resume() from causing SL_RESULT_BUFFER_INSUFFICIENT ("Failed to Enqueue: 7" when seek or resume from pause).

ao_opensles: clear buffer queue in reset()

---

osdep/macOS_mpv_helper.swift
video/out/cocoa-cb/events_view.swift
video/out/cocoa_cb_common.swift
waftools/detections/compiler_swift.py
wscript_build.py

i only tested the oldest supported waf version and there one has to explicitly request an absolute path in comparison to 1.9.8 for example.
for the icc profile change the API [mentioned](https://github.com/mpv-player/mpv/blob/7ee01860d9c16f2d9d9ea3f5ae5c2a699c7cf1f9/libmpv/render.h#L145) that it handles the option itself now.

cocoa-cb: some minor fixes

---

player/lua/stats.lua

Switch from `audio|video` to `audio|video-out-params` properties as per
recommendation in #5670. These properties are tables and include
information explicitly queried later, so switch to using these tables
and reduce the amount of queried properties.
Fixes #5670

stats: improve video/audio detection

---

video/out/cocoa-cb/video_layer.swift
video/out/cocoa-cb/window.swift
video/out/cocoa_cb_common.swift

tested this watching a 16min long video while doing some other heavy stuff. it's quite an extreme example, on normal playback one probably won't notice it most of the time. though it's still an improvement.
```
before:
Dropped: 0 Output: 38 Mistimed: 80 Delayed: 71
after: 
Dropped: 0 Output: 2  Mistimed: 5  Delayed: 2
```
```
Dropped:  decoder-frame-drop-count
Output:   frame-drop-count
Mistimed: mistimed-frame-count
Delayed:  vo-delayed-frame-count
```

cocoa-cb: render on a dedicated dispatch queue

---

options/options.c
options/options.h
video/vaapi.c

On machines with multiple GPUs, /dev/dri/renderD128 isn't guaranteed
to point to a valid vaapi device. This just adds the option to specify
what path to use.
It also reorders the code which opens the device such that if X11
fails (because the device chosen isn't running a server but another
device is), it'll try to use the DRM path.

vaapi: add option to select a non-default device path

---

demux/demux_mkv.c

Quickly tested by a person who had FFmpeg linked with libaom.
Seems as simple as the VP9 mappings, where there is no extradata/
initialization data off-band, and just stuff in the packets
themselves.
Do note that the AV1 video format itself at this point is still
not frozen, so what you might produce one day might not be
decodable the following day.
**P.S.** Originally I thought the listing was alphabetic, but then I noticed prores/hevc after VP8/9, thus added to the end of the list.

demux_mkv: add V_AV1 identifier for AV1

---

waftools/generators/sources.py
wscript_build.py

Utilize the SRC variable for this to get a built-in relative path.
Can be tested by adding `--variant="random_string"` to configure and
build.

build: fixup vendored wayland protocols with variants

---

demux/demux_lavf.c
demux/stheader.h
player/command.c
player/core.h

ffmpeg marks audio tracks which are not meant to be played standalone
as DEPENDENT. these are typically used in DVB broadcasts for audio
descriptions, and are meant to be mixed into the main audio track during
playback.

demux, player: mark dependent tracks

---

demux/demux.c

This fixes an issue where captions stop rendering after an
in-demuxer-cache seek, because the demuxer keeps waiting to find
a keyframe (ds->skip_to_keyframe set to true in execute_cache_seek).

demux: mark eia608 packets as keyframes

---

video/out/opengl/hwdec_ios.m

NULL de-reference causes exception inside CFRelease

hwdec_ios: fix crash after mapper_init failure

---

DOCS/interface-changes.rst
video/out/opengl/context_cocoa.c

this was missed when when opengl-cb was deprecated and i moved cocoa-cb to the new API. i also moved the the entry for cocoa-cb in `interface-changes.rst` underneath the `opengl-cb to libmpv` one and changed it to reference `vo=libmpv` instead. i think this way it makes more sense since we reference the proper `vo` directly instead of suggestion to use a `vo` that was deprecated a few changes later but in the same release.

cocoa: change deprecation warning from opengl-cb to libmpv

---

DOCS/man/options.rst

The manpage parts were forgotten when removing the options.

manpage: remove 4 previously removed options

---

video/out/gpu/video.c

* Log more stuff when a user-specified FBO fails our checks.
* Force-disable compute shaders if an FBO format was not available.
Wasn't sure how to GTFO out of this function in case a user-specified FBO fails, as this most likely we want to have as a critical error.
Fixes #5782 (at least by warning the user instead of silently going on)

vo_gpu: Improve logging and disable compute shaders if an FBO format was not available

---

DOCS/man/vo.rst
libmpv/opengl_cb.h
libmpv/render.h
libmpv/render_gl.h
video/out/drm_atomic.c
video/out/drm_atomic.h
video/out/drm_common.c
video/out/drm_common.h
video/out/gpu/libmpv_gpu.c
video/out/opengl/context_drm_egl.c
video/out/opengl/hwdec_drmprime_drm.c
video/out/vo_drm.c

Here are a few commits that intend to improve drm atomic support.
The main topic there are taking care of are :
- switch the the new API for the drm prime interop.
- use atomic modesetting in atomic path.
- Add the ability to select planes for video & osd
- Add the ability to use a specified osd size that can be different than videomode.
cc @wm4  @xantoz

Various DRM Atomic improvements

---

player/playloop.c

I've been using these patches for a few months to get more visibility into buffering behaviors. Pretty useful IMHO, so I think it's worth merging.
Here's an example where I was using `--cache-wait=1.25` and there was a momentary dip in the demuxer cache:
```
[cplayer] Enter buffering (buffer went from 100% -> 92%) [0.925889s].
[cplayer] Still buffering (buffer went from 92% -> 74%) [0.925889s].
[cplayer] Still buffering (buffer went from 74% -> 78%) [0.975944s].
[cplayer] Still buffering (buffer went from 78% -> 90%) [1.126089s].
[cplayer] End buffering (waited 0.425415 secs) [1.342978s].
```

player: add more logging around buffering state

---

player/lua/ytdl_hook.lua

Fixes `--ytdl-format="dash-fastly_skyfire-video-363357330+dash-fastly_skyfire_sep-audio-363357330" https://vimeo.com/108650530`
This happened because the video track also had audio available and after
adding it expecting an audio-only track, there were no more tracks with video.

ytdl_hook: try to set video track first if available

---

options/m_option.h

bfc33da250e4fdb6bb57bdf051ad666570ae985f added a new m_option flag but didn't shift the ones after it.
Alternatively, we could bump to 9 and have room to add another flag without bumping.

m_option: fix duplicate flag value

---

DOCS/man/options.rst
video/out/gpu/lcms.c

With the advent of actual HDR devices, my real measured ICC profile has
an "infinite" contrast, since the display is completely off on pure
black inputs. 100k:1 might not be enough, so let's just bump it up to
1m:1 to be safe.
Also, improve the logging in the case that the detected contrast is too
high by default.

vo_gpu: allow higher icc-contrast and improve logging

---

demux/demux.c
demux/demux_lavf.c
demux/stheader.h
player/core.h
player/playloop.c
player/video.c

Playing back https://s3.amazonaws.com/tmm1/music.ts (and especially when playing that channel live from my network TV tuner), there are a ton of issues:

Fix playback of "music choice" cable channels in USA (video frames every 6s)

---

video/out/x11_common.c

For some reason, the X default modifier map binds shift+tab to
ISO_Left_Tab instead of the regular Tab. So to get Shift+TAB recognized
by mpv, we also need to accept ISO_Left_Tab.
This patch matches what other programs like e.g. Qt do, which treat Tab
and ISO_Left_Tab as the same thing.
God only knows why the distinction exists, and why X decides to mix up
its bindings like that.
Fixes #5849
I agree that my changes can be …

x11: support Shift+TAB

---

demux/demux_lavf.c
input/cmd.h
input/input.h
input/keycodes.h
osdep/terminal-unix.c
player/command.c
video/decode/vd_lavc.c
video/out/x11_common.c

Some misc. fixes, before I fall asleep.
* Improvements to missing terminal and too many mouse buttons being available.
* Simplify `vd_lavc` 's `get_format` by utilizing an FFmpeg function that has been around since at least 2015.
* Stop black-listing no longer available ffm format that was in ye olden versions of FFmpeg pre-ffserver removal.
* Move `mp_input_section_flags` back to `input/input.h`.
Worked for mingw-w64 with both hwdec and swdec, and most likely will for Android since I have a feeling the last time I tested things I had all these things in the tree.

Random small cherry-picks from das big PR

---

video/out/gpu/video_shaders.c

This sacrifices some dynamic range for well-behaved sources, but
prevents catastrophic desaturation on badly mastered / too bright
sources. I think that's the better trade-off. This makes the
desaturation algorithm much "safer" to deploy by default, as well. One
could even argue going up to strength 1.0, which works better for some
sources but worse for others. But I think the current strength is the
best trade-off even after this change.
agreed to it before, leave the following …

vo_gpu: desaturate after peak detection

---

player/lua/osc.lua

When seeking near the end of the file and the next file loads, seeking
continues on the next file at the same position and then immediately
the file after that. This patch stops slider seeking when a new file is
loaded, which is the standard behavior of many other players.

osc: fix accidentally skipping files when seeking with slider

---

stream/stream_file.c

Obviously "osxfusefs" works only on Mac. On OpenBSD it's just "fuse" while on FreeBSD (for the scenario described in #634) it would be "fusefs.sshfs"

stream_file: enable cache for FUSE filesystems on OpenBSD and FreeBSD

---

video/out/opengl/hwdec_drmprime_drm.c

Change the log-level of an error message that would sometimes show up
during hwdec probing, and could be misleading.
This should fix Issue #5857.

hwdec_drmprime_drm: Do not show error message during probing

---

player/lua/stats.lua

Those accidentally slipped in with 9975835bdeec3f2b04b136ef40c70b02487bb0e6
due to bad copy & paste.
Libass didn't render these superfluous line breaks so I didn't notice. However, with PR https://github.com/libass/libass/pull/285 applied it suddenly does. So fix that before this PR hits libass master. Thanks to @Akemi who noticed it!

stats: remove superfluous line breaks

---

options/options.c

This adds the 'Date', 'Description', 'Rating', and 'Series' tags to the
list of metadata displayed during playback.
The currently-displayed tags make sense for music files, but similar
information for video is more commonly - or at least should be - put
under other tags, while the audio-related tags are often used for
other information on video files (particularly with youtube-dl's
output).

options.c: display additional metadata tags during video playback

---

waftools/checks/custom.py
wscript_build.py

#5528 is confirmed to be still fixed, though i have no idea why the fix (https://github.com/mpv-player/mpv/commit/a17456608c0eb8dce61951b1beb0cd64e29a0f0a) worked in the first place. it should have always failed like in issue #5791. #5791 is fixed by manually adding the library search path now. maybe @AirPort can also confirm that the libjpeg problem is still fixed.
i am open for suggestions if there is a better way to handle this.

build: manually add library search paths for linking

---

demux/demux_mkv.c

demux_mkv: add A_MLP to mkv_audio_tags

---

TOOLS/lua/autoload.lua

`--script-opts=autoload-disabled=yes` now properly stops the script from running.

TOOLS/autoload: Fixed broken "disabled" option

---

waftools/waf_customizations.py

i was under the impression that `LAST_LINKFLAGS` was part of waf, but it's actually something we add manually to our linking process. `LAST_LINKFLAGS` weren't added to libmpv linking. i am not sure if this is an oversight or intentional? if it's intentional i will fix this differently. at least on [windows](https://github.com/mpv-player/mpv/blob/257a2b9646e845ef801588e871b9859d30ebf99a/waftools/detections/compiler.py#L54) `LAST_LINKFLAGS` is used and could cause problems in the case of linking libmpv, if leaving the last link flags out intentionally.

build: fix linking libmpv when swift features are build

---

DOCS/man/options.rst
video/out/gpu/video.c

According to earlier discussions, this can improve visual quality.
This only changes the preferred order of the formats, not the
formats themselves.

gpu: prefer 16bit floating point FBO formats to 16bit integer ones

---

wscript_build.py

mpv.com fails to build when cross-compiling with a multilib version
of GCC, because the -m32 flags aren't getting passed to the build
process for osdep/win32-console-wrapper.c or the link phase for
mpv.com itself.
Fixes #5991

wscript_build: apply project-wide CFLAGS/LDFLAGS to mpv.com

---

.travis.yml
ci/build-mingw64.sh
ci/build-tumbleweed.sh

This way the docker container in itself does no networking.
It seems like travis disabled network access from the actual docker
containers.

ci: do bootstrap outside the docker container

---

audio/format.c
audio/out/ao_opensles.c

OpenSLES (and its AudioTrack backend) in Android can take 32-bit
fixed and floating point input since Android L (API 21).

ao_opensles: allow s32 and float output

---

DOCS/man/vf.rst

An exclamation mark disables the filter by default instead of
enabling it.

manpage: fix --vf exclamation mark description

---

DOCS/man/input.rst

duration is parsed as an integer, and the default value is used if ```-1``` is passed. Passing ```-``` as described here causes a parameter value error.
Please correct me if I'm totally missing something here.

manpage: Correct show-text duration default value

---

audio/format.c

so that af_fmt_to_planar (and hence af_fmt_from_planar) can just
return the input when it is not an interleaved (planar) format.

audio/format: decouple af_fmt_is_planar from af_fmt_to_planar

---

video/out/cocoa-cb/events_view.swift

there are probably more forced unwrapping cases that should be changed, though i would like to leave that for a future refactor PR.

cocoa-cb: fix crash when no screen is available

---

video/out/cocoa_cb_common.swift

apparently the [colorspace](https://developer.apple.com/documentation/quartzcore/caopengllayer/1521873-colorspace#declarations) of the layer is only available on 10.11 but the compiler didn't throw an error, which it usually does.
this is untested since cocoa-cb can only be build on 10.11 (10.10 only has swift 2.x availabe) and i can't be bothered to build all dependencies for a lower target OS version.

cocoa-cb: fix crash on macOS 10.10

---

osdep/macosx_menubar.m

Replace dot syntax with accessor syntax so that clang no longer errors out due to not finding the property servicesMenu on NSApp.
cc @Akemi

osx: Fix compilation due to NSApp having type id

---

bootstrap.py

A user of the [mpv-git AUR package](https://aur.archlinux.org/packages/mpv-git/) requested that waf be downloaded by the packaging system instead of at compile-time. This has several advantages (building without network access, caching the waf download by the packaging system) so I'd like to do it, but I want to avoid building with the wrong version of waf and getting cryptic problems.
This change adds a flag to `bootstrap.py` that will not download waf, but will just perform the version check and error out (failing the build) if it's wrong. This will indicate that the package build script needs to be updated.
This was a 5-minute job and I'm not attached to this patch in particular. If anyone has a better solution to my use case, I'd welcome suggestions.

build: add --no-download option to bootstrap.py

---

audio/out/ao_opensles.c

Apparently some Android builds/forks require this for Bluetooth
audio to work as they unexpectedly accept fast flag for it.
Shouldn't cause any side-effect (e.g. buffer requirement increased
when on wired audio). It's a hardcoded default in the upstream
AAudio implementation anyway.
Ref.:
https://android.googlesource.com/platform/frameworks/av/+/android-8.0.0_r1/media/libaaudio/src/legacy/AudioStreamTrack.cpp#109
https://android.googlesource.com/platform/frameworks/wilhelm/+/android-8.0.0_r1/src/android/AudioPlayer_to_android.cpp#1680
https://android.googlesource.com/platform/frameworks/av/+/android-8.0.0_r1/media/libaudioclient/AudioTrack.cpp#488
Also see https://github.com/termux/termux-packages/issues/2703.

ao_opensles: set numBuffers to 8

---

DOCS/man/options.rst

manpage: fix reference to --tone-mapping by old option name

---

audio/out/ao_openal.c
waftools/checks/custom.py
wscript

This reverts commit af6126adbe61fb2b6cc780025246d33df93072e6. Apple's
OpenAL support is ridiculously out of date, revert back to just using
OpenAL Soft on macOS (fixes #4645).

Revert "ao_openal: enable building on OSX"

---

audio/format.c
audio/format.h
audio/out/ao_pulse.c

also remove the now unused non-sensical af_fmt_seconds_to_bytes.
Alternative to #6047. @sfan5 @jeeb

ao_pulse: fix tlength calculation

---

video/out/gpu/spirv_shaderc.c

Upstream has this now. Didn't really make any different for me (except
making the polar compute shader 2%-3% faster), but maybe it does for
somebody else.

vo_gpu: switch to optimization level performance

---

video/mp_image.c

By overriding it with 1.0 (aka SDR). This prevents blowing up on
mistagged clips.
Fixes #6111

mp_image: strip all HDR peak information from SDR clips

---

player/loadfile.c

```
mpctx->current_track[0][STREAM_VIDEO] (and STREAM_AUDIO) are empty when
using --lavfi-complex. Moving the muxer stream hinting after audio/video chain
initialization and checking if the chains exist fixes encoding with --lavfi-complex.
Previously, the output audio/video streams did not get prepared and the encode
would fail due to unexpected stream addition.
```
Example command using a null lavfi-complex:
`mpv video.mkv --lavfi-complex '[vid1] null [vo]; [aid1] anull [ao]' --o out.mkv`
This will fail without the PR's fix.
This doesn't seem to break anything and as far as I understand the encode mode prep work, it won't. Hopefully someone with more experience can confirm.
(commit name etc open for bikeshedding)

encode: fix expected streams when using --lavfi-complex

---

audio/out/ao_jack.c

This prevents ao_jack from auto-connecting to MIDI ports (or other,
hypothetical future port types).

ao_jack: only auto-connect to audio ports

---

player/lua/ytdl_hook.lua

Not so sure about this one, since I don't remember which site actually was broken because of this, but I checked the assertion with youtube-dl's code.

ytdl_hook: fix audio not being picked up for some sites

---

audio/out/ao_alsa.c

Fixes #5890 to no longer spam messages during pause, and removes spam from EOF.
1. Early exit from `get_space()` if paused or ALSA is not yet initialized. This lack of early exit was not noticed before because there was no logging of error states present in `get_space()`.
2. Special case XRUN errors and attempt to re-initialize the audio output in case one does happen. Warn the user about the (most likely) singular XRUN.
3. Log the ALSA state when we receive and error. This can help when debugging unexpected error cases.
Overall, this inconveniences the users less (no spam!) yet still reminds us that something is not exactly right with some logic somewhere (we get XRUNs right before EOF).

ao_alsa: Improve get_space

---

demux/packet.c

for the rawaudio demuxer to do the expected gapless playback
@jeeb @sfan5

demux/packet: fix demux_packet_shorten

---

DOCS/man/options.rst
osdep/macOS_mpv_helper.swift
osdep/macosx_application.h
osdep/macosx_application.m
video/out/cocoa-cb/video_layer.swift
video/out/cocoa_cb_common.swift
video/out/opengl/common.c

~~i would have liked to add an options for this, but since we need to pre-allocate the opengl context before any options access is available to us this is sadly not possible.~~
besides making mpv usable in VMs, this should also fix a problem with homebrews automatic jenkins testing (https://github.com/Homebrew/homebrew-core/pull/30369). @ilovezfs do you think you can test and confirm that this fixes the testing problem with homebrew?

cocoa-cb: fall back to software renderer when everything fails

---

audio/out/ao_audiounit.m

AudioUnit output driver uses the pull based api so it should have
a reset function instead of a pause function.

ao_audiounit: rename pause function to reset

---

common/encode_lavc.c

We're doing the same thing as the primary path - just that we log
and set 'failed' to true.

encode: simplify encode_lavc_add_packet

---

DOCS/man/mpv.rst

Someone on IRC pointed out that the default stats bindings weren't documented in the interactive control section of the manual, so let's add them with a short mention and a reference to the STATS section of the manual.

man: mention stats in interactive control

---

video/out/opengl/ra_gl.c

This deinit code was never checked, so this line would always crash on
implementations without support for sync objects.
Fixes #6197.

vo_gpu: opengl: fix segfault when gl->DeleteSync is unavailable

---

video/out/x11_common.c

Using strtol and strtoul is allegedly better practice, and I'm going for strtoul here because I'm pretty sure X11 displays cannot be in the negative.

x11_common: replace atoi with strtoul

---

DOCS/interface-changes.rst
DOCS/man/options.rst
etc/builtin.conf
video/out/gpu/video.c
video/out/gpu/video.h

Since linear downscaling makes sense to handle independently from
linear/sigmoid upscaling, we split this option up. Now,
linear-downscaling is its own option that only controls linearization
when downscaling and nothing more. Likewise, linear-upscaling /
sigmoid-upscaling are two mutually exclusive options (the latter
overriding the former) that apply only to upscaling and no longer
implicitly enable linear light downscaling as well.
The old behavior was very confusing, as evidenced by issues such
as #6213. The current behavior should make much more sense, and only
minimally breaks backwards compatibility (since using linear-scaling
directly was very uncommon - most users got this for free as part of
gpu-hq and relied only on that).
Closes #6213.
Ideally, you shouldn't need enter any …

vo_gpu: split --linear-scaling into two separate options

---

video/out/vulkan/ra_vk.c

This was pased on the texture height, which was a mistake. In some cases
it could exceed the actual size of the buffer, leading to a vulkan API
error. This didn't seem to cause any problems in practice, since a
too-large synchronization is just bad for performance and shouldn't do
any harm internally, but either way, it was still undefined behavior to
submit a barrier outside of the buffer size.
Fix the calculation, thus fixing this issue.
agreed to it before, leave the following …

vo_gpu: vulkan: fix the buffer size on partial upload

---

video/out/x11_common.c

On a multi monitor setup, when the center of the window was going off
screen, the icc profile would always switch to the profile of the first
screen.
This fixes the issue by defaulting the value to the current screen.

x11: fix the icc profile when the window goes near off screen

---

video/out/gpu/spirv.c

Fixes GCC8 warning
../video/out/gpu/spirv.c: In function 'spirv_compiler_init':
../video/out/gpu/spirv.c:68:9: warning: 'strncpy' specified bound 32 equals destination size [-Wstringop-truncation]

vo_gpu: vulkan: fix strncpy truncation in spirv_compiler_init

---

video/out/vulkan/context.c

Since the code just broke out of the loop on a match rather than jumping
straight to the end of the function body, it ended up hitting the code
path for when the end of the list was reached.

vo_gpu: vulkan: suppress bogus error message on --vulkan-device

---

waftools/detections/compiler_swift.py

seems like swift 1.x returns a version string like `Swift version 1.1 (swift-600.0.57.4)` whereas swift 2.x and newer return something like`Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) `.
before it just dumbly always took the fourth element after a split by space. obviously that didn't work with the first swift version. i made the swift version extraction a bit more reliable with a regex and hopefully it will prevent errors for future changes in the version string.
Fixes #6212

build: more reliable way of getting the Swift version from a string

---

DOCS/man/options.rst
video/out/gpu/ra.h
video/out/opengl/hwdec_cuda.c
video/out/vulkan/common.h
video/out/vulkan/malloc.c
video/out/vulkan/malloc.h
video/out/vulkan/ra_vk.c
video/out/vulkan/ra_vk.h
video/out/vulkan/utils.c
video/out/vulkan/utils.h
wscript

This is a working implementation of nvdec acceleration with the vulkan backend using the new CUDA 10 vulkan interop API. Due to bad documentation, I haven't yet worked out how to work with a VkImage directly in CUDA, and have needed to use an intermediate VkBuffer as the target for the copy from CUDA, which is then copied to the VkImage texture.
The implementation only works on Linux as the windows memory export mechanism is slightly different and I can't test it.
Finally, I did not attempt to do any semaphore based synchronisation between cuda and vulkan. The interop API supports exporting a vulkan semaphore and using it from CUDA. One can imagine this would be necessary to ensure the CUDA copy is correctly synchronised. I can believe that the existing barrier logic on the buffer -> …

Implement cuda/nvdev hwdec for vulkan backend

---

stream/stream_smb.c

strncpy does not guarantee that the string will be NULL-terminated.

Make sure the string is NULL-terminated after strncpy

---

video/out/opengl/hwdec_drmprime_drm.c

Since 810acf32d6cf0dfbad66c602689ef1218fc0a6e3 video_plane can be NULL
under some circumstances. While there is a check in init, init treats
this as an error condition and would call uninit, which in turn calls
disable_video_plane, which would then segfault. Fix this by including
a NULL check inside disable_video_plane, so that it doesn't try to
disable what isnt' there.

hwdec_drmprime_drm: Missing NULL-check on drm_atomic_context video_plane

---

waftools/checks/custom.py
waftools/detections/compiler_swift.py
wscript
wscript_build.py

this doesn't seem very nice. i suppose using an argument list would probably better than quoting everything in a string?
Fixes #6220

build: add quotes to all Swift build related paths

---

input/ipc-unix.c

On my system, when trying to use mpv with a read-only fd created by
python 3.7, `send` triggers ENOTSOCK, not EBADF. Extend the logic to
detect non-writable fds by this `errno`.

ipc-unix: don't blow up on readonly fd://

---

video/out/vulkan/malloc.c
video/out/vulkan/ra_vk.c
video/out/vulkan/utils.c

I was inconsistent about this originally, as the functionality was
moved into the core spec in 1.1 and so both suffixed and unsuffixed
versions of everything exist and can be mixed together.
There's no reason to fail to build with 1.0.39+ so I'm fixing the
names.

vo_gpu: vulkan: Always use KHR suffix types and defines

---

wscript

`vkGetPhysicalDeviceProperties2KHR` was added in Vulkan 1.0.39,
but 1.0.61 from Ubuntu Xenial (16.04) was the lowest anyone tried
to build mpv with as of late, so we are marking that as the minimum
required version.
This fixes issues arising during build time from having too old
version of vulkan available on a system, instead of causing a failure
to build.

build: add a version requirement for vulkan pkg-config check

---

video/out/cocoa/events_view.m

filling both NSViews with any colour fixes the blank screen on macOS 10.14. though i have no bloody clue why it does that.
anyway i deprecated the cocoa backend and don't really care, though if we want to keep it (even if just for reference) it should at least draw something.
there are still all the other various issues. on resize the content behind the window flickers through and i am not sure if this is a new or old issue.

cocoa: fix drawing on macOS 10.14

---

video/out/opengl/ra_gl.c

vo_gpu: opengl: disable compute shaders for old GLSL

---

video/out/vo_x11.c

vo_x11: fix return value in resize() error paths

---

video/out/opengl/hwdec_cuda.c

We are currently unnecessarily including vulkan headers even when
not building with vulkan support. I also guarded the GL header
inclusion even though this doesn't appear to break anything today.
Fixes #6330.

vo/gpu: hwdec_cuda: Guard GL and Vulkan headers properly

---

filters/f_auto_filters.c

Historically, there's been no way to offer deinterlacing with nvdec,
and for cuviddec, it required a command line flag, with no way to
toggle while playing.
Now that we have a cuda deinterlacing filter in ffmpeg, we can hook
it up hook it up as the cuda auto-deinterlacer. In practice, this
isn't going to be present very often, due to the licensing mess with
the cuda sdk, but we can support it when it is there.

filters: Add cuda/nvdec deinterlacing auto-filter using vf_yadif_cuda

---

DOCS/man/options.rst

Extra line prevents the sub-title formatting.
Removing it, the option is formatted like the others.
With extra line:

man: fix --watch-later-directory formatting

---

DOCS/client-api-changes.rst
DOCS/interface-changes.rst
DOCS/man/vo.rst
libmpv/client.h
libmpv/render.h
libmpv/render_gl.h
video/out/drm_atomic.c
video/out/drm_atomic.h
video/out/drm_common.c
video/out/drm_common.h
video/out/gpu/libmpv_gpu.c
video/out/opengl/context_drm_egl.c
video/out/opengl/hwdec_drmprime_drm.c
video/out/vo_drm.c

The names `drm-osd-plane-id` and `drm-video-plane-id` have been nothing but a source of confusion. One being that the "OSD plane" is actually used for both video and OSD whenever the drmprime-drm hwdec interop is not being used. The -id part is also confusing, since the options in fact accept an index into the list of applicable planes for the currently selected CRTC, and not the DRM object identifier as one might be lead to think (this problem is especially grave when it comes to the variable names used internally in the code).
Instead I propose we name the same options `drm-draw-plane` and `drm-drmprime-video`. `drm-osd-size` follows and becomes `drm-draw-surface-size`.
I also make the options accept the generic parameters "overlay" and "primary", so that a user can specify simply …

drm: better names for  plane options/variables etc.

---

DOCS/man/options.rst
stream/stream_dvb.c

Also, fix an off-by-one check in the code.
closes #6371

stream_dvb: Correct range for dvbin-card option.

---

player/command.c

doing multiply on a property is also a set property command
and the change should be notified so others can observe the change
For example, without this lua scripts cannot observe when volume changes.

command: notify on multiply

---

DOCS/man/options.rst
demux/demux.c
demux/demux_lavf.c

demux: make ALBUM ReplayGain tags optional when using libavformat

---

player/lua/defaults.lua

Idle handlers should be processed after all events have been processed, regardless of whether there are timers. Fixes #5266.

lua: execute idle handlers after timers have been processed

---

player/lua/stats.lua

Merge file-size/file-format and audio channel-count/format into one line
respectively. This fixes stats overflowing the screen in larger than
19:6 aspect ratios. In this case a problem was reported for ~21:9 which
should be common enough for us to "support" it.
Screenshots illustrating the problem by @Akemi: https://0x0.st/s7lL.png https://0x0.st/s7lp.png

stats: merge multiple properties into one line

---

video/decode/vd_lavc.c

yeah i found it kinda unexpected that i had to use `videotoolbox-co`. first i thought the copy modes just didn't work on my end because of that. `--hwdec=help` showed `videotoolbox-co` and the manual says `videotoolbox-copy`.
i don't know if there was a reason for the 16 char length? i arbitrarily increased the size by 8 since 16 was also a multiple of 8 too.

vd_lavc: increase the possible length of the hwdec name

---

video/out/cocoa-cb/window.swift

basically some old and now unneeded code prevent the Split View to work properly in all cases.
Fixes #6443

cocoa-cb: fix side by side Split View again

---

osdep/macosx_compat.h

macosx_compat.h fix typo

---

DOCS/man/input.rst
osdep/macOS_swift_bridge.h
osdep/macOS_swift_extensions.swift
video/out/cocoa_cb_common.swift
wscript_build.py

i decided to use swift extensions to make it look less messy and for convenience. if we have those feature they should be used. i could clean up the type casting for the displayID a bit. if really wanted i could leave it as is and use a normal function for the `displayName`.
otherwise `displayName` is an optional because retrieval of the name could theoretically fail. in that case `Unknown` will be returned as name.
[edit]
since the display info dict isn't so well documented [this](https://0x0.st/sYAJ.txt) is how it could look like. `kDisplaySerialNumber` can be an optional, this is the case for my TV for example.
the display name itself is what is used in the System Information, eg. `DELL X` or `LG TV`

cocoa-cb: add support for VOCTRL_GET_DISPLAY_NAMES

---

video/out/cocoa-cb/events_view.swift

the `propertyList` functions adds an empty element at the end of the array, even so the `NSURLPboardType` type only supports one dropped URL atm per docs. just remove all empty elements instead of using just the first element of the array since `handleFilesArray` expects an array. it's a bit more future proof in the case Apple ever decides to allow more than one URL to be dropped on a view.
Fixes #6241

cocoa-cb: remove empty elements from dropped URLs

---

video/out/wayland_common.c
video/out/wayland_common.h

This is the naming xdg-shell stable adopted, it doesn’t make much sense to keep using “shell” everywhere with all functions calling it “wm_base”.
Finishes what 76211609e3c589dafe3ef9a36cacc06e8f56de09 started.

wayland_common: rename “shell” into “wm_base”

---

filters/f_swresample.c

Use `mp_aframe_get_planes` to properly get the number of planes, instead
of assuming it to be the number of channels.
Fixes #6092

audio: fix segfault caused by incorrect number of planes

---

player/loadfile.c

As stated in the original commit message, if the demuxer set the start
time to the first subtitle packet, the subtitles would be shifted
incorrectly. It appears that it is the case for external PGS subtitles.
This reverts commit 520fc7403621156676b1ca183aed4911bf6c47b5.
Fixes #5485

player: do not rebase start time for subtitle streams

---

demux/demux.c

The seek range update was to early and did not take the removed head
packets into account. And therefore missed that the queue was not
BOF anymore.
This led to not be able to backward seek before the first packet of
the first seek range.
Fix it by moving the seek range update after the possible removal and
the change of the BOF flag.
Fixes: #6522

demux: fix seek range update after head packets are pruned

---

sub/filter_sdh.c

Only printable ASCII characters were considered to be valid texts. Make
it possible that UTF-8 contents are also considered valid.
This does not make the SDH subtitle filter support non-English
languages. This just prevents the filter from blindly marking lines that
have only UTF-8 characters as empty.
Fixes #6502

sub: recognize UTF-8 characters in SDH subtitle filter

---

demux/demux_edl.c

There could be another comment line or the end of the file.
Fixes #6529.

demux_edl: don't assume data follows a comment line

---

osdep/macosx_events.m
waftools/detections/compiler_swift.py

- Enable debug (-g) in swiftc (how was this not done ages ago)
- Fix a crash when shutting down during window animations (e.g. very short playback)

Swift fixes

---

waftools/generators/sources.py

i wasn't aware that disabling the cplugins, disables `syms` and because of that `do_the_symbol_stuff` is never called. because of that `handle_add_object` is again called before the link_task is created.
now `handle_add_object` is called after the same [tasks](https://github.com/mpv-player/mpv/blob/master/waftools/syms.py#L36) as `do_the_symbol_stuff` is called after.

build: fix adding of object files to linking with cplugins disabled

---

video/out/gpu/video.c

The old size limit was chosen before LUT texture was supported in user
shader. At that time, the whole user shader will be compiled and run
on GPU, which makes large user shader impractical to be used.
With the introduction of LUT texture, the old size limit doesn't make
any sense. For example, a 1024x1024 rgba16f LUT will cost 32MB shader
size.
Fix this by increasing the size limit to a value that's unlikely be
reached.

vo_gpu: increase user shader size limit

---

video/out/x11_common.c
video/out/x11_common.h

Regression from 8e3308d687c3acdd0d572015b06efd5b492d93ee.
Broken cases were:
* --no-cursor-autohide acted like --cursor-autohide=always.
* --cursor-autohide-fs-only always hid the cursor if starting
non-fullscreen; entering fullscreen at least once fixed it.
Also added brief descriptions of the two cursor visibility state variables since I had a bit of trouble keeping them straight when I was debugging this.

x11: fix cursor hiding initial state

---

DOCS/man/mpv.rst

The cache options were changed, and this commit
fixes the example big-cache profile to use the
new cache options.

DOCS/man/mpv.rst: Fix big-cache profile example

---

demux/cue.c

Remove the 2-digit-number restriction when reading the number of
minutes in the cue sheet INDEX command.
Fixes #6481

demux: support cue sheets longer than 100 minutes

---

waftools/checks/custom.py
waftools/detections/compiler_swift.py

i didn't really like the version check and decided to use an undocumented class (StrictVersion) from [distutils.version](https://svn.python.org/projects/python/trunk/Lib/distutils/version.py). it's used by many other projects too, though i am not quite sure about the current state ([PEP386](https://www.python.org/dev/peps/pep-0386/) and [PEP440](https://www.python.org/dev/peps/pep-0440/)). apparently a replacement was planned but never merged since 2014? wasn't sure if we want it in.
the second commit adjusts the swift check output message to match the rest, eg in the form of `no ('lib >= lib_min_ver' not found)` when failing, additional it outputs the found version. the latter because it makes debugging easier for me.
the last one is just a minor version bump to the needed swift version. …

build: minor swift build changes

---

osdep/macOS_mpv_helper.swift
video/out/cocoa_cb_common.swift

no idea why i forgot to add it there. added the wakeup call like in the [old cocoa](https://github.com/mpv-player/mpv/blob/1842a932d37638c910f4471d85e81554076c3d2c/video/out/cocoa_common.m#L138) backend. the vo struct needs to be available for the flagEvents function (same as in the [old cocoa](https://github.com/mpv-player/mpv/blob/1842a932d37638c910f4471d85e81554076c3d2c/video/out/cocoa_common.m#L587) backend) since some of the events are sent by cocoa events and that struct wouldn't be available in these cases.

cocoa-cb: wakeup vo when new events are available

---

video/out/cocoa_cb_common.swift

This is a small regression which was fixed in the old cocoa backend and forgotten in cocoa-cb.
also properly handle optionals by not force unwrapping them.
Fixes #3957 again

cocoa-cb: fix Space switching when quitting fs

---

video/out/cocoa-cb/window.swift

yeah, a very dumb bug. i never noticed from my testings since my secondary screen had a smaller resolution than my main one.
i conducted some tests, wrote a small [test script](https://github.com/Akemi/test_secondary_screen_window_position) and wrote down my findings. this probably should be reported to Apple.
Fixes #6453

cocoa-cb: fix a Cocoa window position on init bug

---

DOCS/interface-changes.rst
DOCS/man/options.rst
osdep/macOS_mpv_helper.swift
osdep/macOS_swift_extensions.swift
osdep/macosx_application.h
osdep/macosx_application.m
video/out/cocoa-cb/events_view.swift
video/out/cocoa-cb/title_bar.swift
video/out/cocoa-cb/window.swift
video/out/cocoa_cb_common.swift
wscript_build.py

`cocoa-cb: add support for mac 10.14 Dark mode and run time switching` provides everything PR #5995 does besides the run time switching on macOS earlier than 10.14, because Apple only added official support for it on the newest macOS version. see my comments on the other PR. it's also a bit simpler. that commit could theoretically be removed/merged since it's basically completely refactored in the next commit.
i decided to refactor the title bar styling completely because Apple broke and changed the majority of the stylings, so styling names and the actual look didn't match anymore. i removed the old option and added two new instead, that way the user has more freedom and it's hopefully a bit more future proof. not all combinations of appearances and materials make sense, some are …

cocoa-cb: title bar refactor

---

audio/out/ao_audiounit.m
audio/out/ao_coreaudio_utils.c
audio/out/ao_coreaudio_utils.h

In auditing the ao_audiounit code, I noticed several pieces which were missing. These make the implementation more "correct", and should theoretically improve a/v sync.
I haven't tested this very thoroughly, and in the random videos I tried it didn't seem to make any difference (atleast on my audio setup). A deeper investigation is warranted, perhaps using some kind of video sample optimized for checking lip sync.
cc @sergiou87 @rcombs @sixones @LukePulverenti @ebr11

ao/audiounit: improve a/v sync

---

TOOLS/appveyor-install.sh

This fixes the Appveyor build, which has been broken for a while. Not sure if anyone still cares about it now that Travis is testing Windows as well, but I suppose it's nice to verify that mpv still builds on native Windows.

Fix shaderc dependencies in the Appveyor build

---

osdep/macOS_mpv_helper.swift
osdep/macOS_swift_extensions.swift
video/out/cocoa-cb/events_view.swift
video/out/cocoa-cb/title_bar.swift
video/out/cocoa-cb/video_layer.swift
video/out/cocoa-cb/window.swift
video/out/cocoa_cb_common.swift

only the last commit is relevant. this removes all the forced unwrapping of optionals, with a few exceptions. one is the cocoaCB object which is always available, it's only an optional in some cases because weak vars have to be optionals. the other exception are the cgl pixel format and the context. both are initialised at init of the layer, but couldn't be nicely set before the super.init call.
otherwise this will most likely fix many segfaults that can only be reproduced in very rare conditions if at all.
this depends on following PRs  #6337 #6469 #6491 #6487 #6466 #6336 #5878 #6317 (#6277).

cocoa-cb: remove all force unwrappings of optionals

---

DOCS/man/vo.rst
video/out/drm_common.c
video/out/drm_common.h
video/out/opengl/context_drm_egl.c
video/out/vo_drm.c

--drm-mode now has a proper help option (you no longer have to say --drm-mode=-1 and supply a file to mpv) which lists the available modes of all active connectors. This is also a stepping stone to even nicer ways of specifying the mode for --drm-mode.
<strike>--drm-osd-plane-id and --drm-video-plane-id now take the options "primary" and "overlay" allowing you to select planes by this property, rather than by index.</strike> already merged in another PR.
<strike>I've ordered the commits to facilitate partial merging, should we want just the bug fixes for 0.29.</strike>

drm: user-friendlyness improvements to some options

---

osdep/io.h
stream/stream_libarchive.c

Suggested in IRC as a possible fix to #5759 and #6488. Currently libarchive uses C.UTF-8 as a locale, but that is debian specific and thus broken on other linux distros and macOS. This PR leaves C.UTF-8 as the default, but falls back to LC_CTYPE which should just use the environment variable of the current system. Of course, this also supersedes #6438 and #6268. 

libarchive: add fallback for systems without C.UTF-8

---

DOCS/man/vf.rst

I assume (but cannot confirm) that VA-AP-API is in fact a typo, because most if not all search engine results related to it are from mpv's manual page.
By changing this to VA-API and clarifying that this requires VA-API support on a system to use it, we can hopefully make it clear to unsuspecting Windows users that this is not the filter they're looking for.
Concerns #6690.

man: clarify vavpp requirements

---

video/out/wayland_common.c

Just some super low hanging fruit. There were a lot of extra wayland objects lying around that were never properly freed. There's some more memory leaks, but those are more complicated (i.e. I haven't figured them out yet) and this is pretty nice and concise as it is.

wayland: fix various memory leaks

---

DOCS/man/options.rst
video/out/gpu/user_shaders.c
video/out/gpu/user_shaders.h
video/out/gpu/video.c

This commit essentially makes user shader able to fix offset (produced
by other prescaler, for example) like builtin `--scale`.
@haasn
Test I conducted to verify the commit works as expected:
1. Apply following patch to mpv, to disable offset fixing functionality of `--scale` (when `--scaler-resizes-only` kicks in). The following of the test assumes video is not resized (`--window-scale=1.0` for example).
~~~patch
diff --git a/video/out/gpu/video.c b/video/out/gpu/video.c
index 6004a0ab60..62def3e749 100644
--- a/video/out/gpu/video.c
+++ b/video/out/gpu/video.c
@@ -2336,12 +2336,8 @@ static void pass_scale_main(struct gl_video *p)
struct scaler_config scaler_conf = p->opts.scaler[SCALER_SCALE];
if (p->opts.scaler_resizes_only && !downscaling && !upscaling) {
scaler_conf.kernel.name = …

vo_gpu: allow user shader to fix texture offset

---

TOOLS/appveyor-build.sh
TOOLS/appveyor-install.sh
video/out/d3d11/ra_d3d11.c
wscript

SPIRV-Cross recently added its own built-in C API, which makes crossc kind of unnecessary. This replaces crossc usage with the SPIRV-Cross C API.
Note: I'm not sure if this should be merged right away, because I'm not sure if the current version of SPIRV-Cross is suitable for static linking. Instead, I'm happy for this to be merged at @lachs0r or @shinchiro's convenience (though I'd like to deprecate crossc sooner or later.)

Replace crossc with SPIRV-Cross' built-in C API

---

demux/demux_mkv_timeline.c

Fixes #6009.
This is pretty simplistic. The only questionable case I can see is multiple segments containing fonts with the same name. If they're actually the same font, it seems to work fine -- I tested that. It's just a bit of a waste, I guess. If they aren't the same, well, that'd pretty much have to be an intentionally messed up file and isn't worth worrying about IMO. The "correct" way might be to reinit libass when switching tracks with only the fonts from that segment, but I really don't think that's worth the added complexity.
We could skip the copy for attachments that already appear to be loaded (by name and mime type). Is that worth it?
This is copying more than it has to, because the additional demuxers stay alive and we could just point to their attachments instead of copying …

demux_mkv: copy attachments (fonts) from ordered chapter sources

---

DOCS/man/options.rst
video/out/gpu/error_diffusion.c
video/out/gpu/error_diffusion.h
video/out/gpu/video.c
video/out/gpu/video.h
wscript_build.py

This is a straightforward parallel implementation of error diffusion
algorithms in compute shader. Basically we use single work group with
maximal possible size to process the whole image. After a shift
mapping we are able to process all pixels column by column.
A large ring buffer are allocated in shared memory to speed things up.
However the size of required shared memory depends linearly on the
height of video window (or screen height in fullscreen mode). In case
there is no enough share memory, it will fallback to '--dither=fruit'.
The maximal allowed work group size is hardcoded as 1024. Ideally we
could query GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS. But for whatever
reason, it seems most high end card from nvidia and amd support only
the minimal required value, so I guess we can stick …

vo_gpu: implement error diffusion for dithering

---

TOOLS/appveyor-build.sh
TOOLS/appveyor-install.sh
appveyor.yml

This should fix the Appveyor build (again.) ANGLE was removed from MSYS2, so the ANGLE build is no longer tested, but that's probably fine.

Fix Appveyor for libplacebo and recent MSYS2 changes

---

video/out/d3d11/ra_d3d11.c
video/out/gpu/ra.h
video/out/gpu/utils.c
video/out/opengl/ra_gl.c
video/out/placebo/ra_pl.c

While `ra` supports the concept of a texture as a storage
destination, it does not support the concept of a texture format
being usable for a storage texture. This can lead to us attempting
to create a texture from an incompatible format, with undefined
results.
So, let's introduce an explicit format flag for storage and use
it. In `ra_pl` we can simply reflect the `storable` flag. For
GL and D3D, we'll need to write some new code to do the compatibility
checks. I'm not going to do it here because it's not a regression;
we were already implicitly assuming all formats were storable.
Fixes #6657

video/out/gpu: Add a `storable` flag to ra_format

---

video/out/opengl/context_wayland.c

If the compositor sends a configure event before the surface is initially
mapped, resize gets called before the egl_window gets created, resulting
in a crash in wl_egl_window_resize.
This was fixed back in 618361c697, but was reintroduced when the wayland
code was rewritten in 68f9ee7e0b.

opengl/context_wayland: Fix crash on configure before initial reconfig

---

video/filter/vf_vapoursynth.c

Single-threaded data copying becomes a real performance bottleneck in case of 4K, especially with 10 bit color depth and high frame rates.

vf_vapoursynth: remove excessive locking when reading/writing frames

---

player/client.c

Currently, sending a command to an uninitialized mpv core will leak memory since the mp_cmd struct isn't freed. Reordered it to make sure it won't try to free the cmd if it doesn't exist.

client: fix potential mpv_command memory leak

---

TOOLS/dylib-unhell.py
TOOLS/osxbundle.py
osdep/macOS_mpv_helper.swift
osdep/macOS_swift_compat.swift
osdep/macOS_swift_extensions.swift
video/out/cocoa-cb/events_view.swift
video/out/cocoa-cb/title_bar.swift
video/out/cocoa-cb/window.swift
video/out/cocoa_cb_common.swift
waftools/checks/generic.py
waftools/detections/compiler_swift.py
waftools/generators/headers.py
wscript
wscript_build.py

this depends on #6635 #6655 #6637.
1. the macOS SDK path and version was made configurable, so one can overwrite the autodetected values in the case of fail detection and none Apple toolchains.
2. with the removal of optional force unwrappings we broke building on macOS 10.12, this is fixed before the migration to swift 5/4
3. the swift 5 migration was tested on various platforms and combinations of toolchains. building works with all Apple provided toolchains from 10.12.6/xcode 9.1/swift 4 onwards. in some combinations the swift 5 toolchains from swift.org work too.
4. i tired to keep all compatibility stuff in a separate file. that way it's less intrusive and can easily be removed later when unneeded.
```
success:
macOS 10.12.6	SDK10.13		xcode 9.2	swift 4.0.3
macOS 10.13.6	SDK10.13 …
```

cocoa-cb: migrate to swift 5 with swift 4 fallback

---

video/out/hwdec/hwdec_vaapi.c

This is documented as required (although we did not do it in
the old GL codepath, with no visible problems) and I have seen
transient artifacts after seeking which _appear_ to have gone
away after introducing this.

vo_gpu: hwdec_vaapi: Synchronise after exporting VA surface

---

common/encode_lavc.c

encode: set sample_aspect_ratio on AVStream struct

---

video/out/vulkan/context.c

We collect a 'vulkan-device' option today but then don't actually
pass it on, so it's useless. Once that's fixed, it can be used
to select a specific vulkan device by name.
Tested with the new nvidia offload feature to select between the
nvidia and intel GPUs.

vo/gpu: vulkan: Pass the device name option through to libplacebo

---

DOCS/man/osc.rst
player/lua/assdraw.lua
player/lua/osc.lua

This looks much better imho. In case of the bar style we won't see seek ranges in the past, but that is of little use. If desired I can also make this change into a seekbarstyle option for users to chose from.
See the screenshot for comparison. Top 3 is before and bottom 3 are after. Note that slider style wasn't changed at all since that looks fine (and doesn't really work with the way the seek ranges are rendered now).

osc: improve look of seekranges

---

stream/stream_dvb.c

Discussion in https://github.com/mpv-player/mpv/pull/6372 has highlighted two issues which are fixed in this commit series:
- VDR `channels.conf` is rather flexible about units for the frequency (it accepts Hz, kHz and MHz). We now do as VDR does and multiply the value provided in the config file by 1000 until 1000000 is reached. This fixes compatibility especially with more recent `channels.conf` files. 
- DVB-T2 hardware in some cases seems to be too slow to actually deliver data within 2.5 seconds(!) after tuning. Increase the timeout to 10 seconds. 
Thanks to @berndbb both for finding the issues and for testing my fixes on his HW!

DVB fixes (slow hardware, VDR channels.conf)

---

demux/demux.c

this for example allows --demuxer=rawaudio to work on directories

demux: ignore forced demuxer type for directories

---

player/external_files.c

Currently mpv doesn't load .lrc synced lyrics with the same filename as the song playing, unless you rename them to a supported extension like srt or load them with a Lua script. This pull request just adds lrc to the sub extensions so that the lyrics will be loaded.
Other people who encountered this issue:
[https://unix.stackexchange.com/questions/510422/play-lyrics-automatically-with-mpv](https://unix.stackexchange.com/questions/510422/play-lyrics-automatically-with-mpv)
[https://gist.github.com/guixxx/a349d27d271ca100685c3ce5fb1d5c9f](https://gist.github.com/guixxx/a349d27d271ca100685c3ce5fb1d5c9f)

Autoload .lrc lyrics

---

video/out/gpu/video_shaders.c

In the past, src peak was always equal to or higher than dst peak. But
since `--target-peak` got introduced, this could no longer be the case.
This leads to an incorrect result (scaling for peak mismatch in gamma
light) unless some other option (CMS, --linear-scaling, etc.) forces the
linearization.
Fixes #6533

vo/gpu: fix check on src/dst peak mismatch

---

video/out/opengl/context_glx.c
video/out/opengl/context_x11egl.c
video/out/opengl/oml_sync.c
video/out/opengl/oml_sync.h
wscript_build.py

Presentation feedback, now also for context_x11egl. Trivially backportable, and useful.
Tested to work.
I believe this still suffers from the same race condition as with GLX, but there's not much more you can do with what this extension gives you (actually for GLX there might be some hope still, but as far as I can tell it's pretty hopeless on the EGL side of things since the extension only has eglGetSyncValuesCHROMIUM).

vo_gpu: x11egl: support Mesa OML sync extension

---

player/playloop.c

Fixes #6898. This prevents the pause state from triggering before the audio output is
finished playing back audio. This is particularly helpful for gapless playback.

audio: block ao buffer for keep-open

---

stream/stream_file.c

`s->priv->cancel` will be freed when `s` is freed.
cc a0cce7f775e97aa364d166c278c49df1325e6cc7 @eric

stream_file: avoid double free

---

video/out/d3d11/context.c
video/out/d3d11/hwdec_dxva2dxgi.c

vo_d3d11: fix memory leak that 'ctx11' be not released and crash due to ctx->ra is null pointer access

---

video/out/hwdec/hwdec_cuda.c
video/out/hwdec/hwdec_cuda.h
video/out/hwdec/hwdec_cuda_gl.c
video/out/hwdec/hwdec_cuda_vk.c

This change updates the interop selection to match what I did for
VAAPI, by iterating through an array of init functions until one
of them works.

vo_gpu: hwdec_cuda: Improve interop selection mechanism

---

video/out/wayland_common.c

This one is probably not terribly obvious from just the valgrind log,
but a wayland dev explained it to me just a second ago. Whenever mpv
sends events to the screen with `wl_display_dispatch`, wayland internally
allocates memory to a `struct wl_proxy` object if a new id is found. Quite
a few more things happen to that proxy object, but eventually mpv stores
the data on the client-side in a wrapper type of struct (`struct
wl_data_offer`). mpv's `data_device_listener` keeps track of those proxies
and frees the memory when appropriate. Of course, mpv is constantly
sending events to the screen and does so until the user quits the
player. What happens here is that one final `wl_display_dispatch` is called
right before the user quits the player and before mpv's
`data_device_listener` can …

wayland: fix wl_proxy leak

---

video/filter/vf_fingerprint.c
wscript

I was assuming posix_memalign was the most portable function to use, but
MinGW does not provide it for some reason. Supposedly it provides  C11
aligned_alloc(), and that function is more elegant than posix_memalign()
anyway, so switch to that.
Just to be sure, add a configure test for aligned_alloc(). In theory we
still support C99.
---
Should fixes the CI build, …

vf_fingerprint: use aligned_alloc instead of posix_memalign

---

osdep/io.h
stream/stream_libarchive.c

Using LC_ALL_MASK is unnecessary and unreliable on some systems.

stream_libarchive: Always use LC_CTYPE_MASK for libarchive

---

video/out/wayland_common.c

Fixes #6796. 
~~Will fix #6796 when complete.~~
~~If someone on Wayland with a fancy mouse with a lot of buttons could help me test this PR, that would be great. Adding more buttons is easy, but I don't actually know what they are registered as in the input-event-codes header since I don't own one of those kinds of mice.~~
~~I would need you to build this branch and then run `mpv --input-test --idle --force-window`. There's a printf line in here, so in the terminal it will print the decimal value of any button you press in the input-test. I just need the decimal value of any button pressed and what the button is called under x11 mpv (i.e. `MBTN9` and so on).~~
Done:

wayland: add mouse buttons and fix axis scaling

---

video/out/wayland_common.c
video/out/wayland_common.h

This is forked from #6480 with just a few more lines to fix what I had mentioned there. I only made this since there didn't seem to be any activity from @t-8ch. This also fixes #6185. On wayland, the cursor should automatically hide without having to move it (which is the current behavior). Also, the cursor shouldn't reappear when going to fullscreen (which is what happened with @t-8ch's fix).
Also as a side note, I personally don't really think it's necessary to define a whole new `reset_cursor` function. I think the name is misleading and `set_cursor_visibility(wl, wl->cursor_visible)` is more than clear and sufficient. I left `reset_cursor` since like 50% of this is stolen from @t-8ch anyway, but I'll happily change it if the devs agree with me.
I agree that my changes can be …

wayland: match x11 cursor behavior

---

player/lua/osc.lua

osc: add mouse mid-button as alias to shift+left button

---

video/out/x11_common.c
video/out/x11_common.h

To find the correct ICC profile X atom, the screen number was calculated
directly from the xrandr order of the screens.
But if a primary screen is set, it should be the first Xinerama screen,
even if it is not the first xrandr screen.
Calculate the the proper atom id for each screen.

x11: fix ICC profiling for multiple monitors

---

DOCS/man/input.rst
player/osd.c
sub/dec_sub.c

Currently, the `sub-text` property is explicitly disabled if subtitles are not visible. This just lets `sub-text` work regardless of sub visibility and preserves the behavior of subtitles in the terminal.

osd: allow sub-text to work even if sub-visibility is disabled

---

audio/out/ao_oss.c

ioctl(..., SNDCTL_DSP_CHANNELS, &nchannels) for not supported
nchannels does not return an error and instead set nchannels to
the default value.
Instead of failing with no audio, fallback to stereo.
Without this change file with >2 audio channels on devices that do
not support >2 channels ends up to not using any audio output.

ao_oss: Fallback to stereo when the device does not support >2 channels

---

DOCS/interface-changes.rst
DOCS/man/input.rst
player/command.c

They may be useful  for people who want to select tracks manually.

player: expose bitrate and rotation value on tracks

---

player/playloop.c

Fixes #6571
If a file format supports PTS resets, `get_current_pos_ratio` calculates
the ratio using the stored filepos in the `demuxer` struct instead of a
standard query of the current time in the stream and its total length.
This seems like a reasonable way to avoid weird PTS values, but in
reality this just causes problems and results in inaccurate ratio
values that can affect other parts of the player (most notably the osc
seekbar). For libavformat formats, `demux->filepos` is obtained from the
`demux_lavf_fill_buffer` function which is called on the next packet. The
problem is that there is a slight delay between packets and in some
cases, this delay can be relatively large. That means the obtained
`demuxer->filepos` value will be very inaccurate since it obtains the pos
from the …

playloop: don't read playback pos from byte stream

---

DOCS/man/input.rst
input/input.c
input/input.h
player/command.c

This adds `keybind` as a command which allows users to set input commands to specific keys. This is primarily useful for the client api and lua scripting although it does work in input.conf as well. There's maybe a couple of things people won't like though.
- The argument order is `keyname` and then `command` so for example an entry in `input.conf` would look like this: `keybind CTRL+l "add volume 10"`. To me, this looks better than `keybind "add volume 10" CTRL+l` but maybe people disagree.
- I exposed a new function, `mp_input_bind_keys`, to the header that copies parts of the `bind_keys` function for this. `bind_keys` is clearly geared towards parsing a file so I didn't think modifying it would be appropriate. I did make the choice of calling the location `keybind-command` so that name …

input: add keybind command

---

sub/lavc_conv.c

During initial testing with US closed captions, ARIB captions,
timed text in MP4 or the specific external SRT files I tested with
there were no hints that this flag would be needed for seeking to
work.
Unfortunately, that result seems to have been incorrect.
Fixes #6970

sub/lavc_conv: skip ReadOrder reset when subtitle decoder gets flushed

---

waftools/generators/sources.py
wscript

Use `private-code` instead of `code` here.<sup>[1](https://gitlab.freedesktop.org/wayland/wayland/commit/9b76def674f0a0b99f5850cc800017fc4e03af7d)</sup>

waf: fix wayland-scanner deprecation warning

---

wscript

This test requires libavutil headers but there is no avutil
dependency for it to use. So let's add one, and also reorder the
ffmpeg tests ahead of the video tests so that the avutil dependency
can be used.

wscript: Fix test for ffmpeg drmprime support

---

video/out/wayland_common.c

Certain mpv config options require wl->current_output to be created
before the video can actually start rendering. Just always create it
here if the current_output doesn't exist (the one exception being the
--fs option with no --fs-screen flag). Incidentally, this also fixes
--fs-screen not working on wayland.
Fixes #6653.

wayland: create current_output in wayland_reconfig

---

waftools/detections/compiler.py

Previously the options were tested by compiling a test program with the
option, and support was "detected" if the compilation didn't fail.
However, both gcc and clang only issue a warning on unknown warning option,
hence it never failed and all the warn options were detected as supported.
Now the tested option is used together with -Werror, which makes it fail
if it warns that the warning option is unknown.
Fixes clang unknown option warnings -Wno-format-truncation since 4a6b56f .

build: actually detect supported warning options

---

DOCS/man/input.rst
player/command.c

The question came up on how a client would figure out where screenshot-directory saved its screenshots if it contained mpv-specific expansions. This command should remedy the situation by providing a way for the client to ask mpv to do an expansion.

command: add expand-path to expand mpv paths

---

DOCS/man/options.rst

We default to EGL instead of GLX now, which means vdpau only works if we explicitly specify that we want a GLX context, as vdpau lacks interop for EGL.
Update the hwdec documentation to reflect this.
Concerns #6980.

manpage: update requirements for vdpau hwdec use

---

video/out/cocoa-cb/title_bar.swift

title bar buttons were still clickable right after start up even though they were invisible. just makes the state consistent.
[edit]
only the last commit is relevant, depends on #6595.

cocoa-cb: fix title bar button state on start up

---

demux/demux.c

This was a leftover from commit b2752321 which fixed #6522 but after
the recent demux refactoring this fix is superseded by commit 0f6cda4ab.
Remove the redundant update call.

demux: remove redundant seek range update

---

player/command.c

When the (float) bitrate is returned, it is implicitely converted to an
int64 value, merely discarding the fractional part.
However the bitrate of a CBR track can vary a bit due to timestamp
precision loss after clock conversion (this can affect MPEG-TS audio
tracks). So a bitrate like 191999.999... results in 191999 when
being returned - instead of 192000.
To fix this, apply proper rounding.
----

command: fix bitrate rounding error

---

video/out/d3d11/context.c

Now that I think about it, I don't think it's necessary for get_vsync to know when mpv starts and stops producing frames just to predict the next frame time. New frames will be presented at the same time regardless. It only needs to know if the swapchain underflows, and it already checks for that.

Don't reset D3D11 frame statistics after pause

---

wscript

cc #5331
fixes build errors like:
```
osdep/subprocess-posix.c:82:9: error: 'posix_spawn_file_actions_init' is unavailable: not available on tvOS
if (posix_spawn_file_actions_init(&fa))
^
```

wscript: detect tvOS and disable posix-spawn usage

---

video/out/android_common.c
video/out/android_common.h
video/out/gpu/context.c
video/out/opengl/context_android.c
video/out/vo.h
video/out/vulkan/context_android.c
wscript_build.py

Todo:
no, `InitVulkan()` can be called by support code external to mpv.
how to test: use with[`sfan5/vk`](https://github.com/mpv-android/mpv-android/tree/sfan5/vk) branch of mpv-android

Vulkan context for Android

---

audio/out/ao_pulse.c

Originally DTS-HD was mapped to PA_ENCODING_DTS_IEC61937 which I'm
actually not sure if it ever worked.
These identifiers were added in https://gitlab.freedesktop.org/pulseaudio/pulseaudio/commit/cdeac178019ed3e73840702cb1223df5edd9df43 , which was part of PA version 13. This is rather recent, and thus I'm continuing the ifdef trend (unfortunately).

ao_pulse: add the newly added mappings for TrueHD/DTS-HD formats

---

video/out/opengl/hwdec_drmprime_drm.c
wscript

This allows to use drm hwaccels that require a hwdevice.
Tested with exprimental [v4l2request hwaccel](https://github.com/Kwiboo/FFmpeg/compare/4.0.4-Leia-18.4...v4l2-request-hwaccel-4.0.4) and cedrus driver on an allwinner H3 device
running mpv with `--vo=gpu --gpu-context=drm --hwdec=drm`.
Added `libdrm` version requirement since `drmGetDeviceNameFromFd2` was added in 2.4.74.

vo_gpu: hwdec_drmprime_drm: add hwdec ctx

---

wscript

TARGET_OS_TV seems to always be defined, but set according to the
build configuration. This fixes all Apple configurations being
mis-identified as tvOS.

wscript: check tvOS define's value to be nonzero

---

video/out/opengl/context_drm_egl.c

A user reported problems compiling because EGL_PLATFORM_GBM_KHR was undefined. This user was using nVidias proprietary driver without glvnd which might explain this missing?

context_drm_egl: Add ifdeffery to egl_get_display

---

DOCS/client-api-changes.rst
libmpv/client.h
libmpv/stream_cb.h
stream/stream_cb.c

Some added callbacks I've been using with custom stream_cb backends.
The first commit adds a straightforward `cancel_fn` which integrates the new mp_cancel feature.
The second commit adds `seek_time_fn` which covers a much more obscure use-case, and may require lavf patches depending on the demuxer used (tested with mpegts using https://patchwork.ffmpeg.org/patch/12604/).

stream_cb interface improvements

---

DOCS/man/options.rst
options/options.c
options/options.h
video/out/d3d11/context.c
video/out/drm_common.c
video/out/drm_common.h
video/out/gpu/context.h
video/out/opengl/context.c
video/out/opengl/context_angle.c
video/out/opengl/context_drm_egl.c
video/out/opengl/context_dxinterop.c
video/out/vo_drm.c
video/out/vo_gpu.c
video/out/vulkan/context.c

This ports the same kind of swapchain that context_drm_egl has to vo_drm, which should increase performance significantly by allowing the CPU to run more independently of vsync/not waste time waiting for vsync that could be spent drawing to a back buffer. This arrangement could easily cause high vsync jitter in display-resample mode, so presentation feedback becomes neccessary and is implemented in the same commit.
Further improvements include allowing vo_drm to requeue the same FB for repeat frames, which should help when playing videos with FPS lower than the display FPS in video-sync=display-resample mode by not wasting cycles on redrawing the same frame again.
<strike>TODO: Make the swapchain depth of vo_drm adjustable using --swapchain-depth or otherwise.</strike>

vo_drm: Implement triple buffering/N-buffering and presentation feedback

---

video/out/hwdec/hwdec_cuda.c
video/out/hwdec/hwdec_cuda.h
video/out/hwdec/hwdec_cuda_gl.c

Previously, there appeared to be implicit synchronisation in the
GL interop path, and we never observed any visual glitches. However,
recently, I started seeing stuttering in the GL path and on closer
examination it looked like read-before-write behaviour where GL
would display an old frame again rather than the current one.
After verifying that disabling hwdec made the problem go away,
I tried adding a cuStreamSynchronize() after the memcpys and that
also resolved the problem, so it's clearly sync related.
cuStreamSynchronize() is a CPU sync and so more heavy-weight than
you want, but it's the only tool we have. There is no mechanism
defined for synchronising GL to CUDA (It looks like there is a way
to synchronise CUDA to EGL but it appears one way and so wouldn't
directly address this …

vo_gpu: hwdec_cuda: Synchronise OpenGL Interop

---

wscript

`egl.pc` can be provided either by mesa or libglvnd. The latter doesn't
follow the same version scheme as mesa but instead uses the API version
that the library exposes, which is 1.5 for EGL[1]
[1] https://github.com/NVIDIA/libglvnd/commit/0dfaea2bcb7cdcc785f95e244223bd004a2d7fba#diff-b58a140c00ea99fb9a708e15afaade62R8

build: lower version requirement for EGL

---

demux/demux_libarchive.c
demux/demux_playlist.c
misc/natural_sort.c
misc/natural_sort.h
wscript_build.py

Based on discussion in #6016 with some feedback from @avih.
I have two versions of this. This one doesn't actually parse numbers; it just counts non-padding digits and falls back to lexicographical if they're the same order of magnitude. This might be too "clever". I've done an equivalent implementation using `strtoull` in 9479ba41aa1668808ad36926afd6268553ffe23d, which is much clearer code but will consider any numbers over ULLONG_MAX equal.

Sort filenames naturally when playing a directory / archive

---

video/out/vo_drm.c

Turns out clearing all frambuffers in reconfig isn't such a great idea
when you also end up here when setting pan/scan.
I guess this is just a leftover from a previous iteration of vo_drm
where doing this made sense.

vo_drm: fix flickering when setting pan/scan

---

stream/stream_lavf.c

Add support for gopher:// URLs so they can be played directly with mpv.

player: add support for gopher

---

DOCS/interface-changes.rst
DOCS/man/options.rst
video/out/d3d11/context.c
video/out/gpu/d3d11_helpers.c
video/out/gpu/d3d11_helpers.h

Further steps:
↑ so apparently d3d11va already expects the `ra_d3d11_create` helper to have been run, which is only run exactly where we do our selection. So hwdec is already affected ＼(^o^)／ .
Test build [here](https://megumin.fushizen.eu/builds/2019-04-20T10-33-mpv-git-a11bcb3d84-pr6647_d3d11_adapter_name.7z).
Usage (before we have added a listing):
1. Open and close a file with `--msg-level=vo/gpu/d3d11=v` (or use a log file)
2. See the listing
```
[vo/gpu/d3d11] Initializing GPU context 'd3d11'
[vo/gpu/d3d11] Adapter 0: vendor: 4318, description: NVIDIA GeForce GTX 1080
[vo/gpu/d3d11] Adapter 1: vendor: 5140, description: Microsoft Basic Render Driver
```
3. Use the description with `--d3d11-adapter-name`.
4. Bacon!

vo_gpu/d3d11: adapter selection by name

---

DOCS/interface-changes.rst
DOCS/man/options.rst
player/command.c
stream/dvbin.h
stream/stream_dvb.c

This commit series essentially brings back DVB channel switching. 
Basically, the commit messages contain everything, and I tried to be mostly atomic in my commits, but here a short summary (which sadly got almost as long as the summary of the commit messages):
- Some refactoring to allow checking options for updates as suggested by @wm4 in #6781 . This also cleaned up the option mess in `stream_dvb` by finally keeping them cleanly in a separate struct. 
- More refactoring, since `stream_dvb` accepts some configuration via the stream-URI and also via config parameters. Now, the logic is in one place, and config parameters (if set) always win (e.g. you can finally set a program by name via `dvbin-prog` as expected!). 
- Polling the options for changes. Done in `streaming_read` for lack of …

Bring back DVB channel switching

---

README.md

Link wasn’t attached to anything, and was referencing an archived repo anyway.
However (and this is a repeat of https://github.com/mpv-player/mpv-build/pull/122), you may want to consider reviving that repo, seeing as [the homebrew formula was removed](https://github.com/Homebrew/homebrew-core/commit/41444d526c40b93069b7f0c5414539deb0534179). There is [a cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mpv.rb) but it uses [the prebuilt binaries from `stolendata`](https://laboratory.stolendata.net/~djinn/mpv_osx/) as [referenced on your website](https://mpv.io/installation/).
The formula was almost four times more popular than the cask (6,938 vs 1,848 downloads in the last 90 days), which is why I mentioned reviving the formula on your side.
I’m a Homebrew Cask maintainer, …

README.md: remove dead homebrew-mpv link

---

video/out/wayland_common.c

I previously skipped creating the wl_output if the --fullscreen flag
with no --fsscreen_id was inputted, so the fullscreen video lands on the
correct output (where mpv was launched). This has breakage if someone
combines the --autofit flag (or other similar options with it). Instead,
just actually read xdg_shell spec and realize that you can pass NULL
to xdg_toplevel_set_fullscreen and let the compositor choose the
output if the user doesn't specify it. If this has issues, get a better
compositor.
I (or someone else) just needs to test this on multimonitors to make sure `--fullscreen` works right (i.e. fullscreen on the same output you launched the mpv window on) before I merge it. But I'd be very surprised if it didn't work as expected.
Fixes #7011

wayland: always create wl_output before rendering

---

video/out/opengl/context_wayland.c
video/out/wayland_common.c

Fixes #7019.
Sorry about the other commit. It was stupid. This fixes the memory leak that @wm4 found which occurs during probing without screwing up the vulkan api. Basically `vo_wayland_uninit` was never actually called if the probing for the wayland opengl backend failed meaning there was an extra dangling pointer.

Fix vulkan autoprobe crash

---

DOCS/interface-changes.rst
DOCS/man/input.rst
DOCS/man/options.rst
etc/input.conf
options/options.c
player/command.c

The justification for this is the fact that the `video-aspect` property
doesn't work well with `cycle_values` commands that include the value
"-1".
The "video-aspect" property has effectively no change in behavior, but
we may want to make it read-only in the future. I think it's probably
fine to leave as-is, though.
Fixes #6068.

options: rename --video-aspect to --video-aspect-override

---

player/loadfile.c

As mentioned in the issue #6450 trying to load files for the 'filename' `-` isn't very useful when reading a stream from stdin. I'm not sure if this was the right place to check for this edgecase. But it works out.
would resolve #6450

player: don't load external files when reading from stdin

---

DOCS/interface-changes.rst
DOCS/man/options.rst
video/out/d3d11/context.c
video/out/gpu/d3d11_helpers.c
video/out/gpu/d3d11_helpers.h
wscript

First part of getting to color space configuration (HDR and such).
Adds support for configuring the D3D11 swap chain format. For now we have  been utilizing 8bit RGBA, but other formats are available, such as 10bit RGB with 2bit alpha, 16bit floating point or 8bit BGRA.
The APIs querying the system output's information is surprisingly new, so the Windows dxgi header check is bumped from `dxgi1_2.h` to `dxgi1_6.h` (this is available at the very least on mingw-w64 6.x). The code should still work on Windows 7+, but the system output information will only be available for Windows 10 users at least according to what [MSDN says](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_6/nn-dxgi1_6-idxgioutput6)..
Current logic:
1. If a specific swap chain format is configured, that is …

vo_gpu/d3d11: add support for configuring swap chain output format

---

DOCS/man/options.rst
video/out/d3d11/context.c
video/out/gpu/d3d11_helpers.c
video/out/gpu/d3d11_helpers.h

1. Fixes up config file option based adapter selection by switching to bstr everywhere. I did think if I should have done it before, but I felt like being lazy. This cost me.
2. Switch adapter selection to a case insensitive startswith. Lets one do things a la `"intel"` or `"nvidia"`.
3. Removes an unnecessary nullptr check. `mp_to_utf8` will abort if something goes wrong.
4. Fix a memleak of the adapter description in case an adapter is picked.

vo_gpu/d3d11: misc fixups for adapter selection

---

DOCS/man/vo.rst
video/out/vo.c
video/out/vo_wlshm.c
wscript_build.py

vo_wayland was removed during the wayland rewrite done in 0.28. However,
it is still useful for systems that do not have OpenGL.
The new wayland_common code makes vo_wayland much simpler, and
eliminates many of the issues the previous vo_wayland had.

Reintroduce vo_wayland as vo_wlshm

---

video/out/vo.c
video/out/vo_wlshm.c
wscript
wscript_build.py

This syscall avoids the need to guess an unused filename in /dev/shm and
allows seals to be placed on it.  We immediately return if no fd got
returned, as there isn’t anything we can do otherwise.
Seals especially allow the compositor to drop the SIGBUS protections,
since the kernel promises the fd won’t ever shrink.

wlshm: Use memfd_create() instead of shm_open() on Linux

---

DOCS/man/options.rst
options/options.c
options/options.h
video/out/opengl/context_wayland.c
video/out/vulkan/context.h
video/out/vulkan/context_wayland.c
video/out/wayland_common.c
video/out/wayland_common.h
wscript_build.py

This makes use of the presentation time protocol for the wayland
context. ~~Unfortunately, using the stats lua script (or any other similar
script that constantly renders new things on the screen) breaks the
timings since wayland will register every script update as a
callback+presentation which then screws up the vsync values. There's
probably not a sane way to workaround this, but~~ the vsync numbers really
are much improved otherwise.
Closes #6236.

wayland: use presentation time

---

video/out/opengl/context_wayland.c
video/out/vulkan/context.c
video/out/vulkan/context_wayland.c
video/out/wayland_common.c
video/out/wayland_common.h

There's 2 stupid things here that need to be fixed. First of all,
vulkan wasn't actually using presentation time because somehow the
get_vsync function in context.c disappeared. Secondly, if the mpv window
was hidden it was updating the ust time based on the refresh_usec but
really it should simply just not feed any information to the vsync info
structure. So this adds some logic to assume whether or not a window is
hidden.
Fixes #7079. @aufkrawall, thanks for all the testing. This solves the problem for me. If it works for you in Sway and Plasma (no presentation time but just a double check to make sure nothing here interferes with it which it shouldn't), then I can merge it.

wayland: fix presentation time

---

video/out/wayland_common.c

Possibly fixes #7058. @syphoxy, does this work for you?

wayland: don't get data device if wl_seat is null

---

video/out/d3d11/context.c

I don't know if this bug can occur with flip-model present, but it might be possible if SyncRefreshCount can advance past PresentRefreshCount, and the docs aren't clear about whether this can happen on dropped frames or not.

Prevent wraparound in D3D11 queued frames calculation

---

video/out/d3d11/ra_d3d11.c
video/out/gpu/ra.c

The flag was added in e2976e662d92. We can set it in D3D11 from the flags in D3D11_FEATURE_FORMAT_SUPPORT2. This also includes a change for logging the storableness of each ra_format alongside the other flags in the debug output.

Implement the ra_format.storable flag for the D3D11 backend

---

DOCS/man/osc.rst
player/lua/osc.lua

Among the pointless duplication the right timecode label was given some extra space that wasn't needed.
Fixes: #6904

osc: Unify bottom and topbar code

---

sub/ass_mp.c

Sometimes the atlas can get so large that it exceeds the maximum allowed size for an mp_image. Since the atlas will never shrink naturally, this breaks subtitles entirely until mpv is restarted. Reset the packer so that subtitles can rendered properly once the atlas fits again.
This is a partial workaround for #6286.

ass_mp: reset packer when allocation fails

---

README.md

markdown reference style link requires braces not parenthesis.

README.md: fix dead FAQ link due to syntax error

---

.github/ISSUE_TEMPLATE
video/out/hwdec/hwdec_vaapi.c

See first commit message. I got an email from someone who ran into this trying to build the AUR package. They had `plain-gl` and `vaapi-vulkan` but no `vaapi-egl`. On a system that normally would build with vaapi-egl, the build failure can be reproduced with `./waf configure --disable-vaapi-x-egl --disable-vaapi-wayland --disable-vaapi-drm`.
Second commit is hopefully self-explanatory too. Just tacked it on after realizing `build/config.log` usually ends up being asked for when debugging build failures.
(Wasn't sure if build: was the appropriate prefix for the commit message. It doesn't touch any build-specific files, but it feels like an exclusively build-related change to me.)

Fix VAAPI build failure

---

DOCS/man/options.rst
video/out/wayland_common.c

Just hacking around with scale values on sway seems to work. I can double check later on my actual HiDPI display to make sure nothing weird happens.

wayland: use hidpi-window-scale option

---

video/out/hwdec/hwdec_cuda.c
video/out/hwdec/hwdec_cuda_vk.c

We should only be printing errors that occur when not probing, to
avoid creating the impression that something is wrong - and errors
during probing isn't a problem.

vo_gpu: hwdec_cuda: Reduce message level of errors while probing

---

player/javascript.c

js: don't pre-filter log level argument in mp.enable_messages()

---

audio/out/ao.c
audio/out/ao_audiotrack.c
audio/out/internal.h
misc/jni.c
misc/jni.h
wscript_build.py

This is an alternative to ao_opensles on Android. It uses the push-based API instead of pull-based, but is functionally identical (and uses the same backend on the Android OS anyway).
The only advantage to this (steaming) pile of JNI is support for `AudioFormat.ENCODING_IEC61937` on (some) Android devices running API 24+. On these platforms, you can use (for example) `--audio-spdif=ac3` to passthrough audio over HDMI (use `AudioManager.ACTION_HDMI_AUDIO_PLUG` event's `EXTRA_ENCODINGS` array to detect if the device is capable of `ENCODING_IEC6193`).
AudioFormat also supports `ENCODING_AC3` etc on API 21+, but that is not implemented on this PR as it requires raw audio data (without spdif wrapping), and libmpv does not currently make it easy to receive raw audio from an AO.
Based heavily on …

ao_audiotrack: JNI wrapper for Android's AudioTrack Java API

---

DOCS/interface-changes.rst
DOCS/man/options.rst
options/options.c
options/options.h
osdep/io.h
player/configfiles.c

I often watch sporting events. On many occasions I get files with the
same filename for each session. For example, for F1 I might have the
following directory structure:
F1/
FP1.mkv
FP2.mkv
FP3.mkv
Qualification.mkv
Race.mkv
Since usually one simply watches one race after the other, I usually
just rsync the new event's files over the old ones, so, for example,
Race.mkv will be replaced from the file for the last event with the file
from the new event.
One problem with this is that I like to use --resume-playback for other
kinds of media, so I have it on by default. That works great for, say, a
movie, but doesn't work so well with this scheme, because you can
trivially forget to pass --no-resume-playback on the command line and
end up 2 hours in, watching spoilers as the race results …

player: Optionally validate st_mtime when restoring playback state

---

demux/demux_lavf.c

Useful to understand underlying errors, for example:
>[lavf] error reading packet: Out of memory.

demux_lavf: log packet read errors

---

DOCS/man/osc.rst
player/command.c
player/lua/osc.lua
video/out/vo.h
video/out/wayland_common.c
video/out/wayland_common.h

I had previously mused about the possibility of doing CSDs on the cheap using OSC, so I dicided to just give it a go. It's a bit weird but it definitely works:
Along the way, I also fixed a wayland maximize bug and added support for triggering resize operations with a mouse.
This isn't exactly an RFC but it's also not fully complete. There's some control layout configs you'd probably want to add,and you might want to argue for implementing window control commands for other VOs (x11, win32, etc) although I think these controls have little to no value outside of Wayland.

Wayland Pseudo-Client Side Decorations via OSC

---

DOCS/man/input.rst
video/out/x11_common.c

This allows the pseudo client side decorations to be used under x11,
which might be desirable when running in border=no mode.

x11: implement minimize and maximize related VOCTRLs

---

player/lua/defaults.lua

Commit 311cc5b6 added the ability use flags while omitting name, but
broke the case where both name and flags are omitted.
Now omitting either name or flags or both works as documented.

lua: unbreak mp.add_key_binding(key, fn)

---

player/javascript/defaults.js

This is in addition to the allowed omission of name and/or flags (as
documented).

js: mp.add_key_binding: allow false-y name (match 311cc5b)

---

player/command.c
video/out/vo.h
video/out/wayland_common.c
video/out/wayland_common.h

I wanted to get this done quickly as I introduced the new VOCTRL
behaviour for minimize and maximize and it was immediately made
legacy, so best to purge it before anyone gets confused.
I did not sort out fullscreen as that's more involved and not something
I've educated myself about yet. But I did replace the VOCTRL_FULLSCREEN
usage with the new option change mechanism as that seemed simple
enough.

wayland: update Maximize and Minimize handling to use new options

---

video/out/wayland_common.c
video/out/wayland_common.h

The remaining legacy VOCTRLs are for the fullscreen and border
properties. For fullscreen this largely just replacing the private
state field with the vo option but there are small semantic
differences that we need to be careful of.
For the border setting, it's trivial as we don't have external
mechanisms for changing the state, but I also can't test it as
I'm not using a compositor that supports it.

wayland: update remaining legacy VOCTRL usage to options

---

filters/f_lavfi.c

Without this, adding filters with the prefix would fail, and some filters that have conflicting names with mpv ones were unusable.

f_lavfi: mp_lavfi_is_usable: check for "lavfi-" prefix

---

video/out/drm_common.c
video/out/drm_common.h
video/out/opengl/context_drm_egl.c
video/out/vo_drm.c

Seems like some drivers only increment msc every other page flip when
running in interlaced mode (I'm looking at you nouveau). I.e. it seems
to be incremented at the frame rate, rather than the field rate.
Obviously we can't work with this, so shame the driver and bail.
On intel this isn't an issue, as msc is incremented at field rate
there.
This means presentation feedback won't work correctly in interlaced
modes with those drivers, but who in their right mind uses an
interlaced mode these days, anyway?

drm: avoid division by 0 in drm_pflip_cb with bad drivers

---

video/out/drm_common.c
video/out/drm_common.h
video/out/opengl/context_drm_egl.c
video/out/vo_drm.c

drmModeAddFB is legacy, and might not pick the pixel format you
expect, depending on your driver. Use drmModeAddFB2 which specifies
this explicitly using a fourcc.
(this PR is based on top of #7230 and should be merged after that)

 vo_drm: replace drmModeAddFB usage with drmModeAddFB2

---

video/out/wayland_common.c

The wayland backend needs to keep track of whether or not a window is
hidden for presentation time. There is no presentation feedback when a
window is hidden which means we shouldn't be sending information to the
vo_sync_info structure (i.e. just leave it all at -1). This seemed to
work fine, but recent changes to presentation time in one notable
compositor (Sway; it was probably always broken in Weston actually)
changed the presentation time behavior.
For reasons that aren't clear, there is a greater than 16.666ms delay
between the first presentation time event and the second presentation
time event (compositor latency?) when you switch back to an mpv window
after it is hidden for long enough (a few seconds). When using
presentation time, this causes mpv to feed in some bad values in its …

wayland: adjust hidden state detection

---

video/out/cocoa/window.m
video/out/cocoa_common.m

See commit 4e4252f9169edc and the following as an example how this would
have to be done if done properly.
Since I'm unable to test on OSX, and nobody is interested in fixing this
code (including myself, actually), just remove the deprecated
definitions to make sure the code still builds. This will break runtime
switching of fullscreen, ontop, border. (The way the minimized state is
reported was also deprecated, but commit 40c2f2eeb05 already broke it
anyway.)
---
CC @pigoz @Akemi 
I think it's OK to break it this way, since users should use the swift backend anyway. Maybe it should be disabled by default too, if it isn't already.
Making the PR mainly for the CI.

cocoa_common: remove deprecated VOCTRLs/VO_EVENTs

---

video/out/w32_common.c

* Instead of following VOCTRL_FULLSCREEN, check for option changes.
* Instead of signaling VO_EVENT_FULLSCREEN_STATE, update the cached
option structure and have it propagated to the origin.
Additionally, gets rid of all the straight usage of the VO options
structure.
Done in a similar style to the Wayland common file, where in case
of reading the value, the "payload" from cache is utilized.

video/w32_common: switch full screening to options cache

---

DOCS/interface-changes.rst
DOCS/man/options.rst
video/out/x11_common.c

Apparently there are two different options for controlling which screen an mpv window goes onto: --fs-screen and --screen. The former explicitly only controls which screen a fullscreened window goes onto, but does not appear to actually care about this option at runtime for X11, so pressing f will always fullscreen to the screen mpv is currently on. This means the option is of questionable usefulness for starters.
Making it worse, if you use --screen=1 --fs, mpv will actually fullscreen on screen 0, because --fs-screen isn't set. Instead of doing that, fall back to whatever --screen is set to.
Is `--fs-screen` really intended not to affect what happens at runtime at all? Because that's the current behaviour, I think, which seems counter-intuitive and possibly broken.

video/out/x11: add fs-screen fallback

---

DOCS/man/osc.rst
player/lua/osc.lua

A minority of users have expressed a dislike of hats, calling them "cancer [that] don't belong in software" describing the people who add them as "shitty circlejerks" and "chucklefuck."
While I personally disagree with those opinions, it's probably easier to let them have it their way. For that reason this adds the option `greenandgrumpy` to the osc, which allows users to disable the hat.

osc: add option to disable santa hat

---

stream/stream_dvb.c

This silences the warnings (and fixes the typo in the comment
which marked the fallthrough as explicit before).
@wm4: I'm opening this minimalistic change as a PR since I am not sure if we want this attribute markup in the code. If you prefer the comment markup (leaving the warnings in), feel free to close. 
Redesigning the code to avoid the fallthroughs would mean reworking the logic, which I'd love to avoid - actually, I think we have one of the extra-rare cases here where explicit fallthroughs in some branches of the case statement are helpful to improve readability.

stream_dvb: Remove implicit fallthroughs

---

video/out/gpu/hwdec.h
video/out/gpu/video.c
video/out/opengl/hwdec_vdpau.c

As we are less and less interested in vpdpau, with nvdec and vaapi
being better choices in general on nvidia and AMD respectively, we
might consider removing direct_mode, where we bypass the vdpau
mixer and work directly with yuv textures. Normally, working with
yuv textures would be great, but vdpau built in an assumption that
all frames are delivered as separate fields, causing us to have
to re-interleave them.
nvidia then introduces a new OpenGL extension that can return the
yuv frames as frames, but we can't just unconditionally switch to
that as we'd want to keep supporting older hardware where the drivers
are no longer getting new features. The end result is that we
wouldn't be able to get rid of the old code paths.
Removing direct_mode means we always use the mixer, and work with …

[RFC] vo_gpu: hwdec_vdpau: Remove direct_mode

---

video/out/hwdec/hwdec_vaapi.c
video/out/hwdec/hwdec_vaapi.h
video/out/hwdec/hwdec_vaapi_gl.c
video/vaapi.c
wscript

In vaapi 1.1.0 (which confusingly is libva release 2.1.0), they
introduced a new surface export API that is more efficient, and
we've been supporting that and the old API ever since (Feb 2018).
If we drop support for the old API, we can do some fairly nice cleanup
of the code.
Note that the pkgconfig entries are explicitly versioned by the API
version and not the library version. I confirmed the upstream pkgconfig
files.

vo_gpu: hwdec_vaegl: Remove support for old-style interop

---

DOCS/man/options.rst
video/cuda.c
video/hwdec.c
video/hwdec.h
video/out/gpu/hwdec.c
wscript
wscript_build.py

In the distant past, the cuviddec backed copy hwaccel could be
configured directly using lavc options. However, since that time,
we gained support for automatic hw ctx creation which ended up
bypassing the lavc options.
Rather than trying to find a way to pass those options again, a
better idea is to make the 'cuda-decode-device' option, used by
the interop hwaccels, work for the copy hwaccels too.
And that's pretty simple: we have to add a create function that
checks the option and passes it on to ffmpeg.
Note that this does require a slight re-jig to the configuration
flags, as we now have a scenario where we want to build with support
for the cuda copy hwaccels but not the interop ones. So we need
a distinct configuration flag for that combination.
Fixes #7295.

video: cuda: add explicit context creation for copy hwaccels

---

player/configfiles.c

In final fixups for #7139 it seems I managed to screw up utime error
checks. Everything still works, but we MP_WARN when we don't need to.

configfiles: Fix utime retcode check

---

video/out/gpu/context.c
video/out/wayland_common.c

Here's a compromise for the little wayland controversy earlier. The TL;DR is that gnome=bad, but everyone else works. I don't think it's fair to force sway users (that includes me) or anyone else to default to xwayland when the wayland backend works just fine on it.
Basically the just does two things: skip wayland on the autoprobe if GNOME is being used (i.e. use xwayland) and also explicitly print warnings that GNOME wayland is bad so hopefully users will be more encouraged to bug them and not us. It's also worth noting that xwayland is still  bad on GNOME, but there's less cosmetic issues so I figured it was worthwhile to do that.
I actually wasn't able to test explicitly setting `--gpu-context=wayland/waylandvk` on GNOME because it gave me mysterious display errors that I didn't care …

Only punish GNOME wayland users

---

player/lua/osc.lua

Currently, the activation and deactivation of input handling is done
inside the render() loop, but this does not run when the osc mode is
`never` - which does make sense.
That means that if you are cycling the visibility mode, the input
state will be whatever it was at the time of the mode change. And,
as our modes are ordered `auto` -> `always` -> `never`, the input
state will be enabled when you cycle to `never`.
There are various ways you can imagine fixing this, and in this
change I propose we reset the input state to disabled on a mode
change, and then let render() re-enable input if that's appropriate.
Fixes #7298.

osc: reset input handling state on a change in visibility mode

---

video/out/wayland_common.c

More than one option may change at the same time so don't break out of
this loop.

wayland: don't exit the option loop

---

DOCS/encoding.rst
DOCS/man/encode.rst

4a2f268f67b1505630724b6f8df960fce25770f0 changed the `-add` usage to `-append` in the encoding_profiles.conf so that may be better for this encoding.rst change.
https://github.com/mpv-player/mpv/blob/9eb399193eda34612a016f0310cb4b2aebaabaa1/DOCS/man/mpv.rst L502, 527, 546 still have `-add          Append 1 or more filters (same syntax as -set)` which is technically correct, but doesn't mention that this is a deprecated feature. Not sure how/if I should've updated these.

DOCS: update *-add usage to reflect multiple items being deprecated

---

.github/ISSUE_TEMPLATE/1_dont_ignore.md
.github/ISSUE_TEMPLATE/2_bug_report_linux.md
.github/ISSUE_TEMPLATE/2_bug_report_macos.md
.github/ISSUE_TEMPLATE/2_bug_report_windows.md
.github/ISSUE_TEMPLATE/3_bug_report.md
.github/ISSUE_TEMPLATE/4_bug_report_build.md
.github/ISSUE_TEMPLATE/5_feature_request.md
.github/ISSUE_TEMPLATE/6_question.md
.github/ISSUE_TEMPLATE/config.yml

i split up the issue template for our 3 major platforms, build problems, feature requests and questions. those templates are automatically labelled with the respective applicable labels.  otherwise there is one 'blank' issue template that doesn't fall in any category and a prominent `do not ignore the issue template` message.
furthermore the linux template needs some more adjustments, since i am not sure for what info we should ask for (marked with the question mark in the template for now).
live demo can be seen here https://github.com/Akemi/mpv/issues/new/choose
sadly one can't create direct contact_links for the irc channels. apparently the url can't start with irc://

github: add several issue templates and a warning to not ignore them

---

video/out/cocoa_cb_common.swift

this makes the behaviour more similar to the old cocoa backend.
one corner case that can't be completely fixed is, when minimized and a file without a video track is played (window is removed) and the next file has a video track again. when the next file is played the window is made active again again and deminimized. there is no way to add a window again without making it active/deminimize. this can be worked around with --force-window.

cocoa-cb: don't make window active when minimized on file change

---

video/out/wayland_common.c

Allow the --window-maximized and --window-minimized flags to actually
work when the player is started on wayland. If the compositor doesn't
support maximization or minimization, then these options just do
nothing.

wayland: support maximize/minimize on startup

---

player/lua/osc.lua

It's a bit unintuitive today when you use the un-maximise control
while fullscreened. Depending on the VO in use, this might silently
change the maximise state without any visible effect, or it might
do nothing. It's less surprising if the control exits the fullscreen
state.
Note that the exact behaviour is still VO dependent. If the window
was maximised before being fullscreened, it might exit fullscreen
back to maximised or back to regular window mode.
I thought about trying to explicitly control that behaviour but
it makes the osc code weird and probably wouldn't work all the time.

osc: when fullscreened, un-maximise window control should un-fullscreen

---

player/lua/osc.lua

There are two improvements here:
1) Correct the right-side padding on the title box. This was messed
up previously because I was passing the title box width when I
should be passing the x coordinate. I've also increased the
spacing to separate the title from the window controls more
clearly.
2) I'ved added a mouse tracking area over the title bar so that the
osc doesn't disappear if you hover over the title box. This didn't
work previously because the input area only covers the actual
window controls. The implementation here is simplified in that
it's only a mouse area and not an input area. This is enough to
keep the osc visible, but it won't stop the mouse pointer
disappearing. Fixing that requires a full input area which, for
now, I will say isn't worth the effort.

osc: usability improvements for pseudo-csd title bar

---

etc/input.conf
input/keycodes.c
input/keycodes.h
osdep/macos/remote_command_center.swift
osdep/macosx_application.m

this changes some input commands and might break some other use cases. imo PLAY and PAUSE should explicitly set the proper pause state and only PLAYPAUSE should cycle the pause state.
i am not sure if there is a reason for this. the MP_KEY_* events are used in following files, so we need a bit of input of the related persons, @wm4 @philipl @sfan5 @rossy @Dudemanguy 
sry if i forgot someone.
osdep/w32_keyboard.c
video/out/vo_caca.c
video/out/wayland_common.c
video/out/vo_sdl.c
video/out/x11_common.c

input: don't cycle pause property, mac: report playback state

---

player/configfiles.c

I noticed an oversight when using ytdl-hook -- if the path is a URL, we
try to `stat()` it, which obviously doesn't work. To mitigate that,
don't check or update mtimes for URLs.

player: check if file is URL before attempting to get mtime

---

DOCS/man/options.rst
video/out/opengl/context_wayland.c
video/out/vulkan/context_wayland.c
video/out/wayland_common.c
video/out/wayland_common.h

This originally existed as a hack for weston. In certain scenarios, a
frame taking too long to render would cause vo_wayland_wait_frame to
timeout which would result in a ton of dropped frames. The naive
solution was to just to add a slight delay to the time value. If a
frame took too long, it would likely to fall under the timeout value and
all was well. This was exposed to the user since the default delay
(1000) was completely arbitrary.
However with presentation time, this doesn't appear to be neccesary.
Fresh frames that take longer than the display's refresh rate (16.666 ms
in most cases) behave well in Weston. In the other two main compositors
without presentation time (GNOME and Plasma), they also do not
experience any ill effects. It's better not to overcomplicate things, so
this …

wayland: remove wayland-frame-wait-offset option

---

audio/out/ao_wasapi_utils.c

MPV audio sessions on Windows had an invalid audio session icon path, forcing mixer applications (e.g. sndvol, [EarTrumpet](https://github.com/File-New-Project/EarTrumpet/commit/880fa07a98ab482e9295d995cf95c2d20109b8fd)) to fallback to other methods of finding a usable icon. (It was neither a valid path or a properly formed [indirect string](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-privateextracticonsw).) `init_session_display` will now set a valid audio session icon path.

ao_wasapi_utils: remove invalid audio session icon path (fixes #7269)

---

player/lua.c

It appears Lua's package paths try to load .lua files from the current
working directory. Not only that, but also shared libraries.
WHAT THE FUCK IS HWOEVER IS RESPONSIBLE FOR THIS FUCKING DOING?
mpv isn't setting this package path; currently it's only extending it.
In any sane world, this wouldn't be a default. Most programs use
essentially random working directories and don't change it.
I cannot comprehend what bullshit about "convenience" or whatever made
them do something this broken and dangerous. Thousands of programs using
Lua out there will try to randomly load random code from random
directories.
In mpv's case, this is so security relevant, because mpv is normally
used from the command line, and you will most likely actually change
into your media directory or whatever with the …

lua: fix highly security relevant arbitrary code execution bug

---

video/out/wayland_common.c
video/out/wayland_common.h

There were a couple of erroneous things in the handle_toplevel_config
function. Firstly, looping through the different states was not handled
correctly. Launching a window as maximized (can happen in sway for
example) was always stuck on true and would never be set to false. Fix
this by always checking if XDG_TOPLEVEL_STATE_MAXIMIZED is found or not.
Also do a similar thing for the fullscreen state.
Additionally, there were some issues with resizing windows and
window-scale going back to old sizes. The root of this problem is that
the width and height arguments of handle_toplevel_config aren't actually
guarenteed to be the actual width and height of the surface. There are
times when mpv will set the surface size on its own (like with
window-scale) which will be unknown to the toplevel …

wayland: some toplevel config fixes

---

video/out/wayland_common.c

Wayland uses vo_wayland_wait_frame plus some polling with a timeout for
blocking on vsync. Here are a couple of changes that seem to be
improvements. First, the poll time is always rounded up instead of
truncated. When rendering frames longer than the standard 16.666 ms
timeout, it seems that truncating the poll time slightly early may cause
some vsync jitter spikes. Waiting longer, even if it's too long, appears
to behave better.
The second change is to use wl_display_roundtrip instead of
wl_display_dispatch_pending. wl_display_dispatch_pending dispatches all
events immediately. This is good to avoid blocking, but it's not
guaranteed to wait long enough for all events to be processed on the
display fd. The preceding wl_display_read_events routine ensures that
all events on the display fd …

wayland: adjust vo_wayland_wait_frame logic

---

sub/sd_ass.c

The change, in an earlier commit, in format for ass to handle results
in a different number of fields to skip. Correct that so SDH filtering
works.
Should fix issue #7188

sub: fix SDH filtering after change

---

sub/filter_sdh.c

It is not uncommon with a speaker label with [xxxx] inside.
They should also be filtered out.

sub: enhance SDH filtering

---

video/out/wayland_common.c
video/out/wayland_common.h

Resizing the window while preserving the aspect ratio actually kind of
sucked. The window size could make big dramatic changes which was pretty
unintuitive with respect to where the mouse was actually located.
Instead, let's just do some math to ensure that the window size is
always contained inside the width/height reported by
handle_toplevel_config while preserving the aspect ratio.

wayland: make resizing better

---

TOOLS/lua/autoload.lua

The example configuration uses values of true/false for the script
options. As per DOCS/man/lua.rst boolean values should be represented
with yes/no and using true/false will result in an error.
This updates the comments and changes the true/false values under the
example configuration to yes/no.

TOOLS/lua/autoload.lua: update script comments

---

DOCS/man/mpv.rst

Happened upon this when trying to customize my status line.

manpage: deprecated option in example config

---

osdep/macos/remote_command_center.swift
osdep/macosx_application.m
osdep/macosx_application_objc.h
osdep/macosx_events.m
osdep/macosx_events_objc.h
video/out/cocoa-cb/events_view.swift
video/out/cocoa-cb/window.swift
video/out/cocoa_cb_common.swift
video/out/cocoa_common.m

this is kinda a mess. media key support was only available when our own app/runloop was started and not an external one is used (libmpv). this moves the media key support to the mac events which are always available.
this is still a bit messy and i would like to rewrite the whole thing. as of now, touchbar and cocoa-cb support are not available via libmpv because of aforementioned reason. i want to cleanly separate mpv independent features from the mpv dependent parts, eg at the end we will only have a very rather small NSApplication and a separate component that handles and manages features like media keys, touchbar, etc. hopefully this will also prevent some more breakages in the future.
fixes https://github.com/mpv-player/mpv-examples/issues/29

mac: fix media key support for libmpv users

---

DOCS/man/options.rst
demux/demux_lavf.c

Add 'udp_multicast' to rtsp-transport options and add the rtsp allowed-media-types options.
See https://www.ffmpeg.org/ffmpeg-protocols.html#toc-rtsp for more information.

Add 'udp_multicast' to rtsp-transport options

---

video/out/drm_prime.c
video/out/drm_prime.h
video/out/opengl/hwdec_drmprime_drm.c

This commit fixes a bug where handle for a framebuffer gets double freed.
It seems to happen that the same prime fd gets two framebuffers. As the prime fd is the same the resulting prime handle is also the same.
This means one handle but 2 framebuffers and is leading to the following chain:
1. The first framebuffer gets deleted the handle gets also freed via the ioctl.
2. In startup phase not all 4 dumb buffers for overlay drawing are set up it can happen that the last dumb buffer gets the handle we freed above as they will be allocated on request by GBM.
3. The second framebuffer gets freed the handle will be freed again resulting that the 4's dumb buffer handle is not backed by a buffer.
4. Drm prime continues to assign handles to its prime fds an will lead to have this handle which was …

Fix drm prime

---

video/out/cocoa_cb_common.swift

macOS doesn't like setting both at the same time so the minimized state takes precedence.

cocoa-cb: support maximize/minimize on startup

---

audio/out/ao_wasapi_utils.c

In shared mode, we previously tried to feed the full native format to
IsFormatSupported in the hopes that the "closest match" returned was
actually that.
Turns out, IsFormatSupported will always return the mix format if we
don't use the mix format's sample rate. This will also clobber our
choice of channel map with the mix format channel map even if our
desired channel map is supported due to surround emulation.
The solution is to not bother trying to use anything other than the mix
format sample rate. While we're at it, we might as well use the mix
format PCM sample format (always float32) since this conversion will
happen anyway and may avoid unecessary dithering to intermediate
integer formats if we are already resampling or channel mixing.
The other commit just makes mp_format_res_str …

ao_wasapi: try mix format except for chmap 

---

video/out/wayland_common.c

Based on an idea by sfan5. Remove abs usage, and instead just
check for negative value, and set variable to either +/-1.

wayland: simplify mouse wheel direction calculation

---

.travis.yml

sudo key was deprecated in 2018 https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
otherwise see the warning here https://travis-ci.org/github/mpv-player/mpv/builds/665646319/config?utm_medium=notification&utm_source=github_status#rccb_mpv:.travis.yml@7768452f2d9e1f22.46
also activate the notifications again, since build have been fixed.

travis: fix config validation warnings

---

wscript

Previously, EGL as provided by a pkg-config was checked for independently in several places. The effect this had is that `--disable-egl` would not actually disable EGL from the build, as this only affected the "egl" option relied upon by egl-x11. wayland-gl and egl-drm did their own EGL checks.
By making wayland-gl and drm-egl depend on egl instead, we fix this behaviour and can simplify egl-helpers a bit, as we can now simply check whether egl or one of the other features providing some non-pc egl is enabled, instead of checking every single thing that might be pulling in egl.
Future work could make the "egl" option just be a catchall for any EGL implementation, so that brcmegl and angle and Android can piggyback on the egl option as well.

build: only check for EGL pc in one build option

---

stream/stream_dvb.c

The call was hidden very well, via
dvb_streaming_read -> dvb_update_config
-> dvb_streaming_start -> dvb_set_channel,
and broke the stream buffering logic.
Dropping that call does not noticeably slow down channel switches.
Fixes #7602 .

stream_dvb: Remove call to stream_drop_buffers in fill_buffer.

---

DOCS/man/options.rst
video/out/d3d11/context.c

Picked up from @rossy's box o' nifty features.
Lets the application fully control the rendering onto the screen
instead of the compositor.
Test build [here](https://kuroko.fushizen.eu/mpv_binaries/2018-11-19T22-13-mpv-git-f7d921d892-exclusive_fs.7z).

vo_gpu: d3d11: add support for exclusive fullscreen

---

osdep/terminal-unix.c

zsh often sets DECCKM (i.e. Cursor Key Mode) meaning the arrow keys
send `SS3 A/B/C/D` instead of `CSI A/B/C/D`.
Add `key_entry` definitions for this alongside the existing DECCKM Reset
definitions.

terminal-unix: add key_entry defs for DECCKM mode

---

player/lua/stats.lua

Before (no editions): https://0x0.st/iQW_.png
After (no editions): https://0x0.st/iQW2.png
Before (editions): https://0x0.st/iQW9.png
After (editions): https://0x0.st/iQWL.png
cc @Argon- 
Second commit could be dropped if it's controversial.

Add edition information to stats.lua

---

video/out/opengl/context_wayland.c
video/out/vulkan/context_wayland.c
video/out/wayland_common.c
video/out/wayland_common.h

One not-so-nice hack in the wayland code is the assumption of when a
window is hidden (out of view from the compositor) and an arbitrary
delay for enabling/disabling the usage of presentation time. Since you
do not receive any presentation feedback when a window is hidden on
wayland (a feature or misfeature depending on who you ask), the ust is
updated based on the refresh_nsec statistic gathered from the previous
feedback event.
The flaw with this is that refresh_nsec basically just reports back the
display's refresh rate (1 / refresh_rate * 10^9). It doesn't tell you
how long the vsync interval really was. So as a video is left playing
out of view, the wl->last_queue_display_time becomes increasingly
inaccurate. This led to a vsync spike when bringing the mpv window back
into sight …

wayland: use mp_time deltas for presentation time

---

demux/demux_libarchive.c
stream/stream_libarchive.c
stream/stream_libarchive.h

The motivation here is the last commit which fixes broken seeking on multi-volume old-style rar archives. The other two commits are just small atomic fixes along the way.

stream_libarchive fixes

---

player/playloop.c

This brings the displayed percentage closer to the exact number and
allows mpv to more frequently display 100% when it finishes playing a
typical video or audio file.

player: round position percentage to the nearest integer

---

DOCS/man/lua.rst

I noticed this while reading the documentation.

documentation: fix some ReST syntax mistakes in lua.rst

---

video/out/drm_prime.c

Fallback to drmModeAddFB2 if drmModeAddFB2WithModifiers fails. I've
observed it failing on a pinebook pro running manjaro. We also got "0"
as modifiers from FFmpeg anyway, which might or might not have
something to do with this.
Instead of trying to find the source of the problem (which could be anything, including the non-mainline ffmpeg I have to use to make it work at all not being quite complete), just add this
fallback.
Also I decided to get format_modifiers for all planes from FFmpeg because that looks to me like it makes a lot more sense. However I am unable to test this, as my testing platform (pinebook pro) works fine with just basic drmModeAddFB2, and drmModeAddFB2WithModifiers doesn't seem to want to work at all.

drm_prime: fallback to drmModeAddFB2 if drmModeAddFB2WithModifiers fails

---

video/out/opengl/context_drm_egl.c

extension is not mandatory and is not provided on ie Raspberry Pi

drm: add typedef for PFNEGLGETPLATFORMDISPLAYEXTPROC (#7314)

---

waftools/checks/custom.py
waftools/checks/generic.py
wscript

when building with rpi EGL is provided by librcmegl library and libEGL
should not be linked then

build: link against single EGL provider

---

etc/_mpv.zsh

The generate_xxx() helpers, once defined, would appear as
user-visible functions; this would lead to unexpected and
confusing completion suggestions for gene<tab> after having
once run mpv in that shell.
This PR adds the prefix '_mpv_' to all completion functions
as a convention to make them less user-visible and less likely
to collide with other packages.

zsh completion: helper functions in private namespace

---

video/out/vo_drm.c
video/out/vo_wlshm.c

The image w and h members must match params.w and params.h, so
should not be changed directly. The helper function mp_image_set_size
is designed for this purpose, so just use that instead.
This prevents an assertion error with the rewritten draw_bmp.
Fixes #7721.

vo_wlshm, vo_drm: set image size with mp_image_set_size

---

wscript

FreeBSD 13.0 [added](https://github.com/freebsd/freebsd/commit/575e351fdd996f72921b87e71c2c26466e887ed2) `memfd_create`. Let's relax configure check in case DragonFly follows suit.
<details><summary>Example output</summary>
```
$ mpv --no-config --msg-level=vo=v --vo=wlshm http://www.jell.yfish.us/media/jellyfish-3-mbps-hd-h264.mkv
(+) Video --vid=1 (*) (h264 1920x1080 29.970fps)
[vo/wlshm/wayland] Registered for protocol wl_shm
[vo/wlshm/wayland] Registered for protocol wl_compositor
[vo/wlshm/wayland] Registered for protocol wl_data_device_manager
[vo/wlshm/wayland] Registered for protocol zwp_idle_inhibit_manager_v1
[vo/wlshm/wayland] Registered for protocol xdg_wm_base
[vo/wlshm/wayland] Registered for protocol zxdg_decoration_manager_v1
[vo/wlshm/wayland] Registered for protocol …
```

wlshm: re-enable on FreeBSD

---

player/command.c

Execution of "stop" command in the case when idle mode was not enabled
resulted in player termination scenario not honoring user setting
"save-position-on-quit" from config file. This patch addresses the
issue by checking for "save-position-on-quit" in cmd_stop and saving
state when idle mode is not enabled.

command: save state on stop when user requested save-position-on-quit

---

video/out/x11_common.c

When the window is mapped, ICCCM WM_HINTS (specifically the input and
state fields) are set. To quote the spec, "The input field is used to
communicate to the window manager the input focus model used by the
client" and "[c]lients with the Passive and Locally Active models should
set the input flag to True". mpv falls under the Passive Input model,
so the input flag is set to true. The state hint is set to NormalState.

x11_common: added ICCCM WM_HINTS

---

osdep/subprocess-posix.c

Bionic doesn't implement confstr() at all. ~~So pretend
it's nonfunctional for the fallback code that uses it.~~

osdep: remove confstr() fallback for subprocess spawning

---

audio/out/ao_pulse.c

Previously, device_buffer defaulted to 0. This meant that commit baa7b5c would always wait with a timeout of 0, leading to high CPU usage for PulseAudio users.
By setting device_buffer to the number of samples per channel that PulseAudio sets as its target, this commit fixes this behaviour.

ao/pulse: properly set device_buffer

---

DOCS/man/options.rst
video/csputils.c
video/csputils.h
video/out/gpu/video.c
video/out/gpu/video.h
video/out/gpu/video_shaders.c

1. Reinterpret SDR white as 203 cd/m² instead of 100 cd/m²
2. Implement BT.2390 EETF tone-mapping
While testing this I noticed that for some reason, the HDR peak detection seems broken on vulkan on my end. Not gonna merge this until I figure out why and if that's somehow a bug that only occurs in combination with this patch (for whatever reason?)

HDR changes

---

audio/out/buffer.c

The pull mode APIs don't require locking calls to read the buffer or send
ao_controls. Locks were added in b83bdd1, which introduced deadlocks in
ao_wasapi.
This also allows cleanup of some of the special cases required to avoid
other deadlocks by holding unnecessary locks for pull mode.

audio: only lock ao buffer for push mode APIs

---

video/out/gpu/shader_cache.c

This fixes #6418 and #7846, and likely also fixes https://github.com/mpv-android/mpv-android/issues/196 and https://github.com/mpv-android/mpv-android/issues/276.
It seems using mediump float in the shader causes issues on iOS with kernel resampling, PQ HDR, and maybe more.
Apple suggests [here](https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/BestPracticesforShaders/BestPracticesforShaders.html#//apple_ref/doc/uid/TP40008793-CH7-SW7)  “when in doubt, default to high precision”, so this changes GLES to use highp when it’s available (if GL_FRAGMENT_PRECISION_HIGH is defined). And it fixes all the problems I've seen.
Those mpv-android issues match the defects on iOS, so there’s a good chance this will help there as well, though I'm not …

vo_gpu: use highp float if available for GLES

---

.travis.yml
ci/build-mingw64.sh

Instead of a prebuilt docker container, pull deps ourselves and build them.
This leverages travis caching to not build ffmpeg + the rest every time.
No rebuilds will happen unless caches are manually deleted [here](https://travis-ci.org/github/mpv-player/mpv/caches). This could be changed to rebuild if library versions are bumped in the CI script if desired.
Usual buildtime (with cache) is ~3 minutes. Uncached builds take ~15 minutes.

ci: replace mingw build scripts

---

video/out/hwdec/hwdec_vaapi_vk.c

Requires two changes, notably the inclusion of DRM format modifiers. (Needs recent libplacebo)
Fixes #7666

Add support for vaapi hwdec on vulkan/RADV

---

sub/osd_libass.c

libass recently [switched](https://github.com/libass/libass/pull/390) the default from 1 to 0 for compatibility with ASS scripts that rely on the historical/VSFilter default of 0.
libass does attempt to detect and avoid breaking scripts that rely on the historic libass-only default of 1, but it doesn’t cover tracks created directly through the API, so set the header explicitly.
Ideally this PR should’ve been submitted before the change landed in libass, but we forgot to check mpv’s OSD. Sorry.
Fixes #7900.

osd_libass: set ScaledBorderAndShadow

---

player/external_files.c

Unsure why this was never added, making this simple PR since it probably was an oversight.

external_files: add .pgs subtitle extension

---

DOCS/man/ao.rst

```
$ mpv --ao=sdl --sdl-bufcnt=1234 --msg-level=ao=v /path/to/foo.mp3
Error parsing option sdl-bufcnt (option not found)
Setting commandline option --sdl-bufcnt=1234 failed.
Exiting... (Fatal error)
$ mpv --list-options | fgrep sdl-
--sdl-buflen                     Float (default: 0.000)
--sdl-sw                         Flag (default: no)
--sdl-switch-mode                Flag (default: no)
--sdl-vsync                      Flag (default: yes)
```

man/ao/sdl: drop no longer supported --sdl-bufcnt

---

DOCS/man/af.rst
audio/filter/af_scaletempo2.c
audio/filter/af_scaletempo2_internals.c
audio/filter/af_scaletempo2_internals.h
filters/user_filters.c
filters/user_filters.h
wscript_build.py

I ported the [audio renderer algorithm](https://chromium.googlesource.com/chromium/chromium/+/51ed77e3f37a9a9b80d6d0a8259e84a8ca635259/media/filters/audio_renderer_algorithm.cc) from chromium.
I used the older version linked in #4418 because it seemed a little simpler than the most recent version.
In my opinion, chromium's algorithm sounds much better than `rubberband` and `scaletempo` (at least using the configurations I tried) and comparable to `atempo`.
The code seems to work fine, but I think it needs some more testing and refactoring.
I basically copied `af_rubberband.c` and `audio_renderer_algorithm.cc` from chromium including its dependencies into one file and hacked on it until it somehow worked. But I honestly don't really understand the code fully.
I have some questions:
- What …

[RFC] add audio renderer from chromium for better scaletempo

---

audio/filter/af_scaletempo2.c

The `--speed` parameter did not work with `mpv --no-config whatever.mp3 --video=no --speed=2 --af=scaletempo2` as pointed out in https://github.com/mpv-player/mpv/pull/7865#issuecomment-664243401 .

af_scaletempo2: fix bug where speed was not set

---

.travis.yml

the commits have some more explanation why i did some things. build on macOS 10.12 is fixed again and additionally i could reduce the build time by around 50%, from ~22 mins to ~11 mins.
also updated the 10.14 image to 10.15. it's the setup i wanted from the beginning, eg the newest and oldest official supported macOS version and our oldest supported version to build on as legacy.

travis: fix macOS 10.12 build

---

player/lua/ytdl_hook.lua

Fixes a typo in ytdl_hook when errors occur, I was noticing this from time to time when playing media through youtube-dl. I didn't test this locally before posting the PR.

ytdl_hook: fix typo in unexpected error message

---

player/lua/stats.lua

When switching between files it's possible that r["aspect"] returns nil, resulting in a crash.
```
[stats] 
[stats] stack traceback:
[stats]         [C]: in function 'format'
[stats]         /home/eva/.config/mpv/scripts/stats.lua:548: in function 'add_video'
[stats]         /home/eva/.config/mpv/scripts/stats.lua:618: in function 'f'
[stats]         /home/eva/.config/mpv/scripts/stats.lua:828: in function 'print_page'
[stats]         /home/eva/.config/mpv/scripts/stats.lua:951: in function 'cb'
[stats]         mp.defaults:346: in function 'process_timers'
[stats]         mp.defaults:506: in function 'dispatch_events'
[stats]         mp.defaults:479: in function <mp.defaults:478>
[stats]         [C]: in ?
[stats]         [C]: in ?
[stats] Lua error: …
```

stats: fix crash when aspect ratio is unavailable

---

audio/out/ao_lavc.c

FFmpeg expects those fields to be set on the `AVFrame` when encoding audio, not doing so will cause the `avcodec_send_frame` call to return `EINVAL` (at least in recent builds).
Fixes #7909

ao/lavc: add channels and channel_layout to AVFrame

---

osdep/mpv.exe.manifest

See https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page
This fixes Unicode file names in Lua's built-in I/O library in Windows 10 1903 and up. For example, this script:
```lua
file = io.open("C:\\mpv\\💯.txt", "w")
file:write("test\n")
file:close(file)
```
Creates the following file before this change:
And creates this file after the change:
It might affect other dependencies as well, since I doubt they're all as strict at using wide-char APIs as we are, though Lua was the most obvious one I could think of.

Request the UTF-8 code page by setting activeCodePage in the manifest

---

libmpv/client.h

Looks like a copypaste mistake from mpv_client_name().

client API: fix misleading remark

---

sub/sd_ass.c

According to both file(1) and
https://www.iana.org/assignments/media-types/application/font-sfnt
application/font-sfnt is also a valid mime type for (at least some) .ttf
files.

sub: add application/font-sfnt to the list of font mime types

---

DOCS/man/options.rst
options/options.c
options/options.h
video/out/wayland_common.c

While I was adding `wayland-app-id` in, I noticed some silly things in `create_xdg_surface` which the first commit addresses (nothing too major). The second commit is a bit more opinionated hence the PR. It adds a new option, `--wayland-app-id` which can changed at runtime. For updating during runtime, I opted to use `m_config_cache_get_next_changed` and added the option to `vo_opts`. ~I don't think calling `m_config_cache_write_opt` is needed at any point since this property is entirely controlled by mpv and appears to already update correctly on its own, but feel free to correct me if I'm wrong.~ (That was wrong. I have to call it once initially). A couple of related observations.
1. `wayland-app-id` is pretty similar to `x11-name`. For this commit, I kept them as entirely separate …

wayland: tweak xdg_surface creation and add wayland-app-id as a user option

---

osdep/io.c
osdep/io.h
player/javascript.c
player/lua.c

lua/js utils.get_env_list() uses `environ' which was ANSI, thus
it broke any unicode names/values.
mpv already has an internal utf8_environ for win32, but it's used
only at the getenv(..) wrapper and not exposed in itself, and also it
has lazy initialization - on first getenv() call.
Now `environ' maps to a function which ensures initialization while
keeping it an l-value (like posix expects).
The cost of this fuglyness is that files should include osdep/io.h
(which now declares environ as extern) rather than declaring it
themselves, or else the build will break on mingw.

win32: scripting utils.get_env_list(): use UTF-8

---

video/out/opengl/context_wayland.c
video/out/vulkan/context_wayland.c
video/out/wayland_common.c
video/out/wayland_common.h

The motivation for this change was a segfault caused by e107342 which
has complicated reasons for occuring (i.e. I'm not 100% sure but I think
it is a really weird race). The major part of this commit is moving the
initialization of presentation listener to the frame_callback function.
Calling it in swap_buffers worked fine but in practice it meant a lot of
meaningless function calls if a window was hidden (the presentation
would just be immediately discarded). By calling it in frame_callback,
we ensure the listener is only created when it is possible to receive a
presentation event.
Of course calling the presentation listener in feedback_presented or
feedback_discarded was considered, but ultimately these events are too
slow. Receiving the ust/msc/sbc triplet here and then passing it to …

wayland: refactor presentation time

---

video/out/vo.c
video/out/wayland_common.c

We've had some serious issues with GNOME in the past, but since then
their compositor has undergone some major internal improvements. The
most severe one [1], random vsync spikes and mistimed frames, can no
longer be reproduced by the original author of the issue. There are some
minor UI-related things (lack of window decorations for instance since
there is no xdg-decoration support), but users don't seem to complain
about that too much and they aren't revelant to playback.
3.38 isn't out quite yet, but that should also fix playback issues when
on a multimonitor setup (the fix is in the master branch at the moment).
In terms of playback, the only real concerning issue is the lack of idle
inhibit so a warning is still displayed. But GNOME has their own
workaround that users can use for …

wayland: soften GNOME warning

---

DOCS/man/mpv.rst
stream/stream.c
stream/stream_slice.c
wscript_build.py

Add support for reading a byte range from a stream via
the `part://` protocol.
Syntax is part://PATH@start[-end] where end is a maximum
(read until end or eof).
Size suffixes support in `m_option` is reused so they can
be used with start/end.
This can be very useful with e.g. large MPEGTS streams with
corruption or time-stamp jumps or other issues in them.

Implement slice:// for reading slices of streams

---

video/out/wayland_common.c
video/out/wayland_common.h

Here for testing. Hopefully this will fix all the weird resizing/geometry/whatever behavior if you're really creative video sizes and playlists. See the commit message for more details. Tagging @bitraid because why not.
~~TODO:~~

wayland: refactor geometry/window handling

---

DOCS/man/options.rst
options/options.c
options/options.h
player/loadfile.c
sub/sd_ass.c
sub/sd_lavc.c

This allows users to control whether full dialogue subtitles are displayed
with an audio track already in their preferred subtitle language.
Additionally, this improves handling for the forced flag, automatically
selecting between forced and unforced subtitle streams based on the user's
settings and the selected audio.

player: add --subs-with-matching-audio option

---

video/out/opengl/context_wayland.c
video/out/vo_wlshm.c
video/out/vulkan/context_wayland.c

I figured out a workaround for the sway border issue. To easily reproduce the issue: have an up-to-date mpv (at least db0f9fab), open a video in a non-floating mode (tiled/tabbed/stacking), set the window scale to 2 (alt+2 by default), and then float the window (meta+spacebar by default). The commit message has a longer explanation but basically we just explicitly commit the newly sized surface (as long as it is not fullscreen or maximized) so sway/wlroots can correctly see the new size and update its border dimensions correctly. This shouldn't have any negative impacts.

wayland: conditionally commit surface on resize

---

sub/osd_libass.c
sub/sd_ass.c
wscript

Replaces `ass_set_aspect_ratio` calls with `ass_set_pixel_aspect` and `ASS_OVERRIDE_BIT_FONT_SIZE` with its newer alias `ASS_OVERRIDE_BIT_SELECTIVE_FONT_SCALE`.
The latter requires to bump the minimal libass version from `0.12.1` (07.01.2015) to `0.12.2` (07.05.2015).
Purely cosmetic, might avoid deprecation warnings in [the future](https://github.com/libass/libass/pull/421).

sd_ass, osd_libass: Don't use deprecated libass symbols

---

DOCS/man/options.rst

Very minor tweak that fixes up the grammar.  Tried to change as little as possible

DOCS: fix minor issue on the --video-latency-hacks explanation

---

player/playloop.c

This commit sorts the included headers alphabetically and puts
them in sections, as described by DOCS/contribute.md.

player/playloop.c: reorder included headers per contribute.md

---

DOCS/man/mpv.rst

Change 'already by defined' to 'already defined' and reformat the paragaph.

manpage: fix typo

---

DOCS/man/mpv.rst
stream/stream_slice.c

Example:
* slice://1g-2g@file.ts (1 to 2)
* slice://1g-+2g@file.ts (1 to 3)

stream_slice: interpret `end` as offset if it starts with '+'

---

DOCS/man/options.rst

Don't make the user search for --osd-color only to make him search again
for --sub-color.

manpage: refer to --sub-color for colors

---

waftools/dependencies.py

Fixes #7855.
Satisfied dependencies are stored in a set, so order is dependent on hash seed. The only other use I see is in `__get_features_string__` in headers.py, which is already being sorted.
On my machine, and with --disable-build-date, this produces bit-identical libmpv.so on repeated clean/configure/build.

build: sort dependencies (to make build deterministic)

---

video/out/opengl/context_wayland.c
video/out/vo_wlshm.c
video/out/vulkan/context.c
video/out/vulkan/context.h
video/out/vulkan/context_wayland.c
video/out/wayland_common.c
video/out/wayland_common.h

I thought I'd try a few ways to modify the swapchain for wayland so it renders smarter. Basically, the goal is to only ever render when we have the surface visible. This isn't trivial because of complicated reasons regarding wayland's behavior (inb4 wayland sucks). More details in the commit message.
TODO:

wayland: only render if we have frame callback

---

DOCS/man/options.rst
video/out/wayland_common.c
video/out/wayland_common.h

As per the client API, a client can connect to any arbitrary wayland
socket. mpv has always just passed NULL which connected to the
compositor currently in use, but one could just as easily pass the name
of a different socket (i.e. the value of WAYLAND_DISPLAY). Here, we just
expose this argument as a user configurable option. If the user passes a
socket name that does not exist, then print a warning and fall back to
NULL.

wayland: add wayland-display-socket option

---

DOCS/man/options.rst

just fixes a tiny typo for the `--sub-filter-regex-enable` docs
Instead of 
> ...setting this option to ``yes`` has no default.
It's now
> setting this option to ``yes`` has no **effect**.

DOCS: fix typo on sub-filter-regex-enable

---

DOCS/man/options.rst

There is a small typo in DOCS/man/options.rst.
Closes #8165

manpage: fix simple typo, unminimze -> unminimize

---

wscript_build.py

Fixes an issue with clang not using the -mconsole option if mwindows
is present resulting in mpv.com being a gui program instead of a
console program.
Does not interfere with gcc compilation.
result without this patch
```
file .\mpv.com .\mpv.exe
.\mpv.com: PE32+ executable (GUI) x86-64 (stripped to external PDB)
.\mpv.exe: PE32+ executable (GUI) x86-64 (stripped to external PDB)
```
both executables open the mpv gui with out console output.
result with this patch
```
file .\mpv.com .\mpv.exe
.\mpv.com: PE32+ executable (console) x86-64 (stripped to external PDB)
.\mpv.exe: PE32+ executable (GUI) x86-64 (stripped to external PDB)
```
mpv.com properly outputs text to console instead of instantly opening
a gui
`, for MS Windows` removed from the end of file outputs to reduce col
count …

wscript_build.py: use -Wl,--subsystem,console instead

---

video/out/opengl/context_wayland.c
video/out/vo_wlshm.c
video/out/vulkan/context_wayland.c
video/out/wayland_common.c
video/out/wayland_common.h

efb0c5c changed the rendering logic of mpv on wayland and made it skip
rendering when it did not receive frame callback in time. The idea was
to skip rendering when the surface was hidden and be less wasteful. This
unfortunately had issues in certain instances where a frame callback
could be missed (but the window was still in view) due to imprecise
rendering (like the default audio video-sync mode). This would lead to
the video appearing to stutter since mpv would skip rendering in those
cases.
To account for this case, simply re-add an old heuristic for detecting
if a window is hidden or not since the goal is to simply not render when
a window is hidden. If the wait on the frame callback times out enough
times in a row, then we consider the window hidden and thus begin to
skip rendering …

wayland: be less strict about when to render

---

video/out/gpu/context.h
video/out/opengl/context_wayland.c
video/out/vo_gpu.c
video/out/vo_wlshm.c
video/out/vulkan/context_wayland.c
video/out/wayland_common.c
video/out/wayland_common.h

Follow up to the wayland opaque stuff. It's possible for a user to change `alpha` while a video is running and the renderer does update this properly (i.e. alpha can turn off and on). The previous wayland opaque commit had no way of detecting this so it could incorrectly have an opaque region set. This adds some functionality in `vo_gpu` to update the `ra_ctx` opts when this value is changed by the user and then allows the wayland backends to properly update their opaque regions.

wayland: update opaque region on runtime

---

video/out/opengl/context_x11egl.c
video/out/opengl/egl_helpers.c

7fb972f fixed transparency on x11/EGL/Mesa but happened to also break it
for wayland and nvidia. Ideally on wayland, you should just be able to
pick the right EGLConfig that has alpha but this doesn't seem to work
because reasons. So just go back to setting the EGL_ALPHA_SIZE bit if
the user asks for alpha. Apparently this worked before for nvidia as
well. The hack is to just run an eglQueryString in the x11egl context.
If it picks up Mesa as the EGL_VENDOR, then force ctx->opts.want_alpha
to 0 and let pick_xrgba_config take care of the rest.

vo_gpu: EGL: hack for alpha on different platforms

---

bootstrap.py

There have been mentions that there are apparently some bugs with
regards to possible random build failures, so bumping after a few
years sounds like an OK thing to test/do.

build: bump waf to 2.0.20

---

DOCS/man/mpv.rst
options/path.c
osdep/path-unix.c
osdep/path-win.c

This is the straight revert of the three relevant changes, and improved documentation as a separate change. It didn't make sense to do a partial revert as the docs have to change substantially to reflect the actual behaviour.

Revert to original config directory precedence but with improved documentation

---

appveyor.yml

Based on the workarounds utilized in the MAME project:
1. mamedev/mame@4b4016110a71a5b84b9d19faf20238d20926088d
2. mamedev/mame@2d1bf3ed5cb1f4cdcc40b286a78c24f398217535

ci/appveyor: attempt to work around outdated msys2

---

DOCS/man/input.rst
player/command.c
player/lua/stats.lua

Expose & show hardware pixfmt in stats.lua

---

DOCS/interface-changes.rst
DOCS/man/input.rst
player/command.c
player/configfiles.c
player/core.h

```
This introduces the delete-watch-later-config command, to complement
write-watch-later-config. This is an alternative to #8141.
The general problem that this change is attempting to help solve has
been described in #336, #3169 and #6574. Though persistent playback
position of a single file is generally a solved problem, this is not
the case for playlists, as described in #8138.
The motivation is facilitating intermittent playback of very large
playlists, consisting of hundreds of entries each many hours
long. Though the current "watch later" mechanism works well - provided
that the files each occur only once in that playlist, and are played
only via that playlist - the biggest issue is that the position is
lost completely should mpv exit uncleanly (e.g. due to a power
failure). …
```

command: add delete-watch-later-config

---

video/out/wayland_common.c
wscript

The `wl_pointer` interface defines button argument as “a button code as defined in the Linux kernel's linux/input-event-codes.h header file, e.g. `BTN_LEFT`.”
We could `#define` these few buttons ourselves, but there is no system to test it on, so for now let’s disable Wayland support on them.
This is a call to non-Linux system maintainers, please help test this backend on your system and report issues you find, or even working state.

wayland: disable when linux-event-codes isn’t available

---

player/external_files.c

relevant changes:
* AlbumArtSmall/Folder/thumb will likely be lower-resolution than the first group
* gif/bmp will likely be worse than all others due to their antiquated file format

player: reorder list of external cover files for optimal results

---

DOCS/man/options.rst
player/lua/ytdl_hook.lua

Allows using a youtube-dl not in PATH or a compatible fork of youtube-dl.
Can probably be tested with https://github.com/blackjack4494/yt-dlc, but I didn't get to test it myself yet.

ytdl_hook: support alternative youtube-dl path

---

DOCS/man/console.rst
player/lua/console.lua

This allows keybindings such as:
```
a script-message-to console type "seek :0 absolute" 6
% script-message-to console type "seek  absolute-percent" 6
```
The cursor position 0 isn't allowed because it has the weird effect of
filling the console with the text twice, leaving the cursor in the
middle.
Negative positions would put the cursor n characters before the end, and
positions greater than the text's length at the end. They seem to work
at first, but the console breaks when you move the cursor, so they
aren't allowed.
It seems that float values don't cause issues, but I'm using the
argument's floor anyway to be safe. Using >= 1 instead of > 0 ignores
values like 0.5.

console: let type set the cursor position

---

video/decode/vd_lavc.c

Now that the first hwaccel implementations are coming in, it makes
sense to allow this format.

vd_lavc: add AV1 to the default allowed hwdec codec list

---

DOCS/man/options.rst

Document the change to add AV1 to the list of default hwdec
codecs, in commit 172146e9f7a231b5de21921d883612d18b13a717.

manpage: document av1 addition to --hwdec-codecs default setting

---

video/out/wayland_common.c
video/out/wayland_common.h

The pointer button event had no code to handle any modifier keys. So
this meant input combinations like Shift+MTBN_LEFT did not work. Fix
this by ripping out the modifier-checking code in keyboard key event to
a separate function and using it for both the keyboard and mouse events.
In the case of the mouse, it is possible that the keyboard may not exist
so be sure to check before trying to get any modifiers. Fixes #8239.

wayland: check for modifier keys on pointer events

---

audio/out/ao_alsa.c

1. Looking at the behavior in `audio/out/buffer.c::ao_play_data`, it seems to expect that the default -1 values are not returned as-is from `get_dev_state`, thus always initialize the state with some values (zero for `free_samples`, device_buffer for `queued_samples`, falsie for `playing`). This might be an incorrect interpretation, but I do not see any specific harm in doing this (with such a limited look in the middle of the night).
2. Handle -EPIPE XRUNs from `snd_pcm_status` by making them into SND_PCM_STATE_XRUN and handling that `pcmst`. Inspired by a patch posted on #mpv by malc_ (https://tpaste.us/x1eJ).
Ref #8205 .

ao_alsa: recover_and_get_state improvements

---

DOCS/man/stats.rst
player/javascript.c

For stats page 4 (key `i`/`I`).
CPU time report is the same as at lua.c, but untested - doesn't seem to work on windows - also not for lua.
Memory reporting is disabled by default  due to additional overhead which the reporting requires, and can be enabled with env MPV_LEAK_REPORT=1.
See more info at the commit message.

js: report scripts CPU/memory usage statistics

---

DOCS/man/input.rst
input/input.c
input/input.h
player/command.c
player/command.h
player/javascript.c
player/javascript/defaults.js
player/lua.c
player/lua/defaults.lua
player/playloop.c

This patchset adds a new property `mouse-pos` which external clients can use to track position and hover.
Previously tracking position/hover was only possible by key-binding MOUSE_MOVE etc, but since the OSC force-binds most mouse events, it was impossible for scripts or other clients to track the position without disabling the OSC, and now it is possible.
Also, it adds a minor improvement for the `mouse` command - which will now trigger enter/leave for the default section when appropriate, while previously it didn't.

Add mouse-pos property

---

DOCS/man/options.rst
stream/stream.c

Recent versions of mpv have applied security checks to --playlist
that previously only existed if playlist files were played as an
input directly. This commit documents this change and how to work
around it, in the event that playlist files are trusted.

manpage: document improved --playlist security

---

DOCS/man/input.rst

Having them in the same line made it hard to read in the man page.
--------------------

doc: split BNF definitions of <command> & <argument> in separate lines

---

.travis.yml
ci/build-macos.sh
waftools/detections/compiler_swift.py
wscript

if the macOS sdk build version list on wiki (https://en.wikipedia.org/wiki/Xcode#Xcode_11.x_-_12.x_(since_SwiftUI_framework)) is to be trusted, the scheme needs some more updates in the future. though we can't really tell now without more releases.
for now i added the macOS 11 case.

build: fix macOS arm builds

---

osdep/terminal-unix.c

When mpv is in the background because it was started with
`mpv foo.mp3 &`, or the user did ctrl+z bg, and is then brought back to
the foreground with fg, it buffers input until you press enter. This
makes it accept input immediately.
Having a short interval isn't important, since input is buffered until
the next SIGALRM.
This always works if you do some normal operations while mpv is in the
background, but if you execute fg immediately unfortunately SIGTTIN
isn't sent sometimes, and I don't think there is a way to receive
SIGTTIN earlier. I think that the only alternative would be to always
keep the timer running, even when mpv isn't backgrounded.
Closes #8120.

terminal: process input when foregrounded

---

demux/demux.c
demux/demux.h
player/command.c
player/core.h
player/loadfile.c

How to test:
* Bind some key to `cycle-values vo null gpu`
* Play a remote file so that the demuxer cache is active
* Press the key and observe that:
- it works
- the demuxer cache is not dropped when switching
Use case:
mpv-android has to disable video output while the app is in background since the surface disappears.
It currently does that by switching `vid` between `no` and `1`, which drops the demuxer cache every time the app is brought in/out of background, causing noticeable delay.

Allow vo changing at runtime

---

video/out/vo_sixel.c

Check for any changes in rows/cols/width/height and trigger the reconfig inside draw_frame. On resizing terminal window, sixel output frame should adjust accordingly.

vo_sixel: Add polling in draw_frame to resize

---

DOCS/man/mpv.rst

While this says that _ is replaced with -, it doesn't say that you HAVE
to use _. This isn't obvious and I didn't understand why my profile
conditions with - weren't working at first. Seeing as the person who
reproted #8324 ran into this as well, this may be worth clarifying.

manpage: clarify profile-cond requires underscores

---

DOCS/man/options.rst

With the current wording, I thought that playlist-prefetch doesn't
prefetch the next url within a playlist of m3u8 urls, but it makes a big
difference, and I would have enabled it earlier if it wasn't for this
paragraph.

manpage: clarify that you can prefetch m3u8 urls

---

DOCS/man/options.rst

--alpha=yes doesn't affect only transparent videos and images, but also
the background. I spent time trying researching how to implement
transparent backgrounds and had no idea that they already worked at
least on Wayland.
Background transparency will work on X11 when
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/2376 is
merged. It doesn't work on Windows. No idea about macOS. Either way,
this paragraph already says that it only works on certain environments
twice.
References #6590

manpage: document background transparency

---

player/lua/auto_profiles.lua
waftools/checks/custom.py

CC @jrejaud
If you don't want to go through the trouble of building mpv from this branch, you could test this by disabling the built-in version of the auto_profiles script with `--load-auto-profiles=no` and putting the [patched version](https://raw.githubusercontent.com/mpv-player/mpv/b3c111c65bf4a96c924eed07571297c6a8ca9e0e/player/lua/auto_profiles.lua) in `~/.config/mpv/scripts/`.
---
Lua 5.1 can't handle calling load() on a string. It looks like the existing code was trying to cater to 5.1, with the comment and the setfenv code. It probably worked on 5.1 at some point, but wasn't tested there after some change.
Also added detection of lua51 on Arch, just because that was the easiest way for me to test this. Might as well have it, though.

auto_profiles: fix compile_cond on lua 5.1

---

video/out/wayland_common.c
video/out/x11_common.c
video/out/x11_common.h

Related issue: #8379
I cherry-picked wm4's commit for x11 from another branch (with one minor change in the includes so vdpau would compile correctly) and also implemented this feature for wayland. wm4's changes in x11 will only work with `--geometry` but in wayland it will work with the `--autofit` options as well.

update --geometry/autofit options at runtime

---

video/out/opengl/context_wayland.c
video/out/vo_wlshm.c
video/out/vulkan/context_wayland.c
video/out/wayland_common.c

The first commit just moves all the frame callback/presentation feedback stuff into `wayland_common` since there's no reason to have that all duplicated anymore (well it hasn't be necessary for a long while actually...). As a result of that, I realized that `wlshm` actually can receive presentation feedback now, so I went ahead and implemented it in the second commit since it's only a few more lines.

wayland: unify frame/presentation callback code and add presentation time to wlshm

---

DOCS/interface-changes.rst
DOCS/man/options.rst
osdep/macosx_application.h
osdep/macosx_application.m
video/out/mac/common.swift

this changes the previous behaviour. one can't place the window anymore outside of the visible screen rectangle anymore. this means the window can't be placed on the menu bar or the dock area (as long as the dock is visible) anymore.
i am not sure if this behaviour makes sense in all circumstances and maybe we need a flag to change this behaviour?
Fixes #8272
some examples how the behaviour differs now. the window in the foreground is the new behaviour:
autofit=100%x100%:
autofit=50%x50%:
geometry=500x250+100%+100%
geometry=500x250+0%+100%

mac: use visible frame rectangle for window geometry calculation

---

waftools/checks/custom.py
wscript

Picking up from #8355.
The upside is you can use `./waf configure --lua=52` regardless of how your distro packages Lua versions. Also threw in a little over-engineering to make the used Lua version a bit clearer in logs ("List of enabled features" just showed "52", will now show "lua52").
The downside is losing the ability to pick between the different packaging variants if you somehow end up with more than one for the same version on your machine, and that logs will no long differentiate between said variants. I don't see much harm there, but admittedly the benefit of this patch is similarly small.
The first commit at least should be a simple win, though.

build: make Lua detection more friendly?

---

DOCS/man/options.rst
video/decode/vd_lavc.c

It is supported at least on Intel, from gen8 to gen12, and still gives a pretty welcome reduction of CPU usage on my gen9.

vd_lavc: add VP8 to the default allowed hwdec codec list

---

DOCS/man/ao.rst
DOCS/man/mpv.rst
DOCS/man/options.rst
DOCS/man/vo.rst

Apple has decided that Mac OS X is now named macOS for the time
being. For consistency, it makes sense to use the same name for the
operating system in all places where it occurs. This commit renames
OS X to macOS in the documentation in places where it was otherwise
still using the old name.

manpage: rename OS X references to macOS

---

DOCS/man/options.rst

loop-file counts the number of zero-seeks, not playthroughs,
which makes its counter off by one compared to loop-playlist.

manpage: document off-by-one loop-file behavior

---

.travis.yml
osdep/macos/libmpv_helper.swift
osdep/macos/mpv_helper.swift
osdep/macos/swift_compat.swift
video/out/mac/common.swift
waftools/checks/custom.py
wscript

added a helper function to get pointers of several data at once. otherwise we would need to nest several withUnsafeBytes calls, which would make the whole code an indentation hell and hard to read. see: https://forums.swift.org/t/swift-5-2-pointers-and-coretext/34862
also dropped build support for swift <4.1 and with this support for xcode <= 9.2 and macOS 10.12.

mac: fix usage of temporary pointers and dangling pointers

---

DOCS/man/vf.rst

`--vf format:stereo-in=help` no longer works.  It now must be `--vf=format:stereo-in=help`
After noticing this I regex searched the other man pages and this was the only usage of this old style I could find.

docs: fix an old style parameter reference

---

README.md

since libass 0.15 harfbuzz is no longer optional.
Fixes #8412

README: update libass dependency harfbuzz as non-optional

---

video/out/vo_wlshm.c

The video was otherwise blue, and that’s not how it should be. :)

vo_wlshm: support big endian systems

---

.travis.yml
osdep/macosx_touchbar.h
osdep/macosx_touchbar.m

replaces the broken NSSliderTouchBarItem with a NSCustomTouchBarItem + NSSlider, which are basically identically.
also only update the touch bar items when necessary, eg touch bar and the affected item is visible.
fixes a constraint warning (#7047) and hopefully also at least one performance regression (#8477).

mac: use custom touch bar item and slider instead of a touch bar slider

---

common/msg.c

this change is up for discussion. i think it doesn't make sense for `log-file` to produce a (half) empty file if `really-quiet` is set. we want to at least have a log of `-v -v` verbosity.
introduced by a600d152d21ef398eb72b008ee3fe266696eb638, since the log level is overwritten after the log level was actually found by mp_msg_find_level.
we had that problem on #8581

msg: fix really-quiet option to only affect terminal output

---

video/out/placebo/ra_pl.c
wscript

It's about a year old, and packaged pretty much everywhere that bothers
to package libplacebo at all. Older versions are unlikely to be
prevalent and/or useful.
Starting with v2.72.0, libplacebo validates all of its parameters
internally and turns them into function failures. Doing it twice is
awfully redundant, so we can drop the parameter validation.
Also allows us to drop some preprocessor macros.

vo_gpu: libplacebo: require v2.72.0

---

DOCS/man/options.rst

The 90° step limitation must be a leftover from old behavior since any value between 0 and 359 works now.

manpage: video-rotate supports arbitrary steps

---

player/lua/ytdl_hook.lua

Some tracks happen to lack bitrate information (ie. no tbr value).
In that case, just ignore the track while computing the max bitrate.
For an example, this is a stream in which all audio tracks
have no bitrate: https://www.raiplay.it/dirette/rai1

ytdl_hook: fix crash on missing track bitrate

---

player/audio.c

There was a simple oversight that meant audio outputs were
uninitialized during an encoding, which is not allowed, the encoding
would stop with numerous errors.
I added a single line to prevent the call of uninit_audio_out in
reinit_audio_chain if the encoder was active and this appears to have
fixed the problem without breaking anything else.
Fixes #8568

audio: prevent uninit_audio_out during encoding

---

DOCS/man/ao.rst
audio/out/ao.c
audio/out/ao_oss.c
wscript
wscript_build.py

Return back OSS output.
- code refactored;
- mixer options removed;
- new mpv sound API used;
- add sound devices detect (mpv --audio-device=help will show all available devices);
- only OSSv4 supported now;
Tested on FreeBSD 12.2 amd64.

ao_oss: OSS backend return

---

DOCS/man/options.rst
video/out/gpu/video.c

I think this is a bit of bikeshedding, so feel free to reject this since it's entirely possible for someone to set this value themselves. But I think it's counterintuitive to have a scenario where interpolation can be rapidly turned on and off and cause visual artifacts just because the logic for interpolation is 100x more precise than the logic for retiming your video.
I also cannot think of a scenario where this would break any known (good) default behavior of mpv. This should only affect cases where the the video FPS is within 1% of the display but not within 0.01% of the display. Pretty much only affecting things like streaming. Or so I hope...
fixes: #8378 
fixes: #8653

RFC: vo_gpu: adjust interpolation_threshold's default

---

player/audio.c

Seems to be a slight corner case with the audio API rewrite. When
switching from one file to another one, the volume of the ao would never
be set because the audio chain's ao wasn't set. This caused a bug with
the reset-set-on-file option. The volume/property would be correctly set
internally, but the gain was not actually set when the file switched.
Fixes #8287.
If someone that actually knows how the audio code works can double check to make sure I'm not doing something retarded here, that'd be great.

audio: set audio chain ao on reinit

---

video/out/wayland_common.c
video/out/wayland_common.h

The wayland code uses a heuristic to determine whether or not the mpv
window is hidden since the xdg-shell protocol does not provide a way for
a client to directly know this. We don't render with the frame callback
function for various, complicated reasons but the tl;dr is that it
doesn't work well with mpv's core (maybe an essay should be written on
this one day).
Currently, the aforementioned heuristic considers a window hidden if we
miss more frames in a row than the display's current refresh rate
(completely arbitrary number). However, the wayland protocol does allow
for the display's refresh rate to be 0 in certain cases (like a virtual
output). This completely wrecks the heuristic and basically causes only
every other frame to be rendered (real world example: nested sway
sessions). …

wayland: workaround hidden state detection badness

---

stream/stream_file.c

i tested tuxera ntfs first since it is the commercial version of macfuse/ntfs-3g and would use the same f_fstypename, but it doesn't. so i added it to the list too.
the new f_fstypename for osxfusefs is macfuse, though we will still keep the old name.
was requested on this clossed issue: https://github.com/mpv-player/mpv/issues/634#issuecomment-821959432

stream_file: add new identifier for macOS FUSE filesystems

---

player/lua/osc.lua

Clearing state.osd.data with an empty string at render_wipe() fixes an
issue where changing the OSC visibility from "never" directly to
"always" didn't immediately update the display when the player was
paused. This could be verified by starting the player with
`--script-opts=osc-visibility=always --pause` and then running
`script-message osc-visibility never` followed by
`script-message osc-visibility always`.
Removing the overlay without changing the contents meant the overlay
wouldn't update and display when enabled again until the fields changed
in some way (e.g. seeking, mousing over the OSC area, etc.). Clearing
state.osd.data before removal of the OSC makes sure set_osd doesn't
return on re-enable and instead displays the OSC immediately as the data
is now different.
render_wipe() …

osc: display immediately when visibility changes from never to always

---

video/out/wayland_common.c

It turns out that if a user specifies fullscreen=yes and a width/height
in an autoprofile, the compositor can execute its toplevel listener
event. This can happen before we have any mpv window rendered at all so
we end up performing a bunch of geometry operations and state checks
when we shouldn't. It subtly messes up a lot of things like state
detection. Just return from this function if the geometry has no width
or height yet.
@laichiaheng: Does this commit fix your issue?

wayland: ignore toplevel listener if geometry is 0

---

player/lua/osc.lua

This fixes a bug where using boxvideo with showfullscreen=no or
showwindowed=no resulted in the margins not resetting when the OSC
wasn't visible.
For example, using:
`
script-opts=osc-visibility=always,osc-boxvideo=yes,osc-showfullscreen=no
`
and then going fullscreen would make the OSC disappear but the video
margins would remain. This is because boxvideo was missing a dependence
on the showfullscreen and showwindowed user options.
This is fixed by adding the corresponding conditions to update_margins()
and setting state.marginsREQ on fullscreen changes. update_margins() is
called on tick() if there's a margins update pending, which guarantees
the boxvideo margins are reset appropriately.

osc: reset margins when using boxvideo with showfullscreen/showwindowed

---

DOCS/man/input.rst
player/command.c

This part of the documentation caused me a bit of pain. Also, I went ahead and made the related sub-properties ints like they actually are.

command: osd-dimensions: return ints and doc fixes

---

DOCS/man/input.rst
player/command.c
video/out/mac/common.swift
video/out/opengl/context_drm_egl.c
video/out/vo.h
video/out/vo_drm.c
video/out/vo_rpi.c
video/out/w32_common.c
video/out/wayland_common.c
video/out/x11_common.c

For some reason, this never existed before. Add VOCTRL_GET_DISPLAY_RES
and use it to obtain the current display's resolution from each
vo/windowing backend if applicable. Users can then access the current
display resolution as display-width and display-height as per the client
api. Note that macOS/cocoa was not attempted in this commit since the
author has no clue how to write swift.
Sidenote: I didn't test windows or rpi.
~Edit: Now this PR covers more video/display properties.~ Not anymore.

command: add display-width/display-height property

---

stream/stream_file.c

couldn't really test this because of the reproducibility of it.
see vlc for a similar fix. https://github.com/videolan/vlc/commit/b8b8c438f8f65a93da82364c8fea1dbf987c4a8e https://trac.videolan.org/vlc/ticket/8446
Fixes #4434

stream_file: disable read ahead for remote files on macOS

---

TOOLS/osxbundle/mpv.app/Contents/Info.plist

see the description of the commit for some explanation.
the behaviour can be forced by setting the following environment variable on the terminal:
```
MallocNanoZone="1" mpv PATH/TO/FILE.mkv
```
make sure to call following to the app info.plist cache, otherwise it might take the cached old plist.
```
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -f PATH/TO/mpv.app
```
additional to the reproductions steps from issue #8820 and #7405 and comment(s) here https://github.com/mpv-player/mpv/issues/7405#issuecomment-835799610.
TL;DR the problem is a slow and wasteful memory allocation policy that is only activated when launched from the finder, eg launchd. the environment variable has to be set before/with the …

osxbundle: fix slow and wasteful memory allocation

---

etc/input.conf
options/options.c
options/options.h
player/command.c
sub/dec_sub.c
sub/dec_sub.h
sub/osd.c

Closes issue #8243
Adds a new option `secondary-sub-visibility` which toggles the visibility of the secondary subtitle. The default keybind for toggling the secondary subtitles is `Alt+v`.

sub/osd: add keybinding to toggle secondary subtitles

---

DOCS/man/input.rst
player/command.c

Closes issue #8689. Adds a new property called `secondary-sub-text`, and adds a helper function for getting the current subtitles (`get_subtitle_text` in player/command.c).

player/command: add secondary-sub-text property

---

video/out/opengl/context_wayland.c
video/out/vo_wlshm.c
video/out/vulkan/context_wayland.c
video/out/wayland_common.c
video/out/wayland_common.h

Check the commit message if you want my full blog entry. ~~Basically what this does is add an optional VOCTRL_WAIT_CALLBACK event to the main render loop (specifically in `render_frame`). Like the name implies, a vo/backend can implement a wait function here for blocking purposes right before the succeeding `draw_frame` call. If the vo/backend doesn't need this, then it just instantly returns true and nothing changes. Of course, the target here is wayland and its frame callback but in theory any other vo/backend could leverage this mechanism if it was advantageous.~~ Actually, I just refactored/changed the wayland render loop a bit.
Using this approach greatly simplifies a lot of the wayland logic (a bunch of crap can be deleted) and finally achieves my goal of not having to use …

wayland: simplify render loop 

---

DOCS/interface-changes.rst
DOCS/man/options.rst
video/out/gpu/lcms.c

Not only does this have semantics that make far more sense, it also has
a default that makes far more sense. (Equivalent to the old
`icc-contrast=inf`)
This removes the weird 1000:1 contrast default assumption which
especially broke perceptual profiles and also screws things up for
OLED/CRT/etc.
Should probably close some issues but I honestly can't be bothered to
figure out which of the thousands colorimetry-related issues are
affected.

vo_gpu: replace --icc-contrast by --icc-force-contrast

---

audio/filter/af_scaletempo2_internals.c
wscript

This brings my scaletempo2 benchmark down from ~22s to ~8s on my machine
(-march=native), and down to ~11s with a generic compile.
Closes #8848
TODO:
```
./audio/filter/af_scaletempo2_internals.c: In function ‘hsum8’:
../audio/filter/af_scaletempo2_internals.c:111:21: note: the ABI for passing parameters with 32-byte alignment has changed in GCC 4.6
111 | static inline float hsum8(v8sf v8)
|                     ^~~~~
```

af_scaletempo2: use gcc vectors to speed up inner loop

---

common/recorder.c

```
Avoiding blindly copying the codec_tag between different formats allows
us to mux packets from, say, mpegts streams to matroska, making the
recorder (dump-cache) much more usable as unsupported codec_tags can
make the muxer reject the streams.
```
`dump-cache` Twitch streams to your heart's content now.

recorder: clear codec_tag if no target format support

---

player/lua/osc.lua

When the OSC initializes, it checks whether the current video has chapters, and if it does not, it disables its chapter functionality (chapter buttons are grayed out and unusable, chapter indicators don't show on the seek bar). If another script¹ changes the chapter list after the video has loaded, those changes will be ignored by the OSC until some other event causes it to re-initialize, because it does not observe the chapter list property. This is fixed by simply adding observation of `chapter-list` alongside the other properties that trigger re-initialization.
¹ For example, [this SponsorBlock script](https://github.com/po5/mpv_sponsorblock), with the local database disabled, loads segments asynchronously, creating chapters a short time after playback starts. These chapters don't …

osc: re-initialize when chapter list changes

---

DOCS/man/input.rst
video/out/w32_common.c

```
It seems that currently it's supported by all main VOs (x11, macOS,
wayland, Windows). TCT/sixel/caca probably not, and unknown with SDL.
Fixes #8868
```
@rossy should the WM_* handlers return `0` instead of doing `break` (which later ends up calling and returning `DefWindowProcW(...)`?
The MSDN docs states for both `WM_KILLFOCUS` and `WM_SETFOCUS`: "An application should return zero if it processes this message.", but I _think_ this is inconsistent in mpv handling of WM_* messages - and the WM_KILLFOCUS handler did not return 0 also before this commit.

win32: support the property 'focused'

---

DOCS/man/options.rst

docs: fix reference to the now defunct --video-sync-adrop-size
This is a follow up to 502e7987d8d85cb1d9eb3b3d1af38a1a92cc04e8

docs: fix reference to the now defunct --video-sync-adrop-size

---

DOCS/man/options.rst
options/options.c
options/options.h
video/out/gpu/context.c
video/out/vulkan/context.c
video/out/vulkan/context.h
video/out/vulkan/context_display.c
wscript_build.py

This is the Vulkan equivalent of the drm context for OpenGL, with
the big difference that it's implemented purely in terms of Vulkan
calls and doesn't actually require drm or kms.
The basic idea is to identify a display, mode, and plane on a device,
and then create a display backed surface for the swapchain. In theory,
past that point, everything is the same, and this is in fact the case
on Intel hardware. I can get a video playing on a vt.
On nvidia, naturally, things don't work that way. Instead, nvidia only
implemented the extension for scenarios where a VR application is
stealing a display from a running window system, and not for
standalone scenarios. With additional code, I've got this scenario to
work but that's a separate incremental change.
Other people have tested on AMD, and …

WIP: Vulkan context for VkDisplayKHR (aka: "drm" context for Vulkan)

---

player/external_files.c

Removes the goto which caused lang to be used in the sub->lang
assignment without being initialized when adding cover art. lang is
normally initialized to a garbage value like {start = 0x0, len =
94415366337024}, and so sub->lang was assigned nullptr whether lang was
initialized on not due to safety checks in bstrdup0's internals
(ta_strndup checks if the pointer is null first), but a segfault happens
only on Windows 8 on certain builds of GCC 10.2 with optimization,
assumedly because lang.start is initialized to a non-null value which
bstrdup0 tries to use.
Also remove the check that the external filename is not the same as the
currently playing one, preventing mpv from loading images again as
external cover art, which isn't necessary because cover art is only
added when playing …

player: fix segfault

---

DOCS/man/osc.rst
player/lua/osc.lua

Three commits:
- Add `hoverinfo` framework - "status" at the osc title while hovering some osc elements.
- Add static info text for most buttons.
- Add dynamic seekbar info with target chapter.
The framework allows either static or dynamic text per element (or none). Info for disabled elements does show up - to allow discoverability, but it's grayed-out like the disabled element itself.
The second commit (static buttons text) is open to bikeshedding about format/texts and whether or not we want it also for trivial buttons (e.g. the play/pause button currently does have hoverinfo), but I suggest not to dwell on it too much because it's trivial to change at any time.
Personally I don't have a strong opinion on what the info texts should be exactly, other than it should be useful.
The third …

Osc hoverinfo

---

DOCS/man/options.rst
options/options.c
options/options.h
player/sub.c

This fixes a long-standing apparent issue where mpv would display the last frame with no subtitles at EOF. This is caused by sub rendering switching from video timestamps to audio timestamps when the video ends, and audio streams often running past the timestamp of the last video frame. However, authoring tools (most notably Aegisub) don't tend to provide easy ways to add meaningful subtitles after the end of the video, so this is rarely actually useful.

sub: by default, don't render timestamps after video EOF

---

player/lua/defaults.lua

Two commits:
- Don't allow slow timer callbacks to block script event handling (including quit).
- Timers added from idle observers could fire long after they're due.
More details and example at the commit messages.

Lua: refine timers and idle observers

---

player/configfiles.c

Commits 4d1ffec and 6e481d0 renamed sub-ass-style-override to
sub-ass-override. But in commit bd603c2, when renaming it in
quit-watch-later's backup_properties, which determines which properties
are saved by quit-watch-later/write-watch-later-config, it was
incorrectly renamed to sub-style-override instead, and thus never got
saved even if modified at runtime. Instead mpv attempted to save the
non-existing property "sub-style-override", but since no error is raised
when saving non-existing properties with quit-watch-later, no one
noticed it. This commit renames the saved property to the correct new
name "sub-ass-override" so that it does get saved.

player: fix property name

---

TOOLS/lua/autoload.lua

See commit for logic. Basically ignoring hidden files is probably what 90% of users want, but 10% of users will get annoyed by. Might as well give them an option to allow for hidden files now that extensions are explicitly whitelisted.

TOOLS/lua/autoload: add ignore_hidden option

---

DOCS/man/osc.rst

fix the tiny typo about `seekbarkeyframes`
`true` or `false` cannot be read from conf file. 
So change them to `yes` or `no`.

DOCS: fix typo on seekbarkeyframes

---

player/lua/stats.lua

Seems like a stats kind of thing that might be useful. I called it `Scaled Resolution` which is hopefully clear enough (the size of the scaled video). The value is just the osd-width/height minus the margins.

stats.lua: add scaled resolution

---

player/sub.c

Default regressed on this case in 11423acf3
Reported in https://github.com/mpv-player/mpv/pull/8420#issuecomment-868987385

sub: fix subs/lyrics on music files with sub-past-video-end=no

---

player/lua/osc.lua

osc-visibility can already be changed at runtime via script-message
or other means, but until now there was no way to tell what the
current state is.
Now shared-script-properties/osc-visibility reflects this state.
It's output-only by the osc - changing it does not affect the osc.
Useful if a script wants to change osc-visibility temporarily, and
later restore to its original state.
There's no way to coordinate if more than one script wants to change
it, but that would be a hard problem to solve anyway, even if the
osc itself tried to coordinate such requests from different sources.

osc: expose osc-visibility via shared-script-properties

---

DOCS/man/input.rst
DOCS/man/options.rst
player/command.c
test/subtimes.js

* ~~Adds ```--secondary-sub-delay=<sec>``` as an option and makes it so ```--sub-delay=<sec>``` only affects the primary subtitle.~~
* Adds ```secondary-sub-start``` and ```secondary-sub-end``` properties. Closes #8343.
* Adds a secondary argument to ```sub-seek``` and ```sub-step``` for choosing which subtitle track to seek/step through. The primary subtitle is the default so as not to break compatibility with anything that depended on the old versions.
* Adds documentation for ``secondary-sub-visibility``.

command: adds several commands/properties for secondary subs

---

demux/demux.c
player/audio.c

Heap use after free error reported by Address Sanitizer in case of audio init failure. 
Thread sanitizer reported data race for the variable `in->byte_level_seeks` which is written without acquiring the lock inside `update_bytes_read` and simultaneously being read in `demux_get_reader_state` with lock acquired.

Fix Address Sanitizer reported error and Thread Sanitizer reported data race

---

TOOLS/dylib-unhell.py
TOOLS/osxbundle.py

It seems `osxbundle` will execute `dylib-unhell` with python2, fixed in this pr

osxbundle: use python3

---

DOCS/man/mpv.rst
DOCS/man/stats.rst
player/lua/stats.lua

- Move the internal performance info from page 4 to page 0.
- Add key-bindings list at page 4.
- Support help-like printout of the whole list to the terminal.
The alignment/grouping style is heavily inspired by @medhefgo's #8924 but otherwise it's an independent implementation.
<details>
<summary>Inside: terminal output listing for --no-config</summary>
By default the key names and section titles are in bold, but using `-yes` instead of `yes` disables the terminal escape sequences. The interactive video-window (libass) output is similar in style.
```
$ mpv --idle --no-config --script-opts=stats-help-keys=-yes
Active key bindings:
audio 
SHARP  cycle audio
Ctrl++  add audio-delay 0.100
Ctrl+-  add audio-delay -0.100
brightness 
3  add brightness -1
4  add brightness 1
chapter 
!  add …
```

stats.lua: add keybindings info page

---

DOCS/interface-changes.rst
DOCS/man/options.rst
options/m_config_frontend.c
options/m_config_frontend.h
options/m_option.c
options/options.c
options/options.h
player/configfiles.c
player/core.h
player/main.c

This allows configuring which properties are saved by quit-watch-later.
Fixes #4126, fixes #4641, fixes #5567.

options: add watch-later-options

---

DOCS/man/options.rst
options/m_config_frontend.c

--watch-later-options-remove doesn't accept multiple options, so split
the example.
Also suggest the more correct -clr to empty the list, and remove the
workaround to not print an error with --watch-later-options=

manpage: fix watch-later-options examples

---

video/out/opengl/context_drm_egl.c

Sometimes I use drm and I got annoyed by having to type --gpu-context=drm. The drm context has been explicitly coded to disallow the autoprobe almost its entire existence (since: https://github.com/mpv-player/mpv/commit/f757163058c2e5c7136213b0f79923fcea34b71a). @rr-: do you remember what the reason for that commit was?

context_drm_egl: allow autoprobe selection

---

player/command.c

When changing image-display-duration at runtime, make the new value take
effect immediately, rather than from the next playlist-position change.
This allows toggling the slideshow mode while viewing images (without
hacks like executing playlist-play-index current afterwards).
Changing image-display-duration, and thus mpctx->time_frame, while
playing videos doesn't cause any issue since the value is overwritten
immediately, with any --video-sync option value.

command: handle changes to image-display-duration

---

video/out/opengl/common.c
video/out/opengl/common.h
video/out/opengl/egl_helpers.c

The EGL stuff is really complicated because of historical reasons
(tl;dr: blame EGL). There was one edge case with EGL context creation
that lead to incorrect behavior. EGL_KHR_create_context was created with
EGL 1.4 (which mpv does support) but it is still possible for an EGL 1.4
device to not implement this extension. That means that none of the EGL
attrs that pass a specific opengl version work. So for this obscure
case, there is a fallback context creation at the very end which simply
creates an EGLContext without passing any special attrs.
This has another problem however. mpv has a hard requirement on at least
desktop opengl 2.1 or opengl ES 2.0 to function (we're not asking for
much here). Since the fallback EGL context creation has no version
checking, it is entirely possible to …

egl_helpers: fix create_context fallback behavior

---

TOOLS/lua/autocrop.lua

Because having these on every video is annoying, and when you resume
from watch later files, the filters are applied immediately so they hide
your osd-playing-msg or equivalent show-text commands.

TOOLS/autocrop.lua: allow hiding OSD messages

---

DOCS/man/input.rst

Explain that property expansion isn't performed on commands that accept arguments as arrays and those that accept named arguments.

manpage: explain when properties are expanded

---

DOCS/man/mpv.rst
DOCS/man/stats.rst

This fix the two warnings shown below when trying to compile any 
of the three renditions of the manual:
```
DOCS/man/mpv.rst:46: (ERROR/3) Unknown target name: "--input-test".
DOCS/man/stats.rst:183: (ERROR/3) Unknown target name: "--input-test".
```

DOCS: fix manual compiling warnings

---

DOCS/man/input.rst
DOCS/man/options.rst
options/options.c
player/loadfile.c

Let audio-display determine whether attached pictures or external cover
art tracks should be selected when both are present.
Attached pictures are given priority by default as requested in #8539.
Also updates references to attached pictures in the log and manpage to
refer to cover art as well.
Closes #8539.
Reusing `audio-display` to set the priority instead of adding another option is nice, but it may be better to decide whether the priority of external sub and audio files should be configurable, and if so implement it consistently for sub, audio and cover art, like --{sub,audio-file,cover-art}-auto-select=[no,yes]. I don't know if someone actually needs those though. See #3777.

options: audio-display determines cover priority

---

DOCS/man/input.rst
input/cmd.c
player/lua/stats.lua

- Change custom quotes start-char from `!` (exclamation-mark) to \` (back quote/tick).
- Support single quotes, and refine the docs now that we have 3 types of quotes.
- Detect single quotes in stats.lua page 4 (key bindings).
Main reason for changing `!` to \` is that we have ` cycle-values !reverse ...` which required quoting as `cycle-values "!reverse" ...` after custom quotes were added, but doesn't anymore because `!` is no longer special.
This breaks backward compatibility for anyone who's already using custom quotes at their `input.conf`, however, we didn't make a release yet since custom quotes were added, and it's trivial to use the new char instead.
Supporting single quotes is useful, simple, and technically unrelated to the custom quotes change, but I prefer to have them …

Refine arguments quoting #2

---

options/m_config_frontend.c

Since 1d1d1fbff9 option-info/\<name>/set-locally was being set to true
for every option. This broke setting start from ytdl-hook, which doesn't
overwrite start if it was set-locally. Fix this so that only adding an
option to reset-on-next-file or setting file-local-options/\<name> make
set-locally true like before.
However, it's arguable whether just adding an option to
reset-on-next-file without ever changing it should make set-locally
true, so that e.g.
--reset-on-next-file=start 'https://www.youtube.com/watch?v=LXb3EKWsInQ&t=1m30s'
doesn't start at 90, though it probably should.
Fixes #9081.

options: don't always set set-locally to true

---

video/out/wayland_common.c
video/out/wayland_common.h

Need to actually test some other compositors but probably they work fine since Sway has by far the most complicated geometry handling of the group.

wayland: cleanup handle_toplevel_config

---

DOCS/man/options.rst
options/options.c
options/options.h
sub/filter_jsre.c
sub/filter_regex.c
sub/filter_sdh.c
sub/sd.h
sub/sd_ass.c
wscript_build.py

The core of this patch set is adding a js-based regex filter, pretty much the same as `--js-filter-regex` but with JS regex syntax, and also sharing its control options.
Main reason for adding it is that the regex filter doesn't work on Windows due to missing regex POSIX APIs, but JS support in mpv can, and usually is enabed in Windows builds.
However, while adding it I noticed that there's some duplicated code where ASS sub filters need to extract the text fom the demuxed packet, which is annoying to reinvent/duplicate.
So the first commit adds the text extraction code as utilities for ASS filters, and uses it from the regex filter. The following two commits make use of these utils for the SDH filter.
The 4th commit finally adds the jsre filter which also makes use of these utils.
Then, …

sub: support --sub-filter-jsre (js regex)

---

DOCS/interface-changes.rst
DOCS/man/input.rst
etc/input.conf
player/command.c

Somewhat confusingly, mpv has both a window-scale option and a
current-window-scale property. The documentation lists window-scale
under properties (and it is technically is one), but at its core it is
actually an option which means it behaves subtly different. Options in
mpv are runtime-configurable, but they only change anything if the value
of the option itself changes. window-scale is an option and not meant to
keep track of the actual scale of the window (intended behavior
introduced by d07b7f0). This causes window-scale to do nothing in
certain cases (ex: the window is manually resized and window-scale is
set to 1.00 again). This is logical and consistent with the behavior of
the rest of the mpv options, but it also makes it a poor candidate for
setting the mpv window scale …

command: make current-window-scale writeable

---

DOCS/man/input.rst

Reworded the documentation for clarity on how the `window-scale` and `current-window-scale` properties should behave. This isn't currently consistent across all platforms. E.g. xorg currently handles setting window-scale if it is fullscreen (that is, taking the window out of fullscreen then performs the resize if applicable) but not if it is maximized. Wayland always returns the actual scale value of the window and not the scale value of the non-fullscreened state (that is, when fullscreened it will return what the video is currently scaled by). I'll fix both of those after we iron out what should actually happen. No clue what happens on other platforms. If this behavior doesn't sound right or should be reworded, please weigh in.

manpage: clarify window-scale behavior

---

DOCS/man/options.rst
video/out/wayland_common.c
video/out/wayland_common.h

If somebody that has touch stuff + a wayland compositor could actually test that this works like how I hope it works, that would be very much appreciated. Tagging @soloturn since he expressed interest in touch screen stuff on wayland.
What hopefully happens with this PR:
* One finger touch and move -> the window drags
* One finger touch and move around the edge of the window -> the window resizes
* Two finger touch and move -> the window resizes
* Touching on a visible osc -> actually behaves like a mouse click
* Doing more than two touches at a time (i.e. 3+ fingers) is completely ignored
What won't happen:
* Two finger move (Hopefully this is fine? I don't think adding a ton of extra complexity for a two finger move and a two finger resize is worth it when you can just use one finger.) …

Possible wayland touch improvements

---

player/command.c

The vo currently handles rotations in 90 degree steps and some VOs set
this via VO_CAP_ROTATE90. When the rotation exactly hits either 90 or
270 degrees, this causes the values of dwidth and dheight to perfectly
swap like one would expect. However, the mp_image_params_get_dsize
function call in both of the window scale functions do not take this
special case into account. So the width/height values returned will be
incorrectly flipped in the 90 and 270 degree cases if the vo driver does
implement VO_CAP_ROTATE90 (like vo=gpu). Fortunately, the
mp_image_params struct keeps track of the rotation for us. So all we
need to do is check if the image is rotated at 90 or 270 degrees and
check that the current vo driver supports VO_CAP_ROTATE90. If so, then
swap vid_w and vid_h to their true, …

window-scale fixes

---

player/sub.c
sub/dec_sub.c
sub/dec_sub.h

29e15e6248 prefixed youtube-dl's subs url with an edl prefix to not
download them until they're selected, which is useful when there are
many sub languages. But this prefix broke the alignment of secondary
subs, which would overlap the primary subs instead of always being
placed at the top. This can be tested with
`--sub-file='edl://!no_clip;!delay_open,media_type=sub;secondary_sub.srt'`
When a sub is added, `sub.c:reinit_sub()` is called. This calls in
`init_subdec()` -> `dec_sub.c:sub_create()` -> `init_decoder()` ->
`sd_ass:init()`. Then `reinit_sub()` calls
`sub_control(track->d_sub, SD_CTRL_SET_TOP, &(bool){!!order})` which sets
`sd_ass_priv.on_top` = `true` for secondary subs.
But for EDL subs the real sub is initialized again when in
`dec_sub.c:sub_read_packets()` …

sub: align ytdl-hook secondary subs to the top

---

video/out/vo_vdpau.c

VO_VDPAU: Update vo_vdpau.c to return -1 in reconfig()
When the VT switch out is triggered, the decode thread (VD) falls back
to sw decoding. However, on the VO thread, which is responsible for
handling display preemption and presentation, vo_vdpau.c:reconfig() is
called. The reconfig() function returned -1 when the check_preemption()
returned 0. The vo_reconfig2() (which calls reconfig()) returned -1 in
turn which entered into an error handling path. This led to a series of
functions calls that ultimately set the in_terminate flag to TRUE.
This led the vo_thread to exit which ultimately led to the
MPV application exit.
The fix is to return 0 instead of -1 after the check_preemption() in
the vo_vpdau.c:reconfig(). Returning 0 instead of -1 is not fatal and
does not have any side effects. …

Update vo_vdpau.c to return -1 in reconfig().

---

video/out/x11_common.c

If a user attempted to change the window scale of a maximized window on
x11, nothing would happen since the window manager holds the size of the
window constant. Just do an unmaximize first before performing the
resize.

x11: handle maximized windows with window-scale

---

player/video.c

When changing video track with subtitles with unknown duration, they
aren't shown until you seek, cycle sub back and forth, or apply a video
filter. This is caused by reinit_video_chain_src() calling
reset_subtitle_state() -> sub/sd_ass.c:reset() -> ass_flush_events()
when ctx->duration_unknown is true.
The ass_flush_events() call was added in a714f8e928 so subs with unknown
duration wouldn't multiply on seek, i.e. when reset_subtitle_state() is
called from reset_playback_state(). Therefore, this commit adds an
argument to reset_subtitle_state() that determines whether to call
ass_flush_events().
Alternatively, replacing `reset_subtitle_state()` in `reinit_video_chain_src()` with just `term_osd_set_subs(mpctx, NULL)`, which clears any subtitles printed to the terminal when switching to a …

sub: show subs without duration on vid change

---

DOCS/man/input.rst

- Replace the legacy --osd-status-msg with the newer --osd-msg3.
- Use single quotes in
show-text "This is ${osd-ass-cc/0}{\b1}bold text", which is wrong
because \b is interpreted as an escape sequence. You need to use \\\\b
or single quotes.
- Update the escaping notice, since you can now use single and custom
quotes which don't interpret escape sequences.

DOCS/input: update osd-ass-cc documentation

---

DOCS/compile-windows.md
DOCS/man/af.rst
DOCS/man/javascript.rst
DOCS/man/libmpv.rst
DOCS/man/lua.rst
DOCS/man/vf.rst
DOCS/mplayer-changes.rst
DOCS/waf-buildsystem.rst
README.md

Inspired by #8893 but done a bit more thoroughly. I used:
```
find . -type f \( -name '*.md' -o -name '*.rst' \)  -exec grep -n 'http://' {} +
```
to discover all of these links. The commits are:
- change mpv links to https
- change 3rd party links to https (after checking https is available)
- Change a dead link to the waf book to the current one
There were other dead links that I didn't touch
```
./DOCS/man/ao.rst:33:        You can also try `using the upmix plugin <http://git.io/vfuAy>`_.
./DOCS/man/input.rst:3068:    A list of tags can be found here: http://docs.aegisub.org/latest/ASS_Tags/
./DOCS/compile-windows.md:14:**Warning**: the original MinGW (http://www.mingw.org) is unsupported.
```
Also a link that did not have https
``` …
```

Convert links to HTTPS

---

DOCS/man/input.rst
input/cmd.c

Previously, a list of commands was always considered repeatable.
This behavior was added at 6710527a (and moved around since then),
in order to fix #807 (impossible to make a repeatable list).
The problem was that a list doesn't have the normal repeatability
flags and so it was never repeatable, so it was hardcoded to be
repeatable instead. Presumably it was deemed good enough.
However, this made it impossible to have a non-repeatable list.
This commit changes the behavior so that a list repeatability is
that of the first command at the list.
This way, any list can be made either repeatable or non-repeatable
using the following idiom (e.g. at input.conf), based on the fact
that the "ignore" command is not repeatable by default:
x            ignore; cmd1...; cmd2...   # non-repeatable
y …

command: don't hardcode commands list to be repeatable

---

video/out/w32_common.c

win32: take dpi scale into account with [current-]window-scale (osx/x11/wayland already do that), and two minor refinements:
- Ensure initial dpi-scale value.
- Support the property `display-hidpi-scale` (only used from `console.lua`).

win32: take dpi scale into account with [current-]window-scale

---

sub/osd_libass.c

The fix is in two stages:
- Disable the opaque-box style for the progress bar because it messes up the bar.
- Apply an artificial opaque-box background to the bar with the original color/alpha.

osd_libass: fix progress bar with --osd-back-color

---

DOCS/man/input.rst
player/command.c

The "cycle" command _declaration_ enables repeatability by default,
however, the command handler applies additional logic to augment it,
based on the property which is being cycled - using some guesswork.
Specifically, properties with discrete values are not repeatable
(like sub or osd-level), while continuous properties are repeatable
(like volume).
Previously, the "repeatable" prefix could not override this additional
logic.
This commit changes the behavior so that the logic affects only the
default repeatability (still based on the property like before),
however, the "repeatable" prefix is now allowed to override it.

command: cycle: respect the prefix "repeatable"

---

osdep/terminal-unix.c

Previously, if an unknown ESC sequence was detected where an ASCII
char `<X>` follows the ESC, mpv interpreted it as `ALT+<X>`, which is the
traditional terminal encoding of ALT+letter.
However, if `<X>` is '[' then it's a CSI sequence which continues after
the '[', possibly for quite a while, and has its own termination rules.
Previously, mpv interpreted unknown CSI sequences as ALT+[ and garbage
"keys" from the rest of the sequence.
In this commit, if a unknown CSI sequence is detected, mpv first waits
till it completes, and then throws away exactly the complete sequence.

terminal-unix: identify and ignore unknown CSI sequences

---

LICENSE.GPL
LICENSE.LGPL

The current files contain broken formatting characters
New files downloaded from:
https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
An additional improvement is that the new files use https links and fix url redirects.

Use correct license files from gnu.org

---

video/out/wayland_common.c

Since most compositors set this variable but do not create `~/.icons/default` without user intervention it does seem like more reasonable approach, especially since "default" still will be used as a fallback.

wayland: Read XCURSOR_THEME to get cursor theme and set default cursor size to 24

---

DOCS/man/options.rst

This "bw" should most likely be a "be".

DOCS/options: fix minor typo in compute shaders section

---

etc/mpv.bash-completion

If bash_completion wasn't installed, _filedir wouldn't be defined which
led to all filename-based completions to error out. Specifically
autocompletion would fail when a filename was expected and when
bash_completion wasn't installed. Now we fall back to `compgen -f` if
_filedir fails. According to _filedir's comments, compgen doesn't
handle files with spaces well, but it is still better to complete most
files than none.

bash completion: Allow completions to work without external functions

---

video/out/w32_common.c
video/out/win_state.c
video/out/win_state.h

- First two commits separate the general screen fit calculation from the monitor aspect calculation, and then use this separate calculation from the win32 vo.
- Third commit does the initial fit/center including the border instead of the content. This only affects initial positioning and not the initial size.

w32: fix --monitoraspect application and improve initial fit

---

demux/demux_playlist.c

Last time it was extended was de3ecc60 from 8K to 512K two years ago.
The issue currently is that youtube EDL files can get very big.
Size of about 520K (one line), was observed, at the time of writing:
mpv https://youtube.com/watch?v=DBzFQgSMHdQ --ytdl-format=299
ytdl_hook.lua is unaffected by this because EDL lists don't go through
the file reader at demux_playlist.c (where each line was limited to
512K before this commit), however, EDL files on disk which are
loaded with --playlist=file.edl do.
Increase the limit to 2M so that such EDL files can also be loaded
from disk.

demux_playlist: extend maximum line size (again) to 2M

---

wscript

Its define (HAVE_FFMPEG_STRICT_ABI) is now utilized in a single
location, where an internal libavformat struct member is utilized.
This struct member is now (after around 10 years) finally removed
from public visibility in FFmpeg's master.
After a review of functionality, the information in bytes_read is
passed onto the demuxer layer, and then utilized for
{cache,hack}_unbuffered_read_bytes. This information is then utilized
for:
1. Calculation of bytes_per_second in demux/demux.c::update_cache,
which fills the information for properties "cache-speed" as well as
"raw-input-rate" (of which stats.lua is the most prominent user).
2. bytes_per_second also affects how often update_cache is called in
addition to the two locations it is called unconditionally in
(read_packet, demux_update).
In …

build: enable strict FFmpeg ABI compatibility by default

---

video/out/wayland_common.c

In wayland_common, wl->window_size keeps track of the window's size when
it is not in the fullscreen or maximized state. GET_UNFS_WINDOW_SIZE is
meant to report the size except for when it is fullscreen (hence UNFS).
However, the actual function was merely returning the wl->window_size so
it was wrong for maximized windows. Workaround this by returning
wl->geometry instead when we have the maximized case. Fixes #9207.

wayland: report correct window size when maximized

---

README.md
waftools/features.py

This brings enabled features on the same level as disabled and
auto-detected features by having both alternatives available.
Looking at the commit message of 652895abdce4bc1ff2f00c7f21c0d0d722680806
this seems to have been the intent from the start, but this specific
definition was missing from the option creation in Features.

waftools/features: add forgotten enable variants for enabled features

---

osdep/timer-win2.c
osdep/timer.h
osdep/win32/pthread.c

Before this commit, timeBeginPeriod(1) was set once when mpv starts,
and the timers remained hi-res till mpv exits.
Now we do the same as before on Windows version < 10.
On Windows 10+ we now use timeBeginPeriod if needed, per timeout.
To force a mode regardless of Windows version, set env MPV_HRT:
- "always":  the old behavior - hires timers as long as mpv runs.
- "perwait": sets 1ms timer resolution if timeout < 50ms.
- "never":   don't use timeBeginPeriod at all.
It was observed that on Windows 10 we lose about 0.5ms accuracy of
timeouts with "perwait" mode (acceptable), but otherwise it works
well for continuous timeouts (one after the other) and random ones.
On Windows 7 with "perwait": continous timeouts are accurate, but
random timeouts (after some time without timeouts) have bad …

win32: Windows 10: timeBeginPeriod on demand

---

stream/dvbin.h

We do not actually use this, and it's in a state of maybe-removal from the kernel as of Linux 5.14. Get rid of it; mpv still builds fine without it, so it wasn't needed anyways.
Fixes #9233.

stream/dvbin: remove "full-featured" API includes

---

DOCS/man/options.rst
player/lua/ytdl_hook.lua

Because youtube-dl is inactive and the yt-dlp fork is becoming more
popular, make mpv use yt-dlp without any extra configuration.
yt-dlp is ordered before youtube-dl because it's more obscure, so users
who have yt-dlp installed are more likely to want to use it rather than
youtube-dl.
io.open and os.getenv('PATH') are not used because they don't handle
UTF-8 on Windows 7 and 8.
exists_in_path is based on
https://github.com/TheAMM/mpv_script_libs/blob/master/helpers.lua
Fixes #9208.

ytdl_hook.lua: search for yt-dlp by default

---

video/out/vo_rpi.c

Fixes handle leak that happened whenever tvservice callback was invoked.
Powering on the TV causes HDMI unplug and attached events to be sent to
the tvservice callback.
This meant you could only power on/off your TV a finite number of times
before you were unable to allocate additional resources from VideoCore
(usually resulting in a "Could not get DISPMANX objects." error).
Furthermore because the VideoCore kernel driver does not cleanup handles
when a process dies, the only way to recover from the leak was to reboot
the RPI.

vo_rpi: fix DISPMANX_UPDATE_HANDLE_T leak

---

.github/workflows/build.yml

This CI builder bases on openSUSE Tumbleweed, and recently had
its glibc updated. This led to new syscalls such as 'clone3' not
being allowed through the security layer.
Can be reverted after Github Actions updates their security policy.
actions/virtual-environments#3812

github/workflows: disable seccomp for linux native CI

---

waftools/checks/custom.py
waftools/inflector.py
wscript

This allows using the (pkg-config) package name to choose a specific lua version e.g. `--lua=lua52` or `--lua=lua-5.1` etc.
The same generic names are also autodetected instead of the previous distro-specific names (51deb, 52arch, etc).
The legacy names are still supported, but not documented anymore, and are shadowed by the generic names during autodetection.
Maybe todo in the future:
- The name which shows at the output of `mpv -v` has underscores, e.g. `--lua=lua-5.1` shows as `lua_5_1`. It would be nicer if it would be same as the requested name. mpv doesn't use any of these names (it detects the version using the lua C headers).
- During autodetection, until a package is found, pkg-config is invoked twice than required (both for the generic name and for the legacy name which refer to …

build: lua 5.1/5.2: use generic version names 

---

player/lua/osc.lua

Infinite repeating ticks on idle happened before this commit whenever mpv is in idle state and a tick is triggered (mouse move, property change, etc). Once it started - it never stopped ticking.
These commits fix that.

osc.lua: avoid infinite ticks loop on idle 

---

options/m_option.c

Currently using mpv --msg-level=help, shows an instance of --msglevel
(missing dash). Seems like the help message was only partially updated
with the -msglevel -> --msg-level transition.

options: add missing dash in msg-level help message

---

video/out/hwdec/hwdec_cuda_vk.c
video/out/hwdec/hwdec_vaapi_vk.c
video/out/placebo/ra_pl.c
video/out/placebo/utils.h
video/out/vulkan/context.c
wscript

Bump minimum dependency and remove features that were deprecated starting with libplacebo v3, as these will be removed in libplacebo v4.

Update to libplacebo v3

---

DOCS/man/console.rst
player/lua/console.lua

This always deletes the previous character in other applications with
keybindings based on Emacs or Vim.

console.lua: define remaining emacs keybindings

---

player/javascript/defaults.js

The problem with the previous code - which used mp.get_user_path, is
that it returns a path even with --no-config, and even if the file
doesn't exist.
This is why we tested the "config" property, and also used
mp.utils.file_info to check that the file exists.
mp.find_config_file doesn't return a path with no-cofig and doesn't
return a path if the file doesn't exists. It's simpler and better.

js: ~~/init.js: use mp.find_config_file

---

video/out/wayland_common.c
video/out/x11_common.c

Back when runtime updating of autofit/geometry was added for wayland and
x11 (commits: 4445ac828dca0298543103094357e64f8828ef56 and
ced92ba607ebd98687b26ef3d8c09d5f6e22cf4b respectively), the naive
assumption was that window-related geometry would always be available.
While this is true 99% of the time, this isn't a guarentee. It is
possible for certain things such as loading shaders to delay starting up
the player. This causes autofit/geometry options to be registered as a
runtime update and triggers VOCTRL_VO_OPTS_CHANGED. This ends up calling
some geometry-related functions but this happens before the actual
values are available. Hence, a nullptr was accessed which segfaults. At
least one user experienced this with a combination of options in wayland
but in theory the same thing could …

player: fix autofit/geometry related segfault

---

video/out/vo_gpu_next.c
video/out/vulkan/context.c
video/out/vulkan/context.h
video/out/vulkan/context_wayland.c

Alternative to #9392. It's way simpler (the first commit is purely cosmetic) so this is probably better. I'm assuming here that the `ra_fbo` is never `NULL` normally which I think is fine. Basically, we're just cannibalizing vulkan/context.c a little bit more.

vo_gpu_next: call start_frame in vulkan/context.c

---

video/out/vo_gpu_next.c
wscript

This required an upstream API change to implement in a way that doesn't
unnecessarily re-push or upload frames that won't be used. I consider
this a big enough bug to justify bumping the minimum version for it.
Closes #9401

 vo_gpu_next: fix resource exhaustion on minimized windows 

---

DOCS/interface-changes.rst
DOCS/man/options.rst
video/out/vo_gpu_next.c

Completely untested, since Linux still can't into HDR in 2021. Somebody
please make sure it works.
Technically covers #8219, since gpu-context=drm can be combined with
vo=gpu-next.

vo_gpu_next: implement HDR passthrough

---

video/out/vo_gpu_next.c

Without initializing, the random data causes the `pl_render_image_mix`
function to abort with a SIGSEGV.
I found that the crash was the easiest to reproduce with `--force-window=immediate`, but is not exclusive to that option.

vo_gpu_next: Initialize `pl_frame_mix`

---

video/out/drm_common.c
video/out/drm_common.h
video/out/opengl/context_drm_egl.c
wscript

The GBM supporting nvidia driver doesn't support creating surfaces
without modifiers and using modifiers is more and more recommended as
the right way to do this.
Enumerating modifiers is painfully verbose, but necessary if we are to
allow the driver to pick the best possible one.
Finally, I added support for [A|X]BGR2101010 because nvidia supports
that instead of RGB. Of course, their EGL doesn't support 10bit formats
so you still can't actually use a 10bit DRM format.

context_drm_egl: Use gbm_surface_create_with_modifiers

---

video/out/opengl/egl_helpers.c

d2e8bc449986e012f257249a996386bd323febd0 was the the commit that
originally introduced the usage of this bit. As the message states, the
purpose was to force creating GLES 3 contexts on drivers that do not
return a higher version context than what was requested. With the recent
opengl refactors, mpv's gl selection has already moved away from such
complicated queries. Perhaps when that commit was added things were
different, but nowadays it seems like Mesa simply returns the highest
driver version available that is compatibile with the request (i.e.
requesting GLES 2 returns a GLES 3 context on my machine). In that case,
let's just simply drop EGL_OPENGL_ES3_BIT altogether as it does break
GLES 2 only machines. Fixes #9431.

egl_helpers: remove EGL_OPENGL_ES3_BIT

---

DOCS/man/options.rst

Small typo I found in mpv manpage. There's an extra ` at the option name

DOCS/options: fix `target-colorspace-hint` typo

---

player/lua/ytdl_hook.lua

`youtube-dl` and `yt-dlp` both support `--sub-langs` and `--srt-lang` in addition to `--sub-lang` for defining languages of subtitles.
This hook only checked for `sub-lang` in `--ytdl-raw-options` and inserted `--all-subs` in its absence.

ytdl_hook.lua: improve check for sub language before inserting all-subs

---

video/out/vulkan/context_display.c

While the basic Vulkan Display context can theoretically drive the
display without the involvement of any non-Vulkan code, that prevents
us from using VAAPI acceleration. When initialising VAAPI without a
window system, we need to provide it with an opened DRM render fd
corresponding to the device to use.
In the context of using VK_KHR_display, that means we need to identify
which DRM device matches the selected Vulkan device, and then open its
render fd and set the necessary state that VAAPI expects to find.
With that done, the normal VAAPI<->Vulkan interop can kick in and we
get working acceleration

vo_gpu: vulkan: open DRM render fd when using VK_KHR_display

---

meson.build

This fixes several issues when building for android (some of them quite obvious sorry...). This was tested with [mpv-android](https://github.com/mpv-android/mpv-android).
**Note:** Meson currently ignores pkg-config --static so the above repo won't build (libass linking will fail) without modifying the crossfile. I added this option right under the `[built-in options]` line. Not pretty at all but it works. Maybe there's a better set of flags to achieve the same thing. Unsure.
`c_link_args = ['-Wl,-Bstatic', '/full/path/to/libfribidi.a', '/full/path/to/libfreetype.a', '/full/path/to/libharfbuzz.a', '-Wl,-Bdynamic']` The other way to get the build to work is to add `static: true` to the `meson.build` directly to the libass dependency but I didn't think that was worth it. There doesn't seem …

meson: fix build on android

---

stream/stream_dvb.c

This deadlock was not triggered in real use since configuration
validity does not change at runtime.
closes #9459

stream_dvb: Add missing mutex unlock.

---

audio/out/ao_opensles.c

Upstream "Wilhelm" (the Android OpenSLES implementation) supports only 8000 <= rate <= 192000. Make sure mpv resamples the audio when necessary.

ao_opensles: add guards for sample rate to use

---

libmpv/client.h
libmpv/render.h
meson.build

Admittedly, this is nicer in waf since it has a cross-platform way to
handle exporting symbols. Meson doesn't have this so instead let's
accomplish this with a couple of sym files and adding link arguments to
libmpv. This should make the symbol visibility the same as waf.
I was also able to verify that this also works correctly on windows with msys2.

meson: export the correct symbols in libmpv

---

video/out/vo_gpu_next.c

Fix typo in the warning to avoid ewa_lanczossharp because
it might be removed in the future.

vo_gpu_next: fix lancozs typo to lanczos

---

audio/out/buffer.c

regression introduced in b74c09efbf7c6969fc053265f72cc0501b840ce1:
https://github.com/mpv-player/mpv/blob/e095bdb5f56c1f78c47d1e7583ebc95fc20ba16e/audio/out/buffer.c#L163-L166
this is obviously wrong, as you can compare to a memcpy just a few lines before in the same function:
https://github.com/mpv-player/mpv/blob/e095bdb5f56c1f78c47d1e7583ebc95fc20ba16e/audio/out/buffer.c#L145-L147
here's the original version pre-refactor:
https://github.com/mpv-player/mpv/blob/3a8abbee2fd25f9d137098cd4ed9f7cedf478fbd/audio/out/pull.c#L183-L185
probable root cause of #8381. maybe related to #9472 
this was most likely to cause issues when viewing live/network streams where audio data might not be readily available on every read, causing the underflow code to kick in. it sounds like crackling and popping …

audio: stop corrupting audio on underreads

---

video/out/hwdec/hwdec_vaapi.h
video/out/hwdec/hwdec_vaapi_gl.c

If the EGL extension is present, pass the modifiers for each plane
to the EGL driver.

vo_gpu: hwdec_vaapi: add dma-buf modifiers support.

---

video/out/wayland_common.c

Don't like it but maybe I'll deal with it for now. Fixes #9504.

wayland: increase the vblank waiting time

---

DOCS/man/osc.rst
player/lua/osc.lua

Previously OSD was always displayed on {ch,pl}_{next,prev} left-click,
and seekbar-hover-chapter was always enabled and with fixed format.
Now it can be controlled with:
- chapters_osd, playlist_osd: yes/no (only affects left-click).
- chapter_fmt: lua string.format template, or "no" to disable.
Fixes #4675

osc: add options: chapters/playlist OSD, hover chapter format

---

meson.build

The tl;dr is that a fix for freebsd accidentally broke mingw. Everything is fixed for real with https://github.com/mesonbuild/meson/pull/9642 which would require a version bump. In the meantime just if/else this.

meson: add a temporary workaround for iconv crap

---

meson.build

meson: correct champ.c to chmap.c

meson: correct champ.c to chmap.c

---

player/lua/osc.lua

Previously, numbers like 59.9 could be stuck into the string.format method, resulting in lua rounding the number 59.9 to 60. A simple example that caused the bug: `string.format("%02.0f", 59.9)`.
Warning: This commit is untested.
Screenshot of bug:

osc: fix cache displaying 60s in some cases

---

player/playloop.c

Allow --keep-open=always to work with --loop-playlist, where
before this patch it would work only on the last playthrough of the
playlist. This patch allows it to work on all playthroughs.
Fixes #9470.

player: make --keep-open=always work with --loop-playlist

---

DOCS/man/ao.rst
audio/out/ao_openal.c

Prevent audio distortions caused by OpenAL's 3D effects.

ao_openal: enable AL_SOFT_direct_channels_remix extension by default

---

video/out/opengl/common.c

This function is provided by a different extension on OpenGL ES so we
add a separate gl_functions.
ref: https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_debug.txt tested locally on nvidia drivers. I'm not totally sure if this is the accepted way to handle functions with different extensions between gl and gles but it seems correct.
Signed-off-by: Kurt Kartaltepe <kkartaltepe@gmail.com>

opengl: Support DebugMessageCallback on ES

---

video/out/opengl/common.c
video/out/opengl/common.h
video/out/opengl/context_wayland.c

This is a workaround for nvidia proprietary drivers. The authors of
those drivers interpret the spec such that eglMakeCurrent will not
reconfigure the read and draw buffers. Thus windows wont display
anything drawn by opengl. nvidia authors refer to
https://www.khronos.org/registry/EGL/extensions/KHR/EGL_KHR_no_config_context.txt
specifically Issues 2/3 which reference eglMakeCurrent.
On mesa this is a non-issue and the read/draw targets are assigned with
eglMakeCurrent.
The context must be made current in order to query OpenGL strings. An
earlier proposal to create the wayland window surface similarly to X11
during init was deemed inappropriate so instead we manually set the
targets once we have created a window surface.
I'm not very familiar with the opengl layer in mpv, so if there is …

wayland: ensure read and draw buffers are assigned

---

sub/lavc_conv.c

Since libavcodec major version 59, the requested "ass" format became
the default as the old timing-included format was disabled starting
with that version. Additionally, this option by itself has since
been deprecated as it no longer serves any purpose.
References:
FFmpeg/FFmpeg@1f63665ca567fbc49fa80166d468a822c2999efa
FFmpeg/FFmpeg@176b8d785bf7531b6eb8e3d6e8c03f75cb29de1e
Fixes #9413

sub/lavc_conv: only set subtitle text format when required

---

video/out/opengl/context.c

vo_gpu: opengl: try and create context at version 440 again
nvidia follow the OpenGL spec very strictly, with two particular
consequences:
* They will give you the exact context version that you ask for,
rather than the highest possible version that meets your request.
* They will hide extensions that the specs say require a higher
version than you request, even if it's technically possible to
provide the extension at lower versions.
In our case, we really want a variety of extensions, particularly
compute shaders that are only available in 4.2 or higher. That means
that we must explicitly include a high enough version in our list of
versions to check for us to be able to get a 'good' enough context.
As for which version? We restore the 4.4 version that we had in the
old version selection …

vo_gpu: opengl: try and create context at version 440 again

---

video/out/gpu/error_diffusion.c
video/out/gpu/shader_cache.c
video/out/gpu/video.c
video/out/gpu/video_shaders.c
video/out/opengl/common.c
video/out/opengl/ra_gl.c

It's supposed to work with GLES >= 3.1 but we had all sorts of bad
assumptions in our version handling, and then our compute shader
isn't GLSL-ES compliant.
Still doesn't work. Fails with:
[vo/gpu/opengl] after dispatching compute shader: OpenGL error INVALID_OPERATION.

vo/gpu/opengl: try and make compute shaders work with GLES

---

audio/filter/af_lavcac3enc.c

Simply returning out of this function leaks avpkt, need to always "goto
done".
Fixes #9593

af_lavcac3enc: fix memory leak on no-op

---

filters/f_decoder_wrapper.c
video/mp_image.c

fixes #9249 (JPEG orientation support) with ffmpeg commit [0].
[0] https://github.com/FFmpeg/FFmpeg/commit/e93c9986027d17917c3b4f533b28ee4a2ce7cd4c
tests:
- working with no/90/180/270 jpeg written by exiftool
- still working with h264 mp4 unrotated/rotated 90 degrees in container (plays rotated 90, not 180)
- still not working with rotated mkv (plays without rotation)
- still not working with h264_metadata=rotate=90 mp4 (plays without rotation)

mp_image, f_decoder_wrapper: implement AV_FRAME_DATA_DISPLAYMATRIX

---

meson.build

If you install docutils with pip in the default way, you will get a
script called `rst2man.py` rather than `rst2man`, so look for both
names.

meson: look for rst2man.py as well as rst2man

---

video/out/d3d11/ra_d3d11.c
video/out/gpu/ra.h
video/out/gpu/video.c
video/out/opengl/gl_headers.h
video/out/opengl/ra_gl.c
video/out/placebo/ra_pl.c

We've been assuming that maximum number of compute group threads is
never less than the 1024 defined by the desktop GL spec. Given that we
haven't had working compute shaders for GLES and I guess the Vulkan
spec defines at least as high a value, we've gotten away with it so
far.
But we should really look the value up and respect it.

vo_gpu: stop hard-coding max compute group threads

---

wscript

Shaderc has been shipping .pc files for almost three years and we all
know of the advantages. If this turns out to be problematic the old checks
can be re-added but I'd like to avoid doing this preemptively.

wscript: switch shaderc checks to pkgconfig

---

meson.build

shaderc is a special case dependency in meson. According to the
documentation*, it first checks for shaderc_shared and will fallback to
shaderc_combined (the order is reversed if the static keyword is true).
However, shaderc also has a third .pc file (shaderc_static) which should
be checked. The meson documentation doesn't indicate this, but it also
actually checks shaderc_shared*. shaderc_combined is first checked if
meson looks for static libs and if that is not found it tries
shaderc_shared. So this extra fallback check is not needed.
*: https://mesonbuild.com/Dependencies.html#shaderc
*: https://github.com/mesonbuild/meson/blob/a2934ca9d13ede4eb97b320bc768319ecad7b525/mesonbuild/dependencies/misc.py#L539

meson: remove unneccesary shaderc_static check

---

video/out/wayland_common.c

Commits 04018c306196888861775b248a8596ae494f122b
cd7a7a1de8d8bffa05170befef25b251711c994a introduced behavior that
updated window geometry during wayland events (specifically surface and
output). This is good but they also are too aggressive with
automatically resizing. For example, if a window is manually resized by
the user and then dragged to a different monitor with different geometry
than the initial monitor, mpv will automatically resize itself to the
window's resolution. The initial thought behind this logic was for
autofit to automatically readjust itself on a new monitor, but doing
that breaks other common use cases. An attempt could be made to
distinguish between autofit and a manual resize but that introduces a
lot of complexity for an edge case. It's better to simply not …

wayland: avoid doing unneccesary window resizes

---

video/decode/vd_lavc.c

This has now landed in ffmpeg, and afaik there's no particular reason it shouldn't be enabled by default.

vd_lavc: enable hwdec for prores by default

---

.github/workflows/build.yml
meson.build

I happened to look around at some distros and it looks like a lot of people are up to date on meson versions now which is good. The first commit drops some pip3 calls in the github workflows and instead just uses the OS package manager to fetch meson since it's now new enough. The second commit removes some iconv workaround crap and as a result updates the required meson version to 0.60.3. I know bumping the required version to something that came out a little more than two weeks ago doesn't look nice, but for whatever reason, more distros are on 0.60.3 now than were on 0.60.0 when meson support was initially merged. I don't anticipate bumping the required meson version anytime in the near future, so I think 0.60.3 will be the requirement for a very long time.
Edit: Looks like opensuse's …

Meson CI updates/cleanups

---

audio/filter/af_lavcac3enc.c
common/encode_lavc.c
common/encode_lavc.h
demux/packet.c
video/image_writer.c

This extracts the parts from #8698 that can be done without touching `mp_set_av_packet`. Made sure to include error handling and avoid repeated allocations this time.

Replace some deprecated av_init_packet() calls

---

player/external_files.c

mpv works fine with such audio when extension is changed to something already supported like "ac3".

player: add thd (TrueHD) to whitelist of audio extensions

---

DOCS/interface-changes.rst
DOCS/man/options.rst
etc/input.conf
options/options.c
options/options.h
player/command.c
sub/dec_sub.c
sub/dec_sub.h
sub/osd.c

- Changes `--sub-visibility` from a flag option to a choice option, adding `primary-only` and `secondary-only` choices for displaying only the primary subtitle track and secondary subtitle track respectively
- Removes `--secondary-sub-visibility` and displays a message telling the user to use `--sub-visibility=primary-only` instead
- Removes `Alt+v` as a bind for cycling through `--secondary-sub-visibility`
- ~~Adds `--primary-sub-visibility` option for toggling the visibility of the primary subtitle track independent of `--secondary-sub-visibility`~~
- ~~Adds `Alt+V` shortcut for cycling through `primary-sub-visibility`~~
**Use Case**
I maintain a video player using libmpv that renders primary subtitles outside of mpv by observing the `sub-text` property. I would like to make it so that …

options: adds primary-only and secondary-only choices to --sub-visibility

---

DOCS/interface-changes.rst
DOCS/man/options.rst
sub/dec_sub.c
sub/dec_sub.h
sub/osd.c

Reverts 928668e and instead adds this functionality by modifying `sub-visibility` to only affect primary subs.
Edit: Rebased on master.

options: only apply sub-visibility to primary subs

---

DOCS/man/ao.rst
audio/out/ao.c
audio/out/ao_sndio.c
meson.build
meson_options.txt
wscript
wscript_build.py

This pull request is completely based on #8314 and is its continuation. In fact, this is the @rozhuk-im patch with fixes for the bugs described [here](https://github.com/mpv-player/mpv/pull/8314#issuecomment-917697089) by @brad0 and with improvements described [here](https://github.com/mpv-player/mpv/pull/8314#pullrequestreview-655014951) by @michaelforney . Minor cosmetic changes are also present.
The correct operation of ao_sndio from the patch was tested on OpenBSD current (not on the most current snapshot, though; I don't think it matters in principle).

Another attempt to return ao_sndio to mpv

---

.github/workflows/build.yml
ci/build-freebsd.sh

We have this ao again since #9298 so let's run it through the CI.

ci/build-freebsd: enable sndio ao during build

---

video/out/wayland_common.c
video/out/x11_common.c

This is part of the protocol spec so go ahead and leverage existing mpv
tools to do this. Fixes #9694.
This also would fix #8812. Technically gnome already did their own workaround for that issue, but the reason that crash happened is because the title was never sanitized.

x11/wayland: sanitize titles to UTF-8

---

.github/workflows/build.yml
demux/demux_lavf.c
meson.build
wscript

I'm not sure when we wanted to remove this check exactly, but maybe soon.

build: remove aviocontext bytes_read check

---

video/out/wayland_common.c

Mouse button event codes above `BTN_EXTRA` (the ones currently defined
in `input-event-codes.h` are `BTN_FORWARD`, `BTN_BACK`, and `BTN_TASK`)
are mapped to `MP_MBTN9` and up. (Reminder that due to historical
reasons, the names `BTN_FORWARD` and `BTN_BACK` are completely
misleading; the real forward and back buttons are `BTN_SIDE` and
`BTN_EXTRA` and are already mapped correctly by mpv.)
This functionality is analogous to what the X11 backend supports in
`video/out/x11_common.c` and what the Cocoa backend supports in
`video/out/cocoa/events_view.m`.

wayland: support extra mouse buttons

---

meson.build

There is no libdl library in the *BSD family of operating systems; all required functions (dl{open,close,sym,...}) are in libc and available for every dynamic executable. [1]
Therefore, current check for libdl existence is incorrect. As a consequence, building cplugins is forcibly disabled on the bsd systems, which is wrong, since nothing prevents successful building/working.
In the patch I create 5 logical variables similar to `darwin`, `win32` or `posix`. Of course, I could make just one variable `bsd` and set it to `true` in a loop iterating over a list of 4 bsd systems [2]  or match the OS names with a regular expression, but:
* there is a noticeable non-zero chance that sooner or later we will find a feature that is specific to only one of the BSD family of OSes, not all, and one …

[BSD] Fix cplugins/libdl existence check

---

video/out/w32_common.c

The docs specify that the +-X+-Y geometry values position the content.
This used to work worrectly but got broken at 8fb4fd9a .
Geometry size is unaffected - this only concerns position.
Commit 8fb4fd9a made it center the window rather than the content by
taking the borders into account during positioning, but forgot to make
an exception when a position is specified explicitly.
This commit adds this exception, and now if a specific position is
requested then the borders are ignored, and the content is positioned
correctly.

win32: apply geometry position to content instead of window

---

DOCS/man/vo.rst
video/out/d3d11/context.c
video/out/d3d11/context.h
video/out/gpu_next/context.c
wscript

1. Handle lack of output fbo in D3D11's `start_frame`.
2. Add an API to get the d3d11 swap chain from the RA context.
3. Minor rework of the `gpu-next` context code to make more non-Vulkan use cases share at least some common code.
4. Do initial plugging in of d3d11 shenanigans.
Now locally I see d3d11 working by default, as well as `--gpu-api=vulkan` working. So I haven't broken Vulkan, at least :) .
**Known issues**:
`--d3d11-output-csp=pq` -> the swap chain gets configured properly, but the color space is not propagated to libplacebo so basically you get a very red colored image (since I don't think this is reverse tone mapping :) ) 🔴

vo_gpu_next: initial attempt at adding d3d11 support

---

video/out/filter_kernels.c

In my tests (upscale 1080p to 1440p) cosine windowed sinc with smaller radius was better than lanczos which in same tests was better than all other already implemented filters.
Test results (dssim scaled/original): lanczos, radius=8, antiring=1 (0.0077068); cosine, radius=6, antiring=1 (0.00769295)
Also visually when zoomed in images of both upscales were >99% similar.

filter_kernels: add cosine window

---

video/out/hwdec/hwdec_vaapi.c

While testing support for the exotic formats used by Intel vaapi for
4:2:2 and 4:4:4 surfaces, I realised that we were enumerating all
endpoints and checking formats for them. The problem with this is
that decoding (VLD) endpoints are only a subset of what vaapi exposes.
All the encoding endpoints are there too, and there is also the
None profile that we don't care about, but which generates ffmpeg
warnings if you try and examine it.
So, let's only look at VLD endpoints. This will speed things up a
little bit and make the logging less noisy.

vo_gpu: hwdec_vaapi: Don't probe formats for irrelevant endpoints

---

video/filter/vf_format.c

We only wish to touch actual video frames, which should have an
allocated image attached to them, so just check the frame type
early, and exit by passing through such non-video frames to further
filters in the chain without attempting to process them.
Fixes a crash in case of non-video (EOF/NONE) frames being passed
onto the filter when the dovi option was set to false since
05ccc51d53424a771ece5bb818713d474d7874ce .

vf_format: simplify frame type checking after addition of DoVi option

---

audio/out/ao_pipewire.c

Open points:
* Sometimes the `process()` callback is not fired by Pipewire, so the playback stays frozen. Needs to be investigated.
* The proper hotplug driver-callbacks are not implemented because mpv only calls the hotplug handlers for the first AO that defines them, in this case it will be pulseaudio
* No hotplug events are fired.

ao_pipewire: add support for device selection

---

DOCS/man/mpv.rst

libavfilter's rotate accepts radians, not degrees, so correct its usage
in the documentation's examples.
Also replace vf-add=hflip with vf add hflip, since that example lists
commands, not options, to run.

DOCS/mpv: fix vf=rotate examples

---

.github/workflows/build.yml
meson.build

See the commit messages for full details. The tl;dr is that luajit 2.0 is broken and shouldn't be used on macos and yet the CI pulled it in anyway. When I originally made the meson build, I did some hacks to workaround this behavior (otherwise the build will fail), but really this shouldn't be supported at all since luajit 2.0 is known to have issues on some versions of macos (https://github.com/mpv-player/mpv/issues/7512). This just makes the CI use lua 5.1 instead and the special logic in meson is removed.
I dunno if we want to add any hard errors or warnings if a user tries to build with luajit 2.0 on mac? It seems like a similar change (https://github.com/mpv-player/mpv/pull/7574) was rejected previously so perhaps not.

use lua 5.1 on macos and cleanup meson

---

video/out/gpu/d3d11_helpers.c

This is to fix a bug where adding the `DXGI_USAGE_UNORDERED_ACCESS` flag breaks rendering in Windows 7.
It feels like a bit of a special case, and it's not clear if the breakage in Windows 7 is due to the OS itself, or bad drivers, but flip-model swapchains in Windows 7 (Platform Update) have been notoriously buggy, so it might be the best solution to just remove `UNORDERED_ACCESS` there.

Don't create DXGI_USAGE_UNORDERED_ACCESS backbuffers in Windows 7

---

audio/out/ao_pipewire.c

Store volume only in mpv format, convert it from spa a soon as possible.
Pass volumes to `pw_stream_set_control` as array.

ao_pipewire: fix ao-volume

---

filters/filter.c
video/decode/vd_lavc.c
video/filter/vf_d3d11vpp.c
video/hwdec.c
video/hwdec.h
video/out/gpu/video.c
video/out/gpu/video.h
video/out/vo_gpu.c

Historically, we have treated hwdec interop loading as a completely
separate step from loading the hwdecs themselves. Some hwdecs need an
interop, and some don't, and users generally configure the exact
hwdec they want, so interops that aren't relevant for that hwdec
shouldn't be loaded to save time and avoid warning/error spam.
The basic approach here is to recognise that interops are tied to
hwdecs by imgfmt. The hwdec outputs some format, and an interop is
needed to get that format to the vo without read back.
So, when we try to load an hwdec, instead of just blindly loading all
interops as we do today, let's pass the imgfmt in and only load
interops that work for that format. If more than one interop is
available for the format, the existing logic (whatever it is) will
continue to be …

vo_gpu: hwdec: load hwdec interops on-demand by default

---

DOCS/man/options.rst
options/options.c
player/playloop.c

The stop-screensaver option is currently limited to a simple yes/no
option. While the no option does always disable mpv trying to stop the
screensaver, yes does not mean the screensaver is always stopped. The
screensaver will be enabled again depending on certain conditions (like
if the player is paused). Simply introduce a new value for this option,
always, which does exactly what the name implies: the screensaver will
always be disabled.
Related issue #9872.

options: add always to stop-screensaver

---

meson.build
player/command.c
video/out/vo.c
video/out/vo.h
video/out/vo_gpu_next.c
wscript

Render subs at the video resolution, rather than the overlay resolution.
Uses the new APIs found in libplacebo 196+, to allow controlling the OSD
resolution even for image-attached overlays.
Also fixes an issue where the overlay state did not get correctly
updated while paused. To avoid regenerating the OSD / flushing the cache
constantly, we keep track of OSD changes and only regenerate the OSD
when the OSD state is expected to change in some way (e.g. resolution
change). This requires introducing a new VOCTRL to inform the VO when
the UPDATE_OSD-tagged options have changed.
Fixes #9744, #9524, #9399 and #9398.
TODO:
(*should* subtitles be rotated along with the video, or not?) …

vo_gpu_next: refactor subtitle rendering
