mpv-player/mpv

video/out/w32_common.c
This makes sure SetCursor isn't called when the window enters menu mode. Using WM_NCHITTEST to check if the mouse was in the client area was probably a mistake, since the mouse can still be within the bounds of the client area when the window menu is open.
=> Windows: Don't hide the cursor when the window menu is open

DOCS/man/vo.rst
Completely overlooked that in the original PR.
=> vo_drm: add missing documentation

video/out/vo.c
commit f1746741dee6000b7fd139e7a10f72aba0674b3b changed the drop
logic to have more slack (drop more frames but less frequent) to prevent
drops due to timing jitter when the clip and screen have similar rates.
however, if the clip has higher rate than the screen (or just high
playback speed), then that policy hurts smoothness since these "chunked
drops" look worse than one frame drop at a time.
this patch restores the old drop logic when the playback frame rate is
higher than ~5% above the screen refresh rate, and solves this issue.
Fixes #1897
=> vo: restore normal frame drops logic on high playback rate

DOCS/man/options.rst
Elaborated on the --no-video option and removed trailing spaces.
=> Man update

DOCS/man/options.rst
=> manpage: --media-title -> --force-media-title

DOCS/man/vo.rst, video/out/gl_video.c
=> vo_opengl: reimplement tscale=oversample

video/out/w32_common.c
use the append to playlist functionality if shift is pressed while dropping
=> w32: shift drag and drop appends

video/filter/vf_vdpaurb.c
Today, vdpaurb will fail if it's used with non-hardware-decoded
content. This created work for the user as they have to explicitly
add or not add it, depending on the content.
As an improvement, we can make vdpaurb pass through any frames
that aren't hardware decoded, so that it can always be present in the
filter chain, if desired.
=> vf_vdpaurb: Pass through non-hardware-decoded content

demux/demux_libarchive.c, player/external_files.c, stream/stream_libarchive.c, stream/stream_libarchive.h
* read volumes from directory using known patterns: .rar, .r00 / .part0001.rar / 7z.001.
* use libarchive client data array for per-volume private data
* add switch, open, close callbacks
* other miscellaneous fixes.
=> add libarchive multivolume support

audio/out/ao_openal.c
=> ao_openal: accommodate more sample formats

video/out/opengl/common.c, video/out/opengl/w32.c
encountered a few edge cases running in a broken opengl system.
=> minor opengl fixes

video/out/opengl/angle.c
ANGLE has EGL_KHR_get_all_proc_addresses now (since google/angle@5565936.)
=> Don't load libGLESv2.dll for ANGLE

osdep/terminal-win.c
This was my bad. Turns out reopen_console_handle() was completely broken.
=> Fix Windows console output with raw stdio functions

video/out/opengl/hwdec_dxva2gldx.c
Sharing off-screen plain surfaces causes Nvidia drivers to crash. This makes the shared surface a rendertarget instead. Untested on AMD and Intel.
Ping @kevmitch.
=> Fix DXVA2 interop on Nvidia

input/ipc-win.c
More details in the commit message. This may or may not be paranoia, depending on how dangerous it is to let anyone read from (but not write to) the IPC pipe. In any case, I think it makes the pipe security closer to how it is on Linux.
Before/after:
Disclaimer: I'm definitely not an expert in Windows security.
=> Disallow world-read access to the IPC pipe on Windows

DOCS/mplayer-changes.rst
=> DOCS/mplayer-changes: document HDR support

video/out/opengl/context_angle.c
This avoids a copy of the video image and lowers vsync jitter. Since there are now two options to add to the window_attribs list, it has been made dynamic.
For me, this lowers ${vsync-jitter} from about 0.015 to about 0.005.
=> Enable DirectComposition in ANGLE

video/out/opengl/context_angle.c
Apparently Chrome does this too. Hopefully ANGLE will expose a better way of doing this in future.
=> Update the ANGLE swapchain with eglPostSubBuffer when the window is resized

video/out/opengl/context_angle.c
Hopefully this will get mpv showing video on all kinds of broken hardware. WARP seems to perform well enough for basic video rendering.
I wonder if ignoring the :sw flag is the best way of making sure mpv falls back to WARP on Windows, or if another way would be better (like maybe adding an opengl-sw preset to the list of VOs in vo.c.)
=> Use ANGLE/WARP if there are no hardware adapters

player/command.c
I wasn't sure about the best way to fix it, but this definitely makes things faster with ~10000 playlist items and mpv_observe_property("playlist").
=> Prevent O(n^2) behaviour for playlist property

video/out/w32_common.c
This should fix --wid embedding.
=> Use Windows hooks to detect when the parent window is resized

video/out/win32/displayconfig.c
Windows 8.1/VirtualBox does this.
=> Treat a DisplayConfig refresh rate of 1 as invalid

osdep/terminal-win.c
This also includes a cleanup/refactor of console input handling that makes it a bit simpler.
=> Support modifier keys in the Windows console

TOOLS/appveyor-install.sh
=> TOOLS/appveyor-install: install uchardet release instead

DOCS/man/osc.rst, player/lua/osc.lua
=> osc: add seekbarstyle=knob

player/lua/ytdl_hook.lua
=> ytdl_hook: sort chapters by time

player/lua/osc.lua
1px to 2px squares.
Also move them away from the seekbar.
=> osc: bottombar/topbar: make chapter markers slightly bigger

video/out/cocoa_common.m
i have a bit more sophisticated branch [here](https://github.com/Akemi/mpv/commits/cocoa_spacefix2). the difference is that the linked branch waits for the space transition animation to finish before releasing the window, whereas the this PR closes the window immediately.
i like the behaviour if this PR better, though i am not too sure if it might break some obscure corner case.
=> cocoa: don't change Space on quit in fullscreen

video/out/cocoa/window.h, video/out/cocoa_common.m
=> cocoa: move updateBorder method to the protocol

audio/out/ao_wasapi.c, audio/out/ao_wasapi.h, audio/out/ao_wasapi_changenotify.c, audio/out/ao_wasapi_utils.c, osdep/windows_utils.h, video/out/opengl/context_dxinterop.c
In preparation for the new ANGLE code, which uses SAFE_RELEASE pretty heavily.
=> Add a COM-specific SAFE_RELEASE macro to windows_utils.h

video/out/cocoa/window.m, video/out/cocoa_common.m
i wrote quite a bit in the commit messages about the changes.
=> Cocoa: Displaylink and screen event improvements

video/out/opengl/context_angle.c
Now it should be easier to tell from the log output which are actually being used.
=> Log the ANGLE device/surface implementation

audio/out/ao.c
=> ao: never set ao->device = ""

player/lua/osc.lua
i don't have much clue about the OSC and how proper this fix it. maybe it will at least start a discussion on how to fix it properly if this gets rejected.
=> osc: fix window dragging with showwindowed=no

player/lua/osc.lua
@Coacher check if this fixes both your issues good enough.
=> osc: refactor osc message scaling

video/out/w32_common.c
Second attempt! The diff is large because I moved reinit_window_state above WndProc.
=> Fix undefined behaviour when toggling fullscreen from a Win32 VO

video/out/w32_common.c
Just a refactoring: It shouldn't change behaviour.
=> Refactor Windows mouse button handling

osdep/macosx_events.m
There is explicit code to handle the libmpv case, but it expects that
a dispatch queue is running. This is not necessarily the case. E.g.
edit the simple.c mpv example not to do any playback and to destroy
the mpv handle immediately. It will freeze on exit, because nothing
will release the mpv_handle.
I'm not sure how this should be fixed, so disable it for now in
library mode.
---
Ideally there is a way to detect whether a dispatch queue is active?
=> Fix deadlock on exit with libmpv on OSX

video/out/w32_common.c
It seems like the only message that can arrive before WM_NCCREATE is WM_GETMINMAXINFO. Both messages are processed before CreateWindowEx returns, so it should be okay to use WM_NCCREATE to pass the vo_w32_state pointer to the window procedure.
=> Drop TLS usage in w32_common.c

video/out/opengl/context_angle.c
mpv works OOTB now in VirtualBox for me.
=> Fix fallback to D3D9 with ANGLE

wscript
=> js: wscript: use pkgconfig for mujs (recently added .pc and 1.0.0 tag)

version.sh
This allows us to detect users who run mpv with custom patches.
=> version.sh: append -dirty if the working tree contains modifications

video/out/w32_common.c
This prevents a glitch if a VOCTRL is dispatched while the user is clicking the titlebar, but not moving the mouse.
I just want to make sure the dispatch queue's wakeup function is only called when dispatching a message between threads. If it's called on the same thread, this will deadlock (but I don't think it does this?)
=> Use sent messages to wake up the Win32 thread

DOCS/man/javascript.rst
this is a commit of international importance
=> manpage: scream about JavaScript for case consistency.

DOCS/man/options.rst, input/input.c, input/input.h, input/keycodes.c, input/keycodes.h, osdep/w32_keyboard.c, osdep/w32_keyboard.h, video/out/w32_common.c
It seems like this was tried before in fc9695e63b5b. Hopefully this approach works better. There are also possible future improvements we could try, like setting up global hotkeys.
Not all the new keys are tested. I'll need to find my MCE remote.
=> Handle media keys on Windows

wscript
regression from 83a9b0bc4840c1bb203c23194c5f07f898999034
=> wscript: fix build of videotoolbox hwaccel for iOS

player/lua/ytdl_hook.lua
Unbreaks segmented DASH with the change in
https://github.com/rg3/youtube-dl/commit/1141e9104 which made each
segment URL only use relative path from fragment_base_url with a
different key.
Waiting before it's in a youtube-dl release before merging to see if there's some change.
=> ytdl_hook: support fragments with relative paths

audio/out/ao_wasapi.c, audio/out/ao_wasapi.h, audio/out/ao_wasapi_utils.c
Some wasapi reoganization to hopefully make things a bit simpler and clearer. Should be no user facing changes.
=> Wasapi cleanup

audio/out/ao_wasapi_utils.c
=> ao_wasapi: remove old comment

video/out/opengl/context_angle.c, video/out/opengl/d3d11_helpers.c, video/out/opengl/d3d11_helpers.h, wscript_build.py
I think I'm happy with this now. Tested on Vista and 8.1 in VirtualBox.
=> Extract non-ANGLE specific D3D11 code into d3d11_helpers.c

options/options.c
Related to the discussion in #4483
=> Increase --monitorpixelaspect range

osdep/io.h
This fixes >2GiB files with at least with API level 21.
See: https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md
for the gritty details.
* Based on libavformat's things, except we do not care about API
versions or NDKs without unistd.h, which contains all sorts of
things that we utilize.
* Redefines lseek to always point to the 64bit version.
* Redefines fseeko to always point to lseek with fileno(f),
as actual fseeko was only added with API level 24 (AKA Android 7).
_"Fuck Android"_
=> osdep/io: add android related bullshit

player/javascript.c, player/lua/osc.lua
=> 1. fix rare osc crash. 2. js fix mp.set_property_{native,number}

DOCS/man/options.rst
Man page: fix typo as per https://github.com/mpv-player/mpv/issues/4913
=> Man page: fix typo

DOCS/compile-windows.md
Hopefully these changes look fine. Ping @wiiaboo.
=> Update DOCS/compile-windows.md for changes to mpv and MSYS2

player/video.c
Commit of international importance.
=> video: fix typo in log message

TOOLS/appveyor-build.sh, TOOLS/appveyor-install.sh, appveyor.yml
The builds take a bit longer, at 20min each, but they work now.
=> Update Appveyor for recent changes and test D3D11/Vulkan

video/out/w32_common.c
For consistency with already implemented shcore.dll function loading in w32->api:
Moved loading of imm32.dll to w32_api_load, and declared pImmDisableIME function pointer in the w32->api struct.
Removed unloading of imm32.dll.
=> w32_common: move imm32.dll function to w32->api struct

Copyright
The file was dropped last week or so.
=> Copyright: remove removed file from GPL list

DOCS/man/lua.rst
=> manpage: add note about properties not immediately showing up

osdep/terminal-unix.c
Fixes #4190
This allows you to use terminal input even if you've piped something
into mpv.
=> Use /dev/tty instead of stdin for terminal input

player/video.c
(why doesn't github copy the damn commit message here)
=> video: add a shitty hack to avoid missing subtitles with vf_sub

options/m_option.c
'help' is a valid value for a lot of mpv options, such as `hwdec` or `vo` for printing available values, so this change makes the output of OPT_CHOICE options like `--video-sync=help` more consistent by not reporting an error about invalid value 'help'.
mpv will still report an error for other invalid values, other than `help`.
Before the change:
-----
````
mpv --video-sync=help
Invalid value for option video-sync: help
Valid values are:
audio
display-resample
display-resample-vdrop
display-resample-desync
display-adrop
display-vdrop
display-desync
desync
Error parsing option video-sync (option parameter could not be parsed)
Setting commandline option --video-sync=help failed.
Exiting... (Fatal error)
````
````
mpv --video-sync=dfhlkdjghkdjfg
Invalid value for option video-sync: …
```
=> options: don't report errors on help value for OPT_CHOICE

osdep/terminal-unix.c
Calling do_deactivate_getch2 before joining the terminal thread could
lead to breakage if the terminal thread got another interation in before
it was signaled to stop.
This also addresses a minor error with the order in which things are
initialized - getch2_poll would previously call tcgetpgrp(tty_in) before
tty_in was initialized, which did not lead to broken behavior, but was
not correct either.
Fixes #5195
=> terminal-unix: fix race condition with tty reset

DOCS/man/javascript.rst
=> Fix typo in javascript.rst (reomve)

.travis.yml, TOOLS/travis-deps
Signed-off-by: Stefano Pigozzi <stefano.pigozzi@gmail.com>
=> travis: stop excluding ffmpeg-git

stream/cache.c, stream/stream_libarchive.c
Stupid consequence of a bunch of horrible libarchive API quirks. In practice, this fixes an initial seek into an archive entry, such as when resuming playback in a 7z file.
Also included is a fix for the cache. This fixes a "soft" endless loop because all stream_libarchive seeks failed, and the cache thread kept retrying.
=> Libarchive seeking fix

DOCS/man/mpv.rst, options/m_option.c
=> options: add -add/-append actions to key/value lists

DOCS/man/ao.rst
=> manpage: fix typo in warning

video/out/d3d11/ra_d3d11.c
See #5293. This is a workaround for an Intel driver bug.
=> Avoid copying staging buffers to cbuffers in ra_d3d11

player/main.c
What the heck. This negated the entire check.
=> main: fix typo

DOCS/man/input.rst, player/loadfile.c, player/lua/ytdl_hook.lua
~~TODO: skip retrying demux if there are no scripts with the hook~~
=> player: add on_load_fail hook

DOCS/man/input.rst, DOCS/man/options.rst, input/cmd_list.c, input/cmd_list.h, options/m_option.h, player/command.c, video/out/opengl/context_android.c
why didn't anyone tell me there was a better way to do this earlier?
@kevmitch @tmm1
=> Refactor the recent android changes

demux/demux.c, player/audio.c, player/loadfile.c, player/playloop.c, stream/cache.c
Each commit touches a different issue.
=> More cache related minor fixes

demux/demux.c
Minor unrelated improvements/fixes.
=> Minor demuxer cache fixes

DOCS/interface-changes.rst, DOCS/man/af.rst, DOCS/man/options.rst, DOCS/man/vo.rst, audio/aconverter.c, audio/aconverter.h, audio/aframe.h, audio/filter/af.c, audio/filter/af.h, audio/filter/af_lavrresample.c, etc/builtin.conf, libmpv/client.h, options/m_config.c, options/m_config.h, options/m_option.h, options/options.c, options/options.h, player/audio.c, player/configfiles.c, video/decode/vd_lavc.c, video/filter/vf.c, video/filter/vf_d3d11vpp.c, video/mp_image_pool.c, video/mp_image_pool.h, video/out/vo_vaapi.c
Random unrelated minor changes (probably better than making 5 separate PRs).
=> Minor changes

player/lua/osc.lua
=> osc: leave only demuxer cache duration and limit its refresh rate

DOCS/man/input.rst, options/m_config.c, options/m_config.h, video/decode/vd_lavc.c, video/filter/vf_convert.c, video/img_format.c, video/img_format.h, video/mp_image.c, video/mp_image_pool.c, video/mp_image_pool.h, video/out/vo.c, video/out/vo_drm.c, video/out/vo_tct.c, video/out/vo_x11.c, video/sws_utils.c, video/sws_utils.h
These commits are part of PR #5401, but contain only minor/harmless things. This is the extent to which I'm fine with splitting this. It's simply an inherently monolithic change.
CC @haasn for the mp_image metadata thing
=> Preparations for PR #5401

osdep/macosx_menubar.m
since #4857 didn't lead to anything and is just stalled. added the trivial changes to add the missing menu items myself.
if i should handle that in different way, let me know.
=> osx: add some more menu bar items as suggested by Apples's HIG

options/m_option.c
This lets script query the value of 'background' and similar properties
=> m_option: add print callback to color type

DOCS/man/input.rst, DOCS/man/mpv.rst, DOCS/man/options.rst, audio/format.c, audio/format.h, audio/out/ao_alsa.c, audio/out/ao_lavc.c, audio/out/ao_openal.c, audio/out/ao_opensles.c, audio/out/ao_oss.c, audio/out/ao_wasapi_utils.c, demux/demux.c, input/cmd_list.c, input/cmd_list.h, libmpv/client.h, libmpv/opengl_cb.h, options/m_option.c, options/m_option.h, player/command.c, stream/stream_lavf.c, video/decode/dec_video.c
Various smaller changes, 2 of them fix open github issues.
=> Random changes

demux/cue.c
If tags like TITLE have the whole parameter in " quotes, strip them.
Also remove the leading whitespace, since even with a single space it
was always included.
Fixes #5462.
=> cue: strip quotes and leading whitespace from tags

video/decode/vd_lavc.c
This is a dataflow issue caused by the filters change. When the fallback
happens, vd_lavc does not return a frame, but also does not accept a new
packet, which confuses lavc_process(). Fix this by immediately retrying
to feed the buffered packet and decode a frame on fallback.
Fixes #5489.
=> vd_lavc: fix recently broken hardware decode fallback

filters/f_decoder_wrapper.c, filters/f_demux_in.c, filters/filter.c
1 real fix, plus 2 trivial commits that change a log message each.
=> Filter fixes

video/decode/vd_lavc.c
Also a regression of the filter change. The new code is more picky about
EOF states, and it turns out the weird delay queue (used with some hwdec
copy back modes only) accidentally dropped an EOF event. It reset the
avctx before the delay queue was drained, which meant it never returned
the expected AVERROR_EOF status code.
=> vd_lavc: fix stall with some uses of --hwdec=copy

video/out/gpu/video.c, video/out/gpu/video.h, video/out/gpu/video_shaders.c
=> More HDR peak detection improvements (and a bug fix)

DOCS/man/javascript.rst, DOCS/man/lua.rst, osdep/getpid.h, player/javascript.c, player/lua.c
implements #5208
someone should probably test the js stuff as I couldn't be bothered to install mujs
(apparently someone implemented this already?)
=> lua+js: Implement utils.getpid()

waftools/detections/compiler_swift.py, waftools/generators/sources.py, wscript_build.py
sry about the problems. hopefully this will be the last fix (of a fix).
=> some more swift related build fixes

video/out/cocoa_cb_common.swift, waftools/checks/custom.py, wscript_build.py
=> cocoa-cb: fix drawing on 10.11 and wrong window size after animation

filters/filter.c, player/command.c, video/out/opengl/hwdec_drmprime_drm.c
One real bug, 2 harmless dead code issues. The other reported defects (8 from 11) were false positives as far as I can tell.
=> Coverity fixes

filters/f_auto_filters.c
Which idiot wrote this code? [Yeah, me.]
---
Fixes e.g. rotation by 45 degrees.
=> video: fix --video-rotate in some cases

osdep/macOS_mpv_helper.swift
=> cocoa-cb: fix invalid framebuffer operation error

TOOLS/dylib-unhell.py
it would be appreciated if someone else could test with both python2 and python3. just to make sure i didn't break something else again.
this fixes #5600 and #3316.
=> osxbundle: fix bundle creation with python3

video/out/cocoa-cb/video_layer.swift, video/out/cocoa-cb/window.swift
=> cocoa-cb: fix two crashes.

DOCS/client-api-changes.rst, input/ipc-unix.c, input/ipc-win.c, libmpv/client.h, libmpv/mpv.def, osdep/macosx_events.m, player/client.c, player/client.h, player/core.h, player/main.c, player/scripting.c
=> Cleanup libmpv handle destruction

video/out/opengl/context_drm_egl.c
Right now the atomic request is alive during the renderloop.
We want it to be alive until the drm egl context is destroyed because some properties
might still be set upon interop close
This patch make the request to be kept created even outside the renderloop.
The context uninit will commit the last request.
=> drm/atomic: ensure request is available until uninit

common/av_common.c, common/av_log.c, filters/f_lavfi.c, video/img_format.c, video/mp_image.c, wscript
=> FFmpeg api changes

DOCS/interface-changes.rst, audio/out/ao_opensles.c
Please see the commit messages for details.
=> ao_opensles: buffer fixes for Android O

video/out/gpu/video.c
Now that the feature depends on multiple features, log all of their states in the message.
=> gpu/video: HDR peak computation improvements

player/lua/stats.lua
=> stats: show sample format of audio track

video/out/wayland_common.c, video/out/wayland_common.h, waftools/checks/custom.py
Window size should not change if the window has been maximized or tiled.
=> wayland_common: fix maximized state

osdep/macOS_mpv_helper.swift, osdep/macOS_swift_bridge.h, osdep/macosx_application.h, osdep/macosx_application.m, osdep/macosx_application_objc.h, video/out/cocoa-cb/events_view.swift, video/out/cocoa-cb/video_layer.swift, video/out/cocoa-cb/window.swift, video/out/cocoa_cb_common.swift, video/out/libmpv.h, video/out/vo_libmpv.c
second attempt to remove the pre-allocation and should supersede #5644.
=> cocoa-cb: remove pre-allocation second attempt

stream/stream_file.c, stream/stream_smb.c
=> Smbclient lock all

player/lua/ytdl_hook.lua
=> ytdl_hook: always load ytdl:// links with ytdl_hook first

video/out/gpu/video.c
When using multiple compute shaders as part of the same pass, there can
be a conflict in the block sizes. In the problematic case, the HDR
detection shader can collide with the polar sampling shader. In this
case, the solution is clear - the passes that can handle any size should
"give in" and not overwrite the block sizes.
Fixes #6083.
=> vo_gpu: avoid overwriting compute shader block sizes

video/out/gpu/video_shaders.c
see commit description
I'm not a graphics guy, so this might be the worst idea you've ever seen
~~also `gl_sc_is_gles()` feels like a terrible hack~~
@haasn
=> vo_gpu: adjust PRNG variant used by GL shaders

video/out/gpu/shader_cache.c, video/out/gpu/utils.c
=> Fix a minor edge case related to vulkan push constant packing

README.md
This fixes the line under the header, creates a title header, and
slightly improves list formatting. Minor change but it was annoying me.
=> Improve readme aesthetics.

demux/demux.c, demux/demux_lavf.c, misc/rendezvous.c, player/lua/stats.lua, stream/stream_libarchive.c
These are probably the least controversial or hard-to-review/test changes from his fork.
The EDL mp4 DASH hack thing should be tested but otherwise seems rather straightforward.
v4l2, stream_libarchive and the EDL thing are something that could be back-ported.
=> Minor improvements from wm4's fork

common/encode_lavc.c
Since this function is called with packets on the stack, trying to free
them makes no sense. Instead, it should unref (which is what
`av_interleaved_write_frame` does anyway, rather than freeing).
Also, the calling code tried unreffing the packet a second time, even
after it was "freed" by the callee in the failure case - and after
ownership was taken over by `av_interleaved_write_frame` in the
successful case. Both of these cases were wrong.
agreed to it before, leave the following …
=> encode: fix AVPacket deinitialization logic

video/out/cocoa-cb/window.swift
a small error on my side. didn't notice since i don't use that feature that often.
=> cocoa-cb: fix side by side Split View

video/out/cocoa-cb/window.swift
i can move the CustomTtitleBar into its own file, though i think that is a bit of an overkill and the title bar is part of the window anyway.
on 10.10 and earlier a different key was used for the minmize/zoom setting, so i check both.
Fixes #6223
=> cocoa-cb: fix double clicking the title bar

video/out/opengl/hwdec_cuda.c
Currently, the error paths in init() are a bit confusing, and we can
up trying to pop the current context when there is no context, which
leads to distracting error messages.
I also added an explicit path to return early if the GPU backend is
not OpenGL or Vulkan. It's pointless to do any other cuda init
after that point. (Of course, someone could write more interops.)
Fixes #6256
=> vo_gpu: hwdec_cuda: Clean up init() error handling

DOCS/man/options.rst, video/out/gpu/lcms.c
=> lcms: allow infinite contrast

video/out/gpu/user_shaders.c, video/out/gpu/user_shaders.h, video/out/gpu/video.c
=> Some user shader support improvement

video/out/vo_libmpv.c
=> vo_libmpv: fix null pointer dereference

player/playloop.c
For easier understanding of seek behavior
=> player: show restart position

osdep/macOS_mpv_helper.swift, video/out/cocoa-cb/window.swift, video/out/cocoa_cb_common.swift
nothing major. i will remove all the forced unwrappings on one of theses days.
fixes #6489
=> cocoa-cb: fixes related to minimising

osdep/macOS_mpv_helper.swift, video/out/cocoa-cb/video_layer.swift
just a dumb oversight on my part.
=> cocoa-cb: synchronise the flush with the render

video/out/cocoa-cb/events_view.swift
mostly to make it more consistent with what can be dragged and dropped on the Dock icon.
the validation of the strings can probably be done in a better way. i am open for suggestions.
=> cocoa-cb: add support for dragging certain strings onto the window

video/out/cocoa-cb/video_layer.swift
i meant to do that for a long time now since i was quite bothered by it. i think the pixel format creation is now a lot clearer and easier to understand.
=> cocoa-cb: simplify CGL pixel format creation

DOCS/man/input.rst
=> input docs: seek +exact clarification

version.sh
This is a trivial change, so I am not certain if the license statement is needed, but I will leave it anyway.
=> version.sh: update MPVCOPYRIGHT to include 2019

video/out/opengl/context_drm_egl.c
This implements presentation feedback for context_drm_egl using the
values that get fed to the page flip handler.
Might as well put this up since we have support this in context_glx since the wm4 merge.
=> context_drm_egl: Add support for presentation feedback

video/out/wayland_common.c
Probably the same issue as #6732
=> wayland: fix segfault on uninit

video/out/gpu/video.c
=> vo_gpu: fix taking screenshots of rotated videos

video/out/d3d11/ra_d3d11.c
Whoops, somehow I got the idea that compound literals were function-scoped. I think this fixes #6775, since I had the same missing OSD without the fix.
=> Fix storage lifetime of compound literals in ra_d3d11.c

.travis.yml, ci/build-macos.sh, ci/get_ffmpeg.sh
Apparently now it kind of works. Yayifications.
=> Travis: Rework scripts to re-enable macOS CI builds

audio/out/ao_opensles.c
thanks to @xyzz for pointing this out
=> ao_opensles: fix delayed audio

DOCS/man/options.rst, DOCS/man/vo.rst, player/screenshot.c, player/screenshot.h, video/image_loader.c, video/image_writer.c, video/image_writer.h
=> WebP screenshot support

sub/lavc_conv.c, sub/sd.h, sub/sd_ass.c
Additionally, start using UINT32_MAX subtitle end times as "unknown/show until following".
=> sub: switch to the newer subtitle decoder output format

player/client.c
When update_prop() successfully fetched a changed property value, it
set prop->changed to true to indicate the success.
mark_property_changed() also always set
prop->changed to true and additionally prop->need_new_value to true
This is the case since 6ac0ef78
If the observed property changes every frame and then due to timing
the next mark_property_changed() is called before
gen_property_change_event() and therefore directly after update_prop(),
prop->need_new_value was again true and indicated that a new value
has to be retrieved with update_prop(). As a result the event for the
last successful update_prop() was never triggered. This meant that
a property change event was never generated for frame-based properties
only for properties that were observed with MPV_FORMAT_NONE or when the …
=> client API: fix missing property change events after property updates

video/out/opengl/context_drm_egl.c
Check if eglGetPlatformDisplayEXT is available and try to
use it to obtain the display connection. Fall back to eglGetDisplay
if eglGetPlatformDisplayEXT is not available or failing.
From PR #5992
=> context_drm_egl: Use eglGetPlatformDisplayEXT if available

DOCS/man/ao.rst, audio/out/ao_pulse.c
=> ao_pulse: add --pulse-allow-suspended

video/out/vo_sdl.c
=> vo_sdl: Only create the SDL window once

DOCS/interface-changes.rst, DOCS/man/options.rst, demux/demux_cue.c, options/options.c, options/options.h
=> demux_cue: auto-detect CUE sheet charset

input/event.c
do not outright err and quit the player for this
=> input: ignore empty lines on drag-drop mime data

player/loadfile.c
=> player: use track title if exists instead of filename

video/out/wayland_common.c
This allows compositors to set the theme and size from user
configuration.
=> wayland: read xcursor theme from XCURSOR_* env

wscript_build.py
some optimisations for building.
=> build: don't add swift object when swift disabled

DOCS/man/input.rst, player/command.c, sub/dec_sub.c, sub/dec_sub.h, sub/sd.h, sub/sd_ass.c, sub/sd_lavc.c, test/subtimes.js
I'm not very familiar with the subtitles code, please review with attention :)
=> command: add sub-start & sub-end properties

video/out/d3d11/context.c
This adds support for get_vsync in the d3d11 backend. It's pretty similar to the GLX/EGL stuff, but there are a few differences, which are outlined in the commit message.
One concern I have about merging this is that it might have to be conditionally disabled when exclusive fullscreen mode is added in #6329, because with ``--d3d11-exclusive-fs`` and ``--no-d3d11-flip``, vsync-jitter is actually higher with feedback than without it, and the variation in frame times is so high that it can cause display-sync to get disabled. I don't think this is because the data is bad (I'm pretty sure the actual stddev of frame times is lower,) but I think it's a consequence of how get_vsync works at the moment.
Currently, all the get_vsync backends (glx, egl, drm and now d3d11) use the difference between …
=> Add support for D3D11 presentation feedback

osdep/macosx_menubar.m
this was requested a few times before.
=> osx: add Open Playlist menu bar item

DOCS/man/options.rst, osdep/macOS_mpv_helper.swift, osdep/macOS_swift_compat.swift, osdep/macosx_application.h, osdep/macosx_application.m, video/out/cocoa-cb/video_layer.swift
=> cocoa-cb: add support for 10bit opengl rendering

TOOLS/lua/autoload.lua
Regarding the discussion in https://github.com/occivink/mpv-image-viewer/issues/5
we concluded, that using autoload should result in loading all of the media files in the directory, not just those listed in current EXTENSIONS Set.
Specifically image files (png,jpg,jpeg,tiff,gif,webp,bmp,svg and more) are in scope just as audio files, given that autoload.lua is not limited to video files.
I'm not lua programmer, but I've managed to do something that works in my environments
If allowing all file types right away would be too much of a hassle for the project, i suggest changing default option images to false.
=> autoload.lua Configurable extension types

player/lua/ytdl_hook.lua
Some failures by youtube-dl prompt the user to submit a bug report. If such a failure occurs, we can compare youtube-dl's version to the current calendar date to see how old it is. We don't make this check on every youtube-dl failure, as failing to extract an URL is quite common, and waiting for a second blocking python interpreter startup for every such case would be a bit unpleasant.
Here the assumption is made that any youtube-dl version older than 3 months is probably severely out of date. Users will be warned about this.
We also output the trimmed stderr of youtube-dl with msg.error, as this appeared to have been the behaviour of utils.subprocess without stderr capturing. Since this uses mp.command_native now, we'll have to do this ourselves where appropriate.
=> ytdl_hook: check youtube-dl version if it breaks

player/loadfile.c
Since a track may not be selected twice, it makes sense e.g. for
secondary subtitles to select the next best match and avoid the
duplicate selection.
This allows for example `--slang=en,ja --secondary-sid=auto` to select
'en' as primary and 'ja' as secondary without needing to know the actual
sid for 'ja'.
There might a more elegant solution, I'm open to suggestions.
=> player: avoid duplicate track auto selection

DOCS/man/mpv.rst, etc/input.conf, video/out/vo_sdl.c
=> vo_sdl: Improve mouse input

player/lua/osc.lua
=> osc: calculate osc_geo position after aspect correction

player/javascript/defaults.js, player/lua/defaults.lua
Fix lua complex binding `key_name `, and match in js too.
=> Js complex key name

TOOLS/dylib-unhell.py
Instead of traversing across leafs() which can lead to an infinite loop issue with cross-linked libraries, apply the set() function to the dictionary created by libraries() to create a set (libs_set) without duplicates.
Remove binary from libs_set so that a duplicate of the binary is not added to the libs directory.
Iterate over libs_set to bundle dylibs while using the dictionary (libs_dict) to determine which install_names to change.
I tested this on Mac OS 10.14 with both python 2.7.16 and 3.8.0. Before this edit, I experienced an infinite loop issue because I have freetype and harfbuzz crosslinked. After this edit, dylib-unhell.py worked and exited normally.
I offer these changes into the public domain so they can be used for any purpose whatsoever.
=> dylib-unhell.py: simplify process_libraries() to eliminate leafs()

etc/_mpv.zsh
=> zsh completion: actually make pcre optional

osdep/macos/libmpv_helper.swift, osdep/macos/mpv_helper.swift, osdep/macos/swift_extensions.swift, osdep/macosx_application.m, osdep/macosx_application_objc.h, video/out/cocoa-cb/window.swift, video/out/cocoa_cb_common.swift
this should take care of the removal of the old opts retrieval via the vo struct and also updated tp the new option handling.
=> cocoa-cb: use m_config_cache and new VOCTRL for option handling, add new options and update old ones

player/command.c
For example, when a user switches the aspect-ratio display `16:9`
instead of `1.778` and `Original` instead of `-1`.
This fix is somewhat hacky but necessary and guidance on how to unhack
it would be greatly appreciated.
=> [RFC] ui: fix confusing displayed aspect-ratio

osdep/macosx_application.m, wscript
some small oversights on my side.
=> build: fix build with disabled swift and Media Player

DOCS/man/options.rst
The text here has become somewhat outdated over the years, and it's
worth updating to reflect the current situation.
=> manpage: update discussion of nvidia hardware acceleration

etc/mpv.bash-completion, wscript, wscript_build.py
While we've had a zsh completion script for a while, we haven't had
one for bash. This one is reasonably comprehensive, although there are
improvements one could imagine for certain options.
=> bash completion: add initial implementation of bash completion

.travis.yml, osdep/macosx_application.h, osdep/macosx_application.m, player/lua/console.lua, video/out/cocoa-cb/video_layer.swift, video/out/cocoa_cb_common.swift, video/out/opengl/context_cocoa.c
for testing in issue #7272 and #6874
=> cocoa-cb: several small bug fixes + travis notification change

video/out/cocoa-cb/events_view.swift, video/out/cocoa-cb/window.swift
=> cocoa-cb: add pinch to resize window gesture

video/out/w32_common.c
Basic functionality seems to work, but this isn't ready for merge yet since there are a few bugs:
- Maximizing, entering fullscreen, then un-maximizing gets the window into a bad state. This should probably be fixed by manually setting the maximized state when leaving fullscreen, or using something like SetWindowPlacement to restore the window bounds and the maximized state at the same time.
- Restoring a minimized window seems to move it to the back of the z-order (???)
=> Implement writable window-minimized and window-maximized properties for Windows

video/out/drm_atomic.c
On some platforms the ZPOS property might exist, but be immutable.
This is at least the case on Intel Sandy Bridge since Linux kernel
5.5.0. Trying to set an immutable property will cause.
drmModeAtomicCommit to fail with -EINVAL.
On other platforms we might want to set ZPOS to tweak the layering of
planes.
To reconcile these two, simply have drm_object_set_property check if a
property is immutable before attempting to add it to the atomic
commit, instead returning an error code (which is, as previously,
ignored in the case of ZPOS as we don't strictly need it)
=> drm_atomic: do not set immutable properties

player/lua/options.lua, player/lua/stats.lua
also contains #7401 since the submitter apparently gave up
=> Fix two bugs

.github/ISSUE_TEMPLATE/2_bug_report_macos.md, DOCS/man/options.rst, TOOLS/osxbundle/mpv.app/Contents/Resources/mpv.conf, osdep/macosx_application.m, osdep/macosx_menubar.m
i only activated logging for the bundle for now. i am not sure if any other pseudo-gui should do the same?
=> mac: rework bundle logging

video/out/cocoa-cb/events_view.swift, video/out/cocoa-cb/window.swift, video/out/cocoa_cb_common.swift
i also fixed a small typo in the word cursor.
for testing in #6886. bundle can be downloaded here https://0x0.st/izZ9.zip
=> cocoa-cb: simplify cursor hiding and make it less greedy

.github/ISSUE_TEMPLATE/2_bug_report_linux.md, .github/ISSUE_TEMPLATE/2_bug_report_macos.md, .github/ISSUE_TEMPLATE/2_bug_report_windows.md, .github/ISSUE_TEMPLATE/3_bug_report.md, .github/ISSUE_TEMPLATE/config.yml
i thought it might be good to ask the user to reproduce the issue with --no-config and find the options that causes the problem first? since i find myself often asking about that.
also fix a dumb typo.
=> github: ask users to first reproduce the issue with --no-config

video/out/wayland_common.c
Fixes #7441. Just set screenrc to be equal to current_output's geometry.
Also remove some pointless/extra variables and print a warning/fallback
to screen 0 if a bad id is passed to --fs-screen.
=> wayland: fix autofit and rotating issues

video/out/opengl/common.c
=> OpenGL: Also detect softpipe as a software driver

TOOLS/matroska.py, TOOLS/osxbundle.py, TOOLS/stats-conv.py, waftools/checks/generic.py, waftools/clang_compilation_database.py, waftools/dependencies.py, waftools/detections/compiler.py, waftools/detections/compiler_swift.py, waftools/features.py
previous pr https://github.com/mpv-player/mpv/pull/7354
=> *.py: fix some format issues in python codes, such as indent, new blank line

video/out/wayland_common.c
Previously if the --fs-screen option was set, it would only use the
screen if mpv was launched with --fs and only on startup. During
runtime, the toggle would ignore it. Rework the logic here so that mpv's
fullscreen always uses --fs-screen if it is set. Additionally, cleanup
some unneeded cruft in vo_wayland_reconfig and make find_output more
useful.
=> wayland: always use the fs-screen id for fs

video/out/android_common.c
these jni helpers were introduced in #5589
=> re-use jni helpers in vo_android_init

player/lua.c
TODO:
- Make the talloc ctx a C argument of the autofree script_* functions
so that it's enforced at the C level and also these functions won't
need to call mp_lua_PITA to get the ctx.
- Remove the (now) redundant talloc_free_children at these functions.
- Add destructors for resources which are currently not auto-freed but
they should be, mpv_free_node_content at some places, close_dir at
script_readdir, etc.
=> lua: autofree wrapper instead of the PITA thingy

player/command.c
Edition title is already exposed in demux_edition, it was just never
added to the display. If no edition title exists it will fall back
to the edition number.
=> command: print edition title to OSD when cycling

player/lua/stats.lua
same as #7621 but this time I didn't fuck up the commits.
=> Add Edition information to stats.lua 2

video/out/d3d11/context.c
The current presentation feedback code was only designed to be used with flip model swapchains. Now that we support exclusive fullscreen, it could accidentally be used with bitblt model swapchains. The values that GetFrameStatistics returns in this mode are completely different and it's not clear they're useful at all for estimating latency, so just disable presentation feedback instead.
=> Only use DXGI presentation feedback with flip model swapchains

DOCS/man/stats.rst, player/lua/stats.lua
Code contributed by @avih with only minor modifications to comments by
me.
In case anyone wants to test this/comment prior to merging. Will test it myself in the evening and merge if no objections are raised in the meantime.
=> stats: UP/DOWN scrolling on page 2 (frame stats)

.travis.yml, ci/build-freebsd.sh
TravisCI [supports](https://github.com/travis-ci/travis-build/pulls?q=is%3Apr+freebsd+is%3Aclosed) FreeBSD nowadays. Let's see how well it works.
=> Add FreeBSD to CI

osdep/terminal-win.c
This adds OSC sequence parsing and the 'Change Window Title' OSC command to terminal-win.c's terminal parser.
=> Support --term-title in Windows 8.1 and below

TOOLS/lua/autocrop.lua
autocrop can be real auto now. by `script-opts-append=autocrop-auto=yes`.
=> TOOLS/lua/autocrop.lua: automatically crop at startup

.travis.yml, ci/build-mingw64.sh
* replace lua with luajit because it provides a pkgconfig file
* add shaderc + spirv-cross so d3d11 can be enabled
uncached builds now take [~25 minutes](https://travis-ci.org/github/sfan5/mpv/jobs/703645964)
=> ci: add d3d11 to mingw build

video/out/wayland_common.c
The read of the wayland display fd in vo_wayland_wait_events was
incorrect and technically vulnerable to race conditions. The correct
usage as per the client api is to use `wl_display_prepare_read` as well as
`wl_display_read_events`.
=> wayland: fix a potential race in wait_events

video/out/wayland_common.c
This is mostly a theoretical change (I had to hardcode an error in wlroots to actually test this), but it should be worthwhile. Before this change, the error I had wlroots throw back at mpv leads to a deadlock because of `wl_display_roundtrip`. After this change, mpv correctly errors out and quits.
Basically, `wl_display_dispatch` sucks (for mpv anyway) so we shouldn't use it. Any calls to `wl_display_roundtrip` also need to be handled with care since it can internally call `wl_display_dispatch` (we do need roundtrip). The tricky part is that `wl_display_roundtrip` is used as part of the frame wait. I adjusted how it is handled in a way I think makes sense (see the commit message for a longer explanation). Of course, touching that part of wayland_common is always dangerous since it plays …
=> wayland: avoid potential deadlocks

DOCS/man/input.rst, player/command.c
=> command: add property track-list/N/selected-order

.travis.yml
such a pain in the ass. just for testing now.
=> travis: fix macOS 10.12 legacy build

DOCS/man/options.rst, options/options.c, options/options.h, video/out/cocoa_cb_common.swift, video/out/mac/common.swift
only implemented for macOS for now. i am not sure how feasible it is on other platforms?
=> mac: add an option to prevent focusing of the window

options/options.c
=> options: fix --cover-art-file typo

.travis.yml
=> ci/travis: bump Ubuntu distro version to focal (20.04)

DOCS/man/mpv.rst, etc/input.conf
=> Add default keybindings for sub-scale

video/out/mac/common.swift
i missed this in my first focus related commit.
checking if it builds everywhere properly.
=> mac: make focus property observable

DOCS/man/input.rst
Fixes #8077. I don't know about `get_property profile-list` not returning any response since it works for me, but I think that's a separate issue anyway.
Tell me if you want the commits squashed.
=> manpage: several fixes

video/out/vo_sixel.c
Implement draw_frame instead of draw_image.
=> vo_sixel: draw_frame switch

.travis.yml
=> [WIP] travis: macOS test

video/out/gpu/video.c
=> vo_gpu: revert 8a09299 and conditionally clear framebuffer again

video/out/wayland_common.c
See the commit message for a long winded explanation.
Ideally, this commit is more correct theoretically (in wayland-world anyway), gives more features in niche situations, and hopefully doesn't break something. This touches/re-arranges a lot of stuff in a non-obvious way though so it's totally possible there's a regression hidden in here.
However, you can now drag an mpv window across monitors with different resolutions and/or scaling with autofit/geometry options and it'll update correctly per monitor. Kind of cool. There are other subtle bugs related to output picking that should be fixed as well.
Needs more testing of course.
=> wayland: handle multiple outputs more correctly

TOOLS/appveyor-install.sh
Apparently this got added to MSYS2 in September.
=> Use MSYS2 shaderc package in Appveyor

video/out/mac/title_bar.swift, video/out/mac/window.swift
=> mac: fix a window positioning bug when exiting fullscreen

TOOLS/umpv
=> umpv: remove unused imports 

DOCS/man/options.rst, filters/f_auto_filters.c, filters/f_auto_filters.h
Part 1 of "look how well it performs, then start cleaning up the
old one."
=> filters/auto_filters: switch from scaletempo to scaletempo2

video/out/cocoa_cb_common.swift, video/out/mac/window.swift
not really nice, but whatever apple breaks.
=> mac: fix traditional fullscreen on macOS 11

TOOLS/umpv
Instead of list. potential memory savings for many files.
=> umpv: Use generator expression for files

video/out/wayland_common.c
The wayland output listener can update whenever something about the
output changes (resolution, scale). Currently, the mpv VO updates
correctly when the refresh rate changes, but changes of both scale and
resolution were not considered. This causes a bug in certain cases like
the mouse surface not being shown at certain scale factors due to the
cursor scale not being updated correctly. Also autofit type options
would not update if the resolution changes.
To fix this, we must always reset the window geometry and wl scaling
whenever the output event occurs on wl->current_output. There is no way
to know precisely what changed from the previous state, so all of the
parameters must be reset and then resized.
=> wayland: update geometry + cursor on output event

demux/demux_lavf.c
this fix  https://github.com/mpv-player/mpv/issues/8713,  make asan and valgrind happy.
=> demux_lavf: fix minor memory leaks 

video/out/mac/common.swift
changes of https://github.com/mpv-player/mpv/commit/af26402 made the geometry calculation to take the origin into account. the origin is not screen relative but relative to the main screen. the rest of the code expects screen relative origins. this would place windows, when not on the main screen, out of the screen bounds.
slightly refactor the geometry calculation and make it a bit more comprehensible.
=> mac: fix window geometry calculation on secondary screens

.github/workflows/build.yml, .travis.yml, TOOLS/travis-rebuild-website
not sure if we want this but it's finished and works so here's the PR
(alternative to #8817 essentially)
@JEEB
=> ci: Move MinGW jobs to Github actions

video/out/opengl/context_wayland.c, video/out/vo_wlshm.c, video/out/vulkan/context_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h
Should fix #8851. @focus64, can you confirm?
=>  wayland: shuffle around the render loop again 

DOCS/man/options.rst, options/options.c, player/external_files.c
=> player: load cover art with the media filename

DOCS/man/input.rst, DOCS/man/options.rst
--cover-art-auto affects rescan-external-files, and --autoload-files
affects cover art.
=> manpage: mention cover-art-auto

player/lua/ytdl_hook.lua
ytdl_hook handles JSON parsing errors in a block separate from its normal error handling, which skips the logging of stderr and thus loses any error messages from youtube-dl. I've moved the parsing step to before the main error-handling block and now handle parsing errors inside that block, meaning they're now logged alongside youtube-dl's stderr.
In certain cases, such as when using the yt-dlp fork of youtube-dl, an error would result in output of the word "null", which `utils.parse_json` would parse into a `nil`, which was then incorrectly treated as a parsing error, leading to a crash when attempting to concatenate the `nil` error string into a log message: 
```
[ytdl_hook] stack traceback:
[ytdl_hook] 	@ytdl_hook.lua:971: in function 'fn'
[ytdl_hook] 	mp.defaults:579: in function …
```
=> ytdl_hook: improve handling of json parsing errors

video/out/wayland_common.c, video/out/wayland_common.h
Another day, another wayland refactor. Here for testing (gotta setup multi monitors and all that later).
=> wayland: refactor surface scaling

DOCS/man/input.rst, player/command.c
=> player: add append-play flag to loadlist

player/lua/stats.lua
mpv has two methods to display output from text input:
- show-text (scripting: mp.osd_message) has ass disabled by default
(escaped), and the property osd-ass-cc can control escaping.
- osd-overlay (scripting: mp.set_osd_ass or mp.create_osd_overlay)
has ass enabled (unescaped), and osd-ass-cc is NOT supported.
By default, stats.lua uses mp.osd_message which does support escaping.
That's persistent_overlay=no.
When using persistent_overlay=yes then mp.set_osd_ass is used.
Due to this, the no_ASS(..) function - which is supposed to escape
ass, simply returned its input unmodified when persistent_overlay
is enabled.
This is not a new issue, and the filters on page 1 use no_ASS() to no
avail in persistent mode, however, this content (filter name and value
strings) rarely actually needs …
=> stats.lua: fix ass-escape while persistent_overlay=yes

player/lua/stats.lua
Previously we assumed the key-name string occupies strlen(name) cells,
now we count codepoints instead. We err by at most one cell - if the
key-name codepoint is double-width, vs up to three cells previously.
Also, if the key name was in a right-to-left language, then previously
the name/command were swapped visually. Now we inject a left-to-right
marker before the name to ensure direction.
A bit more details at the commit message.
=> stats.lua: page 4 (keys): better alignment of non-ascii keys

player/lua/stats.lua
This groups current-window-scale under window instead of current.
=> stats.lua: page 4 (keys): group current-window-scale under window

video/out/vo_rpi.c
Previous code was removed in 59cdfe50b2. This caused the OSD layer to be
not resized along with the video layer.
=> Fix vo_rpi fullscreen handling

player/lua/stats.lua
=> Typo lavfi-complex

video/out/vo_tct.c
Using `fwrite` on non-windows platforms yields a great performance increase.
=>  vo_tct: optimize print function on non-windows platforms 

etc/input.conf
These will be shown in the new keybinding list.
=> input.conf: add comments

video/out/wayland_common.c, video/out/wayland_common.h
Not sure if I want this. Leaning towards yes at the moment.
=> wayland: further xdg-decoration/border refinements

video/out/placebo/ra_pl.c
Upstream libplacebo got refactored to use byte-sized strides rather than
texel-sized strides. This commit makes mpv's ra_pl wrapper take
advantage of that, rather than forcing a stride-fixing memcpy.
Note that, technically, we would still need a stride fixing memcpy in
cases when the true stride is not a multiple of the format's texel
*alignment*, however this is a much rarer case and extremely unlikely to
occur in practice, since all relevant formats use power-of-two texel
alignments.
=> vo_gpu: libplacebo: simplify tex transfers for libplacebo 168+

video/out/opengl/context_drm_egl.c, video/out/opengl/context_dxinterop.c, video/out/opengl/context_glx.c, video/out/opengl/context_wayland.c, video/out/opengl/context_win.c, video/out/opengl/context_x11egl.c, video/out/opengl/egl_helpers.c, video/out/opengl/egl_helpers.h, video/out/opengl/hwdec_d3d11egl.c, video/out/opengl/hwdec_dxva2egl.c
fixes what was noted here https://github.com/mpv-player/mpv/pull/9434#issuecomment-968058589 plus all the cleanups I thought of on the way
~~Wayland change not tested but I bet it works~~ (confirmed)
=> eglCreatePlatformWindowSurface(EXT) and other stuff

video/out/vo_gpu_next.c
This almost perfectly recreates the semantics of --vo=gpu, i.e.:
- still frames are never interpolated
- non-repeated frames bypass single frame cache
The only difference is that libplacebo doesn't do a cache/blit on the
full output image, but rather it re-runs the last rendering step. This
has some advantages and some drawbacks. The most notable advantage is
that it also allows re-using the image contents when the only thing that
changes is the OSD (whereas `--vo=gpu` would force a full re-render for
that). The most notable drawback is that it also implies going through
the dithering and output LUT logic on redraws. All in all, I think this
is a pretty good trade-off in favor of `--vo=gpu-next`.
Fully fixes the last remaining performance difference in #9430.
=> vo_gpu_next: simplify and improve frame redrawing logic

video/out/vo_gpu_next.c
Adding vsync_offset to the pts in pl_queue_update actually messes up
frame timings if one isn't using interpolation. The easiest way to see
this is to have the monitor's refresh rate at an integer multiple of a
video during a panning shot (classic case). There will be very visible
judder/stutter in this case that does not happen in vo_gpu. The cause of
this is the addition of the extra vsync_offset. Just match the semantics
of vo_gpu where this is only used when interpolating.
=> vo_gpu_next: fix timings without interpolation

video/out/wayland_common.c
A read can be prepared on the wayland display FD that is never actually
read. This occurs when events are triggered on other FDs in the fd set.
This change cancels a prepared read if poll reported no events for it.
This fixes some hangs due to how nvidia's EGL implementation polls on
the wayland fd unlike mesa implementations. It is based on nvidia's
proposed fix for qt's similar message pump in
https://codereview.qt-project.org/c/qt/qtwayland/+/373473
Testing this locally with gnome-shell it resolves issues where mpv
would only update once every second or so if nvidia's egl-wayland
implementation was loaded. Unfortunately it doesnt solve wayland
output not working on nvidia drivers.
Signed-off-by: Kurt Kartaltepe <kkartaltepe@gmail.com>
=> wayland: cancel prepared reads when no events

video/out/hwdec/hwdec_vaapi_gl.c
This is a bit ugly, we could decompose it.
=> vo_gpu: hwdec_vaapi: avoid drm_fourcc.h dependency

video/out/vo_gpu_next.c
Somewhat annoying but still relatively straightforward. There are
several ways to approach this, but I settled on reusing the pl_queue as
a cheap way to get access to the currently mapped frame. This saves us
from having to process `vo_frame` at all, and also avoids any overhead
from re-uploading the same frame twice.
(However maybe there's some circumstance in which `vo_frame` needs to be
queried/updated first, to get a screenshot of the correct frame? I'm not
sure.)
I also had the option of going with either pl_render_image() on the
extract pl_frame, or just calling pl_render_image_mix directly on it. I
went for the latter, because in the optimal case, this allows the
rendered frame to be directly retrieved from the cache, actually
entirely avoiding any sort of recompute overhead. This …
=> vo_gpu_next: implement VOCTRL_SCREENSHOT 

DOCS/interface-changes.rst, DOCS/man/options.rst, meson.build, video/out/gpu/video.c, video/out/gpu/video.h, video/out/gpu/video_shaders.c, video/out/placebo/utils.c, video/out/placebo/utils.h, video/out/vo_gpu_next.c
https://code.videolan.org/videolan/libplacebo/-/merge_requests/212
=> Update for new libplacebo tone mapping / colorspace refactor

meson.build, player/playloop.c
=> Misc fixes

video/out/wayland_common.c
See the commit messages for details. Going to test this for a bit before I merge it.
=> wayland: actually handle 0x0 resizes correctly

video/out/wayland_common.c
Commit 1 fixes
https://user-images.githubusercontent.com/1882250/152243424-d8685ef2-d175-4d06-a3d8-6da52c167a8e.mp4
Commit 2 fixes
https://user-images.githubusercontent.com/1882250/152243454-2b2b54e6-61f4-40bf-a4a6-0d3e75813101.mp4
=> wayland vo: various fixes for paused rendering

video/out/gpu_next/context.c
Functions to receive the underlying vulkan,gl,d3d11 structure were
added in libplacebo version 4.182. Our current requirement for
gpu-next is 4.190, and thus we can freely utilize these helper
functions.
This conveniently also lets us get rid of related compiler warnings
about unused variables in case of opengl and d3d11 being disabled
in mpv/libplacebo.
=> vo_gpu_next/context: receive underlying API structs from libplacebo

video/out/wayland_common.c
Here for testing. See the commit for details.
=> wayland: partially fix drag and drop handling

video/decode/vd_lavc.c
Previously, when mpv was invoked with unsupported hwdec value, such
as --hwdec=foobar, there was no indication that it doesn't exist.
The reason it's not validated during options parsing is that the name
is only evaluated when selecting hwdec for actual decoding, by
matching it against runtime list of names from ffmpeg.
Additionally, when selecting hwdec for decoding, matching the name
came after filtering by codec, hence overall never-matched-name did
not necessarily indicate it's unsupported (doesn't exist at all).
Now we check the name before filtering by codec, and when done,
warn if no hwdec with that name exists at all.
This means that an unsupported name will now generate such warning
whenever we try to choose a hwdec, i.e. possibly more than once.
It's much better than no …
=> hwdec: warn on unsupported hwdec option value

video/out/vo_gpu_next.c
So, turns out the approach in 7f67a553f doesn't work for all codecs. In
particular, sometimes lavc will internally allocate a new AVBuffer that
just points at the old AVBuffer but has a different opaque field for
some reason. In these cases, the DR metadata doesn't survive the
round-trip through libavcodec.
I explored several alternative ways of solving this problem, including
adding new mp_image fields, but in the end none of them survived the
round-trip through AVFrame and back. The `priv` and `opaque` fields
in respectively `mp_image` and `AVFrame` are also too heavily overloaded
to be of much help.
In the end, bite the bullet and use the same approach as done in
`vo_gpu`, which is to just keep track of a list of all allocations. This
is a really ugly way of doing things IMO, but …
=> vo_gpu_next: properly keep track of DR allocations

audio/out/ao_pipewire.c
Details in the commit messages.
Fixes #10003 and #9992
=> ao_pipwire: Various fixes

video/out/wayland_common.c
In wayland 1.20.0, a couple of new events, name and description, were
added to the interface. Description is not particularly useful, but name
returns back nice names for the output like "DP-1" and so on. It makes
sense to use these for fs-screen-name and prefer them over the model
name (old way of doing it) if they are available. The only problem is
that 1.20.0 is pretty new so old distros aren't going to have it anytime
soon. Deal with this by adding some defines.
=> wayland: use wl_output v4 for --fs-screen-name

video/out/dither.c
Apparently _t names are reserved, and in this case it wasn't very useful anymore (it was useful while developing it, but this code is almost 10 years old now).
Fixes a compilation error on Solaris.
=> video/out/dither: remove custom index_t typedef

video/out/vo_gpu_next.c
One downside of this approach is that it bypasses the mixer cache, but
while this is not ideal for performance reasons, the status quo is also
simply broken so I'd rather have a slower implementation that works than
a faster implementation that does not.
And as it turns out, updating the OSD state and invalidating the mixer
cache correctly is sufficiently nontrivial to do in a clean way, so I'd
rather have this code that I can be reasonably certain does the right
thing.
Fixes #9923 as discussed. Also fixes #9928.
=> vo_gpu_next: fix OSD rendering of screenshots

video/out/vo_vaapi_wayland.c
This code was taken from the older vo_vaapi driver, which does
use the vaapi format list, but the new driver has no use for
these formats, as it is only interested in va surfaces that
can be mapped to wl buffers. The format doesn't enter into
it at all.
=> vo_vaapi_wayland: remove vaapi format query as formats are never used

audio/out/ao_pipewire.c
mpv only remembers volume for two channels.
Always apply the same volume to all channels in case of
non-stereo layout similarly to ao_pulse.
Don't try to do anything smart when averaging volumes,
normally they are equal anyway.
Tested on: https://www2.iis.fraunhofer.de/AAC/multichannel.html
=> ao_pipewire: support ao-volume on non-stereo channel layouts

video/out/wayland_common.c
=> vo_wayland: Add missing newline in wayland_common

.github/workflows/build.yml
Recommended since https://github.com/vmactions/freebsd-vm/compare/v0.2.1...v0.2.2
=> CI: prevent FreeBSD breakage via auto-update

DOCS/interface-changes.rst, DOCS/man/options.rst, video/out/wayland_common.c, video/out/wayland_common.h
I still actually need to get around to testing this (guessing the approach atm). More ifdefs since this requires a new-ish wayland protocols (few months ago).
=> wayland: add support for configure bounds

player/lua/ytdl_hook.lua
One would expect that e.g.
`--script-opts=ytdl_hook-all_formats=no --ytdl-format=bestaudio` and
`--script-opts=ytdl_hook-all_formats=yes --ytdl-format=bestaudio`
to play the exact same tracks without manual intervention.
This already worked when two formats were requested.
For a single format with `all_formats=yes` it would also play a track
that was not requested when available. This was inconsistant with the
behavior of `all_formats=no` (default), which would not play a second
track when only a single one was requested.
This combined with #10395 now plays the exact same tracks with
`all_formats=yes` as without, even when only one format is requested.
=> ytdl_hook: consistant behavior for single format

meson.build
=> meson: fix condition for enabling vaapi-egl

audio/out/ao_pipewire.c
=> ao_pipewire: for_each_sink(): report errors

etc/mpv.metainfo.xml, meson.build, wscript_build.py
Added XDG appstream metadata manifest for better integration.
More info: https://freedesktop.org/software/appstream/docs/chap-Metadata.html
=> Added XDG appstream metadata manifest

video/out/vo_gpu_next.c
Relies on a new upstream API for adding save/load callbacks to the ICC 3DLUT generation parameters.
Closes: https://github.com/mpv-player/mpv/issues/10252
Depends-On: https://code.videolan.org/videolan/libplacebo/-/merge_requests/286
=> vo_gpu_next: implement ICC 3DLUT caching

audio/out/ao_audiounit.m
Fixes 5.1/7.1 output mapping on tvOS 16, and also makes the AC3-layout hack unnecessary.
Also adds some diagnostic log messages.
=> ao_audiounit: get the channel layout from the AU itself

bootstrap.py
=> build: update waf to 2.0.24

TOOLS/lua/autoload.lua
Alphebatize the extensions in autoload.lua's list of extensions and add several more.
=> Autoload.lua extensions improvement

audio/out/ao_pipewire.c
Specifying the id of the target node during stream connect is deprecated.  Instead the property target.object should be used to link by target serial or name.  Using the name allows us to drop a bunch of custom code.
This changes behavior when an invalid device is specified. Previously a warning was printed, now it is not.
I'm not entirely sure how far back this is supported, but a cursory look seemed fine.
Cc @philipl
=> ao_pipewire: use target.object

video/out/vo_gpu_next.c
This brings vo_gpu_next's behavior more in line with vo_gpu. Currently, the status quo was that `vo_gpu_next` generated subtitles with the full resolution of the dst crop, even though practical limitations of libplacebo meant that such subtitles inevitably got cut off at the video boundaries. This was actually a worse status quo than `vo_gpu`, which simply constrained subtitles to the video dimensions to prevent these issues.
With this change, the behavior is the same as `vo_gpu`, which has the exact same problem w.r.t interpolation. Users are back to choosing between --blend-subtitles=yes and not having subtitles in margins, and using --blend-subtitles=no and not having subtitle interpolation.
There are different pros and cons to each approach, and I still ultimately plan on allowing …
=> vo_gpu_next: respect --blend-subtitles=<yes/no>

video/out/x11_common.c
mpv set _NET_WM_DESKTOP to 0xFFFFFFFF, which behaves differently with each window manager. Instead, set the window property to STICKY, and let the window managers deal with it.
tested on `archlinux` with `xfce 4.16` and `bspwm 0.9.10`
=> x11: fix --on-all-workspaces option

player/lua/console.lua
Console already respected the bottom margin to not overlap with the
bottom bar from the OSC, but it would still overlap with the window
decorations from the OSC.
Now everything is clipped above the top margin and no superfluous lines
are drawn.
=> console: respect the top margin shared script property

README.md, ci/build-freebsd.sh, ci/build-macos.sh, ci/build-mingw64.sh, ci/build-tumbleweed.sh, meson.build
None of these are critical, but the next version of meson has a few things that are slightly relevant so I'd thought I'd silence some warnings that would occur, update some docs, and tweak some internal logic.
=> meson: small build tweaks for meson 0.64

generated/wayland/meson.build, video/out/wayland_common.c, video/out/wayland_common.h, wscript
Should fix #10807. Can you confirm @TheOneric?
=> build: add an additional check for wayland-protocols 1.24

video/out/wayland_common.c
A couple of memory-related things to clean up. The second commit is kind of stupid but it works.
=> wayland: some memory fixes

.github/workflows/build.yml, ci/build-mingw64.sh
Having binaries available could come in handy sometimes.
=> mingw64 ci refresh & upload the binaries

.github/workflows/build.yml
Let's see if all of these changes build fine :) .
=> github/workflows: misc cleanups and updates

audio/out/ao_pipewire.c
This adds logging and handling for runtime errors reported by PipeWire.
Cc @philipl
=> ao_pipewire: Report and react to errors in the sound server

audio/out/ao_pipewire.c
=> ao_pipewire: log version information and metadata

generated/wayland/meson.build, video/out/vo_dmabuf_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h, video/out/wlbuf_pool.h, wscript_build.py
=> vo_dmabuf_wayland: use single-pixel-buffer-v1

audio/out/ao_pipewire.c
=> ao_pipewire: Fix resource leaks on initialization failures

TOOLS/umpv
=> TOOLS/umpv: support shell-quotes in $MPV

TOOLS/lua/autoload.lua
Commits https://github.com/mpv-player/mpv/commit/257dbdf06feb366f9eb1f96ceb7026c9365dddaa uses a algorithm of splitting strings into a table of number and string values to achieve natural sorting.
This approach works well in most cases, but it does not work well in some specific scenarios.
Now let's implement natural sorting with a stronger algorithm.
Ref: https://github.com/jonniek/mpv-playlistmanager/commit/3cf323f3c419af77f4141119283c1ec2911491c5
Closes https://github.com/mpv-player/mpv/issues/8969
=> TOOLS/lua/autoload: further optimize the natural sorting

ta/README
Cleaned up a sentence and updated the link to the talloc API documentation.
=> ta/README: update link to talloc documentation

video/out/vo_dmabuf_wayland.c
the viewport source is adjusted whenever the source rectangle changes
=> vo_dmabuf_wayland: support wp_viewport_set_source

stream/stream.c
Same as #11148 but for the stream list
=> stream: remove trailing NULL element from stream list

ci/build-freebsd.sh, ci/build-macos.sh, ci/build-mingw64.sh, ci/build-tumbleweed.sh, libmpv/test.c, meson.build
Details are in each commits message.
=> Some small optimizations for the meson build

video/out/vo_lavc.c
Fixes #11215.
ffmpeg was internally defaulting to 24000fps, which resulted in encoders selecting inappropriate levels and making poor ratecontrol decisions.
=> vo_lavc: set frame rate on encoder

audio/out/ao_pipewire.c
Details in the commits.
Cc @philipl
=> ao_pipewire: some visual cleanups

video/out/vo_dmabuf_wayland.c, video/out/wlbuf_pool.c, video/out/wlbuf_pool.h
This PR makes a few small improvements to how this vo handles resize and reset of pool.
=> vo_dmabuf_wayland: improve resize and buffer pool reset

DOCS/interface-changes.rst, DOCS/man/options.rst, video/filter/vf_sub.c
=> undeprecate stuff

DOCS/interface-changes.rst, video/csputils.c, video/csputils.h
This allows more precise adjustments.
Fixes #11316
Cc @NeilTohno
=> video: make csp equalizer params float

video/out/vo.c
See the commit message for the full explanation.
This looks very similar to #9735, but is different in a few important ways. While the user did correctly identify the problem, the fix was not correct and erroneously resulted in unneeded redraw events. This approach only sets the extra redraw when it is necessary (i.e. to fix the bug caused by the race).
Fixes: #8172 and #8350
=> vo: fix race condition with redraw requests

player/command.c
Meant to fix #11436. @t-8ch, could you verify that this clears up the lsan output for you?
=> player/command: fix mem leak in user-data property

demux/demux_mkv.c
As per the newly-merged spec. Nothing too complex here, though it does need an `AVCodecParameters` to set the profile + some wrapping to make sure it gets freed.
=> demux_mkv: support ARIB captions

TOOLS/docutils-wrapper.py, meson.build
This should probably only merged once https://github.com/rst2pdf/rst2pdf/pull/1111 has been released.
But it's here for review.
(The first two commits could be cherry-picked, as they are generic fixes)
=> meson: rst2pdf handle dependency file

video/out/gpu/d3d11_helpers.c
=> d3d11: retry device creation without debug, if SDK is not available

player/lua/auto_profiles.lua
Here's a way to fix #11550 but still keep the behavior of rejecting invalid properties. The downside is that something like `track-list/0/fake` wouldn't be rejected with this method, but I don't think there's a practical way for that.
=> auto_profiles: try to distinguish invalid properties better

libmpv/client.h
=> client API: fix file name in documentation

DOCS/man/ao.rst, audio/out/ao_pipewire.c
Fixes #11467 
@jpalus Could you test this?
=> ao_pipewire: let sound server determine latency 

video/out/wayland_common.c
See [1] for the motivation. Very similar to the fractional scale, except it's in core and integer-only.
[1]: https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/220
=> wayland: add support for wl_surface.preferred_buffer_scale

audio/out/ao_oss.c
fix for: https://github.com/mpv-player/mpv/issues/10640
=> ao_oss: return actual OSS playing state

video/out/d3d11/ra_d3d11.c
Filtering globally D3D11_MESSAGE_ID_CREATETEXTURE2D_INVALIDDIMENSIONS is suboptimal, because can also hide other invalid usages. In the same time it is not enough, because not only this message is emitted, but also one about E_INVALIDARG. Just flush queue before and clear messages after to ignore this part of code.
As a side note, I don't believe this texture size lookup is in fact useful, but since it is there and is relatively harmless, let's leave it as is.
=> ra_d3d11: change how error messages are ignored during texture size lookup

common/global.h, options/path.c, player/configfiles.c
@Dudemanguy I had to revise a few things after noticing it didn't fix the Android issue at all
ref #10838
=> Path-related fixes

video/out/hwdec/hwdec_cuda_vk.c
The libplacebo sync abstraction is deprecated and we should be using the more explicit Vulkan semaphore helpers instead. This means that more of the book keeping moves to our side, but it's not too bad.
The main subtlety is that while pl_sync owned the exported fd/handle, pl_vulkan_sem does not, so we are responsible for managing them. That means reversing the previous logic - we now can pass the original fd to CUDA and never think about it again, while we have to clean up the Win32 Handle because CUDA will not take ownership.
=> hwdec_cuda: remove usage of deprecated libplacebo sync API

.github/workflows/build.yml, bootstrap.py
=> Fix CI failure with msys2

demux/demux_lavf.c
If demux_open_lavf fails between calling avformat_alloc_context() and assigning the context to priv->avfc, it will never be properly freed.
Fixes #11793.
=> demux/demux_lavf: avoid leaking AVFormatContext during demux_open_lavf

audio/decode/ad_lavc.c
Fixes: https://github.com/mpv-player/mpv/issues/11792
=> ad_lavc: check for allocation failure

osdep/polldev.c, osdep/polldev.h, video/out/wayland_common.c
More details in each commit message.
=> remove some erroneous `POLLERR` usage

DOCS/man/options.rst, meson.build, player/screenshot.c, test/meson.build, test/test_utils.c, test/test_utils.h, video/image_writer.c, video/image_writer.h, wscript
Mentioned it on irc, accepted by @sfan5, resolves #11245.
AVformat version taken from https://github.com/FFmpeg/FFmpeg/commit/84241e63cf2f3cc8f7d8a19e86b99f5af95d2a64.
=> video/image_writer: add basic avif support

video/out/opengl/context_wayland.c, video/out/wayland_common.c
=> wayland: use xdg_surface_set_window_geometry

sub/sd_ass.c
dbc5d7b7db70f898dcd5cbbba76ffed38e5371ee seems to have originally introduced this behavior. At the time, wm4 simply reconfigured ass on every frame in order to accommodate runtime changes in sub options. This certainly works, but these libass API calls are not free and there is at least one known performance regression due to a change in libass*. Regardless of whether or not the libass change is good/bad, there is no need for mpv to constantly reconfigure this. When wm4 made that commit, there was no notification mechanism for options changing that could easily be used so he didn't really have any other choice. But it's nearly 10 years later now and internally we have all the necessary pieces to only configure ass again when we need to: on option changes or resizes. So go ahead and …
=> sd_ass: don't reconfigure ass on every frame

player/loadfile.c
When using lavfi-complex, no single track populates current_track for audio. We work around this by iterating over the list of tracks and using the first non-null language from a selected track. If multiple tracks are selected (i.e. used by the filter) and have conflicting language tags, we'll ignore them all and maintain the previous behavior (null).
=> loadfile: compute audio language for sub selection when using lavfi-complex

video/decode/vd_lavc.c
There is an additional failure path I didn't account for in my previous work. While I ensured that a late hwdec failure in receive_frame can be recovered from my trying the next hwdec, there is a specific combination where if an hwdec fails in receive_frame, and the next hwdec is a full decoder (eg: v4l2m2m), and that also fails, we are left with no decoder and so the entire decoding process ends and playback is stopped.
Basically, we must keep re-attempting the fallback in receive_frame until we get a valid decoder (software or hardware). This edge case will rarely be encountered as there are only a couple of decoder based hwdecs.
Fixes #11947
=> vd_lavc: repeatedly attempt to fallback if hwdec fails in receive_frame

video/out/wayland_common.c, video/out/wayland_common.h
=> wayland: don't treat tiled and maximized windows the same

DOCS/man/input.rst, DOCS/man/options.rst, player/screenshot.c, video/out/vo_drm.c
Now most VOs should be able to do `screenshot window`.
=> software screenshot improvements

DOCS/man/vo.rst, video/out/vo_dmabuf_wayland.c
~~Mostly academic but still.~~
Nope, actually fixes something.
=> vo_dmabuf_wayland: imgfmt improvements

video/out/wayland_common.c
In 1f8013ff3fddd788a517656e09f5ce5d7efd928d, I mistakenly thought this was only used for modifier presses way back in the commit it was introduced in, but it actually also handles non-english keys/letters. Instead of returning early, we should try xkb_keysym_to_utf8 first and then return if that doesn't do anything so the modifier can then be handled in the appropriate event. Fixes #12009.
=> wayland: restore xkb_keysym_to_utf8 handling

video/out/vo_vdpau.c
=> vo_vdpau: set hwdec image format

test/libmpv_test.c
I actually wanted to write an unit test for #12040 but that turned out infeasible.
=> Test-related improvements

video/out/vo_gpu_next.c
Configuration of filter parameters was moved from pl_filter_function (of which the user had to make a copy) to pl_filter_config, with the pl_filter_function remaining immutable.
Implement this new logic in a way that can reasonably exist side-by-side with the old configuration API. Once we drop support for PL_API_VER below 303, we can drastically simplify this code.
Depends on: https://code.videolan.org/videolan/libplacebo/-/merge_requests/523
=> vo_gpu_next: update for new pl_filter configuration API

video/out/vo_gpu_next.c
Closes: https://github.com/mpv-player/mpv/issues/12093
=> vo_gpu_next: add ability to use named hook params

osdep/path-unix.c
Avoids silently proceeding with a truncated path + a small x11 patch.
(Note: doing the allocation dynamically via `ta_xasprintf()` was discussed on the IRC but `pthread_once()` doesn't have context pointer so that'd create a "leak". And trying to smuggle the talloc_ctx through some global would require atomic `void *` or similar which currently doesn't exist on `osdep/atomic.h`).
=> Abort on truncated path

audio/out/ao.h, audio/out/buffer.c, player/audio.c, player/command.c, player/core.h, player/playloop.c, player/sub.c, player/video.c, sub/dec_sub.c, sub/dec_sub.h, sub/sd_lavc.c
Just some relatively low hanging fruit from the issue tracker. Could use some more testing on the second commit since nearly all of the subtitles I have are ASS.
=> miscellaneous fixes

video/out/x11_common.c
No change in functionality intended.
=> x11_common: misc style fixes

DOCS/interface-changes.rst, DOCS/man/input.rst, DOCS/man/options.rst, DOCS/man/vf.rst, common/playlist.c, common/playlist.h, filters/f_output_chain.c, filters/filter.h, meson.build, options/options.c, options/options.h, options/parse_commandline.c, player/command.c, player/loadfile.c, player/osd.c, sub/sd_ass.c, sub/sd_lavc.c, video/filter/vf_vapoursynth.c, video/out/wayland_common.c, video/out/x11_common.c
Handful of small features I'd thought I'd implement. #12131 was originally a part of this but that became surprisingly complicated so I split it out.
=> miscellaneous features

video/out/wayland_common.c
=> wayland keyboard fixes

player/lua/stats.lua
=> stats.lua: display also output resolution

video/out/drm_common.c
It's possible for systems to have multiple cards, and the first capable card to not have a connected output. Skip such cards and continue iterating until we find one with a connected output.
=> drm_common: skip cards that don't have connected outputs

video/out/opengl/context_drm_egl.c
=> context_drm_egl: more correctness fixes + 1 more

video/out/w32_common.c
Fixes: 57ba77fc736f6976bc114974f5955c972139740f
Fixes: #12220
=> win32: don't ignore --screen and --fs-screen

demux/demux_lavf.c
Before this change, mpv used to get the total duration from `avformat_find_stream_info` and used the per-track duration as a fallback. This change reverses this order of preference.
The timestamps returned by `avformat_find_stream_info` are truncated or rounded or floored (depending on the decoder) at the 6th decimal place. For e.g. `avformat_find_stream_info` may return us a duration like 44.138667, whereas the duration we get from the per-track struct has a higher degree of percision like 44.13866666666... and so on.
This caused various problems such as the playback_pts being a bigger value than the duration, which would cause time-remaining to be a negative value in some cases. Or cause you to reach a negative starting timestamp when looping on an audio file with `gapless-audio`. …
=> demux_lavf: get total duration from track durations

filters/f_hwtransfer.c
[This spams about 2k lines with just `-v` when using hwdec on every new video.
](https://0x0.st/HpEC.txt)
If this is useful then I could also make it print all the supported formats as a comma separated list in one line with MP_DBG, instead of TRACE.
=> hwtransfer: make probe_formats logging less spammy

DOCS/interface-changes.rst, DOCS/man/options.rst, video/out/filter_kernels.c
Match changes made in https://code.videolan.org/videolan/libplacebo/-/merge_requests/587
=> chase libplacebo bcspline/bicubic and hermite changes

DOCS/man/options.rst, TOOLS/lua/autocrop.lua, options/m_option.c, player/command.c, player/video.c
=> TOOLS/autocrop.lua: use VO crop always

video/out/w32_common.c
In theory it shouldn't be needed, but apparently on Windows 7 those ordinals returns pointers to not executable code trigerring DEP.
Fixes: #11610
Fixes: 9feeb324eddd9ed73ae667e10275f663d70f7544
=> win32: explicitly guard dark mode calls by Windows version

.github/workflows/comment.yml
Copied from https://github.com/Ryujinx/Ryujinx/blob/master/.github/workflows/nightly_pr_comment.yml
How it looks, See: https://github.com/natural-harmonia-gropius/mpv/pull/2
Additional settings needed:
`Settings` -> `Actions` -> `General` -> `Workflow Permissions`
=> github/workflows: comment PR artifacts links

DOCS/interface-changes.rst, DOCS/man/options.rst, demux/demux.c, demux/demux.h, demux/demux_lavf.c, demux/demux_mf.c, demux/demux_mkv.c, options/m_config_core.c, options/m_config_core.h, options/options.c, options/options.h, stream/stream.c, stream/stream_bluray.c, stream/stream_cdda.c, video/cuda.c, video/out/gpu/video.c, video/out/hwdec/hwdec_cuda_gl.c, video/out/opengl/context_win.c, video/out/opengl/libmpv_gl.c
Second go at this. This time it gets rid of everything. Bunch of commits so it's more readable (hopefully).
=> remove mp_read_option_raw

common/recorder.c
Not sure how long these have been around but it leaked on every packet.
=> recorder: fix a couple of memory leaks

DOCS/man/mpv.rst, etc/restore-old-bindings.conf
Update the docs to the new bindings set by 981a9372ff.
=> DOCS/mpv: update the wheel bindings

video/out/w32_common.c
Fixes window resizing in borderless mode after adding WS_SYSMENU.
Fixes: 172d9be3005c6a85f4f139f1dedccefe26ea8d91
=> win32: add WS_THICKFRAME style in borderless mode

DOCS/interface-changes.rst
Added in f19ada7b583e9bf78de38d228a956c365b5c417b
=> DOCS/interface-changes: mention --backdrop-type

DOCS/interface-changes.rst, DOCS/man/options.rst, options/path.c
=> path: don't override "cache" and "state" paths with configdir

TOOLS/lua/autocrop.lua
Refactor code that is no longer necessary after replacing vf=crop with video-crop. There is no change in behavior.
=> TOOLS/autocrop.lua: simplify code

TOOLS/lua/autocrop.lua
=> TOOLS/autocrop.lua: add support for detect_min_ratio

player/core.h
=> core: remove declarations of unused functions

video/out/w32_common.c
Several window resizing operations (i.e., `--auto-window-resize`,
border dragging with `--keep-aspect-window`, Alt+0/1/2) cause the
window to detach from the snapped borders. This patch resolves
this by recording to which borders the window is snapped, and
using this info to determine how the window should be placed after
resizing. Closes https://github.com/mpv-player/mpv/issues/6588.
=> win32: improve window snapping behavior

README.md
Updates README.md like 1e9a2cbebff updated DOCS/release-policy.md.
=> README: update release frequency

DOCS/interface-changes.rst, filters/f_decoder_wrapper.c, options/m_option.c, options/m_property.c, options/m_property.h, player/command.c, player/lua/stats.lua
Extracted some changes from #12306 hopefully to make it easier for review. Few features of stats.lua are not available without changes added in #12306.
=> stats.lua: separate video parameters from video out

filters/f_hwtransfer.c
Some ffmpeg hwcontexts do not implement frame constraints. That means they cannot report which formats are support for given configurations.
My previous changes to make hwupload more capable relies on the constraints to be provided to accurate describe what combinations are supported, so we will currently see a bunch of errors failing to configure the hwupload filter on platforms such as v4l2 SoCs with drmprime. This doesn't break playback, but it's confusing.
So, the bridge the gap, this change uses the static format metadata that we include for hwdecs to build a fake constraints struct to keep all the other code working.
=> hwtransfer: handle hwcontexts that don't implement frame constraints

common/common.c, common/common.h, video/decode/vd_lavc.c, video/mp_image.c, video/out/vo.h, video/out/vo_gpu_next.c
=> Properly align DR buffers

DOCS/interface-changes.rst, DOCS/man/options.rst, meson.build, stream/stream_cdda.c
It still sucks in a lot of ways but eh.
=> make stream_cdda slightly less broken

meson.build, osdep/timer.c, osdep/win32/include/pthread.h, osdep/win32/pthread.c, test/meson.build, test/test_utils.c, test/test_utils.h, test/timer.c
see https://github.com/mpv-player/mpv/pull/12661#issuecomment-1766207587
~~I'm not insisting on the second change, but for the first a better approach is definitely needed IMO.~~
=> Re-do high-res timers with win32 pthread shim

stream/dvb_tune.c, stream/dvbin.h, stream/stream_dvb.c
this felt like a waste of time
=> dvbin code cleanup

player/lua/ytdl_hook.lua
Fixes stream URLs that require cookies. See:
- https://github.com/yt-dlp/yt-dlp/security/advisories/GHSA-v8mc-9377-rwjj
- [How yt-dlp formats the -cookies argument](https://github.com/yt-dlp/yt-dlp/commit/1ceb657bdd25#diff-045340cd706a52a49d1614a44d092c244144486fdd4101f4b56ae644ac9fdd04R562-R566)
=> ytdl_hook: parse the separate cookies field

filters/f_hwtransfer.c
Some hwdecs (eg: dxva) have no frames constraints and no static supported_formats, which ends up segfaulting. This change fixes the segfault, but also includes additional changes to avoid concluding that direct output of hardware decoded video is impossible.
In the case where there are no frame constraints and no supported_formats, we basically have no idea what the hardware actually supports. Previously, we just tried to display the frame, but all the work I did to detect incompatible formats causes this scenario to now conclude that no formats can be displayed, and forces a HW download to system memory.
I have made a couple of small changes to assume that direct display is possible. If it's not, the VO will error out down the line, which is what happened previously.
=> hwtransfer: handle constraints for hwdec with NULL supported_formats

osdep/compiler.h, ta/ta.c, video/img_format.h, video/out/aspect.c
No real change in functionality intended.
=> Remove some dead code

TOOLS/macos-sdk-version.py, meson.build
=> meson: do the macos sdk version comparison in meson

player/video.c
See commits for explanations. I thought about some of the audio/video stuff some and figured some these additional changes would also be an improvement.
=> more av syncing changes

video/mp_image.c
Fixes rotating image by --video-rotate when filtering.
Fixes: #12771
=> mp_image: pass rotation correctly to/from AVFrame

video/out/placebo/ra_pl.c, video/out/vo_gpu_next.c
Also a bugfix for the pl_cache not being destroyed on uninit.
=> drop several unneeded PL_API_VER checks

options/options.c, video/out/drm_common.c, video/out/present_sync.c, video/out/present_sync.h, video/out/vo.c, video/out/vo.h, video/out/wayland_common.c, video/out/x11_common.c
I didn't like saving the max possible swapchain depth so I tweaked it to make it save the actual swapchain depth instead.
=> small present sync tweaks

player/lua/console.lua
So far completing something like `${some_pro}` with the cursor between `o}` would result in `${some_property}}`. Adding that superfluous `}` can be avoided by checking if it's already in the string after the cursor.
=> console: avoid redundant completion appendage

video/image_writer.c, video/out/gpu/video.c, video/out/gpu/video.h, video/out/vo_gpu_next.c
=> screenshot-related improvements

player/lua/stats.lua
056072bf95 deleted the only use of property_list.
=> stats.lua: remove unused variable

DOCS/interface-changes.rst, DOCS/man/options.rst, video/out/gpu/video.c, video/out/gpu/video.h, video/out/vo_gpu_next.c
Fixes: https://github.com/mpv-player/mpv/issues/12777
=> vo_gpu_next: add --target-gamut option

audio/out/ao_audiotrack.c, audio/out/ao_coreaudio.c, audio/out/ao_pipewire.c, audio/out/buffer.c, audio/out/internal.h, osdep/compiler.h
Continuation of #12643 
Only tested on ao_pipewire.
@handlerug Could you test it with ao_coreaudio?
@tmm1 Could you test it with ao_audiotrack?
=> audio: avoid blocking in pull AOs

demux/demux_lavf.c
Fixes rotation metadata no longer works.
See: https://github.com/FFmpeg/FFmpeg/commit/5432d2aacad5fa7420fe2d9369ed061d521e92d6
Fixes: #12836
=> demux/lavf: don't use deprecated side data

player/video.c, video/out/vo.c, video/out/vo.h, video/out/vo_gpu_next.c
I was rebased on top of @Dudemanguy's changes, pushed them too, to avoid conflict resolve...
=> vo_gpu_next: fix interpolation

video/out/vo_gpu_next.c
Alternative to #12863 without the optimization hacks if it's preferred. This will always increment on *any* redraw with blend subtitles, but for this specific case (still image with subtitles) mpv spams the redraw constantly. So it's incredibly wasteful. Note that vo_gpu currently has the same behavior of always doing the blend subtitles on every single redraw as well.
=> vo_gpu_next: update overlays for blend subtitles on frame redraws

player/command.c
=> command: notify media-title on force-media-title change

TOOLS/dylib-unhell.py, TOOLS/osxbundle.py, TOOLS/osxbundle/mpv.app/Contents/Info.plist, osdep/macosx_application.m
the bundle scripts really need a proper cleanup and rewrite. though for now i just fixed the current problems.
=> mac: fix bundling with relative linked dependencies, fix code signing, add signing

audio/out/ao_wasapi_utils.c, common/msg.c, demux/demux.c, filters/f_autoconvert.c, filters/f_decoder_wrapper.c, filters/f_swresample.c, input/ipc-win.c, osdep/subprocess-win.c, player/loadfile.c, stream/stream_libarchive.c, video/d3d.c, video/out/d3d11/ra_d3d11.c, video/out/gpu/video.c, video/out/opengl/context.c, video/out/vo_direct3d.c, video/out/vo_gpu_next.c, video/out/vulkan/context.c
small fixes from static analysis
=> small fixes

osdep/macosx_menubar.m, video/out/mac/title_bar.swift, video/out/mac/view.swift
the title bar fix is a bit weird but it seems Apple changed some shit sadly.
alternative to #11938
fixes #12899
=> mac: some small fixes and additions

video/out/vo.c, video/out/vo.h, video/out/vo_gpu_next.c
For correctness with vo_get_current_params.
=> vo: add params mutex

audio/out/ao_coreaudio_utils.c, sub/img_convert.c, video/filter/vf_vdpaupp.c, video/out/x11_common.c
=> various: replace some OOM handling

.github/workflows/build.yml
=> github/workflows: install libxxhash on msys2

video/out/w32_common.c
Fixes https://github.com/mpv-player/mpv/issues/1921.
=> win32: stop fullscreen window from moving while dragging hack is active

.github/ISSUE_TEMPLATE/2_bug_report_linux.md, .github/ISSUE_TEMPLATE/2_bug_report_macos.md, .github/ISSUE_TEMPLATE/2_bug_report_windows.md, .github/ISSUE_TEMPLATE/3_bug_report.md, .github/ISSUE_TEMPLATE/4_bug_report_build.md, .github/ISSUE_TEMPLATE/5_feature_request.md, .github/ISSUE_TEMPLATE/6_question.md
There are some inconsistencies for the formats and the information requested across issue templates, so now request a union of them.
=> github/issue_template: unify requested information across templates

audio/out/ao_wasapi_utils.c, osdep/io.c, osdep/io.h, osdep/path-uwp.c, osdep/path-win.c, osdep/win32-console-wrapper.c, video/out/w32_common.c
ping @kasper93 
untested beyond making sure it compiles
=> win32 long-path stuff

player/lua/console.lua
43ed0a83d0 avoided reinserting the string that is appended after certain completions when it is already after the cursor when inserting the longest common prefix of the suggestions. Do the same when cycling through them.
=> console.lua: don't reinsert completion_append after cycling

common/msg.c
All characters are assumed to be single-width. This is consistent with the rest of the code and documentation.
Fixes: #13150
=> msg: improve term_disp_width to support unicode

README.md
Recommend `--profile=fast` for embedded or integrated GPUs, and specify what "not too ancient Linux" means to match reality.
=> README: some recommendation and clarification in system requirements

video/out/wayland_common.c
=> Fix wayland modifiers

sub/filter_sdh.c
=> filter_sdh: optimize get_char_bytes

player/lua/stats.lua
=> stats.lua: make capitalization consistent across pages

osdep/io.c
Fixes compatibility with loading scripts from relative config paths.
Fixes #13212
=> osdep/io: expand path before LoadLibrary

filters/f_lavfi.c
=> f_lavfi: use libplacebo utils instead of mp_csp_*

sub/draw_bmp.c, sub/sd_ass.c, video/csputils.c, video/filter/vf_fingerprint.c, video/mp_image.c
=> all: add missing repr assignments

video/out/opengl/context_wayland.c, video/out/vo_dmabuf_wayland.c, video/out/vo_wlshm.c, video/out/vulkan/context_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h
Alternative to #13324 with some additional improvements.
=> wayland: simplify scaling

DOCS/interface-changes.rst, DOCS/man/input.rst, DOCS/man/mpv.rst, DOCS/man/options.rst, etc/input.conf, filters/f_auto_filters.c, filters/f_auto_filters.h, filters/f_output_chain.c, filters/f_output_chain.h, options/options.c, options/options.h, player/command.c, player/lua/stats.lua
Comments welcome since I have basically no actual interlaced samples.
=> [RFC] player: add an auto option to deinterlace

osdep/macos/libmpv_helper.swift, osdep/macos/remote_command_center.swift, osdep/macosx_events.m
just a small refactor and some newly added features that were requested.
fixes #11233
=> mac/remote: refactor and new features

audio/out/ao_pipewire.c
This is only lightly tested as I seem to have some issue with my hardware or Pipewire setup.
It works for me in some cases, so it isn't completely broken.
Testers are welcome.
=> ao/pipewire: spdif support

options/options.c, options/options.h, player/command.c, video/out/vo.c, video/out/vo.h, video/out/vo_gpu.c, video/out/vo_gpu_next.c, video/out/vo_libmpv.c, video/out/vo_vdpau.c
Well maybe a little bit simpler. Second commit fixes runtime updates of gpu-next specific options
=> simplify option updates

TOOLS/dylib-unhell.py, TOOLS/osxbundle.py
this is the last part to make the macOS bundle completely portable with a vulkan (MoltenVK) gpu-next backend.
=> osxbundle: bundle vulkan driver and layers

DOCS/client-api-changes.rst, DOCS/interface-changes.rst, DOCS/mplayer-changes.rst, DOCS/tech-overview.txt, README.md, TOOLS/osxbundle.py, audio/out/ao_coreaudio_exclusive.c, etc/builtin.conf, libmpv/client.h, libmpv/render_gl.h, options/path.h, osdep/path.h, osdep/semaphore.h, video/out/gpu/ra.h, video/out/opengl/common.c, video/out/opengl/context_glx.c, video/out/opengl/formats.c
not sure if we have a better general commit prefix than `player:`.
=> make mentions of macOS consistent

player/core.h, player/loadfile.c
I'm sure something's broken since there's way too many sub options (whose fault could that be). Anyways, please test. cc @dawidpotocki
=> player/loadfile: rewrite sub autoselection logic

video/image_writer.c
This avoids leaving an empty/corrupt file if `fopen` succeeds but image writing fails afterwards.
=> image_writer: cleanup leftover files if image writing fails

.github/workflows/build.yml, ci/build-openbsd.sh
=> ci: add OpenBSD

DOCS/interface-changes.rst, DOCS/man/input.rst, DOCS/man/options.rst, options/options.c, options/options.h, player/audio.c, player/command.c, player/core.h
=> various: add ao-volume option, to set the system volume at startup

.github/workflows/build.yml, ci/build-linux-old.sh
=> ci: Add explicit build test for ffmpeg 4.4

video/out/wayland_common.c, video/out/wayland_common.h
This is blocked until a new sway version at least because the first commit will cause some very annoying behavior unless you run sway master (old sway bug I've been hacking around for years).
=> wayland geometry stuff

video/out/wayland_common.c, video/out/wayland_common.h
=> Wayland fixes

sub/ass_mp.c, sub/ass_mp.h, sub/osd.h, sub/osd_libass.c, sub/sd_ass.c, video/out/vo_gpu_next.c
Ref: https://code.videolan.org/videolan/libplacebo/-/merge_requests/630
=> vo_gpu_next: render subtitles at video colorspace

video/out/wayland_common.c, video/out/wayland_common.h
Still not happy with some multi monitor behavior. Will look into that sometime later.
=> wayland scaling stuff again

video/out/wayland_common.c
Fixes https://github.com/mpv-player/mpv/issues/13630.
=> wayland_common: fix pointer serial conflict

meson.build
I accidentally closed #13638. Still learning how pull requests work 😥
=> meson: remove main function from libmpv build

DOCS/interface-changes.rst, DOCS/man/input.rst, player/command.c, video/mp_image.h, video/out/vo.c, video/out/vo.h, video/out/vo_gpu_next.c
EDIT: removed images, because it is evolving.
=> vo: add `video-target-params` property

video/out/wayland_common.c
=> wayland: always rescale geometry if in a fullscreen/maximized state

DOCS/interface-changes.rst, DOCS/man/vf.rst, filters/f_autoconvert.c, filters/f_decoder_wrapper.c, filters/f_output_chain.c, player/lua/stats.lua, player/video.c, video/csputils.c, video/filter/refqueue.c, video/filter/vf_format.c, video/filter/vf_gpu.c, video/mp_image.c, video/mp_image.h, video/out/gpu/video.c, video/out/placebo/utils.c, video/out/placebo/utils.h, video/out/vo_gpu_next.c, video/vdpau_mixer.c
and don't side-load it in gpu-next.c
=> mp_image: add Dolby Vision metadata mapping

video/image_writer.c, video/mp_image.c
Note: test with https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=10666
=> video/image_writer: attach MDVC metadata and CLLI metadata

video/repack.c
Allows compiler to do its job and optimize this code. We don't really want to repack in-place.
=> repack: add restrict qualifier to src/dst pointers

DOCS/man/options.rst
=> DOCS/options: improve wording of dither-depth

player/lua/stats.lua
- current ao
- volume and ao volume
- audio delay
- output format
motivated to have feature parity with video section
=> stats.lua: add more information in audio section

DOCS/interface-changes/floating-point_property_expansion.txt, DOCS/man/input.rst, common/common.c, common/common.h, options/m_config_frontend.c, options/m_option.c, options/m_option.h, options/m_property.c, options/m_property.h, player/command.c, test/format.c, test/meson.build, test/test_utils.c
=> m_property: add `>` for fixed precision floating-point expansion

player/command.c
=> player/command: fix udata talloc parent

DOCS/interface-changes/pa-defaults.txt, audio/out/ao_pulse.c
=> ao_pulse: reenable latency hacks by default

.github/workflows/build.yml
=> ci/msys2: fix vulkan package name

player/command.c
Would be better to search the other way around, because options list is bigger than property list, but with minimal changes this is good enough. Both are relatively small tho and the only reason for this micro optimization is to increase the fuzzing throughput.
=> player/command: optimize duplicated property search in command_init

audio/out/ao_coreaudio.c
=> ao_coreaudio: handle latency change on hotplug

player/video.c
=> video: also reset video-sync state when resetting video state

audio/out/ao_pipewire.c
@t-8ch as you've mentioned in #13774
=> ao_pipewire: proper buffer size calculation

osdep/mac/app_hub.swift, osdep/mac/input_helper.swift, osdep/mac/remote_command_center.swift, video/out/mac/common.swift, video/out/mac/view.swift, video/out/mac/window.swift
fixes a +7 years old bug which still occurs with the new API https://stackoverflow.com/questions/37623734/why-nsapplicationdelegate-method-openfiles-is-being-called-multiple-times-on-a
=> mac: cleanups and small fixes

player/lua/stats.lua
=> stats.lua: fix scrolling for page 2

audio/decode/ad_lavc.c, audio/decode/ad_spdif.c, audio/filter/af_drop.c, audio/filter/af_format.c, audio/filter/af_lavcac3enc.c, audio/filter/af_rubberband.c, audio/filter/af_scaletempo.c, audio/filter/af_scaletempo2.c, audio/out/ao_audiotrack.c, audio/out/ao_pulse.c, audio/out/ao_sndio.c, audio/out/buffer.c, audio/out/internal.h, filters/f_autoconvert.c, filters/f_demux_in.c, filters/f_hwtransfer.c, filters/f_output_chain.c, filters/f_swresample.c, filters/f_swscale.c, video/decode/vd_lavc.c
This makes stack traces and stack sampling profilers give more descriptive information.
=> various: make some internal function names more descriptive

osdep/mac/app_hub.swift, osdep/mac/log_helper.swift
alternative to #13843
Fixes #13823
=> mac/log: fix use after free when freeing mpv handle

common/msg.c
No need to recalc string length.
=> msg: use fwrite

TOOLS/lua/autoload.lua
See-Also: https://github.com/dyphire/mpv-config/issues/70
=> TOOLS/lua/autoload: fix allow extending ext sets from script-opts

video/out/vo_gpu_next.c
See: https://code.videolan.org/videolan/libplacebo/-/merge_requests/659
=> vo_gpu_next: invalidate cache object if requested by libplacebo

DOCS/client-api-changes.rst
=> DOCS/client-api-changes.rst: fix formatting

input/input.c
Fixes https://github.com/mpv-player/mpv/issues/13933.
=> input: fix deadlock in adding gamepad input src

sub/dec_sub.c
Fixes: 715feea8d82a750c3d627ee10c4fd6c6fe1fbe86
=> dec_sub: fix locking for sub_ass_get_extradata

DOCS/man/vf.rst, filters/user_filters.c, meson.build, video/filter/vf_gpu.c, video/filter/vf_gpu.h, video/filter/vf_gpu_egl.c, video/filter/vf_gpu_vulkan.c, video/out/vulkan/context.c, video/out/vulkan/context.h
vf_gpu port using vulkan ractx instead of egl.
Should work on Windows as requested in #9354. Tested on Linux.
=> Implement vf=gpu using Vulkan

video/out/w32_common.c
Fixes https://github.com/mpv-player/mpv/issues/13928.
=> w32_common: fix show-in-taskbar toggling after explorer is restarted

osdep/mac/app_hub.swift, osdep/mac/application.swift, osdep/mac/event_helper.swift, osdep/mac/input_helper.swift, osdep/mac/libmpv_helper.swift, osdep/mac/log_helper.swift, osdep/mac/menu_bar.swift, osdep/mac/option_helper.swift, osdep/mac/precise_timer.swift, osdep/mac/remote_command_center.swift, osdep/mac/swift_compat.swift, osdep/mac/swift_extensions.swift, osdep/mac/touch_bar.swift, osdep/mac/type_helper.swift, video/out/cocoa_cb_common.swift, video/out/mac/common.swift, video/out/mac/gl_layer.swift, video/out/mac/title_bar.swift, video/out/mac/view.swift, video/out/mac/window.swift, video/out/mac_common.swift
just the code cleanup changes of #14009. i need those for some further PRs.
=> mac: code cleanup and consistency changes, fix linting issues

etc/powershell-completion.ps1
Creating new pull request..., previous one had commits I was not able to squash...
=> powershell-completion: add PowerShell command line completion

.github/workflows/lint.yml, .swiftlint.yml
swiftlint: https://github.com/realm/SwiftLint
doc: https://realm.github.io/SwiftLint/
action: https://github.com/norio-nomura/action-swiftlint
should only be merged after #14015
=> github/workflows: add swift linting

video/out/wayland_common.c
Might be useful for debugging.
=> wayland: also log version numbers with protocol interface names

player/lua/select.lua
=> select.lua: fix preselecting the current subtitle line

.github/workflows/build.yml
=> ci/mac: silence unnecessary reinstall warnings

audio/out/ao_coreaudio.c
Fixes #7172, #13189
Can someone test this? @rgaufman would you plz have a check?
=> ao_coreaudio: set ao->device_buffer base on hardware latency

player/lua/console.lua
Fixes https://github.com/mpv-player/mpv/pull/14247#issuecomment-2134418206
=> console.lua: fix crash with set ;<Tab>

video/out/vo_vaapi.c
I think this probably still needs more work to adapt to the draw_frame API properly, but nobody should be using this VO in 2024 and nobody should be working on this either.
Fixes #14253
=> Fix vo vaapi

DOCS/interface-changes/sub-ass-override-default.txt, DOCS/man/options.rst, TOOLS/gen-interface-changes.py, etc/input.conf, options/options.c, sub/sd.h, sub/sd_ass.c
=> Fix sub ass override

sub/sd_ass.c
Using strchr should be faster as it is optimized for the job. Also ensure that tags are not escaped and are within {} correctly. This also is important for performance as it allows to scan only needed areas of the string.
=> sub/sd_ass: rewrite is_animated()

audio/out/ao_pcm.c, common/common.c, misc/thread_tools.c, options/parse_commandline.c, player/main.c
=> Minor win32 build fixes

video/out/wayland_common.c
Wayland protocol only guarantees the delivery of modifier information after the enter event. To handle it properly for keys pressed in the enter event, save those keys for later processing in the modifier event.
=> wayland_common: properly handle modifiers for keyboard enter keys

DOCS/compile-windows.md
Currently the documentation for building on Windows, specifically the "Native Compilation with Clang (Windows SDK Build)" route, could use a few minor improvement to make the development onboarding experience more smoothly.
Fixes #14214
=> DOCS/compile-windows.md: improve Windows build documentation

player/lua/osc.lua
=> osc.lua: fix timetotal and timems settings

video/out/d3d11/context.c
If the output display reports high bitdepth, 12-bit and 10-bit swapchain is used the value returned from d3d11_color_depth needs to take it into account.
=> d3d11: return minimum bitdepth for display output and swapchain

player/lua/osc.lua
=> osc.lua: replace tabs with spaces

fuzzers/meson.build
To test if this resolves issues with oss-fuzz.
=> fuzzers: disable some fuzzer targets as we hit out of space errors

demux/demux.c
Since d41f0a54b07d855227b63a6b2c4e92794ff7b86f, enabling a stream will no longer perform a refresh seek, to fix issues with switching video tracks. Additionally, 62e9a0c5f6be63c4cbe6387cbd3419fe19e98b74 also prevents refresh seek on track switching when it happens right after a seek.
Unfortunately, when external audio files are loaded, preventing refresh seeks can cause A-V sync issues. Since external tracks have separate demuxer instances from the internal tracks, the demuxer instances from both internal and external tracks are explicitly sought to the same pts when seeking is performed. When enabling an external audio track for the first time, the existing logic prevents refresh seek because no packets have ever been read, so the track ends up not being sought. This means that switching …
=> demux: allow initial refresh seek for for non-video streams

audio/decode/ad_lavc.c, audio/decode/ad_spdif.c
It is not always available for the demuxer, so update it from decoder.
=> ad_{lavc,spdif}: initialize channel layout

fuzzers/fuzzer_load.c
Nothing should ever modify this data. Also, add CLOEXEC for good measure.
=> fuzzer_load: seal the input fd after writing the data

stream/stream_bluray.c, test/libmpv_encode.c
=> test/libmpv_encode: explicitly discard fread result

DOCS/man/input.rst
I removed the superfluous "does".
=> input.rst: fixed "does does" typo;

player/lua/ytdl_hook.lua
Fixes: acbd537dac4ce4ea0a9ea316181123000a7082c1
Fixes: #14522
=> ytdl_hook.lua: fix hook triggering while it shouldn't

.github/workflows/fuzz.yml
=> workflows/fuzz: run all sanitizers

.github/ISSUE_TEMPLATE/2_bug_report_linux.yml, .github/ISSUE_TEMPLATE/2_bug_report_macos.yml, .github/ISSUE_TEMPLATE/2_bug_report_windows.yml, .github/ISSUE_TEMPLATE/3_bug_report.yml
Fixes: 051e2a8b7a2079130327478aa709095bee396f76
=> github/issue_template: fix paragraph spacing

TOOLS/stats-conv.py
=> Fix stats conv

.github/ISSUE_TEMPLATE/2_bug_report_linux.yml, .github/ISSUE_TEMPLATE/2_bug_report_macos.yml, .github/ISSUE_TEMPLATE/2_bug_report_windows.yml, .github/ISSUE_TEMPLATE/3_bug_report.yml, .github/ISSUE_TEMPLATE/4_bug_report_build.yml, .github/ISSUE_TEMPLATE/5_feature_request.yml
This helps weeding out the low-quality feature requests that really are questions.
=> github/issue_template: ask users to check for already supported features

DOCS/interface-changes/numpad-symbols.txt, DOCS/man/mpv.rst, DOCS/man/options.rst
Clarify a few newly added stuffs.
=> DOCS: numpad/pitch doc fixes

player/lua/console.lua
numpad + - * / was remapped to KP_ADD/KP_SUBTRACT/KP_MULTIPLY/KP_DIVIDE in #14660
=> console.lua: add numpad + - * / keybindings

DOCS/interface-changes/rename-vf-format-chroma-loc, DOCS/man/vf.rst, video/csputils.c
This field was removed in c6b92884658f37f7ea9b55a595ddd252c57202c0
=> DOCS/man/vf: don't document removed vf_format field

fuzzers/common.h, fuzzers/fuzzer_options_parser.c, fuzzers/meson.build, player/client.c
To improve coverage of parse_commandline.c
=> fuzzer_options_parser: add options parser fuzzing

video/out/wayland_common.c
Since a6683ea3c938d590a4fba4f65a1ad5e4d1ca1d8e it is possible to bind MBTN_LEFT to something useful without conflicting with VO dragging. However, currently wayland edge resizing is an exception and trying to resize still triggers MBTN_LEFT. This is not a problem on win32 which does not pass these inputs to the input system.
Fix this on wayland to do the same.
=> video/out/wayland_common: don't pass mouse inputs on resizing edges

player/command.c
=> command: expand ~ paths in load-config-file

video/mp_image.c, video/out/gpu/libmpv_gpu.c, video/out/gpu/video.c, video/out/vo_gpu.c
Fixes #14787
@na-na-hi I don't know if this is 100% correct, can you take a look?
=> vo_gpu: restore dovi mapping after guess_csp 

sub/osd.c, sub/osd_libass.c, sub/osd_state.h
=> sub: remove dead code

osdep/io.c, osdep/io.h
=> osdep/io: redefine off_t for Windows build

DOCS/man/options.rst
See: https://github.com/mpv-player/mpv/pull/9537
=> DOCS/man/options: update defaults for `--hwdec-codecs`

input/input.c, input/keycodes.h, video/out/wayland_common.c
Supersedes https://github.com/mpv-player/mpv/pull/14803
=> video/out/wayland_common: set key state only on keyboard_enter keys

player/lua/stats.lua
=> stats.lua: don't use ASS tags when use_ass is false

player/lua/ytdl_hook.lua
These might be useful
Fixes #14833
=> ytdl_hook: add some more yt-dlp tags

.github/workflows/comment.yml
See: https://github.com/mpv-player/mpv/actions?query=is%3Afailure+event%3Aworkflow_run
=> workflows/comment: prevent failed comment workflow spam

.github/workflows/build.yml, ci/build-msys2.sh
See: https://github.com/msys2/MINGW-packages/commit/1e7737f090e651059d5127d92ab117aa7654fd3e
=> ci/msys2: disable some features for 32-bit build

meson.build, player/main.c
=> player/main: guard smtc.h include

player/lua.c
Less invasive version of #14905.
=> lua: minor tweaks

audio/out/ao_coreaudio_utils.c
Fixes #14828.
@forthrin can you confirm the fix?
=> ao_coreaudio: fix nan in ca_get_device_latency_ns

DOCS/interface-changes/nvidia-true-hdr.txt, DOCS/man/vf.rst, video/filter/vf_d3d11vpp.c
=> vf_d3d11vpp: add NVIDIA RTX Video HDR support

options/m_config_frontend.c, options/m_option.h, video/decode/vd_lavc.c
this has been bothering me for a while
=> options: enable handling --no-hwdec as --hwdec=no

ci/build-mingw64.sh
And change the mirror to working one.
=> ci/mingw: update freetype to 2.13.3

filters/f_hwtransfer.c
Well, this was thinko on last minute code simplification I made. We need to check both input and output formats.
=> f_hwtransfer: fix too aggressive preference to use direct upload format

DOCS/man/input.rst, osdep/mac/swift_extensions.swift, video/out/mac_common.swift
=> mac: fixes some typos and a resize issue

video/out/wayland_common.c
Fixes: 2274311b259b7b03e3764ab4c21d69988b70a337
Fixes: #15022
=> wayland: replace old keymap if we receive a new keymap event

player/command.c
`av_timecode_make_string()` divides by fps unconditionally. And
relying on container_fps always carrying a meaningful value was
misguided. So we now check that fps is non-zero before calling that
function.
Issue encountered with a couple of old FLV files triggering a segfault.
=> command: avoid division by zero in av_timecode_make_string()

player/lua/console.lua
Instead of considering every non-ASCII character 2-cell wide, use this newly introduced property to let msg.c clip the select menu using all available with.
=> console.lua: use ${term-clip-cc} to clip lines

video/out/cocoa_cb_common.swift, video/out/mac/gl_layer.swift
just a test to see if this is actually the problem.
=> cocoa-cb: only request EDR on opengl layer for supported color spaces

video/out/wayland_common.c
~1. Support `--target-prim` and `--target-trc`.~
2. Map PL_COLOR_TRC_BT_1886 to XX_COLOR_MANAGER_V4_TRANSFER_FUNCTION_BT709
=> add more color stuff for vo_dmabuf_wayland

player/command.c, player/core.h, player/loadfile.c, player/playloop.c, player/sub.c, sub/sd_ass.c
=> sub redrawing improvements/fixes

DOCS/man/options.rst, video/out/filter_kernels.c
See discussion here:
https://code.videolan.org/videolan/libplacebo/-/issues/329
https://code.videolan.org/videolan/libplacebo/-/merge_requests/679
=> Credit ImageMagick where applicable

common/msg.c
Fixes: 6aa331289f10b12622fadc1589092276d30296aa
=> msg: fix width with ellipsis

.github/workflows/build.yml, ci/build-common.sh, ci/build-freebsd.sh, ci/build-linux-old.sh, ci/build-macos.sh, ci/build-mingw64.sh, ci/build-msys2.sh, ci/build-openbsd.sh, ci/build-tumbleweed.sh, misc/io_utils.c, osdep/windows_utils.c
=> ci: refactor ci so common args are picked from one location

.editorconfig
noticed on irc by @Akemi and I think it's bad idea too
=> Revert "editorconfig: punish tab usage"

common/msg.c, misc/codepoint_width.c, player/osd.c, test/codepoint_width.c
Also fix formatting while at it.
Fixes: bf025cd289ab6e5f094204d8aee070811fd99bdf
=> msg: add newline conditionally

.github/workflows/build.yml
It has been set in our docker container.
=> workflows/build: remove safe.directory git config

osdep/io.c
This also removes \n from the end of the string, which shouldn't be present in this string.
=> osdep/io: remove duplicated code for error to string conversion

player/command.c
=> command: don't print unneeded new lines for track-list

DOCS/man/osc.rst, player/lua/osc.lua
And add script-opts to configure the fullscreen button bindings.
=> osc.lua: cycle window-maximized when right clicking fullscreen

player/command.c, player/command.h, player/loadfile.c
Extract track metadata formatting out of loadfile.c to reuse in the track-list property.
=> command: print track metadata in ${track-list}

Copyright
Fixes some inaccurate descriptions.
=> Copyright: various fixes

player/lua/osc.lua
=> osc.lua: increase the title font size in box layout

player/lua/osc.lua
=> osc.lua: hide immediately without animation for select.lua

DOCS/interface-changes/sub-ass-override-blur.txt, DOCS/man/options.rst, sub/sd_ass.c
https://github.com/libass/libass/commit/4df64d060a8a89b2cd54678190426079bb9d49a6
Fixes: https://github.com/mpv-player/mpv/issues/14852
=> sub/sd_ass: set ASS_OVERRIDE_BIT_BLUR if available

audio/out/ao_audiotrack.c
The detailed issue is here:
https://github.com/mpv-player/mpv/issues/15212
problem: Since The AudioTrack is not an mpv instance level but a global object, it cannot support multiple mpv instances at the same time. For example, if you create two instances and then destroy one of them, the other instance may crash.
Add jni usage count to fix this.
=> ao_audiotrack: make audiotrack jni multi-instance and multi-thread safe

video/out/wayland_common.c
xdg_toplevel_resize_edge enum values allow for this to work, e.g. `TOP | LEFT = TOP_LEFT`
No functional change.
=> wayland: cleanup check_for_resize function

player/lua/console.lua
Now that default OSD margins have been decreased to 15 it is reasonable to let console.lua inherit them for consistency.
=> console.lua: use OSD margins

video/out/wayland_common.c
=> wayland: don't print same message for fractional and wl_surface scale

player/lua/console.lua
=> console.lua: highlight the first completion in the terminal

DOCS/man/options.rst, video/filter/vf_gpu_vulkan.c, video/out/vulkan/context.c, video/out/vulkan/context.h
=> vulkan/context: propagate --gpu-sw when using vulkan

DOCS/man/mpv.rst, etc/input.conf
Same as https://github.com/mpv-player/mpv/commit/d06f3d39cb840f8839e8d0ef9ff1fa065651031f. 
Fixes: https://github.com/mpv-player/mpv/issues/15416
=> etc/input.conf: add KP_PLUS/KP_SUBTRACT key bindings

demux/demux_lavf.c
1. Utilize `av_stream_get_side_data` instead of looping over all side data entries. This simplifies the code.
In theory if you had multiple entries in a single stream for the same side data type, the looping could be required, but as far as I can tell 41ba6dad721e618c0e54315bd72ad28afbd7b622 makes no mention of this being an issue, and I don't think the official side data helper functions ever made this possible? Thus this probably was just missing the required helper functionality or it wasn't noticed back in 2014?
2. Simplify the function by utilizing early exit and always setting the album data to track data, if track data is available. This lessens the depth of required if/else structures and makes sure we do not actually export a `replaygain_data` structure internally if there was no …
=> demux_lavf: replaygain export simplification

DOCS/man/mpv.rst
It is hard to discover otherwise.
=> DOCS/man/mpv: document that g-e selects disc titles

demux/demux_mkv.c
Fixes: 84ee84abb8bd13a50101a896f451c8853f4706dd
=> demux_mkv: fix memory leak of codec params

DOCS/man/osc.rst
=> DOCS/man/osc: update track middle-click action

DOCS/man/console.rst
See: https://github.com/mpv-player/mpv/pull/15355
=> DOCS/man/console.rst: remove outdated issue

DOCS/man/mpv.rst
Some users did not realize this is possible.
=> DOCS/man/mpv: document that you can deselect the current track

osdep/mac/remote_command_center.swift
follow up of #15115
since we load covers/images directly in a our own thread and the quick look thumbnailing also works asynchronously on its own thread, we need sync/coordinate both threads. otherwise it would be possible that a cover from a different file could overwrite the cover of the current file.
to prevent this every cover generation has a unique timestamp and only covers for the last cover timestamp will ever be shown.
we are also not interested in icon type thumbnails, since those are just generic file type icons.
quick look thumbnails can only be generated if quick look can read those files. files unknown to macOS don't work out of the box and you need to install a quick look extension for this, "QuickLook Video" for mkv.
=> mac/remote: add Quick Look thumbnail as cover fallback

common/version.h.in
Copyright year update speed ranking to fill PR space:
2020: wm4 committed 2019/12/31 11:10 (https://github.com/mpv-player/mpv/commit/934f8e102682901d77e0990aa594f46d745e0396)
2014: wm4 committed 2013/12/31 18:00 (https://github.com/mpv-player/mpv/commit/66fe4f571371b06b84c9e9cd684df9f7fc90b53f)
2015: wm4 committed 2014/12/31 18:00 (https://github.com/mpv-player/mpv/commit/39548ad9e961794e023aef0e281089064dd41f36)
2016: wm4 committed 2015/12/31 18:18 (https://github.com/mpv-player/mpv/commit/de0523ba7b4f76a1c51cc3924b3fcace51fc8e16)
2017: wm4 committed 2017/01/01 13:09 (https://github.com/mpv-player/mpv/commit/8e41f314f19d97849204ff4a7e9ca0fc4e9a8904)
2018: wm4 authored and wiiaboo committed 2018/01/01 16:05 (https://github.com/mpv-player/mpv/commit/a90abe05462a689e55280bc78af2999aa1f3823e) …
=> version.h.in: bump copyright year

audio/out/ao_avfoundation.m, audio/out/ao_coreaudio.c, audio/out/ao_coreaudio_chmap.c, audio/out/ao_coreaudio_chmap.h
This fixes #15584
@low-batt PTAL
=> ao_coreaudio: set kAudioOutputUnitProperty_ChannelMap

player/lua/stats.lua
=> stats.lua: fix page 2 and 0 layout

options/m_option.c
Fixes: a173b477487d7bb7e6d20fd3d8f5d2ee4e0504a6
Fixes: #15667
=> options/m_options: fix scientific notation timestamp parsing

video/out/wayland_common.c
Some Wayland clients not offering text/plain will send their non-text data regardless of the MIME type requested in wl_data_offer.receive. We should just not call receive if they haven't offered a MIME type we want.
If receiving images or other formats from the native clipboard is going to be a thing in the future, instead of this, a MIME score mechanism similar to what is used in dnd will need to be used to choose what to request, with a minimum score required to ignore offers which don't offer a MIME type we want.
BTW, I think it would be a good idea to do the transfer asynchronously with the event loop or dedicated thread. Large clipboard data (or misbehaving clients) may noticeably stall the vo thread. With text only, this is at least very uncommon. The motivation for this patch was …
=> video/out/wayland_common: ignore clipboard offers w/o wanted MIME type

stream/dvb_tune.c, stream/dvb_tune.h, stream/stream_dvb.c
Change MPlayer to mpv and the last sentence like all other files.
=> various: update license headers

DOCS/man/options.rst, misc/dispatch.c, stream/dvb_tune.c, stream/dvb_tune.h, stream/dvbin.h, stream/stream_dvb.c, video/out/drm_common.c, video/out/wayland_common.c
Various fixes related to `poll()`.
=> poll fixes

DOCS/man/console.rst, DOCS/man/lua.rst, DOCS/man/mpv.rst, DOCS/man/select.rst
Also update console's documentation.
Depends on #15655.
=> DOCS/man/select: add this file

DOCS/man/select.rst
Also remove select/ from the last 2 script bindings.
=> DOCS/man/select: document the menu script-binding

DOCS/interface-changes/osc-script-messages.txt, DOCS/man/osc.rst, player/lua/osc.lua
=> misc osc stuff

player/clipboard/clipboard-wayland.c
Fixes: https://github.com/mpv-player/mpv/issues/15763
=> clipboard-wayland: initialize offer fd

DOCS/interface-changes/list-option.txt, DOCS/man/mpv.rst, options/m_option.c
=> list option improvements

player/core.h, player/osd.c, player/sub.c, player/video.c
=> player: print secondary subtitles on the terminal

video/out/vo_kitty.c
When playing a video, 55% of CPU used in strlen, callgraph flip_page: ta_talloc_strdup_append and ta_talloc_asprintf_append and ta_talloc_strndup_append
Before the fix: 2 fps when playing 1080p 24 fps video (--vo-kitty-use-shm=no), 24 fps after the fix.
=> video/out/kitty: make it ten times faster by avoiding strlen

player/lua/console.lua
I'm not sure when this broke but completions after command prefixes were not being updated.
=> console.lua: fix completion after command prefixes

test/libmpv_test_track_selection.c, test/samples/meson.build
Because you can never have too many tests.
=> test/libmpv_test_track_selection: add another multilang selection test

DOCS/man/input.rst
Finally document the property added in 953d225368.
=> DOCS/man/input: document the clock property

DOCS/man/input.rst
=> DOCS/man/input: fix typo

DOCS/man/af.rst, DOCS/man/ao.rst, DOCS/man/input.rst, DOCS/man/options.rst, DOCS/man/vf.rst, DOCS/man/vo.rst
This is already done for other types of list options.
=> DOCS/man: document options which are object settings list options

stream/stream_dvdnav.c
Also parent priv->filename to priv to simplify the cleanup process.
=> stream_dvdnav: properly cleanup on error and fix some memory leaks

etc/restore-osc-bindings.conf
Changed in b0364f876125d4eb45c5cb3c4289b7e3e2100796.
=> etc/restore-osc-bindings.conf: add previously unbound actions

sub/osd.c, video/out/vo_gpu_next.c
=> sub/osd: remove bogus osd redraw notification resetting

demux/demux_mkv.c, demux/stheader.h, filters/f_decoder_wrapper.c
=> demux_mkv: add support for chroma location

video/out/w32_common.c
We only need to return VO_NOTIMPL for them, no need to mp_dispatch_run() and wait for GUI thread to response that.
=> w32_common: avoid any unsupported VOCTRL to synchronize GUI thread

DOCS/man/mpv.rst, stream/stream_edl.c, stream/stream_mf.c, stream/stream_mpv.c
=> stream_mpv: restrict only to network links

etc/mpv.fish, meson.build
It is an adaptation of the bash completion.
=> fish completion: add initial implementation of the fish completion script

player/lua/console.lua
Make it consistent with other scripts.
=> console.lua: use double quotes

ci/build-win32.ps1, osdep/language-win.c, test/libmpv_test_track_selection.c
~~For win32 build this needs https://gitlab.freedesktop.org/gstreamer/meson-ports/ffmpeg/-/merge_requests/141 for actually run the test.~~ (merged)
=> test/libmpv_test_track_selection: fix test and real impl

video/out/vo_dmabuf_wayland.c
=> vo_dmabuf_wayland: hwdec selection improvements

DOCS/interface-changes/osd-cache-opts.txt, DOCS/man/options.rst, options/options.c, options/options.h, sub/osd_libass.c, sub/sd_ass.c
=> Various options to control libass cache and shaper

video/out/wayland_common.c
=> wayland: check if we have color representation manager first

DOCS/interface-changes/background-tile.txt, DOCS/man/options.rst, video/out/gpu/video.c, video/out/gpu/video.h, video/out/vo_gpu_next.c
=> video/out/gpu/video: add options to control background tile appearance

input/cmd.c, options/m_config_frontend.c, options/m_option.c, options/m_option.h, options/m_property.c
Was poking around at something else and noticed this.
=> minor m_option parsing simplifications

DOCS/man/options.rst, sub/ass_mp.c, sub/img_convert.c, sub/img_convert.h, video/out/vo_gpu_next.c
Render subs at video resolution. Important for performance of some heavy typesetting.
=> vo_gpu_next: add support for blend-subtitles=video

video/out/wayland_common.c
The xdg-shell spec states: "If never set, the value is the full bounds of the surface, including any subsurfaces. This updates dynamically on every commit. This unset is meant for extremely simple clients"
mpv's window geometry is never anything other than the full bounds of the surface, including any surfurfaces, so we don't need to set this ourselves. This was added in 828dd65ef84b4d8e95e70752b9eb0833909d1d23 to workaround a Weston bug, and isn't needed anymore.
Tested on wlroots compositors, kwin and weston.
=> wayland: leave window geometry unset

ci/build-mingw64.sh
=> ci/mingw: add lcms2

DOCS/interface-changes/win32-wid0.txt, DOCS/man/options.rst, video/out/w32_common.c
https://github.com/user-attachments/assets/21996be3-aa8a-4eba-a263-5f0d57111573
Closes #10332.
=> video/out/w32_common: support --wid=0

DOCS/interface-changes/console-gap.txt, DOCS/man/console.rst, DOCS/man/context_menu.rst, player/lua/console.lua, player/lua/context_menu.lua
=> console.lua: increase the gap between menu items

video/out/vo_dmabuf_wayland.c
c958990833f86747ffe290950495921bf4c73218 was supposed to implement this, but it got forgotten and the placeholder code which just created/destroyed every buffer for every frame was left. Oops. Finally fix this a couple of years later.
Fixes #16863.
=> vo_dmabuf_wayland: actually reuse OSD buffers
