mpv-player/mpv

video/mp_image.c
These helpers, for some reason, decided to round the returned values up
to multiples of the nearest plane alignment. This logic makes no sense
to me, and completely breaks any sort of oddly-sized mp_image.
This logic was introduced, presumably in error and without real
justification, as part of a major refactor commit (caee8748), As far as
I can tell, removing it again doesn't regress anything.
Fixes several serious bugs including buffer underflows and GPU crashes
in vo_gpu and vo_gpu_next.
=> mp_image: fix mp_image_plane_w/h

meson.build, video/out/vo_gpu_next.c, wscript
libplacebo v198 fixed this properly by adding the ability to flip planes
directly, which is done automatically by the swapchain helpers.
As such, we no longer need to concern ourselves with hacky logic to flip
planes using the crop. This also removes the need for the OSD coordinate
hack on OpenGL.
=> vo_gpu_next: remove/simplify plane flipping hacks

player/lua/ytdl_hook.lua
Some youtube_dl extractors retrieve URLs which contain other URLs
inside of them, for example Funimation, like this:
`https://example.com/video?parameter=https://example.net/something`
The url_is_safe function uses a pattern to match the protocol at the
start of the URL. Before this commit, this pattern was not compliant
with the URL spec (see the definition of "A URL-scheme string"):
https://url.spec.whatwg.org/#url-writing
Therefore it would match any characters, including "://", until the
last occurence of "://" in the string. Thus the above URL would match
`https://example.com/video?parameter=https`
which is not in safe_protos so the video will not play.
Now the protocol can only start with a letter and only contain
alphanumerics, "." "+" or "-" as the spec says, so it will only match …
=> ytdl_hook: fix url_is_safe to match URL protocols properly

filters/f_auto_filters.c
A few years ago, in 25e70f4743c44db59fe8fc902c93a966d95ba8c3, we
disabled the vavpp deinterlacing auto-filter on the basis that it
caused crashes on _some_ hardware with _some_ driver version(s). But
since then, the situation has improved. There is still a limitation
where you can't turn deinterlacing on on the fly with AMD, but it
doesn't crash anymore (That is #7388).
So, given that AMD users have to set up the deinterlacing filter
manually either way, let's re-add the auto-filter for Intel users.
=> filters: Re-add vavpp deinterlacing auto-filter

DOCS/man/options.rst, DOCS/man/vo.rst
The documentation's current discussion of hwdec usage is out of date,
and unnecessarily pessemistic when applied to modern hardware. The
reality is that modern APIs on modern hardware produce reasonable
results and there's no need to pretend otherwise. The current language
that tries to drive people away from using hwdecs at all leads to them
making bad choices when they do try to use it.
Let's also make it clearer that users should use vo=gpu with hwdecs
rather than vo=vaapi or vo=vdpau. Even the existing admonitions have
proven insufficient, so let's strengthen that language.
=> DOCS/options.rst DOCS/vo.rst: Update discussion of hwdec usage

video/out/hwdec/hwdec_vaapi.c, video/out/hwdec/hwdec_vaapi_gl.c
Our logging here today is very poor. We don't make it clear what
formats we are probing, or even that a certain format failed in most
cases. In the case where we do log the error, we don't make it clear
which format it was that failed.
The end result is that we have no idea what the possible and final
format spaces are, which makes it very hard to debug whether things are
working correctly, or to work on supporting additional formats.
=> vo_gpu: hwdec_vaapi: Improve logging when probing surface formats

filters/filter.c, video/decode/vd_lavc.c, video/filter/vf_d3d11vpp.c, video/hwdec.c, video/hwdec.h, video/out/gpu/hwdec.c, video/out/gpu/hwdec.h, video/out/gpu/video.c, video/out/gpu/video.h, video/out/hwdec/hwdec_cuda.c, video/out/vo_gpu.c, video/out/vo_gpu_next.c
When I introduced the concept of lazy loading of hwdecs by img format,
I did not propagate the probing flag correctly, leading to the new
normal loading path not runnng with probing set, meaning that any
errors would show up, creating unnecessary noise.
This change fixes this regression.
=> vo_gpu[_next]: hwdec: fix logging regression when probing

player/lua.c
Stacktraces before (incorrect):
<pre>
[test] stack traceback:
[test] 	[C]: in function 'error'
[test] 	[string "/home/stefan/.mpv/scripts/test.lua"]:1: in main chunk
[test] 	[C]: in ?
[test] 	[C]: in ?
</pre>
after:
<pre>
[test] stack traceback:
[test] 	[C]: in function 'error'
[test] 	/home/stefan/.mpv/scripts/test.lua:1: in main chunk
[test] 	[C]: in ?
[test] 	[C]: in ?
</pre>
=> lua: use correct chunkname when loading script files

osdep/atomic.h, sub/osd.c, sub/osd_state.h
mpv/core's `write_video` calls `osd_set_force_video_pts`, thus interacting with `osd->lock`:
https://github.com/mpv-player/mpv/blob/1c2dde91d369987199782f4914f56019e5a2272c/player/video.c#L1141-L1144
typically this is not a problem, but in the case of `vo_rpi` the vo thread also interacts with `osd->lock` via `update_osd` which ends up calling into `mpgl_osd_generate` > `osd_draw` > `osd_render`
i observed cases where mpv/core was stalling due to slow osd rendering on the VO thread, causing issues with sync calculations
with this PR, mpv/core no longer touches `osd->lock` decoupling the video thread from the core.
=> Use atomic for osd_state.force_video_pts to reduce contention with vo thread

video/decode/vd_lavc.c
The field has been deprecated, yet the upcoming new default is not yet
the default. Thus, until lavc major hits 60 and the default behavior
finally gets changed, we have to explicitly set the field's value.
The deprecation had already been handled by adding the required
version limitation for this code in bbbf3571edfbb0e849d3ef60148743352b84fe84 ,
this change merely just removes the warning which would otherwise
appear until lavc major version gets bumped to 60.
=> vd_lavc: hide a deprecation warning in already handled compatible code

DOCS/man/vo.rst, video/out/drm_atomic.c, video/out/drm_atomic.h, video/out/drm_common.c, video/out/drm_common.h, video/out/opengl/context_drm_egl.c
Variable Refresh Rate (VRR), aka Freesync or Adaptive Sync can be used
with DRM by setting the VRR_ENABLED property on a crtc if the
connector reports that it is VRR_CAPABLE. This is a useful feature
for us as it is common to play 24/25/50 fps content on displays that
are nominally locked to 60Hz. VRR can allow this content to play at
native framerates.
This is a simple change as we just need to check the capability
and set the enabled property if requested by the user. I've defaulted
it to disabled for now, but it might make sense to default to auto
in the long term.
=> drm: context_drm_egl: add support for enabling VRR

player/lua/options.lua
val2str isn't used anywhere. Its only use was removed in dd3e52fe68,
when it was still part of osc.lua.
=> options.lua: remove unused function

video/out/x11_common.c
9a7b2015e1a711a57b6e660774c36956ac59a7f6 added the --screen-name option
for x11, but it was unfortunately broken. The commit does correctly
handle vo_x11_update_screeninfo and select the correct screen. However,
vo_x11_sizehint was missed. Specifically, the force_pos bool was always
false because it only took into account --screen being set and not
--screen-name. To fix this, just add an extra condition to the force_pos
bool so it becomes true if there's a string in --screen_name. Fixes
issue #9877.
=> x11: fix screen-name option

meson.build, video/out/gpu/hwdec.c, video/out/gpu/hwdec.h, video/out/vo_gpu_next.c, wscript
This makes use of the new frame acquire/release callbacks to hold on to
hwdec images only as long as necessary. This should greatly improve the
smoothness/efficiency of hwdec interop, by not holding on to them for
longer than needed.
This also avoids the need to pool hwdec mappers altogether.
Should fix #10067 as well, since frames are now only mapped when we
actually use them.
=> vo_gpu_next: switch to unpooled hwdec mapping

video/out/d3d11/context.c, video/out/d3d11/ra_d3d11.c, video/out/d3d11/ra_d3d11.h
Instead of always having the reference outside of calling resize,
request a backbuffer at start and relieve the backbuffer at
submission for presentation.
=> vo_gpu/d3d11: mimic libplacebo backbuffer usage

video/decode/vd_lavc.c
The VO is available during decoder initialization mostly for direct
rendering purposes, so if f.ex. a complex filter chain is utilized,
there is no video renderer information available via
mp_filter_find_stream_info during creation of the decoder filter.
Thus, check for whether the VO is available before attempting to
check the capabilities flag from it.
Additionally - to simplify logic - makes explicitly requesting GPU
film grain to always disable decoder film grain functionality. The
warning is still shown if the VO is available and no support for
film grain application is available.
Fixes #10079
=> vd_lavc: fix decoder initialization when no VO is available

video/decode/vd_lavc.c
This fixes build failures with avcodec 58.113.100 or before,
matching FFmpeg release versions 4.0 to 4.3.
This flag was added in between avcodec 58.113.100 and 58.114.100
during the FFmpeg 4.4 development cycle. It lacks its own version bump,
so instead a check for the define is utilized instead.
Additionally, warn the user if they request GPU film grain with
too old of an FFmpeg.
Fixes #10088
=> vd_lavc: fixup unchecked usage of AV_CODEC_EXPORT_DATA_FILM_GRAIN

video/out/vo_wlshm.c
draw_image is an old API that was deprecated long ago. However when
wlshm was originally added, it used draw_image. There's no particular
reason for this and it can trivially be switched to draw_frame instead.
This has some real advantages (notably --vo=wlshm --idle --force-window
actually works).
=> vo_wlshm: use draw_frame instead of draw_image

DOCS/man/input.rst, DOCS/man/mpv.rst, DOCS/man/options.rst
This adds a section to the documentation to explain how resuming playback works, and in particular it explains how it affects which playlist entry mpv starts playing from, since this feature was only implied in the --playlist-start documentation.
It also groups the documentation of the watch later options together to make them easier to find.
=> DOCS/{mpv,options}: document the watch later functionality

DOCS/man/options.rst
move the incorrect description of --sub-border-color to --sub-shadow-color
a tiny fix typo in --sub-justify
=> DOCS: fix typo in options_subtitles

DOCS/man/input.rst
The current one hasn't worked in years.
=> DOCS/input: update the ASS tags documentation URL

DOCS/man/options.rst
- Say built-in which is more common than builtin
- Remove "By default" because it implies that the keybindings are
customizabile, and with it the sentence had wrong punctuation and
case
- Remove an extra space
- The script is called console.lua, not repl.lua
=> DOCS/options: update the --load-osd-console documentation

.github/workflows/build.yml
Recently, git patched a CVE which makes it much more strict about
different users operating on directories they don't own. For us, this
causes breakage with version.sh and version.py since they both run a git
describe command to fetch the commit hash. Currently, this only affects
the tumbleweed container (likely because it was recently changed) and
thus the git describe command always errors out. Workaround this by just
explictly adding the mpv directory as a safe directory for git.
=> github/workflows: workaround git permissions error

video/out/vo_gpu_next.c
It is possible for vo_gpu_next to attempt a resize before the windowing
backend is fully initialized. In practice, this can happen on wayland
which means libplacebo attempts a 0x0 resize. Depending on the API, a
0x0 resize may be allowed (vulkan or d3d11), but libplacebo just returns
a 0 in this case which mpv doesn't do anything with anyway. In the case
of opengl, this usage is explictly forbidden and will result in a
warning which may confuse users. Solve this by just not trying a resize
if dwidth and dheight in the vo are not available. Fixes https://github.com/mpv-player/mpv/issues/10083.
=> vo_gpu_next: avoid 0x0 resizes

video/out/vo_wlshm.c, video/out/wayland_common.c
Since 2018, wl_surface_damage_buffer has been explicitly preferred and
recommended over wl_surface_damage*. mpv was still using the old
function in a couple of spots. The only difference is that we need to
pass buffer coordinates instead of surface coordinates. In vo_wlshm,
this is done by using vo->dwidth/vo->dheight since that is always used
whenever wl_buffers are created. In the case of the cursor surfaace, we
actually already passed buffer coordinates to it (img->width/height)
which was probablly technically wrong with wl_surface_damage, but it
doesn't really matter in practice. This requires bumping wl_compositor
to version 4 which is no problem since this dates back to 2015*.
https://gitlab.freedesktop.org/wayland/wayland/-/commit/921d0548035673a1bf6aeb9396b9bc728133411e …
=> wayland: use wl_surface_damage_buffer

demux/demux.c
This pull request adds support for r128 replaygain tags: "R128_TRACK_GAIN" and "R128_ALBUM_GAIN", which are part of opus specification. As the specification prefers "R128_\*" tags to "REPLAYGAIN_\*" tags, it's the common practice for tagging gain values in opus files.
The pr should resolve the issue #5079.
=> demux: add support for r128 replaygain tags

video/image_writer.c
Allow `screenshot-high-bit-depth=yes` to work with JPEG XL
screenshots when `screenshot-sw=no` is set. They already work
as expected when `screenshot-sw=yes` is set, but this allows
the hardware screenshots to work this way too.
=> video/image_writer: fix high-depth JPEG XL screenshots

player/lua/console.lua
09ea3a424fe moved the console above the OSC when it is visible so they
don't overlap, but only changed the first ass:pos() call and forgot to
update the second one, which redraws the cursor on top of the text, so
when both the OSC and the console are visible, a second cursor is drawn
on the OSC. You have to type past where the buttons are to notice it.
This commit synchronizes the position of the 2 ASS events.
=> console.lua: don't render a 2nd cursor on the OSC

video/image_writer.c
If screenshot-tag-colorspace=yes, then set the corresponding
fields in AVCodecContext, not just in AVFrame.
=> video/image_writer: tag colorspace in AVCodecContext

.github/workflows/build.yml
Apparently it is now in public beta.
ref actions/virtual-environments#5446
=> github/workflows: add macOS 12 build

video/out/opengl/context_drm_egl.c
These values and options were simply never looked at in the drm egl
context. This pretty much is just a copy and paste of what is in vo_drm.
Fixes #10157.
As an aside, if someone is bored, a lot of the drm code could be merged together. It'd be a little involved though.
=> context_drm_egl: support monitor par

generated/meson.build, meson.build
Some compiler flags were passed to mpv in order to get it to build as a
gui application on windows. However on the meson build, this always
resulted in mpv being built as a console application. This is because
the function for making executables in meson specifically has a kwarg
called win_subsystem* which defaults to 'console'. That always added
link arguments at the end which compiled mpv.exe as a console
application. The correct thing to do is to remove all of the
subsystem-related flags in the meson build and use the win_subsystem
kwarg as intended by setting it to 'windows,6.0'. For mpv.com, we can
remove the -Wl,--subsystem,console flag since meson will set this by
default in that executable. This makes mpv.exe function correctly and
open with the pseudo-gui while mpv.com acts as a …
=> meson: compile mpv.exe as a win32 gui application

libmpv/client.h
Windows is weird and symbols weren't actually being exported. This is
because \_\_GNUC\_\_ is defined and picked up in the conditional, but
\_\_attribute\_\_((visibility("default"))) doesn't actually export anything
to the dll. Instead, just check if we have win32 defined first and then
always set __declspec(dllexport). Fixes #10171.
=> client API: always export symbols on windows

player/lua.c
If lua_pushstring is OOM, then our joined path allocation is leaked. Use autofree to ensure it's not leaked in case of Lua OOM.
=> lua: avoid rare memory leak in mp.join_path

DOCS/man/af.rst, TOOLS/dylib-unhell.py, TOOLS/macos-sdk-version.py, audio/filter/af_scaletempo2.c, audio/filter/af_scaletempo2_internals.c, audio/filter/af_scaletempo2_internals.h, audio/out/ao_sndio.c, meson.build, player/lua/stats.lua, sub/filter_sdh.c, video/out/gpu/shader_cache.c, video/out/w32_common.c
The modified paragraphs in af.rst could also just be reformatted instead of removing trailing spaces.
=> various: remove trailing whitespace

player/playloop.c
Normally with the keep-open option, mpv is supposed to set the
eof-reached property to true so clients can possibly do interesting
things at this step. However, there was actually an edge case where this
property notification did not occur. If you use keep-open and then seek
in the file past the end (so mpv stops), property notification is not
actually sent in this case. Internally, mpv does a very exact seek at
this step which also ends playback, but it does not set STATUS_EOF to
the ao and vo before the core idle state is updated. To fix this edge
case, it's simply just a matter of explictly setting STATUS_EOF after
seek_to_last_frame in handle_keep_open. This logic will only ever
trigger if keep-open is being used and the seek goes past the end of the
file, so we know that there will …
=> player: set EOF when seeking to end with keep-open

player/main.c
Both mpv's main function and the client API use mp_initialize to start
up. In general, these work the same however the client API had one
slight, unnecessary limitation: you can't start it up with idle=no. In
practice, the libmpv profile (used with the client API) sets idle to
yes, so it's rarely encountered, but there's no particular reason why
this policy needs to be enforced. It turns out that mp_initialize does a
quick check to see if there are any entries in the playlist and if idle
mode is set. If not, it prints the help message and exists. Basically,
it's just the part that handles the terminal message when you type "mpv"
with no arguments. Unfortunately with idle=no, the client API also hits
this code path, exits prematurely with 1 and thus returns an API error.
Fortunately, the …
=> player: check for argv before printing help text

DOCS/man/options.rst, DOCS/man/vo.rst, generated/wayland/meson.build, meson.build, video/out/drm_common.c, video/out/drm_common.h, video/out/vo.c, video/out/vo_vaapi_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h, wscript, wscript_build.py
This PR adds a new vo driver - `vaapi-wayland`, which outputs vaapi-decoded surfaces to a Wayland compositor without any extra copies to system RAM, and without using GPU resources for scaling or colour space conversion.
Command line:
`--hwdec=vaapi --vo=vaapi-wayland foo.mp4`
=> new vaapi-wayland vo driver

video/out/wayland_common.c
E.g. wl_subcompositor could be announced before wl_compositor.
=> wayland: don't depend on the order of global announcements

DOCS/man/osc.rst, player/lua/osc.lua
This is mainly for other user scripts that may conflict with the osc
logo in some way. While you can use script-message and
shared-script-properties (highly discouraged in the documentation for
some reason) to work around this, there's still some brittle edge cases
and complicated logic that can pop up. Adding an option for these two
things (the logo and the "drop files..." text) is really trivial and
would make things easier for scripts. Discussed in a couple of issues
below:
https://github.com/mpv-player/mpv/issues/10201
https://github.com/CogentRedTester/mpv-file-browser/issues/55
=> osc.lua: add idlescreen and osc-idlescreen

player/external_files.c
Maybe useful to others.
Does anyone else want them in cover_files[]?
=> player: add jxl and tiff/tif to list of image extensions

DOCS/man/options.rst
The `absolute` value was incorrectly labelled as the default instead of
the value named `default`, which was somewhat confusing. When the newer
default option was added in 679e410 it seems like wm4 forgot to remove
the label in the manual on the previous default.
=> DOCS/options: fix incorrect labelling of hr-seek default

video/out/opengl/context_wayland.c
Not sure if this has any deeper implications yet but it stops `mpv --no-config --window-maximized file.mkv` from throwing an error on weston.
=> wayland_gl: wait until resize to create egl_window

.github/workflows/build.yml, audio/aframe.c, audio/chmap.c, audio/chmap.h, audio/chmap_avchannel.c, audio/chmap_avchannel.h, audio/decode/ad_lavc.c, audio/filter/af_lavcac3enc.c, audio/out/ao_lavc.c, ci/build-mingw64.sh, ci/build-tumbleweed.sh, common/av_common.c, demux/demux_lavf.c, filters/f_lavfi.c, meson.build, test/chmap.c, wscript, wscript_build.py
This is the new FFmpeg channel layout API utilized in both AVFrames
and AVCodecContexts. The previous one has been deprecated.
Thus while we cannot yet require this new API, we can attempt to
support it if available (with the convenient effect of not having
unnecessary deprecation warnings).
=> add support for AVChannelLayout

video/out/vo_vaapi_wayland.c
1. Remove sync/desync calls in resize.  The resize() method only changes the subsurface's position, which is always synchronized with the parent surface. Reference:
https://wayland-book.com/surfaces-in-depth/subsurfaces.html
2. Only need to attach solid buffer once to main surface, on creation.
=> vaapi-wayland: clean up code

meson.build
In win32 build, if libass and libfontconfig appear after libmingwex
during linking, crash happens whenever fontconfig calls to opendir().
Moving them before ffmpeg (which pulls in libmingwex) makes sure they always appear first.
More info on https://github.com/shinchiro/mpv-winbuild-cmake/issues/217.
CI build passes: https://github.com/CrendKing/mpv/runs/6909174698.
=> meson: rearrange library dependency order to avoid crash with fontconfig

meson.build
Technically this was wrong. If you passed -Dvdpau=enabled but did not
have x11 (a requirement for this), the build would silently just not
build the vdpau VO. The correct behavior is for it to be a hard error.
Accomplish this by using the require function and making sure that x11
is indeed being used before attempting to find the library.
Just making sure this builds correctly first.
Edit: And works as expected.
=> meson: use require when checking for vdpau

video/out/x11_common.c
strcasestr is a GNU extension, but we can just use bstr instead to do
the same thing.
=> x11: replace strcasestr usage with bstr

video/out/x11_common.c
The old logic always reset the x11->has_mesa/has_nvidia values on every
loop through the provider. This meant that it would always just match
whatever the last provider happened to be. So in the case of a dual GPU
system, if nvidia was the very first provider and the integrated
intel/amd card was the second (in practice, this is probably mostly the
other way around), then mpv would set has_mesa to true and has_nvidia to
false and thus try to use presentation. This is not the intended
behavior. Just rework this by also checking x11->has_mesa/has_nvidia in
the loop so a true value from the previous iteration is preserved.
=> x11: correct provider detection logic

DOCS/interface-changes.rst, DOCS/man/options.rst, options/options.c, options/options.h, video/out/x11_common.c
The first commit just adds nouveau to the x11 whitelist (not strictly related but).
~~The second commit is the more interesting one that exposes whether or not to use presentation feedback. In the past, mpv has always just used it, but there's potentially some cases where someone would want to have yes/no control over it (particularly on xorg). Windows was omitted because I have no clue how it works. @rossy: no idea if it makes any sense for Windows to have yes/no type control but feel free to add a commit or something.~~
The second commit is now just a `no/auto/yes` toggle for using present on xorg.
=> x11: add --x11-present option

filters/f_swresample.c
This was introduced in 04257417 without a clear explanation of the bug
it was solving, so I have no idea if it's still needed (or why it ever
was). And it definitely creates unexpected behavior, e.g. forced
clipping when converting between float and floatp.
I therefore think we should simply remove this logic and see if it
regresses anything else, then fix those other bugs *properly* (if
they're still around).
Fixes #9979
=> swresample: don't forcibly clip on every conversion

meson.build
The idea is shamelessly stolen from gnome-remote-desktop. The meson
build does a lot of checks and if you aren't familiar with the internals
of the meson.build, it may not be clear what is actually enabled and
what isn't. Add a little pretty message at the bottom that quickly shows
what the current build has and does not. It's not meant to be
comprehensive. Rather, it's just a short list of the notable features.
=> meson: add a summary at the end of configuration

DOCS/man/osc.rst
This option was added in mpv-player@ec236f7, but its name in the document description is incorrect.
=> DOCS/osc: fix option "showidlescreen" -> "idlescreen"

video/out/opengl/context_x11egl.c
This was introduced in 7fb972fd3997bfa389caa7c1eb899ea4b8444083 and
later revised in f5a094db047ee0162774301a2ce4ed685ca9d539. Transparency
in EGL/X11 has been broken upstream for years in Mesa unfortunately.
However, the first commit claimed to have found a way to preserve
transparency by doing a trick with picking EGLConfigs (the second commit
revises this but keeps the logic in place). However, it doesn't appear
that the first commit actually fixes anything (transparency doesn't work
on my machine) and no one else seems to have reported it working. On the
other hand, if Mesa does ever actually fix this, transparency would
immediately be broken since mpv would always set the EGL_ALPHA_SIZE to
0. Go ahead and remove this since it doesn't seem to have any actual
utility and is technically …
=> context_x11egl: remove supposed transparency fix

meson.build
Fixes:
```
[20/228] Generating html-manpages with a custom command
FAILED: mpv.html
rst2html DOCS/man/mpv.rst ../DOCS/man/mpv.rst mpv.html
Usage
=====
rst2html [options] [<source> [<destination>]]
rst2html: error: Maximum 2 arguments allowed.
```
cc: @Dudemanguy
=> meson: fix rst2html command

video/out/placebo/utils.h
libplacebo 4.157[^1] rename context.h to log.h, and left a compatibility
header. In 5.x, this header has been removed.
Since we require libplacebo 4.157 to build mpv, we can just use log.h to
fix compatibility with 5.x.
[^1]: https://github.com/haasn/libplacebo/commit/2459200a133d1a0f36f092a32a2d5d443cfbee55
=> libplacebo: fix compatibility with libplacebo >= 5

player/lua/ytdl_hook.lua
Closes #8786 and #9978.
Also closes #10225, except not really because as it turns out bilibili now works even without setting HTTP headers (the JSON doesn't even contain them anymore).
Regardless they should always be set, just in case they are needed.
=> ytdl_hook: always set HTTP headers

DOCS/man/osc.rst, player/lua/osc.lua
This PR replaces the hyphen used to indicate time remaining in the on-screen controls with a U+2212 Minus Sign. The width of the time remaining/media duration region is also increased to accommodate the additional width of the minus sign relative to the hyphen.
Tested and screenshotted on Linux.
Before (hyphen):
After (minus sign):
=> osc.lua: use minus character with time remaining

video/out/d3d11/ra_d3d11.c
A VRAM memory leak was present in d3d11 when `idle=yes` and playback stops for an item. This patch re-enables some of the code which is only used during diagnostic which fixes the issue.
I had previously mentioned this and the fix in the #mpv IRC channel.  This resolves the leak in our testing so we are upstreaming it.
=> ra_d3d11: corrected VRAM leak.

video/out/hwdec/hwdec_vaapi.c, video/out/hwdec/hwdec_vaapi_gl.c, video/out/hwdec/hwdec_vaapi_pl.c
This is somewhat academic for now, as we explicitly ask for separate
layers and the scenarios where multi-plane images are required also use
complex formats that cannot be decomposed after the fact, but
nevertheless it is possible for us to consume simple multi-plane
images where there is one layer with n planes instead of n layers with
one plane each.
In these cases, we just treat the planes the same as we would if they
were each in a separate layer and everything works out.
It ought to be possible to make this work for OpenGL but I couldn't
wrap my head around how to provide the right DRM fourcc when
pretending a plane is a layer by itself. So I've left that
unimplemented.
=> hwdec_vaapi_pl: support simple multi-plane image formats

.github/workflows/build.yml
----
GitHub Action is sunsetting the macOS 10.15 Actions runner. It will stop working intermittently until being completely removed by 2022-8-30: https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
I have checked [`vmactions/freebsd-vm`](https://github.com/vmactions/freebsd-vm) does support `macos-12` (which requires `vmactions/freebsd-vm@0.2.0`). The default FreeBSD version of `vmactions/freebsd-vm@0.2.0` is still 13.1.
I have updated the `runs-on` to …
=> ci: bump macos runner version

player/lua/ytdl_hook.lua
The example given in #3024 would not play the correct video when combined with `--ytdl-raw-options=yes-playlist=`.
Allowing `youtube:tab` as extractor and correcting the id check fixes that.
=> ytdl_hook: fix playlist index extraction

video/mp_image.c
plane_clear[p] is never NULL, so it never affects the conditional
=> video: remove unnecessary code

video/out/opengl/hwdec_drmprime_drm.c
On S905X (meson) boards drmModeAtomicCommit called from
disable_video_plane in hwdec_drmprime_drm.c might still be running when
another call is made from queue_flip in context_drm_egl.c.
This causes EBUSY error in queue_flip, and causes mpv to hang.
=> drm: avoid drmModeAtomicCommit races by blocking

video/out/drm_common.c
=> drm_common: skip cards that don't support KMS for autodetection

audio/out/ao_pipewire.c
Note:
It would also be possible to redirect the logging of the pipewire library to the mpv logging subsystem. Not sure if it makes sense though.
=> ao_pipewire: use mpv logging

audio/out/ao_pipewire.c
This came up during my other work.
It doesn't seem to make a difference but should be more correct according to the docs.
=> ao_pipewire: tell audio server about number of queued samples

player/audio.c
This gives pull-based AOs the chance to play all queued audio.
Also it will make sure that the audio has finished playing so we can
reinitialize the AO if format changes are necessary.
Fixes #10018
Fixes #9835
Fixes #8904
@Hello71 @gbpi @kookiesgh Can you validate that this fixes your issues?
=> audio: drain ao on EOF

video/out/opengl/context_drm_egl.c
Any error in page flipping caused mpv to wait indefinitely for a page
flip callback.
=> context_drm_egl: skip page flip wait on error

meson.build, video/out/drm_common.c, wscript
#10477 forgot to bump the required
libdrm version however Debian 11 just barely misses the requirement,
which is a good reason not to require it unconditionally anyway.
=> drm_common: remove hard dependency on drmIsKMS()

player/lua/ytdl_hook.lua
Only matters when configuring ytdl_hook with all_formats=yes.
Tracks are marked as default tracks based on what yt-dlp/youtube-dl returns in the field `requested_formats`.
The problem is that this field only exists when there is more then one requested format.
So `ytdl-format=bestvideo+bestaudio` would have that field, but `ytdl-format=bestaudio` would not, leading to no tracks being marked as default tracks.
The requested formats can also be found under `requested_downloads`, which exists regardless of the number of requested formats. However when there is more then one requested format, `requested_downloads` doesn't contain those formats directly and instead has a field `requested_formats` that is identical to the other `requested_formats`.
Therefore use `requested_downloads` as a …
=> ytdl_hook: fix default track for single format

video/out/x11_common.c
Unexpectedly, x11->screenrc actually doesn't update with randr events.
In a multimonitor configuration it could easily be wrong depending on
the user's layout. While it's tempting to modify the logic so screenrc
changes with randr events, this rectangle is currently used everywhere
and as far as we know, this pretty much works fine. Instead, just loop
over the randr displays that we have and select it if it overlaps with
the winrc. This follows the same logic as the fps selection in the case
of the mpv window overlapping multiple monitors (the last one is
selected).
=> x11: fix display-{width,height} calculation

generated/meson.build, meson.build, meson_options.txt
So the meson build is a complex beast out of necessity, but we can make it a bit nicer. The first two commits are pretty straightforward. The third one rewrites how setting `config.h` is handled so it's more automatic. Basically all you have to do now is append a new entry to the `features` dictionary containing the name of the feature in question and its true/false value and the loop at the end will automatically create the define for you.
=> Meson refactor/simplification

common/playlist.c, libmpv/client.h, meson.build, misc/random.c, misc/random.h, osdep/io.c, osdep/timer.c, wscript_build.py
Add xoshiro as a PRNG implementation instead of relying
on srand() and rand() from the C standard library. This,
in particular, lets us avoid platform-defined behavior with
respect to threading.
=> misc/random: add xoshiro random number implementation

player/lua/ytdl_hook.lua
Every format that was not detected as a video format was added to the
audio tracks. This resulted in e.g. YouTube storyboards from ending up
in the list of audio tracks.
Now formats that are already known to be neither video formats nor audio
formats, will also not end up in any track list.
Formats where it is unknown if they are video or audio formats get
added to tracks if `force_all_formats` is used, otherwise only
formats that are known to contain video or audio become video or audio
tracks respectively.
https://github.com/yt-dlp/yt-dlp/issues/4373#issuecomment-1186637357
Currently it uses `force_all_formats` to decide if questionable formats get added or not. Should we introduce  a new option for that or is this fine?
=> ytdl_hook: improve track detection

audio/out/ao_pipewire.c
Newer versions of Pipewire request a specific amount of data, try to honor it.
Also add some more information about the buffers sent to Pipewire.
=> ao_pipewire: only try to read requested data

.github/workflows/build.yml, ci/build-freebsd.sh
For Linux it would be needed to install pipewire as part of the build image `registry.opensuse.org/home/mia/images/images/mpv-ci:stable-deps` but I don't know where that comes from.
=> ao_pipewire: test on FreeBSD

player/audio.c
52aed495cb ("audio: drain ao on EOF") introduced logic to drain an AO
when EOF of the input has been reached.
When no AO however is present this leads to a NULL-dereference.
Fixes #10556
=> audio: don't try to drain non-existent AO

audio/out/ao_pipewire.c
The error description in #10545 could indicate that we are overflowing
we are corrupting the buffer metadata ourselves through out-of-bound
writes.
This check is also present in pw-cat so it seems to be expected for
b->requested to exceed the actual available buffer space.
Potential fix for #10545
Cc @sfan5 @philipl @thebombzen
=> ao_pipewire: make sure not to exceed the available buffer

meson.build
Missing waf quivalent, and doesn't necessarily output a good error
message. But I might as well set this rather than sitting on it
unnecessarily.
=> meson: fix libplacebo check

DOCS/man/mpv.rst
Additional guidance added to the main INTERACTIVE CONTROLS section to
point the user at the COMMAND INTERFACE section and clarify the location
of default key bindings referenced in the existing wording.
=> DOCS/mpv: added COMMAND INTERFACE refs to INTERACTIVE CONTROL

audio/aframe.c, audio/aframe.h, audio/decode/ad_lavc.c
`opus` codec likes returning denormalized floats in some cases, causing
wacky issues.
Fixes #10290
Open questions:
=> ad_lavc: strip non-normalized floats

video/out/vo_gpu_next.c
Only relevant when `--target-colorspace-hint` is used.
=> vo_gpu_next: fix typo affecting --target-trc option

DOCS/man/options.rst
Several times in the past, I've searched the man page for the word "mono" to remind myself how to do this. This is an incredibly minor change, but I think it's worth explicitly mentioning this special case of `--audio-channels`. Hope it helps at least one other person like me.
=> DOCS: Mention "mono" audio channels option

video/repack.c
I'm adding support in ffmpeg for the XV36 format which will be used
by VAAPI for 12bit 4:4:4 content. It's an undefined-alpha channel
variant of Y412 which is itself a 12bit+4bits padding variant of Y416.
We currently have a repacker for full four channel cccc16, and for
three channel ccc16, but nothing for ccc16x16 with the undefined alpha
channel.
It's simple enough to add one using the existing macros.
=> repack: add repacker for ccc16x16 formats

audio/out/ao.h, audio/out/ao_pipewire.c, player/audio.c, player/command.c, player/core.h
This adds a new aocontrol `AOCONTROL_UPDATE_MEDIA_ROLE` that is used by the core to notify the AOs about the kind of media that is being played. Either a movie or music.
ao_pipewire can forward this to the PipeWire audio server.
=> audio: add AOCONTROL_UPDATE_MEDIA_ROLE

audio/out/ao.c, audio/out/ao.h, audio/out/ao_pipewire.c, player/command.c, player/main.c, ta/ta.c
This adds full hotplug support to the Pipewire AO.
Effectively this means proper use of the initialization APIs `hotplug_init()` and `hotplug_uninit()` and sending of hotplug events.
Unfortunately same changes to core code are necessary. This is because currently mpv expects each system/platform to have only a single AO driver that implements hotplug events and all others only implement device listing.
For pulse and pipewire this is not really applicable. It is possible to have systems where mpv is built with only one of ao_pulse or ao_pipewire, or where ao_pulse and ao_pipewire disagree on the audio devices they see (the audio servers may be running on different machines).
For this to work properly the following changes to the audio core are made:
* Try to use the same AO driver for …
=> pipewire: add full hotplug support

player/lua/ytdl_hook.lua
The parsing used to be unnecessarily complicated,
now it's easier to read and understand.
=> ytdl_hook: simplify exclude option parsing

TOOLS/lua/autoload.lua
- [.m2ts](https://en.wikipedia.org/wiki/.m2ts) used for the Blu-ray disc container file format.
ref: https://github.com/mpv-player/mpv/pull/9772, https://github.com/mpv-player/mpv/pull/9404
=> TOOLS/lua/autoload: add `m2ts` extension

video/out/cocoa_cb_common.swift, video/out/mac/common.swift
Newer swift runtimes assert on `unsafelyUnwrapped` of a null pointer, so this crashes in debug builds. We instead pass down an optional, which works fine.
=> Swift: avoid unnecessary unsafe conversions; fixes crash in debug builds

demux/demux_lavf.c
Unfortunately ffmpeg doesn't differentiate between AV1 and AVIF, so
detect AV1 files with 1 frame as images, as AV1 videos have nb_frames 0
or > 1.
=> demux_lavf: detect avif images

audio/filter/af_scaletempo2_internals.c
When `af_scaletempo2.c:process()` detects a format change, it goes back through `mp_scaletempo2_init()` to reinitialize everything.  However, `mp_scaletempo2.input_buffer` is not necessarily reallocated due to a
check in `af_scaletempo2_internals.c:resize_input_buffer()`.  This is a problem if the number of audio channels increases, since without reallocating, the buffer for the new channel(s) will at best point to NULL, and at worst uninitialized memory.
Since `resize_input_buffer()` is only called from two places, pull size check out into `mp_scaletempo2_fill_input_buffer()`.  This allows each caller to decide whether they want to resize or not.  We could be smarter about when to reallocate, but that would add a lot of machinery for a case I don't expect to be hit often in practice.
=> af_scaletempo2: fix crash when the number of channels increases

player/lua/ytdl_hook.lua
So far the `ext` was always used as the title,
but `name` is more appropriate when it's available.
=> ytdl_hook: use subtitle `name` as title if available

DOCS/interface-changes.rst, DOCS/man/options.rst
Removed the outdated information about environmental brightness with respect to --gamma-factor, and mention that the option is deprecated and subject to future removal.
=> DOCS: deprecate --gamma-factor and --gamma-auto

DOCS/man/options.rst, DOCS/man/vo.rst, meson.build, meson_options.txt, video/out/gpu/hwdec.c, video/out/hwdec/hwdec_aimagereader.c, wscript, wscript_build.py
approach based on https://github.com/mpv-player/mpv/pull/5602#issuecomment-796826604
In short you can tell MediaCodec to render into an [AImageReader](https://developer.android.com/ndk/reference/group/media#aimagereader) and then retrieve the frames from it, no JNI required.
unsolved:
what I'm wondering:
* the texture is always RGB0.
~~why? can we influence this?~~ can't fix
* AImageReader has an internal queue but only one frame is ever in-flight.
Wouldn't it be more efficient to queue several frames? Does this even matter?
cc @jeeb @tmm1 @wang-bin @wnoun
=> Android hwdec utilizing AImageReader

video/out/opengl/context_wayland.c, video/out/vo_vaapi_wayland.c, video/out/vo_wlshm.c, video/out/vulkan/context_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h
The wayland presentation time code currently always assumes that only CLOCK_MONOTONIC can be used. There is a naive attempt to ignore clocks other than CLOCK_MONOTONIC, but the logic is actually totally wrong and the timestamps would be used anyway. Fix this by checking a use_present bool (similar to use_present in xorg) which is set to true if we receive a valid clock in the clockid event. Additionally, allow CLOCK_MONOTONIC_RAW as a valid clockid. In practice, it should be the same as CLOCK_MONOTONIC for us (ntp/adjustime difference wouldn't matter). Since this is a linux-specific clock, add a define for it if it is not found.
=> wayland: correctly handle non-CLOCK_MONOTONIC clocks

player/lua/osc.lua
Should behave pretty much the same as it used to, but the logo stays centered better and it doesn't distort anymore, which was caused by a recent change in libass https://github.com/libass/libass/pull/645.
Has been tested with the latest libass release 0.16.0 and with their latest master commit https://github.com/libass/libass/commit/44f6532daf5eb13cb1aa95f5449a77b5df1dd85b
Closes #10710
=> osc: scale rendered aspect ratio with window aspect ratio

DOCS/man/ao.rst, audio/out/ao_pipewire.c
This PR introduce a new option `--pipewire-remote` to specify the PipeWire remote to connect to.
It also removes some unneeded braces and structures the AO-private data a bit.
Cc @philipl
=> ao_pipewire: option "remote" and small cleanups

.github/workflows/build.yml
Apparently an implicit dependency on it through one of the otherwise installed packages is no longer there.
=> github/workflows: explicitly install Xinerama on FreeBSD

video/out/gpu_next/context.c, video/out/placebo/utils.c, video/out/placebo/utils.h, video/out/vulkan/common.h, video/out/vulkan/utils.c
The new status quo is simple: all messages coming from libplacebo are marked "vo/gpu{-next}/libplacebo", regardless of the backend API (vulkan vs opengl/d3d11).
Messages coming from mpv's internal vulkan code will continue to come from "vo/gpu{-next}/vulkan", and messages coming from the vo module itself will be marked "vo/gpu{-next}".
This is significantly better than the old status quo of vulkan messages coming from "vo/gpu{-next}/vulkan/libplacebo" whereas opengl/d3d11 messages simply came from "vo/gpu{-next}", even when those messages originated from libplacebo.
(It's worth noting that the the destructor for the log is redundant because it's attached to the ctx which is freed on uninit anyway)
=> vo_gpu_next: vulkan: libplacebo: unify log prefix

sub/draw_bmp.c
Fix for the below encountered ASAN error:
```
==374192==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6280005e3992 at pc 0x555556335685 bp 0x7fff5e423890 sp 0x7fff5e423888
READ of size 2 at 0x6280005e3992 thread T25 (mpv/vo)
#0 0x555556335684 in mark_rect ../sub/draw_bmp.c:273
#1 0x555556338d28 in render_ass ../sub/draw_bmp.c:331
#2 0x555556338d28 in render_sb ../sub/draw_bmp.c:463
#3 0x555556344408 in mp_draw_sub_bitmaps ../sub/draw_bmp.c:857
#4 0x555556358bb9 in osd_draw_on_image_p ../sub/osd.c:444
#5 0x55555657ac45 in draw_image ../video/out/vo_x11.c:338
#6 0x555556513a04 in render_frame ../video/out/vo.c:959
#7 0x555556513a04 in vo_thread ../video/out/vo.c:1095
#8 0x7ffff3ef5ea6 in start_thread nptl/pthread_create.c:477
#9 0x7ffff34bbdee in __clone …
```
=> Fix heap-buffer-overflow in mark_rect

sub/sd_ass.c
Existing unknown duration handling can be problematic when a chain of track events (ASS dialogues) shares the same start time.
For reference,
| track->events[n] | Start | Duration |
| :--------------: | :---: | :------: |
| 0 | 5400 | 2147483000 |
| 1 | 5400 | 2147483000 |
| 2 | 7869 | 2147483000 |
| 3 | 7869 | 2147483000 |
| 4 | 7869 | 2147483000 |
| 5 | 11707 | 2147483000 |
Becomes,
| track->events[n] | Start | Duration |
| :--------------: | :---: | :------: |
| 0 | 5400 | 0 |
| 1 | 5400 | 2469 |
| 2 | 7869 | 0 |
| 3 | 7869 | 0 |
| 4 | 7869 | 3838 |
| 5 | 11707 | 2147483000 |
Instead of,
| track->events[n] | Start | Duration |
| :--------------: | :---: | :------: |
| 0 | 5400 | 2469 |
| 1 | 5400 | 2469 |
| 2 | 7869 | 3838 |
| 3 | 7869 | 3838 |
| 4 | 7869 | 3838 |
| 5 | 11707 | …
=> sd_ass: improve handling of subtitles with unknown duration

filters/f_hwtransfer.c, video/out/hwdec/dmabuf_interop_gl.c, video/out/hwdec/hwdec_vaapi.c
The logic around trying to establish what formats are supported by vaapi is confusing, and it turns out that we've been doing it wrong.
Up until now, we've been going through the list of decoding profile endpoints and checking the formats declared in those profiles to build our list.
However, the set of formats that the vaapi driver can actually support is potentially a superset of those supported by any given profile endpoint. This master list is exposed by libavutil via the av_hwframe_transfer_get_formats() function, and so we should use that list as our starting point.
Perhaps surprisingly, this change actually removes no code, because we still want the logic that enumerates endpoints and finds supported formats for endpoints. We need this because we must have at least one known sw …
=> hwdec/vaapi: improve probing of supported sw formats

filters/f_hwtransfer.c
vaapi allows for implicit conversion on upload, which has some
relevance as the set of supported source formats is larger than the
set of displayable formats. In theory, this allows for offloading the
conversion to the GPU - if you have any confidence in the hardware
and/or driver's ability to do the conversion.
Today, we actually track the 'input' and 'output' upload formats
separately all the way up until the point we do a check as to whether
the original source format is an accepted 'output' format and then
reject it if it is not.
This means that we're essentially ignoring all the work we did to track
those 'input' formats in the first place. But it also means that it's a
simple change to compare against the 'input' format instead. The logic
is already in place to do best format …
=> f_hwtransfer: allow hw uploads to implicitly convert formats

demux/demux_mf.c
Adds support for some float formats: PHM and HDR and new very simple image codec QOI.
=> demux_mf: add support for QOI, PHM and HDR images

demux/demux_mkv.c
Add support for playing back AVS2 and AVS3 video streams inside mkv containers if ffmpeg was compiled with avs2/avs3 support.
Fixes: #10695
=> demux_mkv: add AVS2 and AVS3 to tag list

audio/format.c
When using Xcode, `struct entry` already exists (from <search.h>), so the one we declare in audio/format.c needs to be named differently.
=> audio/format: fix Type 'struct entry' has incompatible definitions in different translation units

audio/out/ao.c, audio/out/ao_pipewire.c
The AO is feature-complete now.
As PipeWire also provides compatibility with PulseAudio, ALSA and Jack we should put it before those for the autodetection to work.
It may make sense to delay merging this after 0.35 is release to get some more opt-in testing.
=> ao: promote ao_pipewire

DOCS/man/mpv.rst
Pushing E (aka Shift+e) cycles through Editions for containers that support editions, such as Matroska, although this feature was not documented before this commit.
=> DOCS: document E to cycle through Editions

audio/out/ao_pipewire.c, ci/build-tumbleweed.sh, meson.build, wscript
This patch provides compatibility with the version of libpipewire as shipped in Debian stable.
Supersedes #10787 
Fixes #10786
Cc @philipl @jeeb
=> ao_pipewire: compatibility for libpipewire 0.3.19

video/out/wayland_common.c, video/out/wayland_common.h
Otherwise mpv and the compositor can end up in an eternal loop where
mpv requests one mode, and compositor tells that the mode is not
that (and will most likely not change).
Additionally, log these mismatches - first time as a warning, and
later as debug logging.
=> video/out/wayland_common: clear decoration request even if compositor disagrees

video/out/vo_dmabuf_wayland.c
Building on DRM platform without VAAPI broke because of misuse of HAVE_VAAPI with #ifdef in place of #if. Also, the hwcontext_drm.h header is not required for VAAPI builds, only DRM builds.
=> Fix vo_dmabuf_wayland DRM builds with no VAAPI

.github/workflows/build.yml, ci/build-freebsd.sh
It turns out that the build files are copied back to the host so for the freebsd vm, we can explicitly try to print out any build logs on failure. This should make it a little clearer when the freebsd build actually fails vs just a random ssh failure.
=> ci: freebsd improvements

DOCS/man/options.rst, video/out/gpu/context.c, video/out/gpu/context.h, video/out/vo_dmabuf_wayland.c, video/out/wayland_common.c, video/out/wldmabuf/context_wldmabuf.c
The first two commits fix the potential crash. Should be pretty straight forward. 
The last commit introduces a new `ra_ctx_create_hidden` function that is used specifically for `vo_dmabuf_wayland`. It internally uses `hidden_type` and `hidden_name` so these options are not exposed to users. Overall, it is much more simple than the other counterpart since we don't care about probing, opts, etc. We just want the ra_ctx for hwdec.
=> dmabuf-wayland fixes

options/m_config_frontend.c
Add the profile name to the warning message to clarify the target. Helpful when there are many unhit restores.
close https://github.com/mpv-player/mpv/issues/10785https://github.com/mpv-player/mpv/issues/10785
=> options: show profile name when no restore data

audio/out/ao_coreaudio_utils.h
This matches our internal expectations, as well as fixes handling of non-ASCII device descriptions.
=> ao_coreaudio: specify UTF-8 as text encoding for CFString conversions

demux/codec_tags.c
This patch adds support for two extra WAVEFORMATEXTENSIBLE GUID tags that can appear inside RIFF headers. It also adds support for extra codec IDs that may appear as their own unique wSubFormats inside RIFF headers, such as ATRAC9 inside matroska, as one example.
Fixes #10757.
=> demux/codec_tags: support more WAVEFORMATEXTENSIBLE tags

player/lua/ytdl_hook.lua
Only matters when configuring ytdl_hook with `all_formats=yes`.
So far the tracks were ordered from worst to best quality.
Web players with quality selection always show the highest quality option at the top.
Since tracks are usually listed with the first track at the top, that should also be the highest quality one.
yt-dlp/youtube-dl sorts it's formats from worst to best.
Iterate in reverse to get best track first.
Conflicts with #10399
=> ytdl_hook: reverse order of tracks

.github/workflows/build.yml
This was only needed because the mingw CI used to run on Ubuntu 20.04 which had a version of meson too old for mpv. This hasn't been the case since we switched to 22.04 in f7164fcfaca1b1d8f0ceb9cb58e532c172cf83fa and can now just use the package manager version.
=> github/workflows: remove pip usage in mingw CI

DOCS/man/console.rst, player/lua/console.lua
Deduplicate history like the fish shell. So for example
entering "cmd 1" then "cmd 2" then "cmd 3" then "cmd 1"
would result in a history of
[cmd 2][cmd 3][cmd 1]
instead of
[cmd 1][cmd 2][cmd 3][cmd 1]
Adds a function `history_append` to replace directly appending to
history.
Adds an option `history_dedup` to deactivate the deduplication.
(I already opened a [PR](https://github.com/mpv-player/mpv/pull/10300) for this, but when I moved the commit to a separate branch the PR got automatically closed.)
=> console: add history deduplication

sub/sd_ass.c
It turns out, even xy-VSFilter and XySubFilter do not mangle colours if the video is native RGB regardless of the sub's YCbCr header. libass' docs were also [updated](https://github.com/libass/libass/commit/52783a46c0f56ccfb66795667f069a1d2993cfcf) to reflect this.
To see the difference use `mpv --no-config --sub-ass-vsfilter-color-compat=full -sub-file vid_gbr.ass vid_gbr.mkv` with the provided sample files: [mpv-10826_colourmangling-rgbvid.tar.gz](https://github.com/mpv-player/mpv/files/9922816/mpv-10826_colourmangling-rgbvid.tar.gz).
The values used in the ASS sub are `&HFFFFFF` for text colour and `&HHA184F4` for the rectangle.
On current master (6acb7db9facd41f67aebb54a0daeddaaa30d54b3) there's obviously some severe colour mangling occuring *(which would be good if xy\* did the same, …
=> sd_ass: never mangle colours on RGB video

video/out/hwdec/hwdec_vaapi.c, video/out/vo_dmabuf_wayland.c
This PR improves two aspects of `vaapi` support in the new `dmabuf-wayland` vo:
0. Improve error handling when exporting VA surface
1. Only set VADisplay resource if init process has succeeded
=> vo_dmabuf_wayland: improve vaapi surface export error handling and va display handling

audio/out/ao_audiounit.m
This reverts commit 8b114e574abd08892612e21e784ea1872e1adf8c from https://github.com/mpv-player/mpv/pull/6485
My understanding of IOBufferDuration is still unclear, because the docs don't really say much: https://developer.apple.com/documentation/avfaudio/avaudiosession/1616498-iobufferduration
But since AVAudioSession explicitly exposes `outputLatency`, it should be safe to assume it has already included its own I/O buffers in that latency calculation.
=> Revert "ao/audiounit: include AVAudioSession buffer in latency calc"

DOCS/interface-changes.rst, DOCS/man/options.rst, video/out/gpu/video.c, video/out/gpu/video.h, video/out/vo_gpu_next.c
This is a very simple but easy way of doing it. Ideally, it would be nice if we could also add some sort of introspection about shader parameters at runtime, ideally exposing the entire list of parameters as a custom property dict. But that is a lot of effort for dubious gain.
It's worth noting that, as currently implemented, re-setting `glsl-shader-opts` to a new value doesn't reset back previously mutated values to their defaults.
TODO:
=> vo_gpu_next: add tunable shader parameters

meson.build
Apparently, it is possible for touchbar.m to compile on non-macos machines. Also, the disable switch didn't actually work either. Fix this by using the require() function and making sure that Cocoa (should be apple-only) is found in addition to the compile check passing which is what waf does. Fixes #10847.
=> meson: fix macos-touchbar check

video/out/gpu/hwdec.c, video/out/gpu/hwdec.h, video/out/hwdec/hwdec_cuda.c, video/out/hwdec/hwdec_drmprime_overlay.c, video/out/hwdec/hwdec_vaapi.c
These were introduced for configuration compatibility in 0.35 but we don't want to retain them past that point.
=> vo: hwdec: remove legacy_names

common/av_log.c, player/main.c
1. Adjust the location of the overall FFmpeg version logging.
2. Add libplacebo version as part of `--version`.
=> {common,player}: version logging changes

DOCS/interface-changes.rst, DOCS/man/options.rst, generated/wayland/meson.build, options/options.c, options/options.h, player/core.h, player/misc.c, player/playloop.c, player/video.c, video/out/vo.h, video/out/wayland_common.c, video/out/wayland_common.h, wscript, wscript_build.py
The content-type protocol allows mpv to send compositor a hint about the type of content being displayed on its surface so it could potentially make some sort of optimization. Fundamentally, this is pretty simple but since this requires a very new wayland-protocols version (1.27), we have to mess with the build to add a new define and add a bunch of if's in here. The protocol itself exposes 4 different types of content: none, photo, video, and game. For mpv, we of course send video by default but it is certainly common to view images/photos as well. Additionally, maybe the compositor is bugged in some way and one would like to turn this off. In light of that, a new option has also been added (wayland-content-type) that lets users control what content hint to send to the compositor. For …
=> wayland: add support for content-type protocol

DOCS/interface-changes.rst, DOCS/man/vo.rst, video/out/drm_common.c, video/out/drm_common.h, video/out/opengl/context_drm_egl.c, video/out/vo_drm.c
The legacy DRM API adds some complexity to the DRM code. There are only 4 drivers that do not support the DRM API:
1. radeon (early GCN amd cards)
2. gma500 (ancient intel GPUs)
3. ast (ASPEED SoCs)
4. nouveau
Going forward, new DRM drivers will be guaranteed to support the atomic API so this is a safe removal.
tested on `--vo=drm` and `--vo=gpu{,-next} --gpu-context=drm`
=> drm: remove legacy API

video/out/gpu/lcms.c
Currently, the lcms-related options are only defined when lcms2 is enabled at build time. However, this causes issues (e.g. segfault) for vo_gpu_next, which relies on the presence of these options (to forward them to libplacebo).
(That libplacebo internally depends on lcms2 as well is an implementation detail - compiling mpv *without* lcms against libplacebo *with* lcms should be possible in principle)
Fixes: #10891
Closes: #10856
=> lcms: always parse lcms2-related options

meson.build
BSDs use compiler-rt instead of libatomic for atomic types. In this case, we can handle it similar to how dl is detected. Check for the library (allowing for it to fail), and then check for a header symbol while linking latomic. Fixes #10906.
=> meson: fix stdatomic detection on bsd

video/out/vo_gpu_next.c
Flushing the cache is a hammer-for-a-screw operation, because it nukes *all* renderer state, including the HDR peak detection state. When enabling e.g. --hdr-compute-peak, or any other future methods of dynamic tone mapping, this would lead to bad results (e.g. brightness fluctuations) whenever the OSD state is updated.
Instead of flushing the cache to force an OSD re-render, instead just update the frame signature directly whenever its osd_sync value changes. This accomplishes effectively the same thing but without touching the HDR state.
This is slightly violating the libplacebo abstraction in a way that isn't publicly documented. To be on the safe side we could make a carbon copy of the array before modifying it, but given that this is unlikely to change upstream I'll probably just end …
=> vo_gpu_next: don't flush cache on OSD update

TOOLS/umpv
Conform more to the [XDG standards](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
> There is a single base directory relative to which user-specific runtime files and other file objects should be placed. This directory is defined by the environment variable $XDG_RUNTIME_DIR. 
Didn't test.
=> TOOLS/umpv: prefer $XDG_RUNTIME_DIR

demux/demux_lavf.c, meson.build, video/decode/vd_lavc.c, video/mp_image.c, video/sws_utils.c, wscript
Now that 0.35 has been released, we can consider increasing our minimum
required ffmpeg version. Currently, we think 4.4 is the most recent
version we can move to (from the current requirement of 4.0).
This allows us to remove a few conditionals and I also took the
opportunity to add proper handling for a couple of new deprecations.
I have not handled av_init_packet in this change as it's more
involved and I want us to decide we want to do the version bump before
putting in that work.
=> ffmpeg: increase minimum required version to 4.4

audio/decode/ad_lavc.c, audio/decode/ad_spdif.c, common/av_common.c, common/av_common.h, common/recorder.c, sub/lavc_conv.c, sub/sd_lavc.c, video/decode/vd_lavc.c
This has been a long standing annoyance - ffmpeg is removing sizeof(AVPacket) from the API which means you cannot stack-allocate AVPacket anymore. However, that is something we take advantage of because we use short-lived AVPackets to bridge from native mpv packets in our main decoding paths.
We don't think that switching these to `av_packet_alloc` is desirable, given the cost of heap allocation, so this change takes a different approach - allocating a single packet in the relevant context and reusing it over and over.
That's fairly straight-forward, with the main caveat being that re-initialising the packet is unintuitive. There is no function that does exactly what we need (what `av_init_packet` did). The closest is `av_packet_unref`, which additionally frees buffers and side-data. …
=> ffmpeg: update to handle deprecation of `av_init_packet`

video/out/hwdec/dmabuf_interop_gl.c, video/out/hwdec/hwdec_drmprime.c
H264 hardware decode with v4l2m2m wasn't working on the RPi 4. Mpv would report the image format (yuv420p) wasn't supported. The change to hwdec_drmprime.c is to explicitly say that the format now is supported. The change to dmabuf_interop_gl.c is to specify the colour format of the planes before generating egl images. These changes were tested on a Pi 4 with this fork of ffmpeg: https://github.com/jc-kynesim/rpi-ffmpeg.
Should fix #10956
=> hwdec_drmprime: support yuv420p format

audio/out/ao_pipewire.c
By explictly shutting down the stream pipewire can deactivate the used hardware, saving CPU and power.
Fixes #9835
Cc @philipl 
This is an ao_pipewire-specific alternative to #10931 which seems a bit nicer to me.
I want to test it some more, but putting it out there for opinions and testing.
=> ao_pipewire: deactivate stream at end of playback

video/out/filter_kernels.c
Seems to me that `params[1]` is set to `NAN` and here should be the same value as in `params[0]`. Also small suggestion, I think that an entire function could be simplified to `return bessel_i0(p->params[0] * sqrt(1.0 - x * x)) / bessel_i0(p->params[0]);` or ` return bessel_i0(p->params[0] * sqrt(1.0 - x * x));`. Because `if (x > 1)` seems to be unnecessary here since we do similar thing elsewhere for all windows and normalization here is also probably unnecessary because we normalize kernel with weight sum.
=> filter_kernels: fix kaiser

player/external_files.c
We ask users to freely share log files with us, which is usually okay, unless a user has some unrelated and potentially embarrassing files in their working directory. These would show up in the debug level message output that `--log-file` enables.
Change the listing of potential external files to trace log level, to save the users and the developers the embarrassment.
=> external_files: set log level for potential files to trace

audio/out/buffer.c
When a pull AO reaches reaches EOF then ao_read_data() will set p->playing = false.
Because the ao is marked as not playing ao_set_pause(true) will not reset the AO.
This keeps the output stream unintentionally open.
Another conditional is added that makes sure the necessary reset is performed.
Fixes #9835 
This is a revised version of the change presented in #9835 before.
I am not entirely sure this is the correct place to fix this.
Test protocol:
* `pw-top`
* `mpv --no-config --ao=pipewire --keep-open $FILE`
* Validate that the `S`(tate) column in `pw-top` for the mpv node shows `I`
Cc @philipl @sfan5 , if maybe uau could take a look that would be great, too.
=> audio: reset pull AO at end of file

demux/demux_lavf.c, demux/packet.c
In the previous change, I replaced the callsites that used `av_init_packet`, but there are a handful of places that use stack allocated packets with no initialisation.
In one case, I just switched to heap allocation as it's only done once per stream at most.
In the other case, I removed our usage of the AVPackets as a convenience mechanism to transfer data into a heap allocated packet. Instead, I inlined the data copying.
=> demux: replace deprecated usage of stack allocated AVPackets

video/out/x11_common.c
Since the modesetting driver now has TearFree support with integration into xpresent, it's important that xpresent is used with the modesetting driver to get the correct vsync timing when a frame is delayed by one vblank interval due to a pending page-flip enqueued by a different entity. The modesetting driver ensures that the xpresent extension reports the correct presentation timing when TearFree is used; mpv just needs to listen to it.
Add the modesetting driver to the xpresent whitelist so mpv can get the correct presentation completion timing when modesetting TearFree is used.
This is also helpful for when xpresent performs page flips directly in the modesetting driver and a natural delay in the display pipeline causes a page flip to be delayed by one vblank interval or more.
=> x11: add modesetting to the xpresent whitelist

DOCS/interface-changes.rst, DOCS/man/options.rst, demux/demux.c
Buffering ahead nonstop into the cache results in nonstop disk or network activity to read stream data from wherever it may originate. Currently, there's no way to configure the demuxer to back off once it's buffered ahead enough data, since the cache limit will be perpetually not-reached as a stream continues to play, until the entire stream is eventually buffered.
On a laptop with an i9-12900H with decoding performed by the iGPU, watching a locally-saved 1080p video which hasn't been buffered into the page cache consumes approximately 15 W even with caching enabled. When configuring a hysteresis to make the demuxer back off, power consumption drops to 9 W when watching the same video, resulting in a whopping 6 W of power savings.
To make it possible to attain significant power savings …
=> demux: add --demuxer-hysteresis-secs option to save power with caching

video/out/opengl/common.c
This change enables mpv to work in the WSL2 (WSLg) environment where OpenGL is implemented on top of D3D12.
This reverts commit 149d98d244.
Mentioned OpenGL implementation (GDI Generic) in the original change will be rejected by version check, so there is no need to handle it manually.
Signed-off-by: Kacper Michajłow <kasper93@gmail.com>
=> vo_opengl: do not blindly reject all Microsoft's OpenGL implementations

audio/out/ao_coreaudio.c
[motivation]
Seeking on MacOS appears to be lagged when users connect to wireless audio output (airpods for example).
This commit attempts to fix mpv-player/mpv#10270
[observation]
1. When using other media player (VLC to be exact) simultaneously, the lagging on seek disappear. We could guess that the AudioDevice is on some sort of "warm-up" state.
See mpv-player/mpv#9243 for detailed description.
2. `AudioOutputUnitStart` takes significant longer time after each seek or pause/play when using wireless output devices compares to wired devices.
[rationale]
After investigate codes in ao_coreaudio.c, it appears that the the `stop` function was used as `ao_driver.reset` function. Therefore every seek and pause would call `AudioOutputUnitStop`.
It turns out that `ao_driver.reset` function is …
=> ao_coreaudio: use AudioUnitReset as ao_driver.reset to prevent long restart

video/out/hwdec/hwdec_drmprime.c
This commit fixes an issue happening in "hwdec_drmprime.c". This issue generates a cascade of small memory leaks. The logs were reported by the gcc sanitizer (-fsanitize=leak).
```
==4914==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 24 byte(s) in 1 object(s) allocated from:
#0 0x7f974f4c80 in __interceptor_posix_memalign (/usr/lib64/libasan.so.6+0xa4c80)
#1 0x7f95aa1638 in av_malloc (/usr/local/lib64/libavutil.so.56+0x31638)
#2 0x7f95aa185c in av_mallocz (/usr/local/lib64/libavutil.so.56+0x3185c)
#3 0x7f95a8bc30 in av_buffer_create (/usr/local/lib64/libavutil.so.56+0x1bc30)
#4 0x7f95a975e4 in av_hwdevice_ctx_alloc (/usr/local/lib64/libavutil.so.56+0x275e4)
#5 0x7f95a97b74 in av_hwdevice_ctx_create (/usr/local/lib64/libavutil.so.56+0x27b74)
#6 0x969e5c in init …
```
=> hwdec_drmprime: fix memory leak

video/out/hwdec/hwdec_drmprime_overlay.c
This commit fixes a minor memory leak related to drmGetDeviceNameFromFd2(). This function returns a string allocated with strdup().
```
Direct leak of 15 byte(s) in 1 object(s) allocated from:
#0 0x7f95cd9050 in __interceptor_strdup (/usr/lib64/libasan.so.6+0x59050)
#1 0x7f93dd2520 in drmGetDeviceNameFromFd2 ../xf86drm.c:4787
#2 0x971494 in init ../video/out/hwdec/hwdec_drmprime_overlay.c:303
#3 0x842548 in ra_hwdec_load_driver ../video/out/gpu/hwdec.c:103
#4 0x842a2c in load_add_hwdec ../video/out/gpu/hwdec.c:235
#5 0x845684 in ra_hwdec_ctx_load_fmt ../video/out/gpu/hwdec.c:331
#6 0x8e0dec in request_hwdec_api ../video/out/vo_gpu.c:131
#7 0x8e0dec in control ../video/out/vo_gpu.c:202
#8 0x8ccc9c in run_control ../video/out/vo.c:661
#9 0x62c7ac in mp_dispatch_queue_process …
```
=> vo: hwdec: fix drmGetDeviceNameFromFd2() related memory leak

sub/draw_bmp.c
e97819f88e451623a397b79d101497205fe849f9 corrected a special case condition that lead to an out of bounds access if the total width happened to be an integer multiple of SLICE_W (256) which could cause a crash in software VOs. However, it turns out that the functions in this file evaluate quite differently when using encoding mode (and presumably libmpv as well according to reports although I could not independently verify it).
The logic here gets complicated but what ends up happening is that, in blend_overlay_with_video, the value of x + w can be greater than p->w in certain cases in encoding mode. The x is the positional value of the slice which remained unchanged from before, but w can take the full value of SLICE_W (256) which is not necessarily correct. The width of the final slice …
=> draw_bmp: ensure last slice width is less than total width

video/out/wayland_common.c, video/out/wayland_common.h
Fixes #11022 but it's better this time.
First commit is just extra. The actual fix is the second one which basically just dispatches wayland events and then does another roundtrip before doing uninit. A `wl->feedback == fback` check is added now since these two are not necessarily the same pointer.
=> wayland presentation fixes (again)

TOOLS/docutils-wrapper.py, meson.build
This allows us to rebuild the manpages and html documentation only when necessary. It is not necessary to manually keep the list of dependencies up to date.
Unfortunately rst2pdf does not yet support this feature, see https://github.com/rst2pdf/rst2pdf/issues/1108
=> meson: dynamically compute dependencies for manpage and html build

video/out/vulkan/utils.c
vk->surface is a handle and not a pointer, so assign VK_NULL_HANDLE. This fixes the following build error on 32bit Windows when using clang for example, which errors out when assigning a 32bit pointer to a 64bit integer:
```
../mpv-0.35.0/video/out/vulkan/utils.c:37:21:
error: incompatible pointer to integer conversion assigning to 'VkSurfaceKHR' (aka 'unsigned long long') from 'void *' [-Wint-conversion]
vk->surface = NULL;
^ ~~~~
```
=> vulkan: fix build error for 32bit builds with clang

video/out/android_common.c, video/out/android_common.h, video/out/opengl/context_wayland.c, video/out/vulkan/context_wayland.c, video/out/w32_common.c, video/out/w32_common.h, video/out/wayland_common.c, video/out/wayland_common.h, video/out/wldmabuf/context_wldmabuf.c, video/out/x11_common.c, video/out/x11_common.h
1. Make anything that's like `vo_platform_init` return a bool.
2. Cleanup vo_wayland_init on error.
3. Make vo_wayland_reconfig a bool.
=> various function return consistency fixes

player/video.c
Instead of choosing based on smallest deviation from set speed,
use the speed change from the smallest factor that does not
exceed `video-sync-max-video-change`.
Example where this makes a difference:
`mpv --no-config --speed=1.21 --video-sync=display-resample --video-sync-max-video-change=5 --video-sync-max-factor=10 https://github.com/haasn/interpolation-samples/raw/master/24fps/native.mkv`
(the same speed as pressing `]` twice)
Playback with these changes is noticeably smoother then without.
Explanation:
Without this it calculates
```
factor  1 scale 1.032727
factor  2 scale 1.032727
factor  3 scale 1.032727
factor  4 scale 1.032727
factor  5 scale 1.032727
factor  6 scale 1.032727
factor  7 scale 1.032727
factor  8 scale 0.971979
factor  9 scale 0.978373
factor 10 scale 0.983550
``` …
=> player: choose speed of smallest acceptable factor for display sync

DOCS/interface-changes.rst, DOCS/man/options.rst, common/common.h, options/options.c, player/audio.c, player/video.c
So far there was no way to sync video to display and have audio sync to video without changes in pitch.
With this option the audio does not get resampled (pitch change) and instead the corrected audio speed is applied to audio filters.
This allows higher values for `video-sync-max-video-change` without changes in pitch.
Closes #10210
=> player: add video-sync=display-tempo

DOCS/interface-changes.rst, DOCS/man/options.rst, options/options.c, player/configfiles.c
The watch-later mechanism has always unconditionally wrote start to files to save the playback position. When this was later expanded to watch-later-options, this logic was kept in place. But we don't actually have to unconditionally write this and can allow users to remove the option from the list if they want to. The start value still requires some special handling; it should always be written if possible regardless of the value changing. However, we can just place it within the default set of options for watch-later-options so it can be removed like any other.
This should fix #10776 since the auto profile condition in there would work with this PR.
=> player: don't force saving start in watch-later-options

meson.build
docutils installs these by default with .py, there just happen to be some distros that symlink/rename (Gentoo doesn't and keeps upstream's names).
waf automatically finds it even with .py, so used not to be an issue.
Thanks.
=> meson: also search for rst2html with .py extension

audio/out/buffer.c
~mpv internally has ao_lavc and vo_lavc that are used strictly for encoding mode. Because of the way option selection works, you can actually select these (--vo=lavc and/or --ao=lavc) on the commandline. Of course, these will fail (ao=lavc actually segfaults), but there's no business in allowing this anyway. Rework the ao/vo selection a bit and explictly fail if a user happens to select either one of these without also specifying encoding mode. Fixes #10175.~
Now just a null check basically.
=>  audio: fix crash during uninit on ao_lavc

TOOLS/lua/autoload.lua
The current approach does not work well with titles like `EP.1.v0.1080p.mp4`, but with this such titles get sorted properly. I've made a related PR for [uosc](https://github.com/tomasklaen/uosc/pull/426) where I tested for regressions and looked at the performance impact.
=> TOOLS/lua/autoload: improve alphanumeric sorting

.github/ISSUE_TEMPLATE/4_bug_report_build.md, DOCS/compile-windows.md, README.md, wscript
While the waf build has served us well for many years, it's time to officially consider it deprecated. The meson build was added fully with the intention to eventually replace waf and its current state is more than good enough to do that. Let's start the deprecation period now to give users a heads up to switch before we remove waf for good.
Please let me know if I missed something somewhere.
P.S. if somebody could update `compile-windows.md` with meson instructions that would be great.
=> build: officially deprecate waf

audio/out/ao.c, video/out/vo.c
As discussed in #11145 instead of relying on the last element to be NULL we can use the known length of the list.
Also the VO driver list can be static.
=> clean up driver lists for AOs/VOs

video/out/hwdec/hwdec_cuda.h, video/out/hwdec/hwdec_cuda_vk.c
This handle type was only needed for backwards compatibility with windows 7. Dropping it allows us to simplify the code: there is no longer a need for runtime checks, as the handle type can now be statically assigned based on the platform.
The motivating usecase here, apart from code simplification, is a desired switch to timeline semaphores, which (in the CUDA API) only supports the non-KMT win32 handles.
It's worth pointing out that we need no runtime check for IsWindows8OrGreater(), because the `export_caps.sync` check will already fail on versions of windows not supporting PL_HANDLE_WIN32.
=> hwdec_cuda: drop support for PL_HANDLE_WIN32_KMT

meson.build
A couple of programs were always unconditionally searched for, but we don't have to do this if we're not on darwin.
=> meson: skip some unneeded macos-specific checks

options/options.c, options/options.h, video/drmprime.c, video/out/drm_atomic.c, video/out/drm_atomic.h, video/out/drm_common.c, video/out/drm_common.h, video/out/hwdec/hwdec_drmprime.c, video/out/hwdec/hwdec_drmprime_overlay.c, video/out/opengl/context_drm_egl.c, video/out/vo.h, video/out/vo_drm.c
A longstanding pain point of the drm VOs is the relative lack of state sharing. While drm_common does provide some sharing, it's far less than other platforms like x11 or wayland. What we do here is essentially copy them by creating a new vo_drm_state struct and using it in vo_drm and context_drm_egl. Much of the functionality that was essentially duplicated in both VOs/contexts is now reduced simple functions in drm_common. The usage of the term 'kms' was also mostly eliminated since this is libdrm nowadays from a userspace perspective.
The diff is probably not really readable but some key points:
- The `kms` struct is gone and replaced by `vo_drm_state`.
- Now `vo_drm_init`, `vo_drm_uninit`, etc. are used for managing the VOs like how it works on other platforms.
- `drm_opts` was …
=> drm: rewrite based around vo_drm_state

common/msg.c, player/main.c
Previously, if log-file was set not via a CLI option (e.g. set via mpv.conf or other config file, or set from a script init phase), then meaningful early log messages were thrown away because the log file name was unknown initially.
Such early log messages include the command line arguments, any options set from mpv.conf, and possibly more.
Now we store up to 5000 early messages before the log file name is known, and flush them once/if it becomes known, or destroy this buffer once mpv init is complete.
The implementation is similar and adjacent, but not identical, to an existing early log system for mpv clients which request a log buffer.
=> msg: log-file set at mpv.conf: don't ignore early messages

DOCS/interface-changes.rst, DOCS/man/options.rst, video/decode/vd_lavc.c, video/out/dr_helper.c, video/out/dr_helper.h, video/out/gpu/libmpv_gpu.c, video/out/gpu/ra.h, video/out/gpu/video.c, video/out/gpu/video.h, video/out/libmpv.h, video/out/opengl/common.c, video/out/opengl/common.h, video/out/opengl/ra_gl.c, video/out/placebo/ra_pl.c, video/out/vo.c, video/out/vo.h, video/out/vo_gpu.c, video/out/vo_gpu_next.c, video/out/vo_libmpv.c
This reverts commit d6af6efbf9873906bd21000551fa0f284c441eff.
On platforms where the GPU cannot cache snoop the buffers we're rendering into, DR makes the decoding horrifically slow. Some of the affected platforms are any ARM with either lima, panfrost or vc4, (A64, RK3xxx, RPis, etc.) as well as seemingly low-end Intel SoCs according to user reports.
Defaulting this option to on is therefore a potential show stopper for many people who are unaware of it, as it makes the playback unusable. Meanwhile, on systems where DR works (like mine), the performance benefit appears to be in the realm of 10%, which is fine to miss out on if a user doesn't know about the option.
What seemingly changed to make this problem crop up as of late is that both mpv and drivers have gotten better, and DR is …
=> Add "auto" option to vd-lavc-dr and make it the default

DOCS/interface-changes.rst, generated/wayland/meson.build, video/out/opengl/context_wayland.c, video/out/vo_dmabuf_wayland.c, video/out/vo_wlshm.c, video/out/vulkan/context_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h, wscript, wscript_build.py
~Currently depends on wayland-protocols from master. Presumably they'll cut a new release soon though since this is a pretty major feature.~ Now depends on wayland-protocols 1.31.
Tested this on sway/wlroots with https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3511 and https://github.com/swaywm/sway/pull/6929 (with the later rebased/cherry-picked locally). Seems to work as desired and fortunately it's not nearly as invasive into mpv's geometry handling as I initially feared.
This does sort of change the semantics of how mpv on wayland handles HiDPI but it's actually more inline with other platforms now. Basically, the window is always scaled by the extra scale factor. Previously, it was always shown as the exact pixel size with no extra scaling.
Eventually, I'd like to …
=> wayland: add wp-fractional-scale-v1 support

video/out/opengl/context_glx.c, video/out/opengl/context_x11egl.c, video/out/vulkan/context_xlib.c
PresentNotifyMSC turns out to be not only redundant, but also harmful with x11egl because eglSwapBuffers in mesa uses PresentPixmap behind the scenes when DRI3 is available, which already generates a PresentCompleteNotify event when the buffer swap actually finishes. This is important because without using the timing information from these PresentCompleteKindPixmap events, there's no way for mpv to know exactly when a frame becomes visible on the display.
By using PresentNotifyMSC in conjunction with eglSwapBuffers, two problems are created:
1. mpv assumes that a vblank won't elapse (i.e., it assumes the current MSC won't change) between the time when eglSwapBuffers enqueues the buffer swap and the time when mpv calls PresentNotifyMSC to ask xorg for a notification at the next MSC, …
=> x11: remove PresentNotifyMSC from egl/glx/vulkan to fix xpresent timing

audio/out/ao.h, audio/out/ao_alsa.c, audio/out/ao_coreaudio.c, audio/out/ao_openal.c, audio/out/ao_oss.c, audio/out/ao_pipewire.c, audio/out/ao_pulse.c, audio/out/ao_sndio.c, audio/out/ao_wasapi.c, player/command.c
ao-volume is represented in the code with a `struct ao_control_vol_t` which contains volumes for two channels, left and right.
However the code implementing this property in command.c never treats these values individually. They are always averaged together. On the other hand the code in the AOs handling these values also has to handle the case where *not* exactly two channels are handled.
So let's remove the `struct ao_control_vol_t` and replace it with a simple float.
This makes the semantics clear to AO authors and allows us to drop some code from the AOs and command.c.
Tested with:
=> audio: simplify implementation of property ao-volume

meson.build
When building both cplayer and libmpv in the same build previously all sources were built twice.
By reusing the objects from libmpv in cplayer we can thus save 50% percent of the build steps.
=> meson: reuse libmpv objects for cplayer

video/out/hwdec/hwdec_vaapi.c, video/out/vo_dmabuf_wayland.c
It turns out the vaExportSurfaceHandle() may open file descriptors even if the export fails !
=> Plug a few file descriptor leaks

DOCS/man/ipc.rst
Add a missing 'not' to the JSON-IPC documentation.
=> DOCS: Add missing 'not'

DOCS/client-api-changes.rst, DOCS/man/input.rst, DOCS/man/javascript.rst, DOCS/man/lua.rst, libmpv/client.h, misc/json.c, misc/node.c, misc/node.h, options/m_option.c, options/m_property.h, player/client.c, player/command.c, player/javascript.c, player/javascript/defaults.js, player/lua.c, player/lua/defaults.lua
This will replace shared-script-properties in new usage. It can be used for all the same things, but is much more versatile. Clients can create arbitrary sub-objects, and text expansion can access them.
For instance, if a script sets `udata/my-script/property1` to "test", that value will be available by expanding `${udata/my-script/property1}`.
=> player/command: add udata property

DOCS/man/input.rst, DOCS/man/javascript.rst, DOCS/man/lua.rst, player/javascript/defaults.js, player/lua/defaults.lua
This reverts:
3fb4140c lua/defaults: add user_data helpers
68a20e7a javascript/defaults: add user_data helpers
00510379 lua/js: fix user_data_del util function
As well as the lua/js parts of:
3ec2a098 docs: document new user-data property
user-data and its sub-properties can be set/get/observed/deleted via the standard properties interface, so there's no need for additional helpers specific to user-data, which only added maintenance burden.
=> lua/js: remove user-data helpers

DOCS/man/options.rst, video/out/wayland_common.c
The first two commits are fixes. The last one adds a new choice to `wayland-configure-bounds` so it behaves in a more user-friendly manner.
=> wayland geometry/scaling fixes and improvements

video/image_writer.c
Writing an image either with vo_image or with a screenshot will strip the colorspace info because it allocates a new mp_image that contains the same data as the old image after calling mp_image_params_guess_csp. However, mp_image_params_guess_csp cannot always guess the appropriate colorspace, so it picks a "sane default." Since this function also changes parameters so the space always makes sense, this extra info isn't harmful and allows screenshots and vo_image outs to be properly tagged with the correct colorspace.
Fixes #10988.
=> video/image_writer: avoid stripping colorspace info when writing image

audio/out/ao_pipewire.c
Use the ao->probing property to upgrade the status message when the AO is explicitly selected.
Suggested-by: uau on #mpv-devel
Cc @philipl
=> ao_pipewire: adjust message level based on probing

DOCS/man/options.rst, audio/out/ao_pipewire.c
Note: If this leads to a conflict and therefore an error then the failure will not be properly returned from `init()` and playback will be stuck. I am working on an independent PR that fixes this.
=> ao_pipewire: add support for exclusive mode und report errors from init()

DOCS/man/input.rst
This is a small change to address #11256 
Removes 2 lines stating that the features `subtext` and `sub-text-ass` are experimental and may be removed.
=> DOCS/input: remove experimental note from sub-text and sub-text-ass

DOCS/interface-changes.rst, DOCS/man/options.rst, video/image_writer.c
With significant improvements to the color tagging support in various screenshot formats, e.g. cICP in FFmpeg, and JPEG XL's generally robust color support, it's safe to default this to yes.
=> video/image_writer: change screenshot-tag-colorspace default to yes

video/out/hwdec/dmabuf_interop.h, video/out/hwdec/dmabuf_interop_wl.c, video/out/hwdec/hwdec_drmprime.c, video/out/hwdec/hwdec_vaapi.c, video/out/vo_dmabuf_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h, video/out/wldmabuf/context_wldmabuf.c, video/out/wldmabuf/ra_wldmabuf.c, video/out/wldmabuf/ra_wldmabuf.h
For formats that are **not** supported by hardware, this PR enables the choice of an upload format that is supported by the compositor.
=> format detection for vaapi+wayland : accept/reject based on compositor support

sub/osd_libass.c
The `osd-overlay` command didn't trigger a redraw when the overlay was set to hidden.
This is fine when the overlay was already hidden before that, but transitioning from not hidden to hidden requires a redraw.
Closes #10227
=> command: only avoid redrawing when old and new osd are both hidden

DOCS/man/ao.rst, audio/out/ao_pipewire.c
PipeWire supports a global volume control for streams that works on top of the per-channel volumes.
As mpv only supports a single volume with ao-volume it can make sense to use the single global volume from PipeWire for it. This allows the user to also specify per-channel volumes and not have mpv trample over them.
This mode is not the default as pulseaudio does not support this global volume control and all tooling controlling PipeWire via pipewire-pulse (like pavucontrol) will not be able to see this channel.
=> ao_pipewire: allow usage of global volume control

options/m_property.c
This allows operations on properties with longer names (e.g. deeply-nested user-data sub-props).
=> m_property: avoid using a small stack buffer in m_property_do_bstr

player/screenshot.c, video/image_writer.c, video/image_writer.h, video/out/vo.h, video/out/vo_gpu_next.c
A series of screenshot-related changes aimed at fixing #10988.
Testing very heavily welcome. I'm not entirely happy with this, because I think there are a few corner cases that need to be ironed out. And in particular, it might be worth making sure `screenshot window` still dumps out pixels as-is, since this is actually a useful debugging tool (for myself and others), which I think this series breaks.
RFC, I guess.
=> vo_gpu_next: overhaul screenshot support (HDR/native screenshots, better colorspace defaulting, better triggering of fast path)

audio/out/ao_pipewire.c
Older versions of pipewire segfault when calling spa_hook_remove() on hooks that are zeroed.
Add a backfill for the logic added by pipewire 0.3.57.
Being able to remove zeroed hooks makes errorhandling much easier.
Fixes #11309
Cc @philipl 
@acedogblast  Could you validate this?
=> ao_pipewire: fix removal of zeroed hooks on old pipewire

video/image_writer.c
effort=4 has a significant increase in quality/bpp compared to effort=3 with a very minor increase in encoding time. It's worth the trade-off as a default setting for lossy encoding.
=> video/image_writer: use effort=4 default for JXL screenshots

video/out/vo_dmabuf_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h, video/out/wldmabuf/ra_wldmabuf.c
This was originally dropped because it was thought to be unneeded at the time, but at least some devices (rockchip) apparently are still on old compositors that use linux-dmabuf v2. It's not much code, and for testing purposes it's good to have around since it's hard to test drmprime otherwise. Some minor additions are here to support the newly added vaapi-format mapping in v2 of the protocol.
This reverts commit a5b9d529eec8d4bb6fc858143337c3573ec8afd0.
=> Revert "vo_dmabuf_wayland: drop support for linux-dmabuf-v2"

video/filter/vf_format.c, video/mp_image.c, video/mp_image.h, video/out/placebo/utils.c, video/out/placebo/utils.h, video/out/vo_gpu_next.c
The changes would allow `vo=gpu-next` to have per-frame/scene dynamic brightness metadata coming from the Dolby Vision RPU.
I've changed the implementation to have the dependency in `libplacebo` instead.
Blocked by https://code.videolan.org/videolan/libplacebo/-/merge_requests/371 for now
=> vo_gpu_next: parse Dolby Vision metadata for dynamic scene brightness

meson.build, options/options.c, video/out/gpu/context.c, wscript, wscript_build.py
This allows building directly against ICDs that don't implement this extension.
=> Vulkan: add configure check for VK_KHR_display extension

DOCS/client-api-changes.rst
incorrectly placed under 0.35.0 by 2cfaa820e54b12de437bb4da97d894ad610abcdd
=>  DOCS/client-api-changes.rst: move mpv_del_property to 0.36.0

video/out/vo_gpu_next.c
=> vo_gpu_next: fix color space hint with target peak override

video/decode/vd_lavc.c
on android the autoprobe order looks as follows:
<pre>
[vd:info]   mediacodec (h264_mediacodec-mediacodec) device=10 copying=0
[vd:info]   mediacodec (mpeg2_mediacodec-mediacodec) device=10 copying=0
[vd:info]   mediacodec (av1_mediacodec-mediacodec) device=10 copying=0
[vd:info]   mediacodec (hevc_mediacodec-mediacodec) device=10 copying=0
[vd:info]   mediacodec (mpeg4_mediacodec-mediacodec) device=10 copying=0
[vd:info]   mediacodec (vp8_mediacodec-mediacodec) device=10 copying=0
[vd:info]   mediacodec (vp9_mediacodec-mediacodec) device=10 copying=0
[vd:info]   v4l2m2m-copy (h263_v4l2m2m-v4l2m2m-copy) device=0 copying=1
[vd:info]   v4l2m2m-copy (h264_v4l2m2m-v4l2m2m-copy) device=0 copying=1
[vd:info]   mediacodec-copy (h264_mediacodec-mediacodec-copy) device=10 copying=1
[vd:info] …
=> hwdec autoprobing improvements

DOCS/man/input.rst, player/command.c
The title in the playlist should get set when we get a title and the playlist title isn't set already.
#8548 has essentially the same goal, but this has the advantage that
1. It actually works (maybe the handling of media-title has changed since that was implemented)
2. The title gets stored in the playlist item instead of only showing the media-title as the playlist-item title when the playlist property gets accessed, so printing the playlist will show the title too.
3. The media-title does not shadow the playlist-item title if it actually has one set.
4. Any playlist item that has been opened will have a title if it didn't already have one from the playlist file, not only the current one
Somewhat closes #4780, but still only shows titles for files/urls that have been opened before. I …
=> player: set playlist title to media title if not set already

player/lua/console.lua, player/lua/osc.lua
This is pretty self-explanatory. The improvement to `console` is pretty clear.
In theory, `osc` could also use property observation to allow other clients to set `osc/visibility` and `osc/idlescreen`, though it'd need to make sure to avoid infinite recursion with itself.
=> Use user-data for builtin scripts

options/m_option.c, options/m_option.h, options/m_property.c, options/m_property.h, player/client.c
Changing the CONF_TYPE_FLAG was a bad idea because mpv_node.u.flag
continues to be an int, leading to a mismatch in type sizes which can
lead to problems with memcpy().
Closes #11373
=> Revert property transition

player/audio.c
Fixes #8301. duplicate is in line 194.
https://github.com/mpv-player/mpv/blob/master/player/audio.c#L186-L195
=> audio: remove a duplicate clearing of a struct variable

TOOLS/lua/autocrop.lua
This reorders some code and checks the image track-list sub-property
instead of the albumart one, so that when playing audio without enough
playtime-remaining and images, the "autocrop only works for videos."
warning is logged instead of the "Not enough time to detect crop." one.
It also avoids repeating this warning twice in the code.
As of e16d0dd15d current-tracks returns a video track even when
lavfi-complex is used, so the track-list loop in is_cropable can be
replaced with just checking current-tracks/video while still cropping
videos with lavfi-complex.
=> TOOLS/autocrop.lua: log a more accurate warning

player/lua/ytdl_hook.lua
This refactors exec to only return the result of the subprocess command,
and makes the rest of run_ytdl_hook use the fields of this result,
because specifying all those return values multiple times is unwieldy
now that exec is called several times, and this is easier to read
anyway.
I removed the line
err = string.format("%s returned '%d'", err, es)
altogether instead of updating the es variable, because there was no
chance of it being executed since it would only happen when
result.killed_by_us is true, but run_ytdl_hook returns early when it is.
=> ytdl_hook.lua: make exec return a single value

player/lua/ytdl_hook.lua
ytdl_hook always set force-media-title, making users unable to force a media-title via options.
To prevent that, check if force-media-title is already set to avoid overwriting it.
ref. https://github.com/mpv-player/mpv/pull/10453#issuecomment-1445277496
=> ytdl_hook: don't overwrite force-media-title

video/filter/vf_gpu.c, video/out/gpu/video.c
As per https://github.com/mpv-player/mpv/blob/master/video/out/gpu/ra.h#L130
Writing my own RA and I hit an issue by assuming depth couldn't be null.
=> video: Fix depth=0 on textures downloaded from ra

video/out/gpu/d3d11_helpers.c
Similar to libplacebo, `DXGI_SWAP_EFFECT_FLIP_DISCARD` is preferred on Windows 10 or later.
=> Prefer `DXGI_SWAP_EFFECT_FLIP_DISCARD` over `DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL` on Windows 10 or later

video/out/gpu/context.h, video/out/vo_dmabuf_wayland.c, video/out/vo_wlshm.c, video/out/wayland_common.c, video/out/wayland_common.h
The alpha argument is only used as a bool but is an int. Passing a 0 or 1 to an argument called alpha is confusing - at first glance it looks like you're specifying an alpha value of 0 or 1. Since it's only used as a bool, make it a bool.
=> wayland: Use bool type for vo_wayland_set_opaque_region

video/out/wayland_common.c, video/out/wayland_common.h
Which is `wl->video_surface` for vo_dmabuf_wayland.
Listening on `wl->surface` results in freezes if it is occluded and culled by the compositor. Which mutter does, and the wl_surface::frame spec warns about:
> A server should avoid signaling the frame callbacks if the surface is not visible in any way, e.g. the surface is off-screen, or completely obscured by other opaque surfaces.
=> wayland: request frame callbacks on the topmost surface

DOCS/man/mpv.rst, DOCS/man/options.rst, sub/ass_mp.c, sub/ass_mp.h, sub/osd.c, sub/osd.h, sub/osd_libass.c, sub/sd_ass.c
These options make it possible to specify the directory that will be
passed to `ass_set_fonts_dir()`, akin to VLC's `--ssa-fontsdir` and
FFmpeg's `fontsdir`.
Fixes #8338
=> sub: add --sub-fonts-dir and --osd-fonts-dir options

video/out/gpu/ra.c
This came up in #9828. According to the header comments, creating a 1D ra_tex requires height and depth to be set to 1. For a 2D texture, it requires depth be set to 1. There were a couple of spots in mpv's code where this wasn't be followed. Although there was no known bug from this, the rest of the code works like this so it was a good idea to go ahead and sync it up. As a followup, let's just add a couple of simple asserts to ra.c to enforce this so it doesn't go unnoticed in the future.
Inspired by @sfan5's comment: https://github.com/mpv-player/mpv/pull/9828#issuecomment-1448491152
=> ra: assert when using params with dimensions

player/lua/ytdl_hook.lua
With dash the first fragment was always considered an init fragment if
there wasn't a duration. However that only makes sense when there are
also other fragments, so check if there are other fragments in addition
to the lack of a duration.
It will always print the error "EDL doesn't support fragments without duration with MP4 DASH", and _someone_ will probably complain about that, so maybe we should make it a warning instead?
Closes #11392
=> ytdl_hook: init fragment requires other fragments

video/mp_image.c
This fixes HDR10 and HDR10+ metadata usage in vo_gpu_next when hwdec copy variant is used.
=> mp_image: copy side data in mp_image_copy_attributes

video/out/wayland_common.c
Resizing by mouse didn't work for me on KDE plasma (didn't try anything else).
This change fixes it for me, but I don't have any other DE installed, so please also test on something else if possible.
Touch input doesn't test for the presence of borders, should we change that?
=> wayland: fix client side resize

video/out/vo_gpu_next.c
libplacebo v6.265.0 removed v4 deprecations. We already require PL_API_VER >= 202, so we don't need to wrap pl_tex_transfer_params.row_pitch around a conditional, which exists since PL_API_VER >= 168. However, pl_source_frame does not exist until PL_API_VER >= 219, so we should use a conditional directive.
=> vo_gpu_next: compatibility with libplacebo v6.265

common/av_common.c, common/av_common.h, sub/lavc_conv.c, sub/sd.h, sub/sd_ass.c, sub/sd_lavc.c
First const'ifies all getters that take in `mp_codec_params` as an argument, then extends lavc_conv's init to take in the full mp codecpar struct.
This way we receive such minor details as the profile (necessary for ARIB captions, among others) during init. This enables decoders to switch between ARIB caption profile A and profile C streams.
Verified by @aimoff  .
For image based subs (`sd_lavc`):
=> sub/lavc_conv: properly fill avctx with codecpar values at init

.github/workflows/build.yml, test/meson.build, test/ref/draw_bmp.txt, test/ref/img_formats.txt, test/ref/repack.txt, test/ref/zimg_formats.txt
=> update tests for ffmpeg 6.0

options/options.c
If an mpv build neither supports lua nor javascript, but only cplugins, the scripts options are still usable to select which cplugins to load.
=> options: enable scripts related opts also with cplugins.

DOCS/man/lua.rst
Fixed a typo in `DOCS/man/lua.rst`.
=> DOCS/lua: fix typo

DOCS/man/input.rst, player/screenshot.c
This feels like the most sane way to resolve the copying to clipboard issues that I've had with other scripts, where you had to take 2 screenshots if you wanted to keep a copy on disk.
Now all it takes is this:
```lua
res, err = mp.command_native({"screenshot"})
if err == nil or res == nil then
mp.command_native_async({'run', 'xclip', '-sel', 'c', '-t', 'image/png', '-i', res.filename}, function(suc, _, err)
mp.osd_message(suc and 'Copied screenshot to clipboard' or err)
end)
end
```
=> player/screenshot: add filename return field

meson.build
This is the latest stable release, and what we should use for libplacebo-next per haasn's recommendation.
The previous 202 version wasn't even a release.
=> meson: bump libplacebo-next required version to 5.264

video/out/gpu_next/context.c, video/out/vo_gpu_next.c, wscript
We don't need these anymore now that we require PL_API_VER>=264 for building libplacebo-next. Also bump PL_API_VER for waf
=> vo_gpu_next: drop various PL_API_VER checks

demux/demux_lavf.c
`io_close2` was introduced as a superior replacement for `io_close` in ffmpeg 5.0, and then deprecated in 6.0. The difference is that `io_close2` can return errors. In our case, we're just calling through to the original function anyway, so we don't need to do more than pass the return value back.
=> demux_lavf: update to handle deprecation of `io_close`

player/lua/auto_profiles.lua
Previously, it just silently didn't do anything which is not very intuitive. Since the lua api returns an error string, check to see if it matches the "property not found" case and print an error message. Additionally, don't add the fake property to the internal cached_properties list or try to observe it. This avoids redundant evaluate calls which will never actually succeed. We do still mark it under watched_properties however. This avoids having to call mp.get_property_native multiple times.
=> auto_profiles: check for non-existent properties

meson.build, video/out/opengl/context_angle.c, wscript
Recent MSYS update switched to using vanilla EGL headers, which doesn't include eglext_angle.h implicitly.
=> context_angle: include eglext_angle.h explicitly

player/lua/osc.lua
The idle logo could appear on the left side of the window for a split second after starting.
That is because when osd dimensions can be reported as 0 at the very beginning.
Since the width gets calculated based on a fixed height and the aspect ratio, which is 0, that results in a width of 0 until the next update.
ref. https://github.com/mpv-player/mpv/pull/10712#issuecomment-1274398139
@Obegg can you please test if this fixes the problem for you?
=> osc: skip rendering when osd_dimensions are 0

DOCS/man/mpv.rst, player/lua/auto_profiles.lua
Instead of erroring when values returned by profile-cond expressions aren't booleans, apply the relative profiles as long as the return values are truthy. This allows shortening conditions like
`profile-cond=path:match('foo') ~= nil`
to
`profile-cond=path:match('foo')`
=> auto_profiles.lua: apply profiles when conditions are truthy

.github/workflows/lint.yml, ci/lint-commit-msg.py
works on PRs and normally pushed commits (in a branch)
here's an example how it looks https://github.com/sfan5/mpv/pull/1
to get a feeling for the rules, here's all commits since last release thrown into it: https://0x0.st/HXrp.txt
most are directly and objectively grounded in contribute.md, some other could be argued to be personal preference
=> ci: add a workflow that lints commit messages

video/mp_image.c
As the Dolby Vision metadata is only supported for vo_gpu_next, the check whether to use the metadata is now handled by `mp_map_dovi_metadata_to_pl` in `placebo/utils.c`.
It doesn't hurt to keep the metadata in `mp_image`, and might be useful to library users.
I'm just not sure how it affects encoding?
=> mp_image: always add AV_FRAME_DATA_DOVI_METADATA when present

video/out/gpu/video.c
Make the index into the arrays in copy_image()
unsigned to make compiler trust that we don't access out of bounds and prevent compiler warning.
=> video/out/gpu: Fix compilation warning of out of bound access

player/screenshot.c
If --screenshot-tag-colorspace=no, then there won't be any color tags in the output space, so PNG and JXL screenshots should be written as sRGB rather than the native space of the input video.
=> player/screenshot: avoid non-sRGB spaces with --screenshot-tag-csp=no

video/out/wayland_common.c
Bounds are received as Wayland logical units, but is currently treated as physical units.
Fixes #11571.
=> wayland: correctly scale configure_bounds

DOCS/man/input.rst, meson.build
This finally allows us to put any user defined options into the CONFIGURATION variable like what waf does. The arbitrary hardcoded fallback is left in place for old meson versions. Also update the documentation in regards to the mpv-configuration variable to be relevant to meson.
I opted to just pass the string from `meson.build_options()` directly into the define instead of trying to prefix it with `meson setup build` or something since there's a lot of different ways you can change the build options.
=> meson: use the new build_options method

player/lua/ytdl_hook.lua
Fixes the issue where an entire youtube video would be played instead of just the specified clip.
Also adds previously unsupported reading of yt-dlp's end_time parameter.
Fixes #11567
=> ytdl_hook: fix clip start and end

video/out/hwdec/dmabuf_interop_gl.c, video/out/hwdec/hwdec_drmprime.c
With these changes mpv is now aware of the "rpi4_8" and "rpi4_10" formats that are used for HEVC hardware decode on the Raspberry Pi 4. To make this work with the existing mpv structure I had to do a couple things. The first was manually defining the IMGFMTs because ffmpeg doesn't. Usually for special HW accel formats ffmpeg handles it, but not in this case, so it is just made to act like NV12. The second was to use a #define for the AV_PIX_FMTs because otherwise mpv wouldn't compile with normal ffmpeg. This is admittedly a little hacky but it shouldn't interfere with anything and can be removed once the changes from https://github.com/jc-kynesim/rpi-ffmpeg are upstreamed. These formats also won't work without some changes I did in mesa which the status of can be found here …
=> hwdec_drmprime: support rpi4_8 and rpi4_10 formats

video/out/vo_gpu_next.c
Address of variables can't be used for constant initialization in C language modes.
See https://github.com/llvm/llvm-project/commit/0c43d8077e605ab78d85180f0dcaa4df1ae37607
=> vo_gpu_next: fixes to allow using dllimport

sub/dec_sub.c, sub/sd_ass.c
Previously, changing options like sub-ass at runtime only worked for interleaved ASS subs whereas external or converted subs would simply disappear. This PR fixes that issue.
=> sub: fix UPDATE_SUB_HARD for converted and external subtitles

misc/charset_conv.c
If mp_iconv_to_utf8 was given an empty string to convert in the buf parameter it would corrupt memory when writing a null into outbuf before returning it to the caller. This happened when streaming from a URL that ends in a slash. For such a URL the method mp_basename returns an empty string. The method append_dir_subtitles passes the result returned from mp_basename to mp_iconv_to_utf8 which then corrupts memory. This was detected using Guard Malloc. The fix changes mp_iconv_to_utf8 check up front if buf is empty and if it is return buf as the result in compliance with the documented behavior of the method when no conversion is needed.
Fixes #11626
=> charset_conv: fix memory corruption in mp_iconv_to_utf8

options/parse_configfile.c, options/parse_configfile.h, player/client.c, player/configfiles.c, player/main.c
This aligns the possible sources of config files other loaded data. For example `--input-conf`.
=> options: read config file as stream

meson.build
This lets us use meson's custom dl dependency as well as the version method when checking rst2pdf's version.
libplacebo requires 0.63 anyways, so not really a big burden imo.
=> meson: bump required version to 0.62

DOCS/man/options.rst
The `--x11-name` option takes a string for the window class name, but this isn't reflected in the man page.
=> DOCS/options: document required parameter for --x11-name

video/mp_image.c
The old frame properties are deprecated and have been replaced by frame flags.
=> mp_image: use the ffmpeg interlaced frame flags where available

DOCS/interface-changes.rst, DOCS/man/options.rst, video/out/gpu/lcms.c, video/out/gpu/lcms.h, video/out/vo_gpu_next.c
Also while at it respect target-peak option when ICC profile is used.
Fixes #11449
=> vo_gpu_next: allow to use ICC profile luminance value

demux/demux_lavf.c
Note that this won't fix all HLS issues because a commit still needs to be merged upstream. Ideally test it with: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20230512202622.29531-1-leo.izen@gmail.com/
=> demux/demux_lavf: pass dummy filename when an HLS mimetype is detected

player/external_files.c
Previously, we'd only attempt to call guess_lang_from_filename if the external file name matched the video name ignoring the extensions. So if they didn't match, we'd just report the language as "unknown". And since the name will never match for urls, the language would always be treated as unknown.
Now we'll always try to guess the language from the filename regardless of its similarity to the video file name.
Closes #10348
=> player: always try to detect subtitle language from file name

video/out/vo_gpu_next.c
Address of variables can't be used for constant initialization in C language modes.
=> vo_gpu_next: fix to allow using dllimport

video/out/hwdec/hwdec_vulkan.c
ffmpeg was previously allocating images for frames as the code size,
rather than the presentation one (1088 vs 1080 in the most common
example). Using the coded size when wrapping images for libplacebo
resulted in incorrect scaling from 1088 -> 1080, but even using the
presentation size wasn't perfect, as discussed in the original
commit.
However, ffmpeg has now been updated to use the presentation size for
the frame images, after discussions that concluded this must be done
because there is no way for a frame consumer to fix the dimensions
without copying the frame.
With that ffmpeg change, we can just use the normal layout information
like all the other hwdecs.
=> hwdec_vulkan: account for vulkan frames now using presentation size

video/out/vulkan/context.c
=> vo/vulkan: do not define zero sized array

meson.build, video/out/vulkan/context.c, wscript
I originally wrote this trying to avoid doing an explicit version check on the headers, but it just makes things more confusing, and the requirements harder to understand.
So, Vulkan interop now takes a dependency on the header release where they finalised the video decode headers. VK_EXT_descriptor_buffer was added in 1.3.235, so that's covered as well.
Along the way I fixed a bug in the waf build where it was depending on libplacebo-next instead of libplacebo-decode.
=> hwdec_vulkan: simplify requirement checks for Vulkan interop

demux/demux_lavf.c
Unfortunately Content-Type matching seems to be not enough as there are mistagged streams. Try to match extension and pass-through URL.
Fixes #11700
=> demux/demux_lavf: strip URL parameters before matching extension

player/external_files.c
519e56f caused an attempt to get the language even if the file name didn't start with the movie title. However, detecting a language when fuzz >= 1 or the language is known, caused prio to be non-zero which caused the file to be included regardless of its name. This shouldn't be the behavior when sub-auto != all.
Now all the prio updates that depend on lang will only happen if the file in question starts with the movie name. Since language was never detected before if this wasn't true, the behavior should be the same as before 519e56f when sub-auto != all.
Closes: #11749
and merged faster. Nobody wants …
=> player: don't load unwanted files after 519e56f

DOCS/man/mpv.rst
It is worth adding this example because it has been asked multiple times in the issue tracker and the IRC channel.
string.find() is used because it's 20 times faster than string.match().
=> DOCS/mpv: add an example for applying profiles to certain paths

ci/build-msys2.sh
Now that it has been fixed upstream we can enable and test if it links correctly.
=> ci/msys2: enable egl-angle-lib

DOCS/man/options.rst, options/options.c, options/options.h, video/out/wayland_common.c, video/out/x11_common.c
See #9201 for some related discussion. tl;dr: wayland sucks but this isn't a bad option to have regardless to allow more precise control over the exact drag-and-drop behavior.
Windows and macOS were omitted because both are surprisingly complicated here. Windows requires using `m_config_cache_get_next_changed` to truly have runtime support option changes which isn't too bad but I have no way of testing it anyway so I didn't bother. No idea what's going on in macOS.
=> player: add drag-and-drop option

generated/wayland/meson.build, meson.build, video/out/vo_dmabuf_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h, video/out/wldmabuf/ra_wldmabuf.c, waftools/checks/custom.py, wscript
Since debian 12 is out, we can bump quite a few wayland-related things without feeling too bad. This lets us drop a lot of annoying guards and stuff.
=> bump minimum required wayland versions

audio/out/ao_pipewire.c, meson.build
Now that Debian 12 is released, bump the minium required version to what is provided in Ubuntu Jammy (22.04).
The same as has been done for the wayland dependencies.
=> ao_pipewire: bump dependency to 0.3.48

video/out/vo_mediacodec_embed.c
mediacodec_embed uses "vo" instead of "hw". Fix the following error:
../video/out/vo_mediacodec_embed.c:60:20: error: use of undeclared identifier 'hw'
MP_VERBOSE(hw, "Failed to create hwdevice_ctx\n");
=> hwdec: Fix undeclared identifier in mediacodec_embed

player/loadfile.c
in the first iteration, *out will be null and thus the steal and the strdup both sets the parent to NULL - leaking the allocation later on (caught via LeakSanitizer).
let append_lang() take care of setting the parent instead.
=> loadfile: fix leak due to setting NULL parent

sub/osd.c, video/filter/refqueue.c, video/mp_image.c, video/out/vo.c
this changes mp_image_new_ref() to handle allocation failure itself instead of doing it at its many call-sites (some of which never checked for failure at all).
also remove MP_HANDLE_OOM() from the call sites since this is not necessary anymore.
not all the call-sites have been touched, since some of the caller might be relying on `mp_image_new_ref(NULL)` returning NULL.
Fixes: https://github.com/mpv-player/mpv/issues/11840
=> mp_image: abort on av_buffer_ref() failure

DOCS/man/options.rst, video/decode/vd_lavc.c
Today, the only way to make mpv consider multiple hwdecs and pick the first one that works is to use one of the `auto` modes. But the list that is considered in those cases is hard-coded. If the user wants to provide their own list, they are out of luck.
And I think that there is now a significant reason to support this - the new Vulkan hwdec is definitely not ready to be in the auto list, but if you want to use it by default, it will not work with many codecs that are normally hardware decodable (only h.264, hevc and av1 if you are very lucky). Everything else will fall back to software decoding.
Instead, what you really want to say is: use Vulkan for whatever it supports, and fall back to my old hwdec for everything else.
One side-effect of this implementation is that you can freely mix …
=> vd_lavc: let the user provide a priority list of hwdecs to consider

options/options.c
shorter and more robust this way instead of inserting at an index by
manually counting.
the surrounding code also uses `[STREAM_*] = ..` so it's more consistent
as well.
the reason for these casts are unknown but they were presumably to
silence warnings 9 years ago. but it doesn't seem to be necessary
nowadays, so just drop the casts and also drop the `const` from the
compound literal type.
some small technical notes:
1. while string literals aren't `const` in C, writing to them is
undefined (do not ask me why). and so compilers will typically put
string literals into read only section anyways, regardless of
weather `const` was used in the source or not. so this shouldn't make
any difference codegen wise.
2. making the array of pointers `const` on the other hand might affect
codegen, eg: …
=> options: minor style fixes

DOCS/man/options.rst, options/options.c, video/out/w32_common.c, video/out/wayland_common.c, video/out/win32/droptarget.c, video/out/win32/droptarget.h, video/out/x11_common.c
First commit implements the `no` option for `drag-and-drop`. The second commit attempts to implement the option in windows (didn't seem too bad looking at again). Of course, that is completely untested so if someone (ping @kasper93) could test to make sure it actually works, that would be appreciated.
=> add --no-drag-and-drop and a windows implementation

.github/workflows/build.yml, ci/build-msys2.sh, ci/msys2-meson.txt
Fixes: eb4da3400a1c37eea7b258b00297e8b8fcdd8db4
=> ci/msys2: double down on running meson through python3.11

meson.build, video/out/vo_gpu_next.c
Instead copy the data on-demand when VOCTRL_PERFORMANCE_DATA is requested.
This require minimal libplacebo API version bump. Since new libplacebo release is close and the requirement in mpv is planned to be bumped too let's wait for it instead ifdefing everything. In the meantime we can review, so it is ready when it gets unblocked.
=> vo_gpu_next: use pl_dispatch_info_move to avoid useless data copy

wscript
Was forgotten in b73d96776cfee61f88bf60b27315baab32a2115d. Can't wait until we finally remove the waf build.
=> wscript: bump required libplacebo-next version to 5.266

TOOLS/lua/autoload.lua
We used to sort the playlist with playlist-move after every loadfile (slow operation).  
Instead, append all files in order and call playlist-move once to move the only entry we don't control the position of.  
Don't fetch every playlist item separately, reuse native property.  
We used to pick up on new files added to the directory, but only when playing an entry at the edge of the playlist due to an early return.  
New files are now added to the playlist on every file change.  
This still works as expected and doesn't load duplicate files on shuffled playlists or playlists with files manually added after autoload.
33% faster on average for my test directory with 1371 files. Initial run of `find_and_add_entries` went from 1.6s-2.2s (2s avg) to 1.1s-1.4s (1.3s avg).
Not moving the current …
=> TOOLS/lua/autoload: avoid unnecessary playlist manipulation, performance

DOCS/interface-changes.rst, DOCS/man/options.rst, options/options.c, options/options.h, video/out/wayland_common.c, video/out/x11_common.c
See #8938.
Add an option for allowing pointer events to pass through the mpv
window. This could be useful in cases where a user wants to display
transparent images/video with mpv and interact with applications beneath
the window. This commit implements this functionality for x11 and
wayland. Note that whether or not this actually works likely depends on
your window manager and/or compositor. E.g. sway ignores pointer events
but does not send the events to the window below (no clue if intentional
or a bug). Weston behaves as expected.
As an aside, the APIs do allow for specifying a region of any arbitrary size for a passthrough. I did not think such granularity would have any practical use. Most likely, you either would want mouse events on the entire window (vast majority of cases) or …
=> player: add --input-cursor-passthrough option

DOCS/man/options.rst, demux/cache.c, video/out/gpu/lcms.c, video/out/vo_gpu_next.c
mp_get_platform_path has a trick where it will return null if
--no-config is used in order to avoid loading config files. When trying
to get a cache or state path, this logic was copied, but it doesn't
really make any sense. We should always try to get some path when
calling either one of those types and avoid returning NULL. It fixes a
segfault that occurs if you do --no-config --vo=gpu-next because cache
is on by default and the aforementioned behavior of
mp_get_platform_path.
@sfan5: I don't think this should regress anything for android but could you double check?
=> various: correctly ignore cache files with --no-config

TOOLS/lua/autoload.lua
Certain file extensions are unlikely to be added to the set by default, such as ".ts" because they conflict with typescript files. Allow users to add them anyway through script-opts if they wish to do so.
=>  TOOLS/lua/autoload.lua: allow extending ext sets from script-opts

DOCS/interface-changes.rst, DOCS/man/options.rst, demux/demux_playlist.c, options/options.c, options/options.h
Adds a new option `--directory-mode=recursive|lazy|ignore` to control recursive loading of directories, as suggested in https://github.com/mpv-player/mpv/pull/11292#issuecomment-1426792272
Sort files in front of directories, as suggested in https://github.com/mpv-player/mpv/pull/11292#issuecomment-1426701499
=> Improving directories in playlists

osdep/terminal-unix.c
the reason for checking `EBADF|EINVAL` specifically is unknown. but it's clearly not working as intended since it can cause issues like #11795.
instead of checking for "bad errors" check for known "good errors" where we might not want to break out. this includes:
* EINTR: which can happen if read() is interrupted by some signal.
* EAGAIN: which happens if a non-blocking fd would block. `tty_in` is _not_ non-blocking, so EAGAIN should never occur here. but it's added just in case that changes in the future.
Fixes: https://github.com/mpv-player/mpv/issues/11795
- - -
Supersedes https://github.com/mpv-player/mpv/pull/11805, since that PR seems to be abandoned by the author. There was some discussion about the issue in that PR.
=> terminal-unix: better error detection logic

input/ipc.c, misc/json.h, player/lua.c, test/json.c
This change allows decoding deeper nested JSON with `utils.parse_json()` from Lua scripts.
I have no clue if 50 is a good or bad value. There seems to be no information why it was set to 32. I set the value to 50 because that value is used here as well:
https://github.com/mpv-player/mpv/blob/6ed521fd14a4cb3ac5bcf69610a8b30fc44facb0/input/ipc.c#L129
**I did not compile nor test this change.**
---
My use-case:
I want to decode the JSON data that is embedded in the Youtube website. This worked until a few days ago. But now the JSON data got bigger (deeper nested/JSON tree has more levels) and the current value 32 is not enough. I tested it with a few Youtube videos and it seems 36 would be enough for my use-case as well. [Related issue in my lua …
=> lua: script_parse_json increase max_depth to 50

player/configfiles.c, player/core.h, player/loadfile.c
Currently, mpv immediately deletes the watch_later file after an attempt at playing the file is made. This is not really ideal because the file may fail to load for a variety of reasons (including not even existing), but the state is cleared anyway unconditionally. Instead, just wait until after playback is successfully initialized before deleting it. This way silly mistakes like forgetting to mount the drive doesn't result in deleting your watch_later data. Fixes #3427.
=> player: delete watch_later file after successful load

generated/wayland/meson.build, video/out/wayland_common.c, video/out/wayland_common.h, wscript, wscript_build.py
This protocol no longer requires us to draw a separate cursor surface and all of that horrible stuff. We can just ask the compositor for the default cursor instead since that's literally all mpv cares about.
Should theoretically fix #11671.
Tested with https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4106 + https://github.com/swaywm/sway/pull/7571. Also requires wayland-protocols from master right now hence draft.
=> wayland: add cursor-shape-v1 support

video/out/wayland_common.c
mpv already guesses when the window is hidden so plugging in a proper event that actually tells us this is really trivial. Note that there's some redundancy with setting wl->hidden in a few spots, but nothing can really be done about that as long as the crappy hack is still in place.
Requires https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/201 to actually be useful and not actually tested.
=> wayland: add support for suspended toplevel

video/out/wayland_common.c
Fixes crash on compositors with xdg_toplevel version >= 5
Fixes #11907
=> wayland: add xdg_toplevel.wm_capabilities handler

DOCS/man/stats.rst, player/lua/stats.lua
This replaces deprecated `sans` with `sans-serif` in the `stats.lua`.
Also updates documentation with correct default values.
Fixes such warnings on platforms without `sans` aliases (e.g. macOS and probably Windows):
```
[osd/libass] fontselect: Using default font family: (sans, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
[osd/libass] fontselect: Using default font family: (sans, 700, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica-Bold
```
`fontconfig` maps `sans` to `sans-serif`:
https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/main/fonts.conf.in#L57-67
=> stats.lua: set sans-serif as default font

wscript_build.py
The patch that added these protocols (#11701) didn't include them in the list of sources, which caused build failure with wayland-protocols 1.32.
=> wayland: add 1.32 protocols to sources

DOCS/man/vo.rst, sub/draw_bmp.c, video/out/vo_dmabuf_wayland.c, video/out/wayland_common.c, video/out/wayland_common.h
Fixes #10342 and supersedes #10322.
Draft right now for two reasons.
vo_vaapi, where the drawing osd bits of this code are lifted from, actually crashes right now on master with ASAN as soon as you try to resize it with the mouse. I just think there's something fundamentally wrong with the code in this area (without d1d2370d073e9b70a181696e57075545b4802517 and e97819f88e451623a397b79d101497205fe849f9 it just crashed instantly in mark_rect instead so those didn't cause a regression; they help). I'll try to look into it.
=> vo_dmabuf_wayland: add osd support

player/loadfile.c
6a365b258a broke deleting redirect entries for resuming playback. If you do mpv dir1 dir2, quit-watch-later on a file in dir1, then later quit-watch-later on a file in dir2, mpv dir1 dir2 would not resume from dir2 because the redirect entry for dir1 is never deleted.
Fix this by deleting watch later config files for directory/playlist entries,
=> player: delete watch later redirect entries again

DOCS/man/options.rst, etc/input.conf, video/decode/vd_lavc.c
Today, if hwdec initialisation succeeds, we move on to attempting
decoding, and if decoding fails, we enter a fallback path that will
only do software decoding.
This is suboptimal because some hwdecs and codec combinations can
pass hwdec init, but then fail at hwaccel init, or even frame decoding.
In these situations, we will never attempt other hwdecs in the `auto`
or manually specified lists which might work.
One good example is someone tries to use `vulkan,auto` and tries to
play av1 content. The vulkan decoding will fail at hwaccel init time,
and then fallback to software instead of going through the auto list
which would allow vaapi, nvdec, etc to play the file.
Instead, let's not give up immediately, and try the next hwdec after
a failure, just like we do if hwdec init fails.
The …
=> vd_lavc: try other hwdecs when falling back after an hwdec failure 

DOCS/man/mpv.rst, osdep/path-win.c
First, someone please make sure this actually works since I didn't test it at all. This implements separate cache directories in windows. It's meant to be `%LOCALAPPDATA%`. It seems like everyone agrees on that one at least. For the portable_config path, it should be a separate subdirectory within it called `cache`. Dunno how people feel about that. Feel free to complain. Fixes #11898.
=> path-win: implement cache directories

DOCS/man/mpv.rst, osdep/path-darwin.c
Since shader/icc caches are enabled by default now `~/.config/mpv` may contain a lot of cache files on macOS. Most likely, users want to have only configuration files here so change default cache path to macOS specific directory.
=> player: set default cache dir on macOS

sub/sd_ass.c
We internally convert SRT to ASS and render them with libass, however as of libass 0.17.0, the text shadows and borders scale in the x-axis, while they previously did not. This means naively setting PlayRes{X,Y} to be 4:3 will result in stretched shadows and borders in the x-axis. Fix this by setting PlayResX = (PlayResY * DAR).
Fixes #11825
=> sd_ass: fix converted subtitles having too-wide borders

player/loadfile.c
This fixes a build warning about missing prototypes
=> loadfile: make get_audio_lang function static

DOCS/interface-changes.rst, DOCS/man/options.rst, video/out/gpu/video.c, video/out/gpu/video.h, video/out/vo_gpu_next.c
For better control over target display levels.
=> vo_gpu_next: add --target-contrast option

video/out/wayland_common.c, video/out/wayland_common.h
I don't know why we've been doing this wrong for so long or how I didn't notice until now. Wayland specifically has an event for handling modifiers. We even named it "keyboard_handle_modifiers" in the code. What we should so is just get the modifier and save it after the xkb state is updated. Then later if the user does something else (press another key or clicks the mouse button), the saved modifier key is applied. If you let go of the modifier at any point, the xkb will just update its state again and we save a 0 again here (i.e. no modifier). This solves bizarre issues with modifiers not working with some keys (don't ask me why though) and is clearly more correct. Fixes #10286 and fixes #11945.
=> wayland: handle modifier keys correctly

etc/builtin.conf
The `auto` behavior doesn't really make sense in these contexts.
=> builtin.conf: unset default languages in libmpv and encode profiles

player/lua/osc.lua
Currently, the osc will add a margin of (osc_height / 2) to the deadzonesize for the window controls, the topbar and the bottombar, i.e. when osc-deadzonesize=1, the osc will show up even if the cursor is only hovering (osc_height / 2) pixels above or below it. This is not what this option is supposed to do according to the manual, instead osc-deadzonesize=1 should result in the osc only appearing when it is directly hovered. The user can simply set osc-deadzonesize=0.9 or so if such a margin is desired, instead make the option work as advertised by removing this margin.
It should be noted that osc-layout=box does not share this behavior, and it already works as advertised in the manual.
=> osc: don't add margins to osc-deadzonesize

osdep/terminal-unix.c
fixes regression caused by 2e7fcc5a2 where it wouldn't receive terminal input if the process was foregrounded later on like this:
$ mpv something.mp4 &
$ fg
ref: https://github.com/mpv-player/mpv/issues/11795
- - -
Note: untested on macos. Someone on macos should test this to ensure that it doesn't reintroduce #11795 or cause some other weird issue.
=> terminal-unix: fix not listening on input after being foregrounded

audio/out/ao_pipewire.c
Instead of trying to guess the correct number in mpv let the pipewire server choose.
Fixes #9992
@sta-c0000 @AtticFinder65536 Could you check if this solves your issue?
=> ao_pipewire: use native buffersize by default

video/out/vo_vaapi.c
While use of vo_vaapi is discouraged, as long as it's still part of mpv it should at least work. This PR fixes a segfault in draw_osd and makes hardware decode interop work again.
=> A few vo_vaapi fixes

filters/f_decoder_wrapper.h, player/video.c, video/decode/vd_lavc.c
The first commit actually fixes `--vd-lavc-software-fallback=no` which amusingly will fallback to software decoding anyways on you. The second commit implements a mechanism in vo->driver to specify that no software decoding is allowed (i.e. for dmabuf-wayland).
=> vd_lavc: respect vd-lavc-software-fallback opt

audio/out/ao_pipewire.c
Doing a pw_thread_loop_wait() without checking conditions is invalid. The thread loop could be signalled for other reasons and in this case the wait needs to continue.
PipeWire added such additional signaling in
commit 33be898130f0 ("thread-loop: signal when started").
This meant that for_each_sink would return before the callbacks have fired and session_has_sink() would incorrectly return "false", failing the initialization of ao_pipewire.
Fixes #11995
=> ao_pipewire: for_each_sink: properly check termination condition

meson.build, video/out/vo_gpu_next.c
tested with libplacebo 5.264.1-1 (Arch)
the idea is to revert the revert (reapply the original commit) after release
=> Revert "vo_gpu_next: use pl_dispatch_info_move to avoid useless data copy"

meson.build, video/out/gpu/context.c
This has always been a pet peeve of mine and in fact I named the option in meson "egl-wayland" with the intention of finally doing this. We call everything that's egl "egl" internally except for wayland.
=> build: internally rename gl-wayland to egl-wayland

meson.build, meson_options.txt
Noticed this when I was playing with compiling mpv without GL (-Dgl=disabled). vaapi-drm and vaapi-wayland work just fine with vulkan/libplacebo, they don't need egl.
=> some vaapi build changes

common/msg.c
mpv has a historical convention where it actually always prints stuff to stdout. When doing encoding mode and outputing it to stdout, there's logic during startup force all the output to stderr instead so it doesn't mess up the encode. This is well and good, but mpv can put messages into stdout before mp_msg_force_stderr is run (like parsing a config file and finding errors). That puts junk data in the encode and screws up the output. Fix it by simply running an fseek in mp_msg_force_stderr to mark that as the start of the stream. That function is only ever called by encode mode anyways.
Supersedes #9302 (see some discussion there).
=> msg: print MSGL_WARN and higher error messages to stderr

osdep/language-posix.c
If we see "C" in one of the language vars we check, don't treat it as a language tag. Once we've checked everything, if we don't have any languages, but saw "C" anywhere, fall back on "en".
=> language-posix: as a fallback, treat "C" as "en"

meson.build, meson_options.txt
I noticed that my -Dwayland=disable build would still link to libva-wayland, this PR fixes that. There's also another drm_egl->drm change that I missed in my previous PR.
=> more vaapi build changes

meson.build
Curiously, vaapi requiring libdl has always existed ever since support was added to mpv (2827295703c74e3c119df9a435aa856e268c2ea9). After some investigation in IRC from uau and JEEB, it was concluded that the libdl requirement was blindly copied from the vdpau check above it. At the time, the vdpau code actually used dlsym so it was needed. The check was later dropped when waf support was added
(7e2edad8efea55e8df1faa695d1389ef4e326d7c). However, the requirement in vaapi lived on, and actually it was never needed. libva does use dl when building its libraries unsurprisingly, but this isn't relevant to mpv in any way. Just drop it.
=> build: remove unneeded libdl requirement for vaapi

player/video.c
The track during lavfi-complex can actually be NULL which meant that ca4192e2df7bcfdb9e18461f19e1bd2dd0ee3c7a regressed lavfi-complex by causing mpv to crash during runtime changes of the filter. Additionally, it's possible for the decoder wrapper to also be NULL. check_framedrop within write_video checks this, but check_for_hwdec_fallback does not. Perhaps, it's impossible for this to happen, but we might as well add the check here to be on the safe side since mp_decoder_wrapper_control is not designed to handle a NULL.
=> player/video: check for track and decoder existence

.github/workflows/build.yml, ci/build-msys2.sh
Python 3.11 will be released soon as default Python package, and actually python3.11 package already disappeared from the repository.
This reverts commit c637beb5223b0af5a671c8829a0e1a42e7e9a411.
=> Revert "ci/msys2: double down on running meson through python3.11"

DOCS/interface-changes.rst, DOCS/man/options.rst, options/options.c
1669c4698d237eb885aa3f9c5b81983de6009418 notably flipped the default of --subs-with-matching-audio from yes to no as part of a series of changes that gave more control over sub selection behavior. While the increased amount of options is definitely nice, changing the default to no results in very unintuitive behavior. For example, setting alang=en and slang=en in your config will not show any subtitles since the audio stream is English as well so --subs-with-matching-audio being no causes the subs to not be be selected. This is very weird for users who reasonably expect slang being set to actually result in showing subs and this is what mpv did for the past decade.
The other case is when a subtitle does not have a language tag but is flagged as default. Because --subs-fallback (a new …
=> options: restore old default sub selection behavior

version.py
- Use ctime() instead manual format string. Fixes 12-hour format (%I) without AM/PM (%p) specified. It is 24-hours now, as it should be.
- Avoid naive datetime object.
- Fix timestamp type, it is float in Python.
- Remove dummy fallback branch.
- Use f-strings for readability.
- Always rebuild version.h is repository is dirty.
RFC: I actually was thinking about changing the format to `date -u --rfc-email` -> `Sat, 29 Jul 2023 09:19:20 +0000` and probably without tz, so `Sat, 29 Jul 2023 09:19:20`, I find it more readable than ctime... but you will likely not agree, so I didn't include this change.
RFC2: Build time has limited usefulness in the binary. And causes only troubles with build reproducibility and so on. We could just remove it...
=> version.py: fix build date

audio/out/ao.h, audio/out/ao_pipewire.c, player/audio.c, player/command.c, player/core.h
The dynamic approach is racy.
For more details see the commit messages.
Potential successor: #11253
Fixes: #12041
=> ao_pipewire: revert media role handling

sub/draw_bmp.c, video/out/vo_dmabuf_wayland.c, video/out/vo_vaapi.c
This is yet another unfortunate side effect of the width % SLICE_W == 0 special case. While looping through these rectangles, the rc->x1 value on the final loop can be greater than the actual total width. This will cause a buffer overflow if using the mp_draw_sub_overlay API. 2 of the current VOs that use that work around it by adjusting the values returned, but the better fix is to correct what's actually given in the rectangles so you can safely use the values. As for the fix, it's simply ensuring that rc->x1 doesn't extend beyond p->w with a MPMIN. Previously, the code would always naively add SLICE_W (256) to rc->x0 which would easily extend past the actual width in many cases. The adjustments in vo_vaapi and vo_dmabuf_wayland are dropped and in theory vo_direct3d should work now …
=> draw_bmp: fix overflowing coordinates in mark_rcs

audio/out/ao_sndio.c, meson.build
Use sio_flush() instead of sio_stop() to improve controls responsiveness.
=> ao_sndio: use sio_flush() to improve controls responsiveness

audio/out/ao.h, audio/out/ao_pipewire.c, player/audio.c
wireplumber uses the media role when the node is first created.
To have the property available at this point reliably we need to set it
directly when creating the stream/node.
Cc @philipl
=> ao_pipewire: set media role during init()

meson.build, video/out/drm_common.c
Debian 12 is out, with 2.4.114, and Ubuntu 22.04 has 2.4.110, this
#ifdef is no longer needed
=> drm: bump minimum version to 2.4.105

test/libmpv_test.c, test/meson.build
Get rid of the time during the while loop and just let this run forever in case of a failure and also bump the timeout in meson to 60 seconds since we know it is possible for msys to take a very long time on occasion. That should be plenty of time for it to finish.
=> test: bump libmpv test timeout

video/out/gpu/video.c, video/out/vo_gpu_next.c
The first commit fixes #12031. The second commit implements the behavior suggested [here](https://github.com/mpv-player/mpv/issues/12031#issuecomment-1657004574). That is, cscale will use the value of scale if it is unset.
=> vo_gpu/vo_gpu_next: scaler fixes

DOCS/man/options.rst
Commit 45e95311b83560d6e716f6cbc9fc8506f828c4cc added `hdr-peak-percentile` to the docs, but the mention of `-vo=gpu-next` was missing a second `, causing a warning message to be displayed.
=> DOCS/options: fix typo in hdr-peak-percentile

video/decode/vd_lavc.c
In the same way that fallback in receive_frame() needs to be repeated until we get a working decoder, we have to do the same thing in reinit(). Calling force_fallback() only once can still yield a non functional decoder.
The reason why we have these multiple paths which each require their own fallback logic is that we can fail at different stages:
* hwdec init
* decoder init <- repeated fallback was missing here
* frame decoding
Fixes #12084
=> vd_lavc: repeatedly attempt to fallback if hwdec fails in reinit

options/m_option.c
Fixes wrong time parsing when the value starts with "-".
**Reproduction steps:**
file length: `00:10:00`
- `mpv --start=-02:30 --pause <file>`  
expected position: `00:07:30`  
actual position: `00:08:30`
- `mpv --start=-00:02:30 --pause <file>`  
expected position: `00:07:30`  
actual position: `00:02:30`
=> options: fix relative time parsing

test/meson.build
Found out with a CI image where FFmpeg is not located in the default sysroot.
=> test/meson: add missing avutil dependency to chmap test

video/out/w32_common.c
The win32 code already updates itself on dpi changes. However, it never signalled mpv's core when this happened which meant that the display-hidpi-scale property never changed. Simply send the VO_EVENT_DPI event when appropriate. Fixes #12081.
=> win32: signal VO_EVENT_DPI on dpi changes

video/mp_image.c
ffmpeg does not tag yuv levels if no metadata is available, but for some pixel formats it should be implicitly infered as full range. Instead of defaulting to limited range always. Fixes (M)JPEG playback.
This mimic ffmpeg's behaviour.
See: https://github.com/FFmpeg/FFmpeg/blob/d295b6b6936c9c691a4871851fdaec04d407e54b/libswscale/utils.c#L926-L962
Fixes: #12089
=> mp_image: properly infer color levels for some pixfmts

DOCS/interface-changes.rst, audio/out/ao_audiotrack.c
useful to generate some sample files:
```bash
for rate in 22050 44100 48000 96000; do
ffmpeg -f lavfi -i aevalsrc="sin(440*2*PI*t):s=$rate:d=5" -c:a pcm_s16le -y s16_$rate.wav
done
for rate in 22050 44100 48000 96000; do
ffmpeg -f lavfi -i aevalsrc="sin(440*2*PI*t):s=$rate:d=5" -c:a pcm_f32le -y float_$rate.mka
done
for chan in quad 5.1 7.1; do
ffmpeg -f lavfi -i aevalsrc="sin(440*2*PI*t):c=$chan:d=5" -c:a libvorbis -y layout_$chan.mka
done
```
=> ao_audiotrack features & fixes

filters/f_decoder_wrapper.c, options/m_option.c, options/m_option.h
This specific option type is only used for the video aspect. The underlying type was a float to represent the inputted value, but it's actually not precise enough. When using something like 4:3, the values of the incorrect digits are actually significant enough to make av_d2q return a very funky numerator and denominator which is close to 4/3 but not quite. This leads to some "off by one pixel" errors. Weirdly, mpv's actual calculations for this were already being done as double, but then converted to floats for this specific type. Just drop the conversion step and leave it all as double which has the precision we need (i.e. AVRational is now 4/3 for the this case). Fixes #8190.
=> m_option: change m_option_type_aspect to double

player/command.c
1df0a42a8cb12005311f6a03f3a1c4329c798f8c changed aspect-ratio from floats to doubles, but forgot to change this function for pretty-printing them as fractions for the video-aspect-override property
=> command: fix stack smashing when displaying aspect-ratio

DOCS/man/options.rst, player/lua/ytdl_hook.lua
Fix the issue where when the given path(s) for yt-dlp/youtube-dl already have ".exe" in it (Like `--script-opts=ytdl_hook-ytdl_path=D:\yt-dlp.exe`), the search for the exe of yt-dlp will fail due to redundant .exe suffix.
Keep in mind since the Lua script will try the original `path` even if the search failed:
https://github.com/mpv-player/mpv/blob/983e8f0100b98bd8aed48e5fe86dd5682174b04e/player/lua/ytdl_hook.lua#L846-L848
So this is more about a minor issue that it causes MPV to print lots of errors in verbose:
```
[ytdl_hook] Video disabled. Only using audio
[global] config path: 'D:\yt-dlp.exe.exe' -/-> 'D:\yt-dlp.exe.exe'
[global] config path: 'D:\yt-dlp.exe.exe' -/-> 'D:\yt-dlp.exe.exe'
[global] config path: 'D:\yt-dlp.exe.exe' -/-> 'D:\yt-dlp.exe.exe'
[ytdl_hook] No youtube-dl found …
```
=> ytdl_hook: fix Windows exe search with suffix

demux/demux_playlist.c
Discovered by @christoph-heinrich in IRC.
09c701b797c44293dc0e22874b4acf0246b3d148 added a fallback for headerless m3u files. However, it requires that the bstr len be greater than 10. This means that a m3u playlist with a single entry with a very short filename (such as "test.flac") will not be recognized as a playlist since the amount of data is too small. The reason for this restriction is unexplained and really shouldn't matter given that the important thing mpv should be doing is checking if the data is text. Just loosen the check to pass as long as the len is greater than 0.
=> demux_playlist: remove len restriction on headerless m3u

video/out/w32_common.c
It was actually always wrong, and no one ever noticed. This currently returns the size of the entire display area and not one actual monitor. Fix this by calling get_monitor_info and then doing the appropriate subtractions. Checked by @CrendKing and fixes #12172.
=> win32: fix display resolution calculation on mulitple monitors

video/out/vo.c
I did some digging and vsync_offset being negative is completely normal and happens during typical playback too. It's just the error being the other way around (too early vs too late). So I think the simplest fix is probably to just make vsync_offset 0 if we're paused and trying to render a frame.
cc @haasn
=> vo: clear vsync_offset if drawing while paused

meson.build
At least NetBSD ossaudio(3) right now has SNDCTL_DSP_SETPLAYVOL support but does not support SNDCTL_DSP_HALT chocking at build time.
NFCI on platforms where oss audio output is supported.
=> build: check for SNDCTL_DSP_HALT for oss-audio

player/core.h, player/loadfile.c
A playlist with the first entry referring to itself will cause mpv to loop forever trying to open it. Obviously there's no reason to ever actually do this, but we can gracefully error out in this case since it's simple to detect. ~~Note that doing a ping-pong loop with something like m3u files referring to each other will still "work" (i.e. loop forever). There's nothing we can really do about that so the solution is still "don't do that".~~ Fixes #3967.
Edit: Now should work for any self referential playlist.
=> loadfile: avoid infinite playlist loading loops

DOCS/man/options.rst, video/out/gpu/video.c, video/out/gpu/video_shaders.c
This completely disables all smoothing. Despite what the manual claims, a decay rate of 1.0 does *not*.
It's worth pointing out that this depends on the following commit to work properly in --vo=gpu-next, but I don't think working around such a minor detail is worth the trouble, considering people building nightly mpv are probably also building nightly libplacebo it should just work (tm).
See-Also: https://github.com/haasn/libplacebo/commit/1c464baaf4c6228dcfac87f19db1dafc22e328c8
See-Also: https://github.com/haasn/libplacebo/commit/83af2d4ebd5086a56f7b1a2f86628ada3612ee7c
=> vo_gpu: allow --hdr-peak-decay-rate=0.0

.github/workflows/build.yml, ci/build-mingw64.sh, ci/build-msys2.sh, meson.build, meson_options.txt, video/out/hwdec/hwdec_cuda_vk.c, video/out/placebo/ra_pl.c, video/out/placebo/utils.c, video/out/vo.c, video/out/vo_gpu_next.c
Also includes the new HDR contrast recovery option. I included it by default in the `gpu-hq` profile.
Question: Should we "downgrade" HDR peak detection from on-by-default to on-in-gpu-hq as well? It's really punishing for slower devices, even after libplacebo v6's optimizations.
=> libplacebo v6 updates

DOCS/interface-changes.rst, DOCS/man/options.rst, video/out/vo_gpu_next.c
Some fun things to try:
* configuring custom scaler kernels (`upscaler=custom` + configuring kernel/window and params manually)
* `--libplacebo-opts=temperature=-0.3`: adapt to D55 for nighttime viewing
* `--libplacebo-opts=tone_map_metadata=cie_y`: force use of DV/peak detection (CIE Y) metadata, ignoring HDR10(+)
* `--libplacebo-opts=cone=on,cone_preset=deuteranomaly`: color blindness simulation
* `--libplacebo-opts=distort=on,distort_bicubic=yes,distort_shear_x=1,distort_shear_y=-1,distort_alpha_mode=independent,distort_constrain=true`: rotate image by by 45°
* `--libplacebo-opts=preset=high_quality`: override all settings to their libplacebo "high quality" presets, ignoring mpv settings
=> Update to new libplacebo options system and add `--libplacebo-opts`

sub/sd_lavc.c
02a80f850b5403da89fefed7b32b3f3dfb82f647 isn't a good fix and I found instances where subs lingered far too long on the screen. So instead, I tried to use `SUB_GAP_THRESHOLD` which seems to do the trick.
=> try fixing sd_lavc stuff again.

video/out/opengl/context_drm_egl.c
If we failed to create a gbm surface, we would call drm_egl_uninit to free up any state we had allocated. However, we would segfault if we tried to cleanup properties there were never initialized. Null checks have been added to guard against this.
=> context_drm_egl: don't free egl properties if they are null

meson.build, video/out/x11_common.c, video/out/x11_common.h
Three things:
1. Hard require at least randr 1.4 because it's literally over a decade old and we use some parts of that.
2. Completely remove legacy xinerama and only use randr instead (refactor part).
3. Set the sizehint for the `--fs-screen` and `--fs-sceen-name` options because otherwise it won't even fullscreen on the right display initially (tested on plasma x11).
=> x11: geometry refactor

audio/out/ao_oss.c
In addition to the patch, appropriate additions to the mpv.conf file
will of course be needed for this to work. For example on my system:
audio-device=oss//dev/dsp4
audio-spdif=ac3,dts,dts-hd,eac3,truehd
This has been tested using recent FreeBSD-13.1-stable, using external
surround processors (both a Trinnov Altitude 16 and an LG OLED that supports Dolby Atmos, and connected with HDMI to an NVidia RTX 2070).
Author and tester: David G Lawrence <dg1007@dglawrence.com>
=> ao_oss: add "spdif" passthrough support for high bitrate codecs (e.g Dolby Atmos, DTS-HD, etc.) over HDMI

video/out/w32_common.c
Currently on Windows, mpv is taking focus when launched with `--window-minimized=yes`.  This commit stops Windows from focusing the minimized window, which is consistent with what happens when the window is manually minimized.
Resolves: #9641
=> w32_common: fixes minimized window being focused on launch

audio/out/ao_jack.c
This change sets the device_buffer member of the ao struct for the JACK ao to whatever value we read during init.
While JACK allows changing the audio buffer size on-the-fly (you can do this for example through DBus), having it somehow reconfigure the entire audio buffer logic of mpv that depends on device_buffer in some way when that happens only leads to audio dropout and weird code. device_buffer's role is mostly for prebuffer from what I understand, which means that simply setting it to its current value in the init function is fine.
=> ao/jack: set device_buffer to JACK buffer size

audio/out/ao_pulse.c
The idea behind period_size is that it's the minimum amount of data that your audio subsystem wants to fetch.
For PulseAudio, this is given by the minreq buffer attribute, which is in bytes for all channels. Hence the divisions.
=> ao/pulse: implement period_size

video/out/w32_common.c
Currently the `--geometry` parameter is constrained by the size of the primary monitor even if the position of the window is located on another monitor. This PR attempts to fix this in two ways:
1. Don't constrain the window size if `VO_WIN_FORCE_POS` is set, this is set when either `--geometry` or `--force-window-pos` is used.
2. Fix the root cause issue by fetching the monitor based on the cached window bounds when the window is not yet visible.
=> w32_common: fix --geometry parameter being constrainted to the incorrect monitor

sub/osd.c
We should update the osd when the window is resized, previously we weren't signalling for an update.
Fixes #12228
=> sub/osd: signal osd_changed on resize

player/playloop.c
See each individual commit for more information.
To reproduce each bug, get the sample file from the linked issue and run the following commands.
`mpv --no-config 02\ Kevin\ Penkin\ -\ Old\ Stories.flac --force-window --keep-open --start=421`
When mpv reaches EOF, the time-remaining property will be negative 0. After the first commit in this PR, the time-remaining property will be zero when mpv seeks to EOF while paused. 
However, time-remaining will still be negative 0 when mpv reaches EOF while playing through the audio. This is fixed by clamping to length.
Another issue is that time-pos being a negative number when gapless audio is enabled (default), and mpv is looping the same file. This can be reproduced with this:
`mpv --no-config 02\ Kevin\ Penkin\ -\ Old\ Stories.flac …
=> player: use audio pts corresponding to playing audio on EOF 

DOCS/interface-changes.rst, DOCS/man/options.rst, options/m_option.h, options/options.c, options/options.h, player/command.c, player/external_files.c, player/external_files.h
--audio-file-auto, --cover-art-auto, and --sub-auto all work by using an internally hardcoded list that determine what file extensions get recognized. This is fine and people periodically update it, but we can actually expose this as a stringlist option instead. This way users can add or remove any file extension for any type. For the most part, this is pretty pretty easy and involves making sub_exts, etc. the defaults for the new options (--audio-file-auto-exts, --cover-art-auto-exts, and --sub-auto-exts). There's actually one slight complication however. The input code uses mp_might_be_subtitle_file which guesses if the file drag and dropped file is a subtitle. The input ctx has no access to mpctx so we have to be clever here.
For this, the trick is to recognize that we can leverage the …
=> player: make all autoload extensions configurable

filters/f_autoconvert.c, filters/f_hwtransfer.c, filters/f_hwtransfer.h, filters/f_output_chain.c, video/hwdec.h, video/out/hwdec/dmabuf_interop_wl.c, video/out/hwdec/hwdec_vaapi.c
Historically, we have not attempted to support hw->hw format conversion in the autoconvert logic. If a user needed to do these kinds of conversions, they needed to manually insert the hw format's scale filter manually (eg: scale_vaapi).
This was usually fine because the general rule is that any format supported by the hardware can be used as well as any other. ie: You would only need to do conversion if you have a specific goal in mind.
However, we now have two situations where we can find ourselves with a hardware format being produced by a decoder that cannot be accepted by a VO via hwdec-interop:
* dmabuf-wayland can only accept formats that the Wayland compositor accepts. In the case of GNOME, it can only accept a handful of RGB formats.
* When decoding via VAAPI on Intel hardware, …
=> hwtransfer: implement support for hw->hw format conversion

DOCS/man/input.rst, player/command.c, sub/dec_sub.c, sub/dec_sub.h
Added so I can do what #12157 does through a lua script (with sub-ass-force-style) instead, since it seems there isn't much interest in that PR.
I still prefer that PR for this but it seems mpv don't want too many hacks around libass
=> command: add `sub-ass-extradata` property

player/lua/osc.lua
See commit messages.
[Old - DVD/PGS subs](https://github.com/mpv-player/mpv/assets/6298234/eb6876d5-47cd-45ad-856e-8f192860b80b)
[Old - non DVD/PGS subs](https://github.com/mpv-player/mpv/assets/6298234/95a42811-b011-4043-83d0-d8bcfa69f771)
[New - DVD/PGS subs](https://github.com/mpv-player/mpv/assets/6298234/25478222-637a-43dd-b868-20760037b358)
[New - non DVD/PGS subs](https://github.com/mpv-player/mpv/assets/6298234/22b7723f-0ca2-42cf-b87b-9a16333028cb)
=> osc: only add sub forced-only toggle to layout for DVD/PGS subs

DOCS/man/vf.rst, filters/f_lavfi.c
Ideally, users should be using lavfi-complex instead of lavfi-bridge for such a use case, however currently lavfi-complex doesn't support hwdec. So we can allow filters with dynamic inputs to work with lavfi-bridge, at the cost of them only being able to take in only one input. This should probably be reverted when/if lavfi-complex has hwdec, but for now this allows us to use libplacebo as a video filter with hwdec in mpv again.
Basically the same as #12170 but Github don't let you reopen PRs if you force pushed while it was closed...
I've made the code changes requested by @kasper93, and also added a note about --vf limitations in the docs. I'm not particularly sold on the idea of allowing filters with dynamic in/out in lavfi-bridge, but there are certainly limitations with lavfi-complex …
=> f_lavfi: don't reject dynamic lavfi ins/outs (v2)

video/out/vo_dmabuf_wayland.c
Attaching a NULL buffer unmaps the surface, allowing compositors to skip blending the empty buffer.
Closes #12236
=> vo_dmabuf_wayland: unmap osd surface when not needed

common/playlist.c, common/playlist.h, options/path.c, options/path.h, player/configfiles.c, player/loadfile.c
35f43dfacbe added a system to write resume files for redirects, i.e. directories and playlists that mpv expands.
It creates a resume file for each redirect, and for the first redirect only, it writes a resume file for each segment of its path, without even converting it to an absolute path if it's relative. This is incomplete and overcomplicated and it's strange that wm4 went for it:
`mpv 'Iron Maiden/1982 The Number of the Beast/8 Hallowed Be Thy Name.mp3'`
This doesn't save any redirect entry.
`mpv --directory-mode=recursive 'Iron Maiden'`, then quit-watch-later on Hallowed Be Thy Name
This saves a redirect entry for "Iron Maiden", but not for "1982 The Number of the Beast". It doesn't save redirect entries for the directories above "Iron Maiden" either because "Iron Maiden" isn't …
=> player: always write redirect entries for resuming playback

DOCS/interface-changes.rst, DOCS/man/options.rst, options/options.c, options/options.h, player/loadfile.c
Unfortunately, the `auto` slang behavior still proved to be problematic in some instances. Essentially, it would be as if you set `slang` to the value of your OS language (if unset) which is not necessarily desirable and results in subs getting selected when they shouldn't. For example, with `--no-config` on `en_US.UTF-8` would basically behave like `--slang=en` and cause english subtitles to be selected even if it is not the default track. Flipping `--subs-with-matching-audio` to no again would simply cause the opposite problem where people that do set `slang` have subtitles not actually picked.
So instead, just divorce this concept from `--slang` all together because it doesn't really fit there (additionally, it removes it from `--alang` and `--vlang` as well but `auto` has no real use …
=> player: add --subs-match-os-language option

etc/input.conf
Wheel being seek by default is very unintuitive and surprising to a lot of users. It seems to be one of the things most consistently complained about in the default UI. I change this on all of my devices, and so do many others.
It's trivial for users who like the old behavior to change it back.
=> input.conf: swap wheel up/down with wheel left/right

DOCS/interface-changes.rst, DOCS/man/options.rst, demux/demux_playlist.c
64959c450d solved the problems with resuming playback, so default to --directory-mode=lazy because it's faster, especially on slow drives, and results in smaller playlists.
=> demux_playlist: default to --directory-mode=lazy

player/lua/osc.lua
DVD/PGS are definitely not common, and ones that make use of the forced subpictures flag even less so. For this button to be useful, the subtitle track would need to be DVD or PGS, the track would need to make use of the forced flag, the user would have to know what forced subpictures are, and the user would need to have the preference of only viewing forced subpictures on a subtitle. The function of this button is too niche to be on the osc, if this behavior is desired the user can simply bind a key in their input.conf. Moreover, this button only adds confusion because there's no intuitive way to show what it does, and there's no explanation for it anywhere in the manuals. osc real-estate is quite limited as it is, so let's not waste any space on buttons with highly questionable utility …
=> osc: remove toggle for forced only subpictures

etc/builtin.conf
Prevents transient brightness spikes on scene transitions at the cost of sometimes forcing an extra indirect pass (in particular, when downscaling). But on GPUs powerful enough to run gpu-hq, the extra indirect pass shouldn't matter too much. This option mostly exists for weak iGPUs.
=> builtin.conf: add --allow-delayed-peak-detect=no to gpu-hq

DOCS/interface-changes.rst, DOCS/man/options.rst, video/out/gpu/video.c, video/out/gpu/video.h, video/out/gpu/video_shaders.c
`--vo=gpu-next` no longer uses this option, being replaced entirely by a luminance-based approach internally. And even for `--vo=gpu`, the values other than 'hybrid' are universally inferior in quality.
In the interest of gradually reducing the amount of option bloat here, remove this mostly-pointless option.
=> vo_gpu: remove --tone-mapping-mode

ci/lint-commit-msg.py
The default revert will always add 9 extra characters which means it could go over the 72 character soft limit if the commit being reverted has a long subject. We won't fuss about this so just shut up the lint in this case.
=> ci/lint: ignore message length for revert commits

DOCS/man/osc.rst, player/lua/osc.lua
the osc currently allows for changing volume via scrolling when on top of the volume icon. this does the same thing for the seekbar by allowing seeking via scroll.
=> osc: add scrolling to the seekbar

etc/_mpv.zsh, etc/mpv.bash-completion
Avoids tab completion parsing the mpv.conf file. Fixes printing warnings when pressing tab if `mpv.conf` contains errors, for example. Also avoids spending unnecessary time reading from disk and potentially loading profiles, user scripts etc.
=> zsh-completion: use --no-config

DOCS/man/options.rst, stream/dvb_tune.c, stream/dvbin.h, stream/stream_dvb.c
This adds support for the ISDB-T delivery system (used e.g. in Brazil, Japan), and contains some related DVB fixes:
* Detection and treatment of ISDBT channel config files created by `dvbv5-scan` which look like VDR style config files. 
* Fixes an issue potentially loosing track of a channel list / adapter combination if an adapter supports many delivery systems. 
* A few helpful verbose output messages in case issues pop up in the channel parsing code. 
* Related documentation pieces. 
ISDBT tuning has been tested by @fvp in #12218 (he has the appropriate hardware and reception), and I have tested common existing delivery systems with channel configs are not broken (DVB-S/S2, DVB-T/T2). Thanks for the testing! 
closes #12218
=> stream/dvbin: add support for delivery system ISDB-T 

etc/_mpv.zsh, etc/mpv.bash-completion
We were over-enthusiastic when introducing --no-config into the autocompletions. When autocompleting profiles, you actually need the config, because that's where the profiles come from.
zsh is untested - I don't use it.
=> {zsh,bash}-completion: use config when autocompleting profiles

DOCS/man/options.rst, meson.build, misc/uuid.c, misc/uuid.h, video/out/vulkan/context.c
We currently only allow specifying the Vulkan device to use by name. We
did this to avoid confusion around devices being enumerated in an
unpredictable order. However, there is a valid edge case where a system
may contain multiple devices of the same type - which means they will
have the same name, and so you can't control which one is used.
This change implements picking devices by UUID so that if names don't
work, you have some option available. As Vulkan 1.1 is a hard
requirement for libplacebo, we can just use UUIDs without conditional
checks.
Fixes #10898
=> vo: vulkan: allow picking devices by UUID

osdep/path-darwin.c, osdep/path-unix.c
mpv saves cache by default nowadays, but vo_gpu is pretty spammy and saves a bunch of files per shader. If someone is using the non-XDG config directory, this all gets dumped directly into ~/.mpv which isn't so nice. Save it to a sub directory called "cache" instead (or alternatively submit to your XDG overlords). For unfortunate reasons, macOS uses XDG_CONFIG_HOME and has the same legacy fallback mechanism, so this applies to it too.
=> path-{darwin,unix}: save cache to subdir when using non-XDG path

DOCS/man/options.rst, TOOLS/lua/autocrop.lua, options/m_option.c, options/m_option.h, player/command.c, player/lua/stats.lua, player/video.c, video/decode/vd_lavc.c, video/mp_image.c
This makes it easier to apply crops without need to manually calc the offset. I wanted for it to be top-left corner based, but maybe it was not that good idea in retrospect.
Also rename scrw/scrh, since they don't refer to screen. It was copied form m_geometry apply.
=> m_option: make m_rect_apply center based

video/out/vo_gpu_next.c
Interrim solution, forwards compatible with new and backwards compatible with old API. Eventually, we will want to discontinue the use of deprecated pl_icc_params.save/load and pl_renderer_save/load, but that requires minimum version bump.
=> vo_gpu_next: forwards compatibility with pl_cache

sub/sd_lavc.c
Timestamps are converted from microsecond resolution timestamp, we don't have more precision, so we have to account for that when comparing the floating point values as them will slightly be off.
Fixes: #12327
=> sd_lavc: account for floating point inaccuracy

video/out/vo.c, video/out/vo.h
So strangely enough, estimated_vsync_interval is stored as a double but nominal_vsync_interval is not and neither is the vsync_interval. Those are stored as int64_t. This loss of precision can matter even in common cases. For instance, take a typical 60 Hz monitor. Instead of 16666.6666 (repeating) being calculated as the vsync interval, you'll get 16666 since the decimals are truncated. This is not really good at all and affects the calculated speed values you get when using display sync. For consistency and better precision, these should all be doubles just like estimated_vsync_interval. Technically this means that we won't be able to store as high of an integer value but such values would be absurdly huge and never actually needed. Also estimated_vsync_interval already can't handle …
=> vo: change vsync_interval to double

DOCS/interface-changes.rst, DOCS/man/options.rst, player/loadfile.c
In the never ending quest of trying to satisfy every possible user request for subtitle autoselection, I ended up redoing how --subs-fallback-forced works. The old behavior had it as strictly a fallback-type option when there were no lang matches, but now we can make it an active part of compare_track and it works along with slang to select the desired track. Since it's a three state option, the no option still works to avoid selecting any forced subtitle tracks. The meaning of always slightly changes to mean "only select forced subtitle tracks" and yes remains essentially the same (no special priority given besides the audio matching subtitle language case).
So instead of making yet another option, I opted to change `subs-fallback-forced` instead because it's significantly saner and also …
=> player: redo --subs-fallback-forced

DOCS/man/options.rst, video/decode/vd_lavc.c
While this resolves limitations of lavc decoder crop, it also introduces artifacts with some of the source files or hwdec.
Depending on chroma sampler it is possible to sample outside the decoder crop area, pulling dirty pixels into the image. Some decoders left them zeroed, not black. To fix that we would need specifc solution during mapping of avframes.
As most of the files require the crop only in bottom/right area, the AVCodecContext::apply_cropping works ok for those.
For all other cases that require more fancy cropping like 1440x1080+240+0 user can manually set `--vd-apply-cropping=no`.
Limitations of the lavc crop are explained here:
https://ffmpeg.org/doxygen/trunk/structAVCodecContext.html#a4745c7455c317272c4e139d6f369936c
Fixes: 826ce82cad315f7a48f9c971d3a5fa005a9eab46
=> vd_lavc: by default enable cropping by decoder

DOCS/man/options.rst
Adds `catmull_rom` as an example for `--scale` in the user manual, alongside a brief description of the filter.
`catmull_rom` was only exposed to users as an available filter through `--scale=help`. However, `catmull_rom` is very often aliased as "Bicubic" in other applications such as GIMP and VapourSynth, and is a relatively popular resizing filter. The documentation lacked any description of `catmull_rom`, outside of a brief mention of it in the `--tscale` section.
=> DOCS/options: add catmull_rom as an example for --scale

stream/stream_lavf.c
Re-submit the pull request based on https://github.com/mpv-player/mpv/pull/11703.
https://github.com/mpv-player/mpv/issues/11080 has been submitted to mpv for handling webdav:// and webdavs:// links. However, the GNOME Nautilus file manager that I'm using does not support browsing of webdav:// and webdavs:// links.
The GNOME Nautilus file manager supports browsing of dav:// and davs:// links only. Additionally, dav:// and davs:// are also types of webdav links. Therefore, adding an "or" operation to include support for dav:// and davs:// links.
=> stream: accept dav:// and davs:// urls

meson.build
The new symbol "vkGetPhysicalDeviceProperties2" was recently added after refactoring context.c.
=> meson: check vulkan version

TOOLS/lua/autoload.lua
Adds support for adding directories to the playlist in addition to files.
The new option `directories` controls if directories get added.
Directories get sorted together with files to behave the same way mpv behaves when it loads directories directly.
=> TOOLS/lua/autoload: support directories

video/out/present_sync.c
The original OML sync implementation (which is where this calculation originally comes from) made now_monotonic and ust_mp_time unsigned. This is fine except it has the assumption that now_monotonic is always greater than ust. This actually isn't always the case. In wayland, I observed instances where the reported timestamp is in the future. Of course, it's a valid question to wonder if this even makes sense but these UST values are essentially opaque black boxes to us anyways. It's entirely plausible that the gpu is expecting the actual presentation of the last swap to be a bit in the future, the compositor gets this and reports this to us. So we'll consider such stats as valid. Note that xorg doesn't have this problem because it's roughly one swap buffer call behind because of how the …
=> present_sync: allow future timestamps

DOCS/interface-changes.rst, DOCS/man/options.rst, video/out/gpu/lcms.c, video/out/gpu/lcms.h, video/out/vo_gpu_next.c
Upstream has moved from passing struct pl_icc_profile to directly
attaching a managed pl_icc_object, plus providing a new function
pl_icc_update to update the ICC profile object parameters (if needed).
To facilitate this move, pull our ICC params back out of pl_options and
update the target ICC object directly.
=> vo_gpu_next: update for new ICC profile API

DOCS/man/osc.rst, player/lua/osc.lua
Consistent with other osc buttons now
Fixes #12377
=> osc: add scrolling to audio/sub buttons

video/out/w32_common.c
It is quite unnecessary to log every window move.
=> win32: remove noisy debug log

video/out/vo_gpu_next.c
This would always apply the config blur and taper values to the kernel, even if it was zero because the user didn't specify any.
Fixes #12415
=> vo_gpu_next: fix blur and taper values being zero

DOCS/interface-changes.rst, DOCS/man/options.rst, demux/cache.c
This is a horrible name that only causes confusion (e.g. see #12418). Maybe some other cache options should also be prepended with --demuxer for consistency, but this one is the only one that has an unintuitive meaning.
=> demux: prepend some cache options with demuxer

DOCS/interface-changes.rst, DOCS/man/options.rst, etc/builtin.conf, video/out/gpu/video.c, video/out/vo_gpu_next.c
It's confusing that the mid-quality option is in the gpu-hq profile, while the recommended filter is not. Also prefer the sharper catmull-rom for dscale, as it produces better results.
It's time to retire Spline36.
=> builtin.conf: modernize internal profiles

audio/filter/af_scaletempo2.c, audio/filter/af_scaletempo2_internals.c, audio/filter/af_scaletempo2_internals.h
Update: Apologies for how big this PR has gotten. It turns out there were a lot of unnoticed issues in scaletempo2, which are fixed here. There are detailed commit messages, but see my [comment](https://github.com/mpv-player/mpv/pull/12052#issuecomment-1685231794) for a summary.
Original text:
This is what I came up with to fix #12028. It calculates the scaletempo2 delay based on the current buffer positions.
My testing consisted of the process described in #12028. With normal settings, the audio seems fine both with the new code, and without delay calculation (by removing the pts adjustment altogether as described in the issue). I find it impossible to notice the differences _during_ speed changes in any case.
There was an additional issue that audio was always delayed by half the …
=> af_scaletempo2: fix audio-video de-sync caused by speed changes

player/playloop.c, video/mp_image.c, video/mp_image.h, video/out/vo_dmabuf_wayland.c, video/out/wayland_common.c
The osd support was originally written with the requirement that we have
actual frames getting delivered to the VO. This isn't always the case
though. If you force a window on a blank audio file for example, then
there will be no frame thus draw_frame did nothing. Since the previous
commit allows us to reliably detect this, we can rearrange the code
around a little bit to make this possible. A key change is to make the
osd_subsurface have wl->surface as the parent. This is seemingly
required otherwise the osd_surface buffers are never visible above the
empty video_surface when we have a black window. Also nuke the desync
call since it's completely pointless. Fixes https://github.com/mpv-player/mpv/issues/12429.
=> vo_dmabuf_wayland: support osd rendering when there's no video

common/msg_control.h, demux/timeline.h, filters/f_async_queue.h, filters/f_decoder_wrapper.h, filters/f_lavfi.h, misc/thread_pool.h, player/command.h, sub/ass_mp.h, sub/sd_ass.c
Mostly to silence clangd, but the sd_ass integer division is actually a bug fix for subtitles with unknown durations
=> miscellaneous cosmetic fixes

DOCS/man/options.rst, video/out/gpu/video_shaders.c
This allows adding grain without debanding. libplacebo already supported this, so no changes are required there.
=> vo_gpu: allow deband-iterations to be 0

video/out/gpu/video.c
There was assumption in the code that default settings are compatible with dumb mode and are only one that should be used in this case.
Use proper settings from user after checking that they are dumb.
=> vo_gpu: don't override scaler options with default ones

.github/workflows/build.yml, ci/build-macos.sh
Apparently it is available in public beta since late April.
ref https://github.com/actions/runner-images/issues/6426
=> github/workflows: add macOS 13 build

video/out/vo_gpu_next.c
Target frame parameters were used instead of source frame.
Also for HDR videos it seems that subtitles target SDR white, so set that too.
=> vo_gpu_next: use proper color for subtitles

DOCS/man/options.rst, options/options.c, options/options.h, video/out/w32_common.c
Add an option to control the mpv window's affinity. This will affect how it's displayed on the desktop and in system-level operations like taking screenshots.
=> win32: add an option to change window affinity

demux/demux_lavf.c
`demux->duration` is set to -1 on initialization, and some checks rely on it being -1 when unknown. Before this commit, we set `demux->duration` to 0 when unknown. This is incorrect and breaks rtsp logic for disabling seeking outside of cached regions.
To fix these issues, initialize `total_duration` and `av_duration` at -1. They're only changed if a real duration is detected, so in cases where the duration is unknown, demux->duration is set to -1 correctly.
Fixes: e6afc53e7c ("demux_lavf: get total duration from track durations")
Fixes #12454
=> demux_lavf: set duration to -1 if unknown

DOCS/man/mpv.rst, video/out/wayland_common.c
Unbelievably, mutter actually supports the idle inhibit protocol now after many years of pain*. Let's remove this hacky warning.
*: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3145
Blocked until the next GNOME release, but I'll leave it here so I don't forget.
=> wayland: remove gnome-specific idle-inhibit warning

player/lua/osc.lua
The midpoint of two numbers is given by their sum divided by two.
It's gone unnoticed because `s_min` is basically always zero. The only reason I noticed it is because I've been messing around with the slider's min and max values.
=> osc.lua: fix calculation for slider's midpoint

DOCS/man/mpv.rst, etc/input.conf
There was a discrepancy in what the keybind was advertised to do in the manual, and what the comment in input.conf described it to be doing. It makes very little sense to add a keybind that changes the default and doesn't allow you to get back to the default. This keybind is much more useful if it toggles between yes/force instead of no/force.
=> input.conf: make `u` toggle between force and yes

DOCS/man/options.rst, options/options.c, options/options.h, video/out/w32_common.c
Adds the ability to change the style of the backdrop to mica (alt), none or acrylic.
This is a Windows 11 only feature, I can't test this on 10 and it's most likely not gonna work on 7 at all, but since we only support 10+ it doesn't matter.
Feel free to test on fully updated 10 and report back.
The backdrop style mainly affects the Top bar/border because we have no other GUI elements where the backdrop is visible, e.g no button popup windows or anything.
As far as I can tell, Mica is transparent to the desktop background only, same as mica-alt, while acrylic is transparent to the windows/objects directly behind it.
While we're at it, should we set acrylic to be the default? or just let windows handle it, idk.. RFC on that.
Another question, but to my code, is the enum mapping fine? I …
=> win32: add option to change backdrop style

DOCS/man/af.rst, DOCS/man/options.rst, audio/filter/af_scaletempo2.c
Apparently this isn't so obvious. I would know.
=> DOCS/options: add example for custom pitch correction filter

DOCS/interface-changes.rst, player/command.c, player/lua/osc.lua
=> deprecate shared-script-properties

video/out/wayland_common.c
Calling wl_display_disconnect closes the file descriptor, no need to manually do it ourselves beforehand which causes a double close on the fd.
=> video: out: wayland_common: don't double close display fd

player/lua/osc.lua
The default `z` of an overlay is 0, which is used by e.g. console.lua.
Having the idle logo at a `z` of 1000 means that it ends up above the console (and anything that doesn't set a value higher then 1000). It doesn't make sense for the idle logo to overshadow other things, so put it at -1000 instead to prevent that.
=> osc: move the idle logo behind other overlays

demux/demux.c, demux/demux.h, sub/dec_sub.c
a323dfae426e43451f4d3e08a9a63cb7d1c1ace9 almost fixed subtitle tracks disappearing when paused but it actually missed one part: the behavior of demux_read_packet_async_until. It's a bit unintuitive, but for subtitle streams, that function would only return the very first packet regardless of whatever pts you pass to it. So the previous commit worked on the very first subtitle, but not actually any of the others (oops). This is because subtitle streams never marked as eager and thus never actually read farther ahead. While the video is playing, this is OK, but if we're paused and switching subtitle tracks then the stream should be eagerly read. Luckily, the logic is already there in the function for this. All we have to do add an extra argument to
demux_read_packet_async_until to force the …
=> demux: eagerly read subtitle streams when switching tracks while paused

audio/chmap.c, audio/chmap.h, audio/out/ao_coreaudio_chmap.c, audio/out/ao_pipewire.c, audio/out/ao_wasapi_utils.c
=> audio/chmap: support up to 64 channels

video/out/hwdec/dmabuf_interop_gl.c, video/out/hwdec/hwdec_drmprime.c
NV16 is the half subsampled version of NV12 format where  it is quarter subsampled.
Decoders which support High 4:2:2 profile of h264, provide the frames in NV16 format to establish richer colorspace.
Similar profiles are also available in HEVC and other popular codecs. This patch allows NV16 frames to be displayed over drmprime layers.
Tested to be working with https://github.com/jernejsk/ffmpeg/tree/v4l2-request-n6.0
You can use High422 Profile h264 file to verify.
Here are some samples:
http://videos.hd-trailers.net/TheLastWitchHunter_TRLR1-1080p-HDTN.mp4
http://videos.hd-trailers.net/Poltergeist_DOM_TrailerD-1080p-HDTN.mp4
if someone else wants to double check.
=> Add NV16 support for drmprime hwdec

player/command.c, player/core.h, player/loadfile.c, player/playloop.c
When seeking chapters, `last_chapter_seek` acts as a projection of what the current chapter will be once mpv has a chance to seek to it. This allows for more accurate results from the `chapter` property.
It works by comparing the projection to the actual current chapter and returning the larger of the two indexes, but this only works when seeking forward.
If we want it to work for both forward and backward chapter seeking, we can instead use a boolean called `last_chapter_flag`, which gets switched on when a chapter seek request is made, and then switched off when the seek has been performed.
We should also check to ensure that we don't allow the chapter index to be set to -1 unless there is a span of time between the very beginning of the track and the start of the first chapter.
Since …
=> playloop: make chapter property more accurate when chapter-seeking

DOCS/man/lua.rst
This seems to have been a leftover from copying the entry below it.
=> DOCS/lua: remove superfluous parameter

video/out/w32_common.c
Fixes missing icon when initial window is created without caption.
Fixes: #12472
=> win32: set WS_SYSMENU style always

demux/demux.c
Yeah another try at this. So when inspecting lazy_stream_needs_wait, I realized it had a curious !ds->reader_head condition. Actually, this is what is messing everything up. This was originally added in cf2b7a4997299ff9e0ff91d4273cd294686b001f for showing large negative sub delay values correctly. It worked because the packet will eventually be discarded during playback causing ds->reader_head not exist and thus the next one will correctly be read ahead as needed.
But for the "switching subtitle tracks while paused" case, this is actually bad. As the stream is read, eventually you'll find a packet and set the reader_head. But it's not going to be the correct packet (unless you're looking for the very first one), so you need to read more. This won't happen because of the !ds->reader_head …
=> demux: fix erroneous condition in lazy_stream_needs_wait

etc/restore-old-bindings.conf
Remove keybindings for properties that have been removed because they can no longer be used even if you restore them.
Fix the L keybinding: it was bound to cycle-values loop when loop was an alias for loop-playlist, but now it's an alias for loop-file.
"osd" was a command that cycles osd-level from 0 to 3.
Keep only the newest I show-text "${filename}" from mpv 0.26, the mpv 0.5 line for it is a mistake because it was bound to that in input.conf from a749c61437 (2012) until 2e84934be7 (2017), while mpv 0.5 is from 2014.
=> restore-old-bindings.conf: remove unusable bindings

video/out/vo.c, video/out/vo.h, video/out/vo_caca.c, video/out/vo_direct3d.c, video/out/vo_image.c, video/out/vo_null.c, video/out/vo_sdl.c, video/out/vo_tct.c, video/out/vo_vaapi.c, video/out/vo_x11.c, video/out/vo_xv.c
0739cfc20934ac7772ab71dbae7ecba4ba10fda4 added the draw_frame API
deprecated draw_image internally. VOs that still used draw_image were
around, but really there's no reason to not just "upgrade" them anyway.
draw_frame is what the "real" VOs that people care about (gpu/gpu-next)
use. So we can just simplfy the code a bit now. VOCTRL_REDRAW_FRAME is
also no longer needed so that can be completely deleted as well. Note
that several of these VOs are legacy crap anyway (e.g. vaapi) and maybe
should just be deleted but whatever. vo_direct3d was also completely
untested (not that anyone should ever use it).
=> vo: fully replace draw_image with draw_frame

DOCS/man/options.rst, player/external_files.c
Combine the cover art whitelist with the extensions in --cover-art-auto-exts instead of hardcoding them. This is shorter, checks for more extensions, saves us from updating the whitelist everytime we add a new image extension, and since the whitelist had gotten so big and the priority is calculated as
MP_ARRAY_SIZE(cover_files) - n, files like cover.jpg were taking priority over cover art loaded by --cover-art-auto=exact.
=> external_files: base cover-art-whitelist on cover-art-auto-exts

demux/codec_tags.c
This only had jpeg and png in it strangely enough. Fixes #11592.
=> codec_tags: map some more image mimetypes

video/out/w32_common.c
We have to support all changing states, not only borderless.
=> win32: adjust WM_NCACTIVATE for better compatibility with window state

meson.build
This allows libmpv users to build it as a subproject easily, i.e. meson setup build --force-fallback-for=mpv -Dmpv:libmpv=true, if the mpv source is in the subprojects directory. Mainly useful for development.
For an easy test, take this meson.build file and drop in the mpv-examples [simple](https://github.com/mpv-player/mpv-examples/tree/master/libmpv/simple) directory.
```
project('simple', 'c')
mpv = executable('simple', 'simple.c', dependencies: dependency('mpv'))
```
Place the mpv source directory within a subprojects folder in simple however you like (symlink or just a copy). If you do: `meson setup build --force-fallback-for=mpv -Dmpv:libmpv=true`, the subproject fallback will work with this branch but not on master.
=> meson: declare libmpv as a dependency and override it

TOOLS/lua/autoload.lua
msg.info for when you're potentially adding hundreds of files is way too spammy and not really useful (autoload loads files, what?). Bump it up to msg.verbose. Also bump up the previously existing msg.verbose logs up to msg.debug to keep the difference in log levels. Fixes #12551.
=> TOOLS/lua/autoload: bump the msg-level of some logging

video/out/vo.c, video/out/vo.h, video/out/vo_dmabuf_wayland.c
When implementing vo_dmabuf_wayland, it always did a copy of the image from the current frame and worked with that. The reason was because mpv's core held onto the frame and caused some timing issues and rendering glitches depending on when it freed the image. This is pretty easy to fix: just make vo_dmabuf_wayland manage the the frames. In vo.h, we add a boolean that a VO can set to make them manage freeing frames directly. After doing this, change the buffers in vo_dmabuf_wayland to store the whole vo_frame instead of just the image. Then, just modify some things a bit so frame is freed instead of the image. Now, we should truly have zero-copy playback (in theory anyway).
=> vo_dmabuf_wayland: eliminate an extra frame copy

DOCS/man/options.rst, player/external_files.c
I made a mistake in 0070a5820e here because there were 2 separate groups of "front" filenames.
=> external_files: remove duplicate from cover art whitelist

common/playlist.h, player/command.c, player/core.h, player/loadfile.c
2c6a3cb1f27e02b2e66390a2465ab648905a64d0 originally added this struct member and then 1be863afdbe9017aa227234e8525b209fb818224 later added some more logic to loadfile that uses this. There's been more changes since then of course, but bits using playback_short and playback_start have mostly stayed the same. It's a bit strange it's worked this way for so long since it makes an assumption on how long files should be and leads to weird, broken behavior on playlists with shorter videos. The main reason for playlist_short, as far as I can tell, is to deal with some fringe cases with short videos and trying to go back in the playlist. More specifically, if you use --loop=inf on a very short video (say less than 1 second) and try to go back in the playlist, you won't be able to without any of …
=> loadfile: fix an old wonky playlist heuristic

video/out/w32_common.c
This fixes white background appearing for short period of time before first frame is drawn. Clear to black as this is way less distracting than bright white flash.
Borderless window and fullscreen seems to be initially not drawn/transparent, so no need to clear it to black. Only when decorations are enabled (--border) the issue happens.
Fixes: #12549
=> win32: clear client area to black early

video/out/vo_dmabuf_wayland.c
The current calculation makes the implicit assumption that the margins on both sides are always equal (the 2 times multiplication). This isn't true though. For example, a 720p video fullscreened on a 1680x1050 display will have a top margin of 52 but a bottom margin of 53. The current calculation just multiplies 52 by 2, so it's off by one. Fix this by adding together all the margins together (left + right or top + bottom) then adding that to the dst window size (width or height). This way, we get the full size of the window for the viewport. Fixes #12554.
=> vo_dmabuf_wayland: correct full window size calculation

player/command.c, video/out/vo.c, video/out/vo.h, video/out/vo_gpu_next.c
fbe154831a8addfc18a4f81e1c4b9284c31acace added a new VOCTRL to signal when the OSD changed for gpu-next's handling of subtitles, but this is both not necessary and actually incomplete. The VOCTRL would signal OSD changes, but not all subtitle changes (like selecting another non-external sub track for example). VOCTRL_OSD_CHANGED was used to increment p->osd_sync which would then redraw the blended subtitles if the player was paused.
But there's already a VOCTRL_PAUSE and VOCTRL_RESUME. Plus, the sub_bitmap_list object will have items in it if it changed in any way, so we don't need the VOCTRL_OSD_CHANGED method at all. That can be removed.
The check that fp->osd_sync < p->osd_sync stays in place since that's an optimization while the video is playing, but we also check the pause state as …
=> vo_gpu_next: improve updating overlays

sub/sd_ass.c
The function called to get sub-start and sub-end returns early when the subtitle's duration is unknown, but by just removing this check the properties work fine. The final sub line has a very large sub-end, but that is much better than not having the properties work at all.
=> sd_ass: enable sub-start and sub-end with unknown duration subs

DOCS/man/af.rst, audio/filter/af_scaletempo.c
`overlap` uses a factor not a percentage.
=> af_scaletempo: overlap is a factor not a percentage

DOCS/interface-changes.rst, DOCS/man/options.rst, demux/demux.c, demux/demux_cue.c, demux/demux_playlist.c, misc/charset_conv.c, stream/stream_lavf.c
1. Use `--metadata-codepage` in stream_lavf.
2. Remove ancient crap.
3. Make demux_cue use `--metadata-codepage` instead of its own duplicate option.
4. Set the default of `--metadata-codepage` to `auto`.
=> codepage improvements

video/mp_image.c
It is already set above.
Fixes: #12577, #12587
=> mp_image: don't copy crop value from opaque_ref

ci/build-mingw64.sh
Upstream has been changing buildsystem and current vulkan.pc is not
functional with custom prefix path.
Rollback to older version until it is fixed.
See:
https://github.com/KhronosGroup/Vulkan-Loader/issues/1318
https://github.com/KhronosGroup/Vulkan-Loader/issues/1319
=> ci/mingw: use vulkan-loader v1.3.266

player/video.c, video/out/vo.c, video/out/vo.h
vo_still_displaying() is racey with vo_request_wakeup_on_done() and above that it doesn't work as expected. VO can run out of work and go to sleep for 1000s, while the play thread still returns on vo_still_displaying() check, because of a check `now < frame_end` so it never advances and go to sleep itself.
This fixes dead lock that we have when image parameters changes during playback.
This reverts commit 0c9ac5835be70ae26e4aa875e833fe2c7b3b3bf3.
Fixes: #12575
=> Revert "video: remove another redundant wakeup"

DOCS/man/console.rst, player/lua/console.lua
Tab completion now temporarily shows a colored table of all potential completions
between the log messages and prompt.
The table automatically adjusts its column count depending on the space available.
As there is no way of knowing the exact width in characters, this is an estimate
and can be adjusted with the new option `font_hw_ratio`.
I expect the default value to work for everyone who doesn't set their own font.
The spacing between the columns also adjusts automatically, depending on
how much space is left.
=> console: show suggestions for completion

ci/build-tumbleweed.sh
We don't have much test coverage, but even running the built binary doesn't harm to check with sanitizers.
=> ci: add sanitizers to Tumbleweed build

DOCS/interface-changes.rst, DOCS/man/input.rst, common/playlist.c, common/playlist.h, player/command.c
playlist-prev-playlist goes to the beginning of the previous playlist because this seems more useful and symmetrical to playlist-next-playlist. It does not go to the beginning when the current playlist-path starts with the previous playlist-path, e.g. with mpv --loop-playlist foo/, which expands to foo/{1..9}.zip, the current playlist path foo/1.zip beings with the playlist-path foo/ of {2..9}.zip and thus playlist-prev-playlist goes to 9.zip rather than to 2.zip.
Closes #12495.
=> command: add playlist-next-playlist and playlist-prev-playlist

DOCS/man/console.rst, player/lua/console.lua
This binding commonly closes similar input buffers like vim's Command-line mode and dmenu.
=> console.lua: exit with with Ctrl+[

DOCS/man/lua.rst
This still shows the old way of calling read_options even though it was deprecated 8 years in ago 327b091909e.
=> DOCS/lua: update read_options example

DOCS/man/options.rst
Only vpdau-copy works with EGL. 2d1d815cc7 already added this to manpage, and 1c8d2246bf removed it again, but that seems to be a mistake because I can only get vdpau to work with GLX, and another user also reported that only vdpau-copy was working for him with the default EGL.
=> DOCS/options: vdpau requires GLX

DOCS/man/lua.rst, player/lua/defaults.lua
Added to the functions `mp.add_timeout` and `mp.add_periodic_timer`.
If the `inactive` argument is set to `true` or a truthy value, the timer will wait to be manually started with a call to its `resume()` method.
=> defaults.lua: add an inactive parameter to timer constructors

player/lua/ytdl_hook.lua
Use EDL for single tracks with metadata to set the uploader, channel url and description metadata with --ytdl-format=best. Currently, these are only set with the other ytdl formats with video and audio in different streams.
The uploader tag is commonly available in sites other than Youtube too, so it may be simpler to always use EDL with single tracks.
=> ytdl_hook.lua: set metadata with single tracks

common/playlist.c, player/command.c
This was wrongly assuming that playlist_path is always set for the current playlist entry, but it's only set when a file was added by expanding a playlist.
The crash in playlist_get_first_in_next_playlist can be reproduced with mpv foo.mkv foo.zip, playlist-next, playlist-prev, playlist-next-playlist. You need to run playlist-next, playlist-prev first because foo.zip's playlist_path is NULL until you do that, which makes playlist_get_first_in_next_playlist return immediately.
The crash in cmd_playlist_next_prev_playlist can be replicated with mpv --loop-playlist foo.zip foo.mkv, running playlist-next until foo.mkv, and playlist-play-next. Again, you need to open foo.zip first or its playlist_path is NULL which skips running strcmp(entry->playlist_path, …
=> command: fix segfault with playlist-{next,prev}-playlist

video/out/opengl/hwdec_dxva2egl.c
Fixes type mismatch after recent changes.
Fixes: 59dd7d94af7651baf7e60966c5f8e7d52959d958
=> hwdec_dxva2egl: fix log value type

player/lua/stats.lua
The text didn't line up with with the percentages above it because it didn't use a monospace font.
Instead insert the text at the same position in the template as the percentages and convert one o.prefix_sep from the percentages into hard coded \h\h to ensure alignment even when the user changes o.prefix_sep.
=> stats.lua: fix page 2 alignment of "Total"

DOCS/man/af.rst, audio/filter/af_scaletempo2.c
scaletempo2 doesn't do a good job when the signal contains frequencies less then 1/search_interval.
With a search interval of 30ms that means anything below 33.333Hz sounds bad.
Depending on the genre it's very common for music to contain frequencies down to 30Hz, and sometimes even a little bit below that. Therefore a higher default value is needed to handle such cases.
Based on that an argument can be made for a value of 50, as that should work down to 20Hz, or something even higher because movies sometimes have some infrasonic content.
However the downside of big search intervals is increased CPU usage and intelligibility at higher speeds, as it effectively leads to parts of the audio being skipped.
A value of 40 can handle frequencies down to 25Hz, enough for all music except very …
=> af_scaletempo2: better defaults

player/lua/stats.lua
These are ancient and have existed since before stats.lua lived in the
mpv repository. We don't need to worry about ancient mpv versions
anymore, so remove these.
=> stats.lua: remove compatibility aliases of properties

.github/workflows/build.yml
Homebrew has finally given up supporting macOS 11, and all updated dependencies are being built locally. Additionally, python3.12 - being a dependency of libass in Homebrew - seems to completely fail under cairo's meson usage on macOS 11, even if we let it build.
Thus, finally remove macOS 11 from our macOS build matrix, leaving 12 and 13.
ref: Homebrew/brew#16019
=> github/workflows: remove macOS 11 build

DOCS/interface-changes.rst
directory-mode's default was changed again to auto afterwards.
=> DOCS/interface-changes: remove redundant change

DOCS/man/options.rst
This may have been true 10 years ago but now reset-on-next-file can definitely reset options that weren't explicitly set.
=> DOCS/options: remove obsolete notice

options/m_option.c, player/command.c
To avoid switching to scientific notation. Apparently it is "jarring" for some users.
This preserves status quo from before 9dddfc4f where pretty printer were truncated to 3 decimal places, now it is 4.
=> player/command: truncate anything < 1e-4 in pretty printer

common/tags.c, common/tags.h, demux/demux_lavf.c
This ensures that when lavf appends metadata
that occurs later in the stream,
it starts from empty each time.
Fixes: <https://github.com/mpv-player/mpv/issues/12559>
=> demux_lavf: clear original metadata after copying

player/lua/stats.lua
It is useless to show this because it's just a bogus value taken from --mf-fps.
=> stats.lua: hide images' FPS

ci/lint-commit-msg.py
Otherwise acronyms and such would fail the lint, and it doesn't make any sense to enforce it here. Also make sure that the length of the word is greater than 1 to avoid something like "foo: A blah blah" from passing.
=> ci/lint: allow the first word to be all caps

demux/demux_mkv.c, video/mp_image.c
DisplayWidth/DisplayHeight applies to the video frame after cropping (PixelCrop* Elements).
=> demux_mkv: PAR should be calculated after applying crop

audio/out/buffer.c, osdep/threads.c, osdep/threads.h, osdep/win32/include/pthread.h, osdep/win32/pthread.c
ao_read_data() is used by pull AOs potentially from threads managed by external libraries.  These threads can be sensitive to blocking. For example the pipewire ao is using a realtime thread for the callbacks.
Note:
I don't have a specific problem this fixes, but it looked like it could be one in theory.
=> audio: don't block on lock in ao_read_data

README.md, osdep/timer.c
macOS didn't support clock_gettime until 10.12 which was released roughly 7 years ago. Since we're breaking support for ancient OSes anyway, we might as well break some old macOS versions for fun. This makes 10.12 the minimum supported macOS version.
=> timer: drop ancient macOS fallback

demux/demux_mkv.c
track->v_width isn't always the same as track->v_dwidth. So the crop calculation logic here could actually change the dimensions of the video even if there was no crop set simply because track->v_width is a different value. Rearrange the ternary a bit so we keep the same logic as before in the no-crop case. Fixes #12680.
=> demux_mkv: don't set codec crop rect when there is no crop

video/filter/vf_vapoursynth.c
Fixing consequences of https://github.com/mpv-player/mpv/pull/11224.
W/o this there's no way now to set correct time_base and encoder always do "240 fps".
=> vf_vapoursynth: set nominal_fps after the filter

options/path.c
currently for a filename such as ".file" mpv incorrectly thinks of the entire filename as being an extension. skip leading dots to avoid treating "hidden/dot" files as extension.
=> path: don't treat "hidden" files as extension

DOCS/contribute.md
I'm guilty of violating this, but surely I can't be the only one. 85 is pretty small and there's plenty of lines in the codebase that go well over that. Surely nobody programs on tiny screens anymore and the kernel raised the limit to 100 a few years ago so let's just copy that.
=> DOCS/contribute: increase hard column limit to 100

.github/workflows/build.yml, .gitignore, ci/build-macos.sh, ci/build-mingw64.sh, meson.build, meson_options.txt, player/main.c, subprojects/libplacebo.wrap, video/out/gpu/hwdec.c, video/out/hwdec/hwdec_drmprime.c, video/out/hwdec/hwdec_vaapi.c, video/out/vo.c
This works by first checking if the required libplacebo version is available on the system, if it isn't then we'll automatically fallback to the wrap and fetch libplacebo recursively with all its submodules and link statically.
For now, we're only pulling in the latest tagged release instead of master or a specific revision.
=> make libplacebo a required dependency

options/m_config_core.c, options/m_config_frontend.c, options/m_option.h, options/m_property.c, player/client.c, player/command.c
C standard says that `= {0}` activates and initializes first member of union. We expect whole union to be zeroed, it is used as default value.
Initialize union with one zeroed default instance to ensure proper init.
Fixes: #12711
=> m_option: initialize m_option_value union properly

.github/workflows/build.yml, ci/build-freebsd.sh
Since vmactions is basically a bootlooping disaster with no signs of life from upstream, let's try a different action instead and hope it works better.
=> github/workflows: use cross-platform-actions for freebsd

demux/codec_tags.c, demux/codec_tags.h, demux/demux_mf.c, demux/demux_mkv.c, player/sub.c
Basically a way to fix #12387. I know I could have left the logic completely in `demux_mkv`, but reusing the list in `demux_mf` seemed better to me than making yet another mapping of things we consider images.
=> update subtitles on mkvs with an image track

.github/workflows/build.yml
Maybe macos-13 runners will be more stable?
=> github/workflows: use macos-13 host for freebsd

osdep/subprocess-posix.c, osdep/terminal-unix.c
This fixes warnings generated for `unused-result` since read/write
functions are declared with the `warn_unused_result` attribute when mpv
is build with `-O1 -D_FORTIFY_SOURCE=1` with clang. Cast to avoid to
avoid these warnings.
=>  osdep: fix clang warnings with `_FORTIFY_SOURCE`

DOCS/interface-changes.rst, DOCS/man/options.rst, etc/builtin.conf, video/out/vo_gpu_next.c
Also enable peak detect in fast profile, with delayed peak allowed. This still doesn't require FBO indirection.
Peak detection greatly increases HDR experience. It has been optimized in libplacebo to a point that even on slow Intel iGPU it is safe to use.
=> options: disable --allow-delayed-peak-detect by default

.github/workflows/build.yml
In the pursuit of stability.
It is slower, qemu based, but if this is not stable, I don't know what
will be...
Bump timeout to 30 minutes, just in case. It seems to take 12-15
minutes to finish.
=> github/workflows: use ubuntu-latest host for freebsd

DOCS/interface-changes.rst, DOCS/man/options.rst, DOCS/man/stats.rst, options/options.c, options/options.h, player/javascript.c
The MPV_LEAK_REPORT environment variable was previously read in order to determine whether or not to enable memory reporting for javascript scripts. This is kind of weird and deviates from the norm of exposing an option to the user. So let's just add --js-memory-report and disable it by default instead.
Based on discussion from here: https://github.com/mpv-player/mpv/pull/12571#discussion_r1371922356
=> javascript: use --js-memory-report option instead of MPV_LEAK_REPORT

DOCS/man/options.rst
This option does nothing when put inside config files.
=> DOCS/options: clarify `no-config` is a command line flag

common/msg.c, osdep/semaphore_osx.c, osdep/timer.c, osdep/timer.h
otherwise, it may give wrong/unwanted results due to operator precedence when used in arithmetic expressions.
=> timer: remove MP_START_TIME

TOOLS/macos-sdk-version.py
Python 3.10 deprecated disutils and then removed it in 3.12. The macos sdk check uses the version compare from there, so it needs to be replaced with something else. So instead use the API from the packaging module which is also widely available and a fit replacement.
Might need to install python-packaging for the CI. Let's see.
Edit: evidently not.
=> TOOLS/macos-sdk-version: use packaging instead of distutils for version

osdep/timer-linux.c
CLOCK_MONOTONIC_RAW is linux-specific and not necessarily available everywhere (like BSDs). It makes sense to prefer it because mpv does a lot of measurements at small intervals (e.g. every frame) so theoretically it should be more accurate. However if the OS doesn't have that, just use CLOCK_MONOTONIC instead which is almost exactly the same. The slight difference probably doesn't matter for us anyway. This does mean that for any POSIX system (minus macOS which has its own stuff), we effectively require CLOCK_MONOTONIC to be available. This clock is technically optional according to POSIX, but the chances of any OS we care about not actually supporting this is probably 0. As a benefit, we know the time returned from this codepath is always monotonic.
=> timer-linux: fallback to CLOCK_MONOTONIC instead of timespec_get

TOOLS/file2string.py, TOOLS/matroska.py
This was originally for the waf build, and then later writing the output to a file was added for meson. Since the waf build is no longer around anymore, remove the dead code.
=> TOOLS/{file2string,matroska}: drop unneeded stdout output

meson.build
This fixes compilation on macOS when Python 3.12 is installed as [`meson`](https://formulae.brew.sh/formula/meson#default) dependency from Homebrew.
[`python@3.12`](https://formulae.brew.sh/formula/python@3.12#default) installs executable as `python3.12` so `python3` still refers to system Python 3.9.
ref: https://github.com/mpv-player/mpv/pull/12763
cc: @Dudemanguy
=> meson: import python module

audio/out/ao_coreaudio.c
Change the resulting buffer sizes to match the actual amount of samples read, and set a flag in case no samples were read at all.
References: https://github.com/mpv-player/mpv/pull/12643
=> ao_coreaudio: signal buffer underruns

DOCS/man/options.rst, player/lua/ytdl_hook.lua
Successor to #7848
Doing it this way has the downside that all added thumbnails get downloaded. This could be avoided if they were added like formats when `all_formats=yes` is used, but that can be changed some other time.
=>  ytdl_hook: support thumbnails

DOCS/interface-changes.rst, DOCS/man/af.rst, DOCS/man/mpv.rst, DOCS/man/options.rst, DOCS/man/vf.rst, options/m_option.c
1. Make `-remove` remove all matches in the list, not just the first one.
2. Drop the `-del` syntax which was deprecated years ago and probably not really useful.
Technically, adding multiple items is also deprecated but I'm not sure if we should really drop that, so I didn't do that.
=> cleanup list option/filter syntax

video/filter/vf_vapoursynth.c
Vapoursynth does not provide crop metadata and input one is likely to be invalidated during filtering, so just set to full frame.
Fixes: #12780
=> vf_vapoursynth: set crop metadata after mapping vapoursynth frame

player/lua/console.lua
cycle-values already completed the first two arguments, but the command accepts infinitely many arguments, so enable completion for all of them.
I left the loop in there in case it'll be useful in the future, but it can be removed if that's preferred.
@guidocella
=> console: complete infinite cycle-values arguments

player/lua/console.lua
This adds some more completers to console.lua.
Question: do we want to complete `del` with the list option verbs even though it's deprecated or is it one of these things that no one is going to remove without wm4?
=> console.lua: add more completers

player/lua/defaults.lua, player/lua/options.lua, player/lua/osc.lua, player/lua/stats.lua, player/lua/ytdl_hook.lua
For whatever reason, some of the lua code (particularly the osc and ytdl_hook) is full of a bunch of stuff like if (foo), if not (foo == nil), etc. The parenthesis aren't needed in lua and actually just look weird since nobody actually writes lua like this. You can see most of the other conditionals are written normally. So cleanup the style to match when the parenthesis clearly aren't doing anything.
I'm sure I made an oopsie somewhere so someone please double check me.
=> lua: remove a ton of unneeded parenthesis

video/out/w32_common.c
Not sure how often `get_refresh_rate_from_gdi()` is actually called but just in case.
=> win32: add more values for monitor refresh rate detection

DOCS/interface-changes.rst, DOCS/man/input.rst, demux/demux_mkv.c, filters/f_decoder_wrapper.c, player/command.c, player/lua/stats.lua, test/meson.build, test/test_utils.c, video/csputils.c, video/csputils.h, video/filter/vf_format.c, video/image_writer.c, video/mp_image.c, video/out/gpu/video.c, video/out/gpu/video_shaders.c, video/out/vo.h, video/out/vo_gpu_next.c, video/zimg.c
Extracted from #12306, since it is stuck in limbo
=> csputils: add pl_hdr_metadata to mp_colorspace and deprecate sig_peak

osdep/threads-posix.h, osdep/threads-win32.h, osdep/threads.h
Also remove duplicated macro.
Fixes: #12818 #12820
=> threads: unbreak mpv on builds without asserts

player/video.c, video/out/vo.c
This would cause mpv to, in some very specific scenarios, have a negative vsync_offset after seeking which would result in mpv requesting a pts before the first frame to libplacebo.
Fix it by setting it to 0 when we reset state, such as after seeking.
Fixes: https://github.com/mpv-player/mpv/issues/12813
=> video: reset `display_sync_error` when resetting state

player/lua/ytdl_hook.lua
Apparently twitch provides two thumbnails, one has a `preference` field and the other one does not, which leads to a crash when `--script-opts=ytdl_hook-thumbnails=best` is used. To fix this fall back to `-math.huge` in case there has already been a thumbnail with preference set.
=> ytdl_hook: fix mixed thumbnail.preference availability

video/out/drm_common.c, video/out/drm_common.h, video/out/opengl/context_drm_egl.c, video/out/present_sync.c, video/out/present_sync.h, video/out/vo_drm.c, video/out/wayland_common.c, video/out/x11_common.c
I had to enhance `present_sync` a little bit, but this gets drm on the same codepath that x11 and wayland already use in regards to this stuff.
=> drm: use present_sync mechanism for presentation feedback

DOCS/man/input.rst
Because b56e63e2a9 removed it.
=> DOCS/input: stop documenting vf del

player/command.c, sub/sd.h, sub/sd_ass.c
In the sub seek code path, there was an arbitrary small offset added to the pts before the seek. However when seeking backwards, the offset was an additional subtraction. de6eace6e984be3cd2515e9be6362a0cf04b7457 added this logic 10 years ago and perhaps it made sense then, but the additional subtraction when seeking backwards causes the subtitle seek to go too far to the previous subtitle if the durations overlaps. This should always be an addition to work correctly. Additionally, the sub stepping code path also could use this offset for the same reason (duration overlaps). Let's always add the offset to refpts to account for both cases and update the comment to be a little more relevant. Fixes #11445.
=> player/command: adjust offsets when sub seeking/stepping

DOCS/man/options.rst, video/out/wayland_common.c
There's some geometry-related things that mpv has to calculate before the window is actually mapped onto the screen in wayland. But there's no way to know which output the window will end up on before it happens, so it's possible to calculate it using the wrong values. mpv corrects itself later when the surface event happens, but making the initial guess work better can help in certain cases.
find_output is the only thing that needs to be changed here. Its main purpose is to grab the right output based on user settings when we're trying to full screen and giving a fallback in case we don't have wl->current_output yet. The x11 code already does something similar, so we're basically just copying it. Allow user settings like --screen and --screen-name to influence the initial wl_output …
=> wayland: improve wl_output guessing before mpv window is mapped

DOCS/man/console.rst, DOCS/man/mpv.rst
Capitalization makes a difference for letter keys, so we should use the correct one.
Also the formatting of some keybindings was inconsistent.
@Akemi can you please confirm that `Command` works on macOS?
=> DOCS: keybindings correction and consistency

player/lua/console.lua
This is useful to see the complete list of commands or properties instead of having to type the first letter before any suggestions are available.
There are over 9000 properties (thanks to [this](https://github.com/mpv-player/mpv/blob/6b74b55283cd4f78138b0b7e8143263d091823d8/player/lua/console.lua#L493-L500)), which required some optimizations to make it not terribly slow on luajit. Lua interpreter was still pretty slow though and requires the last commit to become usable.
=> console: enable completions without a prefix

DOCS/man/options.rst, options/options.c, options/options.h, sub/sd_ass.c
Stretch a subtitle duration so it ends when the next one starts.
Should help with subtitles which erroneously have zero durations.
I found such a subrip substitles stream in the wild.
=> sub: Add --sub-stretch-durations option

player/lua/console.lua, player/lua/stats.lua
The background from `--osd-back-color` is [mutually exclusive](https://github.com/mpv-player/mpv/blob/2dc8e70093d9f80a01696f059ff02784bcb7b5f0/sub/ass_mp.c#L66-L72) with text shadows and ASS apparently uses the color and alpha set for shadows (`\4c` and `\4a`) for that background.
console and stats were always overwriting those values, effectively ignoring the actual values set in `--osd-back-color`.
Replicate the check done in ass_mp.c and only set shadow color and alpha when there actually are shadows.
=> console/stats: don't overwrite color and alpha of `osd-back-color`

player/command.c
Without this, changing the vo at runtime with --force-window --idle would kill the vo.
=> player/command: handle force window on runtime vo changes

player/lua/console.lua
=> console.lua: don't print the console log to the OSD when switching VO

DOCS/man/options.rst
Fixes another one of those "flickering when seeking with interpolation" vo_gpu_next edge cases.
=> vo_gpu_next: require more than one frame for interpolation

player/command.c, player/video.c, video/out/vo.c, video/out/vo.h, video/out/vo_gpu_next.c
Currently VOCTRL are completely unusable for frequent data query. Since the HDR parameter addition to video-params, the parameters can change each frame. In which case observe on those parameter would be triggered constantly. The problem is that quering those parameters involves VOCTRL which in turn involves whole render cycle of delay.
I'm not quite happy with this solution, but don't see better one without changing observe/notify logic significantly. And even than for metadata that changes each frame, we would need to still have some kind of cache to not wait for VOCTRL again...
Fixes: 84de84b
Fixes: #12825
=> vo: remove VOCTRL_HDR_METADATA

.editorconfig
if we're going to have an editorconfig, might as well make it accurately reflect the coding guide.
also set trim trailing whitespace to true.
=> editorconfig: add max line

osdep/poll_wrapper.c, video/out/drm_common.c, video/out/vo.c, video/out/vo_sdl.c, video/out/wayland_common.c, video/out/x11_common.c
Most importantly, the wait_until addition was missed while doing the unit conversions to nanoseconds which meant mpv woke up roughly every second since not nearly enough time was added. It was meant to be 1000 seconds (1e9 in microseconds). Use a macro so it's more readable. Also put some other wild 1e9 calculations inside of a macro as well.
Fixes a899e14bccb667af243f8fce454160e17ae45c2a.
=> vo: replace some magic numbers with timer macros

DOCS/man/input.rst, player/command.c
Having the show-progress command obey no-osd is nonsensical and
unintuitive. The show-text command already ignores no-osd, so there's
precedence for this. Fixes #5662.
=> player/command: make show-progress work regardless of osd prefix

osdep/io.c, osdep/io.h, video/out/vo_gpu_next.c
context: while I was testing stuff mpv once complained about "Failed loading cache: file seems empty or truncated"
I assumed this must have happened during an mpv crash or while multiple instances were trying to write the file (at the same time) and decided to make these changes.
<s>@<a></a>kasper93 I vaguely remember atomic `rename` for overwriting not working on Windows. Any advice? </s>
Indeed doesn't work, should be fixed now.
=> Save libplacebo.cache file atomically

TOOLS/macos-sdk-version.py, meson.build
i checked some of the oldest and newest xcode and command line tools for the problem with the sdk version and the truncated minor version. the only version that still exhibits that problem is xcode older than 12. xcode 12 is the newest version supported on our oldest macOS version supported. since xcode 11 is also still supported on 10.15 i added the sdk version retrieval with an xcode only tool in the case xcode is installed. this can be removed once we drop support for macOS 10.15.
anyway, the very error prone conversion from sdk build version to sdk version can be safely removed now and we get proper sdk version retrieval in all cases now (other than Apple fucking up again).
```
build-version	version		ProductVersion
CommandLineTools 11.3.1		19B90		10.15.1
CommandLineTools 12.1		19G68 …
```
=> TOOLS/macos-sdk-version: remove legacy sdk version retrieval

video/out/mac_common.swift
just some swift compatibility with apparently swift versions older than 5.5. if we drop swift 5 someday this can be reverted.
=> mac: fix build on older swift versions

DOCS/interface-changes.rst, osdep/macos/swift_extensions.swift, video/out/mac/common.swift
remove the old broken display name retrieval and use the new property introduced in 10.15.
=> mac: change display name retrieval to localizedName NSScreen property

video/out/wayland_common.c, video/out/wayland_common.h
In the past, this worked by accident because the initial startup was racy and sometimes the initial firing of handle_toplevel_config would happen after reconfig. Since we now properly wait on all compositor events we can save the initial size hint that is given to us and try to use that as the window-size/geometry provided the --autofit/geometry options aren't explictly set. Fixes #11134.
Extracted from #12260.
=> wayland: obey initial size hints set by the compositor

osdep/w32_keyboard.c
MP_MBTN_BACK is already mapped, the appcmd duplicates this.
Fixes: #12768
Fixes: 8301906
=> osdep/w32_keyboard: remove duplicated MP_KEY_BACK mapping

player/lua/console.lua
String formatting of Lua crashes with widths greater then 99, so limit the value to that.
A nicer solution would be to create our own string padding function that can handle bigger widths, but such long  suggestions aren't common enough to be worth the effort.
=> console: fix crash for long suggestion strings

video/out/wayland_common.c
When pressing `shift+tab` we get `0xfe20` instead of `0xff09`, which corresponds to the `XKB_KEY_ISO_Left_Tab` define.
=> wayland: fix shift+tab keyboard input

demux/demux.c
cd59ea8afab6381951a3ae19a43e422906d02164 removed an arbitrary start offset added to the timer. However, it turns out that demux secretly depends on this. When updating cache to actually read bytes from the stream, there's a diff >= MP_TIME_S_TO_NS(1) check to make it only update once every second. With the old MP_START_TIME macro, the initial time value would always be at least 1e10, so this would also be true. Since we don't have that offset anymore, now the initial time is less than that so it is not updated and properties like file-size are 0. Just be sure to always update if the last_speed_query is 0 (i.e. we just started the player). Fixes #12869.
=> demux: always update the cache on init

DOCS/man/options.rst
The back color overrides the shadow, not the border.
=> DOCS/options: osd-shadow is ignored with osd-back-color

options/m_option.c
b56e63e2a9 removed -del for list options but it is still listed in the list structs, which means that it is still tab completed on the CLI like the other actions, and seems to behave like -set. Remove it so it is no longer tab completed.
=> m_option: remove leftovers of del action

demux/demux_playlist.c
In acac614032529997e0a8d89d35a8613b505e04fb, I sort of cargoculted what I had to do for m3u, but it's actually not needed. bstr_split_tok unexpectedly doesn't modify the original string. So the line_dup business in the ini parsing is not needed. Remove it. The part in parse_ref_init isn't wrong but naming the variable "line_dup" instead of "value" is stupid so adjust that. And finally, you can actually force a codepage in mpv (add "+" before the codepage) which will cause every line to be allocated memory including the header lines even though those are obviously valid utf8 that should never need conversion. This wasn't taken into account so add an extra pl_free_line in a couple of places to make sure they are freed.
=> demux_playlist: simplify ini parsing

DOCS/man/input.rst, player/command.c, player/lua/stats.lua
The "Resolution" property shows the storage resolution for videos with non-square pixels.
Currently, display aspect ratio is shown for both "Resolution" and "Output Resolution" properties which results in a duplicate, and is incorrect for the "Resolution" property.
The correct aspect ratio is now shown using the `video-params/sar` and `video-params/sar-name` properties.
Related issues: https://github.com/mpv-player/mpv/issues/9100, https://github.com/mpv-player/mpv/issues/9409
=> stats.lua: fix incorrect storage aspect ratio value

player/loadfile.c
fix secondary sub disappear after sub-reload, sub-remove.
=> player: don't remove all selected sub tracks in mp_dselect_track

meson.build, meson_options.txt, video/out/gpu/hwdec.c, video/out/hwdec/hwdec_ios_gl.m, video/out/hwdec/hwdec_mac_gl.c, video/out/hwdec/hwdec_vt.c, video/out/hwdec/hwdec_vt.h, video/out/hwdec/hwdec_vt_pl.m
Relevant now that #7482 is merged. Also removes some code duplication between the macOS and iOS paths.
=> hwdec: support videotoolbox with libplacebo

video/out/vo_gpu_next.c
If you view a ton of files (like images), the cache can grow to massive sizes and slow down quitting the player to a noticeable amount. Turn the max size down to 10 MiB for now as a workaround until we improve the cache saving later.
=> vo_gpu_next: set max shader cache size back down to 10 MiB

test/meson.build, test/ref/draw_bmp.txt, test/ref/img_formats.txt, test/ref/repack.txt, test/ref/zimg_formats.txt, video/out/hwdec/hwdec_vulkan.c
These tests should really be rewritten to be less stupid so they don't break everytime ffmpeg updates its formats, but that's too much effort right now. Bump the required libavutil version as well.
https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/8e1ef7c38f6906455ae96984d032e57106e11b77
=> test: update ffmpeg format refs

DOCS/man/options.rst
The behavior is also the case for SDL vo, so document it.
=> DOCS: properly document --force-window-position behavior

video/out/vo_sdl.c
It only registers 1 mouse wheel event per 10 physical mouse wheel clicks.
=> vo_sdl: fix broken mouse wheel multiplier

DOCS/man/options.rst, video/out/vo_gpu_next.c
Backwards compatibility wrapper can be bumped once sufficient libplacebo version is a minimum dependency.
See-Also: https://github.com/mpv-player/mpv/pull/12902
Blocked by https://code.videolan.org/videolan/libplacebo/-/merge_requests/626
=> vo_gpu_next: simplify and improve cache code

video/out/vo_gpu_next.c
This avoids limitation of hwdecs number of frames in-flight.
=> vo_gpu_next: reduce number of requested frames from VO

DOCS/interface-changes.rst, DOCS/man/input.rst, player/command.c, player/javascript/defaults.js, player/lua/defaults.lua
If we really want to go through a proper deprecation period, we can, but the manual has stated for a long time that "It's a makeshift solution which could go away any time (for example, when a better solution becomes available)" which is exactly what happened with the `user-data` addition. So I figure just screw it and delete the code.
=> player: remove shared-script-properties property

meson.build
=> meson: unbreak build without X11 and Wayland

audio/out/ao_coreaudio_utils.c
PR #12747 missed updating a variable declaration in `ca_change_physical_format_sync`, which ultimately leads to the thread crashing.  The problem reproduces consistently on AS Macs (I don't have an Intel Mac to test on anymore), and produces stack traces like the following:
```
Thread 3 Crashed:: mpv
0   libsystem_kernel.dylib                     0x18cebd11c __pthread_kill + 8
1   libsystem_pthread.dylib                    0x18cef4cc0 pthread_kill + 288
2   libsystem_c.dylib                          0x18ce04ad4 __abort + 136
3   libsystem_c.dylib                          0x18cdf56c4 __stack_chk_fail + 96
4   mpv                                        0x1026b66d0 ca_change_physical_format_sync + 420
5   mpv                                        0x1026b3b70 init + 1052
6   mpv …
```
=> ao/coreaudio_exclusive: fix segfault when changing formats

input/sdl_gamepad.c
=> sdl_gamepad: add version check for SDL_HINT_JOYSTICK_THREAD

osdep/macos/libmpv_helper.swift, osdep/macos/mpv_helper.swift, osdep/macosx_application.h, osdep/macosx_application.m, osdep/macosx_application_objc.h, video/out/mac/title_bar.swift
the whole things is getting a bit messy. this should probably be refactored in the future, but for now just fix it.
fixes #12518
=> mac: fix libmpv usage without embedding

DOCS/man/options.rst, video/out/mac/common.swift
dumb race condition and some old leftovers from the old cocoa backend.
=> mac: fix a race condition when updating the window title

DOCS/interface-changes.rst, DOCS/man/options.rst, options/options.c, options/options.h, player/command.c, player/misc.c, sub/dec_sub.c
Add --secondary-sub-delay option and decouple --sub-delay from secondary subtitles. This produces desirable behavior in most cases as secondary and primary subtitles tracks tend to be timed independently of one another.
This feature is implemented by turning the sub_delay field in mp_subtitle_opts into an array of 2 floats. From here the track index is either passed around or derived when sub_delay is needed. There are some cases in dec_sub.c where it is possible for dec_sub.order (equivalent to track index) to be -1. In these cases, sub_delay is inferred as 0.
Closes #2629
---
The pull request contains code for the "ideal" solution as far as I'm concerned, but based on the discussion that happened last time in #8954 I doubt it will be merged as is. This time around I'm interested in …
=> options: add secondary-sub-delay

DOCS/man/mpv.rst
I don't know why I thought they did in 7798881360, but single quotes disable escape sequences only in input.conf commands.
=> DOCS/mpv: quotes in mpv.conf don't escape backslash

common/meson.build
fix version determination when building mpv from release tarball extracted within another git repository
=> build: restrict git describe to top level source directory

ci/build-mingw64.sh, ci/build-msys2.sh, meson.build, player/meson.build
This always bothered me, but it will finally be possible to do this in the next meson version. So this is blocked until 1.3.0 comes out and mingw updates to it. Leaving it here so I don't forget about it later.
=> meson: generate .com in the same place as the .exe if possible

ci/build-msys2.sh
=> ci/msys2: don't error out when subprojects dir already exists

meson.build
meson is able to detect blocks of code that are guarded with version checks, but we did that in reverse order and mpv.exe was complaining.
=> meson: move mpv.com target after mpv.exe to avoid meson version warning

ci/build-freebsd.sh, ci/build-mingw64.sh, ci/build-tumbleweed.sh, osdep/meson.build
486bb93dfa90bf948cff8d77ad685f54d0928531 removed the wrap which made these specific options obsolete.
=> ci: remove leftover libplacebo subproject options

player/playloop.c
ca2b05c0fb changed the window size with --force-window and no video tracks to be closer to 16:9, but I don't see why we shouldn't have an actual 16:9 ratio. The advantage is that subtitles with fullscreen and no video tracks will have the same size and position (depending on the values of --sub-scale-with-window and --sub-use-margins) as with 16:9 videos, because there will be no (invisible) black bars.
=> playloop: use a 16:9 ratio with --force-window

video/out/mac/common.swift
an edge case i never tested before.
=> mac: fix initial window size and position when already maximized

options/m_option.c
Apparently we never did this
Fixes #13014
=> m_option: respect pathlist seperator when printing

player/lua/console.lua
This was a simpler fix to not print the console log to the OSD while switching VO.
=> console.lua: simplify the condition to print to the terminal

DOCS/man/console.rst, player/lua/console.lua
A simplified version of the text width estimation code from uosc.
An osd_overlay is created with compute_bounds=true for measuring the width of the lower case alphabet at what's estimated to be the largest font size possible without clipping.
The lower case alphabet was chosen to get decent results for proportional fonts, even if they aren't officially supported.
Before porting this I've checked  the font_hw_ratio for a few monospace fonts, so if this is not wanted we could change the default value to 1.8 (or slightly less) to avoid wrapping for most people.
Font | font_hw_ratio
--- | ---:
3270Medium | 1.8
Menlo | 1.85
Hack | 1.85
Fira Code | 1.9
Monaco | 2.0
monospace | 2.3
Inconsolata | 2.5
=> console: automatically determine the font_hw_ratio

DOCS/man/input.rst, input/cmd.h, player/command.c
Added display width/height to `overlay-add` command to allow overlay to be scaled on display.  Useful when a fullscreen overlay is rendered at a lower resolution than the `osd-width`/`height` for performance reasons.
=> player/command: Added ability to scale overlay.

video/out/x11_common.c
Compose key doesn't function in X11 because `XFilterEvent()` isn't called, and `XNInputStyle` is set to a wrong value. This results in `KeyPress` events for the separate keyboard inputs in the compose key input sequence instead of the composed character, making it impossible to input certain characters which require compose key.
Fix this by calling the required `XFilterEvent()` and set `XNInputStyle` to the correct value.
This makes proper the implementation of the feature introduced in https://github.com/mpv-player/mpv/commit/ad455c43.
=> x11_common: fix compose key handling

player/sub.c
When updating subtitles while paused, mpv waits until a packet is available. However in the case of a network stream, it is possible that mpv will pause itself when buffering for cache reasons. This makes that particular loop do a busy loop and can take a long time depending on network streams. Simply just don't do the loop here if we are paused for cache reasons. Fixes #13077.
cc @sfan5
=> sub: don't busy loop if the player is paused for cache

common/playlist.c, options/parse_commandline.c
When using the --playlist option on the commandline, it would mark all entries on the command as having the playlist-path of the value of that passed option, not just the ones that were expanded from it. Fix this by moving the playlist_populate_playlist_path to the same place where the playlist file gets expanded.
Ref https://github.com/mpv-player/mpv/issues/13075#issuecomment-1852179164
=> playlist: correctly populate playlist-path with the --playlist option

demux/codec_tags.c
Add .jxl as a file extension that maps to an image codec. Note that this will include animated JXL files, but .gif is also on that list so they are not different in that regard
=> demux/codec_tags: add jxl/jpegxl extension mapping to image codecs

video/out/mac/common.swift
tested with the [cocoabasic](https://github.com/mpv-player/mpv-examples/blob/master/libmpv/cocoa/cocoabasic.m) example with:
```
int64_t win;
mpv_get_property(mpv, "window-id", MPV_FORMAT_INT64, &win);
NSWindow *window = (NSWindow *)win;
printf("window height: %f width: %f\n", window.frame.size.height, window.frame.size.width);
---------prints
event: start-file
event: file-loaded
event: video-reconfig
event: video-reconfig
event: playback-restart
window height: 1038.000000 width: 1920.000000
event: video-reconfig
event: end-file
event: video-reconfig
event: idle
```
=> mac: add support for window-id property

DOCS/man/console.rst, player/lua/console.lua
This is useful for completing files and more rarely for profiles. It will also be useful to third-party scripts interacting with the console once the API to do it is merged.
=> console.lua: make completion case-insensitive

player/lua/console.lua
Also inline option-info's sub-properties so we don't have to define sub-properties at the top of the function for every one we decide to complete.
=> console.lua: complete current-tracks sub-properties

player/lua/console.lua
Clear completion suggestions from functions that move the cursor, so that you can't insert suggestions at the wrong spot by pressing Tab again after moving the cursor,
Also clear suggestions from some editing functions that were never updated. It is not actually necessary to clear suggestions from functions that remove text in front of the cursor, but since handle_del() already clears them, let's just clear them everywhere.
=> console.lua: clear the suggestions when you move the cursor

DOCS/man/options.rst, osdep/macOS_swift_bridge.h, osdep/macos/mpv_helper.swift, video/out/mac/view.swift
not sure if we should remove the "(X11, Wayland, Windows and macOS only)" completely since all platforms support it now, though not all backends?
=> mac: add support for drag-and-drop option

filters/f_hwtransfer.c, video/out/hwdec/hwdec_drmprime.c
As a result of the work I did the explicitly check for formats supported by the vo in the f_autoconvert logic, I introduced a regression in the handling of the rpi4_8 and rpi4_10 formats. These require special handling because they only exist in the rpi forks and not upstream ffmpeg, which means they don't have stable pix fmt values that we can use directly.
Previously, we simply didn't declare them as supported, which was ok, as nothing was really enforcing the list of supported formats, but that has changed.
As we still can't simply use the pix fmts, I had to do a slightly ridiculous dance to look them up by name, and if they exist, then register them as supported.
Good times.
=> hwdec_drmprime: try and declare support for weird forked ffmpeg formats

DOCS/man/options.rst
f1c4d20e6577f32018e20efc4ab9da7d4e1ab4ac added this option, but the documentation is actually backwards. --replaygain-clip allows clipping. Having it disabled, the default, prevents it. Keep the behavior the same, but change the documentation to reflect reality. Closes #13111.
=> DOCS/options: fix documentation for replaygain-clip

options/options.c, options/options.h, player/command.c, player/misc.c, player/osd.c, sub/dec_sub.c, sub/sd.h, sub/sd_ass.c, sub/sd_lavc.c
Follow up to some discussion we had in #13073.
=> player: refactor secondary subtitle options and properties 

DOCS/man/input.rst, input/input.c, input/input.h, player/command.c
can be used to emulate precise scrolling from libmpv (and probably other fun things)
test: `keypress Shift+UP 0.2` should seek exactly 1s
=> command: support passing scale to `keypress`

player/lua.c
Even for successful calls, utils.format_json returns nil as the second return value. This doesn't have any purpose and is not documented, and it is inconvenient for passing JSON to script-message, because
mp.commandv('script-message', 'foo', utils.format_json(...))
errors because mp.commandv receives nil as the fourth argument.
This commit makes format_json return only one value in case of success to fix this.
=> lua: don't return a second value from successful format_json

osdep/terminal-unix.c
24270b8587 disabled the cursor while mpv is running, but if you send mpv to the background, it is not re-enabled until you run bg, and not even after that if mpv is paused. Fix this by enabling the cursor from the SIGTSTP handler.
=> terminal-unix: enable the cursor after ctrl+z

DOCS/man/osc.rst, player/lua/osc.lua
Not everyone necessarily wants this feature as it can interfere with whatever they already have the scroll wheel configured to in input.conf. Add an option for this. Fixes #13096.
=> osc: allow disabling special mouse wheel behavior

osdep/mpv.exe.manifest
win32: support long file paths
=> win32: support long file paths

osdep/mpv.exe.manifest
ref: https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests#heaptype
The speed of releasing the demuxer cache has been greatly improved, from more than 10 seconds down to 1 second. (tested on win11 22h2 with `--demuxer-max-bytes=16384MiB`)
=> win32: opt in to the windows segment heap

DOCS/man/options.rst, video/out/cocoa_cb_common.swift, video/out/mac/common.swift, video/out/mac/window.swift, video/out/mac_common.swift
related issue #8379, after that only windows seems to be missing. when merged the mac label can be removed
=> mac: update geometry/autofit opts on runtime

common/av_log.c
After recent change in FFmpeg it is not longer safe to call item_name.
Ref: https://github.com/FFmpeg/FFmpeg/commit/0c6203c97a99f69dbaa6e4011d48c331e1111f5e
=> common/av_log: do not assume AVClass.item_name is always set

DOCS/man/options.rst
- --image-display-duration does not hide the OSC.
- Saying "Setting --image-display-duration" makes no sense because it is not a boolean and it cannot be unset.
=> DOCS/options: fix --image-display-duration's documentation

player/lua/console.lua
Reuse common_prefix_length() to make find_common_prefix() shorter and
faster by not creating many temporary strings.
The decrease in the average time to run find_common_prefix() over 1000
calls I measured is:
set \<Tab>: 1e-4s -> 1e-5s
set s\<Tab>: 1e-5s -> 5e-6s
=> console.lua: refactor find_common_prefix

player/screenshot.c
This allows taking more than 99999 screenshots in a single session, and also for the case when a sequence of 99999 screenshots already exists on the filesystem.
=> screenshot: remove artificial limit on the number of screenshots taken

DOCS/man/options.rst, video/out/w32_common.c
This completes the support for all supported desktop platforms.
Related: https://github.com/mpv-player/mpv/issues/8701, addresses the click through part.
=> win32: add support for --input-cursor-passthrough option

DOCS/man/input.rst, DOCS/man/options.rst
Some places in the manpage uses `.. admonition:: Warning` instead of the specific directive type  `.. warning::` for warning admonitions. This causes the "Warning" text appearing in black color instead of red. Correct them here.
=> DOCS/man: use the correct directive type for "Warning" admonitions

DOCS/man/mpv.rst, DOCS/man/options.rst
The historical info is moved to the documentation of `--stop-screensaver`.
=> DOCS/man: remove "Linux desktop issues" section

player/lua/console.lua
This is commonly done to understand whether a window is focused. This explicitly checks if focused is false instead of unavailable to not break the cursor where focused is unimplemented like on --vo=drm.
The cursor is taller than the input text so it is made transparent instead of completely removing it so that the log doesn't move up and down while toggling focus. Alternatively, cheight = opts.font_size * 8 can be changed to 7.
=> console.lua: hide the cursor when unfocused

DOCS/man/ao.rst
--ao=pipewire has been preferred on Linux for a long time, and this note even makes it sound like alsa is preferred on any system. Just say that the print order is the order in which the drivers are tried so this note won't have to be updated again in the future, like --gpu-context's documentation does.
=> DOCS/ao: change wrong note on which driver is preferred

player/lua/console.lua
Makes Tab expand loadfile ~/ to loadfile /home/$USER/.
I used expand-path instead of os.getenv('HOME') to make it work on Windows.
If there is a ~ before the file command it will be expanded instead, e.g. print-text ~; loadfile ~/, but this shouldn't happen in real-world usage and would need implementing a command parser to fix.
=> console.lua: expand ~/ in file completion

DOCS/man/options.rst, video/out/d3d11/context.c, video/out/d3d11/context.h, video/out/gpu_next/context.c
Currently, libplacebo always tries to reconfigure the d3d11 swapchain to a 10-bit output format because disable_10bit_sdr isn't set to true, even when an 8-bit format is explicitly requested via `--d3d11-output-format`.
Fix this by passing the requested output format preference to libplacebo.
=> vo_gpu_next: respect d3d11 swapchain output format preference

video/out/x11_common.c, video/out/x11_common.h
`Xft.dpi` is much more widely used nowadays by GUI programs compared to the X11 screen DPI.
This is the best we can get for a vendor-neutral scaling preference value under X11 in terms of adoption.
If `Xft.dpi` isn't available, the X11 screen DPI is used as a fallback.
=> x11_common: prefer Xft.dpi for HiDPI scaling

filters/f_lavfi.c
Only when the lavf version is sufficiently new enough to actually have these fields. See:
https://github.com/FFmpeg/FFmpeg/commit/2d555dc82d4ccd3c54c76e2fb3c861a8652de1c6
Fixes #13234
=> f_lavfi: provide color_space and color_range params for lavf

demux/demux_lavf.c
Remove this "hack" from 2017 which disabled `advanced_editlist` while demuxing mov/mp4. See: b7b12c36af96af14b8371d16c5a7f98a7a17915f as well as b86a2316df260de70012fb05dbddf06118b00611
At present, advanced edit list support seems to be mature enough that it doesn't need to be disabled by us and disabling it seems to break more files based on testing with `elist` files in FFmpeg's FATE suite.
Fixes #13252
=> demux_lavf: remove `fix_editlists` hack for mp4

.github/workflows/build.yml, ci/build-msys2.sh
This package isn't available for i686 anymore, and not worth the hassle to only install it for win64 since it isn't particularly useful.
See: https://github.com/msys2/MINGW-packages/commit/fff2fa3711e3cf1c9b65b12784ab3d9428a779f1
=> github/workflows: don't install angleproject on msys2

DOCS/interface-changes.rst, DOCS/man/javascript.rst, DOCS/man/lua.rst, player/javascript/defaults.js, player/lua.c, player/lua/console.lua, player/lua/input.lua, player/lua/meson.build
This lets scripts get textual input from the user using console.lua.
=> scripting: add mp.input

DOCS/man/mpv.rst
This doesn't actually work on either Windows or Linux with --terminal. With --no-terminal or --no-input-terminal the SIGTERM handler is never registered, so it definitely can't work.
Just remove the note about signals because it would be complicated to explain that they don't terminate abruptly only with --terminal and only if that signal has a handler, and it wouldn't be of interest to most users.
=> DOCS/mpv: the playback position is not remembered after poweroff

osdep/terminal-unix.c
This can cause mpv to abruptly quit without following the proper uninit
process when a second `SIGTERM` or `SIGQUIT` is sent and mpv
didn't quit on the first one already. This is because the default action
for these signals is to terminate the program immediately, similar to
`SIGKILL`, and `SA_RESETHAND` resets the `quit_request_sighandler` to
`SIG_DFL` for the default action.
Also keep the `SA_RESETHAND` flag for SIGINT because the current
behavior is to quit after receiving two Ctrl+C no matter what, this is
probably convenient and worth keeping.
This change is because it was too easy to send multiple quit requests
accidentally or before mpv is prepared to handle these signals during
preinit.
An easy way to reproduce is with `timeout 1 mpv [...]` where mpv would
quit abruptly anywhere …
=> terminal-unix: don't set `SA_RESETHAND` for quit request signals

DOCS/man/lua.rst, player/javascript/defaults.js, player/lua/console.lua, player/lua/input.lua
When running the console in the terminal, style log lines with the same escape sequences as msg.c.
This system will be more useful to third party scripts interacting with the console e.g. a script to select a playlist entry can invert the color of the selection.
Also add a missing newline to help's error message.
=> console.lua: style log lines in the terminal

common/msg.c, osdep/terminal-unix.c
Some signal handler related fixes. Also incorporates the `isatty` change from https://github.com/mpv-player/mpv/pull/13224.
=> terminal-unix: signal related fixes

meson.build, test/meson.build, video/out/w32_common.c
The IME was intentionally disabled 8 years ago because it was "not useful for key-bindings". It also broke Alt+Shift language switching. 
Now that text input is an official part of mpv it's time to re-enable it.
Reverts https://github.com/mpv-player/mpv/commit/bf6b981367e45c3f926d3e667bba3f3ed6e9dc37.
Fixes https://github.com/mpv-player/mpv/issues/9168.
Fixes https://github.com/mpv-player/mpv/issues/9168#issuecomment-1748674241.
=> win32: re-enable IME

player/command.c
This is 1 billion times smaller than it should be in SI units.
=> command: fix bitrate unit capitalization

video/out/wayland_common.c
Per xdg-shell protocol specification, it's not illegal for compositor to send negative width and height values. But negative values are nonsense to mpv, and can cause protocol error afterwards, like `xdg_surface::set_window_geometry` which doesn't accept negative values. Treat any negative values as zero (client determines size) for now.
Fixes https://github.com/mpv-player/mpv/issues/13301.
=> wayland_common: guard against negative configure sizes

sub/sd_ass.c
f9cefbfec4 made it so mp_ass_flush_old_events() is continously called on subtitles with unknown duration, without explaining why, breaking sub-seek/step -1 with a VO (the issue does not occur when showing subtitles in the terminal because get_bitmaps() is not called). I don't experience any issue after removing the call, so delete it to fix these commands.
After removing that, you can sub-seek -1 once after regular playback, but not after seeking and thus not multiple times in a row. This is caused by a714f8e928 which fixed subtitles with unknown duration being duplicated when seeking with a VO (it does not happen in the terminal) by clearing old lines on seeks, which broke sub-seek -1 and sub-step -1 in a second way after any seek. The proper fix is to remove the line …
=> sub: fix sub-seek and sub-step -1 with unknown duration subs

TOOLS/lua/autoload.lua
> Quickly going through a directory with too many loadable files causes the autoload tasks to pile up and exiting the player will take forever. Avoid this by skipping loading when playback is aborted.
Not sure if it's the best way to do it but it does speed up exiting when there are too many autoload tasks queued (happens to me when I'm going through a folder with thousands of images).
EDIT:
Related: https://github.com/mpv-player/mpv/issues/12563. I think what @Obegg really meant seems to be the same as what I've described here.
`autoload.lua` can block quitting when it can't catch up with the incoming `start-file` events. Checking the `playback-abort` property ensures at most one autoload task is really executed on quitting and it seems to keep the script's behavior in normal cases. A …
=> TOOLS/lua/autoload: skip loading when playback is aborted

player/lua/osc.lua
When the mouse cursor is hovering over the (CSD) windowcontrols title, the osc keeps displaying, but the cursor autohide isn't disabled like other visible regions.
Fix this by disabling the cursor autohide in this region. All other existing behaviors of the mouse cursor in this region are unchanged, including triggering main window area input and allowing VO dragging.
=> osc: don't autohide mouse cursor when hovering over windowcontrols title

DOCS/man/lua.rst, TOOLS/lua/skip-logo.lua, player/lua/console.lua, player/lua/osc.lua
mp.observe_property('foo', nil, ...) calls the handler 2 times on each playlist change even when the property doesn't change. This is dangerous because if you haven't read observe_property's documentation in a long time this is easy to forget, and you can end up using it for handlers that are computationally expensive or that cause unintended side effects.
Therefore, this commit discourages its use more explicitly in the documentation, and replaces its usages in scripts.
For console.lua, observing focused with type nil leads to calling mp.osd_message('') when changing file while playing in the terminal with the console disabled. I don't notice issues from this, but it's safer to avoid it.
For playlist and track-list this doesn't really matter since they trigger multiple changes on each …
=> scripting: don't observe properties with type nil

video/out/placebo/utils.c
With --really-quiet the message level is -1 which is not in the msg_lev_to_pl_log enum, so handle it explicitly.
=> libplacebo: fix out-of-bounds read with --really-quiet

player/command.c
The lingering cache needs to be cleared so the packets don't stay forever on the screen past their welcome. Do this by simply refreshing the stream. Fixes #13148.
=> player/command: reselect track after UPDATE_SUB_HARD

DOCS/interface-changes.rst, DOCS/man/input.rst, player/command.c, player/lua/stats.lua, video/out/gpu/context.c, video/out/vo.h
This displays the current GPU context when `--vo=gpu` or `--vo=gpu-next` is used, which shows the platform and backend information of the vo which are previously not available.
The name of the GPU context is available as `current-gpu-context` property.
=> stats.lua: display the current GPU context

player/command.c, player/external_files.c, player/external_files.h
If a track's language was guessed from its filename, the commands that reload the track, like sub-reload, remove it. Fix this by calling guess_lang_from_filename() again.
Note that backing up t->lang and restoring it if nt->lang is NULL would work incorrectly when lang is in the stream and it is removed before reloading.
=> command: restore lang after track reload

DOCS/interface-changes.rst, DOCS/man/options.rst, options/options.c, options/options.h, player/osd.c
c62b45ec2ab020dad04a95aff3c85aab631b1f32 adjusted the total remaining time, but not the playback position.
=> player: remove --term-remaining-playtime option

common/msg.c
This prevents mp_msg_flush_status_line() from printing an unnecessary newline when changing file after setting --really-quiet at runtime. If mpv is backgrounded, this newline garbles the output of TUI programs.
With this change the cursor is not re-enabled after setting --really-quiet at runtime and quitting with mpv in the foreground, so enable it on uninit.
=> msg: reset status_lines when setting --really-quiet

video/out/w32_common.c
Fixes https://github.com/mpv-player/mpv/issues/13327.
=> win32: stop waiting for messages if the window is destroyed

DOCS/man/options.rst, options/options.c, options/options.h, sub/sd_lavc.c
We have `--vd-lavc-o` and `--ad-lavc-o`, but no equivalent option for
subtitles.
=> sub: add `--sub-lavc-o` option

DOCS/interface-changes.rst, DOCS/man/options.rst, DOCS/mplayer-changes.rst, TOOLS/lua/autodeint.lua, filters/f_auto_filters.c
I don't actually deinterlace ever but allegedly this is better than yadif, and there's no real reason to not have this be the fallback deinterlace when we're not using hw frames. Also change various mentions of yadif to bwdif. Ref #12835.
=> [RFC] f_auto_filters: change fallback deinterlace to bwdif

etc/mpv.bash-completion
Parse and cache the options lazily not to impact the shell startup time.
=> bash-completion: parse the mpv options lazily

player/video.c
This reverts commit cb2b579f61764452652c6cf5c6a94ae5e67c77ed.
This breaks files where the audio starts much later after the video since mpv reads the first audio packet even if it isn't supposed to start yet, resulting in the audio_status being STATUS_READY for the entire time mpv is "waiting" for the first audio packet to be played.
=> Revert "player/video: loosen logic checks for adjust_sync"

DOCS/man/osc.rst, player/lua/osc.lua
This allows the title shown with the windowcontrols to be controlled separately from the normal osc title. Fixes #13295.
=> osc: add osc-windowcontrols_title option

filters/f_auto_filters.c
Followup to 45f822593f14d78fa22e74fa4e725a3ffd6f713c. vulkan hwdec uses bwdif_vulkan so no reason to not make cuda also match.
=> f_auto_filters: use bwdif_cuda for deinterlacing with cuda hwdec

player/command.c
This avoids dropping the entire cache when vo is changed but tracks stay the same. Only tested on Android.
On Android, the only time that the vo is switched is when you turn off the screen or background the app. In this case, I think that a refresh seek isn't necessary, which is why I changed this line.
It is more of a *hack* than a *fix*, I would be thankful for some feedback on how to make this work on other platforms where you might switch the vo in different contexts.
=> command: do a normal seek instead of a refresh seek when switching vo

player/video.c
This workarounds the issue with vo_g that would freeze in certain condition. I haven't go deep inside to understand why, so this should be considered as a workaround.
Fixes: #13256
=> player/video: force vo reconfigure on color parameters change

audio/decode/ad_spdif.c
There is an issue with the DTS passthrough playback of 44.1khz content. With the current implementation, every DTS core content (regardless of sample rate) is passed to the AVR in a 2ch@48Khz manner. This is only fine for 48Khz and 24/96 content, but not for 44.1khz content, that could be found on some DVD-Audio discs. In this case, this leads to mangled audio or no audio at all.
This commit fixes the issue. The issue is also described here:
https://github.com/mpv-player/mpv/issues/12078
https://github.com/mpv-player/mpv/issues/6651
The fix also takes into account that there are some DTS variants with a samplerate of 96khz (e.g. DTS 24/96), somehow they are recognized wrongly as 48khz by the code. Don´t rely on this "bug", do it correctly. Now every DTS core samplerate above 44.1Khz is …
=> ad_spdif: fix DTS 44.1khz passthrough playback

player/video.c, video/out/vo.h
32-bit signed integer can hold ~2.1s stored as nanoseconds. While frame duration doesn't make sense to be this long, the existing clamp is to 10s. Change type to double, which is consistent with other fields in vo_frame.
=> vo: change vo_frame duration to double

common/version.h.in
Copyright year update speed ranking to fill PR space:
2020: wm4 committed 2019/12/31 11:10 (https://github.com/mpv-player/mpv/commit/934f8e102682901d77e0990aa594f46d745e0396)
2014: wm4 committed 2013/12/31 18:00 (https://github.com/mpv-player/mpv/commit/66fe4f571371b06b84c9e9cd684df9f7fc90b53f)
2015: wm4 committed 2014/12/31 18:00 (https://github.com/mpv-player/mpv/commit/39548ad9e961794e023aef0e281089064dd41f36)
2016: wm4 committed 2015/12/31 18:18 (https://github.com/mpv-player/mpv/commit/de0523ba7b4f76a1c51cc3924b3fcace51fc8e16)
2017: wm4 committed 2017/01/01 13:09 (https://github.com/mpv-player/mpv/commit/8e41f314f19d97849204ff4a7e9ca0fc4e9a8904)
2018: wm4 authored and wiiaboo committed 2018/01/01 16:05 (https://github.com/mpv-player/mpv/commit/a90abe05462a689e55280bc78af2999aa1f3823e) …
=> version.h.in: bump copyright year

video/out/hwdec/dmabuf_interop_gl.c, video/out/hwdec/hwdec_drmprime.c
This PR allows mpv to accept AV_PIX_FMT_P010 and AV_PIX_FMT_P210 thorugh EGL.
Tested with rockchip rk3588 and https://github.com/nyanmisaka/ffmpeg-rockchip, since currently no V4L interface supports proper 10bit formats.
Full documentation is here: https://github.com/hbiyik/ffmpeg-rockchip/wiki/Rendering#mpv
=> 10bit formats with EGL hwdec_drmprime

DOCS/man/options.rst, meson.build, osdep/io.c, osdep/io.h, stream/stream.c, stream/stream.h, video/out/vo_gpu_next.c
Not sure why my #12907 got closed and I don't see a way to reopen it anymore. So let's make another one.
Save the cache to separate files to avoid loading/saving a huge combined libplacebo.cache. This approach allows the saving of only new cache objects and avoids resaving the entire cache, especially even if only a tiny change was made.
This commit improves the cold start time of mpv and avoids saving data when it's not necessary.
Number of changes were made:
- each cached object is saved in its own file
- cache files are prefixed with the name of cached object
- cache directory is cleaned on each uninit 
- the least recently used cache files are removed if cumulative cache size is above limit 
- files used in the recent 24 hours are not removed to allow changes to mpv.conf without …
=> vo_gpu_next: save cache to separate files

video/out/wayland_common.c
left_ptr is apparently a legacy name. The correct name per the spec is default*. Fixes #13376
*: https://github.com/swaywm/sway/commit/974a8629a8f0f403028332543e4bd31d98f611c1
=> wayland: use "default" cursor instead of "left_ptr"

DOCS/man/options.rst, video/out/x11_common.c
Some X11 window managers support controlling the title bar independently from other window decorations with `_MOTIF_WM_HINTS`. This allows hiding the title bar while keeping other decorations like the resizing borders.
Let mpv respect the `--title-bar` option on X11 so `--no-title-bar` can hide the title bar only like on win32.
=> x11_common: support `--title-bar`

video/out/wayland_common.c, video/out/wayland_common.h
Commit f54ad8eb055771a080f079964504cb0f32fc4014 broke high resolution scrolling because one logical mouse click is generated for every scroll event, no matter the magnitude. This makes scrolling on trackpad way too fast.
Revert the axis scaling change in that commit and clamp the resulting value between -1 and 1 to make sure mouse wheel scrolling works as intended on compositors which send a value larger than 10 for these events.
=> wayland_common: properly handle high resolution scrolling

DOCS/interface-changes.rst, DOCS/man/input.rst, input/input.c, input/input.h, player/command.c, player/lua/auto_profiles.lua
This adds the commands `load-config-file` and `load-input-conf`. They can be used to auto reload configuration files, e.g. in vim:
```vim
autocmd BufWritePost ~/.config/mpv/mpv.conf silent !echo load-config-file %:p | socat - /tmp/mpvsocket
autocmd BufWritePost ~/.config/mpv/input.conf silent !echo load-input-conf %:p | socat - /tmp/mpvsocket
```
Partially fixes #6362. This is simpler than spawning a thread to observe changes to these files with inotify and doing the equivalent on each platform, but it relies on users configuring their text editor.
=> command: add `load-config-file` and `load-input-conf`

.github/workflows/comment.yml
There is an upstream regression in v7. Use v6 until Node 16 is still available.
See: https://github.com/actions/github-script/issues/448
=> github/workflows: revert to github-script@v6

options/m_option.h, player/command.c, video/csputils.c, video/out/gpu/video.c, video/out/vo.c, video/out/vo.h
When adding things like brightness or gamma, the video obviously needs a redraw if paused. This happened to work in the normal case because the OSD notification triggered a redraw, but if you use no-osd the picture won't change. Fix this by adding another option flag, UPDATE_VIDEO, and simplying calling vo_redraw. That way something like "no-osd add gamma 1" actually works.
=> player: ensure runtime updates of certain rendering options

audio/out/buffer.c
As mentioned in [0] the suffix "_locked" would have been the appropriate naming in line with similar uses inside mpv.
See `mp_abort_recheck_locked()`, `mp_abort_trigger_locked()`, `retrigger_locked()`, `wakeup_locked()`...
[0] https://github.com/mpv-player/mpv/pull/12811#discussion_r1477518525
=> audio: rename ao_read_data_unlocked

.github/workflows/build.yml
Exclude more files not participating in the build process, including `README.md`, to achieve the original goal of preventing artifacts comment spam.
=> github/workflows: ignore more files from build workflow

filters/f_output_chain.c
Fixes https://github.com/mpv-player/mpv/issues/13432.
memcheck log showing the location of the first free:
```
==15178== Thread 1 mpv:
==15178== Invalid read of size 8
==15178==    at 0x3FBFE3: free_obj_settings_list (m_option.c:2978)
==15178==    by 0x3D1AA8: m_option_free (m_option.h:554)
==15178==    by 0x3D2844: destroy_user (f_output_chain.c:226)
==15178==    by 0x3DA1A2: filter_destructor (filter.c:756)
==15178==    by 0x4AEAB2: ta_free (ta.c:242)
==15178==    by 0x3DA140: mp_filter_free_children (filter.c:747)
==15178==    by 0x3DA1AE: filter_destructor (filter.c:759)
==15178==    by 0x4AEAB2: ta_free (ta.c:242)
==15178==    by 0x43A139: vo_chain_uninit (video.c:152)
==15178==    by 0x43A183: uninit_video_chain (video.c:161)
==15178==    by 0x43A6DD: reinit_video_chain_src …
```
=> f_output_chain: prevent double free of child filters

player/lua/console.lua
Move common_prefix_length() and related functions before the first call to common_prefix_length(). It works now because it's global but if we ever make all functions local for consistency it will stop working.
=> console.lua: move functions to strip common characters

demux/demux_mkv.c
Some files, especially with quite a few audio tracks have video blocks further away, which made them false detected as still images.
Fixes: 26a5146
=> demux_mkv: increase probing size for still image

video/out/wayland_common.c
When the mpv surface leaves the output, we no longer mark it as the current output. However, this implicitly depends on there being a preceding surface entrance event to a different output. This is not necessarily the case. Consider moving the window from monitor 1, to monitor 1-2, and then back to 1 again. mpv gets the entrance event to monitor 2 and sets that as the current output to work off of. Then when you move back to only monitor 1, it removes monitor 2 from the current output. However, monitor 1 is not updated again as the current output because there is not a new surface entrance event in this case (the window never left). So the numbers that mpv's core is using are incorrect and for the wrong monitor. Luckily, we already keep track of what outputs the mpv surface is currently …
=> wayland: set current_output on surface leave if applicable

demux/demux_mkv.c
mp1 currently isn't recognized in matroska despite being supported, adding the tag enables playback. Fixes: #9533
=> demux_mkv: add tags for A_MPEG/L1(mp1) audio

demux/demux.c, demux/stheader.h
Clarify that ffmpeg sets AV_DISPOSITION_STILL_IMAGE for sparse videos like https://s3.amazonaws.com/tmm1/music-choice.ts, not for images.
=> demux: clarify the meaning of still_image

video/out/wayland_common.c
Since 1f8013ff3f, if you release a modifier before a regular key on Wayland, that key gets pressed again because keyboard_handle_modifiers() calls mp_input_put_key() regardless of whether a modifier is pressed or released, e.g. if you press Shift+s it easy to take an another screenshot with s by accident. Fix this by releasing keys when releasing modifiers, matching the other VOs' behavior.
Ideally, releasing the modifier should input the key alone after --input-ar-delay, while this patch disables it forever, e.g. on X11 if you type something in the console, hold Ctrl+h, and release Ctrl, it starts typing h instead of deleting characters. This doesn't work because keyboard_handle_key() is only called when you first press a key, while on X11 KeyPress keeps getting sent as you hold down the …
=> wayland: don't press keys again when releasing modifiers

demux/codec_tags.c, misc/rendezvous.c, osdep/subprocess-win.c, video/out/filter_kernels.c, video/out/gpu/error_diffusion.c, video/out/gpu/video_shaders.c, video/out/w32_common.c
Replace various dead links with live replacements or archives. Less friction for anyone who wants to look up these references.
=> various: replace dead links in comments

osdep/subprocess-posix.c
Note: I'm not 100% sure how this happens but I have a local reproducer with wl-copy and the fix definitely works.
=> osdep: fix infinite loop when cancelling subprocess

README.md, meson.build
This will prevent building demos and link statically with libplacebo by default if system libplacebo is not found.
@sfan5
=> meson: set default options for libplacebo if using subproject

player/video.c, video/out/vo.c, video/out/vo.h
This avoids clearing the queued frame and the currently displayed one on VO reconfiguration requests that happen when new frames arrive. Instead, let those frames be fully displayed.
Fixes mf:// playback issues introduced after commit ef11d31c3acfd71307a94e44ad164a4861287675.
We have to wait on the play loop thread; otherwise, the VO thread can be starved because no one would wake it up after the last frame is fully displayed. VO keeps track of queued frames and the current one, but what we care about is the actual on-screen display duration. In this case, VO is already sleeping because the frame is already rendered. Hence, we cannot return from the write_video function and expect the already sleeping VO thread to wake the playback thread and ask for new frames. This issue has been fixed …
=> player/video: wait for the frames to be fully displayed before reconfig

DOCS/man/options.rst, demux/packet.h, player/core.h, player/playloop.c, player/sub.c, sub/dec_sub.c, sub/dec_sub.h, sub/sd_ass.c, sub/sd_lavc.c, video/out/vo_gpu_next.c
mpv is currently very wasteful when drawing subs when they're being drawn to the terminal or being drawn ontop of a still image. It actually runs on every single loop which spams VOs with tons of completely unneeded redraw calls. We can be smarter here and detect when the subtitle actually changes and signal the redraw only when it's needed instead.
=> player/sub: avoid wasteful sub redraws

demux/demux_mkv.c, options/m_option.c
It is possible to have data with empty block that contains additions. In which case the block would not be added and the additions would leak.
Found by fuzzing.
=> demux_mkv: fix few issues found during developing fuzzers

DOCS/man/lua.rst
The current documentation lacks clarity regarding the interaction between the `repeatable` and `complex` options. Through an analysis of the source code ([`player/lua/defaults.lua`](https://github.com/mpv-player/mpv/blob/master/player/lua/defaults.lua#L224) and
[`player/js/defaults.js`](https://github.com/mpv-player/mpv/blob/master/player/javascript/defaults.js#L325)), it was observed that the `repeatable` option is only meaningful when the `complex` option is not enabled. Additionally, the `complex` option in the existing documentation is confusing, actually `fn` can be called on key repeat when `complex` is `true` and `repeatable` is not `true`.
1. Clarified that the `repeatable` option only applies when the complex option is not set to `true`.
2. Revised the description of the …
=> DOCS/lua: clarify `repeatable` and `complex` for `add_key_binding`

DOCS/interface-changes.rst, DOCS/man/options.rst, input/input.c
Fixes https://github.com/mpv-player/mpv/issues/11175.
Fixes https://github.com/mpv-player/mpv/issues/11851. Note that while the issue was poorly conveyed, the concern of the preprocessing causing input delay is valid. See the description of the second undesirable behavior in the commit message for details.
=> input: add `--input-preprocess-wheel` option 

osdep/threads-posix.h
In OpenBSD the compilation fail because `osdep/threads-posix.h` need include `pthread_np.h `
This change fix the issue.
```
[3/199] Compiling C object libmpv.so.2.2.0.p/audio_out_ao_lavc.c.o
FAILED: libmpv.so.2.2.0.p/audio_out_ao_lavc.c.o
/usr/local/llvm16/bin/../libexec/ccc-analyzer -Ilibmpv.so.2.2.0.p -I. -I.. -Icommon -
Ietc -Iplayer/javascript -Iplayer/lua -Isub -I/usr/local/include -I/usr/X11R6/include
-I/usr/local/include/harfbuzz -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.
0/include -I/usr/local/include/fribidi -I/usr/X11R6/include/freetype2 -I/usr/local/in
clude/libxml2 -I/usr/local/include/lua-5.1 -I/usr/X11R6/include/libdrm -fvisibility=h
idden -fdiagnostics-color=always -Wall -Winvalid-pch -std=c11 -O2 -g -D_FILE_OFFSET_B
ITS=64 -Werror=implicit-function-declaration …
```
=> Fix headers for OpenBSD compilation

video/out/vo_gpu_next.c
Previously, libplacebo would fail to render the image since mpv was feeding it bogus bitmaps with 0 width/height. An easy way to encounter this would be to set sub-scale to 0 with bitmap/image subs.
=> vo_gpu_next: don't add 0 width/height sub bitmaps to pl_overlay

DOCS/man/input.rst
On wayland, depending on the wl_output protocol version used, the display-names property can have different values. Mention this in the documentation, like for other platforms.
=> DOCS/man: add description of display-names property for wayland

video/out/d3d11/context.c, video/out/opengl/context_win.c, video/out/vulkan/context_win.c, video/out/w32_common.c, video/out/w32_common.h
This adds support for `--alpha=yes` for `--gpu-api=d3d11` (with `--d3d11-flip=no`) and `--gpu-api=opengl` on win32.
=> win32: support `--alpha=yes`

.github/workflows/build.yml
Homebrew finally pulled the plug on lua 5.1, and it is no more. So we have to change to a different lua package and the only other choice is luajit (no 5.2 in homebrew). We used to use luajit for the ci, but 649556b2b65207c0d40751fae941223978b04932 switched it to lua 5.1. As explained there, luajit 2.0 was horribly bugged and not usuable for mpv and the build had to do dumb hacks to work around it. I expected 5.1 to last a bit longer than a couple of years, but luckily it seems like luajit in homebrew now pulls a luajit 2.1 version (some rolling release thing or however upstream works). The details don't really matter for us since 2.1 does not have all the awful issues that 2.0 used to have. So just switch to luajit again.
=> github/workflows: switch back to luajit for macos

video/out/cocoa_cb_common.swift, video/out/mac/gl_layer.swift
i could never reproduce this issue so i can't really confirm it fixed. though thanks to @low-batt thorough investigation on #11681 and https://github.com/iina/iina/pull/3581 the fix is rather obvious.
=> cocoa-cb: lock CGLContext on uninit and manual redraw

audio/filter/af_lavcac3enc.c, common/encode_lavc.c
See: https://github.com/FFmpeg/FFmpeg/commit/1cc24d749569a42510399a29b034f7a77bdec34e
=> af_lavcac3enc: don't use deprecated `avcodec_close`

DOCS/client-api-changes.rst, libmpv/client.h, video/out/vo.c, video/out/vo_libmpv.c
~this basically reverts commit 7b5a258. this was done for macOS since the only working vo was cocoa-cb (libmpv) and it would otherwise always use the deprecated opengl cocoa backend.~
~we now have a working vulkan gpu/gpu-next backend on macOS which should be the new default vo. vo=libmpv has to be explicitly set now to use cocoa-cb.~
@Dudemanguy @jeeb 
i am not sure if it's a problem that libmpv won't be used as a fallback like this and `vo=libmpv` has to be explicitly set to use it? we will probably get a few issues in the future when mpv is not build with vulkan support and without moltenvk, since it won't playback anything even if cocoa-cb is included in the build.
also should this probing check be reverted too, i am not sure what exactly it is for? …
=> vo: move libmpv back to the bottom in the auto-probing order

DOCS/man/mpv.rst, etc/input.conf
There are good reasons to bind `Ctrl+WHEEL_UP/WHEEL_DOWN` to `video-zoom`:
- They are ubiquitous and familiar key bindings to represent zooming operations, which are used in all popular web browsers, document viewers, and document editors.
- Because `WHEEL_UP/WHEEL_DOWN` are scaled with high-resolution scrolling input devices like touchpads, this allows smooth zooming.
- This makes "pinch to zoom" with touchpads and touchscreens work out of box on Windows, since by default applications receive these key inputs for pinch gesture.
- It had been considered to bind these keys to `window-scale` instead. However, this results in horrible UX as the keybinds work only when the mouse pointer is over the mpv window, and if the window shrinks during this operation, the window below mpv now receives …
=> input.conf: bind `Ctrl+WHEEL_UP/DOWN` to `video-zoom`

video/out/x11_common.c, video/out/x11_common.h
Begin the `_NET_WM_MOVERESIZE` window dragging in `ButtonPress` event to match the behavior of win32 and wayland, simplify logic by dropping the `win_drag_button1_down` hack required by the old method, and fix a race condition described in commit 19f101db680f966a6e56035a16784541be390982, which happens when moving the mouse and releasing the button at the same time.
The race condition can be easily triggered when using a touch screen (tested with libinput driver), where a tap is translated to `MotionNotify`, `ButtonPress`, `MotionNotify`, and `ButtonRelease` in sequence, with the last 2 events having the same timestamp. This has caused some window managers to not stop dragging after the `ButtonRelease`, resulting in window being stuck in dragging state after a single tap.
=> x11_common: handle window dragging in ButtonPress event

osdep/io.c
`fopen()` with 'x' mode is a non-portable glibc extension, is currently unused, and should not be used in order to maintain POSIX compatibility. Thus there is no need for the Windows wrapper `mp_fopen()` to support it.
=> osdep/io: ignore 'x' mode for mp_fopen

player/command.c, sub/sd.h
commit 1: command: don't add SUB_SEEK_OFFSET twice with sub-seek
The name SD_CTRL_SUB_STEP is misleading, but it is also used for sub-seek, and sub/sd_ass.c already adds SUB_SEEK_OFFSET with it.
commit 2: command: fix sub-seek while paused without a video
When using sub-seek without a video track while paused, adding the 0.01 SUB_SEEK_OFFSET to the new timestamp is not enough to show the new subtitle line. Add 0.1 instead to fix it. 0.01 is already enough for sub-step.
=> fix sub-seek without a video

.github/workflows/build.yml
- Use hardware accelerated virtualization on Linux runners
- Update to FreeBSD 14.0
=> github/workflows: update cross-platform-actions to v0.23.0

player/configfiles.c
With --ignore-path-in-watch-later-config, --write-filename-in-watch-later-config still writes the absolute path of files in the comment, even though the hash is calculated from the basename. Make it write the basename to avoid confusion.
Also stop writing redirect entries for parent directories with --ignore-path-in-watch-later-config, both because it's redundant, and because with this patch it would write the basename of directories in the comment, which would be wrong because their hashes are calculated from the absolute paths.
=> player: fix watch later config comments when ignoring path 

audio/out/ao_wasapi.c, audio/out/ao_wasapi.h
This is also meant to fix #12615 but with more conservative changes to hopefully have an earlier merge into upstream (I know it's bad manner and practice, but the issue has been bugging me for quite some time 🥲, and it is actually very easily triggered). Different from #13434, the buffer space checks using `IAudioClient_GetCurrentPadding` and logic for resolving cascading buffer underruns are kept in case there are older Windows versions that behave differently.
To test, add for example the following key binding:
```
v set ao-volume 50
```
Press `v` while in playback with `--ao=wasapi` and `--audio-exclusive=yes` and notice the glitches and slowly accumulating A/V desync without this patch.
=> ao_wasapi: address premature buffer fills in exclusive mode

video/out/gpu/video.c
This should have been done from the start but the previous fix happened to work when the video output doesn't have vertical black bars.
=> vo_gpu: use fbo texture height for fragment coordinate calculation

DOCS/interface-changes.rst, DOCS/man/options.rst, options/options.c, player/command.c, video/out/w32_common.c, video/out/wayland_common.c, video/out/x11_common.c
Follow up to #13470.
Apparently wayland behaves differently here than other backends, but I would argue it's better and more intuitive so I made x11 and win32 (untested) match it. I don't know how macOS works but I would guess it needs to be changed to be brought in line the changes in this PR (cc @Akemi).
So to sum it up:
1. The DPI scale factor should not be taken into account when setting the window scale. It is unintuitive and adds extra complexity for no benefit. When a user sets a window scale to 1, they reasonably expect the scale to actually be 1. Not 1 multiplied by some other random number. This was mentioned in #9437 and I agree with the user.
2. The DPI scale still needs to be accurately reported to the `display-hidpi-scale` property regardless of the value of …
=> [RFC] hidpi-window-scale changes

ci/lint-commit-msg.py
1. Explicitly add typing to lint_rules
2. Fix return type for get_commit_range()
3. Fix no-return path with get_commit_range()
=> ci: fix typing in lint-commit-msg.py

sub/sd_ass.c
LRC subtitles can have lines with multiple timestamps, e.g.
[00:00.00][00:02.00]foo
[00:01.00]bar
Currently mpv shows only the "foo" that was decoded first, because it compares the packet file position to check if a packet was already seen, and it is the same for both occurrences of "foo". Fix this by also comparing the pts.
This keeps comparing the packet position on top of the pts to not break subtitle lines with the same timestamp, like:
1
00:00:00,000 --> 00:00:01,000
foo
2
00:00:00,000 --> 00:00:01,000
bar
where mpv shows both lines on top of each other. They are common in ASS subtitles.
Fixes https://github.com/mpv-player/mpv/issues/13497.
=> sub: fix LRC lines with multiple timestamps

osdep/io.c, osdep/io.h
`unlink()` was never wrapped in win32, so all usages of it were referring the ANSI version of the function. This doesn't work properly for Windows versions before 1903 (where the UTF-8 codepage is requested).
Fix this by adding `mp_unlink()` which wraps over `_wunlink()`.
=> osdep/io: add `mp_unlink()`

audio/out/ao.c
Fixes https://github.com/mpv-player/mpv/issues/13538.
=> ao: don't clip floating point formats at non-unity gain

ci/build-mingw64.sh
No longer needed after commit:
https://github.com/FFmpeg/FFmpeg/commit/e06ce6d2b45edac4a2df04f304e18d4727417d24
This reverts commit 09606b9db9e228ac80cadb5fd7875ad60c9bd178.
=> Revert "ci/mingw: pin Vulkan version again"

player/main.c
98a27b3cd1e6af743af67699318df1946ce5bf8f changed this to mpv but that's kind of pointless since the binary is already named mpv so that will be the default thread name. Evidently, people rename/symlink the binary to something else so might as well make them happier. Fixes #13469.
=> player/main: don't set the main thread name

video/out/vo_gpu_next.c
Fixes 84015959cc5d36d8973b2f07ece066902bbbdbe7
=> vo_gpu_next: fix win32 io wrap

DOCS/man/options.rst
Just a couple of consistency changes to the `--scale` documentation in the manual. The formatting and rewording changes are self-explanatory but there's also an expanded description for `mitchell`, because it was almost spline36-levels of useless.
- Define the radius value. The `hermite` example mentions that having a support of radius=1 is special, but why? The reader needs a point of comparison to actually see how hermite is different from other BC-splines.
- Define (B,C) values. `bicubic`, `hermite` and `catmull_rom` have their (B,C) values defined, so the omission here is a bit weird.
- Define the use-case. `mitchell` is generally referred to as a "[satisfactory compromise](https://www.cs.utexas.edu/~fussell/courses/cs384g-fall2013/lectures/mitchell/Mitchell.pdf)" or an …
=> DOCS/options: make --scale documentation more consistent

DOCS/man/options.rst, options/options.c, sub/osd_libass.c
Make the OSD bar markers bigger so we can default to a smaller, better-looking border size, without sacrificing markers' visibility.
=> osd_libass: update the OSD bar's dent and border size

DOCS/interface-changes.rst, DOCS/man/options.rst, video/out/gpu/video.c, video/out/gpu/video.h, video/out/gpu_next/context.c, video/out/vo_gpu.c, video/out/vo_gpu_next.c
A spiritual successor to #9621 but it also implements vo_gpu_next support. This depends on this libplacebo [MR](https://code.videolan.org/videolan/libplacebo/-/merge_requests/640).
This splits `--alpha` into two options: `--alpha` and `--blend`. `alpha` strictly controls whether or not draw the framebuffer with the alpha component if possible (default yes). `blend` is what controls blending the alpha component into either tiles, the background color, or nothing. This makes it possible to blend with a partially transparent background color e.g. something like `mpv --background=0.5/0.5 --blend=background image.png`.
TODO:
Edit: Nevermind. The alpha component in `--background` is bugged in `vo_gpu` period. `--background=0.5/0.0` is not fully transparent and has a light grayish color for …
=> vo_gpu/vo_gpu_next: overhaul alpha related options

DOCS/man/options.rst, player/lua/console.lua, player/lua/stats.lua
When `--osd-blur` is set to a nonzero value, the graphs also become blurry. This is because they are rendered by the `osd-overlay` command with the "OSD" style which has OSD blur applied, and are treated no differently from texts. Fix this by using the "Default" style for these graphs which uses the default OSD options.
=> stats.lua: fix blurry graphs when `--osd-blur` is set

osdep/macosx_application.m, osdep/macosx_application_objc.h, osdep/macosx_events.h, osdep/macosx_events.m, video/out/vo_libmpv.c
this is something that bothered me for a long time and i think this is an even bigger problem than before all the moltenvk changes, the added support of a vulkan backend on macOS and making gpu(-next) the default vo on macOS again. back when cocoa-cb was added it was decided against properly initialising cocoa-cb on demand because mac dependent code should be kept out of libmpv. so we were stuck with a suboptimal solution.
cocoa-cb was always pre-allocated in the Application itself because libmpv needs to be set up before usage, an opengl context has to be set and because it was decided mac specific code should be kept out of libmpv.
this means that a completely working libmpv and opengl renderer was set up even if it wasn't used. leading to unnecessary log message, resources being used …
=> cocoa-cb: remove pre-allocation and initialise only when used

video/out/mac_common.swift
this logic was copied from the cocoa-cb opengl backend, since it was assumed both layers work similar. apparently they don't and a nil value on the metal layer means use the display colour profile, while on the opengl layer it means undefined behaviour.
this also fixes a problem with the target-colorspace-hint option, since moltenvk needs to set this colour space itself for a proper hint. both mechanism would compete to set the colour space.
=> mac: remove unnecessary metal layer colour space update

osdep/macosx_application.m, osdep/macosx_events.m
the swift obj-c bridging header is only included when cocoa-cb is enabled. cocoa-cb is not the only swift feature anymore and disabling cocoa-cb leads to a runtime error that specific swift classes could not be found.
include the swift obj-c bridging header in the case swift features are enabled.
=> build: fix build when disabling cocoa-cb

sub/sd_ass.c
An ass event like `{\p1\pos{1,1}}m 0 0 l -3 -7 l 11 -7 l 11 -2` ends the drawing mode started with `\p1` due to `\pos` gets confused with `\p`, and thus that line is wrongly considered to be visible text.
Fixes https://github.com/christoph-heinrich/mpv-subtitle-lines/issues/5
=> sd_ass: don't wrongly recognize \pos as \p

options/m_option.c, options/m_option.h, video/out/drm_common.c, video/out/gpu/context.c, video/out/gpu/d3d11_helpers.h, video/out/gpu/hwdec.h, video/out/gpu/lcms.c, video/out/gpu/video.c, video/out/vulkan/context.c, video/vaapi.c
The opt validator functions are casted to generic validator, which has erased type for value. Calling function by pointer of different definition is an UB.
Avoid that by generating wrapper function that does proper argument type conversion and calls validator function.
Fixes UBSAN failures on Clang 17, which enabled fsanitize=function by default.
=> various: avoid function pointer casts

video/out/vulkan/common.h, video/out/vulkan/context_mac.m
i totally forgot about this after the initial PR was just sitting there for an eternity.
=> mac/vulkan: remove old deprecated VK_MVK_macos_surface extension remains

TOOLS/dylib_unhell.py
=> osxbundle: fix bundling when homebrew is not installed

video/out/mac/common.swift, video/out/mac/view.swift
from the moltenvk docs. imo kinda dumb that this is 'needed', since the layer delegate functions are on the view now, even if not used. though if they ever need to be used there is no clear distinction between view and layer functionality because of this.
> When creating a CAMetalLayer to underpin the Vulkan surface to render to, it is strongly recommended that you ensure the delegate of the CAMetalLayer is the NSView/UIView in which the layer is contained, to ensure correct and optimized Vulkan swapchain and refresh timing behavior across multiple display screens that might have different properties.
=> mac/vulkan: set NSView as layer delegate like recommended by MoltenVK

video/out/mac/gl_layer.swift
lets see how this pans out. Apple changed a lot regarding layer handling and opengl. a lot of the issues got fixed a lot of new issues occurred. i couldn't reproduce any of the issues anymore that were fixed with the dedicated render queue, though can reproduce the new issues that we have.
related old commit 965ba23303d980c239e2b0191488766cfa7b0f75
=> cocoa-cb: render on main queue instead of dedicated queue

DOCS/interface-changes.rst, DOCS/man/input.rst, input/input.c, player/command.c, video/out/vo.h, video/out/w32_common.c, video/out/wayland_common.c, video/out/wayland_common.h, video/out/x11_common.c, video/out/x11_common.h
This removes all hardcoded VO dragging logic in win32, x11, and wayland, and handle them centrally in the input system, which now issues the new `begin-vo-dragging` command to start VO dragging for VOs which implement `VOCTRL_BEGIN_DRAGGING`.
The new command also allows scripts to initialize VO dragging with other mouse buttons.
Because the VO dragging is now centralized, it's possible to make further improvements, such as a deadzone mechanism to fix the conflict with `MBTN_LEFT` mouse bind.
Fixes https://github.com/mpv-player/mpv/pull/13457#issuecomment-1965068837.
=> centralize VO dragging

demux/demux_lavf.c
avif files will commonly be probed as "mov,mp4,m4a,3gp,3g2,mj2" by ffmpeg, but demux_lavf currently has some logic to skip avformat_find_stream_info for these kinds of files. It was introduced in 6f8c953042a7a964686e5923f5c61025ef6b842e. Presumably, the optimization of mentioned in that commit is still valid however for avif we specifically need to do the avformat_find_stream_info call. Without it, several codec proprieties like width, height, etc. are unavailable. So just check the extension type and disable the skipinfo optimization.
=> demux_lavf: always find stream info for avif files

DOCS/interface-changes.rst, DOCS/man/options.rst, filters/f_auto_filters.c, options/options.c, options/options.h, video/filter/refqueue.c, video/filter/refqueue.h, video/filter/vf_d3d11vpp.c, video/filter/vf_vavpp.c, video/filter/vf_vdpaupp.c
There was previously no way to set the field parity when using --deinterlace or pressing d. The ffmpeg filters(bwdif, bwdif_vulkan, bwdif_cuda) already have a parity parameter so it was just a matter of passing the option through.
As for the other ones(vdpaupp, vavpp, d3d11vpp), I am still unsure when does the MP_IMGFIELD_TOP_FIRST flag get set on the mp_image that refqueue reads, if it ever gets set at all, since it seems like mp_image always assumes bottom field first? I made the parity options take precedence over the flag but the default "auto" option should work exactly the same as before. Nevertheless the logic could be simplified if this is something that's not used anymore.
Also note that out of the inbuilt hardware ones I only tested d3d11vpp but vdpaupp and vavpp should behave …
=> filters: add ---deinterlace-field-parity option

audio/decode/ad_spdif.c
=> ad_spdif: handle deprecated FF_PROFILE_* definitions

video/out/mac/common.swift, video/out/mac/metal_layer.swift, video/out/mac/window.swift, video/out/mac_common.swift, video/out/vulkan/context_mac.m
first commit works around a broken workaround: https://github.com/KhronosGroup/MoltenVK/blame/b56c152a1245a95e7d4e8d64baca8ae42e85ae6a/MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm#L274-L283
MoltenVK itself tries to work around a supposedly Metal problem that itself causes flicker, black screens or broken rendering. it sets the drawableSize to 1x1 to forcefully complete the presentation. though if 1x1 resolution frame is presented it causes a visual flicker or rather a solid coloured frame. it causes even more problems since sometimes it does not reset the drawableSize to the proper resolution and keeps rendering everything in 1x1.
work around this workaround by discarding drawableSize that are <=1 in any direction.
second commit is just some minor bugfix and optimisation.
=> mac/vulkan: workaround for MoltenVK problem that causes flicker

DOCS/man/input.rst
Some incorrect syntax is used in DOCS/man/input.rst with https://github.com/mpv-player/mpv/commit/c678033c1d60b48ae02fbbe4815869b9504a17f6 causing failure of PDF manual generation with rst2pdf. There are single rather than double back-ticks for insert-at and insert-at-play so this is fixed and a couple of typos are also corrected with this commit.
With these changes the PDF manual generation works fine once again.
=> DOCS/man/input.rst: fix incorrect syntax

.github/workflows/docs.yml
Not sure if this is particularly useful, but we might as well generate these as well. Also use the docutils wrapper since that's what the meson build does.
=> github/workflows: generate html and pdf in docs job as well

TOOLS/osxbundle/mpv.app/Contents/Info.plist
this is a somewhat weird change. i have no idea if it actually improves things or if it's just some placebo Apple marketing.
Game Mode 'documentation' lol: https://support.apple.com/en-us/105118
mpv isn't really a game and categorising our App bundle as game seems counterintuitive. though as a video player it does have some similarities, possibly needing considerably CPU and GPU resources and low presentation latencies.
the macOS Game Mode promises exactly that, it gives App the highest priority access to CPU and GPU resources and lowers usage for background tasks.
sadly the Game Mode can only be activated by categorising the App as a game and that is only possible with an App bundle and not as a command line tool.
=> osxbundle: activate Game Mode with App bundle

TOOLS/osxbundle.py
`--deep` is deprecated as of macos 13.0.
It is also not supported by alternative `codesign` implementations like
[sigtool](https://github.com/thefloweringash/sigtool).
Related: https://github.com/NixOS/nixpkgs/pull/270691
=> osxbundle: avoid running `codesign` with deprecated `--deep` argument

audio/decode/ad_spdif.c, filters/f_lavfi.c
ffmpeg recently changed this field to be const which causes our CI to fail on newer versions.
See: https://github.com/FFmpeg/FFmpeg/commit/2a68d945cd74265bb71c3d38b7a2e7f7d7e87be5
=> ad_spdif: handle const buf pointee in avio_alloc_context

filters/f_lavfi.c, filters/f_swresample.c
These options were deprecated with the addition of the channel layout API about a couple of years ago*. Unfortunately, we never saw the deprecation messages so it went unnoticed until they were completely removed with the recent major version bump. Fix this by setting in_chlayout and out_chlayout instead if we have AV_CHANNEL_LAYOUT.
Fixes #13662.
*: https://github.com/FFmpeg/FFmpeg/commit/8a5896ec1f635ccf0d726f7ba7a06649ebeebf25
=> swresample: stop using deprecated {in,out}_channel_layout options

audio/decode/ad_spdif.c
Just noticed that one old deprecated FF_PROFILE_* definition was left unaltered - fix this.
This commit changes/updates FF_PROFILE_DTS_HD_HRA to AV_PROFILE_DTS_HD_HRA.
=> ad_spdif: update deprecated FF_PROFILE_DTS_HD_HRA definition

DOCS/tech-overview.txt
There had been various refactors happened since the details here were last written. As a result, lots of them are now outdated. 
This updates them to provide the up-to-date info.
=> DOCS/tech-overview.txt: updates for refactored code

options/path.c
--no-config is equivalent to --config-dir="".
Fixes: df758880e26c ("path: don't override "cache" and "state" paths with configdir")
=> path: don't load any files if --no-config is passed

video/out/gpu/video.c
Fixes https://github.com/mpv-player/mpv/issues/8223.
=> vo_gpu: fix broken chroma plane for rotated semi-planar formats

meson.build
It's a bit inconsistent. meson.build suggests that videotoolbox-gl could be used in pair with ios-gl. But this then includes macos specific files later on.
Without this fix, 0.37 now causes _ra_hwdec_videotoolbox symbol not found when ran on hardware cause hwdec_vt is never included. 0.36 worked correctly so I guess placebo related refactor of meson.build caused this regression.
=> meson: fix ios-gl hwdec build

video/out/gpu_next/context.c, video/out/gpu_next/context.h, video/out/vo_gpu.c, video/out/vo_gpu_next.c
It seems that GLX requires us to explicitly set opts.want alpha before ra_ctx_create is called. b7fd232524bc213df91fa77ca0261ff514fad1e4 rearranged the function calls in a way made this not work. Fix this by rearranging ti again so the value is set before ra_ctx is created.
=> vo_gpu/vo_gpu_next: fix transparency in glx

video/out/wayland_common.c
Currently, Wayland is above X11 and DRM in probe order. The success of automatic probing depends on the fact that unsuitable backends would fail to initialize. For example, X11 backend (which uses Xlib) fails to initialize if DISPLAY environment variable is not set, so starting mpv in VT console will pick the DRM backend as expected, even when an X server is running in another VT.
However, libwayland-client used by the Wayland backend has the "helpful" behavior of falling back to "wayland-0" if WAYLAND_DISPLAY is not set. This breaks autoprobing if mpv is started from X server or VT console while a running Wayland compositor running in another VT (or even running as an X client) is using "wayland-0" for protocol socket name: mpv will start playing in the Wayland compsitor instead of using …
=> wayland_common: require WAYLAND_DISPLAY to be set for initialization

meson.build, osdep/mac/application.m, osdep/mac/application_objc.h, osdep/mac/events.h, osdep/mac/events.m, osdep/mac/events_objc.h, osdep/mac/input_helper.swift, osdep/mac/menu_bar.swift, osdep/mac/mpv_helper.swift, osdep/mac/remote_command_center.swift, osdep/mac/swift_bridge.h, osdep/mac/swift_extensions.swift, osdep/mac/touchbar.h, osdep/mac/touchbar.m, video/out/cocoa_cb_common.swift, video/out/mac/common.swift, video/out/mac/view.swift, video/out/mac/window.swift, video/out/mac_common.swift
this reworks key input management. one big part of the preparations to rewrite the events class into a more generic macOS platform features hub that work independent of a video output.
in further steps and with the swift conversion, functions calls will get less nested/verbose. though for now we have to live with a bit of ugliness for the sake of objective-c.
=> mac/input: move input related function into new class, cleanup and optimisations

audio/out/ao_coreaudio.c
Commit 39f7f83 changed ao_driver.reset to use AudioUnitReset instead of AudioOutputUnitStop. The problem with calling AudioOutputUnitStop was that AudioOutputUnitStart takes a significant amount of time after a stop when a wireless audio device is being used. This resulted in lagging that was noticeable to users during seeking and short pause/resume cycles. Switching to AudioUnitReset eliminated this lagging.
However with the switch to AudioUnitReset the macOS daemon coreaudiod continued to consume CPU time and did not release a powerd assertion that it created on behalf of mpv, preventing macOS from sleeping.
This commit will change ao_coreaudio.reset to call AudioOutputUnitStop after a delay if playback has not resumed. This preserves the faster restart of playback for seeking and short …
=> ao_coreaudio: stop audio unit after idle timeout

DOCS/man/options.rst, video/out/w32_common.c, video/out/wayland_common.c, video/out/x11_common.c, video/out/x11_common.h
This fixes setting window position on x11 and supports setting geometry on runtime on win32. 
Closes https://github.com/mpv-player/mpv/issues/8379.
Fixes 8e793bde78f00fbb64223db30851c6d080c4abeb.
=> runtime geometry change fixes

DOCS/man/input.rst, demux/demux_lavf.c, demux/stheader.h, player/command.c
It can be useful to know the underlying format of any entry in the track list. Only applicable to the lavf demuxer.
=> demux: add a format-name property

video/out/w32_common.c
With runtime geometry change, currently it only results in a `SetWindowPos` call to resize the window. However, `SetWindowPos` doesn't change the window maximized state, so Windows still thinks that the window is maximized even though it no longer covers the whole workspace. This results in visual glitches, and if the window is dragged afterwards it's "restored" again.
Fix this by unmaximize the window in this case, which also matches the behavior of X11 and Wayland.
Also update maximized state when leaving fullscreen. Fixes https://github.com/mpv-player/mpv/issues/10687.
=> win32: fix window maximized state after setting window size

video/out/vo_gpu_next.c
Upstream ASS specification says that all subtitles should be rendered with color primaries and transfer matching their associated video. But as expected after further discussion the decision has been made to fallback to SDR mode in case of HDR video.
See-Also: https://github.com/libass/libass/blob/649a7c2e1fc6f4188ea1a89968560715800b883d/libass/ass_types.h#L233-L237
See-Also: libass/libass#297
See-Also: mpv-player#13381
Fixes: mpv-player#13673
=> vo_gpu_next: don't render ASS subtitles at HDR colorspace

DOCS/man/options.rst, video/out/vo_gpu_next.c, video/out/vulkan/context.c
Depends on https://github.com/mpv-player/mpv/pull/13646
Fixes the issue described in https://github.com/mpv-player/mpv/issues/11862 for SDR files for non-d3d11 gpu-api. We currently don't have a smarter way to get the real on-the-wire bpc for other APIs, so this is the best that can be done.
Alternative to #13642
=> vo_gpu_next: make `dither-depth=auto` mean 8 bpc for SDR

osdep/windows_utils.c, osdep/windows_utils.h, video/out/win32/droptarget.c
This PR implements shell link resolving and enables it on dropped targets. Closes https://github.com/mpv-player/mpv/issues/8424.
mpv's behavior now matches VLC's behavior with this PR (resolves dropped shell links, but doesn't resolve shell links provided by other means, e.g. commandline). It doesn't match mpc-hc's behavior (resolves all shell links), but that requires touching platform-independent code. A separate PR will address that should such use case arises later.
=> win32: resolve dropped shell links (Windows shortcuts)

audio/filter/af_lavcac3enc.c
Hi,
I have found that this pull request:
https://github.com/mpv-player/mpv/pull/9594
did not fully solved the problem on 2 channel audio
I propose the attached pull request to solve the problem
=> af_lavcac3enc: fix memory leak on 2ch audio

misc/bstr.c, misc/bstr.h, osdep/io.c, osdep/io.h, osdep/terminal-dummy.c, osdep/terminal-win.c, osdep/terminal.h, player/main.c, test/test_utils.c, test/test_utils.h
GetConsoleMode() can be quite slow and in mpv the mode never changes, so we can just check it once.
Fixes performance when writing lots of logs to terminal.
=> win32: cache GetConsoleMode state for stdout/stderr

meson.build, osdep/threads-win32.h, osdep/timer-win32.c, osdep/timer.h, test/meson.build
`timeBeginPeriod()` and `timeEndPeriod()` internally call `NtSetTimerResolution()` to raise/reset timer resolution on win32/NT platforms.
The latter allows setting the timer resolution to less than 1 ms. Modern x86 platforms (I have tested on Ivy Bridge which is the case, but it's likely also the case on older hardware) support a minimum timer resolution of 0.5 ms, as reported by `NtQueryTimerResolution()`.
=> win32: increase hires timer resolution

common/msg.c
Make it more straightforward by always calculating top offset first instead of having two branches, that tries to calc it directly.
This also fixes missing negative check before `\033[%dA` which was in practice only problem on macOS which was handling negative values, while in fact it shouldn't.
Fixes: #13484
=> msg: simplify the line_skip calculation

DOCS/interface-changes/term-size.txt, DOCS/man/input.rst, DOCS/man/stats.rst, player/command.c, player/lua/stats.lua
Fixes scrolling for page 0 in the terminal and unifies the scrolling implementation.
Also introduces a new line shortening function for the terminal that is used by all scrollable pages now.
=> stats.lua: fixes and unification

input/input.c
https://github.com/mpv-player/mpv/commit/585d8c6856e8eaf77c518ad4679e8c66660fc440 increased max active section limit from 5 to 50 but this obviously doesn't properly fix the problem. Input still breaks if more than 25 scripts are loaded, or if some scripts define lots of input sections.
Remove the limit completely by using a dynamic array for active sections.
Fixes https://github.com/mpv-player/mpv/issues/13707.
=> input: remove max active section limit 

DOCS/interface-changes/escape-ass.txt, DOCS/man/input.rst, DOCS/man/osc.rst, player/command.c, player/lua/console.lua, player/lua/osc.lua, player/lua/stats.lua, sub/osd.h, sub/osd_libass.c
This adds a function to escape ASS tags to remove code duplication between sub/osd_libass.c, console.lua, osc.lua, stats.lua and any user script that calls mp.create_osd_overlay().
Always replacing \n with \\\\N in mangle_ass() even when it is not called by utils.escape_ass doesn't seem to cause any issue, but I made it conditional anyway to avoid changing how all OSD messages are treated unnecessarily.
Fixes #11209, fixes #11275.
=> command: add escape-ass

DOCS/interface-changes/add-input-commands.txt, DOCS/man/options.rst, options/options.c, options/options.h, player/command.c, player/command.h, player/playloop.c
Basically a simple way to perform any command/property action from the command line. This takes the exact same syntax as input.conf but not including the key naturally. Potentially useful for weird properties that don't map well to options (like ao-volume).
Another try at fixing #12353.
=> options: add --input-commands option

filters/user_filters.c, meson.build, video/out/opengl/egl_helpers.c
the knowledge that `EGL_CONTEXT_CLIENT_VERSION` is not allowed with GL comes from here: https://n9.dy.fi/meego/html/egl/eglCreateContext.html?tab=0 (and is also written in the EGL 1.4 spec)
=> Some EGL fixes

video/out/vulkan/context.c
As no drivers were ever released with the unstable extension, it's not needed anymore.
Not bumping the required headers version yet.
=> hwdec/vulkan: enable the stable AV1 extension

demux/demux_mkv.c
Most FFV1 videos seem to be encoded using FFmpeg, which uses the V_MS/VFW/FOURCC tag, but GStreamer's matroskamux uses [the V_FFV1 tag](https://www.matroska.org/technical/codec_specs.html#v_ffv1). This means that mpv could [previously not load GStreamer-muxed FFV1 videos in a .mkv](https://github.com/valadaptive/ntsc-rs/issues/49).
Fixing this seems to be as simple as adding V_FFV1 to `mkv_video_tags`--I've tested it and it plays back these videos properly now. I added it at the bottom since I can't ascertain any existing order.
[Here's a test video](https://github.com/mpv-player/mpv/files/14733876/v_ffv1.mkv.zip) (it's 1 FPS because lossless video is huge). In the current master branch it will fail to load, but with this PR it should work.
=> demux_mkv: support V_FFV1 tag
